### PR TITLE
fix #14545 windows CI docs

### LINKED ISSUE #14545: windows CI docs fails with strange errors
this PR https://github.com/timotheecour/Nim/pull/279 does nothing except a dummy modification to system.nim to trigger windows CI docs and reproduce the issue.
for posterity: logs are here https://gist.github.com/timotheecour/651249370f686efe05462f9dbf342d59

spurious errors are annoying because when there's a real error, it's hard to find in the noise of spurious errors; so we should aim for 0 errors and CI passing.

note: these errors happen sometimes but not always

### error 1
why do we have both:
* C:\Users\runneradmin\nimcache\iterators_d\runnableExamples\iterators_examples1.nim
* d:\a\Nim\Nim\lib\pure\includes\osenv.nim(138, 6)
* D:\a\Nim\Nim\lib\pure\includes\osenv.nim(138, 6) # -> **the fact that d: and D: are treated differently is already a bug in itself**

this seems a direct cause of the following error:

```
2020-06-02T03:44:50.5300553Z d:\a\Nim\Nim\lib\pure\ssl_certs.nim(70, 15) Error: ambiguous call; both os.existsEnv(key: string) [declared in d:\a\Nim\Nim\lib\pure\includes\osenv.nim(138, 6)] and os.existsEnv(key: string) [declared in D:\a\Nim\Nim\lib\pure\includes\osenv.nim(138, 6)] match for: (string)
```

other similar example:
```
and:
2020-06-02T03:44:30.1791374Z bin\nim.exe doc --errormax:3 --hint:Conf:off --hint:Path:off --hint:Processing:off -d:boot --putenv:nimversion=1.3.5 --git.commit:devel --git.url:https://github.com/nim-lang/Nim --outdir:web\upload\1.3.5 --index:on lib\std\decls.nim
2020-06-02T03:44:30.1809722Z C:\Users\runneradmin\nimcache\iterators_d\runnableExamples\iterators_examples1.nim(10, 16) Error: ambiguous call; both iterators.fields(x: T: tuple or object) [declared in D:\a\Nim\Nim\lib\system\iterators.nim(244, 10)] and iterators.fields(x: T: tuple or object) [declared in d:\a\Nim\Nim\lib\system\iterators.nim(244, 10)] match for: (tuple of (int, string))
2020-06-02T03:44:30.2707062Z [runnableExamples] failed: generated file: 'C:\Users\runneradmin\nimcache\iterators_d\runnableExamples\iterators_group0_examples.nim' group: '(rdoccmd: "", docCmd: "", code: "# autogenerated by docgen\n# source: d:\\a\\Nim\\Nim\\lib\\system\\iterators.nim\n# rdoccmd: \nimport r\"C:\\Users\\runneradmin\\nimcache\\iterators_d\\runnableExamples\\iterators_examples1.nim\"\nimport r\"C:\\Users\\runneradmin\\nimcache\\iterators_d\\runnableExamples\\iterators_examples2.nim\"\nimport r\"C:\\Users\\runneradmin\\nimcache\\iterators_d\\runnableExamples\\iterators_examples3.nim\"\nimport r\"C:\\Users\\runneradmin\\nimcache\\iterators_d\\runnableExamples\\iterators_examples4.nim\"\n", index: 0)' cmd: D:\a\Nim\Nim\bin\nim.exe c -r --warning:UnusedImport:off --path:d:\a\Nim\Nim\lib\system --nimcache:C:\Users\runneradmin\nimcache\iterators_d\runnableExamples   C:\Users\runneradmin\nimcache\iterators_d\runnableExamples\iterators_group0_examples.nim
```

## error 2: c.graph.sysTypes[tySequence] == nil
```
2020-06-01T07:00:39.3283949Z bin\nim.exe doc --hint:Conf:off --hint:Path:off --hint:Processing:off -d:boot --putenv:nimversion=1.3.5 --git.commit:devel --git.url:https://github.com/nim-lang/Nim --outdir:web\upload\1.3.5 --index:on lib\system.nim
2020-06-01T07:00:39.9891579Z fatal.nim(49)            sysFatal
2020-06-01T07:00:39.9892209Z Error: unhandled exception: semtypes.nim(2034, 12) `c.graph.sysTypes[tySequence] == nil`  [AssertionDefect]
2020-06-01T07:00:39.9892649Z 
```

- [x] error 3: test snippets give errors for manual.rst and tut1.rst
=> fixed in https://github.com/nim-lang/Nim/pull/14569
```
2020-06-02T03:42:50.2397994Z C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_111.nim(10, 5) Error: type mismatch: got <proc (x: string){.noSideEffect, gcsafe, locks: 0.}> but expected 'Callback = proc (s: string){.closure.}'

2020-06-02T03:42:51.1640609Z C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_112.nim(7, 19) Error: can have an unlisted effect: IO

2020-06-02T03:42:55.9860740Z C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_114.nim(14, 2) Error: type mismatch: got <proc (y: var int){.noSideEffect, gcsafe, locks: 0.}, int>

2020-06-02T03:43:04.8412582Z C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_118.nim(5, 12) Error: undeclared identifier: 'x'

2020-06-02T03:43:04.8418844Z C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_120.nim(11, 7) Error: redefinition of 'i'; previous declaration here: C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_120.nim(7, 7)

2020-06-02T03:43:14.4008968Z C:\Users\runneradmin\nimcache\tut1_d\tut1\tut1_snippet_115.nim(3, 6) Error: undeclared identifier: 'x'

2020-06-02T03:43:14.4017186Z C:\Users\runneradmin\nimcache\tut1_d\tut1\tut1_snippet_116.nim(3, 6) Error: undeclared identifier: 'x'

2020-06-02T03:43:18.3428215Z C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_126.nim(6, 9) Error: undeclared field: 'T' for type system.int [declared in D:\a\Nim\Nim\lib\system\basic_types.nim(2, 3)] 

2020-06-02T03:43:18.3974515Z C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_127.nim(6, 1) Error: undeclared identifier: 'unknownIdentifier'

2020-06-02T03:43:22.4043359Z C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_128.nim(8, 21) Error: attempting to call routine: 'something'

2020-06-02T03:43:22.4052786Z C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_129.nim(8, 17) Error: undeclared field: 'sequtils' 

2020-06-02T03:43:30.0369863Z C:\Users\runneradmin\nimcache\manual_d\manual\manual_snippet_135.nim(5, 11) Error: undeclared identifier: '%'
```

### Additional Information
```
devel 1.3.5 e5b64af
```
the above log actually contains a lot more errors, and that's because nim doc keeps going on errors, causing errors to snowball even though only the 1st one typically matters (the rest being consequences of 1st error)
I'm fixing this aspect in https://github.com/nim-lang/Nim/pull/14546 to make `nim doc` (and other tools) honor `--errormax`

### PR DESCRIPTION
**Pull request by timotheecour**
fix #14545 windows CI docs

turns out `expandFilename` is not good enough:
```nim
    # getFullPathName doesn't do case corrections, so we have to use this convoluted
    # way of retrieving the true filename
    for x in walkFiles(result):
      result = x
    if not existsFile(result) and not existsDir(result):
      # consider using: `raiseOSError(osLastError(), result)`
      raise newException(OSError, "file '" & result & "' does not exist")
```
maybe a future PR can fix `expandFilename` by returning proper case, eg `d:\Users\FooB` => `D:\Users\Foob`, and maybe it'd be a simple as patching `expandFilename` to return the drive uppercase, I haven't checked whether that would work; but at least this PR should be robust

## note
CI failure caused by CI failure caused by https://github.com/timotheecour/Nim/issues/167

### CODE REVIEW

File: compiler/msgs.nim [hunk 1]
```diff
@@ -66,14 +66,20 @@ when defined(nimpretty):
   proc fileSection*(conf: ConfigRef; fid: FileIndex; a, b: int): string =
     substr(conf.m.fileInfos[fid.int].fullContent, a, b)
 
+proc canonicalCase(path: string): string =
```
Comment (Araq) [inline compiler/msgs.nim]: Please make this a ``var string`` version. All usages call it with a temporary that could be mutated. No allocations then.

Comment (timotheecour) [reply compiler/msgs.nim]: > All usages call it with a temporary that could be mutated

there's a complication here which is that `canon` can be shallow depending on runtime conditions, and its original value is needed in `newFileInfo(canon...` so you don't end up with ugly paths in error messages like `/users/timothee/git_clone/nim/...` instead of original case `/Users/timothee/git_clone/nim/...`

well, you asked for it ... so I'm introducing lib/std/private/strutils2.nim to do this cleanly.

I could've obviously done things differently, and even forgo this optimization given the fact that `canonicalizePath` calls `expandFile` which in turns calls a filesystem syscall which will mostly likely dwarf any saving here.
But the reason I've added `strutils2.nim` is:
* I want to add this at some point so might as well start here
* this is a good staging ground (only private use within compiler + tooling in nim repo) so API can keep improving with real usage and without being bogged down by backward compatibility arguments given that it's private
* this is intended to grow, in particular towards https://github.com/nim-lang/RFCs/issues/191 and several other string API that will benefit from a more performant base (in particular avoiding un-necessary allocations)
* eventually the dependency can be reversed (eg std/strutils would import strutils2)
* the point is to write the ugly code once as reusable code

**Comment by Araq** [comment]
Come on... It's pretty nice stuff but it slows down compile times further. I prefer your previous fix then. (And yeah, I'm longing for IC...)

**Comment by timotheecour** [comment]
> it slows down compile times further

I care a lot about compilation times so I did some extensive testing and this is not the case.
## ./koch boot -d:release
`gtime -v ./koch boot -d:release`
* right before commit `add lib/std/private/strutils2.nim`
        User time (seconds): 192.75
        System time (seconds): 11.75
        Percent of CPU this job got: 409%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:49.97
* right after commit `add lib/std/private/strutils2.nim`
        User time (seconds): 192.30
        System time (seconds): 11.78
        Percent of CPU this job got: 402%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:50.75

(doing it twice doesn't change results beyond noise)

## `XDG_CONFIG_HOME= nim c -r testament/testament all`
* right before: 499.455 seconds
* right after: 486.211 seconds

## more generally, modules are cheap
just to settle this issue once and for all, I wrote this PR https://github.com/nim-lang/Nim/pull/14614 to benchmark compilation times in several cases, see PR for details but one takeaway is this:
**importing n=1000 small modules costs 6ms per module with --force, and 1ms per module when recompiling with no change**.

Feel free to experiment further.

This was the main motivation behind https://github.com/nim-lang/Nim/issues/9581 (megatest)

File: lib/std/private/strutils2.nim [hunk 2]
```diff
@@ -0,0 +1,55 @@
+##[
```
Comment (Araq) [inline lib/std/private/strutils2.nim]: This should be ``compiler/strutils2.nim``, ``lib/std/private`` creates bootstrapping problems and is a contradiction. ("A standard hidden library?")

File: lib/std/private/strutils2.nim [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+
+proc toLowerAscii*(a: var string) =
+  ## optimized and inplace overload of strutils.toLowerAscii
+  # refs https://github.com/timotheecour/Nim/pull/54
+  # this is 10X faster than a naive implementation using a an optimization trick
+  # that can be adapted in similar contexts. Predictable writes avoid write
+  # hazards and lead to better machine code, compared to random writes arising
+  # from: `if c.isUpperAscii: c = ...`
+  for c in mitems(a):
+    c = chr(c.ord + (if c.isUpperAscii: (ord('a') - ord('A')) else: 0))
```
Comment (Araq) [inline lib/std/private/strutils2.nim]: ``if c in {'A'..'Z'}``  and then you can remove the ``import std / strutils`` too.

**Comment by Araq** [comment]
Fine, so please address my remarks.

File: lib/std/private/strutils2.nim (hunk 3 above)
Comment (timotheecour) [reply lib/std/private/strutils2.nim]: done

File: lib/std/private/strutils2.nim (hunk 2 above)
Comment (timotheecour) [reply lib/std/private/strutils2.nim]: done but see below.

**Comment by timotheecour** [comment]
PTAL, all comments addressed.

https://github.com/nim-lang/Nim/pull/14590#discussion_r437273294

> This should be compiler/strutils2.nim, lib/std/private creates bootstrapping problems and is a contradiction. ("A standard hidden library?")

applied your suggestion for the sake of moving forward; but I don't understand why it would create a bootstrapping problem or contradiction? CI was green after all.

A purported goal of `lib/std/private/strutils2` (and a few other modules inside `lib/std/private/`) was to use `strutils2` not just in compiler but in stdlib + tools, but keeping it private from usage outside nim repo until API stabilizes to the point no breaking change will be needed, after which it can migrate out to `lib/std/` with minimal module renames and transparently for code outside nim repo.

This addresses the concern you had with `std/experimental`, since we're still battle testing it via internal usage inside nim repo, while shielding us from backward compatibility concerns.
Now that it's in `compiler/strutils2.nim`, usage outside compiler (eg `./tests/stdlib/tstrutils2.nim`) must use `import "$lib/.." / compiler/strutils2` in which seems less than ideal.

Future plans I had in mind was moving forward with https://github.com/nim-lang/RFCs/issues/191
