### PR TITLE
fix #7535(Poor error message for spawn when a procedure (without calling it))

### LINKED ISSUE #7535: Poor error message for `spawn` when a procedure (without calling it) is passed
Nim version: 0.18.0 [MacOSX: amd64]

I experimented the behaviour of `spawn` and `parallel` for a project, and I got an issue passing an anonymous procedure to `spawn`.

The following code demonstrates the expected behaviour:
```nim
proc my_proc(x: uint32) =
    echo x
proc print_parallel_ok(r: uint32) =
    for x in 0..r:
        spawn my_proc x
```
The compiler compiles the code, and running it is ok.

Otherwise, the following demonstrates the error:
```nim
proc print_parallel_nok(r: uint32) =
    for x in 0..r:
        spawn (proc (x: uint32) = echo x)
```
Here, instead of using a named procedure, I passed an anonymous procedure to `spawn`.

The error, passing an anonymous procedure to `spawn` is: `expression 'spawn proc (x: uint32) = echo [x], nimCreateFlowVar' is of type 'FlowVar[proc (x: uint32){.gcsafe, locks: 0.}]' and has to be discarded`.  
Also, if I add a discard, I get an internal compiler error.

### PR DESCRIPTION
**Pull request by ringabout**
fix #7535

follow up
- [x] improve all of the error messages: "'spawn' takes a call expression; got "(see https://github.com/nim-lang/Nim/pull/17774#discussion_r615748765)

### CODE REVIEW

File: tests/parallel/t7535.nim [hunk 1]
```diff
@@ -0,0 +1,10 @@
+discard """
+  errormsg: "'spawn' takes a call expression; got proc (x: uint32) = echo [x]"
```
Comment (ringabout) [inline tests/parallel/t7535.nim]:
```suggestion
discard """
  matrix: "--threads:on"
  errormsg: "'spawn' takes a call expression; got proc (x: uint32) = echo [x]"
```

File: compiler/semexprs.nim [hunk 2]
```diff
@@ -2284,11 +2284,16 @@ proc semMagic(c: PContext, n: PNode, s: PSym, flags: TExprFlags): PNode =
...
       localError(c.config, n.info, "compiler was built without 'spawn' support")
-      result = n
+      result = errorNode(c, n)
     else:
       result = setMs(n, s)
       for i in 1..<n.len:
         result[i] = semExpr(c, n[i])
+
+      if n.len > 1 and n[1].kind notin nkCallKinds:
+        localError(c.config, n[1].info, "'spawn' takes a call expression; got " & $n[1])
```
Comment (konsumlamm) [inline compiler/semexprs.nim]:
```suggestion
        localError(c.config, n[1].info, "'spawn' takes a call expression; got: " & $n[1])
```
Or something else, so that the expression and the message are separated.

Comment (ringabout) [reply compiler/semexprs.nim]: Yeah, I will change it , it's pre-existing(I copied the old messages)

File: compiler/semexprs.nim [hunk 3]
```diff
@@ -2284,11 +2284,16 @@ proc semMagic(c: PContext, n: PNode, s: PSym, flags: TExprFlags): PNode =
...
+        return errorNode(c, n)
```
Comment (Clyybber) [inline compiler/semexprs.nim]:
```suggestion
        return localErrorNode(c, n, n[1].info, "'spawn' takes a call expression; got " & $n[1])
```

File: compiler/semexprs.nim [hunk 4]
```diff
@@ -2284,11 +2284,16 @@ proc semMagic(c: PContext, n: PNode, s: PSym, flags: TExprFlags): PNode =
     markUsed(c, n.info, s)
     when defined(leanCompiler):
       localError(c.config, n.info, "compiler was built without 'spawn' support")
-      result = n
+      result = errorNode(c, n)
```
Comment (Clyybber) [inline compiler/semexprs.nim]: same as https://github.com/nim-lang/Nim/pull/17774/files#r615943088 here (github doesn't let me make a suggestion here)

File: compiler/semexprs.nim (hunk 3 above)
Comment (ringabout) [reply compiler/semexprs.nim]: fixed

File: compiler/semexprs.nim (hunk 4 above)
Comment (ringabout) [reply compiler/semexprs.nim]: fixed

**Review by Clyybber — APPROVED** [review]
