### PR TITLE
Fixes #5457 - StdLib base64 encodeInternal crashes with out of bound exception

### LINKED ISSUE #5457: StdLib base64 encodeInternal crashes with out of bound exception
Occurs when `newLine` is not nil or empty and string to be encoded expands to `lineLen`.

Example from the forum where the bug was [reported by Jordan](https://forum.nim-lang.org/t/2824):
```nim
import strutils, base64
echo "+".repeat(57).encode()
```

### PR DESCRIPTION
**Pull request by napalu**
StdLib base64 encodeInternal crashes with out of bound exception

### CODE REVIEW

File: lib/pure/base64.nim [hunk 1]
```diff
@@ -49,8 +49,8 @@ template encodeInternal(s: expr, lineLen: int, newLine: string): stmt {.immediat
   ## `newline` is added.
   var total = ((len(s) + 2) div 3) * 4
   var numLines = (total + lineLen - 1) div lineLen
-  if numLines > 0: inc(total, (numLines-1) * newLine.len)
-
+  if numLines > 0: inc(total, (numLines - 1) * newLine.len)
+
```
Comment (Araq) [inline lib/pure/base64.nim]: change your editor settings please, trailing whitespace here.
