### PR TITLE
fix #9437(fix `re.replace` wrong behaviour)

### LINKED ISSUE #9437: re.replace("foo", re"", "-") returns -foo, inconsistent with nre.replace
Detailed comment: https://github.com/nim-lang/Nim/issues/9315#issuecomment-429677984

/cc @skilchen 

**EDIT by @timotheecour**
```nim
import re
echo replace("foo", re"", "-")
# -foo
```

* nre returns `"-f-o-o-"`
* strutils.replace returns `"-f-o-o-"`
* Python/JS/whatever also does it this way (see https://github.com/nim-lang/Nim/pull/9280#issuecomment-428843621)
* nim-regex "-f-o-o" but pending https://github.com/nitely/nim-regex/issues/29 (which seems accepted), shall return `"-f-o-o-"`
* strutils.multiReplace currently crashes (https://github.com/nim-lang/Nim/issues/9557)
* count throws on empty string (since https://github.com/nim-lang/Nim/pull/9280)

copying over the comment from @skilchen :
-----------------

```nim
import re
echo replace("foo", re"", "-")
```
produces:
-foo
While in the common understanding of regular expressions there is an empty string in front of any string, one between every substring of length 1 and one at the end of the string.
nre.nim produces the usually expected -f-o-o-
With nre as well as in the other languages I know the following is also possible:
```nim
import nre
echo replace("foo", re"^|$", "-")
```
which produces
-foo-
as expected, but using re you get: -foo which doesn't seem correct.
```nim
import re
echo "".replacef(re"([^\d]*)(\d*)([^\w]*)", "$1 - $2 - $3")
```
still produces an empty line, which doesn't seem correct, I would expect - -. However on a string that usually should be split using this pattern, it works:
```nim
import re
echo "abc123###".replacef(re"([^\d]*)(\d*)([^\w]*)", "$1 - $2 - $3")
```
correctly produces:
abc - 123 - ###

---------------

## further discussion
* https://github.com/nim-lang/Nim/commit/8955470644972e2d1f2b029650c04505ebacca23#r30894413
@Araq said:
> There is no wrong logic here, we don't claim to be bug-compatible with other regex engines.

if we're departing from other regex engines, an option could be to throw ; but at least it'd be nice to have consistent behavior across re,nre,nim-regex

### PR DESCRIPTION
**Pull request by ringabout**
fix #9437

follow up:
<del> - [x] fix the terrible function declaration </del>

### CODE REVIEW

File: lib/impure/re.nim [hunk 1]
```diff
@@ -200,27 +200,27 @@ proc findBounds*(s: string, pattern: Regex,
   result = findBounds(cstring(s), pattern, matches, start, s.len)
 
 proc findBounds*(buf: cstring, pattern: Regex,
-                 start = 0, bufSize: int): tuple[first, last: int] =
+                 start = 0, bufSize = 0, flags = int32(0)): tuple[first, last: int] =
```
Comment (timotheecour) [inline lib/impure/re.nim]: flags is not documented, so adding this optional param would need a doc comment mention.
But exposing a raw int32 param representing a bitfield is not very nim-esque, and instead should be exposed via an enum. But for this PR it doesn't seem needed to add this optional param in the public API; how about add a private findBounds overload with this extra flags param, so that we can decide in future work how to expose is as public API?

Comment (ringabout) [reply lib/impure/re.nim]: ok

**Comment by dom96** [comment]
https://github.com/nim-lang/Nim/pull/17547#issuecomment-808907897 :)

File: lib/impure/re.nim (hunk 1 above)
Comment (ringabout) [reply lib/impure/re.nim]: fixed

**Comment by kaushalmodi** [comment]
It's passing all the tests, so it's good to merge?

**Comment by ringabout** [comment]
It needs some reviews I think.
