### PR TITLE
fixes #19401; fixes #19402; rework Forward declaration and finalizer for ORC

### LINKED ISSUE #19401: Internal error on ARC/ORC when using forward declaration of finalizer proc
### Example
compile with --gc:arc
```nim

type Foo = ref object
proc delete(self: Foo) 
proc newFoo: Foo = new(result, delete)
proc delete(self: Foo) = echo("delete Foo")

if isMainModule:
  proc test() = discard newFoo()
  test()
```

### Current Output
```
Error: internal error: expr: proc not init delete
```

### Expected Output
```
delete foo
```

### Additional Information
Tested nim version 1.4.2 up to devel (15e3813d96ad5646476b629f3a20ece89dff064d)

If using `type Foo = ref object of RootObj` the problem is different: code compiles but silently skips finalizer call. I'm opening an independent issue for that.

### LINKED ISSUE #19402: Finalizer not called for type `ref object of RootObj` when using ARC/ORC + Forward declaration
### Example
compile with --gc:arc
```nim
type Foo = ref object of RootObj
proc delete(self: Foo) 
proc newFoo: Foo = new(result, delete)
proc delete(self: Foo) = echo("delete Foo")

if isMainModule:
  proc test() = discard newFoo()
  test()
```

### Current Output
```
none
```

### Expected Output
```
delete foo
```

### Additional Information
Tested nim version 1.4.2 up to devel (15e3813d96ad5646476b629f3a20ece89dff064d)

It works with --gc:refc, it gives a different problem if `type Foo = ref object` (see https://github.com/nim-lang/Nim/issues/19401)

### PR DESCRIPTION
**Pull request by ringabout**
fixes #19401
fixes #19402

It is a draft because It's the solution I can think of for now. I'm going to examine it tomorrow. At least it works for #19401 and  #19402 locally.

### CODE REVIEW

**Comment by ringabout** [comment]
It seems that at the time of `magicsAfterOverloadResolution` is called, the finalizer function is not transformed completely. By adding a wrapper around the finalizer function, we can ignore the incomplete function body and delay the analysis to later phases. Finally, when the finalizer function gets transformed properly, and the wrapper function will call it. So we don't need to touch the internal symbols of the finalizer function.

For instance
```nim
type
  Object = object
  Ref = ref Object

proc delete(x: Ref)
```
It generates a `deleteFinalizerWrapper` function:
```nim
proc delete(x: Ref)
proc deleteFinalizerWrapper(x: var Object) =
  delete(x)
```
After some refactorings, it can solve https://github.com/nim-lang/Nim/issues/19231 too

File: compiler/semmagic.nim [hunk 1]
```diff
@@ -535,7 +535,28 @@ proc magicsAfterOverloadResolution(c: PContext, n: PNode,
             getAttachedOp(c.graph, t, attachedDestructor).owner == fin:
           discard "already turned this one into a finalizer"
         else:
-          bindTypeHook(c, turnFinalizerIntoDestructor(c, fin, n.info), n, attachedDestructor)
+          if sfForward in fin.flags:
```
Comment (Araq) [inline compiler/semmagic.nim]: Move the full `of mNewFinalize` logic into its own proc please.

Comment (ringabout) [reply compiler/semmagic.nim]: done
