### PR TITLE
fix #19678 Broken behavior with string ranges in case labels

### LINKED ISSUE #19678: Broken behavior with string ranges in case labels
Using ranges like `"0" .. "9"` inside case labels is completely borked and sometimes even crashes the C code generator.

### Example
```nim
case "5":
    of "0" .. "9":
        echo "Hello!"  # Does not run
    else:
        discard

echo "5" in "0" .. "9"  # This does and correctly prints "true"
```

### Current Output

```
true
```

### Expected Output
```
Hello!
true
```

### Possible Solution

Minimal investigation by @Yardanico suggests this may be due to how the compiler handles string ranges in case labels, which apparently does not use the regular `..` operator. No solution is immediately obvious other than, well, fixing string ranges?

### Additional Information
The issue originally arised as a C codegen crash with the following error message: 
```
Error: unhandled exception: ccgstmts.nim(836, 11) `b[i].kind != nkRange  [AssertionDefect]`
```
```
$ nim -v
Nim Compiler Version 1.6.2 [Linux: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 9084d9bc02bcd983b81a4c76a05f27b9ce2707dd
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by bung87**
fix #19678

### CODE REVIEW

File: compiler/semtypes.nim [hunk 1]
```diff
@@ -554,6 +554,8 @@ proc semBranchRange(c: PContext, t, a, b: PNode, covered: var Int128): PNode =
   checkMinSonsLen(t, 1, c.config)
   let ac = semConstExpr(c, a)
   let bc = semConstExpr(c, b)
+  if ac.kind == nkStrLit or bc.kind == nkStrLit:
```
Comment (Araq) [inline compiler/semtypes.nim]:
```suggestion
  if ac.kind in {nkStrLit..nkTripleStrLit} or bc.kind in {nkStrLit..nkTripleStrLit}:
```
