### PR TITLE
don't warn/error symbols in semGenericStmt/templates

### LINKED ISSUE #11805: `push warning[Deprecated]: off` doesn't work with templates
2 bugs:
* `push warning[Deprecated]: off` doesn't work with templates; 
* the warnings get duplicated at each template call stack and need to be suppressed an equivalent number of times

### Example
```nim
# lib.nim:
  proc foo2*() {.deprecated: "use foo2 instead".} = echo "ok1"

# main.nim:
  import ./lib
  template myfun*() =
    {.push warning[Deprecated]: off.}
    foo2()
    {.pop.}
  myfun()
```

### Current Output
```
Warning: use foo2 instead; foo2 is deprecated [Deprecated]
```

### Expected Output
no warning

Furthermore, if you remove the push/pop, you'll get 2 warnings instead of 1.

with double push it finally suppresses the warning:
```nim
  import ./lib
  {.push warning[Deprecated]: off.}
  template myfun*() =
    {.push warning[Deprecated]: off.}
    foo2()
    {.pop.}
  {.pop.}
  myfun()
```
but this isn't practical in more complex settings

### Additional Information
* Your Nim version (output of `nim -v`).
latest devel f50e4500c257e3d57654f5230db75042da233d24
* in my use case, I needed to suppress `callsite` deprecation warnings; `callsite` was needed for my use case (`args: varargs[untyped]` doesn't contain enough information)

### LINKED ISSUE #15650: {.deprecated.} false positive within template/generics
### Example
```nim
proc bar() {.deprecated.} = discard

template foo() =
  when false:
    bar()
  else:
    discard

foo()
```

### Current Output
```
test.nim(5, 5) Warning: bar is deprecated [Deprecated]
```

### Expected Output
No warnings should be shown.

### Additional Information
- The same bug manifests if `foo` is a generic proc

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-10-19
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: f20e485827df6df97b8396558b10d7c59ca1b7dc
active boot switches: -d:release -d:nimUseLinenoise -d:nativeStackTrace
```

### LINKED ISSUE #24903: `when false` block body inside `proc m(_: int | int)` invokes pragmas
### Nim Version

```
Nim Compiler Version 2.2.4 [Linux: amd64]
Compiled at 2025-04-22
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: f7145dd26efeeeb6eeae6fff649db244d81b212d
active boot switches: -d:release
```

```
Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2025-04-22
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: d966ee3fc3874f63b4e32a7edc7566982bb570ce
active boot switches: -d:release
```

### Description

```nim
template r(_: untyped) =
  static: doAssert false
proc y() {.r.} = discard
proc m(_: int | int) =
  when false: y()
```
or
```nim
proc y() {.deprecated.} = discard
proc m(_: int | int) =
  when false: y()
```
or
```nim
proc y() {.error.} = discard
proc m(_: int | int) =
  when false: y()
```

### Current Output

```text
With the macro-style pragma:

stack trace: (most recent call last)
/tmp/c.nim(2, 11)        c
/tmp/nim23/lib/std/assertions.nim(41, 14) failedAssertImpl
/tmp/nim23/lib/std/assertions.nim(36, 13) raiseAssert
/tmp/nim23/lib/system/fatal.nim(53, 5) sysFatal
/tmp/c.nim(3, 12) template/generic instantiation of `r` from here
/tmp/nim23/lib/system/fatal.nim(53, 5) Error: unhandled exception: /tmp/c.nim(2, 11) `false`  [AssertionDefect]

With deprecated:
/tmp/c.nim(3, 15) Warning: y is deprecated [Deprecated]
/tmp/c.nim(2, 6) Hint: 'm' is declared but not used [XDeclaredButNotUsed]
H

With error:
/tmp/c.nim(3, 15) Error: usage of 'y' is an {.error.} defined at /tmp/c.nim(1, 1)
```

### Expected Output

```text
None, it's in a when false block but still lexically/syntactically valid.
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### LINKED ISSUE #24905: `{.push warning[Deprecated]: off.}` has no apparent effect within generic `proc`
### Nim Version

```
Nim Compiler Version 2.2.4 [Linux: amd64]
Compiled at 2025-04-23
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: f7145dd26efeeeb6eeae6fff649db244d81b212d
active boot switches: -d:release
```

```
Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2025-04-23
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: d966ee3fc3874f63b4e32a7edc7566982bb570ce
active boot switches: -d:release
```

### Description

```nim
proc y() {.deprecated.} = discard
proc v(_: int | int) =
  {.push warning[Deprecated]: off.}
  y()
  {.pop.}
```

### Current Output

```text
/tmp/e.nim(4, 3) Warning: y is deprecated [Deprecated]
/tmp/e.nim(2, 6) Hint: 'v' is declared but not used [XDeclaredButNotUsed]
```

### Expected Output

```text
/tmp/e.nim(2, 6) Hint: 'v' is declared but not used [XDeclaredButNotUsed]
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #24905
fixes #24903
fixes https://github.com/nim-lang/Nim/issues/11805
fixes https://github.com/nim-lang/Nim/issues/15650

In the first phase of generic checking, we cannot warn/error symbols because they can belong a false branch of `when` or there is a `push/pop` options using open symbols. So we cannot decide whether to warn/error or not

### CODE REVIEW

File: compiler/semtempl.nim [hunk 1]
```diff
@@ -72,7 +72,7 @@ proc symChoice(c: PContext, n: PNode, s: PSym, r: TSymChoiceRule;
         incl(s.flags, sfUsed)
         markOwnerModuleAsUsed(c, s)
       else:
-        markUsed(c, info, s)
+        markUsed(c, info, s, inGenerics = inGenerics)
```
Comment (metagn) [inline compiler/semtempl.nim]: Instead of modifying `markUsed`, just triggering the `if` branch above (i.e. `if isField or inGenerics:` rather than `if isField:`) should be enough.

Also this should apply to templates as well as generics. Another option might be to make the top `if` branch the default behavior for `symChoice` and call `markUsed` manually when the produced node is an `nkSym`. The only place where this isn't already done and isn't in generics/templates seems to be `semexprs.semSymGenericInstantiation`.

Comment (ringabout) [reply compiler/semtempl.nim]: Shouldn't we check style and suggestSym though?
```nim
  when defined(nimsuggest):
    suggestSym(c.graph, info, s, c.graph.usageSym, false)
  if checkStyle:
    styleCheckUse(c, info, s)
```

Comment (metagn) [reply compiler/semtempl.nim]: It would be good to detect it early but then the `when false` case would still be a problem, especially with `--styleCheck:error`. Depends whichever behavior is less annoying.
