### PR TITLE
Fix #15909

### LINKED ISSUE #15909: Compiler crash using if as an expression with a noreturn branch
The compiler crashes with `SIGSEGV: Illegal storage access. (Attempt to read from nil?)` when attempting to compile the following source with `--gc:arc`, `--gc:orc` or `--newruntime`:

```nim
proc f1() {.noreturn.} = raise newException(CatchableError, "")

proc f2(): int = 5

proc f3(): int =
  let x = if (let y = f2(); y != 0):
    y
  else:
    f1()
  x * 2

discard f3()
```

### Additional Information

The version I'm using:

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-11-09
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 49f68122e658ba7bcc13340fe157e276b4033a90
active boot switches: -d:release
```

The compiler built in debug mode shows the following stack trace:

```
....Traceback (most recent call last)   
/storage/projects/Nim/compiler/nim.nim(119) nim
/storage/projects/Nim/compiler/nim.nim(84) handleCmdLine
/storage/projects/Nim/compiler/main.nim(240) mainCommand
/storage/projects/Nim/compiler/main.nim(205) compileToBackend     
/storage/projects/Nim/compiler/main.nim(86) commandCompileToC
/storage/projects/Nim/compiler/modules.nim(163) compileProject
/storage/projects/Nim/compiler/modules.nim(91) compileModule
/storage/projects/Nim/compiler/passes.nim(196) processModule
/storage/projects/Nim/compiler/passes.nim(73) processTopLevelStmt
/storage/projects/Nim/compiler/cgen.nim(1931) myProcess
/storage/projects/Nim/compiler/cgen.nim(984) genProcBody
/storage/projects/Nim/compiler/ccgstmts.nim(1581) genStmts
/storage/projects/Nim/compiler/ccgexprs.nim(2769) expr
/storage/projects/Nim/compiler/ccgexprs.nim(2553) genStmtList
/storage/projects/Nim/compiler/ccgstmts.nim(1581) genStmts
/storage/projects/Nim/compiler/ccgexprs.nim(2810) expr
/storage/projects/Nim/compiler/cgen.nim(624) initLocExprSingleUse
/storage/projects/Nim/compiler/ccgexprs.nim(2739) expr
/storage/projects/Nim/compiler/ccgcalls.nim(781) genCall
/storage/projects/Nim/compiler/ccgcalls.nim(778) genAsgnCall
/storage/projects/Nim/compiler/ccgcalls.nim(377) genPrefixCall
/storage/projects/Nim/compiler/cgen.nim(611) initLocExpr
/storage/projects/Nim/compiler/ccgexprs.nim(2663) expr
/storage/projects/Nim/compiler/cgen.nim(1235) genProc
/storage/projects/Nim/compiler/cgen.nim(1177) genProcNoForward
/storage/projects/Nim/compiler/cgen.nim(1001) genProcAux
/storage/projects/Nim/compiler/injectdestructors.nim(1023) injectDestructorCalls
/storage/projects/Nim/compiler/varpartitions.nim(895) computeCursors
/storage/projects/Nim/compiler/varpartitions.nim(840) computeGraphPartitions
/storage/projects/Nim/compiler/varpartitions.nim(660) traverse
/storage/projects/Nim/compiler/varpartitions.nim(748) traverse
/storage/projects/Nim/compiler/varpartitions.nim(656) traverse
/storage/projects/Nim/compiler/varpartitions.nim(601) deps
/storage/projects/Nim/compiler/varpartitions.nim(412) destMightOwn
/storage/projects/Nim/compiler/ast.nim(1885) destMightOwn
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### PR DESCRIPTION
**Pull request by Fanael**

### CODE REVIEW

File: compiler/varpartitions.nim [hunk 1]
```diff
@@ -457,11 +457,11 @@ proc destMightOwn(c: var Partitions; dest: var VarIndex; n: PNode) =
     destMightOwn(c, dest, n[0])
 
   of nkCallKinds:
-    if hasDestructor(n.typ):
```
Comment (ringabout) [inline compiler/varpartitions.nim]: There is no need to check nil twice IMO.

```nim
  if n.typ != nil:
    if hasDestructor(n.typ):
      # calls do construct, what we construct must be destroyed,
      # so dest cannot be a cursor:
      dest.flags.incl ownsData
    elif n.typ.kind in {tyLent, tyVar}:
      # we know the result is derived from the first argument:
      var roots: seq[PSym]
      allRoots(n[1], roots)
      for r in roots:
        connect(c, dest.sym, r, n[1].info)
    else:
       ....
```

Comment (Fanael) [reply compiler/varpartitions.nim]: Then you need additional logic to make sure that both `nil` types and types that don't match either condition reach the following `else`. This may actually not matter for `noreturn` procs, but I'm not certain, so I left that bit unchanged.

**Comment by ringabout** [comment]
Please also add a testcase to else branch and better to run tests to check its result:

```nim
proc f1() {.noreturn.} = raise newException(CatchableError, "")

proc f2(): int = 5

proc f3(): int =
  let x = if (let y = f2(); y == 0):
    y
  else:
    f1()
  x * 2

doAssertRaises(CatchableError):
  f3()
```

And I don't think this should pass the tests:
```nim
proc f1() {.noreturn.} =
  discard

proc f2(): int = 5

proc f3(): int =
  let x = if (let y = f2(); y == 0):
    y
  else:
    f1()
  x * 2

echo f3()
```
IMO we should disallow this.

**Comment by Fanael** [comment]
I've further simplified the testcase and made it executable.

**Comment by Fanael** [comment]
Implemented @cooldome's suggested fix.
