### PR TITLE
fix #14698 nkRecWhen caused internalAssert in semConstructFields when generic type not mentioned in fields

### LINKED ISSUE #14698: `nkRecWhen` causes internalAssert in semConstructFields
`nkRecWhen` causes internalAssert in semConstructFields
### Example
```nim
when true: # D20200616T211751:here
  type Foo[T] = ref object
    x1: int
    when false: discard
  let t = Foo[float](x1: 1)
```

### Current Output
Error: internal error: /Users/timothee/git_clone/nim/Nim_devel/compiler/semobjconstr.nim(324, 20)

### Expected Output
```
works
```

### Additional Information
found while working on https://github.com/nim-lang/Nim/pull/14694
devel ff93302f69c724bc03d7e0529fb0b9b6bfa0b36e 1.3.5

the bug disappears if we change `ref object` to `object`, or make `Foo` not generic
EDIT: bug also disappears with this:
```nim
when true:
  type Foo[T] = object
    x1: int
    when false: discard
  type PFoo[T] = ref Foo[T]
  let t = PFoo[float](x1: 1)
```

EDIT: happens when `T` not mentioned in fields

### PR DESCRIPTION
**Pull request by timotheecour**
fix #14698

### CODE REVIEW

File: compiler/semtypinst.nim [hunk 1]
```diff
@@ -630,7 +630,10 @@ proc replaceTypeVarsTAux(cl: var TReplTypeVars, t: PType): PType =
       result = t
 
       # Slow path, we have some work to do
-      if result.n != nil and t.kind == tyObject:
```
Comment (Araq) [inline compiler/semtypinst.nim:633]: I don't understand this patch. First of all, if ``t.kind == tyRef`` you cannot assume that the child is an object.

Comment (timotheecour) [reply compiler/semtypinst.nim:633]: > First of all, if t.kind == tyRef you cannot assume that the child is an object.

fixed

> I don't understand this patch

The code path for ref vs obj is very similar  before reaching this point but diverges here; since only `tyObject` was handled but not `tyRef`, it led to a bug.

This kind of bug is tricky to fix because the effect of the bug happens at a very different place from the source of the bug; this could be improved by better debugging facilities such as a tracing mechanism; `dtrace` and a custom code instrumentation (analog to `nimFrame`) would help for this kind of bugs, where 2 traces would be diffed to find the diverging point(s)

Comment (Araq) [reply compiler/semtypinst.nim:633]: We alias ``result`` to ``t``. We know ``t.kind == tyRef`` so we set ``result.n`` for ``result.kind == tyRef``. But a ref type has no ``n`` field. This patch cannot be correct.

Comment (Araq) [reply compiler/semtypinst.nim:633]: But this works too:

```nim

      if t.kind == tyRef and t.len > 0 and t[0].kind == tyObject and t[0].n != nil:
        discard replaceObjBranches(cl, t[0].n)

```

File: compiler/semtypinst.nim [hunk 2]
```diff
@@ -630,7 +630,10 @@ proc replaceTypeVarsTAux(cl: var TReplTypeVars, t: PType): PType =
...
+      if t.kind == tyRef and t.len > 0 and t[0].kind == tyObject and t[0].n != nil:
+        result.n = replaceObjBranches(cl, t[0].n)
```
Comment (Araq) [inline compiler/semtypinst.nim]:
```suggestion
        discard replaceObjBranches(cl, t[0].n)
```
