### PR TITLE
fix #14475; unittest.require now works with `nim c`; require and check now works with -d:nodejs

### LINKED ISSUE #14475: unittest require quits program with an exit code of 0
uinittest `require` does not always quit the test program with an exit code that indicates an error.
This makes it obviously unusable in automated testing.

### Example
```nim
import unittest

suite "Test":
  test "test require":
    require false
```

### Current Output
```
$ nim c -r req.nim; echo $?
[Suite] Test
    /home/deme/repos/nim-tests/req.nim(5, 12): Check failed: false
0

```

### Expected Output
```
$ nim c -r req.nim; echo $?
[Suite] Test
    /home/deme/repos/nim-tests/req.nim(5, 12): Check failed: false
Error: execution of an external program failed: '... '
1

```

### Additional Information

* Even with an earlier `check` that fails it will still give error code of 0.
* Noticed it does work when require is not in a test block:
```nim
import unittest

suite "Test":
  require false
```
* Was checking the code quickly and noticed that it uses the `abortOnError` internally. Did the same test with `abortOnError=true` and `check` and it has the same problem.

```
$ nim -v
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf
# and
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-27
Copyright (c) 2006-2020 by Andreas Rumpf
```

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #14475: unittest.require now works
* make unittest work with -d:nodejs (which is a related but different issue)

that bug was pretty bad, and in fact fixing it reveals 2 test failures:
* https://github.com/inim-repl/INim/issues/89
* https://github.com/Nycto/DelaunayNim/issues/3

## CI failure unrelated
* https://github.com/nim-lang/Nim/issues/14685

### CODE REVIEW

File: lib/system.nim [hunk 1]
```diff
@@ -1127,12 +1127,9 @@ const
     ## is the value that should be passed to `quit <#quit,int>`_ to indicate
     ## failure.
 
-when defined(js) and defined(nodejs) and not defined(nimscript):
-  var programResult* {.importc: "process.exitCode".}: int
-  programResult = 0
```
Comment (Clyybber) [inline lib/system.nim:1132]: Is this the bugfix? Why didn't this work?

Comment (timotheecour) [reply lib/system.nim:1132]: it's one of the bugfixes; before PR, `programResult = 1` was a noop with `nim js -d:nodejs`

Comment (Clyybber) [reply lib/system.nim:1132]: Why did it not work with the importc way though?

Comment (timotheecour) [reply lib/system.nim:1132]: probably because exitCode is a special variable, eg:
```nim
  {.emit:"""
  function bar0(){
    console.log("exitCode", process.exitCode);
    process.exitCode = 1;
    console.log("exitCode", process.exitCode);
  }
  """.}

  proc bar0(){.importc:"bar0".}

  proc main()=
    bar0()
  main()
```

this prints:
```
exitCode undefined
exitCode 1
```
instead of:
```
exitCode 0
exitCode 1
```

**Comment by Nycto** [comment]
I believe https://github.com/Nycto/DelaunayNim/issues/3 has been fixed -- please give it a test to confirm

**Comment by timotheecour** [comment]
> I believe Nycto/DelaunayNim#3 has been fixed -- please give it a test to confirm

done

**Comment by timotheecour** [comment]
@araq any other comments on this? before this PR unittest silently ignores failures
