### PR TITLE
isLastRead regression fix

### LINKED ISSUE #10462: regression: isLastRead doesn't work for variables declared and used in cycles
The following code fails to compile:
```nim
proc test1: MyCopyableObject =
  for i in 0..<2:
    var myseq = newNonCopyableObject()
    result = myseq

discard test1
```

Compiler complains that last line in `test1` is not a last read of `myseq` variable and another read is located at the same line ;)))

I will make a fix.

### PR DESCRIPTION
**Pull request by cooldome**
I have also noticed is that new `isLastRead` can crash with integer overflow because `fork` did `variantA+1` without checking if `variant(A) == high(int)` which does happen due to `goto high(int)` instructions.

Fixes #10462

### CODE REVIEW

File: compiler/destroyer.nim [hunk 1]
```diff
@@ -150,14 +150,16 @@ proc isLastRead(s: PSym; c: var Con; pc, comesFrom: int): int =
       pc = pc + c.g[pc].dest
     of fork:
       # every branch must lead to the last read of the location:
-      let variantA = isLastRead(s, c, pc+1, pc)
+      var variantA = isLastRead(s, c, pc+1, pc)
       if variantA < 0: return -1
       let variantB = isLastRead(s, c, pc + c.g[pc].dest, pc)
       if variantB < 0: return -1
-      pc = variantA+1
```
Comment (cooldome) [inline compiler/destroyer.nim]: this line is the reason for integer overflows

File: compiler/destroyer.nim [hunk 2]
```diff
@@ -150,14 +150,16 @@ proc isLastRead(s: PSym; c: var Con; pc, comesFrom: int): int =
...
+      elif variantA == high(int): 
+        variantA = variantB
+      pc = variantA
     of InstrKind.join:
       let dest = pc + c.g[pc].dest
-      if dest == comesFrom: return pc
+      if dest == comesFrom: return pc + 1
```
Comment (cooldome) [inline compiler/destroyer.nim]: I am now adding +1 here such that fork does not have to do it, avoid integer overflows

File: compiler/dfa.nim [hunk 3]
```diff
@@ -639,6 +640,8 @@ proc gen(c: var Con; n: PNode) =
         genMagic(c, n, s.magic)
       else:
         genCall(c, n)
+      if sfNoReturn in n.sons[0].sym.flags:
```
Comment (cooldome) [inline compiler/dfa.nim]: sfNoReturn is better indicator for noReturn then `mExit`

Comment (Araq) [reply compiler/dfa.nim]: Ok, but in the longer run, if we depend on 'sfNoReturn' we should also check that ``.noReturn`` procs do not lie about this attribute.

File: compiler/destroyer.nim [hunk 4]
```diff
@@ -150,14 +150,16 @@ proc isLastRead(s: PSym; c: var Con; pc, comesFrom: int): int =
...
       # every branch must lead to the last read of the location:
-      let variantA = isLastRead(s, c, pc+1, pc)
+      var variantA = isLastRead(s, c, pc+1, pc)
       if variantA < 0: return -1
       let variantB = isLastRead(s, c, pc + c.g[pc].dest, pc)
       if variantB < 0: return -1
-      pc = variantA+1
+      elif variantA == high(int): 
+        variantA = variantB
+      pc = variantA
```
[the remark this answers is not in the document]
Comment (cooldome) [reply compiler/destroyer.nim]: I have added it, because test https://github.com/nim-lang/Nim/blob/devel/tests/destructor/tprevent_assign2.nim fails otherwise. I will have a look in my details why it is happening.

I don't understand how codegen can be involved, could you please explain?

**Comment by cooldome** [comment]
I had a look more into the issue. IMO, taking `pc` of `variantB` on `fork` when `variantA` is a dead end is the best possible option given current structure of control flow graph. Control flow graph will need a lot of work otherwise.

I suggest accepting this PR, so it will unblock other destructor related work. It is an improvement to current state of the world anyway. While we take extra time to rethink control flow graph structure and interpretation.
