### PR TITLE
Fixes Naive virtual crash the compiler fixes #22269

### LINKED ISSUE #22269: Naive virtual crash the compiler
### Description

I believe it was introduced in https://github.com/nim-lang/Nim/pull/21979

```nim

type
  Foo  = object
proc naiveMember(x: Foo): int {. virtual .} = 2

let foo = Foo()
echo naiveMember(foo)

```

Fails by crashing the compiler

### Nim Version

devel

### Current Output

```text
Crash compiler
```

### Expected Output

```text
2
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jmgomez**
Fixes Naive virtual crash the compiler fixes #22269

### CODE REVIEW

**Comment by jmgomez** [comment]
Notice CI passes but there is a test that hangs

File: compiler/ccgtypes.nim [hunk 1]
```diff
@@ -774,7 +774,7 @@ proc getRecordDesc(m: BModule; typ: PType, name: Rope,
     result = structOrUnion & " " & name
     result.add(getRecordDescAux(m, typ, name, baseType, check, hasField))
     let desc = getRecordFields(m, typ, check)
-    if not hasField:
+    if not hasField and m.g.graph.memberProcsPerType.len == 0:
```
Comment (Araq) [inline compiler/ccgtypes.nim]: What? Why does that matter? That is not even a type specific test!

Comment (jmgomez) [reply compiler/ccgtypes.nim]: wdym? To switch the test against a proc flag? or are you asking why is it necessary to test there?

Comment (Araq) [reply compiler/ccgtypes.nim]: Just explain the reasoning behind this logic here please.

Comment (jmgomez) [reply compiler/ccgtypes.nim]: Before this regression, the code looked like:
```nim
 if desc == "" and not hasField:
      result.addf("char dummy;$n", [])

```
By removing `desc` as a test by itself (hence my question on internals) broke it because `constructor` and `virtual` does write in `desc`

Comment (Araq) [reply compiler/ccgtypes.nim]: I still don't get it, there is nothing type specific about the test `m.g.graph.memberProcsPerType.len == 0` which means as soon as memberProcsPerType contains something the code generation for every type would be affected.

Comment (jmgomez) [reply compiler/ccgtypes.nim]: Apologies, dont know what I was thinking :/
