### PR TITLE
fix #15005; [ARC] Global variable declared in a block is destroyed too…

### LINKED ISSUE #15005: [ARC] Global variable declared in a block is destroyed too early
Following code works well before the update: **An optimizer for ARC (#14962)**.
Compiling with --gc:arc.

### Example
```nim
import wNim/[wApp, wFrame, wButton]

let app = App()
let frame = Frame()
let button = Button(frame)

frame.wEvent_Size do ():
  frame.autolayout """
    HV:|[button]|
  """

frame.show()
frame.center()
app.mainLoop()
```

### Current Output
```
Traceback (most recent call last)
O:\nim\wnim\release\test3.nim(14) test3
O:\nim\wnim\release\wNim\private\wApp.nim(304) mainLoop
O:\nim\wnim\release\wNim\private\wApp.nim(296) messageLoop
O:\nim\wnim\release\wNim\private\wWindow.nim(2262) wWndProc
O:\nim\wnim\release\wNim\private\wWindow.nim(2262) wWndProc
O:\nim\wnim\release\wNim\private\wWindow.nim(2262) wWndProc
O:\nim\wnim\release\wNim\private\wWindow.nim(2250) wWndProc
O:\nim\wnim\release\wNim\private\wWindow.nim(1289) processMessage
O:\nim\wnim\release\wNim\private\wWindow.nim(1283) processMessage
O:\nim\wnim\release\wNim\private\wWindow.nim(1240) processEvent
O:\nim\wnim\release\wNim\private\wWindow.nim(1222) callHandler
O:\nim\wnim\release\wNim\private\wWindow.nim(1971) wWindow_DoSize
O:\nim\wnim\release\wNim\private\wWindow.nim(1297) processMessage
O:\nim\wnim\release\wNim\private\wWindow.nim(1289) processMessage
O:\nim\wnim\release\wNim\private\wWindow.nim(1283) processMessage
O:\nim\wnim\release\wNim\private\wWindow.nim(1252) processEvent
O:\nim\wnim\release\wNim\private\wWindow.nim(1226) callHandler
O:\nim\wnim\release\wNim\private\wResizable.nim(234) :anonymous
O:\nim\wnim\release\wNim\private\wResizer.nim(92) resolve
O:\nim\wnim\release\wNim\private\kiwi\solver.nim(273) updateVariables
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

Thanks to @Yardanico, the simplified code is
```nim
type
  Resizer = ref object
    data: string

proc layout() =
  block:
    var resizer {.global.}: Resizer
    if resizer == nil:
      resizer = Resizer(data: "hi")

    discard resizer.data == "hi"

layout()
layout()
```

```
$ nim -v
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-07-17
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 6b607413e90111f74dd77c1fa31ba5f183f72bdf
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by bung87**
… early  

fix #15005. 

now expand as below.
```
--expandArc: test

var
  b15005
  a15005`gensym0
var alreadyExecuted`gensym1 = false
if not alreadyExecuted`gensym1:
  alreadyExecuted`gensym1 = true
  `=sink`(a15005`gensym0, T(data: "hi"))
`=copy`(b15005, a15005`gensym0)
const
  loc`gensym3 = (filename: "t15005.nim", line: 15, column: 2)
  ploc`gensym3 = "t15005.nim(15, 3)"
bind instantiationInfo
mixin failedAssertImpl
{.line: (filename: "t15005.nim", line: 15, column: 2).}:
  if not (b15005.data == "hi"):
    failedAssertImpl("t15005.nim(15, 3) `b15005.data == \"hi\"` ")
`=destroy`(b15005)
-- end of expandArc ------------------------
```

### CODE REVIEW

File: compiler/injectdestructors.nim [hunk 1]
```diff
@@ -1153,7 +1153,8 @@ proc moveOrCopy(dest, ri: PNode; c: var Con; s: var Scope, flags: set[MoveOrCopy
         let snk = c.genSink(s, dest, ri, flags)
         result = newTree(nkStmtList, snk, c.genWasMoved(ri))
       elif ri.sym.kind != skParam and ri.sym.owner == c.owner and
-          isLastRead(ri, c, s) and canBeMoved(c, dest.typ) and not isCursor(ri):
+          isLastRead(ri, c, s) and canBeMoved(c, dest.typ) and not isCursor(ri) and
+          {sfGlobal, sfPure} <= ri.sym.flags == false:
```
Comment (Araq) [inline compiler/injectdestructors.nim:1157]:
```suggestion
          {sfGlobal, sfPure} * ri.sym.flags == {}:
```

Comment (bung87) [reply compiler/injectdestructors.nim:1157]: it's for "not a subset of ri.sym.flags", I know the code too long, I have to revisit my old patch that mis use `*`
see https://play.nim-lang.org/#ix=4Cu6, maybe we have to make a sugar like `notin` or combine {sfGlobal, sfPure} into an new symbol flag.

Comment (ringabout) [reply compiler/injectdestructors.nim:1157]: Well, you are free to use `ri.sym.flags < {sfGlobal, sfPure}` or `{sfGlobal, sfPure} * ri.sym.flags != {sfGlobal, sfPure}:`.

Comment (bung87) [reply compiler/injectdestructors.nim:1157]: the last one looks ugly

Comment (bung87) [reply compiler/injectdestructors.nim:1157]:
```nim
type E = enum
  a = 1
  b = 2
  c = 3
  e = 4

echo {a,b,c} < {c, e} # false
```
likely we need sugar operator.

Comment (Araq) [reply compiler/injectdestructors.nim:1157]: Is this some kind of joke? You merge your own PRs that have non resolved points of discussion?

Comment (bung87) [reply compiler/injectdestructors.nim:1157]: the final choice is `not ({sfGlobal, sfPure} <= ri.sym.flags)`

Comment (Araq) [reply compiler/injectdestructors.nim:1157]: That is not what "github diff" showed me but ok.

Comment (ringabout) [reply compiler/injectdestructors.nim:1157]: That diff is from another later PR  https://github.com/nim-lang/Nim/commit/f18e4c4050cb59cf828372f89c01d9e80f6516c5

Comment (bung87) [reply compiler/injectdestructors.nim:1157]: yeah, I fix in another PR, as we all noticed this part here, after merging, I thought there may have something to do, so I checked `proc `<=``, `runnableExamples` the elegant syntax is there
