### PR TITLE
Fix problems with persistent HTTP connections

### LINKED ISSUE #4969: Problems with persistent HTTP connections
Current `httpclient` and `asynchttpserver` have the following problems:
1. Multipart request "breaks" the connection: the following request parsing fails.
2. Requests modify `(Async)HttpClient`'s headers. For example, `POST` request will write `Content-Length` there. This breaks following `GET` requests, unless the programmer explicitly removes corresponding headers.

Here's an example, demonstrating both problems:
```nim
import asynchttpserver, asyncdispatch, httpclient, unittest, os

proc cb(req: Request) {.async.} =
  case req.reqMethod
  of HttpGet:
    await req.respond(Http200, "OK")
  of HttpPost:
    await req.respond(Http200, "OK")
  else:
    await req.respond(Http400, "Unknown method")

proc runServer() {.thread.} =
  var server = newAsyncHttpServer()
  waitFor server.serve(Port(5555), cb)

let url = "http://localhost:5555"

var t: Thread[void]
createThread(t, runServer)

sleep(500)

suite "HTTP":
  setup:
    let client = newHttpClient()

  teardown:
    client.close

  test "Multipart shouldn't break persistent connections":
    var md = newMultipartData()
    md.add("foo", "bar")
    discard client.postContent(url, multipart = md)
    # This fails
    discard client.postContent(url, multipart = md)

  test "Shouldn't preserve specific headers between requests":
    discard client.postContent(url, "content")
    # This hangs
    discard client.getContent(url)

quit 0
```

Nim version: 0f34196

### PR DESCRIPTION
**Pull request by nigredo-tori**
Fixes #4969 

1. More robust request parsing in accordance with https://tools.ietf.org/html/rfc7230#section-3.5 .
2. Add `overrideHeaders` parameter to `request` procs for headers that shouldn't persist between requests.

### CODE REVIEW

**Comment by Araq** [comment]
@dom96 Please review, looks good to me.

File: lib/pure/asynchttpserver.nim [hunk 1]
```diff
@@ -133,14 +133,21 @@ proc processClient(client: AsyncSocket, address: string,
...
 
-    # First line - GET /path HTTP/1.1
-    lineFut.mget().setLen(0)
-    lineFut.clean()
-    await client.recvLineInto(lineFut) # TODO: Timeouts.
-    if lineFut.mget == "":
-      client.close()
-      return
+    # We should skip empty lines before the request
+    # https://tools.ietf.org/html/rfc7230#section-3.5
```
Comment (dom96) [inline lib/pure/asynchttpserver.nim]: The spec says that "at least one empty line" should be ignored. Let's remove this infinite loop.

File: lib/pure/httpclient.nim [hunk 2]
```diff
@@ -989,8 +989,17 @@ proc newConnection(client: HttpClient | AsyncHttpClient,
...
+  result = newHttpHeaders()
+  # Copy by value
+  result.table[] = fallback.table[]
+  for k, vs in override.table:
+    result[k] = vs
+
 proc request*(client: HttpClient | AsyncHttpClient, url: string,
-              httpMethod: string, body = ""): Future[Response] {.multisync.} =
+              httpMethod: string, body = "",
+              overrideHeaders: HttpHeaders = nil): Future[Response] {.multisync.} =
```
Comment (dom96) [inline lib/pure/httpclient.nim]: Rename the parameters to ``headers``.

File: lib/pure/httpclient.nim [hunk 3]
```diff
@@ -1023,11 +1032,17 @@ proc request*(client: HttpClient | AsyncHttpClient, url: string,
   else:
     await newConnection(client, connectionUrl)
 
-  if not client.headers.hasKey("user-agent") and client.userAgent != "":
-    client.headers["User-Agent"] = client.userAgent
+  var effectiveHeaders: HttpHeaders
+  if overrideHeaders != nil:
+    effectiveHeaders = overrideHeaders.withFallback(client.headers)
```
Comment (dom96) [inline lib/pure/httpclient.nim]: Let's put the nil check into the ``withFallback`` function and maybe reverse it. Call it ``override`` and change it so that it's called like so:

```
client.headers.override(overrideHeaders)
```

**Comment by nigredo-tori** [comment]
@dom96, changed as requested.

**Comment by dom96** [comment]
@nigredo-tori thanks!
