### PR TITLE
fix #18823 Passing Natural to bitops.BitsRange[T] parameter in generi…

### LINKED ISSUE #18823: Passing Natural to bitops.BitsRange[T] parameter in generic proc is compile error
Minimum code:
```nim
import std/bitops

testBit(1, 1.Natural)
```

Compile error message:
```
f:\temp\nim-1.5.1\lib\pure\bitops.nim(63, 37) Error: 'sizeof' requires '.importc' types to be '.completeStruct'
```

Minimum code without importing bitops:
```nim
type BitsRange[T] = range[0..sizeof(T)*8-1]

proc bar[T](a: T; b: BitsRange[T]) =
  discard

bar(1, 2.Natural)
```

Compile error message:
```
f:\temp\testbitr.nim(1, 36) Error: 'sizeof' requires '.importc' types to be '.completeStruct'
```

This code also produces same compile error:
```nim
type BitsRange[T] = range[0..sizeof(T)*8-1]

proc bar[T](a: T; b: BitsRange[T]) =
  discard

bar(1.Natural, 2.Natural)
```

Just converting `Natural` variable to BitsRange[int] doesn't make compile error.
Following code compiles without erorr.
```nim
type BitsRange[T] = range[0..sizeof(T)*8-1]

var x: BitsRange[int] = 0
x = 1.Natural
echo x

var y: BitsRange[Natural] = 0
y = 1.Natural
echo y
y = 2
echo y

proc foo(x: BitsRange[int]) =
  discard

foo(1)
foo(1.Natural)

proc foo2(x: BitsRange[Natural]) =
  discard

foo2(1)
foo2(1.Natural)

proc bar[T](a: T; b: BitsRange[T]) =
  discard

bar(1.Natural, 2)
```

Nim version:
```
f:\temp>nim -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-09-08
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by bung87**
…c proc is compile error

fix #18823

### CODE REVIEW

File: compiler/ast.nim [hunk 1]
```diff
@@ -2017,7 +2017,10 @@ proc findUnresolvedStatic*(n: PNode): PNode =
   # n.typ == nil: see issue #14802
   if n.kind == nkSym and n.typ != nil and n.typ.kind == tyStatic and n.typ.n == nil:
     return n
-
+  if n.typ != nil and n.typ.kind == tyTypeDesc:
+    let t = skipTypes(n.typ, {tyTypeDesc})
+    if t != nil and t.kind == tyGenericParam and t.len == 0:
```
Comment (Araq) [inline compiler/ast.nim]:
```suggestion
    if t.kind == tyGenericParam and t.len == 0:
```

`skipTypes` never returns nil.

File: compiler/ast.nim [hunk 2]
```diff
@@ -2017,7 +2017,10 @@ proc findUnresolvedStatic*(n: PNode): PNode =
   # n.typ == nil: see issue #14802
   if n.kind == nkSym and n.typ != nil and n.typ.kind == tyStatic and n.typ.n == nil:
     return n
-
+  if n.typ != nil and n.typ.kind == tyTypeDesc:
```
Comment (Araq) [inline compiler/ast.nim:2027]: But why would an "unresolved static" be a typedesc?

Comment (bung87) [reply compiler/ast.nim:2027]: no sure, there are multiple places make typedesc node,
like in `semExpr`  line 2970  
```nim
of nkTypeOfExpr..nkTupleClassTy, nkStaticTy, nkRefTy..nkEnumTy:
    if c.matchedConcept != nil and n.len == 1:
      let modifier = n.modifierTypeKindOfNode
      if modifier != tyNone:
        var baseType = semExpr(c, n[0]).typ.skipTypes({tyTypeDesc})
        result.typ = c.makeTypeDesc(c.newTypeWithSons(modifier, @[baseType]))
        return
```

Comment (bung87) [reply compiler/ast.nim:2027]: also forget to mention, it's static -> typedesc -> typedesc ->generic., skip once doesn't work out for test case.

File: compiler/sigmatch.nim [hunk 3]
```diff
@@ -1140,9 +1141,10 @@ proc typeRel(c: var TCandidate, f, aOrig: PType,
       if result notin {isNone, isGeneric}:
         # resolve any late-bound static expressions
         # that may appear in the range:
+        let expectedType = skipTypes(f, {tyRange})
```
Comment (Araq) [inline compiler/sigmatch.nim]: Why skip `range` here? How do you know that the expected type is not the range but its basetype?

This is just overfitting the logic so that the test case compiles.

Comment (bung87) [reply compiler/sigmatch.nim]: here under `if a.kind == f.kind` the whole block whether compare base type via `result = typeRel(c, base(f), base(a), flags)` or handle `f.n[0]` `f.n[1]`
