### PR TITLE
suggestion for a simple fix for #21279

### LINKED ISSUE #21279: C++ backend: Nim memsetting imported classes to 0 breaks semantics established by default constructor of imported classes
### Description

While trying to iterate over a C++ std::vector of std::string*s using the Nim 2.0 RC with MSVC 17.4.4, I stumbled upon the following problem:

```Nim
{.passC: "/std:c++latest /permissive- /Zc:strictStrings-".}

import strformat

type
    String {.importcpp: "std::string" header: "<string>" byref.} = object
    Vector [T] {.importcpp: "std::vector" header: "<vector>".} = object

proc createVector[T](): Vector[T] {.importcpp: "std::vector<'*0>(@)" constructor.}

proc createString(str: cstring): String {.importcpp: "std::string(@)" constructor.}
proc cstr(str: String): cstring {.importcpp: "(NCSTRING)#.c_str()".}
proc `$`(str: String): string = $(str.cstr)

proc add[T](this: var Vector[T], elem: T) {.importcpp: "#.push_back(@)".}
proc len[T](this: Vector[T]): csize_t {.importcpp: "#.size()".}
proc `[]`[T](this: Vector[T], idx: csize_t): T {.importcpp: "#[#]".}

iterator items[T](vec: Vector[T]): T =  
  for i in 0 ..< vec.len:
      yield vec[i]

proc run() =
    type Stuff = object
        a : String

    var
        foo = createVector[Stuff]()
        s0, s1 = Stuff()    
    s0.a = createString("ABC")
    s1.a = createString("DEF")

    foo.add(s0)
    foo.add(s1)

    for s in foo:
        echo &"{s.a}"

    echo "+++"

    for i in 0 ..< foo.len:
        echo &"{foo[i].a}"

run()
```

I expected to see:

```
ABC
DEF
+++
ABC
DEF
```

Instead, I got this:

```
*RANDOM STRING*
DEF
+++
ABC
DEF
```

Digging deeper into the C++ output, I found a major difference between how the first kind of loop is set up compared to the latter. In the first case, a default constructed std::string is being ```nimZeroMem```ed, i. e. memset to 0, like this:

```C++
...
tyObject_Stuff__B5du9cMG9ab5FexF5gAcu9c7Q s;
nimZeroMem((void*)(&s), sizeof(tyObject_Stuff__B5du9cMG9ab5FexF5gAcu9c7Q));
...
```

This though can mess with the work of the default constructor (in case of std::string for instance: resetting capacity, pointer to char buffer). The memset is not only unnecessary with a default constructor in place, there is also a good chance it destroys the internal semantics already established by the constructor.

Removing the nimZeroMem call results in the expected output.

### Nim Version

Nim Compiler Version 1.9.1 [Windows: amd64]
Compiled at 2022-12-22

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by heterodoxic**
This is my very first attempt at a pull request at all. The purpose of this very simple fix is to tackle issue #21279: it is just a very rough heuristic, catching obvious cases, while neglecting several others where nimZeroMem might cause trouble as well. Yet, I prefer such a small fix for now, in order to minimize the chance of any side effects.

Would close #21279 for instances where ~~"shallowly composed objects"~~ objects containing imported C++ types are used.

### CODE REVIEW

**Comment by heterodoxic** [comment]
The two failing CI checks complain about missing packages: am I right to assume those problems are not related to my suggested changes (sorry, still utterly new to working with GitHub)?

**Comment by ringabout** [comment]
Nice work! I'm restarting the CI.

**Comment by heterodoxic** [comment]
Thank you, and thank you! :upside_down_face:

**Comment by heterodoxic** [comment]
Almost there! :smile:
This time unfortunately, a stubborn one decided to time out, as far as I can tell...

**Comment by Araq** [comment]
This is still incomplete and getting quite messy. It would need to use the general type iteration mechanism as types.nim offers it:

```nim

proc searchTypeFor*(t: PType, predicate: TTypePredicate): bool

```

**Comment by heterodoxic** [comment]
Thank you @Araq! As I am still quite new to both GitHubbing and Nim hacking, I was mostly hoping for stirring up any guidance at all on my early attempts, and am still struggling with wrapping my head around the compiler's and codegen's internals. I will inspect `searchTypeFor` and will try to come up with a more thorough solution (especially dealing with deeply nested objects).

BTW: I have not forgotten about my thread gathering some other aspects at #21308, and will add more stuff to it soon. I would appreciate it very much if you were to have a more regular look at it, offering some assistance for the layhumans there to improve the experience of travelling between the worlds of Nim and C++.

Most of all: thank you for your time and effort on Nim!

**Comment by heterodoxic** [comment]
Please have a look at this revised proposal :slightly_smiling_face:.

File: compiler/cgen.nim [hunk 1]
```diff
@@ -480,6 +480,10 @@ proc resetLoc(p: BProc, loc: var TLoc) =
       # on the bytes following the m_type field?
       genObjectInit(p, cpsStmts, loc.t, loc, constructObj)
 
+proc containsImportedCppType(typ: PType): bool =
+  let actualType = typ.skipTypes({tyRef, tyPtr})
```
Comment (Araq) [inline compiler/cgen.nim]: Why? a ptr pointing to an imported C++ type can still be set to nil safely and should be.

Comment (heterodoxic) [reply compiler/cgen.nim]: Agreed, apparently, there is no need for skipping tyPtr. This was not about a pointer's operations, but to make sure that imported C++ types are actually correctly dug up by this method (i. e. if I were to remove the skipping of tyRef, ARC/ORC managed structures containing C++ classes would fall through the search pattern).

**Comment by heterodoxic** [comment]
Thank you for your support. I hope this version seems more appropriate (not sure about my naming of the proc). Sorry about the closing and re-opening repetitions of the pull request, still learning both GitHub and Nim internals, obviously.

**Comment by Araq** [comment]
This is now as I described it should be. However, it's still not correct for types that mix both e.g. Nim's `seq` which needs zero initialization and an imported C++ type.

**Comment by heterodoxic** [comment]
Yes, as you can see, the problem is not as easy as the "Easy" label that was attached to my issue suggests: especially not for a newbie Nim hacker. :wink:

I hope you realize though that liberally memsetting structs to 0 for C++ codegen was a far too simplistic design decision in the first place, **if** easy C++ interop is supposed to be a major feature of Nim.

I will try to come up with a solution which satisfies mixed cases, but I gladly welcome any further and more comprehensive assistance.

As it stands, I think this is a major problem for C++ interop with pervasive negative effects worth fixing rather quickly, and of course more thoroughly than I am trying so far, lacking knowledge of the deeper mechanisms of Nim.

Yet, I am trying to help here with my modest means at disposal at the moment, so I am looking forward to reading further detailed guidance how we could fix this together, how we could improve upon an already nice C++ interop experience! :slightly_smiling_face:

**Comment by heterodoxic** [comment]
What minimal C++ version are we targetting? Were we to aim for C++11, default value initialization by braces could save a lot of work here by delegating zero-initialization to the respective compiler, as far as I gathered (https://en.cppreference.com/w/cpp/language/value_initialization).

**Comment by Araq** [comment]
Indeed we aim for C++11.

**Comment by heterodoxic** [comment]
With C++11 backing us up, I figured: why engage myself in meticulous work for default-initialization contingencies when there is a  compiler around who will gladly do this for us - as soon as we inform it to do so by appending `{}` to declarations for [automatically stored](https://en.cppreference.com/book/storage_durations) variables output by the codegen?

So the rationale behind these changes is in short: find objects being/containing  imported structs/classes and apply C++ default-initialization rules, which should also take care of cases where they are mixed with pure Nim data types.

Please have a close look at this, I hope it moves forward a remedy against the problem I outlined at the very beginning without harming Nim's ecology.

**Comment by Araq** [comment]
This is an excellent solution but `nim cpp tests/misc/trunner_special.nim` fails with this change.

**Comment by heterodoxic** [comment]
Could you please restart the CI? I am still barely able to grasp the tests' output, but it seems the test failed due to some SSL (verification timeout?) trouble? I have noticed it fail for other pull requests completed unrelated to my changes.

**Comment by heterodoxic** [comment]
Once these changes might be applied to the current code base, I will probably file another pull request to expand C++11 default-value initialization to more carefully examined places, thus significantly reducing the emitted code size, and increasing readibility of the output, I hope.
