### PR TITLE
Minor fixes for asyncjs

### LINKED ISSUE #6971: asyncjs assign async proc doesnt work
The following code doesnt work with asyncjs:
```
import asyncjs

var foo = proc(): Future[void] {.gcsafe, closure, async.} =
  echo "baa"

waitFor foo()
```
Stacktrace:

> stack trace: (most recent call last)                                                                                                                                                                                    
> lib/js/asyncjs.nim(137)  async                                                                                                                                                                                          
> lib/js/asyncjs.nim(92)   generateJsasync                                                                                                                                                                                
> lib/system.nim(3756)     failedAssertImpl                                                                                                                                                                               
> lib/system.nim(3748)     raiseAssert                                                                                                                                                                                    
> lib/system.nim(2811)     sysFatal                                                                                                                                                                                       
> asyncjsassignbug.nim(3, 32) template/generic instantiation from here                                                                                                                                                    
> lib/system.nim(2811, 7) Error: unhandled exception: kind(arg) == nnkProcDef

### PR DESCRIPTION
**Pull request by LemonBoy**
Mark internal procedures as used
Allow .async. for more node kinds
Make .async. work for nkStmtList

Fixes #6971

### CODE REVIEW

File: lib/js/asyncjs.nim [hunk 1]
```diff
@@ -137,7 +140,12 @@ proc generateJsasync(arg: NimNode): NimNode =
 macro async*(arg: untyped): untyped =
   ## Macro which converts normal procedures into
   ## javascript-compatible async procedures
-  generateJsasync(arg)
+  if arg.kind == nnkStmtList:
+    for oneProc in arg:
+      result = newStmtList()
```
Comment (Araq) [inline lib/js/asyncjs.nim]: This assignment should be outside the ``for`` loop.
