### PR TITLE
fixes #25566; `{.align.}` pragma where each 16-byte-aligned

### LINKED ISSUE #25566: Regression from v2.2.6 to v2.2.8 and also `devel` in refc `{.align.}` pragma where each 16-byte-aligned heap objects gets its own page
### Nim Version

Pre-regression:
```
Nim Compiler Version 2.2.6 [Linux: amd64]
Compiled at 2026-03-01
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: ab00c56904e3126ad826bb520d243513a139436a
active boot switches: -d:release
```

Post-regression:
```
Nim Compiler Version 2.2.8 [Linux: amd64]
Compiled at 2026-03-01
Copyright (c) 2006-2026 by Andreas Rumpf

git hash: 4f500679b196fad944caa50a753f5bbfaefda001
active boot switches: -d:release
```

```
Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2026-03-01
Copyright (c) 2006-2026 by Andreas Rumpf

git hash: e69d672354f6ee663e93c0ca2c4d02ebc22681ca
active boot switches: -d:release
```

### Description

```nim
type U = object
  d {.align: 16.}: int8
var e: seq[ref U]
for i in 0 ..< 10000: e.add(new U)
echo getTotalMem()
```
Also notably, if one uses a variation of this:
```nim
type U = object
  d {.align: 16.}: int8
var e: seq[ref U]
for i in 0 ..< 10000: e.add(new U)
for f in e: echo cast[uint](addr f[]) mod 4096
```
in v2.2.8, every one byte (but sure, 16-byte-aligned) item is in its own 4096-byte, at a constant offset of 64 into said page, explaining the increased memory usage.

For v2.2.6, it shows:
```
80
112
144
176
208
240
272
304
336
368
```
and cycles around more gradually, with 32-byte strides.

### Current Output

```text
With v2.2.6: 1052672
With v2.2.8 and devel: 45916160
```

### Expected Output

```text

```

### Known Workarounds

_No response_

### Additional Information

Potentially related to:
- https://github.com/nim-lang/Nim/pull/25525

### PR DESCRIPTION
**Pull request by ringabout**
fixes #25566

### CODE REVIEW

File: tests/align/talign2.nim [hunk 1]
```diff
@@ -0,0 +1,11 @@
+discard """
+  matrix: "--mm:refc -d:useGcAssert -d:useSysAssert; --mm:orc"
+  targets: "c cpp"
```
Comment (ringabout) [inline tests/align/talign2.nim]:
```suggestion
```

**Comment by arnetheduck** [comment]
why the 16-byte alignment on 32-bit platforms? ie malloc on 32-bit targets typically aligns to 8 (using `max_align_t` from the C standard to tell) - it just wastes a bit of memory without providing much practical benefit.

What's important with an allocator is that it respects the alignment requirements of the type, not any one random alignment like 16.

**Comment by Araq** [comment]
Yeah and equally important is to have a "hotfix" in place while we rewrite the entire allocator because alignment is a bitch.

**Comment by arnetheduck** [comment]
> Yeah and equally important is to have a "hotfix" in place while we rewrite the entire allocator because alignment is a bitch.

The alternative here is to roll back the attempt at implementing alignment, ie `align: 16` never worked on 32-bit before either (or any other alignment for that matter). Supporting `align` is only useful if it works for all settings of `align`.

**Comment by Araq** [comment]
How so? No codebase uses "all settings of align", there are only a handful values that are used in practice.
