### PR TITLE
fix #8871 runnableExamples now preserves source code comments, litterals, and all formatting; other bug fix

### LINKED ISSUE #8871: runnableExamples should preserve source code doc comments, strings, and (maybe) formatting
```nim
proc foo*()=
  runnableExamples:
    import std/strutils
    ## line_doc_comment
    # bar
    doAssert "'foo" == "'foo"
    ##[
    foo
    bar
    ]##
    doAssert: not "foo".startsWith "ba"
```

renders as:
```nim
import
  "pathto/runnableExamples/t03_bad_quoting.nim"

import
  std / strutils

block:
  doAssert "\'foo" == "\'foo"
  ## foo
  ## bar
  ## 
  doAssert:
    not "foo".startsWith "ba"
```

- [ ]  the added quoting `\'` in  `"\'foo" , although not incorrect, is not needed and the way it's written in the source (`"'foo"`)should be preserved
- [ ] the `line_doc_comment` is not rendered
- [ ] an extra `##` with empty comment (below `bar`) is wrongly inserted
- [ ] [minor] formatting is a bit odd, eg `doAssert: not "foo".startsWith "ba" is in 1 line in source file but gets split in 2 when rendered which is rather ugly (and vertical space hoarder, when there are a bunch of these) ; not sure how easy it'd be to fix that since it's rendered
```nim
doAssert:
    not "foo".startsWith "ba"
```

## these are correct:
* the multiline doc comment is rendered (although see note above regarding extra `##`)
* the comment `bar` which is not a doc comment is not preserved (useful to distinguish what shd end up in docs vs not)

## links
* pr_fix_8871_runnableExamples_verbatim (didn't finish)

### LINKED ISSUE #9345: runnableExamples: `\r` renders as `\c`
runnableExamples: `\r` renders as `\c`

```nim
proc removePrefix*(s: var string, chars: set[char] = Newlines) {.
  rtl, extern: "nsuRemovePrefixCharSet".} =
  ## Removes all characters from `chars` from the start of the string `s`
  ## (in-place).
  ##
  runnableExamples:
     var userInput = "\r\n*~Hello World!"
```

shows as:

/Users/timothee/.cache/nim/strutils_d/runnableExamples/strutils_examples13.nim
```nim
import
  "/Users/timothee/git_clone/nim/Nim/lib/pure/strutils.nim"

block:
  var userInput = "\c\n*~Hello World!"
  userInput.removePrefix
```

likewise in rendered html page, but that's a consequence of above: it renders as `var userInput = "\c\n*~Hello World!"`

### LINKED ISSUE #14473: `nim doc ..` on a user project is attempting to run runnableExamples from stdlibs, and failing incorrectly [devel] [regression]
`nim doc ..` is failing because of 2 reasons:
- runnableExamples are attempted to be run from an imported stdlib (`sequtils` in this example). This is not expected. 
- While above should not be happening, it is failing for not finding a proc from the imported stdlib module (`toSeq` from `sequtils` in this example).

### Example
```nim
# https://forum.nim-lang.org/t/6382#39363
import std/[sequtils]

# "nim doc t.nim" will work once below line is uncommented
# export sequtils

template doit():untyped =
  ## doit
  ## return output only
  toSeq([1,2,3,4,5])

echo doit()
```

### Current Output

```
/tmp/kmodi/.cache/nim/t_d/runnableExamples/t_examples1.nim(15, 12) Error: undeclared identifier: 'toSeq'
[runnableExamples] failed: generated file: '/tmp/kmodi/.cache/nim/t_d/runnableExamples/t_group0_examples.nim' group: '(rdoccmd: "", docCmd: "", code: "# autogenerated by docgen\n# source: /home/kmodi/sandbox/nim/bug_reports/nim_doc_over_eager_runnableExamples/t.nim\n# rdoccmd: \nimport r\"/tmp/kmodi/.cache/nim/t_d/runnableExamples/t_examples1.nim\"\n", index: 0)' cmd: /home/kmodi/usr_local/apps/6/nim/devel/bin/nim c -r --warning:UnusedImport:off --path:/home/kmodi/sandbox/nim/bug_reports/nim_doc_over_eager_runnableExamples --nimcache:/tmp/kmodi/.cache/nim/t_d/runnableExamples   /tmp/kmodi/.cache/nim/t_d/runnableExamples/t_group0_examples.nim
```

### Expected Output
```
# (no runnable examples should be running from stdlibs or imported nimble packages)
@[1, 2, 3, 4, 5]
```

### Additional Information

* Minimal example was provided by @qqtop on https://forum.nim-lang.org/t/6382#39363
* This issue is blocking generation of docs for my projects.
* This regression is starting to fail the `nim doc` executions on Travis done using the latest nim devel. Example: https://travis-ci.org/github/kaushalmodi/version/jobs/692027081#L355
* I haven't confirmed but probably this commit ( https://github.com/nim-lang/Nim/commit/f96555bd102d534342eac14063bd8d93ec08a6dc ) caused this regression /cc @timotheecour Can you please take a look at this issue?

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-26
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2a4a43b05fa3fa6ad3f85543ccfbd9ea450c9be0
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #8871
* EDIT: fix #9345
* fix a regression introduced in https://github.com/nim-lang/Nim/pull/14441 that would cause skipping runnableExamples in templates in some cases; and made the logic cleaner (and easier to change if needed) by using a simple state machine instead of a recursive call in `getAllRunnableExamples`
* fix https://github.com/nim-lang/Nim/issues/14473 (similar/same as above point)
* found a corner from 1st version of this PR and fixed it, see `testNimDocTrailingExample`, because `numLines` is inclusive

most imporantly:
* add a lot of regression tests to prevent future regressions

so now both #8871 and #8871 as can be seen in by comparing `nim doc --outdir:htmldocs --project nimdoc/testproject/testproject.nim`:

## for #8871
right before https://github.com/nim-lang/Nim/pull/14441:
image

after this PR:
image

=> we're now preserving formatting exactly (in particular we don't skip comments, change litterals and change indentation etc)

## and for #8871
right before https://github.com/nim-lang/Nim/pull/14441:
image

after this PR:
image

=> we're now not skipping doc comments (C) after the 1st runnableExamples (R) so if you have CRCRC you end up with CRCRC instead of CRR; also we're now preserving ordering

### CODE REVIEW

**Comment by kaushalmodi** [comment]
This is awesome! Just yesterday, I noticed that runnableExamples was reformatting my manually set indentation; e.g. [this][1] rendered to https://kaushalmodi.github.io/version/#getVersion%2CopenArray%5Bstring%5D%2Cstring

[1]: https://github.com/kaushalmodi/version/blob/09100e7d619e8b681bb794d7b38d2b66e23a8af9/src/version.nim#L139-L147

**Comment by Araq** [comment]
Did you consider to re-use nimpretty's approach? Also, is it time to make ``nimdoc`` a tool of its own?

**Comment by timotheecour** [comment]
@araq PTAL (you can look at generated html for `nim doc --project -r nimdoc/testproject/testproject.nim`)

> Did you consider to re-use nimpretty's approach?

nimpretty doesn't do syntax highlighting so the code I wrote is still needed even with reusing/calling nimpretty.
Future work could nimpretty-fy the source code string (it may or may not be desirable though eg wrt preserving user formatted examples). 

This PR got a bit larger than initially because I fixed other issues (see updated note in top post) and added a lot of tests, but the part that's responsible for extracting and rendering runnableExampes (ie fixing #8871) is actually quite concise.

> Also, is it time to make nimdoc a tool of its own?

IMO we should completely separate the reflection part (getting postprocessed (after semcheck) AST with module infos, symbols, doc comments properly attached, runnableExamples-as-string, etc) from the rendering part (including running runnableExamples which calls nim-as-binary and doesn't need to depend on compiler sources). All rendering code should be separated from the compiler and would just consume what the 1st step produces (IR, json, PNode, etc see below though).

and here's how it should work IMO:

## macros should be powerful enough to enable full reflection and 100% replace docgen

We can have really clean concise `nim-doc-as-library` by adding just a few magics that would enable full reflection (representing AST after semcheck for each module as 1 NimNode (typed AST)), **without even having to `import compiler`**.

This is one of the uses cases I had in mind with https://github.com/nim-lang/Nim/pull/9560 and https://github.com/nim-lang/Nim/pull/8903 and I actually had a working prototype of `nim-doc` in pure user code using those 2 PR's, that did not need `import compiler`. It didn't handle many important things like RST parsing, running runnableExamples etc from doc comments, but would be doable especially if we separate rst-logic from compiler and usable in a separate module (stdlib or fusion, probably stdlib since compiler still needs it for now )

Note: this approach invovles 0 serialization (no IR or json needed) since the macros get all they need via a NimNode for each module representing all symbols. It's then possible for user code to then convert these to whatever format needed (json, etc) or to re-do what nim doc does.

## other use cases for reflection beyond nim doc
these could be implemented in user code via macros by exposing AST after semantic phase:
* search tool (eg: list all routines that take an `openArray[string]` as 1st argument
* linter (eg: report when `result` is un-assigned)
* nimfix (eg: replace noop code like `myseq = @[]` initializations)
etc

**Comment by Clyybber** [comment]
@timotheecour Love the idea of docgen as a macro.
Maybe it can be done without additional magics via this approach:
```nim
import macros

macro genDocs(e: typed) =
  echo treeRepr e

genDocs:
  include moduleWeWantToGenerateDocsFor
```

**Comment by Araq** [comment]
> macros should be powerful enough to enable full reflection and 100% replace docgen

I completely disagree. This idea that we can never ever *reduce* an AST because it might be rendered back to ascii somewhere did cost us years of implementation effort, keeps costing us effort and makes writing macros more complex. What's the benefit? A good docgen is still as hard to implement as it was before, if not harder and you'll put pressure on the Nim VM.

**Comment by kaushalmodi** [comment]
@timotheecour Referring to your comment in https://github.com/nim-lang/Nim/issues/14473#issuecomment-634927880,

> this should be fixed in #14439 (I just tried), can you confirm on your end and also for your project that #14439 works?

Yes, I just confirmed that this PR fixes the minimal example in https://github.com/nim-lang/Nim/issues/14473, as well as in my real project.

Can you update a test case in this PR to also `import std/[sequtils]` and use one of the exported symbols from that in the test case to match the test case in https://github.com/nim-lang/Nim/issues/14473 ?

Thanks!

**Comment by timotheecour** [comment]
> Can you update a test case in this PR to also import std/[sequtils] and use one of the exported symbols from that in the test case to match the test case in #14473 ?

done. (see also: https://github.com/nim-lang/RFCs/issues/231)

**Comment by timotheecour** [comment]
friendly ping @araq because this fixes a very recent regression that I've introduced in  #14441 that prevents some runnableExamples from running; let me know if you instead want me
* A to split it in 2 PR's but, since this PR adds a number of tests (which I should've done in https://github.com/nim-lang/Nim/pull/14441 ...) it should give more confidence
* B revert https://github.com/nim-lang/Nim/pull/14441 in the meantime

File: compiler/docgen.nim [hunk 1]
```diff
@@ -529,67 +534,104 @@ proc prepareExample(d: PDoc; n: PNode): string =
...
-    getAllRunnableExamplesRec(d, n[i], orig, dest, previousIsRunnable2)
+      return rsRunnable
+  else: discard
+  return rsDone
+    # change this to `rsStart` if you want to keep generating doc comments
+    # and runnableExamples that occur after some code in routine
+
+proc getRoutineBody(n: PNode): PNode =
+  ## works around a transf bug D20200526T163511 where `result` messes AST
+  # TODO: try w templates and macro, see if they're affected
```
Comment (Araq) [inline compiler/docgen.nim]: What's wrong  with ``bodyPos``?

File: compiler/renderverbatim.nim [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+  #[
+  we stop at the first de-indentation; there's an inherent ambiguity with non
+  doc comments since they can have arbitrary indentation, so we just take the
+  practical route and require a runnableExamples to keep its code (including non
+  doc comments) to its indentation level.
+  ]#
+  for j in 0..<indent:
+    if src.len <= j: return true
+    if src[j] == ' ': continue
+    return false
```
Comment (Araq) [inline compiler/renderverbatim.nim]: Most convoluted control flow. ``if src[j] != ' ': return false``.

File: compiler/renderverbatim.nim [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+  return true
+
+proc extractRunnableExamplesSource*(conf: ConfigRef; n: PNode): string =
+  ## TLineInfo.offsetA,offsetB would be cleaner but it's only enabled for nimpretty,
+  ## we'd need to check performance impact to enable it for nimdoc.
+  let first = n.lastSon.info
+  let last = n.lastNodeRec.info
+  var ret = ""
```
Comment (Araq) [inline compiler/renderverbatim.nim]: Use ``result``

File: compiler/renderverbatim.nim [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+  ]#
+  for j in 0..<indent:
+    if src.len <= j: return true
+    if src[j] == ' ': continue
+    return false
+  return true
+
+proc extractRunnableExamplesSource*(conf: ConfigRef; n: PNode): string =
+  ## TLineInfo.offsetA,offsetB would be cleaner but it's only enabled for nimpretty,
+  ## we'd need to check performance impact to enable it for nimdoc.
```
Comment (Araq) [inline compiler/renderverbatim.nim:28]: Not a fan, but ok.

File: compiler/renderverbatim.nim [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+  let first = n.lastSon.info
+  let last = n.lastNodeRec.info
```
Comment (Araq) [inline compiler/renderverbatim.nim:44]: But what if the "last" node is the result of a template expansion and refers to a different file entirely?

File: compiler/renderverbatim.nim (hunk 3 above)
Comment (timotheecour) [reply compiler/renderverbatim.nim]: done

File: compiler/renderverbatim.nim (hunk 2 above)
Comment (timotheecour) [reply compiler/renderverbatim.nim]: done

File: compiler/renderverbatim.nim (hunk 4 above)
Comment (timotheecour) [reply compiler/renderverbatim.nim:28]: it'd avoid some hacks I'm doing, but the hacks aren't too bad and very localized

File: compiler/renderverbatim.nim (hunk 5 above)
Comment (timotheecour) [reply compiler/renderverbatim.nim:44]: that can't happen AFAIK because template isn't semchecked at this point; see the `fromUtilsGen` test I added and look at the resulting html

File: compiler/docgen.nim (hunk 1 above)
Comment (timotheecour) [reply compiler/docgen.nim]: will reply below so this doesn't get burried

**Comment by timotheecour** [comment]
@araq PTAL; all points addressed and found I more corner case that i fixed (regular comments before the 1st node inside a runnableExamples are now correctly handled, ie appear as part of the doc comment)


in reply to https://github.com/nim-lang/Nim/pull/14439#discussion_r431822781

> What's wrong with bodyPos?

I added some explanation inside PR code; whether it's a bug or not I'm not sure, but it seems inconsistent that you have:
```nim
  proc someType*(): int =
    ## foo
    result = 3
=> this is weird
  result =
    ## foo
    3;

  proc someType*(): int =
    ## foo
    3
=> this is fine
  ## foo
  result = 3;
```

IMO the sane behavior is for transf to transform the 1st case into the following instead:
```nim
## foo
result = 3;
```


This has very strong echoes of https://github.com/nim-lang/Nim/issues/14420#issuecomment-633711557

EDIT: simplified further in https://github.com/nim-lang/Nim/pull/14701
