### PR TITLE
Fix #17412

### LINKED ISSUE #17412: `seq.pop` deletes the whole seq at compile time using ARC-bootstrapped Nim
To reproduce this, **you need to bootstrap using ARC**: `koch boot --gc:arc`.

This behavior was spotted in several `important_packages`, and this is an extracted minimal example.

### Example
```nim
var a {.compileTime.} = @["a"]

proc foo =
    a.add("b")
    a.add("c")
    a.add("d")
    echo a
    let c = a.pop() # causes trouble
    echo c
    echo a # should be: @["a", "b", "c"]; it is: @[]
    a.add("z") # "attempt to access a nil address"

static:
  foo()
```

### Current Output
```
@["a", "b", "c", "d"]
d
@[]
stack trace: (most recent call last)
(...)/filename.nim(11, 6) Error: attempt to access a nil address  
```

### Expected Output
```
@["a", "b", "c", "d"]
d
@["a", "b", "c"]
```

cc @Clyybber

### PR DESCRIPTION
**Pull request by Clyybber**
This is not as clean as I'd like, because I had to move `ccgIntroducedPtr` to ccgutils. Ideally the c backend would be more modular and use imports.

### CODE REVIEW

File: compiler/liftdestructors.nim [hunk 1]
```diff
@@ -230,6 +230,14 @@ proc fillBodyObjT(c: var TLiftCtx; t: PType, body, x, y: PNode) =
     # for every field (dependent on dest.kind):
     #   `=` dest.field, src.field
     # =destroy(blob)
+    if ccgIntroducedPtr(c.g.config,
+         (var dummy = newSym(skTemp, getIdent(c.g.cache, lowerings.genPrefix), nextSymId c.idgen, c.fn, c.info); dummy.typ = y.typ; dummy), y.typ):
```
Comment (Araq) [inline compiler/liftdestructors.nim]: Move this outside the `ccgIntroducedPtr` call.

Comment (Clyybber) [reply compiler/liftdestructors.nim]: Done
