### PR TITLE
generate symchoice for ambiguous types in templates & generics + handle types in symchoices

### LINKED ISSUE #23898: Identifier exported as typename in one module and `template` in another can't be used in `template`
### Description

`c.nim`:
```nim
type K* = object
```

`s.nim`:
```nim
import ./c
export c
template K*(kind: static int): auto = typedesc[c.K]
template B*(kind: static int): auto = typedesc[c.K]
```

`j.nim`
```nim
import ./s
discard default(B(0))       # compiles
discard default(s.B(0))     # compiles
discard default(K(0))       # compiles
template r() =
  discard default(B(0))     # compiles
  discard default(s.B(0))   # compiles
  discard default(K(0))     # does not compile
```

### Nim Version

```
Nim Compiler Version 2.0.10 [Linux: amd64]
Compiled at 2024-07-27
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 92e505577e8b6b9214b6fcdd7fe1b0e9a244023b
active boot switches: -d:release
```

```
Nim Compiler Version 2.1.9 [Linux: amd64]
Compiled at 2024-07-27
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 39629a1adcbcc822508acc3983f444328f90dd85
active boot switches: -d:release
```

### Current Output

```text
j.nim(8, 19) Error: ambiguous identifier: 'K' -- use one of the following:
  c.K: K
  s.K: template (kind: static[int]): auto
```

### Expected Output

```text
If B(0), s.B(0), and K(0) work outside the template, and B(0) and s.B(0) work inside the template, K(0) also works inside the template.
```

### Possible Solution

_No response_

### Additional Information

Related to https://github.com/nim-lang/Nim/issues/23893 and `c.nim` and `s.nim` in both issues are identical.

In particular, as a result of that issue, one cannot work around this issue that readily in templates because by adding that disambiguating module identifier, it hits that issue instead of this issue but still does not compile.

### PR DESCRIPTION
**Pull request by metagn**
fixes #23898, supersedes #23966 and #23990

Since #20631 ambiguous type symbols in templates are rejected outright, now we generate a symchoice for type nodes if they're ambiguous, a generalization of what was done in #22375. This is done for generics as well. Symchoices also handle type symbols better now, ensuring their type is a `typedesc` type; this probably isn't necessary for everything to work but it makes the logic more robust.

Similar to #23989, we have to prepare for the fact that ambiguous type symbols behave differently than normal type symbols and either error normally or relegate to other routine symbols if the symbol is being called. Generating a symchoice emulates this behavior, `semExpr` will find the type symbol first, but since the symchoice has other symbols, it will count as an ambiguous type symbol.

I know it seems spammy to carry around an ambiguity flag everywhere, but in the future when we have something like #23104 we could just always generate a symchoice, and the symchoice itself would carry the info of whether the first symbol was ambiguous. But this could harm compiler performance/memory use, it might be better to generate it only when we have to, which in the case of type symbols is only when they're ambiguous.

### CODE REVIEW

File: lib/pure/ioselects/ioselectors_select.nim [hunk 1]
```diff
@@ -314,7 +314,7 @@ proc selectInto*[T](s: Selector[T], timeout: int,
 
   if timeout != -1:
     when defined(genode) or defined(freertos) or defined(zephyr) or defined(nuttx):
-      tv.tv_sec = Time(timeout div 1_000)
+      tv.tv_sec = posix.Time(timeout div 1_000)
```
Comment (Araq) [inline lib/pure/ioselects/ioselectors_select.nim:317]: Does this imply a breaking change?

Comment (metagn) [reply lib/pure/ioselects/ioselectors_select.nim:317]: Generics completely ignore ambiguous types in the current compiler, the `Time` identifier here is actually ambiguous between `times.Time` and `posix.Time` but only by chance the compiler picked `posix.Time` first and captured it. It now gives an ambiguity error, the same one it would give if the proc wasn't generic.

It's breaking in the sense that it can cause compile errors but only for code that essentially worked by random chance. I also think all it does would be causing compile errors, I don't think there's a chance of it leaking into runtime or anything like that. An exception is macros having to deal with symchoices but it really shouldn't be a problem, maybe we can still mention the AST difference in the changelog just in case someone encounters it.

Comment (metagn) [reply lib/pure/ioselects/ioselectors_select.nim:317]: Added to changelog
