### PR TITLE
fixes #16080

### LINKED ISSUE #16080: db_sqlite: Error: undeclared field: 'untypedLen'
The following code taken from the db_sqlite isMainModule section does not compile:

```
var db = open(":memory:", "", "", "")
exec(db, sql"create table tbl1(one varchar(10), two smallint)", [])
exec(db, sql"insert into tbl1 values('hello!',10)", [])
exec(db, sql"insert into tbl1 values('goodbye', 20)", [])
var p1 = db.prepare "create table tbl2(one varchar(10), two smallint)"
exec(db, p1)
finalize(p1)
```

Compiler Error:
```
s.nim(31, 5) template/generic instantiation of `exec` from here
~/.choosenim/toolchains/nim-1.4.0/lib/impure/db_sqlite.nim(795, 12) Error: undeclared field: 'untypedLen'
```
I took a look at line 795 of db_sqlite:
```
macro untypedLen(args: varargs[untyped]): int =
  newLit(args.len)

template exec*(db: DbConn, stmtName: SqlPrepared,
          args: varargs[typed]): untyped =
  when args.untypedLen > 0:								#<-- Error happens here
    if reset(stmtName.PStmt) != SQLITE_OK:
      dbError(db)
    if clear_bindings(stmtName.PStmt) != SQLITE_OK:
      dbError(db)
    stmtName.bindParams(args)
  if not tryExec(db, stmtName): dbError(db)
```

If I change the code to:

```
-  when args.untypedLen > 0:
+  when untypedLen(args) > 0:
```

It compiles and works fine.

Nim Version:
```
Nim Compiler Version 1.4.0 [Linux: amd64]
Compiled at 2020-10-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: bdcd87afca238a0a7b2c70971827cf9172817b12
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by RokkuCode**
db_sqlite: Error: undeclared field: 'untypedLen'

### CODE REVIEW

File: lib/impure/db_sqlite.nim [hunk 1]
```diff
@@ -850,7 +850,7 @@ macro bindParams*(ps: SqlPrepared, params: varargs[untyped]): untyped {.since: (
     else:
       result.add newCall(bindNull, preparedStatement, newIntLitNode idx + 1)
 
-macro untypedLen(args: varargs[untyped]): int =
+macro untypedLen*(args: varargs[untyped]): int =
```
Comment (Araq) [inline lib/impure/db_sqlite.nim]:
```suggestion
macro untypedLen(args: varargs[untyped]): int =
```

**Comment by Araq** [comment]
Instead change the line ``when args.untypedLen > 0:`` to ``when untypedLen(args) > 0:``
