### PR TITLE
Modification to implementation of round() such that it returns a floa…

### LINKED ISSUE #3473: Changing math.round() and adding math.integer()
I just needed something like `let a = math.round((a - b) * 100.0) / 100.0` which does not work because `math.round()` returns an `int`.

Should this not better be something like this in math module:

```nim
proc round*(x: float): float {.importc: "round", header: "<math.h>".}
proc roundToEven*(x: float): float {.importc: "lrint", header: "<math.h>".}

# and "maybe"
proc roundToInt*(x: float): int = toInt(x)
proc integer*(x: float): int = int(x)
```
So that you stay in the floating point domain when using round?

I would also prefer to have an additional `round(x, digits)` in the standard library `let x = round(a - b,2)`.

While experimenting I found that `toInt()` is also rounding. `toInt(0.5)` results in 1 which is unexpected for me. I would think `toInt()` basically drops the decimals and nothing else. While `int(0.5)` and `int(-0.5)` is doing what I expected from `toInt()`. So we could probably just change `math.round()` to return floating point like `ceil()` and `floor()` does and let `toInt()` as it is as and use it where `round()` was used before.

It even seems to me that round is using the "wrong" function to be use. `lrint()` rounds x.5 depending on x. If x is even it rounds down if x is uneven it rounds up. This is to "even out" rounding errors in financial data. Which is a nice function but probably not what I expect from `round()`, no matter if that results in an int or float type.

But then. With this information I have all I need but with "not obvious" names. So I would still like to have "round()" doing the propper mathematical round (as it is in math module) and deliver a floating point type. While we could introduce another `round()` which uses `lrint()` with either `lrint()` as name or probably `financialRound() / ieeeRound() / roundToEven()` which also returns floating point but explains what it really does. 

```nim
echo int(0.5) # 0
echo int(-0.5) # 0

echo toInt(0.5) # 1
echo toInt(-0.5) # -1

echo round(0.5) # 0
echo round(-0.5) # 0

echo round(1.5) # 2
echo round(-1.5) # 2
```

### PR DESCRIPTION
**Pull request by abudden**
Modification to implementation of round() such that it returns a float and accepts a places argument (fixes #3473).

This also involved moving some functions around to get the hierarchy correct and the documentation for frexp was modified such that it was clear that it can return a float in either the range [-1, -0.5] or [0.5, 1].

Also includes a function to split decimal numbers at the decimal place (splitDecimal).

First pull request in a series to implement engineering formatting of numbers in strings.

### CODE REVIEW

File: lib/pure/math.nim [hunk 1]
```diff
@@ -256,22 +247,11 @@ else:
 
   proc exp*(x: float32): float32 {.importc: "Math.exp", nodecl.}
   proc exp*(x: float64): float64 {.importc: "Math.exp", nodecl.}
-  proc round*(x: float): int {.importc: "Math.round", nodecl.}
+  proc round0*(x: float): float {.importc: "Math.round", nodecl.}
```
Comment (Araq) [inline lib/pure/math.nim]: According to you, you don't want to export 'round0' ;-)

File: lib/pure/math.nim [hunk 2]
```diff
@@ -295,6 +275,60 @@ else:
...
+      exponent = 0
+      result = 0.0
+    elif x < 0.0:
+      result = -frexp(-x, exponent)
+    else:
+      var ex = floor(log2(x))
+      exponent = round(ex)
+      result = x / pow(2.0, ex)
+
+proc splitDecimal*[T: float32|float64](x: T): tuple[intpart: T, floatpart: T] =
```
Comment (Araq) [inline lib/pure/math.nim]: Why is intpart also a floating point type?

File: lib/pure/math.nim [hunk 3]
```diff
@@ -357,3 +391,36 @@ when isMainModule and not defined(JS):
   assert(lgamma(1.0) == 0.0) # ln(1.0) == 0.0
   assert(erf(6.0) > erf(5.0))
   assert(erfc(6.0) < erfc(5.0))
+when isMainModule:
+  # Function for approximate comparison of floats
+  proc floatIsEqual(x, y: float): bool = (abs(x-y) < 1e-9)
```
Comment (Araq) [inline lib/pure/math.nim]: proc `=~` or `==~` is more readable here.

File: lib/pure/math.nim (hunk 1 above)
Comment (abudden) [inline lib/pure/math.nim]: Whoops!

File: lib/pure/math.nim (hunk 2 above)
Comment (abudden) [inline lib/pure/math.nim]: Urmm... Convention? http://www.cplusplus.com/reference/cmath/modf/

File: lib/pure/math.nim (hunk 3 above)
Comment (abudden) [inline lib/pure/math.nim]: Hmmm... okay.  I don't think I'd seen that one before.  There doesn't seem to be an applicable reference in the index ([http://nim-lang.org/docs/theindex.html#=~](http://nim-lang.org/docs/theindex.html#=~)).  Where can I find out about what `=~` and `==~` mean?

**Comment by abudden** [comment]
Sorry: I've inadvertently included the splitDecimal function in this push request.  I'm still learning how these things work; I didn't expect it to be added when I pushed the branch after submitting the pull request.  I'll edit the description accordingly.

File: lib/pure/math.nim (hunk 2 above)
Comment (abudden) [inline lib/pure/math.nim]: Also I guess because of the range of numbers.  A floating point value of 1.5e300 will (presumably) be split into an intpart of 1.5e300 and a floatpart of 0.  The intpart fits in a float64 but not in an int64.

File: lib/pure/math.nim (hunk 1 above)
Comment (abudden) [inline lib/pure/math.nim]: Fixed in 1b9c66d

File: lib/pure/math.nim (hunk 3 above)
Comment (abudden) [inline lib/pure/math.nim]: I've searched through the code-base and can't find any relevant reference to `=~` or `==~`, so I assume you mean that I should implement it as a local proc instead of calling that proc `floatIsEqual`.  I've implemented that in 695b251; I used `==~` in case `=~` ever makes it into the standard library.
