### PR TITLE
fixes #10942. Lent T bug

### LINKED ISSUE #10942: `lent T` can return garbage
I was able to reproduce this problem only with `--cpu:i386 --cc:vcc` compiler arguments, but the problem is fundamental. Test case:
```nim
type
  MyField = object
    b: seq[string]

  MyObject = object
    f: MyField

proc getX(x: MyObject): lent MyField = 
  x.f

let a = MyObject()
echo a.getX.b.len

# doAssert: a.getX().unsafeAddr == a.f
```

The generated code for `getX` proc has fundamental flaw:
```C

N_LIB_PRIVATE N_NIMCALL(tyObject_MyField_TRBCGJu2GrSeYqJblPj9bNA*, 
getX_bA682BkQAkX49bq4vsNGpig)(tyObject_MyObject_J9bt9aFMq9aaD4DaLIDS9cAW1Q x) {
	tyObject_MyField_TRBCGJu2GrSeYqJblPj9bNA* result;
	result = (tyObject_MyField_TRBCGJu2GrSeYqJblPj9bNA*)0;
	result = (&x.f);
	return result;
}
```
The `x` argument is passed by copy hence returned pointer is  a pointer to a temporary object. I am afraid it is not a valid C code.

If proc returns `lent T` then all object/tuple arguments needs be passed by reference.
I have tried fixing it by changing codegen, but it wasn't not enough. sempass needs to add hidden addr, derefs nodes to make it work.

### PR DESCRIPTION
**Pull request by cooldome**
adds support for unsafeAddr for `lent T` returned type.
fixes #10942 by passing by reference object and tuples if `lent T` is returned

### CODE REVIEW

File: compiler/parampatterns.nim [hunk 1]
```diff
@@ -254,7 +258,7 @@ proc isAssignable*(owner: PSym, n: PNode; isUnsafeAddr=false): TAssignableResult
       # types that are equal modulo distinction preserve l-value:
       result = isAssignable(owner, n.sons[1], isUnsafeAddr)
   of nkHiddenDeref:
-    if n[0].typ.kind == tyLent: result = arDiscriminant
```
Comment (Araq) [inline compiler/parampatterns.nim]: You need to watch out that ``returnsLent().field = value`` and ``passToVarT(returnsLent())`` is not allowed. ``arDiscriminant`` was supposed to cover that.

Comment (cooldome) [reply compiler/parampatterns.nim]: Good catch, missed the fact that else is lValue. Fixed. Extended test to cover this case

File: compiler/parampatterns.nim [hunk 2]
```diff
@@ -230,17 +230,21 @@ proc isAssignable*(owner: PSym, n: PNode; isUnsafeAddr=false): TAssignableResult
...
         sfDiscriminant in n[1].sym.flags:
       result = arDiscriminant
   of nkBracketExpr:
-    if skipTypes(n.sons[0].typ, abstractInst-{tyTypeDesc}).kind in
-        {tyVar, tyPtr, tyRef}:
+    let t = skipTypes(n.sons[0].typ, abstractInst-{tyTypeDesc})
+    if t.kind in {tyVar, tyPtr, tyRef}:
+      result = arLValue
+    elif isUnsafeAddr and t.kind == tyLent:
       result = arLValue
```
Comment (Araq) [inline compiler/parampatterns.nim]: Why is that not ``arDiscriminant``?

File: compiler/parampatterns.nim [hunk 3]
```diff
@@ -230,17 +230,21 @@ proc isAssignable*(owner: PSym, n: PNode; isUnsafeAddr=false): TAssignableResult
       let t = n.sym.typ.skipTypes({tyTypeDesc})
       if t.kind == tyVar: result = arStrange
   of nkDotExpr:
-    if skipTypes(n.sons[0].typ, abstractInst-{tyTypeDesc}).kind in
-        {tyVar, tyPtr, tyRef}:
+    let t = skipTypes(n.sons[0].typ, abstractInst-{tyTypeDesc})
+    if t.kind in {tyVar, tyPtr, tyRef}:
+      result = arLValue
+    elif isUnsafeAddr and t.kind == tyLent:
       result = arLValue
```
Comment (Araq) [inline compiler/parampatterns.nim]: Why is that not ``arDiscriminant``?
