### PR TITLE
fixes #21617; createTypeBoundOps with PContext in order to instantiate generics

### LINKED ISSUE #21617: Can't use generic as method return type
### Description

```nim
type Test = ref object of RootObj

method bug(t: Test): seq[float] {.base.} = discard
```
With arc/orc

### Nim Version

c71192043b9febbfc058717ad3d4fde3a22c61da

### Current Output

```text
/tmp/test.nim(3, 8) Error: cannot generate destructor for generic type: seq[float]
```

### Expected Output

```text
Compiles
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #21617

### CODE REVIEW

File: compiler/cgen.nim [hunk 1]
```diff
@@ -1099,7 +1099,7 @@ proc genProcBody(p: BProc; procBody: PNode) =
 proc isNoReturn(m: BModule; s: PSym): bool {.inline.} =
   sfNoReturn in s.flags and m.config.exc != excGoto
 
-proc genProcAux(m: BModule, prc: PSym) =
+proc genProcAux*(m: BModule, prc: PSym) =
```
Comment (Araq) [inline compiler/cgen.nim:1102]: There is no need to export this, I think.

File: compiler/cgmeth.nim [hunk 2]
```diff
@@ -213,7 +213,7 @@ proc sortBucket(a: var seq[PSym], relevantCols: IntSet) =
       a[j] = v
     if h == 1: break
 
-proc genDispatcher(g: ModuleGraph; methods: seq[PSym], relevantCols: IntSet; idgen: IdGenerator): PSym =
+proc genDispatcher(g: ModuleGraph; methods: seq[PSym], relevantCols: IntSet): PSym =
```
Comment (Araq) [inline compiler/cgmeth.nim]: Ideally you keep the `idgen` parameter, the module graph's id generator is not as good for IC.

File: compiler/cgmeth.nim [hunk 3]
```diff
@@ -276,7 +272,7 @@ proc genDispatcher(g: ModuleGraph; methods: seq[PSym], relevantCols: IntSet; idg
   nilchecks.flags.incl nfTransf # should not be further transformed
   result.ast[bodyPos] = nilchecks
 
-proc generateMethodDispatchers*(g: ModuleGraph, idgen: IdGenerator): PNode =
+proc generateMethodDispatchers*(g: ModuleGraph): PNode =
```
Comment (Araq) [inline compiler/cgmeth.nim]: Likewise.

File: compiler/cgen.nim (hunk 1 above)
Comment (ringabout) [reply compiler/cgen.nim:1102]: It is used in pipelines because `createTypeBoundOps` needs `PContext` to work propely and the C code of method dispatcher cannot be generated in the cgen module. In pipelines, it needs to generate the code of the symbol. `genTopLevelStatement(m, disp.sym.ast)` is not enough. It has to use `genProcAux` like what is done before.

```nim
        let ctx = preparePContext(graph, module, idgen)
        for disp in disps:
          let retTyp = disp.sym.typ[0]
          if retTyp != nil:
            # todo properly semcheck the code of dispatcher?
            createTypeBoundOps(graph, ctx, retTyp, disp.info, idgen)
          genProcAux(BModule(bModule), disp.sym)
 ```
