### PR TITLE
fixes #21290; deindent if the last same level is a text node

### LINKED ISSUE #21290: std/xmltree: adds indentation incorrectly to text nodes
### Description

The following example:
```nim
import std/xmltree
let x = newXmlTree("foo",[
  newXmlTree("bar",[
    newText("Hola"),
    newXmlTree("qux",[
      newXmlTree("plugh",[])
    ])
  ])
])
echo x
```
outputs:
```
<foo>
  <bar>Hola  <qux>    <plugh />  </qux></bar>
</foo>
```

Whatever the output is, there shouldn't be any spaces left between the text node and the consecutive node. So it should be:
```xml
.... <bar>Hola<qux>...
```

### Nim Version

Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

### Current Output

```text
<foo>
  <bar>Hola  <qux>    <plugh />  </qux></bar>
</foo>
```

### Expected Output

```text
<foo>
  <bar>Hola<qux><plugh /></qux></bar>
</foo>
```

### Possible Solution
If the function `add` is modified as follows:
```nim
proc add*(result: var string, n: XmlNode, indent = 0, indWidth = 2,
          addNewLines = true; forceNoSpace:bool = false) =
  ## Adds the textual representation of `n` to string `result`.
  runnableExamples:
    var
      a = newElement("firstTag")
      b = newText("my text")
      c = newComment("my comment")
      s = ""
    s.add(c)
    s.add(a)
    s.add(b)
    assert s == "<!-- my comment --><firstTag />my text"

  proc addEscapedAttr(result: var string, s: string) =
    # `addEscaped` alternative with less escaped characters.
    # Only to be used for escaping attribute values enclosed in double quotes!
    for c in items(s):
      case c
      of '<': result.add("&lt;")
      of '>': result.add("&gt;")
      of '&': result.add("&amp;")
      of '"': result.add("&quot;")
      else: result.add(c)

  if n == nil: return

  case n.k
  of xnElement:
    # initially indents and adds new lines as per function call
    if indent > 0 and not forceNoSpace:
      result.addIndent(indent, addNewLines)

    result.add('<')
    result.add(n.fTag)
    if not isNil(n.fAttr):
      for key, val in pairs(n.fAttr):
        result.add(' ')
        result.add(key)
        result.add("=\"")
        result.addEscapedAttr(val)
        result.add('"')

    if n.len == 0:
      result.add(" />")
      return

    result.add('>')

    var avoidIndent = false
    for i in 0 ..< n.len:
      if n[i].kind in {xnText, xnEntity}:
        avoidIndent = true  
        result.add(n[i], 0, indWidth, false)
      else:
        if avoidIndent:
          result.add(n[i], indent + indWidth, indWidth, addNewLines, true) # avoids indent and newline
        else:
          result.add(n[i], indent+indWidth, indWidth, addNewLines)       
        avoidIndent = false

    if not avoidIndent:
      result.addIndent(indent, addNewLines)

    result.add("</")
    result.add(n.fTag)
    result.add(">")
  of xnText:
    result.addEscaped(n.fText)

  of xnVerbatimText:
    result.add(n.fText)
  of xnComment:
    result.add("<!-- ")
    result.addEscaped(n.fText)
    result.add(" -->")
  of xnCData:
    result.add("<![CDATA[")
    result.add(n.fText)
    result.add("]]>")
  of xnEntity:
    result.add('&')
    result.add(n.fText)
    result.add(';')
```

This creates the following output:
```xml
<foo>
  <bar>Hola<qux>
      <plugh />
    </qux>
  </bar>
</foo>
```

### Additional Information

https://forum.nim-lang.org/t/9836

### PR DESCRIPTION
**Pull request by ringabout**
fixes #21290

### CODE REVIEW

File: tests/stdlib/txmltree.nim [hunk 1]
```diff
@@ -83,3 +83,19 @@ block:
...
+      newXmlTree("qux",[
+        newXmlTree("plugh",[])
+      ])
+    ])
+  ])
+
+  let s = $x
+  doAssert $parseXml(s) == s
+  doAssert s == """<foo>
+  <bar>Hola<qux>    <plugh />  </qux></bar>
```
Comment (metagn) [inline tests/stdlib/txmltree.nim:100]: In the issue the expected output is `Hola<qux><plugh /></qux>`

Comment (ringabout) [reply tests/stdlib/txmltree.nim:100]: Yeah, I only agree that there shouldn't have any spaces after text nodes. That's an obvious bug since `$parseXml(s) == s` is not satisfied.


> Whatever the output is, there shouldn't be any spaces left between the text node and the consecutive node. So it should be:

There are two proposed output in that issue

```xml
<foo>
  <bar>Hola<qux><plugh /></qux></bar>
</foo>
```

```xml
<foo>
  <bar>Hola<qux>
      <plugh />
    </qux>
  </bar>
</foo>
```

I simply fix the bug.

Comment (ringabout) [reply tests/stdlib/txmltree.nim:100]: There are two proposed output in that issue

```xml
<foo>
  <bar>Hola  <qux>    <plugh />  </qux></bar>
</foo>
```

```xml
<foo>
  <bar>Hola<qux>
      <plugh />
    </qux>
  </bar>
</foo>
```
