### PR TITLE
fix #17267

### LINKED ISSUE #17267: js should ignore threads:on
```nim
echo "Hello"
```

nim js -r --threads:on app.nim

```
Error: 'getCurrentException' is not GC-safe as it accesses 'lastJSError' which is a global using GC'ed memory
```

Nim v1.4.2
Nim devel

### PR DESCRIPTION
**Pull request by ringabout**
fix #17267

### CODE REVIEW

File: compiler/main.nim [hunk 1]
```diff
@@ -119,6 +119,10 @@ proc commandCompileToJS(graph: ModuleGraph) =
     if conf.outFile.isEmpty:
       conf.outFile = RelativeFile(conf.projectName & ".js")
 
+    # js backend will ignore threads options
```
Comment (timotheecour) [inline compiler/main.nim]: i think the correct fix is similar to the one done for gc:arc:
```nim
  of "gc":
    if conf.backend == backendJs: return # for: bug #16033
```

so in this case it'd be:
```nim
  of "threadanalysis":
    if conf.backend == backendJs: discard
    else: processOnOffSwitchG(conf, {optThreadAnalysis}, arg, pass, info)
...
  of "threads":
    if conf.backend == backendJs: discard
    else: processOnOffSwitchG(conf, {optThreads}, arg, pass, info)
```

that way there's no intermediate bad state where those flags would be set (causing further other side effects) and then later unset

(for more background see https://github.com/nim-lang/Nim/pull/16036 and its followup https://github.com/nim-lang/Nim/pull/16056)

Comment (ringabout) [reply compiler/main.nim]: make sense

Comment (ringabout) [reply compiler/main.nim]: thanks

File: compiler/main.nim [hunk 2]
```diff
@@ -119,6 +119,10 @@ proc commandCompileToJS(graph: ModuleGraph) =
...
+    excl(conf.globalOptions, optThreads)
+    excl(conf.globalOptions, optThreadAnalysis)
+
```
Comment (ringabout) [inline compiler/main.nim]:
```suggestion
```

**Review by timotheecour — APPROVED** [review]

File: tests/threads/tjsthreads.nim [hunk 3]
```diff
@@ -0,0 +1,5 @@
+discard """
+  targets: "js"
+"""
+
+echo 123
```
Comment (timotheecour) [inline tests/threads/tjsthreads.nim]: I think this works "by accident" and could break in future because there is no corresponding `output: "123"` in spec, so might break megatest once we implement megatest-per-unique-option.
in any case i'd prefer:
```nim
discard """
  targets: "c cpp js"
  matrix: "--threads"
"""
discard
```

File: tests/threads/tjsthreads.nim [hunk 4]
```diff
@@ -0,0 +1,5 @@
+discard """
+  targets: "js"
+"""
```
Comment (ringabout) [inline tests/threads/tjsthreads.nim]:
```suggestion
discard """
  targets: "c cpp js"
  matrix: "--threads"
"""
```

**Review by timotheecour — APPROVED** [review]
