### PR TITLE
prevents declaring a constructor without importcpp fixes #22712

### LINKED ISSUE #22712: Defining a proc with constructor pragma cause compile error
### Description

When defined a procedure with constructor pragma, compile error comes from type section that imports C++ struct with `importcpp` pragma.
When that proc was not defined, it compiles without error.

Example:
```nim
{.emit: """/*TYPESECTION*/
struct CppStruct {
  CppStruct();
};
""".}

type CppStruct {.importcpp.} = object

when true: # Changing this to false doesn't cause compile error
  proc makeCppStruct(): CppStruct {.constructor.} =
    discard
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-17
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8836207a4e68c177d5059131df05a9d433dd3c8d
active boot switches: -d:release

### Current Output

```text
$ nim cpp testcpp.nim 
testcpp.nim(7, 30) Error: invalid pragma: CppStruct {.importcpp.}
```

### Expected Output

```text
Compiles without errors
```

### Possible Solution

_No response_

### Additional Information

That example code compiles without errors on Nim 2.0 stable.

### PR DESCRIPTION
**Pull request by jmgomez**

### CODE REVIEW

File: compiler/semstmts.nim [hunk 1]
```diff
@@ -2369,7 +2374,7 @@ proc semProcAux(c: PContext, n: PNode, kind: TSymKind,
         # used for overload resolution (there is no instantiation of the symbol)
         if s.kind notin {skMacro, skTemplate} and s.magic == mNone: paramsTypeCheck(c, s.typ)
         var resultType: PType
-        if sfConstructor in s.flags:
+        if {sfConstructor, sfImportc} * s.flags == { sfConstructor }:
```
Comment (Araq) [inline compiler/semstmts.nim]:
```suggestion
        if {sfConstructor, sfImportc} * s.flags == {sfConstructor}:
```
