### PR TITLE
[WIP] Pervasive replacement of nkRecWhen in generic types

### LINKED ISSUE #8417: Compiler crash when X[A: static[int]]'s body is dependent on another const
```nim
const Z = 0
type X[A: static[int]] = object
  when Z == 0:
    discard
  else:
    discard
let k = X[0]()
```

Crashes. Curiously, the following does not:

```nim
const Z = 0
type X[A: static[int]] = object
  when Z == 0 and A == 3:
    discard
  else:
    discard
let k = X[0]()
```

Possibly related to https://github.com/nim-lang/Nim/issues/8416.

Here is the traceback:

```
Error: internal error: (filename: "semobjconstr.nim", line: 242, column: 19)
Traceback (most recent call last)
nim.nim(133)             nim
nim.nim(97)              handleCmdLine
main.nim(162)            mainCommand
main.nim(73)             commandCompileToC
modules.nim(124)         compileProject
modules.nim(71)          compileModule
passes.nim(194)          processModule
passes.nim(103)          processTopLevelStmt
sem.nim(592)             myProcess
sem.nim(560)             semStmtAndGenerateGenerics
semstmts.nim(1891)       semStmt
semexprs.nim(912)        semExprNoType
semexprs.nim(2523)       semExpr
semstmts.nim(481)        semVarOrLet
semexprs.nim(59)         semExprWithType
semexprs.nim(2441)       semExpr
semexprs.nim(864)        semIndirectOp
semobjconstr.nim(275)    semObjConstr
semobjconstr.nim(249)    semConstructType
semobjconstr.nim(142)    semConstructFields
msgs.nim(536)            semConstructFields
msgs.nim(529)            internalError
msgs.nim(405)            rawMessage
msgs.nim(402)            rawMessage
msgs.nim(324)            handleError
msgs.nim(314)            quit
FAILURE
```

### PR DESCRIPTION
**Pull request by LemonBoy**
Long story short, even if the type contains no reference at all to its
generic parameters we still have to walk its AST and evaluate any
nkRecWhen nodes that semRecordNodeAux skipped due to the type being a
generic one.

We also must be careful to modify the type `n` node in place since it
may be referenced by the caller as seen in the tillegaltyperecursion
test.

I found this to be the nicest solution to the problem, we can't perform this resolution before the type is fully constructed as some `when` statements may refer to generic parameters and performing yet another (it'd be the third) pass over the type in order to resolve the remaining `nkRecWhen` is not that nice performance-wise.

This fixes #8417 and half of #7378.

### CODE REVIEW

**Comment by zah** [comment]
Hrm, OK, but we could also have changed the definition of `containsGenericType` to take into account the problematic `when` branches.

File: compiler/semtypinst.nim [hunk 1]
```diff
@@ -185,6 +218,11 @@ proc replaceTypeVarsN(cl: var TReplTypeVars, n: PNode; start=0): PNode =
     for i in countup(0, sonsLen(n) - 1):
       var it = n.sons[i]
       if it == nil: illFormedAst(n, cl.c.config)
+      if mdbg:
```
Comment (Araq) [inline compiler/semtypinst.nim]: Please remove this debug code.

File: compiler/semtypinst.nim [hunk 2]
```diff
@@ -198,6 +236,9 @@ proc replaceTypeVarsN(cl: var TReplTypeVars, n: PNode; start=0): PNode =
         if branch == nil: branch = it.sons[0]
       else: illFormedAst(n, cl.c.config)
     if branch != nil:
+      if mdbg:
```
Comment (Araq) [inline compiler/semtypinst.nim]: Please remove this debug code.

File: compiler/semtypinst.nim [hunk 3]
```diff
@@ -166,6 +166,39 @@ proc reResolveCallsWithTypedescParams(cl: var TReplTypeVars, n: PNode): PNode =
...
+proc replaceObjBranches(cl: TReplTypeVars, n: PNode): PNode =
+  result = n
+  case n.kind
+  of nkNone..nkNilLit:
+    discard
+  of nkRecWhen:
+    var branch: PNode = nil              # the branch to take
+    for i in countup(0, sonsLen(n) - 1):
+      var it = n.sons[i]
+      if mdbg:
```
Comment (Araq) [inline compiler/semtypinst.nim]: Please remove this debug code.
