### PR TITLE
fix dot calls with resolved symbols in templates

### LINKED ISSUE #7085: Error on method call syntax within a template
Following code doesn't work:

```nim
# Module A
proc foo(a: string): string =
  return a

template baz*(a: string): string =
  var b = a.foo()
  b
```

```nim
# Module B
import A

echo baz("hello")
# xxx template/generic instantiation from here
# xxx Error: attempting to call undeclared routine: 'foo'
```

Works replacing the method call by a regular proc call. Also works as is when using the template within module A. Also works when exporting `foo`. I can only guess the compiler tries to resolve the method call too late. The *method call limitations* section of the manual does not mention this specific case.

### LINKED ISSUE #20073: Method syntax in templates doesn't find bound functions that aren't in scope in caller
### Example
a.nim:
```nim
# Note: neither of these are exported, but are available in module a
type Foo = object
proc foo(f: Foo) = discard

template works*() =
  var f: Foo
  foo(f)

template boom*() =
  bind foo # tried this, but doesn't help
  var f: Foo
  f.foo() # Error: attempting to call undeclared routine: 'foo'
  f.foo # Error: undeclared field: 'foo' for type a.Foo
```

b.nim:
```nim
import a

works()
boom()
```

### Current Output
```
> nim r b
Hint: used config file '/home/mstearn/.choosenim/toolchains/nim-1.6.6/config/nim.cfg' [Conf]
Hint: used config file '/home/mstearn/.choosenim/toolchains/nim-1.6.6/config/config.nims' [Conf]
..........................................................
/home/mstearn/nim/realm/b.nim(4, 5) template/generic instantiation of `boom` from here
/home/mstearn/nim/realm/a.nim(11, 4) Error: attempting to call undeclared routine: 'foo'
```

(Also repros with devel)

### Expected Output
should compile

### Possible Solution

🤷

### Additional Information
This seems to go back to pre 1.0 (I tried 1.2.0 and 0.20.0 in addition to 1.6.6 and devel)

```
> nim -v
Nim Compiler Version 1.6.6 [Linux: amd64]
Compiled at 2022-05-05
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 0565a70eab02122ce278b98181c7d1170870865c
active boot switches: -d:releas
```

### PR DESCRIPTION
**Pull request by metagn**
fixes #20073, fixes #7085

`dotTransformation` transforms any resolved `nkSym`s as the field name back into `nkIdent`, but does not do this for sym choices. Generics account for this by [converting to `nkClosedSymChoice`](https://github.com/nim-lang/Nim/blob/21d941c16a84daa855870717f064802b052d6792/compiler/semgnrc.nim#L67-L68), but templates don't do anything similar. Now this is done in templates, but since code depended on it turning to `nkIdent` which was not resolved, we use `nkOpenSymChoice` instead.

### CODE REVIEW

File: tests/lexer/tcustom_numeric_literals.nim [hunk 1]
```diff
@@ -134,17 +134,14 @@ template main =
...
   block: # bug 1 from https://github.com/nim-lang/Nim/pull/17020#issuecomment-803193947
     macro deb1(a): untyped = newLit a.repr
-    macro deb2(a): untyped = newLit a.lispRepr
+    macro deb2(a): untyped =
+      a[1] = ident($a[1])
+      newLit a.lispRepr
     doAssert deb1(-12'wrap) == "-12'wrap"
     doAssert deb1(-12'nonexistent) == "-12'nonexistent"
     doAssert deb2(-12'nonexistent) == """(DotExpr (RStrLit "-12") (Ident "\'nonexistent"))"""
-    when false: # xxx bug:
```
Comment (metagn) [inline tests/lexer/tcustom_numeric_literals.nim:141]: This was not a bug. It's because this code is in a giant `main` template, which binds the outer `'wrap` and `wrap2`, because that's how the language works.

File: tests/lexer/tcustom_numeric_literals.nim [hunk 2]
```diff
@@ -165,21 +162,16 @@ template main =
     doAssert fn2() == "[[-12]]"
     doAssert fn3() == "[[-12]]"
 
-    when false: # xxx this fails; bug 9 from https://github.com/nim-lang/Nim/pull/17020#issuecomment-803193947
```
Comment (metagn) [inline tests/lexer/tcustom_numeric_literals.nim:168]: Meanwhile this was actually the bug fixed by this PR, custom numeric literals generate dot fields which did not keep their resolved symbols in templates. It really wouldn't have taken much investigation to figure out this is related to dot fields and has nothing to do with custom numeric literals. The linked comment thinks it has something to do with `'abc` not working where `abc` is a template param??? Very weird understanding of the language

**Comment by narimiran** [comment]
@arnetheduck I think I've seen this kind of error appearing in Status' codebase. Backport to 1.6?

**Comment by arnetheduck** [comment]
sure, looks interesting as far as bugfixes go
