### PR TITLE
Fix fat pointers, object copying, magic double evals on JS

### LINKED ISSUE #9410: Refs and ptrs aren't properly stored in object fields and in arrays on JS target
```nim
block:
    var someint = 500

    let p: ptr int = someint.addr
    let tup = (f: p)
    p[] = 654
    echo p[], " ", tup.f[]

block:
    var someint = 500

    let p: ptr int = someint.addr
    let arr = [p]
    p[] = 256
    echo someint, " ", p[], " ", arr[0][]

block:
    var someref: ref int
    new(someref)
    var someref2 = someref

    let tup1 = (f: someref)
    var tup2 = (f: someref)
    tup2.f = someref

    someref[] = 543

    echo someref[], " ", tup1.f[], " ", tup2.f[], " ", someref2[]
```
JS output
```
654 undefined
256 256 undefined
543 undefined undefined 543

```
C output
```
654 654
256 256 256
543 543 543 543
```

### PR DESCRIPTION
**Pull request by recloser**
Fixes #9410, #9389, #9643, #9644

### CODE REVIEW

File: compiler/jsgen.nim [hunk 1]
```diff
@@ -1855,7 +1855,10 @@ proc genArrayConstr(p: PProc, n: PNode, r: var TCompRes) =
   for i in countup(0, sonsLen(n) - 1):
     if i > 0: add(r.res, ", ")
     gen(p, n.sons[i], a)
-    add(r.res, a.res)
+    if a.typ == etyBaseIndex:
+      add(r.res, n.sons[i].sym.loc.r)
```
[the remark this answers is not in the document]
Comment (recloser) [reply compiler/jsgen.nim]: Yeah, this is a total hack. I tested some more and it doesn't deal properly with copying at all. I must admit I'm quite confused about how ptrs/refs are dealt with. The second element seems to be used for indexing, but it's always just 0. Wouldn't it be better to simply use a single element array?

Looks to me like a bunch of stuff will have to be changed since even seemingly simple stuff seems to generate rubbish, eg. (on 0.19)
```nim
block:
    var f: ref string
    new(f)
    f[] = "abc"
    echo f[]
```
generates
```js
L5: do {
	var f_25079 = [[null, 0]];
	var f_25079_Idx = 0;
	f_25079[1] = null;
	f_25079[0][f_25079[1]] = nimCopy(null, makeNimstrLit("abc"), NTI138);
	rawEcho(f_25079[0][f_25079[1]]);
} while(false);
```
`genNew` default initializes f[1] instead of f[0][0], and then the string is stored under f[0]["null"]. Yes, the "null" string key. WTF?

Anyway, I'll look into this more tommorow.

[the remark this answers is not in the document]
Comment (LemonBoy) [reply compiler/jsgen.nim]: > The second element seems to be used for indexing, but it's always just 0.

Not really. In order to support the `ptr`/`ref` semantics a pointer is described by a base and a displacement since JS has no concept of pointers. A small example will surely help here, consider the following snippet:

```nim
type
  Foo = object
    field: string

var
  oj = Foo(field: "bar")
  x = addr oj.field
  aj = [1,2,3]
  y = addr aj[1]

echo x[]
echo y[]
```

This is compiled down to:

```js
var oj_25006 = [{field: makeNimstrLit("bar")}];
var x_25008 = [oj_25006[0], "field"];
var aj_25012 = [nimCopy(null, [1, 2, 3], NTI25009)];
var y_25014 = [aj_25012[0], 1];
rawEcho(x_25008[0][x_25008[1]]);
rawEcho(cstrToNimstr((y_25014[0][y_25014[1]])+""));
```

As you can see the second element keeps track of "where" we are inside of the object the first element points to.

File: tests/js/t9410.nim [hunk 2]
```diff
@@ -0,0 +1,234 @@
+discard """
+  output: '''3 3
```
Comment (yglukhov) [inline tests/js/t9410.nim]: Please use `doAssert` instead of `echo` + expected output.

Comment (recloser) [reply tests/js/t9410.nim]: Will do, I used `echo`s since it initially made it easier to just compare the outputs of JS and C at a glance, but I guess the test grew a bit too large for that now.

**Comment by Araq** [comment]
It's pretty cool but we also need a more disciplined approach about how to handle this "eval only once" problem. Can't we just inject temporaries for every proc call that is not to a 'magic' proc (or to a magic proc that evaluates more than once)?

**Comment by recloser** [comment]
Temps are already being made for non-magic procs, it's the magics and inline magic impls that cause issues. 

Some magics can be easily fixed, for instance `mHigh`:
https://github.com/nim-lang/Nim/blob/491f19e96551d5ea380fc9cabe194fb195a26bb4/compiler/jsgen.nim#L1814-L1815
This could just make a temp for `$1` if the AST for `n[1]` involves a call of some kind.

Others would need to depend on that hack that I used for fixing `mInc` already. Consider this:
https://github.com/nim-lang/Nim/blob/491f19e96551d5ea380fc9cabe194fb195a26bb4/compiler/jsgen.nim#L1764-L1766
If this involves a deref like
```nim
getSomeVarString() &= 'c'
```
we can't just assign `$1` to a tmp, since that just gives us the dereferenced string itself which might be null. We need the ptr itself, but after defering we normally don't have that anymore. This is where the hack comes in, it'll store the temp that it needs to make for derefing in the normally unused address field:
```nim
"if ($2 != null) { addChar($1[0][$1[1]], $3); } else { $1[0][$1[1]] = [$3]; }" % [a.address, a.res, b.res]
```
Here `$2` will be expanded to something like
```js
(Tmp123 = getSomeVarString(), Tmp123[0])[Tmp123[1]]
```
and `$1` will be that `Tmp123` symbol itself. That way we can still access the ptr without double evaling and create the string/seq/whatever in case it was nil.

**Comment by Araq** [comment]
Ok, thanks for the explanation.

**Comment by Araq** [comment]
If you want a review, remove the ``[wip]``.

File: lib/system.nim [hunk 3]
```diff
@@ -2503,12 +2503,13 @@ proc `==`*[T](x, y: seq[T]): bool {.noSideEffect.} =
     when not defined(JS):
       proc seqToPtr[T](x: seq[T]): pointer {.inline, nosideeffect.} =
         result = cast[pointer](x)
-    else:
```
Comment (Araq) [inline lib/system.nim]: This entire diff looks suspicous to me.

Comment (recloser) [reply lib/system.nim]: This just checks if both params are backed by the same object. Since unsafeAddr can't be called here (seqs aren't treated as mapped directly to objects, so you'd a [box] to get the (base, index) ptr), I can't see an alternative way to do this check here.
