### PR TITLE
deprecate += and friends for bool and enum

### LINKED ISSUE #10257: `+=` (+ friends) shouldn't be allowed for `bool`
in most languages, `+=` isn't allowed for `bool`, but in Nim it is.
I can't think of any use case for that "feature".

```nim
proc main()=
  var a=false
  a+=true # ok ; proposal: CT error
  echo a
  a+=true # Error: unhandled exception: over- or underflow [OverflowError]

main()
```

this can lead to `OverflowError` and also masks the lack of error probably hides bugs (programmer probably didn't intend `a` to be `bool` in that context; which just happened to me)

## proposal
disallow integer arithmetic operators on `bool`, instead force using boolean operators. They can't ever lead to such `OverflowError` so are safer.

### PR DESCRIPTION
**Pull request by krux02**
`*=` never worked for bool, so didn't implement a deprecation path.
fixes #10257

### CODE REVIEW

File: lib/system.nim [hunk 1]
```diff
@@ -3881,15 +3881,21 @@ proc gorgeEx*(command: string, input = "", cache = ""): tuple[output: string,
...
+proc `+=`*[T: enum|bool](x: var T, y: T) {.
+  magic: "Inc", noSideEffect, deprecated: "use `inc` instead".}
+
+proc `-=`*[T: SomeInteger](x: var T, y: T) {.
   magic: "Dec", noSideEffect.}
   ## Decrements an ordinal
 
-proc `*=`*[T: SomeOrdinal|uint|uint64](x: var T, y: T) {.
+proc `-=`*[T: enum|bool](x: var T, y: T) {.
+  magic: "Dec", noSideEffect, deprecated: "use `dec` instead".}
```
Comment (kaushalmodi) [inline lib/system.nim]: I believe that the deprecation message should include the Nim version starting when that deprecation is effective. That would later help to batch remove deprecations.

If these deprecations are effective starting Nim 0.20, then it's easy to grep for version-specific deprecations and remove all in one go.

Very much related: https://github.com/nim-lang/RFCs/issues/93

File: lib/system.nim [hunk 2]
```diff
@@ -3881,15 +3881,21 @@ proc gorgeEx*(command: string, input = "", cache = ""): tuple[output: string,
...
 
-proc `+=`*[T: SomeOrdinal|uint|uint64](x: var T, y: T) {.
+proc `+=`*[T: SomeInteger](x: var T, y: T) {.
   magic: "Inc", noSideEffect.}
-  ## Increments an ordinal
+  ## Increments an integer
 
-proc `-=`*[T: SomeOrdinal|uint|uint64](x: var T, y: T) {.
+proc `+=`*[T: enum|bool](x: var T, y: T) {.
+  magic: "Inc", noSideEffect, deprecated: "use `inc` instead".}
```
Comment (kaushalmodi) [inline lib/system.nim]:
```suggestion
  magic: "Inc", noSideEffect, deprecated: "0.20.0, use `inc` instead".}
```

File: lib/system.nim (hunk 1 above)
Comment (kaushalmodi) [inline lib/system.nim]:
```suggestion
  magic: "Dec", noSideEffect, deprecated: "0.20.0, use `dec` instead".}
```

File: lib/system.nim (hunk 2 above)
Comment (kaushalmodi) [reply lib/system.nim]: @krux02 Looks like you didn't merge this suggested edit.
