### PR TITLE
fix #16384 and #17144

### LINKED ISSUE #16384: regression since 1.4.2: vm crash with lists.SinglyLinkedRing
### Example
```nim
import lists

template fn() =
  var L: SinglyLinkedRing[int]
  L.prepend(4)
  doAssert $L == "[4]" # ok

  L.prepend(4)
  doAssert $L == "[4, 4]" # bug: crash wo stacktrace or error

static: fn() # bug
fn() # ok
```

### Current Output
crashes with no output if running via choosenim nim shim
crashes with segmentation fault (no output) if running without nim shim on devel nim binary or 1.4.2, eg:
[1]    97786 segmentation fault nim r main.nim

### Expected Output
works

### Additional Information
1.4.2:
[1]    97786 segmentation fault nim r main
devel 5d8f862bc644e1db076e7e8cc8a2fe8c99009329 1.5.1: 
ditto

1.4.0:
works

discovered while reviewing https://github.com/nim-lang/Nim/pull/16362 and was trying to wrap test inside the classic pattern:
```nim
template main =
  # all the tests here
main()
static: main()
```

which is yet another argument while this pattern is useful, as it'd have prevented this regression

### LINKED ISSUE #17144: prependMoved failed at compile time
When diving into #17126, found this issue.

failed at Nim devel
```nim
import std/[lists, sequtils]

template main() =
  block:
    var
      l0 = initSinglyLinkedList[int]()
      l1 = [1].toSinglyLinkedList
      l2 = [2, 3].toSinglyLinkedList
      l3 = [4, 5, 6].toSinglyLinkedList
    l3.prependMoved l0
    l2.prependMoved l1

    doAssert l3.toSeq == [4, 5, 6]
    doAssert l2.toSeq == [1, 2, 3]
    l3.prepend l0
    doAssert l3.toSeq == [4, 5, 6]

static: main()
main()
```

Error: unhandled exception: D:\QQPCmgr\Desktop\Nim\test.nim(16, 14) `l3`gensym0.toSeq == [4, 5, 6]`  [AssertionDefect]

Work at RT

```
> nim -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-02-16
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #16384
fix #17144

### CODE REVIEW

File: compiler/vmgen.nim [hunk 1]
```diff
@@ -466,9 +466,12 @@ proc sameConstant*(a, b: PNode): bool =
     of nkEmpty: result = true
     else:
       if a.len == b.len:
-        for i in 0..<a.len:
-          if not sameConstant(a[i], b[i]): return
-        result = true
+        if first and cyclicTree(a):
```
Comment (timotheecour) [inline compiler/vmgen.nim]: not sure if this is correct, maybe instead we could do this differently:

in https://github.com/nim-lang/Nim/pull/15724/files#diff-43e428ef9f574e1c6c74da514b5f337286e4402916c094bac1c8e21ed6aca36bR998 instead of:

`elif sameConstant(nb, nc): ret = true`

do something that only considers procvar's

**Comment by Araq** [comment]
Why backport? This is not a regression and risky in itself.

**Comment by ringabout** [comment]
the codes from #16384 works for Nim 1.4.0 but failed at Nim 1.4.2. This PR fix the issue?

File: tests/stdlib/tlists.nim [hunk 2]
```diff
@@ -2,232 +2,242 @@ discard """
...
+          l1 = [1].toList
+          l2 = [2, 3].toList
+          l3 = [4, 5, 6].toList
+        l3.prependMoved l0
+        l2.prependMoved l1
+        doAssert l3.toSeq == [4, 5, 6]
+        doAssert l2.toSeq == [1, 2, 3]
+        l3.prepend l0
+        echo l0.toSeq
+        echo l3.toSeq
```
Comment (ringabout) [inline tests/stdlib/tlists.nim]:
```suggestion
```

File: compiler/vmgen.nim (hunk 1 above)
Comment (Araq) [reply compiler/vmgen.nim]: I'm quite sure `cyclicTree` is buggy and this is a strange solution. Instead special case tyProc or similar.

Comment (ringabout) [reply compiler/vmgen.nim]: done

File: tests/stdlib/tlists.nim [hunk 3]
```diff
@@ -2,232 +2,240 @@ discard """
...
+          l1 = [1].toList
+          l2 = [2, 3].toList
+          l3 = [4, 5, 6].toList
+        l3.prependMoved l0
+        l2.prependMoved l1
+        doAssert l3.toSeq == [4, 5, 6]
+        doAssert l2.toSeq == [1, 2, 3]
+        l3.prepend l0
+        when nimvm:
+          discard # TODO fixme
```
Comment (timotheecour) [inline tests/stdlib/tlists.nim]: somehow `doAssert l3.toSeq == [4, 5, 6]` works for me in VM after your PR (both c and js), what do you get here?

Comment (ringabout) [reply tests/stdlib/tlists.nim]: https://github.com/nim-lang/Nim/issues/17144

What about before my PR?

Comment (timotheecour) [reply tests/stdlib/tlists.nim]: EDIT: indeed, this seems to work now, and your PR fixes https://github.com/nim-lang/Nim/issues/17144 as well, great!

Comment (ringabout) [reply tests/stdlib/tlists.nim]: It seems that my new solution fixes the bug,

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
LGTM after removing the `TODO fixme` since it now works.

also note for other reviewers that to view the diff, it's best to do it locally after diffing against a file where you indent the whole test inside a `template main`, then the resulting diff is tiny:

```
diff --git a/Users/timothee/git_clone//nim//Nim_devel//tests/stdlib/tlists.nim b/tests/stdlib/tlists.nim
index bbce444d5..91afcf4b6 100644
--- a/Users/timothee/git_clone//nim//Nim_devel//tests/stdlib/tlists.nim
+++ b/tests/stdlib/tlists.nim
@@ -2,11 +2,12 @@ discard """
   targets: "c js"
 """

-import lists, sequtils
+import std/[lists, sequtils]

 const
   data = [1, 2, 3, 4, 5, 6]

+
 template main =
   block SinglyLinkedListTest1:
     var L: SinglyLinkedList[int]
@@ -184,7 +185,10 @@ template main =
         doAssert l3.toSeq == [4, 5, 6]
         doAssert l2.toSeq == [1, 2, 3]
         l3.prepend l0
-        doAssert l3.toSeq == [4, 5, 6]
+        when nimvm:
+          # discard # TODO fixme
+        else:
+          doAssert l3.toSeq == [4, 5, 6]
       block:
         var c = [0, 1].toList
         c.prependMoved c
```

**Comment by timotheecour** [comment]
I'd be fine with backporting this in its current state, but can be decided later.

**Review by timotheecour — APPROVED** [review]

File: compiler/vm.nim [hunk 4]
```diff
@@ -1019,7 +1019,8 @@ proc rawExecute(c: PCtx, start: int, tos: PStackFrame): TFullReg =
         let nc = regs[rc].node
         if nb.kind != nc.kind: discard
         elif (nb == nc) or (nb.kind == nkNilLit): ret = true # intentional
-        elif sameConstant(nb, nc): ret = true
+        elif (nb.kind in {nkSym, nkTupleConstr} and nb.typ.kind == tyProc) and sameConstant(nb, nc):
```
Comment (Araq) [inline compiler/vm.nim]: What about ``nkClosure``?

Comment (ringabout) [inline compiler/vm.nim]:
```suggestion
        elif (nb.kind in {nkSym, nkTupleConstr, nkClosure} and nb.typ.kind == tyProc) and sameConstant(nb, nc):
```
