### PR TITLE
Fixes #24369

### LINKED ISSUE #24369: Array field that has array-element type with copy-protector and default value set on a field will yield error
### Description

Sorry for the bad title, I am not sure how describe this better. However, I have a rather short piece of code that reproduces the code.

The following code will give a compiler error.

```nim
type
  Bar = object
    b: int = 1

  Foo = object
    f*: array[1, Bar]

proc `=copy`(dest: var Bar, source: Bar) {.error.}

discard Foo()
```

### Nim Version

Nim Compiler Version 2.2.0 [Linux: amd64]
Compiled at 2024-10-02
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 78983f1876726a49c69d65629ab433ea1310ece1
active boot switches: -d:release

### Current Output

```text
....../nim-2.2.0/lib/system.nim(2955, 19) Error: '=copy' is not available for type <Bar>; requires a copy because it's not the last read of 'y'; try to make y a 'sink' parameter; routine: arrayWith
```

### Expected Output

```text
<no compilation error>
```

### Known Workarounds

- Removing the default value for `Bar.b` will get rid of the error.
- Removing the copy-prevention will get rid of the error.
- Using `=dup` will get rid of the error (see comment below)
- Not using the object-initialiser will get rid of the error (i.g. not using `Foo()` and setting fields manually).

### Additional Information

I noticed that there is a comment ```# TODO: fixme it should be `=dup` ``` just at the line where the error is reported. When changing that according line to ```result[i] = `=dup`(y)``` the compiler error is gone. Not sure if that has any further impact in other places though...

### PR DESCRIPTION
**Pull request by saemideluxe**
Hope this fixes #24369, happy for any feedback on the PR.

### CODE REVIEW

File: lib/system.nim [hunk 1]
```diff
@@ -2969,5 +2969,4 @@ proc arrayWith*[T](y: T, size: static int): array[size, T] {.raises: [].} =
     when nimvm:
       result[i] = y
     else:
-      # TODO: fixme it should be `=dup`
-      result[i] = y
+      result[i] = `=dup`(y)
```
Comment (Araq) [inline lib/system.nim]: Problem is that the comment is wrong and the explicit `=dup` should not be necessary.

Comment (saemideluxe) [reply lib/system.nim]: So, if I understand correctly, the current implementation of `arrayWith` is correct as it has been so far (as we actually *will* copy `y`, but in the example type we forbid copying values, so semantics seem correct to me). But maybe there would need to be an alternative implementation of this function to implement array initialization using the `default` proc to generate the default value instead of passing in a default value?

If my assumptions are correct, I guess I would need to make changes in the `defaultNodeField` proc. Somewhere around here: https://github.com/nim-lang/Nim/blob/15271dba2f4772a193f027d36c05b838dfff5bd4/compiler/sem.nim#L674 correct?

Comment (metagn) [reply lib/system.nim]: Maybe instead of a generalized `arrayWith` the compiler could use an `arrayWithDefault` that does `result[i] = default(T)`, if `default(T)` behaves as expected in this case. @ringabout

Comment (saemideluxe) [reply lib/system.nim]: Okay, I pushed an according change. I am not sure if my changes in `compiler/sem.nim` are sound, please check.

File: compiler/sem.nim [hunk 2]
```diff
@@ -671,8 +671,9 @@ proc defaultNodeField(c: PContext, a: PNode, aTyp: PType, checkDefault: bool): P
     if child != nil:
       let node = newNode(nkIntLit)
       node.intVal = toInt64(lengthOrd(c.graph.config, aTypSkip))
-      result = semExpr(c, newTree(nkCall, newSymNode(getSysSym(c.graph, a.info, "arrayWith"), a.info),
-              semExprWithType(c, child),
+      let typeNode = newNode(nkSym)
```
Comment (metagn) [inline compiler/sem.nim]: You should be able to make an `nkType` node with a `typedesc` type as is done [here](https://github.com/nim-lang/Nim/blob/46bb47a444bd377860d832fc1c62b262343f36a2/compiler/sem.nim#L608-L613) or [here](https://github.com/nim-lang/Nim/blob/46bb47a444bd377860d832fc1c62b262343f36a2/compiler/semobjconstr.nim#L183-L188) instead. Putting it into a helper proc i.e. `newTypeDescNode(c, typ, info)` would be appreciated as well.

Edit: Or just simply reusing `semdata.makeTypeDesc` and doing something like `let typeNode = newNodeIT(nkType, a.info, makeTypeDesc(c, aTypSkip[1]))`.

**Review by metagn — APPROVED** [review]
Maybe @ringabout has some input?

**Review by ringabout — APPROVED** [review]

**Comment by saemideluxe** [comment]
Any chance that this will be merged for the next release?
