### PR TITLE
fix compound inheritance penalty

### LINKED ISSUE #24773: Ambiguous call on resolveable overloads
### Nim Version

2.0, devel

### Description

```nim
type
  A {.inheritable.} = object
  B = object of A
  C = object of B

proc add(v: B, v2: A) =
  discard

proc add(v: A, v2: A) =
  discard

var x: C
var y: B

add(x, y)
```

In the above hierarchy, the `v: B` overload is clearly better (since the other arguments are all equal to start with) - [C++](https://godbolt.org/z/MdfManbE9) can do the right thing here - seems like nim should also be able to do so.

### Current Output

```text
testit.nim(15, 4) Error: ambiguous call; both testit.add(v: B, v2: A) [proc declared in testit.nim(6, 6)] and testit.add(v: A, v2: A) [proc declared in testit.nim(9, 6)] match for: (C, B)
```

### Expected Output

```text
compiles
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
fixes #24773

`c.inheritancePenalty` is supposed to be used for the entire match, but in these places the inheritance penalty of a single argument overrides the entire match penalty. The `+ ord(c.inheritancePenalty < 0)` is copied from other places that use the same idiom, the intent is that the existing penalty changes from -1 to 0 first to mark that it participates in inheritance before adding the inheritance depth.

### CODE REVIEW

File: compiler/sigmatch.nim [hunk 1]
```diff
@@ -1540,12 +1540,14 @@ proc typeRel(c: var TCandidate, f, aOrig: PType,
         reduceToBase(a)
     if effectiveArgType.kind == tyObject:
       if sameObjectTypes(f, effectiveArgType):
-        c.inheritancePenalty = if tfFinal in f.flags: -1 else: 0
+        if tfFinal notin f.flags:
+          inc c.inheritancePenalty, 0 + ord(c.inheritancePenalty < 0)
```
Comment (Araq) [inline compiler/sigmatch.nim]:
```suggestion
          inc c.inheritancePenalty, ord(c.inheritancePenalty < 0)
```
