### PR TITLE
fix #8305 #7808 #10285 #11061 + other bugs with type mismatch error msgs

### LINKED ISSUE #7808: Passing tuple with proc leads to confusing errors
```nim
proc foo(x: (string, proc ())) =
  x[1]()

foo(
  ("foobar", proc () = echo("Hello!"))
)
```

```
/private/tmp/aporia/a8.nim(4, 4) Error: type mismatch: got <tuple of (string, proc (){.gcsafe, locks: 0.})>
but expected one of:
proc foo(x: (string, proc ()))
expression: foo(("foobar", proc () = echo(["Hello!"])))
```

Adding ``{.closure.}`` to the proc fixes it but there is no way you can figure that out from this error.

In addition, this {.closure.} isn't a problem when the procedure isn't in a tuple so it's doubly confusing. I guess there is some rules here to implicitly add the {.closure.} which do not apply when the proc is in a tuple. It would be nice if they did (as adding ``{.closure.}`` to ``=>`` isn't easy, I suppose alternatively we could add that pragma to all ``=>`` procedures).

### LINKED ISSUE #8305: type mismatch error drops crucial pragma info when there's only 1 argument
on a type mismatch error, nim does an optimization when there's only 1 argument, however that optimization drops information that's useful for debugging such as pragmas, without which it's impossible to grok why the mismatch occurred. It's a bug.

```nim
#[ 
 ]#

proc fun*(s: string): string {.  .} = discard

when true:
  proc foo*[T, S](op: proc (x: T): S {. cdecl .}): auto = 1
  echo foo(fun)

else:
  proc foo*[T, S](a:int, op: proc (x: T): S {. cdecl .}): auto = 1
  echo foo(0, fun)

```

```
Error: type mismatch: got <proc (s: string): string{.noSideEffect, gcsafe, locks: 0.}>
but expected one of:
proc foo[T, S](op: proc (x: T): S): auto

expression: foo(fun)
    echo foo(fun)
```
This error msg is useless, it misses the fact that 1st argument is "proc (x: T): S{.cdecl.}" (ie, misses pragma)

Now replace code above with "when false" (which adds a dummy argument, which causes nim error messages to show extended error message)
```
Error: type mismatch: got <int literal(0), proc (s: string): string{.noSideEffect, gcsafe, locks: 0.}>
but expected one of:
proc foo[T, S](a: int; op: proc (x: T): S): auto
  first type mismatch at position: 2
  required type: proc (x: T): S{.cdecl.}
  but expression 'fun' is of type: proc (s: string): string{.noSideEffect, gcsafe, locks: 0.}

expression: foo(0, fun)
    echo foo(0, fun)
```

* furthermore, it may not be abvious which pragma mis-maches cause the error (eg .noSideEffect, gcsafe, locks: 0 are fine, but cdecl is not), but that's a separate issue : ideally compiler would tell you that.

### LINKED ISSUE #10285: Function signature don't match when inside seq/array/openarray
When storing functions inside seqs/arrays the arguments no longer match to the function signature:

```nimrod
proc takesFunc(f: proc (x: int) {.gcsafe, locks: 0.}) =
  echo "takes single Func"

proc takesFuncs(fs: openarray[proc (x: int) {.gcsafe, locks: 0.}]) =
  echo "takes multiple Func"

takesFunc(proc (x: int) {.gcsafe, locks: 0.} = echo x)         # works
takesFuncs([proc (x: int) {.gcsafe, locks: 0.} = echo x])      # fails
```

Error:

```
test.nim(8, 11) Error: type mismatch: got <array[0..0, proc (x: int){.gcsafe, locks: 0.}]>
but expected one of: 
proc takesFuncs(fs: openArray[proc (x: int) {.gcsafe, locks: 0.}])

expression: takesFuncs([proc (x: int) {.gcsafe, locks: 0.} = echo [x]])
```

As far as I can tell, the compiler expects exactly the type it got, and from the `takesFunc` case I would conclude that the function I try to pass in is compatible in general. Interestingly it is possible to convince the compiler that the type is correct by adding an explicit conversion to the elements:

```nimrod
# that works, despite looking like a noop conversion
takesFuncs([(proc (x: int) {.gcsafe, locks: 0.})(proc (x: int) {.gcsafe, locks: 0.} = echo x)])
```

It doesn't seem to be relevant whether its a seq / array / openarray. I haven't checked if the problem extends to other generic types.

Tested with latest devel.

### LINKED ISSUE #11061: Type mismatch error "first type mismatch at" points to wrong argument/position
The type mismatch error can point to the wrong arguments/positions.

### Example

```nim
type
  A = object of RootObj
  B = object of A

proc f(b: B) = discard
proc f(a: A) = discard

f(A(), "extra")
```

### Current Output
```
test.nim(8, 2) Error: type mismatch: got <A, string>
but expected one of: 
proc f(b: B)
  first type mismatch at position: 1
  required type: B
  but expression 'A()' is of type: A
proc f(a: A)
  first type mismatch at position: 1
  required type: A
  but expression 'A()' is of type: A

expression: f(A(), "extra")
```

### Expected Output

Maybe the same output one gets when replacing the expression to `f(B(), "extra")` which gives:

```
test.nim(8, 2) Error: type mismatch: got <B, string>
but expected one of: 
proc f(b: B)
proc f(a: A)

expression: f(B(), "extra")
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-04-13
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: f6ad071a46a2bec57db453343d8d8b75d3d16ac2
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by timotheecour**
## bugs fixed
* fix #11061
* fix #8305
* fix #7808 
* fix #10285 (was closed but issue remains as mentioned by @bluenote10 in https://github.com/nim-lang/Nim/issues/7808#issuecomment-508905750 : the err msg doesn't show that `closure` is missing; this PR fixes that)

## additional bugs fixed
fix other bugs with type mismatch error msgs that I didn't create separate issues for, eg:
*  fix https://github.com/nim-lang/Nim/issues/11061#issuecomment-508969796 sigmatch gets confused with param/arg position after varargs
* fix https://github.com/nim-lang/Nim/issues/11061#issuecomment-508970046 err msg incorrectly says something is immutable
* fix https://github.com/nim-lang/Nim/issues/11061#issuecomment-508970465 err msg doesn't tell you what when wrong when an argument is bound twice
  (`errCannotBindXTwice` was removed because of #3836, but with this PR the error message now tells you `named param already provided: a0` instead of nothing)

## other
* now shows more informative diagnostic error, eg the mismatched parameter name; handy when there are lots of arguments to identify it by name
* the previous approach was using X vs -X for `firstMismatch` depending on whether there was a type mismatch (>0) or other kind of mismatch (<0), but there was a number of issues associated with this approach; this PR cleans up the logic via a new `MismatchKind` enum which reports the kind of mismatch, resulting in simpler code and bug fixes
* previous code had no way to properly deal with matches occuring after a varargs param since there was only 1 position recorded ; after this PR we have both `arg` (argument position) and `formal` (pointing to formal param)

## implementation notes for reviewers
* the semantics of matching/nonmatching don't change, only the error messages can change (in particular `csMatch` is set exactly as before PR)
* `unmatchedVarParam, mutabilityProblem` were removed, redundant after the refactor
* `m.firstMismatch.kind` can be set more than once times inside `matchesAux`; its done this way to cover all cases with the simplest possible logic (the previous logic was setting `firstMismatch` in many places but lots of cases were missing / wrong)

### CODE REVIEW

File: tests/errmsgs/tsigmatch.nim [hunk 1]
```diff
@@ -0,0 +1,222 @@
...
+  first type mismatch at position: 1
+  required type for a1: float
+  but expression 'default(Mystring)' is of type: Mystring
+
+expression: fun1(default(Mystring), "asdf")
+'''
+  errormsg: "type mismatch"
+"""
+
+
```
Comment (narimiran) [inline tests/errmsgs/tsigmatch.nim]: Why are these 60 empty lines needed?

File: tests/concepts/t3330.nim [hunk 2]
```diff
@@ -2,48 +2,62 @@ discard """
...
+t3330.nim(63, 8) template/generic instantiation of `add` from here
+t3330.nim(70, 6) Foo: 'bar.value' cannot be assigned to
+t3330.nim(63, 8) template/generic instantiation of `add` from here
+t3330.nim(71, 6) Foo: 'bar.x' cannot be assigned to
 
 expression: test(bar)'''
 """
 
+# Note: the test currently fails because the candidates are presented in
+# different order on travis with `NIM_COMPILE_TO_CPP=false CPU=i386`;
```
Comment (narimiran) [inline tests/concepts/t3330.nim]: If this fails only on 32-bit, why not disable it only for that? The syntax is: `disabled: "32bit"`.

File: tests/errmsgs/tsigmatch.nim (hunk 1 above)
Comment (timotheecour) [reply tests/errmsgs/tsigmatch.nim]: fixed

File: tests/concepts/t3330.nim (hunk 2 above)
Comment (timotheecour) [reply tests/concepts/t3330.nim]: fixed; note that the test was disabled before this PR

**Comment by timotheecour** [comment]
PTAL
