### PR TITLE
Fixes #5738

### LINKED ISSUE #5738: async + threads:on + globals = error
```nim
import asyncdispatch
var s = "hi"
proc foo() {.async.} = echo s
```
```
nim c --threads:on test.nim
```
```
test.nim(3, 12) template/generic instantiation from here
Projects/nim/lib/pure/asyncmacro.nim(31, 8) Error: 'cb' is not GC-safe as it accesses 'nameIterVar' which is a global using GC'ed memory
```
Originated from https://github.com/dom96/jester/issues/110

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

File: lib/pure/asyncmacro.nim [hunk 1]
```diff
@@ -38,7 +38,8 @@ template createCb(retFutureSym, iteratorNameSym,
                     "`nil` Future?"
             raise newException(AssertionError, msg % name)
         else:
-          next.callback = cb
+          {.gcsafe.}:
+            next.callback = cast[proc() {.closure, gcsafe.}](cb)
```
Comment (dom96) [inline lib/pure/asyncmacro.nim]: Can we use a type conversion instead of a cast here?

File: tests/async/tasync_gcsafe.nim [hunk 2]
```diff
@@ -0,0 +1,36 @@
+discard """
```
Comment (dom96) [inline tests/async/tasync_gcsafe.nim]: yay, tests!

**Comment by yglukhov** [comment]
Rebased and squashed.
