### PR TITLE
close #15563  add testcase

### LINKED ISSUE #15563: adding varargs data generates invalid C code with ARC
My project uses varargs to pass parameters. 
https://github.com/planety/prologue/blob/d588f926ae0d103978aecb6038b1c92f2d4659a6/src/prologue/core/application.nim#L368

```nim
proc hello(x: varargs[string]) =
  var T: seq[string]
  T.add x

hello("123")
```

produces

```
C:\Users\blue\nimcache\test_d\@mtest.nim.c: In function 'hello__wyfMTSuarUNjz0a04AFgKg':
C:\Users\blue\nimcache\test_d\@mtest.nim.c:139:2: error: conversion to non-scalar type requested
  colontmpD_ = (tyVarargs__L2x01mN3UeI6VC9aO5FxndQ)0;
  ^~~~~~~~~~
C:\Users\blue\nimcache\test_d\@mtest.nim.c:141:13: error: incompatible types when assigning to type 'tyVarargs__L2x01mN3UeI6VC9aO5FxndQ' {aka 'struct <anonymous>'} from type 'int'
  colontmpD_ = 0;
             ^
C:\Users\blue\nimcache\test_d\@mtest.nim.c:143:68: error: incompatible type for argument 3 of 'eq___UryAk6fTVSBdD4nIV2wHUA'
  eq___UryAk6fTVSBdD4nIV2wHUA(colontmpD_.Field0, colontmpD_.Field1, x, xLen_0);
                                                                    ^
C:\Users\blue\nimcache\test_d\@mtest.nim.c:110:128: note: expected 'tyVarargs__L2x01mN3UeI6VC9aO5FxndQ' {aka 'struct <anonymous>'} but argument is of type 'NimStringV2 *' {aka 'struct NimStringV2 *'}
 N_LIB_PRIVATE N_NIMCALL(void, eq___UryAk6fTVSBdD4nIV2wHUA)(NimStringV2* dest, NI destLen_0, tyVarargs__L2x01mN3UeI6VC9aO5FxndQ src, NI srcLen_0) {
                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~

Error: execution of an external compiler program 'gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields   -IC:\Users\blue\.choosenim\toolchains\nim-#devel\lib -ID:\QQPCMgr\Desktop\prologue -o C:\Users\blue\nimcache\test_d\@mtest.nim.c.o C:\Users\blue\nimcache\test_d\@mtest.nim.c' failed with exit code: 1
```

Nim version
```
D:\QQPCMgr\Desktop\prologue>nim -v
Nim Compiler Version 1.3.7 [Windows: amd64]
Compiled at 2020-10-07
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
close #15563

### CODE REVIEW

File: tests/typerel/t15563.nim [hunk 1]
```diff
@@ -0,0 +1,9 @@
+discard """
+  matrix: "--gc:refc; --gc: arc"
+"""
+
+proc hello(x: varargs[string]) =
+  var T: seq[string]
+  T.add x
```
Comment (timotheecour) [inline tests/typerel/t15563.nim]: nit:
```suggestion
  var s: seq[string]
  s.add x
```

File: tests/typerel/t15563.nim [hunk 2]
```diff
@@ -0,0 +1,9 @@
+discard """
+  matrix: "--gc:refc; --gc: arc"
+"""
+
+proc hello(x: varargs[string]) =
+  var s: seq[string]
+  s.add x
+
+hello("123")
```
Comment (timotheecour) [inline tests/typerel/t15563.nim]:
```nim
template main =
  proc hello(x: varargs[string]): seq[string] =
    var s: seq[string]
    s.add x
    s

  doAssert hello() == @[]
  doAssert hello("a1") == @["a1"]
  doAssert hello("a1", "a2") == @["a1", "a2"]

static: main()
main()
```
and move to something like `tests/system/tvarargs.nim` (so more tests can be added there) 

plus the usual `targets: "c js"`

Comment (xflywind) [reply tests/typerel/t15563.nim:9]: js + arc?

**Review by timotheecour — APPROVED** [review]
