### PR TITLE
fixes #7906, array and openarray arg vs. ptr/ref generic

### LINKED ISSUE #7906: array and openarray arg vs. ptr/ref generic polymorphic issue
the battle against #4799 continues. and this is the next obstacle.

```Nim
type
  Fruit[T] = ref object of RootObj
    color: T
  Apple[T] = ref object of Fruit[T]
  Banana[T] = ref object of Fruit[T]

proc testArray[T](x: array[3, Fruit[T]]) =
  for c in x:
    echo c.color

proc testOpenArray[T](x: openArray[Fruit[T]]) =
  for c in x:
    echo c.color

var a = Fruit[int](color: 1)
var b = Apple[int](color: 2)
var c = Banana[int](color: 3)
testArray([a, b, c]) #ok
testArray([b, c, a]) #failed

testOpenArray([a, b, c]) #ok
testOpenArray([b, c, a]) #failed

testOpenArray(@[a, b, c]) #ok
testOpenArray(@[b, c, a]) #ok

type
  Vehicle[T] = object of RootObj
    color: T
  Car[T] = object of Vehicle[T]
  Bike[T] = object of Vehicle[T]

proc testArray[T](x: array[3, ptr Vehicle[T]]) =
  for c in x:
    echo c.color

proc testOpenArray[T](x: openArray[ptr Vehicle[T]]) =
  for c in x:
    echo c.color

var u = Vehicle[int](color: 1)
var v = Bike[int](color: 2)
var w = Car[int](color: 3)
testArray([u.addr, v.addr, w.addr]) #failed
testArray([w.addr, u.addr, v.addr]) #failed

testOpenArray([u.addr, v.addr, w.addr]) #failed
testOpenArray([w.addr, u.addr, v.addr]) #failed

testOpenArray(@[u.addr, v.addr, w.addr]) #failed
testOpenArray(@[w.addr, u.addr, v.addr]) #failed
```

### PR DESCRIPTION
**Pull request by jangko**

### CODE REVIEW

File: compiler/sem.nim [hunk 1]
```diff
@@ -158,11 +158,12 @@ proc commonType*(x, y: PType): PType =
...
       b = b.lastSon.skipTypes({tyGenericInst})
     if a.kind == tyObject and b.kind == tyObject:
-      result = commonSuperclass(a, b, k)
+      result = commonSuperclass(a, b)
       # this will trigger an error later:
       if result.isNil or result == a: return x
       if result == b: return y
-      if k != tyNone:
+      # bug #7906
+      if k != tyNone and x.kind != tyGenericInst:
```
Comment (Araq) [inline compiler/sem.nim]: Please add a comment here explaining your reasoning. It seems fishy, why is ``tyGenericInst`` harmful here?

Comment (jangko) [reply compiler/sem.nim]: I will add a comment.

the reason is
```Nim
type
   GenericObject[T] = object
   GenericRefObject[T] = ref object
   
var a = GenericRefObject[int]          # tyGenericInst of ref object
var b = new(ref GenericObject[int]) # tyRef of tyGenericInst
```

from user perpective, a and b should be not too different, but inside the compiler, they are two different types.

so, if it already a tyGenericInst of ref object, it would be wrong to add more tyRef in front of it.
additional tyRef in the next compiler phase will generate ill formed AST.
