### PR TITLE
fix #7405 and #8195

### LINKED ISSUE #7405: `Error: cannot 'importc' variable at compile time` shows wrong context
BUG:D20180323T174016 

```
nim c -r bugs/t01_error_context.nim
lib/system/sysio.nim(351, 20) Error: cannot 'importc' variable at compile time
```
the error doesn't show the right context where error occurs.

```nim
import strutils, sequtils

# replace this with some path to some text file
const input = "/Users/timothee/git_clone/LPATHBench/agraph"

proc testCTFE():auto=
    let lines0 = toSeq(input.lines)
    # let lines0 = input.lines()
    echo lines0
    result = 0

const res1=testCTFE()
# let res1=testCTFE()
echo $("res1", res1)
```

In D the error is more helpful and points to user source code, eg:

```
void main(){
  import core.stdc.stdio;
  enum s=printf("hello\n");
}
```
```
dmd -o- main.d
main.d(3): Error: printf cannot be interpreted at compile time, because it has no available source code
```

### PR DESCRIPTION
**Pull request by timotheecour**
fix https://github.com/nim-lang/Nim/issues/8195

fix https://github.com/nim-lang/Nim/issues/7405

NOTE: to fix these I ran:
```
(cd $git_clone_D/nim/Nim/  && ./koch temp)
$git_clone_D/nim/Nim/bin/nim_temp c -r test.nim
```
then looked at the stack trace to see a good insertion point for adding context via pushInfoContext that wasn't already covered by pushInfoContext

EG:
after this:
```
 $git_clone_D/nim/Nim/bin/nim_temp c -r bugs/t01_error_context.nim
/Users/timothee/git_clone/nim/timn/bugs/t01_error_context.nim(14, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim/lib/system/sysio.nim(351, 20) Error: cannot 'importc' variable at compile time
    var p: pointer = fopen(filename, FormatOpen[mode])
                     ^
$git_clone_D/nim/Nim/bin/nim_temp c -r bugs/t30_nocontext_request_echo.nim
/Users/timothee/git_clone/nim/timn/bugs/t30_nocontext_request_echo.nim(18, 6) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim/lib/system.nim(2816, 32) Error: request to generate code for .compileTime proc: $
    proc echo*(x: varargs[typed, `$`]) {.magic: "Echo", tags: [WriteIOEffect],
                                 ^
```

before this, the "template/generic instantiation from here" was skipped

### CODE REVIEW

**Comment by timotheecour** [comment]
sent out https://github.com/nim-lang/Nim/pull/8198

File: compiler/ccgstmts.nim [hunk 1]
```diff
@@ -1147,5 +1147,7 @@ proc genAsgn(p: BProc, e: PNode, fastAsgn: bool) =
 
 proc genStmts(p: BProc, t: PNode) =
   var a: TLoc
+  pushInfoContext(p.config, t.info)
```
Comment (Araq) [inline compiler/ccgstmts.nim]: The backend should not be concerned with the quality of error messages.

File: compiler/semstmts.nim [hunk 2]
```diff
@@ -1890,4 +1890,6 @@ proc semStmtList(c: PContext, n: PNode, flags: TExprFlags): PNode =
 
 proc semStmt(c: PContext, n: PNode): PNode =
   # now: simply an alias:
+  pushInfoContext(c.config, n.info)
```
Comment (Araq) [inline compiler/semstmts.nim]: Dubious, and likely to produce tons of false positives. The error message is **Instantiation from here** and ``semStmt`` doesn't perform any instantiations. Instantiation here refers to template/macro or generic expansions.

Comment (timotheecour) [reply compiler/semstmts.nim]: how about renaming "template/generic instantiation from her" to something more general, eg "obtained from her" ?

> Dubious, and likely to produce tons of false positives

do you have such an example where it produces a ton of false positives?

**Comment by timotheecour** [comment]
@Araq this PR actually solves a real problem which is that no context is shown in some cases (cf bug reports), leading to compiler messages that are really hard to interpret as there's nothing pointing to where the error came from.

IMO benefits (fixing the above mentioned issues) outweigh the cons (more context being shown)

If you really don't want this to be the default, would you be OK if I make these changes  controlled by a new `hint[extendedContext]` ?

File: compiler/ccgstmts.nim (hunk 1 above)
Comment (timotheecour) [reply compiler/ccgstmts.nim]: without this, I get one of the 2 bugs I mentioned

**Comment by Araq** [comment]
Yes, the problem is very real, but the solution is bad, sorry. We need a real fix.

File: compiler/semstmts.nim (hunk 2 above)
Comment (Araq) [reply compiler/semstmts.nim]: Well the tests are not even green with this PR, for example tests/parallel/tgc_unsafe2.nim fails.

Comment (timotheecour) [reply compiler/semstmts.nim]: right, they would be green if I make these context subject to a `hint[extendedContext]` (which would be off by default); If you're ok with that I'll go ahead and make that change.

**Comment by timotheecour** [comment]
@Araq would you accept a modified PR that would add these `pushInfoContext` only when a new `hint[extendedContext]` is on ?
I keep running into these issues and this PR helps a lot debugging such issues. It'd be a nop by default without that hint

**Comment by Araq** [comment]
> would you accept a modified PR that would add these pushInfoContext only when a new hint[extendedContext] is on ?

Meh, alright.

**Comment by timotheecour** [comment]
@Araq PTAL

File: compiler/lineinfos.nim [hunk 3]
```diff
@@ -158,27 +163,15 @@ type
...
-                                         warnProveField, warnProveIndex,
-                                         warnGcUnsafe,
-                                         hintPath,
-                                         hintDependency,
-                                         hintCodeBegin, hintCodeEnd,
-                                         hintSource, hintStackTrace,
-                                         hintGlobalVar, hintGCStats},
-    {low(TNoteKind)..high(TNoteKind)} - {hintStackTrace, warnUninit},
-    {low(TNoteKind)..high(TNoteKind)}]
+  NotesVerbosity* = (proc(): array[0..3, TNoteKinds] =
```
Comment (timotheecour) [inline compiler/lineinfos.nim]: this change makes code more DRY, avoiding future bugs caused by someone putting a hint in 1 block of NotesVerbosity but not another block of NotesVerbosity

File: compiler/ccgstmts.nim [hunk 4]
```diff
@@ -1147,5 +1147,11 @@ proc genAsgn(p: BProc, e: PNode, fastAsgn: bool) =
 
 proc genStmts(p: BProc, t: PNode) =
   var a: TLoc
+
+  let isPush = hintExtendedContext in p.config.notes
+  if isPush: pushInfoContext(p.config, t.info)
+  defer:
```
Comment (timotheecour) [inline compiler/ccgstmts.nim]: using defer for correctness; see also https://forum.nim-lang.org/t/4022: "are nim exceptions "zero cost" (on error-free execution) ? (if so, `defer` should be used more)"

**Comment by timotheecour** [comment]
NOTE: the travis failure seems unrelated (cf https://github.com/nim-lang/Nim/issues/8226 flaky test: Failure: reOutputsDiffer in tests/parallel/tsysspawn.nim I just filed)

File: compiler/lineinfos.nim (hunk 3 above)
Comment (Araq) [reply compiler/lineinfos.nim]: That's obscure code, use named const sets to avoid the DRY violation.

File: compiler/semexprs.nim [hunk 5]
```diff
@@ -907,6 +907,10 @@ proc buildEchoStmt(c: PContext, n: PNode): PNode =
   result = semExpr(c, result)
 
 proc semExprNoType(c: PContext, n: PNode): PNode =
+  let isPush = hintExtendedContext in c.config.notes
+  if isPush: pushInfoContext(c.config, n.info)
+  defer:
```
Comment (Araq) [inline compiler/semexprs.nim]: Don't use ``defer`` nor try finally. This code cannot throw anyway.

File: compiler/ccgstmts.nim (hunk 4 above)
Comment (Araq) [reply compiler/ccgstmts.nim]: Don't use ``defer`` nor try finally. This code cannot throw anyway.

File: compiler/lineinfos.nim (hunk 3 above)
Comment (timotheecour) [reply compiler/lineinfos.nim]: made the anonymous proc not anonymous (although i preferred the anonymous proc version, it's a common idiom n in C++, D, javascript + others, to avoid adding symbols in scope)

File: compiler/ccgstmts.nim (hunk 4 above)
Comment (timotheecour) [reply compiler/ccgstmts.nim]: done, although I preferred the `defer` way (assuming `defer` gets fixed cf https://github.com/nim-lang/Nim/issues/8254), it's more robust in case future code changes make that code throw

File: compiler/semexprs.nim (hunk 5 above)
Comment (timotheecour) [reply compiler/semexprs.nim]: done (ditto)

**Comment by timotheecour** [comment]
@Araq  PTAL

File: compiler/lineinfos.nim (hunk 3 above)
Comment (Araq) [reply compiler/lineinfos.nim]: That's not at all what I asked you to do. I asked you to use Nim's set feature. You know, that thing that C++, D, JS lack.
