### PR TITLE
fix #17960: honor `matrix` also for `action: compile, action: reject`

### LINKED ISSUE #17960: testament: `matrix` silently ignored when `action` is specified
### Example
add tests/misc/tfoo6.nim:
```nim
discard """
  action: reject
  matrix: "--nonexistant"
"""

echo "bar"
```

`XDG_CONFIG_HOME= nim r --lib:lib testament/testament.nim --verbose r tests/misc/tfoo6.nim`

### Current Output
non-sensical, and doesn't mention the cmd in matrix:
```
executing: /Users/timothee/.nimble/bin/nim c --hints:on -d:testing --clearNimblePath --nimblePath:build/deps/pkgs --nimCache:nimcache/tests/misc/tfoo6.nim_4a8a08f09d37b73795649038408b5f33 tests/misc/tfoo6.nim
FAIL: tests/misc/tfoo6.nim c
Test "tests/misc/tfoo6.nim" in category "misc"
Failure: reFilesDiffer
Expected:
tests/misc/tfoo6.nim

Gotten:

...
```

### Expected Output
executing should show the cmd in matrix

### Additional Information
1.5.1 98c29c01eb91a0c6ce7da09380a272eebe6bca6f

(why is testament so buggy? ...)

### PR DESCRIPTION
**Pull request by timotheecour**
fix https://github.com/nim-lang/Nim/issues/17960

### CODE REVIEW

File: testament/testament.nim [hunk 1]
```diff
@@ -478,14 +478,16 @@ proc equalModuloLastNewline(a, b: string): bool =
...
                     target: TTarget, nimcache: string, extraOptions = "") =
   test.startTime = epochTime()
+  template callNimCompilerImpl(): untyped = 
+    # xxx this used to also pass: `--stdout --hint:Path:off`, but was done inconsistently
+    # with other branches
+    callNimCompiler(expected.getCmd, test.name, test.options, nimcache, target, extraOptions)
   case expected.action
   of actionCompile:
-    var given = callNimCompiler(expected.getCmd, test.name, test.options, nimcache, target,
-          extraOptions = " --stdout --hint[Path]:off --hint[Processing]:off")
```
Comment (timotheecour) [inline testament/testament.nim:484]: note that tests/config.nims already contains `hint("Processing", off)` so `--hint[Processing]:off"` wasn't needed here;

as for `--stdout --hint[Path]:off` they were inconsistently used (not used in actionRun nor actionReject)
