### PR TITLE
many bugfixes for js

### LINKED ISSUE #11331: JS Backend generates invalid assignments on LHS
Don't have a small example, but hopefully someone can repro:

```nim
game.particleAdjustments[id].sizeDelta += -sizeDiff
```

generates:

```js
(Tmp15 = (Tmp14 = HEX5BHEX5D_346700(game_366300.sim.particles, id_370614), Tmp14)[0][Tmp14[1]].size, Tmp15) = addInt(Tmp15, size_diff_370622);
```

Expanding it does fix the problem:

```nim
game.particleAdjustments[id].sizeDelta =
      game.particleAdjustments[id].sizeDelta - sizeDiff
```

### LINKED ISSUE #11783: regression(0.18): nim js gives runtime error when appending to an uninitialized string
nim js gives runtime error when appending an uninitialized string to an uninitialized string.
This works fine with `nim c` but gives runtime error with `nim js`:

reduced from a crash in a more complex program:

### Example
```nim
proc fun(): string =
  # return "" # this removes the crash
  discard

var ret: string
# ret = ""  # this removes the crash
ret.add fun()
```

### Current Output
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t0549.js:39
if (ret_311230[0] != null) { ret_311230[0] = (ret_311230[0]).concat(fun_311214()); } else { ret_311230[0] = fun_311214().slice(); };
                                                                                                                        ^

TypeError: Cannot read property 'slice' of null
    at Object.<anonymous> (/Users/timothee/git_clone/nim/timn/tests/nim/all/t0549.js:39:121)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

### Expected Output
should work (and print nothing), just like it does with `nim c`

### Additional Information
* Your Nim version (output of `nim -v`).
latest devel f50e4500c257e3d57654f5230db75042da233d24

same bug with 0.19, 0.20

doesn't crash with 0.18, hence marking it as a regression, but not super sure 0.18 was 100% correct either, eg, i can make 0.18 crash by adding `  echo ret` (but doesn't crash if i precede by `ret.add "asdf"`)

### LINKED ISSUE #12256: [JS] `reset` sets value types to null
```nim
var x: bool

{.emit: ["console.log(", x, ")"].}

reset x

{.emit: ["console.log(", x, ")"].}
```
Console log:
> false
> null

Stable 1.0

### LINKED ISSUE #12672: [JS] Invalid codegen
### Example
```nim
proc foo =
  var x: seq[seq[int]]
  for row in x.mitems:
    let i = 1
    inc row[i-1]

foo()
```

### Current Output
```
Uncaught SyntaxError: Invalid left-hand side in assignment

(Tmp4 = row_42215[row_42215_Idx][chckIndx(subInt(i_42217, 1), 0, row_42215[row_42215_Idx].length+0-1)-0], Tmp4) = addInt(Tmp4, 1);
```

### Expected Output
No errors

### Additional Information

```
$ nim -v
Nim Compiler Version 1.0.2
```

### LINKED ISSUE #13966: Failing seq/table operation JS codegen
### Example
```nim
import tables

var t: Table[int8, array[int8, seq[tuple[]]]]

t[0] = default(array[int8, seq[tuple[]]])
t[0][0].add ()
```

### Current Output
```
SyntaxError: invalid increment/decrement operand
```

### Additional Information

* Nim 1.2.0

### LINKED ISSUE #14087: Bad JS codegen when adding to string field in object in seq with complex expression for index
This case is very specific. Changing `object` to `ref object` gives the same error, using a seq instead of a string doesn't error.

### Example
```nim
type Obj = object
  str: string

var s = @[Obj(str: "abc"), Obj(str: "def")]
# works:
s[1].str.add("ghi")
# fails:
s[s.len - 1].str.add("ghi")
# fails:
s[^1].str.add("ghi")
# fails, s.high or high(s) doesn't matter:
s[s.high].str.add("ghi")

let slen = s.len
# fails:
s[slen - 1].str.add("ghi")

let shigh = s.high
# works
s[shigh].str.add("ghi")
```

### Current Output
```
if (s_622017[0][(s_622017[0] != null ? (s_622017[0].length-1) : -1)].str != null) { Tmp1 = (Tmp1).concat(makeNimstrLit("ghi")); } else { Tmp1 = makeNimstrLit("ghi"); };
                                                                                                  ^

TypeError: Cannot read property 'concat' of undefined
```

Relevant codegen:

```js
var Tmp1;
var s_622017 = [[{str: makeNimstrLit("abc")}, {str: makeNimstrLit("def")}]];
if (s_622017[0][(s_622017[0] != null ? (s_622017[0].length-1) : -1)].str != null) { Tmp1 = (Tmp1).concat(makeNimstrLit("ghi")); } else { Tmp1 = makeNimstrLit("ghi"); };
```

### Expected Output
`s` becomes `@[Obj(str: "abc"), Obj(str: "defghi")]`

### Possible Solution

* [Relevant codegen branch](https://github.com/nim-lang/Nim/blob/eca8f1d79f712613437918e397f7abb58bc29515/compiler/jsgen.nim#L1895), `maybeMakeTemp` is the culprit, a temporary variable shouldn't be created

```
$ nim -v
Nim Compiler Version 1.2.0
```

### LINKED ISSUE #14117: JS: adding to uninitialized seq/string inside object variant is no-op
### Example
```nim
type
  A = object
    case kind: bool
    of true:
      sons: seq[int]
    else: discard

var a = A(kind: true)
echo a.sons.len
a.sons.add(1)
echo a.sons.len
```

### Current Output
```
0
0
```

### Expected Output
```
0
1
```

### Additional Information

* This breaks `parsesql` for JS (with #14095) and probably way more standard library modules that I haven't tested yet.

```
$ nim -v
Nim Compiler Version 1.2.0
```

### LINKED ISSUE #14123: JS temp generation with array/seq/string issues
JS is failing at doing operations when modifying `var T`s, because of incorrectly generated and used temp variables.

* `inc`/`+=` failures (`dec` probably fails the same way):
  - [x] #11331
  - [x] #12672

* Seq/string addition:
  - [x] #13966 (the main problem in this issue is arrays with negative index but it would still break because a temp is being wrongly used)
  - [x] #14087
  - [x] #14117

* `reset`, probably related, works with #14158:
  - [x] #12256

All of these use an index with a subscript first (except #14117, that accesses a field) then do the add/inc operation. They all assign to temp variables instead of a field/index, like `if (null != (Temp1 = arr[i-1], Temp1)) { Temp1 += 1 } else { Temp1 = 1 }` when it should be `if (null != (Temp1 = i-1, Temp1)) { arr[Temp1] += 1 } else { arr[Temp1] = 1 }` if anything.

From my deduction, the issue is either in [`maybeMakeTemp` in jsgen](https://github.com/nim-lang/Nim/blob/eca8f1d79f712613437918e397f7abb58bc29515/compiler/jsgen.nim#L445), or the subscripts like `arr[i-1]` are not being recognized as `var T` by the compiler.

### LINKED ISSUE #14153: JS: no bound checks at top level
This only happens on top level, it works inside `proc main` or similar. `--boundchecks:on` doesn't help.

### Example
```nim
var x = @[1, 2, 3]

echo x[5]
x[5] = 8
```

### Current Output
```nim
undefined
```

### Expected Output
```
Error: unhandled exception: index 5 not in 0 .. 2 [IndexError]
```

### Possible Solution

* [jsgen.genArrayAccess](https://github.com/nim-lang/Nim/blob/3b5a504692495324afdb7c20159122e66100f767/compiler/jsgen.nim#L1171) checks for `optBoundsCheck in p.options` which evaluates to false at top level and true anywhere else.
* Workaround:
```nim
var x = @[1, 2, 3]

proc main =
  echo x[5]
  x[5] = 8
main()
```

```
$ nim -v
Nim Compiler Version 1.3.1 [Windows: amd64]

git hash: 3b5a504692495324afdb7c20159122e66100f767
```

### PR DESCRIPTION
**Pull request by metagn**
fixes #12672, fixes #14153, closes #14123, closes #11331, fixes #11783, fixes #13966, fixes #14087, fixes #14117, closes #12256.

mostly fixes the fact that it was allowed to assign to newly created temp variables. additionally attempts to get rid of null initialized seqs/strings (though they might pop up here and there); this simplifies a lot of things and makes code size smaller. even if null seqs/strings pop up here and there it's still better than all those bugs existing.

Kind of sloppy (I was supposed to remove `checkOverflowInt` and `checkOverflowInt64` but I kept them), if you don't like an unused change or formatting issue please say so.

### CODE REVIEW

File: tests/js/tjshello.nim [hunk 1]
```diff
@@ -1,4 +1,5 @@
 discard """
+  cmd: "nim $target $options --stackTrace:off --lineTrace:off $file"
```
Comment (hlaaftana) [inline tests/js/tjshello.nim:2]: If you're wondering why this is here, fixing top level compile options resulted in stack traces actually getting enabled at top level which bumps this above 1000 characters. I didn't disable stack traces for system includes at first, which generated 20000 characters, but I fixed that and now it's just below 4000. So we have to explicitly disable it.

**Comment by timotheecour** [comment]
also fixed https://github.com/nim-lang/Nim/issues/11788 !

**Comment by dom96** [comment]
holy wow, thanks @hlaaftana!
