### PR TITLE
forbid casting to bare unchecked array

### LINKED ISSUE #11180: Casting a pointer to an UncheckedArray[uint8] crashes the compiler
When you `cast[UncheckedArray[uint8]]`, the compiler doesn't report an error, it just crashes.

### Example
```nim
var
  rawMem = alloc0(20)
  byteUA = cast[UncheckedArray[uint8]](rawMem)

byteUA[3] = 12'u8
echo byteUA[4]
```

### Current Output
```
Error: internal error: genAssignment: tyUncheckedArray
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

### Expected Output
The compiler should report that you need to cast to a `ptr UncheckedArray[uint8]`, not `UncheckedArray[uint8]`

### Additional Information
```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-05-02
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```
related issue: #9403

### PR DESCRIPTION
**Pull request by krux02**
fix #11180

### CODE REVIEW

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -164,7 +164,7 @@ proc isCastable(conf: ConfigRef; dst, src: PType): bool =
   #                       tySequence, tyPointer, tyNil, tyOpenArray,
   #                       tyProc, tySet, tyEnum, tyBool, tyChar}
   let src = src.skipTypes(tyUserTypeClasses)
-  if skipTypes(dst, abstractInst-{tyOpenArray}).kind == tyOpenArray:
+  if skipTypes(dst, abstractInst-{tyOpenArray}).kind in {tyOpenArray}:
```
Comment (narimiran) [inline compiler/semexprs.nim]: Nitpick: Since you decided to go for another solution (compared to the initial one which had `{tyOpenArray, tyUncheckedArray}`), this change can be reverted to keep things clean.

Comment (krux02) [reply compiler/semexprs.nim]: sure

**Comment by krux02** [comment]
Test failure: ``tests/ccgbugs/xua9578.nim(3, 25) Error: invalid type: 'UncheckedArray[mytype]' in this context: 'proc (x: var UncheckedArray[mytype])' for proc``

That file doesn't exist. At least not on my distribution of Nim.

**Comment by krux02** [comment]
yay github
```
fatal: unable to access 'https://github.com/nim-lang/csources/': Failed to connect to github.com port 443: Timed out
```

**Comment by krux02** [comment]
test failure is yet another github timeout

**Comment by mratsim** [comment]
Only Mac C failed but Mac C++ and Linux C worked on Travis, so I think we can go ahead.
