### PR TITLE
fix posix.mq_receive compilation with cpp backend

### LINKED ISSUE #20709: posix.mq_receive does not compile with cpp backend
### What happened?

This file compiles and runs with the C backend, but does not compile with the CPP backend.

```nim
# mqfail.nim
import posix

type Message = object
  value: int

const MQ_PATH = "/top_level_file"
const MQ_PRIORITY = 170
const MQ_MESSAGE_SIZE = sizeof(Message)

when isMainModule:
  var mqd_a: posix.MqAttr = MqAttr(mq_maxmsg: 10, mq_msgsize: clong(MQ_MESSAGE_SIZE))
  let writable: posix.Mqd = posix.mq_open(
    MQ_PATH,
    posix.O_CREAT or posix.O_WRONLY or posix.O_NONBLOCK,
    posix.S_IRWXU,
    addr(mqd_a)
  )
  let readable: posix.Mqd = posix.mq_open(
      MQ_PATH,
      posix.O_RDONLY or posix.O_NONBLOCK,
      posix.S_IRWXU,
      addr(mqd_a)
    )
  
  let sent: Message = Message(value: 88)
  block:
    let success: int = writable.mq_send(
      cast[cstring](sent.addr),
      MQ_MESSAGE_SIZE,
      MQ_PRIORITY
    )
    let error: cint = errno
    if success != 0:
      echo "Failed to write " &
        $sizeof(Message) &
        " bytes to mqd_t file descriptor " &
        $writable &
        " because failed with reason: " &
        $strerror(error)
    assert success == 0, $success
    
  block:
    var buffer: Message
    var priority: int
    let bytesRead: int = readable.mq_receive(cast[cstring](buffer.addr), MQ_MESSAGE_SIZE, priority)
    echo $buffer
    assert buffer == sent
    assert bytesRead == MQ_MESSAGE_SIZE
```

This code passes with compiled with `c` backend
```console
 nim c --verbosity:0 --run mqfail.nim
(value: 88)
```
but fails to compile with `cpp` backend:
```console
$ nim cpp --verbosity:0 --run mqfail.nim
/home/user/.cache/nim/mqfail_d/@mmqfail.nim.cpp: In function ‘void NimMainModule()’:
/home/user/.cache/nim/mqfail_d/@mmqfail.nim.cpp:319:104: error: cannot convert ‘NI*’ {aka ‘long int*’} to ‘unsigned int*’
  319 | il_18))), ((NI)8), (&priority__mqfail_19));
      |                    ~^~~~~~~~~~~~~~~~~~~~~
      |                     |
      |                     NI* {aka long int*}

In file included from /home/user/.cache/nim/mqfail_d/@mmqfail.nim.cpp:8:
/usr/include/mqueue.h:67:21: note:   initializing argument 4 of ‘ssize_t mq_receive(mqd_t, char*, size_t, unsigned int*)’
   67 |       unsigned int *__msg_prio) __nonnull ((2));
      |       ~~~~~~~~~~~~~~^~~~~~~~~~
Error: execution of an external compiler program 'g++ -c -std=gnu++17 -funsigned-char  -w -fmax-errors=3 -fpermissive -pthread   -I/home/user/n5m/lib -I/home/user -o /home/user/.cache/nim/mqfail_d/@mmqfail.nim.cpp.o /home/user/.cache/nim/mqfail_d/@mmqfail.nim.cpp' failed with exit code: 1
```

### Nim Version

f8b5464f31834bf97e7f9023644e255f2e9b6485
```console
$ nim -v
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-10-31
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: f8b5464f31834bf97e7f9023644e255f2e9b6485
active boot switches: -d:release
```

### Current Standard Output Logs

```shell
/home/user/.cache/nim/mqfail_d/@mmqfail.nim.cpp: In function ‘void NimMainModule()’:
/home/user/.cache/nim/mqfail_d/@mmqfail.nim.cpp:319:104: error: cannot convert ‘NI*’ {aka ‘long int*’} to ‘unsigned int*’
  319 | il_18))), ((NI)8), (&priority__mqfail_19));
      |                    ~^~~~~~~~~~~~~~~~~~~~~
      |                     |
      |                     NI* {aka long int*}

In file included from /home/user/.cache/nim/mqfail_d/@mmqfail.nim.cpp:8:
/usr/include/mqueue.h:67:21: note:   initializing argument 4 of ‘ssize_t mq_receive(mqd_t, char*, size_t, unsigned int*)’
   67 |       unsigned int *__msg_prio) __nonnull ((2));
      |       ~~~~~~~~~~~~~~^~~~~~~~~~
Error: execution of an external compiler program 'g++ -c -std=gnu++17 -funsigned-char  -w -fmax-errors=3 -fpermissive -pthread   -I/home/user/n5m/lib -I/home/user -o /home/user/.cache/nim/mqfail_d/@mmqfail.nim.cpp.o /home/user/.cache/nim/mqfail_d/@mmqfail.nim.cpp' failed with exit code: 1
```

### Expected Standard Output Logs

```shell
(value: 88)
```

### Possible Solution

Make Nim's `posix` module compatible with the types defined in [`mqueue.h`](https://man7.org/linux/man-pages/man3/mq_receive.3.html):
```c
ssize_t mq_receive(mqd_t mqdes, char *msg_ptr,
                   size_t msg_len, unsigned int *msg_prio);
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by n5m**
FIx #20709

### CODE REVIEW

**Comment by Araq** [comment]
Don't write a test case via a runnable **example**.

**Comment by Araq** [comment]
Fails on OSX which doesn't have this feature, apparently.

File: lib/posix/posix.nim [hunk 1]
```diff
@@ -249,26 +249,102 @@ proc setlocale*(a1: cint, a2: cstring): cstring {.
...
-    varargs, importc, header: "<mqueue.h>".}
-  proc mq_receive*(a1: Mqd, a2: cstring, a3: int, a4: var int): int {.
+when not (defined(nintendoswitch) or defined(macos) or defined(macosx)):
+  proc mq_notify*(mqdes: Mqd, event: ptr SigEvent): cint {.
     importc, header: "<mqueue.h>".}
-  proc mq_send*(a1: Mqd, a2: cstring, a3: int, a4: int): cint {.
+
+  proc mq_open*(name: cstring, flags: cint): Mqd {.
+    varargs, importc, header: "<mqueue.h>".} =
+    runnableExamples:
```
Comment (Araq) [inline lib/posix/posix.nim]: Remove this, the posix.nim wrapper doesn't need runnable examples, one is on his own when importing posix.nim.
