### PR TITLE
Ref #18177 - lbgc.so.5.0 on OpenBSD 6.9

### LINKED ISSUE #18177: regression: tests/dll/client.nim fails on openbsd: could not load: libgc.so.4.0
### Example
https://azusa.runners.sr.ht/logs/519617/test/log

### Current Output
```
[31mFAIL: [36mtests/dll/client.nim c  --gc:boehm --threads:on             [34m ( 0.82 sec)[0m

Category: dllName: tests/dll/client.nim c  --gc:boehm --threads:onAction: runResult: reExitcodesDiffer-------- Expected -------exitcode: 0--------- Given  --------exitcode: 1
Output:could not load: libgc.so.4.0(compile with -d:nimDebugDlOpen for more information)<br class="Apple-interchange-newline">

```

could not load: libgc.so.4.0

### Additional Information
1.5.1 a77360da5bad40d22e942cdd5cb9614c3548bf34
https://gist.github.com/timotheecour/734653f1aab6021f87d1e742a6257dcb
my guess is the fix in https://github.com/nim-lang/Nim/pull/12134 was fragile, and the version should be picked in a more robust way /cc @euantorano

### PR DESCRIPTION
**Pull request by euantorano**
Fixes #18177 - OpenBSD 6.9 has `libgc.so.5.0` rather than 4.0.

### CODE REVIEW

**Comment by euantorano** [comment]
Note: I've not tried this syntax before, so hopefully it's correct...

File: lib/system.nim [hunk 1]
```diff
@@ -1146,7 +1146,7 @@ when defined(boehmgc):
   elif defined(macosx):
     const boehmLib = "libgc.dylib"
   elif defined(openbsd):
-    const boehmLib = "libgc.so.4.0"
+    const boehmLib = "libgc.so.(4|5).0"
```
Comment (timotheecour) [inline lib/system.nim:1149]: while this may work, it still sounds fragile when the v6 is introduced in future; could the following work, `const boehmLib = "libgc.so"` ? (assuming it's a symlink pointing to "latest") ?

Comment (euantorano) [reply lib/system.nim:1149]: Unfortunately OpenBSD doesn't create such a symlink I don't believe.

**Review by timotheecour — APPROVED** [review]

File: lib/system.nim (hunk 1 above)
Comment (timotheecour) [reply lib/system.nim:1149]: ok, LGTM; but maybe we should support `const boehmLib = "libgc.so.*.0"` ?

**Comment by timotheecour** [comment]
@Araq i'm merging this because nim CI for pulls (not pull_requests, which don't run openbsd unless PR author makes a PR against a branch originating from nim-lang, which only members can do) is red; this change seems correct but waiting for CI won't help because openbsd isn't run (for same rason); after this is merged, let's see if it makes nim CI (for non-PRs) green again

**Comment by timotheecour** [comment]
after this PR i see a different, unrelated failure in openbsd: https://builds.sr.ht/~araq/job/519693

```
#519693] 2021/06/04 22:47:02 Booting image openbsd/latest (default) on port 22850
[#519693] 2021/06/04 22:47:07 Waiting for guest to settle
[#519693] 2021/06/04 22:47:26 Sending tasks
[#519693] 2021/06/04 22:47:26 Sending build environment
[#519693] 2021/06/04 22:47:27 Installing packages
Warning: Permanently added '[localhost]:22850' (ECDSA) to the list of known hosts.
quirks-3.633 signed on 2021-06-04T14:08:56Z
New and changed readme(s):
	/usr/local/share/doc/pkg-readmes/sdl2
--- +node-12.16.1p1 -------------------
You may wish to add /usr/local/lib/node_modules/npm/man to /etc/man.conf
You may wish to add /usr/local/lib/node_modules/sshpk/man to /etc/man.conf
[#519693] 2021/06/04 22:47:59 Cloning repositories
Cloning into 'Nim'...
error: 773 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
[#519693] 2021/06/04 22:48:23 Failed to clone repository. If this a private repository, make sure you've added a suitable SSH key.
[#519693] 2021/06/04 22:48:23 https://man.sr.ht/builds.sr.ht/private-repos.md
[#519693] 2021/06/04 22:48:23 Processing post-failed triggers...
[#519693] 2021/06/04 22:48:24 Sent build results email to Andreas Rumpf <rumpf_a@web.de>
[#519693] 2021/06/04 22:48:24 Sending webhook...
[#519693] 2021/06/04 22:48:25 Webhook response: 200
[#519693] 2021/06/04 22:48:25 Sent build status to GitHub
[#519693] 2021/06/04 22:48:25 Build failed.
[#519693] 2021/06/04 22:48:25 The build environment will be kept alive for 10 minutes.
[#519693] 2021/06/04 22:48:25 To log in with SSH and examine it, use the following command:
[#519693] 2021/06/04 22:48:25 
[#519693] 2021/06/04 22:48:25 	ssh -t builds@azusa.runners.sr.ht connect 519693
[#519693] 2021/06/04 22:48:25 
[#519693] 2021/06/04 22:48:25 After logging in, the deadline is increased to your remaining build time.
[#519693] 2021/06/04 22:58:25 Deadline elapsed. Terminating build environment.
[#519693] 2021/06/04 22:58:25 Error: git clone: exit status 128
```

**Comment by euantorano** [comment]
Is this repeatable? It looks like it failed to clone the repository for some reason - this wouldn’t be an issue with Nim as such.

**Comment by timotheecour** [comment]
> Is this repeatable? It looks like it failed to clone the repository for some reason - this wouldn’t be an issue with Nim as such.

I think i've seen it before with bsd pipelines; if this keeps happening we should use `gitutils.retryCall`
