### PR TITLE
fixes #25008; Compiler internal error with static overload

### LINKED ISSUE #25008: Compiler internal error `compiler/vmgen.nim(1771, 23)` with `static` overload
### Nim Version

```
Nim Compiler Version 2.2.4 [Linux: amd64]
Compiled at 2025-06-18
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: f7145dd26efeeeb6eeae6fff649db244d81b212d
active boot switches: -d:release
```

```
Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2025-06-18
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: aba93615105b8243b95c534f2d7c39aa69ace997
active boot switches: -d:release
```

### Description

```nim
proc g(_: static bool) = discard
proc g(_: int) = discard
proc y() = g((; let k = 0; k))
```

### Current Output

```text
Error: internal error: /tmp/nim/compiler/vmgen.nim(1771, 23)
No stack traceback available
To create a stacktrace, rerun compilation with './koch temp c <file>', see https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler for details
```

### Expected Output

```text
No internal error
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #25008

It seems that `semOverloadedCall` evaluates the same node twice using `tryConstExpr` in order for `efExplain` to print all the diagnostic output. The problem is that `tryConstExpr` has side effects, i.e., it changes the slot index of variables after VM execution.

### CODE REVIEW

File: compiler/sem.nim [hunk 1]
```diff
@@ -346,6 +346,19 @@ proc fixupTypeAfterEval(c: PContext, evaluated, eOrig: PNode; producedClosure: v
...
 
+proc resetEvalPosition(n: PNode) =
+  # resets the eval position of variables because `tryConstExpr` may be
+  # called multiple times on the same node
+  case n.kind
+  of {nkNone..nkNilLit}-{nkSym}:
+    discard
+  of nkSym:
+    if n.sym.kind in {skVar, skLet} and sfGlobal notin n.sym.flags:
+      n.sym.position = 0
```
Comment (Araq) [inline compiler/sem.nim:357]: What is `position` even used for? By the VM?
