### PR TITLE
fix #15939 #15464 #16169 #16226 VM now supports `addr(mystring[ind])` (index + index assignment)

### LINKED ISSUE #15464: VM fails when returning `var char` via `var string`
### Example
```nim
# fine:
proc access(s: var seq[char], i: int): var char = s[i]

static:
  var s = @['a', 'b', 'c']
  access(s, 2) = '!'
  discard access(s, 0)

# fails:
proc access(s: var string, i: int): var char = s[i]

static:
  var s = "abc"
  access(s, 2) = '!'
  discard access(s, 0)
```

### Current Output
```
(14, 9) Error: attempt to access a nil address
if you comment out the previous one:
(15, 17) Error: attempt to access a nil address kind: rkInt
```

### Expected Output
compiles

### Additional Information
* possibly related: #14339, #14420

```
$ nim -v
Nim Compiler Version 1.3.5
(latest devel)
```

### LINKED ISSUE #15939: addr(s[ind]) doesn't work in VM with string|cstring: attempt to access a nil address kind: rkInt
After this PR https://github.com/nim-lang/Nim/pull/15461 is merged
```nim
const foo = "foo"

proc proc1(s: var string) =
  if s[^1] notin {'a'..'z'}:
    s = ""

proc proc2(f: string): string =
  result = f
  proc1(result)

const bar = proc2(foo)
echo bar
```
Gave errors:
```
....
stack trace: (most recent call last)
D:\QQPCmgr\Desktop\Nim\test.nim(13, 18)
D:\QQPCmgr\Desktop\Nim\test.nim(11, 8) proc2
D:\QQPCmgr\Desktop\Nim\test.nim(6, 7) proc1
D:\QQPCmgr\Desktop\Nim\test.nim(6, 7) Error: attempt to access a nil address kind: rkInt
```

Or you can reproduce this error with other versions of Nim
```nim
const foo = "foo"

proc `[]`*(s: var string; i: BackwardsIndex): var char {.inline.} = s[s.len - int(i)]

proc proc1(s: var string) =
  if s[^1] notin {'a'..'z'}:
    s = ""

proc proc2(f: string): string =
  result = f
  proc1(result)

const bar = proc2(foo)
echo bar
```

### LINKED ISSUE #16169: important_packages argparse breaks CI
important_packages argparse breaks CI

### Current Output
```
  FAIL: argparse C
  Test "argparse" in category "nimble-packages-1"
  Failure: reBuildFailed
  package test failed
  $ nimble test
    Verifying dependencies for argparse@1.0.0
    Compiling /Users/runner/work/Nim/Nim/pkgstemp/argparse/tests/test1 (from package argparse) using c backend
  stack trace: (most recent call last)
  /Users/runner/work/Nim/Nim/pkgstemp/argparse/src/argparse.nim(93, 12) domkParser
  /Users/runner/work/Nim/Nim/pkgstemp/argparse/src/argparse/backend.nim(760, 27) generateDefs
  /Users/runner/work/Nim/Nim/pkgstemp/argparse/src/argparse/backend.nim(689, 19) helpProcDef
  /Users/runner/work/Nim/Nim/pkgstemp/argparse/src/argparse/backend.nim(685, 9) getHelpText
  /Users/runner/work/Nim/Nim/lib/pure/strutils.nim(2873, 11) stripLineEnd
  /Users/runner/work/Nim/Nim/pkgstemp/argparse/tests/test1.nim(25, 7) template/generic instantiation of `suite` from here
  /Users/runner/work/Nim/Nim/pkgstemp/argparse/tests/test1.nim(26, 8) template/generic instantiation of `test` from here
  /Users/runner/work/Nim/Nim/pkgstemp/argparse/tests/test1.nim(27, 22) template/generic instantiation of `newParser` from here
  /Users/runner/work/Nim/Nim/lib/pure/strutils.nim(2873, 11) Error: attempt to access a nil address kind: rkInt
         Tip: 1 messages have been suppressed, use --verbose to show them.
       Error: Execution failed with exit code 256
          ... Command: /Users/runner/work/Nim/Nim/bin/nim c --noNimblePath -d:NimblePkgVersion=1.0.0 --hints:off -r --path:. /Users/runner/work/Nim/Nim/pkgstemp/argparse/tests/test1
  
  PASS: arraymancer C                                                (35.84 sec)

```

### Additional Information

in unrelated PR https://github.com/nim-lang/Nim/pull/16166/checks?check_run_id=1466652591

### LINKED ISSUE #16226: Error: attempt to access a nil address kind: rkInt (caused by result[^1])
New bug in devel: `result[^1]` breaks inside macros but `result[len-1]` work.

### Example
```nim
import macros

proc bar(): string =
  result = "hi"
  echo result[^1]

macro foo() =
  echo bar()

foo()
```

### Current Output

```
stack trace: (most recent call last)
C:\p\jsony\tests\foo.nim(8, 11) foo
C:\p\jsony\tests\foo.nim(5, 14) bar
C:\p\jsony\tests\foo.nim(10, 4) template/generic instantiation of `foo` from here
C:\p\jsony\tests\foo.nim(5, 14) Error: attempt to access a nil address kind: rkInt
```

### Expected Output

during compile:
```
i
hi
```

### Possible Solution

Worked on 1.4.0, breaks now.

This `result[result.len-1]` works  though:

```nim
import macros

proc bar(): string =
  result = "hi"
  echo result[result.len-1]

macro foo() =
  echo bar()

foo()
```

```
nim c -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2020-12-02
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release```

### PR DESCRIPTION
**Pull request by timotheecour**
fix #15464
fix #15939
fix #16169
fix #16226
see test: tests/misc/taddr.nim

## future work after this is merged:
- [x] re-enable argparse (refs dd5405c)

### CODE REVIEW

**Comment by timotheecour** [comment]
friendly ping @araq now that CI is broken (https://github.com/nim-lang/Nim/issues/16169)

File: compiler/vm.nim [hunk 1]
```diff
@@ -677,6 +679,23 @@ proc rawExecute(c: PCtx, start: int, tos: PStackFrame): TFullReg =
...
+    of opcLdStrIdxAddr:
+      # a = addr(b[c]); similar to opcLdArrAddr
+      decodeBC(rkNode)
+      if regs[rc].intVal > high(int):
+        stackTrace(c, tos, pc, formatErrorIndexBound(regs[rc].intVal, high(int)))
+      let idx = regs[rc].intVal.int
+      let s = regs[rb].node.strVal.addr # or `byaddr`
+      if idx <% s[].len:
+         # `makePtrType` not accessible from vm.nim
+        let typ = newType(tyPtr, nextId c.idgen, c.module.owner)
```
Comment (Araq) [inline compiler/vm.nim:691]: This is not required, values in the VM are untyped. ``node.typ`` can remain nil.

Comment (timotheecour) [reply compiler/vm.nim:691]: it's needed otherwise `assert typ != nil` fails in `maybeHandlePtr`.
And that assert is needed, the type is propagated to `derefPtrToReg` and used there in `case typ.kind`.

Comment (Araq) [reply compiler/vm.nim:691]: That indicates serious design problems with ``derefPtrToReg`` but we can improve this later.
