### PR TITLE
pseudorandom probing for hash collision

### LINKED ISSUE #13393: Slow insertion of uint in Tables and Sets Collections depending on the value
A long time ago I noticed that the Tables and Sets collections took a long time to add values ​​and I decided to search further.

So, I noticed that the problem was: the higher a significant bit in an integer, the slower the insertion of a value will be.

Using uint32, entering values ​​with the lowest 16 bits is 14 times faster than entering values ​​with the highest 16 bits.

Using uint64 the situation is more serious. Entering values ​​with the low 32 bits is about 256 times faster than entering values ​​with the highest 32 bits, this for the Sets collection. For Tables collection, the difference increases to 348 times.

I will not put sample code, because I created a github repository with the problem, where it is possible to see the codes used and even a quick solution using seqs and sort, as well as code using similar collections in other languages ​​to do the same work that show a greater consistency in execution time.

It is a problem related or equal to the one treated here: [11764](https://github.com/nim-lang/Nim/issues/11764)

### Example and Current Output
Visit this link [https://github.com/rockcavera/nim-problem](https://github.com/rockcavera/nim-problem)

### Expected Output
A less significant difference is expected between the addition of values, that is, closer execution times, the same occurs in other languages.

### Possible Solution

* I can't say if the problem is with the designer adopted for the collections or a wrong choice of hash... I didn't delve into the current code of the collections due to lack of time.

### Additional Information

* The test was carried out on several Nim versions since before the release of 1.0 and they all have the same problem

### PR DESCRIPTION
**Pull request by timotheecour**
(EDIT: see followup https://github.com/nim-lang/Nim/pull/13440 with a "best of both worlds" approach and additional benchmarks) 

performance benchmark shows this can work, see below.

* fixes #13393
* fixes analog problem for bitsets
* fixes collisions for small floats (as explained in #13410, small floats would previously all have the same hash value, causing major slowdowns)
* completely different approach from #13410 but some parts of that PR are still relevant and useful even in combination with this PR

this investigates pseudorandom probing for hash collisions, as done in python.
The main idea is to use this recursion in `nextTry`:
```nim
perturb = perturb shr PERTURB_SHIFT # with perturb initialized to hash(key) before recursion
h = ((5*h) + 1 + perturb) and maxHash
```
instead of linear probing:
`h = (h + 1) and maxHash`

## consequences
* at least similar (within 10%) performance in all cases I tested compared to before PR (see #13410 for test cases)
* no catastrophic slowdowns (issue #13393) which were causing 100x-1000x (and likely unbounded) slowdowns
* hash key computation is now only required to produce good hash keys modulo 64 bit, not modulo n bits for n<64, since the whole hash key is used in probing sequence. That means hash key computation for primitive types can remain fast.
* for theory on justification of `((5*h) + 1 + perturb) and maxHash`, refer to python internal docs (cpython implementation of dictionaries) or other material which explains pretty well; the basic idea is that `((5*h) + 1 + perturb) and maxHash` recursion is affected by all bits of hash(key) (so that different hashkeys will not follow exactly the same path and clustering is avoided), and if a free slot still isn't found by the time perturb = 0, then the recursion becomes `h = ((5*h) + 1) and maxHash` which is guaranteed to visit each slot exactly once. The visit occurs in pseudorandom order, and that order depends on the full 64 bit hash(key).
* should be resilient to adversarial attacks (but can still be made more resilient with adding an (unguessable) fixed seed in the recursion, eg: `h = ((5*h) + 1 + perturb + seed) and maxHash` with seed initialized upoon application startup)

## consequence for deletion
* there is no way to adapt `Algorithm R (Deletion with linear probing)` from Knuth Volume 3 to our new recursion, since multiple unrelated paths can pass through a given index (unlike with linear probing `h = (h + 1) and maxHash` or even `h = (h + c) and maxHash` with c constant). So I instead keep track of deletions, and adapt the table implementation as follows:
* each cell is in 3 states: empty (hash=0), deleted(h=-1), valid(h!=0, h!=1)
* rehash when count(empty) < 1/3 numSlots

## note: 
this is a slight modification from python: I'm using `translateBits` which results in large (eg 30x) speedups in cases like #13393 at 0 extra cost; it makes the hash influence the path earlier on. python doesn't do `translateBits` and does suffer from #13393 (although not catastrophically (eg 1000x) thanks to `PERTURB_SHIFT`) as well as you can see with:
```nim
  n = 10_000_000
  t={}
  for i in range(n):
    key = i << 32 # 68 sec 
    # key = i # 3 sec
    t[key] = str(key)
```
but with this PR, this isn't the case.

## TODO for future PR's
- [ ] do same with:
strtabs
compiler/astalgo.nim
compiler/treetab.nim
system/cellsets
(I don't quite understand why we have so many Table variants; seems to me like at least some of them could be reusing existing ones)

- [ ] investigate whether following refinement would improve speed even further:
```nim
  if iteration < thres: # eg thres = 4
    result = (h + 1) and maxHash
  else:
    perturb = perturb shr PERTURB_SHIFT
    result = ((5*h) + 1 + perturb) and maxHash
  iteration.inc
```
with the idea being to improve cache locality unless we're detecting we're in a dense collision cluster, in which case we're switching to pseudo-random probing to break out of the cluster. In some benchmarks at least this led to some speedups, but it'd require a bit of code refactoring to avoid introducing code duplication. So this is left for future work.

- [ ] [EDIT] OrderedTable.del is O(n) (including before PR), because every `del` rebuilds whole table; instead, using tombstones as introduced in this PR would make it O(1)

- [ ] [EDIT] support `dec`, and having zero counts, in `CountTable` using tombstones
- [ ] SharedTable should auto-init, like other tables; it should have some iterators, and simply ask user to protect access via `withLock` instead of current API which is rather cumbersome and unlike other tables

### CODE REVIEW

File: lib/pure/collections/hashcommon.nim [hunk 1]
```diff
@@ -20,32 +20,66 @@ when not defined(nimHasDefault):
 
 # hcode for real keys cannot be zero.  hcode==0 signifies an empty slot.  These
 # two procs retain clarity of that encoding without the space cost of an enum.
-proc isEmpty(hcode: Hash): bool {.inline.} =
-  result = hcode == 0
+when false:
+  proc isEmpty(hcode: Hash): bool {.inline.} =
+    result = hcode == 0
```
Comment (krux02) [inline lib/pure/collections/hashcommon.nim]: please don't add dead code.

File: lib/pure/collections/hashcommon.nim [hunk 2]
```diff
@@ -20,32 +20,66 @@ when not defined(nimHasDefault):
...
+  result = hcode != 0 and hcode != deletedMarker # SPEED: could improve w bit magic
 
 proc isFilled(hcode: Hash): bool {.inline.} =
   result = hcode != 0
 
-proc nextTry(h, maxHash: Hash): Hash {.inline.} =
-  result = (h + 1) and maxHash
+
+proc nextTry(h, maxHash: Hash, perturb: var Hash): Hash {.inline.} =
+  # TODO: shouldn't perturb be unsigned?
```
Comment (krux02) [inline lib/pure/collections/hashcommon.nim]: `Hash` should be unsigend. That is a design mistake of nim.

File: lib/pure/collections/hashcommon.nim [hunk 3]
```diff
@@ -20,32 +20,66 @@ when not defined(nimHasDefault):
...
-    if t.data[h].hcode == hc and t.data[h].key == key:
-      return h
-    h = nextTry(h, maxHash(t))
-  result = -1 - h # < 0 => MISSING; insert idx = -1 - result
+  var perturb = hc
+  var deletedIndex = -1
+  while true:
+    if isFilledValid(t.data[h].hcode):
+      # Compare hc THEN key with boolean short circuit. This makes the common case
+      # zero ==key's for missing (e.g.inserts) and exactly one ==key for present.
```
Comment (krux02) [inline lib/pure/collections/hashcommon.nim:84]: What is `==key`, Please use common English in the comments.

File: lib/pure/collections/hashcommon.nim [hunk 4]
```diff
@@ -20,32 +20,66 @@ when not defined(nimHasDefault):
...
 proc isFilled(hcode: Hash): bool {.inline.} =
   result = hcode != 0
 
-proc nextTry(h, maxHash: Hash): Hash {.inline.} =
-  result = (h + 1) and maxHash
+
+proc nextTry(h, maxHash: Hash, perturb: var Hash): Hash {.inline.} =
+  # TODO: shouldn't perturb be unsigned?
+  const PERTURB_SHIFT = 5
+  # SPEED IMPROVE
```
Comment (krux02) [inline lib/pure/collections/hashcommon.nim]: The technical term is `performance`. I know you make this mistake regularly, so please write it down.

File: lib/pure/collections/hashcommon.nim [hunk 5]
```diff
@@ -20,32 +20,66 @@ when not defined(nimHasDefault):
...
-proc isEmpty(hcode: Hash): bool {.inline.} =
-  result = hcode == 0
+when false:
+  proc isEmpty(hcode: Hash): bool {.inline.} =
+    result = hcode == 0
+
+const freeMarker = 0
+const deletedMarker = -1
+
+proc isFilledValid(hcode: Hash): bool {.inline.} =
```
Comment (krux02) [inline lib/pure/collections/hashcommon.nim]: How about `isFilledAndValid`. "filled valid" has a very different meaning.

**Review by krux02 — COMMENTED** [review]
Here is some superficial comments on your WIP status. Feel free to ignore it if you don't like it.

File: lib/pure/collections/hashcommon.nim (hunk 2 above)
Comment (timotheecour) [reply lib/pure/collections/hashcommon.nim]: I agree. Only question is whether this can be fixed wo breaking too much code.

Comment (krux02) [reply lib/pure/collections/hashcommon.nim]: Well, custom overloads of `hash` that use `int` instead of the type `Hash` won't work anymore.

Comment (Araq) [reply lib/pure/collections/hashcommon.nim]: Exactly, we won't change it.

File: lib/pure/collections/hashcommon.nim (hunk 3 above)
Comment (timotheecour) [reply lib/pure/collections/hashcommon.nim:84]: that's a pre-existing comment

File: lib/pure/collections/hashcommon.nim (hunk 5 above)
Comment (timotheecour) [reply lib/pure/collections/hashcommon.nim]: done

File: lib/pure/collections/hashcommon.nim (hunk 1 above)
Comment (timotheecour) [reply lib/pure/collections/hashcommon.nim]: i wouldn't have in the final version of this WIP; anyways, done

File: lib/pure/collections/hashcommon.nim [hunk 6]
```diff
@@ -18,34 +18,76 @@ when not defined(nimHasDefault):
...
+proc isFilledAndValid(hcode: Hash): bool {.inline.} =
+  result = hcode != 0 and hcode != deletedMarker
+    # performance: we could use bit magic if needed
 
 proc isFilled(hcode: Hash): bool {.inline.} =
   result = hcode != 0
 
-proc nextTry(h, maxHash: Hash): Hash {.inline.} =
-  result = (h + 1) and maxHash
+type UHash* = uint
```
Comment (Araq) [inline lib/pure/collections/hashcommon.nim]: Why export this?

File: lib/pure/testutils.nim [hunk 7]
```diff
@@ -0,0 +1,13 @@
+## utilities to help writing tests
```
Comment (Araq) [inline lib/pure/testutils.nim]: Add least add an "experimental API" remark, or "Internal API".

Comment (timotheecour) [reply lib/pure/testutils.nim]: done

File: lib/pure/collections/hashcommon.nim (hunk 6 above)
Comment (timotheecour) [reply lib/pure/collections/hashcommon.nim]: fixed

**Comment by Araq** [comment]
Superb work, should also be backported, if possible. @narimiran

File: lib/pure/testutils.nim [hunk 8]
```diff
@@ -0,0 +1,15 @@
...
+
+proc sortedPairs*[T](t: T): auto =
+  ## helps when writing tests involving tables in a way that's robust to
+  ## changes in hashing functions / table implementation.
+  toSeq(t.pairs).sorted
+
+template sortedItems*(t: untyped): untyped =
+  ## helps when writing tests involving tables in a way that's robust to
+  ## changes in hashing functions / table implementation.
+  sorted(toSeq(t))
```
Comment (Clyybber) [inline lib/pure/testutils.nim:15]: IMO you should use `toSeq(t.pairs).sorted` and `sorted(toSeq(t))` in the tests instead.
This is bloat IMO and saves like 5 keypresses.

File: lib/pure/collections/intsets.nim [hunk 9]
```diff
@@ -46,30 +46,43 @@ type
...
+  # FACTOR with hashcommon.mustRehash
   assert(length > counter)
   result = (length * 2 < counter * 3) or (length - counter < 4)
 
-proc nextTry(h, maxHash: Hash): Hash {.inline.} =
-  result = ((5 * h) + 1) and maxHash
+proc mustRehash2[T](t: T): bool {.inline.} =
+  # FACTOR with hashcommon.mustRehash2
+  let counter2 = t.counter + t.countDeleted
+  result = mustRehash(t.max + 1, counter2)
```
Comment (Clyybber) [inline lib/pure/collections/intsets.nim]: Why can't mustRehash be replaced with this?

File: lib/pure/collections/hashcommon.nim [hunk 10]
```diff
@@ -18,34 +18,77 @@ when not defined(nimHasDefault):
...
+  perturb = perturb shr PERTURB_SHIFT
 
 proc mustRehash(length, counter: int): bool {.inline.} =
   assert(length > counter)
-  result = (length * 2 < counter * 3) or (length - counter < 4)
+  result = (length * 2 < counter * 3) or (length - counter < 4) # synchronize with `rightSize`
+
+proc mustRehash2[T](t: T): bool {.inline.} =
+  let counter2 = t.counter + t.countDeleted
+  result = mustRehash(t.dataLen, counter2)
```
Comment (Clyybber) [inline lib/pure/collections/hashcommon.nim]: Ditto here

**Review by Clyybber — COMMENTED** [review]
Awesome!

File: lib/pure/collections/hashcommon.nim (hunk 10 above)
Comment (timotheecour) [reply lib/pure/collections/hashcommon.nim]: done

File: lib/pure/collections/intsets.nim (hunk 9 above)
Comment (timotheecour) [reply lib/pure/collections/intsets.nim]: done (led to a few complications which is why I wanted to defer this to subsequent PRs, but I've done it now)

File: lib/pure/testutils.nim (hunk 8 above)
Comment (timotheecour) [reply lib/pure/testutils.nim:15]: * sure, it's a bit "bloaty" but it simplifies tests (stdlib + other ones) and encourages using it instead of flaky alternatives like `$t` which has caused much churn in the past every time hashes/table/etc algorithms change; I've had to fix a number of tests (both in stdlib + in other nimble packages) to make those tests non-flaky; this simplifies this.
* it's a bit more than 5 keypresses in practice: `toSeq(t.pairs).sorted` prevents using method call syntax/UFCS (because pairs is an iterator), but `sortedPairs` can be used with MCS; in practice tests often involve expressions to define `t` so having MCS makes the test simpler to read/write
* (also, needs 1 import `testutils` instead of 2 `imports algorithm, sequtils` to achive this goal, but that argument is very minor; in practice `import sequtils` can cause further issues (see nim issues involving import sequtils except toSeq) so it'd in fact be `imports algorithm`, from sequtils import toSeq`; etc)

all those complications I've had in the past when fixing test led me to the simple realization that testutils is needed.

Comment (Clyybber) [reply lib/pure/testutils.nim:15]: As I said, use `toSeq(....` in the tests.
Even if it is only "a bit bloaty" it is too much to be a candidate for adding to the stdlib IMO.
All the other arguments are very minor, as you admit yourself.
Please remove this module.

File: lib/pure/collections/intsets.nim (hunk 9 above)
Comment (Clyybber) [reply lib/pure/collections/intsets.nim]: Thanks!

**Comment by c-blake** [comment]
This was a bad change.  Random probing is a bad approach from first principles of cache locality as now noted in comments near `nextTry`, but punted on for the impl.  Also in that comment "a few" iterations are mentioned.  It's not a few.  Modern hardware pulls in like 64*(1..3) bytes at a time in a linear scan but the big 65-100 ns DIMM latencies cannot be masked by random scans.  For small keys you could easily fit a dozen hash cells in that well-latency-masked memory, not just the "first few".  Naively counting "comparisons" or "probe depth" is **extremely** misleading.

In my most immediate rudimentary benchmark I did in 10 minutes after seeing this PR merged, I've already seen over a 25% performance regression just with this little anagram thing I posted in the forum recently and that *fits in L3 cache*.  It will be much worse with bigger tables where DIMMs of 10x the latency get hit.  You've also added back in tombstones which now means dynamic workloads that delete a lot in some insert-delete steady state like a bounded cache will have to rehash the whole table globally every N deletes instead of locally each delete.

I think this whole re-do was a very poorly impact measured/considered change.  It impacts everyone - some people with big tables who care the most in the neighborhood of 1.5-2.0x depending on load factor on the table. And it's only to fix behavior for poor hash functions which people could already change?  Now to avoid the slowdown from bouncing around memory randomly people have to implement their own whole `Table` or somehow avoid the one in the stdlib?  And maybe tell others to as well?  That does not seem like a UX improvement to me at all.

If you really have to change it from strict linear probing (which is **not a problem with a good hash**) to something more resistant to weak hashes, Robin Hood with backshift deletion is the way to go.  It creates tables that age well naturally with no tombstones and only does local reorganization with more contained costs for users who do know how to make better hash functions.  It minimizes the chain/cluster length "variance over the table".

**Comment by c-blake** [comment]
Honestly, with hardware pre-fetching you don't even know what to set that `thresh` to.  It will vary from one machine/CPU to the next to the next.  The one consistent trend in the past 40 years of CPU evolution has been to make linear scan loops fast and hide the hardly ever improving DIMM latency as much as possible.  As soon as you start to stray from that you suffer.

**Comment by c-blake** [comment]
You can't even really trust "hot loop" benchmarks in this, either.  You do some hot loop benchmark and only notice some 20-25% performance hit, but then in some real code where something happens "in between" Table accesses and "all of a sudden" the performance hit doubles or quadruples, as recently mentioned here https://forum.nim-lang.org/t/5734#35856 - really the hot loop microbenchmark was just not testing what you wanted.

**Comment by c-blake** [comment]
Looking over at your one set of benchmarks I could find which you used to justify "low performance impact" (https://github.com/timotheecour/vitanim/blob/master/testcases/tests/t0129b.nim, right???) I see only tests with like a million 8 byte keys in hot loops.  That's 100% in L3 cache which has approximately 10X better latency than dynamic RAM.  In short, it doesn't really test anything interesting about this table structure change.

**Comment by c-blake** [comment]
Perhaps more constructively - Robin Hood hashing is honestly pretty simple..arguably simpler than the explanation for this new probe sequence.  It just keeps collision chains sorted by their "distance from their home cell" (where they would hash to in an empty table).  That's it!

You can shift cells around with `moveMem`. Since we save hash codes we can easily and quickly compute the home cell.  As a bonus, for unsuccessful lookups (such as at insert new key time) you can stop, on average, halfway down the collision chain (once you pass the spot where a key "should have been" if it were present.

There are a lot of articles on this if you search for them.  E.g., this http://codecapsule.com/2013/11/17/robin-hood-hashing-backward-shift-deletion/  .  I've done it twice before once in C and once in Nim.  If you need me to, I can do a PR, but it might have to wait until next week.

**Comment by c-blake** [comment]
Rust used a Robin Hood table for quite a few years (until it switched to the much more complex port of Google's "Swiss" Tables).

**Comment by c-blake** [comment]
..and those "Swiss" tables mostly only get speed through vectorization tricks and much fine-tuning which is an ongoing maintenance burden as CPUs evolve/diversify..and also IIRC do not have the minimum variance guarantees of Robin Hood or its consequent 90+% memory utilization.  And RH has no extra hard to tune parameters.  Same old, "when to resize".  That's it.

RH is even friendly to being used as a *disk-resident* table, like B-Trees. These days fast computers have a budget of like 500 cycles multiplied by 4-way or 5-way superscalar or 2000-2500 dynamic CPU instructions per cache miss.  At that scale, almost anything that is supposed to handle larger than L3 cache data should be done almost the same way as if you did it "on disk".  Random probing decidedly does not have that trait.

**Comment by c-blake** [comment]
Oh, and incidentally - to support users who don't know how tables and hashes work from long collision chains we should just **count the loops** made in the comparisons.  Experts should be able to opt out of with a special `define` (or maybe as part of `danger`)..Somehow, though.

Then you can write out some kind of run-time warning message (probably exactly once per `Table` instance or maybe use a global variable to make it once per program or once per thread using a Table).  I'm not sure if there are other similar run-time "things are not going as planned but maybe we should not quit/raise exceptions" warnings in the stdlib or if so how they are reported.  It seems unlikely excessive hash collisions are the *only* case of something like this, though we may currently punt on all of them.

Anyway, doing that if you're a naive user and hashes misbehave then you get told what to do - use a better hash function.  Also, if you didn't take care against adversaries and you got attacked then this would at least write a message somewhere.  E.g., if you had code not designed to be safe from attack that was then run in an unsafe environment.

**Comment by timotheecour** [comment]
* @c-blake please see detailed benchmark numbers I'm reporting in https://github.com/nim-lang/Nim/pull/13440 with the mixed linear/pseudorandom approach I've been suggesting: worse case is 1.06 slowdown, best case is 1000X/unlimited; other simple cases of interest are > 2X faster (as compared to before https://github.com/nim-lang/Nim/pull/13418)
* the "better hash approach" was precisely what I had tried in previous PR https://github.com/nim-lang/Nim/pull/13410 but @Araq wanted a solution more robust against adversarial attacks; also note that it introduces a ~2X slowdown in several simple distributions (but at least avoids the catastrophic slowdowns); I compare against that in https://github.com/nim-lang/Nim/pull/13440

* with further code improvements + refactorings, I expect it will eventually become easier to both experiment with and customize the hashing+collision resolution and have it work across all Table types (there are many); right now there is much code duplication making this hard.
* we should be data driven, design good (representative for many workloads, easy to modify etc) benchmarks instead of using theoretical arguments or fixating on a single use case that would've gotten slower, there is no magic bullet for all tasks but there are still algorithms that have better overall tradeoffs. That being said, you are a making some good points and hopefully these turn into benchmarks + PR's for further improvements.

> I see only tests with like a million 8 byte keys in hot loops. That's 100% in L3 cache which has approximately 10X better latency than dynamic RAM. In short, it doesn't really test anything interesting about this table structure change.

I've also run tests on 20M keys and 100M keys (with key, val, hcode are int64, ie cell size with padding = 24B); that is 2.4GB which definitely doesn't fit on my 16MB cache.


## robin hood hashing
> If you need me to, I can do a PR, but it might have to wait until next week.

@c-blake if you think you can improve on the numbers I posted in https://github.com/nim-lang/Nim/pull/13440, by all means please do :) ; a draft PR is all that's needed for a start (ie no need to fix everything, just enough to run the benchmark I posted in that PR and compare apples to apples https://github.com/nim-lang/Nim/pull/13440 against robinhood hashing or swiss tables or your own version of it)
Note that, whether with pseudorandom hashing or robin hood hash or other collision algorithms, the major difficulty is not really implementing the algorithm, but to adapt all the existing code to work with it; there is quite a bit of code duplication that needs to be refactored before we should make further improvements.

one concern: seems to me robin hood suffers from #13393 as well (eg try with keys of the form `i shl 32`); if you use a better hash with robin hood, you'll pay a price to compute the hash (see performance numbers i have); if you don't you'll end up with a few large clusters and large probe sizes.
However, IMO the main idea of robin hood can be combined with the mixed approach of https://github.com/nim-lang/Nim/pull/13440: for low depths we proceed with linear probe and swap along the search as done in robinhood; and for depth > thres we switch to pseudorandom probing.

**Comment by c-blake** [comment]
As mentioned, tombstones cause performance lumpiness grief for steady-state constant membership heavy deletion workloads like a cache.

Also, while I am generally in favor of data-drivenness and benchmarks, as mentioned hot loop benchmarks can be so misleading that theoretical arguments tell you more when the primary cost driver is DIMM latency.  The CPU branch predictor detects the hot loop and works ahead by 1000 instructions to mask dynamic RAM latency it severely pollutes these numbers.  Even if you benchmark `array_access[random_element]` where you use a PRNG for the element you get misled about what happens when you don't have a perfectly oiled loop machine.  CPU performance counters for aggregate cache misses do not even tell the whole story because of pre-fetching logic.  And when you try to use more complicated things as benchmarks then all that complication pollutes your numbers, too.  There are model specific registers you can use to turn off pre-fetching but then the numbers are suspect for other reasons.

You don't have to fly completely blind.  On my main box at home I have 65 ns latency and 32 GB/s bandwidth.  So, a scan of up to 65\*32=2080 or half a memory page can be hidden.  That is very fast RAM, though.  Most would be more like (80-120)\*(20..24) or 1600..2880 bytes.  These are all really large regions for hash cells < 32B.   Regular linear probing with a good hash has a longest probe depth per table of about log-base2(table size).  So, for lookup latency, what is by far the most sensible thing to do is just fall back on "well, you cannot do better than 1 fetch + a linear-in-physical-memory scan as long as the scan is short-ish".  Your threshold thing kind of gets there, but tombstones create unnecessary aging rehashing trouble and temptation to use slow probe sequences whose slowness is not detected by naive benchmarks as happened here.

While you can fall down a rabbit hole of ever more complex probe sequences and there are many papers on this, you know what?  That's all about memory systems from 40+ years ago.  None will be as optimized by the CPU+memory system as a linear scan.  Fortunately or unfortunately the entire CPU+memory system has been optimized to hide latency in benchmarks.  Even having a nextTry isolated proc and tombstomes and "ease of experimentation" is probably asking for trouble like what happened here.  But yeah, you do need your hash to do some kind of minimal spreading out

Appeal to "but Python did it this way" is also wrong for multiple reasons.  Python was always slow and uses these things as part of its basic object model so much that it's all selected for in-L1-cache tiny tables than broad workloads.  CPython also no longer even does it this way for tables, only sets.  Also, some 1.5-2.0x performance hit at 75% full without the threshold and tombstones would not bother Python users anyway who would "outsource" performance sensitive stuff to some more carefully done C thing.

This depend-on-the-whole hash code sequence doesn't help with attacks - attackers can just collide in the code instead of the modulus.  We all get that.  It only helps with weak user hashes, but those could *also* collide the whole code. So, it's still a band-aid on totally awful hashes and @Araq is absolutely correct that the right solution for scaling guarantees is a B-tree.  Some warning message like "far more than expected hash loops - use a better hash function or B-tree" might well direct someone to do exactly that.

Anyway, in short - A) your hot loops are measure something not of interest besides the hot loop itself, so your 1.06x number is not quite meaningless but not what you should base decisions/comparisons upon, B) the real thing of interest is hard enough to measure that people agreeing on "realistic workloads" will be nearly impossible, C) there exists a simple alternative dodging all this, namely robin hood used by performance freak/non outsourcing Rustaceans for like 5 years until they moved to something with CPU architecture-specific tuning with its obvious ongoing maintenance burden, D) counting loops in rawGet or whatever and warning users will 1) always be necessary, 2) is super easy both to have and to disable and to regulate to avoid zillions of messages, and 3) and can immediately guide them to a better solution - the only thing needing agreement is how the runtime should warn.

**Comment by Araq** [comment]
> If you need me to, I can do a PR, but it might have to wait until next week.

Oh yeah please!

**Comment by Araq** [comment]
> with further code improvements + refactorings, I expect it will eventually become easier to both experiment with and customize the hashing+collision resolution and have it work across all Table types (there are many); right now there is much code duplication making this hard.

The code duplication also helps. The compiler hashes Nim identifiers, not "random numbers" and so a specialized implementation can exploit this, a stdlib impl can't. The compiler also never deletes anything inside a table so you can leave out the tombstone logic.

**Comment by timotheecour** [comment]
@c-blake you can take a look at this WIP for robin hood hashing:
https://github.com/timotheecour/Nim/commit/96a2d493e9aaf58c6e39c2e2834bec518346856a

doesn't yet allow bootstrapping nim from it but shd be usable as a library at least for `Table`; can be used as follows:
```
nim c --lib:lib -r -d:danger $vitanim_D/testcases/tableutils/benchmain.nim
```
seems to work but performance seems unequivocally worse compared to https://github.com/nim-lang/Nim/pull/13440 using same benchmark as on that PR; of course that could very possibly be due to bugs in my implementation which I wrote quickly as a POC; feel free to improve / come up with a better one in your own PR + hopefully report better performance numbers. As I mentioned earlier, it does suffer from #13393 and better hashing would also incur runtime cost.


> The compiler hashes Nim identifiers, not "random numbers" and so a specialized implementation can exploit this, a stdlib impl can't.

I would hope, with all the work done to improve tables/hashes, that stdlib implementation is now good enough for such use cases without any compromise on performance, and that at least some of (strtabs, compiler/astalgo, compiler/treetab, system/cellsets, pure/strtabs, sets) could simply reuse tables, or at least a common denominator that would allow fine tuning based on runtime/compile time properties, eg depthThres, mustRehashfillRatio, canDeleteCell. I don't think this would create a monster, quite the opposite.

**Comment by Araq** [comment]
> I don't think this would create a monster, quite the opposite.

Maybe but I don't see the point, instead of optimizing N different implementations you "optimize" a single one for diverse use cases. But this makes the problem much harder to solve, optimization is specialization. For example cellsets hashes pointers, nothing else. The only reason so much effort has to be put into the stdlib's hash tables is that we cannot anticipate how it's used.

**Comment by c-blake** [comment]
I agree having >1 entry point makes sense and "optimization is specialization" is a very quotable saying.  Some require no delete which is another wrinkle besides the ones @Araq mentioned.  I'm not sure the right number is the exact current number, but each candidate for conversion should be considered very carefully.  Adversarial inputs or bad user hashes are other dimensions the impls do not all share.  So, at least 3 bits/8 possibilities.  Maybe 2 bits/4 if you want to coalesce adversarial & bad.  There are surely others.

There is this VLDB 2015 paper "A Seven Dimensional Analysis of Hashing Methods" with a crazy complicated flowchart at the end.  Nothing is perfect, but Robin Hood has the most "arrows in" of the bunch.  (I also bet it'd be easy to poke holes in their benchmarks, though.)
