### PR TITLE
Fix double defer with break in closureiterators [backport]

### LINKED ISSUE #18824: `break`ing out of block in closure iterator causes finally/defer to execute twice
When defining a block inside of an iterator, any defer/finally block within that block will be executed twice in case of a break.

### Example
```nim
iterator poc_iterator: int {.closure.}  =
  block:
    defer: echo "In defer"
    break
  echo "Outside block"

for _ in poc_iterator():
  discard
```

### Current Output
```
In defer
In defer
Outside block
```

### Expected Output
```
In defer
Outside block
```

```
$ nim -v
Nim Compiler Version 1.4.8 [MacOSX: amd64]
```

### LINKED ISSUE #20624: break in closure iterator causes `finally` to be executed twice
```nim
import asyncdispatch

proc tryFinally(){.async.} =
  block route:
    try:
      echo "trying"
      raise
    except:
      echo "exception caught"
      break route
    finally:
      echo "finally block"
```

Output:

```
trying
exception caught
finally block
finally block
```

Originally reported in https://github.com/dom96/jester/issues/301. CC @sdmcallister

### PR DESCRIPTION
**Pull request by Menduist**
fixes #18824
fixes #20624
alternative to #20626

I did this fix a few months ago, but didn't push it as I wanted to refactor the closure iterator exception handling. Didn't have time to do it so far, so pushing this in the meantime

### CODE REVIEW

**Comment by ringabout** [comment]
Probably backport to 1.6?

**Comment by Araq** [comment]
@narimiran please backport.

File: tests/iter/titer_issues.nim [hunk 1]
```diff
@@ -362,3 +366,29 @@ block:
...
+
+for _ in poc_iterator():
+  discard
+
+# bug #20624
+iterator tryFinally() {.closure.} =
+  block route:
+    try:
+      echo "trying"
+      raise
```
Comment (arnetheduck) [inline tests/iter/titer_issues.nim:386]: as far as tests go, this raises a defect which may or may not be catchable
