### PR TITLE
fix #12521(type alias for openArray)

### LINKED ISSUE #12521: using a type alias for openArray[T] causes C compilation error
creating a type alias for openArray[T] and use it causes a C compilation error, it doesn't happen when using original name instead

### Example
```nim
# Type alias for openArray[T]
type slice[T] = openArray[T]

# Proc using that alias
proc testing(sl: slice[int]) =
    for item in sl:
        echo item

if isMainModule:
    var mySeq = @[1,2,3,4,5,6,7,8,9]
    testing(mySeq)
    testing(mySeq[2..^2])
```

### Current Output
```
Hint: used config file 'D:\Users\cristian_camilo.ruiz\Documents\nim-1.0.2_x64\nim-1.0.2\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: aliasbug [Processing]
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: aliasbug.nim
Error: execution of an external compiler program 'D:\Users\cristian_camilo.ruiz\Documents\nim-1.0.2_x64\nim-1.0.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -ID:\Users\cristian_camilo.ruiz\Documents\nim-1.0.2_x64\nim-1.0.2\lib -ID:\Users\cristian_camilo.ruiz\Documents -o D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c.o D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c' failed with exit code: 1

D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c: In function 'testing__GyMBzRo4wITKrSIMUGCTsQ':
D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c:191:15: error: 'slLen_0' undeclared (first use in this function)
     if (!(i < slLen_0)) goto LA3;
               ^~~~~~~
D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c:191:15: note: each undeclared identifier is reported only once for each function it appears in
D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c: In function 'NimMainModule':
D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c:275:3: error: too many arguments to function 'testing__GyMBzRo4wITKrSIMUGCTsQ'
   testing__GyMBzRo4wITKrSIMUGCTsQ(mySlice__pKaE8O6Sx2lwlCScvcc69cQ->data, (mySlice__pKaE8O6Sx2lwlCScvcc69cQ ? mySlice__pKaE8O6Sx2lwlCScvcc69cQ->Sup.len : 0));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c:9:0:
D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c:177:31: note: declared here
 N_LIB_PRIVATE N_NIMCALL(void, testing__GyMBzRo4wITKrSIMUGCTsQ)(NI* sl) { nimfr_("testing", "D:\\Users\\cristian_camilo.ruiz\\Documents\\aliasbug.nim");
                               ^
D:\Users\cristian_camilo.ruiz\Documents\nim-1.0.2_x64\nim-1.0.2\lib/nimbase.h:240:57: note: in definition of macro 'N_NIMCALL'
 #    define N_NIMCALL(rettype, name) rettype __fastcall name
                                                         ^~~~
D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c:280:3: error: too many arguments to function 'testing__GyMBzRo4wITKrSIMUGCTsQ'
   testing__GyMBzRo4wITKrSIMUGCTsQ(T6_->data, (T6_ ? T6_->Sup.len : 0));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c:9:0:
D:\Users\cristian_camilo.ruiz\nimcache\aliasbug_d\@maliasbug.nim.c:177:31: note: declared here
 N_LIB_PRIVATE N_NIMCALL(void, testing__GyMBzRo4wITKrSIMUGCTsQ)(NI* sl) { nimfr_("testing", "D:\\Users\\cristian_camilo.ruiz\\Documents\\aliasbug.nim");
                               ^
D:\Users\cristian_camilo.ruiz\Documents\nim-1.0.2_x64\nim-1.0.2\lib/nimbase.h:240:57: note: in definition of macro 'N_NIMCALL'
 #    define N_NIMCALL(rettype, name) rettype __fastcall name
                                                         ^~~~
```

### Expected Output
```
1
2
3
4
5
6
7
8
9

3
4
5
6
7
8
```

### Additional Information

* Trying other names for openArray but openArray seems good because is the same concept as Delphi

```
$ nim -v
Nim Compiler Version 1.0.2 [Windows: amd64]
Compiled at 2019-10-22
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 193b3c66bbeffafaebff166d24b9866f1eaaac0e
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #12521

### CODE REVIEW

File: compiler/ccgtypes.nim [hunk 1]
```diff
@@ -454,7 +454,7 @@ proc genProcParams(m: BModule, t: PType, rettype, params: var Rope,
     params.add(param.loc.r)
     # declare the len field for open arrays:
     var arr = param.typ
-    if arr.kind in {tyVar, tyLent, tySink}: arr = arr.lastSon
+    if arr.kind in {tyVar, tyLent, tySink, tyGenericInst}: arr = arr.lastSon
```
Comment (Araq) [inline compiler/ccgtypes.nim]:
```suggestion

    var arr = param.typ.skipTypes({tyGenericInst})
    if arr.kind in {tyVar, tyLent, tySink}: arr = arr.lastSon
```
