### PR TITLE
type with same name in different scope now works

### LINKED ISSUE #15526: regression(1.2 => 1.4 onwards): Block-local ref types with the same name lead to bad codegen: `no member named`
basically same as fixed https://github.com/nim-lang/Nim/issues/5170 but for ref types

### Example
```nim
when true: # D20201008T141857
  block:
    type Foo = ref object
      x1: int
    let f1 = Foo(x1: 1)
  block:
    type Foo = ref object
      x2: int
    let f2 = Foo(x2: 2)
```

### Current Output
```
@mt11116.nim.c:422:10: error: no member named 'x2' in 'struct tyObject_FoocolonObjectType___ktEbVfDBqcSUCx9b6syN8LA'
                (*T4_).x2 = ((NI) 2);
```

### Expected Output
works

### Additional Information
basically same as fixed https://github.com/nim-lang/Nim/issues/5170 (which was fixed) but for ref types
* nim devel 1.3.7 3eaacac2303ab9fc1aef62208a112fae0ddd9152 and prior
* EDIT: very similar to https://github.com/nim-lang/Nim/issues/17162

### LINKED ISSUE #17162: regression(1.2=>1.4 onwards): enum with same name in different scope gives wrong RT results
### Example
```nim
when true:
  # proc main = # ditto
  template main =
    block:
      type A = enum a0, a1, a2
      for ai in A:
        echo (ai,)
    block:
      type A = enum b0, b1, b2, b3
      for ai in A:
        echo (ai,)

  static: main() # ok
  main() # bug
```

### Current Output
vm:
(a0,)
(a1,)
(a2,)
(b0,)
(b1,)
(b2,)
(b3,)

rt:
(a0,)
(a1,)
(a2,)
(a0,)
(a1,)
(a2,)
(3 (invalid data!),)

### Expected Output
rt should be like vm:
(a0,)
(a1,)
(a2,)
(b0,)
(b1,)
(b2,)
(b3,)

### Additional Information
* works 1.2.8
* fails 1.4.0
* fails 1.5.1 74a8f23801316cd9e5b7ea072bf0c8c0465b0626

Note that it works in vm or in js but not in c backend
EDIT: seems very similar to https://github.com/nim-lang/Nim/issues/15526
(and also to https://github.com/nim-lang/Nim/issues/5170 but that was fixed)

### LINKED ISSUE #17666: Redefinition and usage of ref type in different scopes leads to invalid c code
It seems that when you define a type with different fields in two different scopes, and instantiate it in both scopes, and accedss a field in the second defintion, that didnt exist in the first definition, the generated c-code will be invalid.

Compiling this:
```nim
block:
    type Foo = ref object
    echo Foo().repr
block:
    type Foo = ref object
      field: int
    echo Foo().field

```

will result in:
```
[I] felix@rzbl ~/tmp> nim c nimbug.nim
Hint: used config file '/home/felix/git/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/felix/git/Nim/config/config.nims' [Conf]
....                                                                                                        
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_formatfloat.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: nimbug.nim
/home/felix/.cache/nim/nimbug_d/@mnimbug.nim.c: In function ‘NimMainModule’:
/home/felix/.cache/nim/nimbug_d/@mnimbug.nim.c:191:30: error: ‘tyObject_FoocolonObjectType___fGcm43VB58lQvE79caF19bjQ’ {aka ‘struct tyObject_FoocolonObjectType___fGcm43VB58lQvE79caF19bjQ’} has no member named ‘field’  191 |   T5_[0] = nimIntToStr((*T6_).field);
      |                              ^
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/felix/git/Nim/lib -I/home/felix/tmp -o /home/felix/.cache/nim/nimbug_d/@mnimbug.nim.c.o /home/felix/.cache/nim/nimbug_d/@mnimbug.nim.c' failed with exit code: 1
```

Also:
```
[I] felix@rzbl ~/tmp> nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-04-04
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 97764c8dc91081875f57029ae3f72d3a503f5e45
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by timotheecour**
* fix https://github.com/nim-lang/Nim/issues/15526
* fix https://github.com/nim-lang/Nim/issues/17162
* fix https://github.com/nim-lang/Nim/issues/17666
* fix tests/enum/tenum.nim which was wrong (was affected by https://github.com/nim-lang/Nim/issues/17162)

## unrelated question for reviewer
sighashes doesn't seem to do any caching, is that intentional?

## future work
* avoid (pre-existing) hacks to prevent endless recursion, and use caching via a hash table, which should also speed `hashType` (but we also need to assess whether `hashType` has some non-negligible cost)

### CODE REVIEW

File: tests/ccgbugs/tsame_name.nim [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+        doAssert f1.x1 == 1
+      block:
+        type Foo = object
+          x2: int
+        let f2 = Foo(x2: 2)
+        doAssert f2.x2 == 2
+    static: fn()
+    fn()
+
+when true: # ditto, refs https://github.com/nim-lang/Nim/issues/5170#issuecomment-582712132
```
Comment (ghost) [inline tests/ccgbugs/tsame_name.nim]: a debug leftover?  `when true` doesn't affect anything really

Comment (timotheecour) [reply tests/ccgbugs/tsame_name.nim]: it's intentional, just to delineate this section for the reader

File: tests/enum/tenum.nim [hunk 2]
```diff
@@ -6,7 +6,7 @@ ABCDC
 foo
 first0second32third64
 my value A1my value Bconc2valueCabc4abc
-my value A0my value Bconc1valueCabc3valueC
```
Comment (Araq) [inline tests/enum/tenum.nim:9]: Why did this change?

Comment (timotheecour) [reply tests/enum/tenum.nim:9]: the test was wrong, and was affected by #17162 ; x should be abc, not valueC
