### PR TITLE
fix #16458; make useNimRtl compile for --gc:orc

### LINKED ISSUE #16458: useNimRtl does not work for --gc:orc/arc (in windows)
### Example
command: `nim c --gc:orc --d:useNimRtl anysource.nim`

### Current Output
```
Hint: used config file 'C:\Users\CodeHz\.choosenim\toolchains\nim-1.4.2\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\CodeHz\.choosenim\toolchains\nim-1.4.2\config\config.nims' [Conf]
.
C:\Users\CodeHz\.choosenim\toolchains\nim-1.4.2\lib\system\mmdisp.nim(78, 25) template/generic instantiation of `instantiateForRegion` from here
C:\Users\CodeHz\.choosenim\toolchains\nim-1.4.2\lib\system\alloc.nim(1030, 3) Error: redefinition of 'allocImpl'; previous declaration here: C:\Users\CodeHz\.choosenim\toolchains\nim-1.4.2\lib\system\memalloc.nim(38, 8)
```

### Expected Output
(works)

### Possible Solution

no idea

### Additional Information

```
Nim Compiler Version 1.4.2 [Windows: amd64]
Compiled at 2020-11-30
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #16458

### CODE REVIEW

File: lib/system/mmdisp.nim [hunk 1]
```diff
@@ -82,8 +82,9 @@ else:
     # XXX due to bootstrapping reasons, we cannot use  compileOption("gc", "stack") here
     include "system/gc_regions"
   elif defined(nimV2) or usesDestructors:
-    var allocator {.rtlThreadVar.}: MemRegion
-    instantiateForRegion(allocator)
+    when not defined(useNimRtl):
+      var allocator {.rtlThreadVar.}: MemRegion
+      instantiateForRegion(allocator)
```
Comment (ringabout) [inline lib/system/mmdisp.nim:87]: Refc uses this condition too => https://github.com/nim-lang/Nim/blob/27e548140b0f51a8dbc6f6094764e02f08ae509e/lib/system/gc.nim#L149
