### PR TITLE
fix #17177

### LINKED ISSUE #17177: asyncjs: declaring .async proc inside an .async proc gives CT error
### Example
```nim
import std/asyncjs
proc fn1(n: int): Future[int] {.async.} = return n
proc main2() =
  proc fn2(n: int): Future[int] {.async.} = return n
proc main3(a: auto) =
  proc fn3(n: int): Future[int] {.async.} = return n
proc main4() {.async.} =
  proc fn4(n: int): Future[int] {.async.} = return n # xxx bug: uncomment this and it works
  discard
```

### Current Output
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11907.nim(11, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11907.nim(12, 52) Error: type mismatch:
 got 'Future[Future[system.int]]' for 'jsResolve(jsResolve(n))' [ref declared in /Users/timothee/git_clone/nim/Nim_devel/lib/js/asyncjs.nim(68, 3)]
 but expected 'Future[system.int]' [ref declared in /Users/timothee/git_clone/nim/Nim_devel/lib/js/asyncjs.nim(68, 3)]
    proc fn4(n: int): Future[int] {.async.} = return n
```

### Expected Output
works

### Additional Information
* 1.5.1 a4e6b242d56d80df004bf625643fcb3c9d3f1b7f
* looks similar to https://github.com/nim-lang/Nim/issues/16786 but definitely a different issue
* prevents using `(a: int) {.async.} => await ...` anonymous procs inside an async proc which would be useful sugar for the new `asyncjs.then` (https://github.com/nim-lang/Nim/pull/16871)

### PR DESCRIPTION
**Pull request by ringabout**
Return/Result stmt will be resolved multiple times in a nested async js function, so adding a overload which accepts `Future[T]` is reasonable.

### CODE REVIEW

File: tests/js/t17177.nim [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import std/asyncjs
+
```
Comment (timotheecour) [inline tests/js/t17177.nim:2]: I will move this to `tasyncjs` in followup work after https://github.com/nim-lang/Nim/pull/17189

Comment (ringabout) [reply tests/js/t17177.nim:2]: I agree

**Review by timotheecour — APPROVED** [review]
seems reasonable.
after this PR, the disabled block in https://github.com/nim-lang/Nim/pull/17189 works now a bit better
```nim
      # this now works:
      proc asyncIdentityNested(n: int): Future[int] {.async.} = return n
      let x5 = await asyncFact(3).then(asyncIdentityNested)
      doAssert x5 == 3 * 2

      # this still dosen't work, probably for reasons related to => or async
      let x6 = await asyncFact(3).then((a:int) {.async.} => a * 11)
```
