### PR TITLE
fixes #4799, varargs now can accept polymorphic types

### LINKED ISSUE #4799: varags broken with polymorphic types
Currently, it is not possible to pass in subtyped objects in varags arguments.

```
type
  Base = ref object of RootObj
  A = ref object of Base
  B = ref object of Base

proc test(oa: varargs[Base]) = discard

#test(A()))          # FAILS TO COMPILE:
                     # Error: type mismatch: got (A)
                     # but expected one of:
                     # proc test(oa: varargs[Base])

#test(A(), B())      # FAILS TO COMPILE:
                     # Error: type mismatch: got (A, B)
                     # but expected one of:
                     # proc test(oa: varargs[Base])
```

### PR DESCRIPTION
**Pull request by jangko**

### CODE REVIEW

File: compiler/ccgexprs.nim [hunk 1]
```diff
@@ -347,7 +347,8 @@ proc genAssignment(p: BProc, dest, src: TLoc, flags: TAssignmentFlags) =
     else:
       useStringh(p.module)
       linefmt(p, cpsStmts,
-           "memcpy((void*)$1, (NIM_CONST void*)$2, sizeof($1[0])*$1Len_0);$n",
+           #"memcpy((void*)$1, (NIM_CONST void*)$2, sizeof($1[0])*$1Len_0);$n",
+           "$1 = $2;$n",
```
[the remark this answers is not in the document]
Comment (jangko) [reply compiler/ccgexprs.nim]: all other Nim types of varargs are not processes through this `else` branch. they are processed somewhere else.
because of bug #4799, this `else` branch never executed anymore.
the above code also not a C arrays assignment, but plain pointer assignment.
the transform part already transform the AST into single pointer assignment, not a sequence of pointers anymore.
because of this reasons, the memcpy no longer needed, at least we haven't encountered other use case of this `else` branch besides simple pointer assignment.

[the remark this answers is not in the document]
Comment (jangko) [reply compiler/ccgexprs.nim]: perhaps a clear annotation/comment for this `else` branch sufficient, until another bug comes up?

**Comment by Araq** [comment]
Does it work with an explicit ``[]`` array construction too? Please add that to the test. Then it should be fine.

**Comment by jangko** [comment]
I found two more issue with this case:
* sigmatch bug: array construction works with ref object and ptr object, not work with generic object
* codegen bug: using array construction or not, ordinary object will crash/garbage at runtime. need to locate the problem. the generated code not using memcpy, only a deep nested curly braces and address operator. turn out the ordinary object part also never executed because of bug #4799

remind myself:
- [ ] fix codegen bug for ordinary object
- [ ] fix sigmatch for generic object
- [ ] test proc scope too, not only global scope
- [ ] test generic ref object
- [ ] test array [ ] generic
- [ ] explicit array construction [ ] test

File: compiler/sigmatch.nim [hunk 2]
```diff
@@ -2000,6 +2000,13 @@ proc paramTypesMatchAux(m: var TCandidate, f, a: PType,
           m.baseTypeMatch = true
         else:
           result = userConvMatch(c, m, base(f), a, arg)
+          # bug #4799, varargs accepting subtype relation object
+          if result.isNil and r == isSubtype:
```
Comment (Araq) [inline compiler/sigmatch.nim]: The check for ``r == isSubtype`` needs to be moved above ``userConvMatch``, I think.

Comment (jangko) [reply compiler/sigmatch.nim]: Thank you for the tip, I will take a look, after #7600 and #7601

**Comment by jangko** [comment]
#7955 and #7956 can be safely excluded, although they were discovered during #4799 investigation.
this one is ready for review

File: tests/typerel/t4799_2.nim [hunk 3]
```diff
@@ -0,0 +1,24 @@
+discard """
```
Comment (zah) [inline tests/typerel/t4799_2.nim]: Perhaps this bug doesn't deserve so many separate test cases (they slow down the execution of the test suite a little bit).

The alternative would be to use the `accept`/`reject` approach that is frequently used in the rest of the test suite:
https://github.com/nim-lang/Nim/blob/devel/tests/cpp/tcovariancerules.nim#L168

File: tests/typerel/t4799.nim [hunk 4]
```diff
@@ -0,0 +1,245 @@
...
+    result = ""
+    for c in x:
+      result.add $c.tire
+
+  var v = Vehicle(tire: 3)
+  var c = Car(tire: 4)
+  var b = Bike(tire: 2)
+
+  reject:
+    echo testVehicle b, c, v
```
Comment (Araq) [inline tests/typerel/t4799.nim]: same problem.

File: tests/typerel/t4799.nim [hunk 5]
```diff
@@ -0,0 +1,245 @@
...
+proc testVehicle(x: varargs[RVehicle]): string {.used.} =
+  result = ""
+  for c in x:
+    result.add $c.tire
+
+var rc = RCar(tire: 4)
+var rb = RBike(tire: 2)
+
+reject:
+  echo testVehicle rb, rc
```
Comment (Araq) [inline tests/typerel/t4799.nim]: same problem.

**Comment by Araq** [comment]
I'm accepting this but in the future please add more tests that should fail the type checker. A language where everything has a valid interpretation is a language that doesn't detect mistakes.
