### PR TITLE
Make range checks in semConv

### LINKED ISSUE #6679: Instant compiler murder: NaN.char
```shell
[i]  ~/code/lang/nim ; nim --version
Nim Compiler Version 0.17.3 (2017-11-02) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

active boot switches: -d:release

[i]  ~/code/lang/nim ; cat scratch.nim 
echo NaN.char

[i]  ~/code/lang/nim ; nim c scratch.nim 
Hint: used config file '/home/zax/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: scratch [Processing]
scratch.nim(1, 6) Error: internal error: getStrOrChar
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```
---

I would expect this to produce a compiler error; this looks like a compiler crash.

### LINKED ISSUE #7102: range bounds are not checked if initialized inside if condition check
The code below shows that ranges are not checked if a subrange is initialized in a if statement. 

``` nim
type
  IntRange = range[0..10]
  CharRange = range['a'..'i']

#[
  # this gives a compile-time error for i and a warning for c(as it should).
var
  i:IntRange = IntRange(11)
  c:CharRange = CharRange('q')

echo i
echo c
]#

#However, the lines below do compile and even print!
if 'q' == CharRange('q'):
  echo "this should not even compile without a warning."

if 11 == IntRange(11):
  echo "this should not even compile."
```
when compiled with `nim c -r test.nim` it gives the following output:
```
Hint: used config file '/etc/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
CC: test
Hint:  [Link]
Hint: operation successful (12636 lines compiled; 0.358 sec total; 22.422MiB peakmem; Debug Build) [SuccessX]
Hint: /home/username/nimtest/test  [Exec]
this should not even compile without a warning.
this should not even compile.
```

output of `nim --version` is.
```
Nim Compiler Version 0.17.2 (2017-09-11) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf
```

### LINKED ISSUE #7580: `compiles` doesn't work for invalid compile time conversions
Snippet:
```nim
#discard Natural(-1) # Error: conversion from int literal(-1) to Natural is invalid
echo compiles Natural(-1) # got "true", expected "false"
```

Nim version:
```
Nim Compiler Version 0.18.1 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 0b99e8e8cb8dfe3de8d3fa38cc48f919acd0fe4c
active boot switches: -d:release -d:nativeStackTrace
```

### PR DESCRIPTION
**Pull request by GULPF**
Another compiler adventure

Previously the type conversion range checks where only added by `transf.nim`, and evaluated statically when possible. This method missed the cases where the type conversion had already been done during semchecking due to constant folding. To solve this I've changed `checkConvertible` to also make sure that the value is within the range of the destination type.  

I'm not entirely happy with this solution. I feel it should be possible to let `changeType` do the range checking, but I'm not sure how `semConv` would need to change to allow for that.

This new semcheck found a bug in `posix` that I've corrected. It also found a bug in the [opengl package](https://github.com/nim-lang/opengl) which causes a test failure, but I don't know how to fix that one. Relevant line:

https://github.com/nim-lang/opengl/blob/4106d6efc6ad32d848fe75d89f629c8a97012940/src/opengl/private/constants.nim#L4692

`0xFFFFFFFFFFFFFFFF` obviously doesn't fit into `GLenum` (an alias for unit32), so I'm not sure what to do.

Fixes #7102
Fixes #7580
Fixes #6679

### CODE REVIEW

**Comment by GULPF** [comment]
AppVeyor failure indicates a bug in `winlean.nim`: 
```nim
const
 IOC_OUT* = 0x40000000
 IOC_IN*  = 0x80000000
 IOC_WS2* = 0x08000000
 IOC_INOUT* = IOC_IN or IOC_OUT

template WSAIORW*(x,y): untyped = (IOC_INOUT or x or y)

const
  SIO_GET_EXTENSION_FUNCTION_POINTER* = WSAIORW(IOC_WS2,6).DWORD
```
I think `IOC_IN` is supposed to be a `int32` literal, but the compiler decides that it's `int64`, which results in a different value.

**Comment by GULPF** [comment]
Previous comment is incorrect. It appears that [DWORD is supposed to be uin32](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx), not int32 like `winlean` defines. `0x80000000` fits inside uint32. Several other `winlean` types are also incorrect.

**Comment by Araq** [comment]
This is pretty important, please fix the CI builds and continue to work on this.

**Comment by GULPF** [comment]
OK, I've cleaned up the PR a bit, fixed the winlean constants and submitted https://github.com/nim-lang/opengl/pull/51 which fixes the other test failure.

I haven't changed `DWORD` to `uint32` because that's a big breaking change which is unrelated to this PR, and I don't know if it's correct anyway.

**Comment by cooldome** [comment]
Supertb, absolute must have.

Araq, looks like DWORD needs to be changed to uint32 what do you think?

**Comment by GULPF** [comment]
After getting more familiar with semfold.nim, I've tried another approach for this that I think is much better. I haven't really tested it yet and it's not finished, but it looks good.

**Comment by GULPF** [comment]
Turns out `semfold` isn't applied in a lot of cases (e.g `let i = Natural(-1)` is folded by the `transf` pass, not by `semfold`), so the original idea is more robust after all.

**Comment by GULPF** [comment]
The last failing test is because the tests doesn't use the devel version of https://github.com/nim-lang/opengl/. The opengl package should probably get a version bump.

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -115,15 +117,23 @@ proc checkConvertible(c: PContext, castDest, src: PType): TConvStatus =
...
+      (skipTypes(srcTyp, abstractVarRange-{tyTypeDesc}).kind in
+        IntegralTypes + {tyFloat..tyFloat64}):
+    # accept conversion to integral types, unless outside of range
+    if targetTyp.isOrdinalType:
+      if src.kind in nkCharLit..nkUInt64Lit and
+          src.intVal notin firstOrd(targetTyp)..lastOrd(targetTyp):
+        result = convNotInRange
+      elif src.kind in nkFloatLit..nkFloat64Lit and
+          src.floatVal notin
+            firstOrd(targetTyp).toBiggestFloat..lastOrd(targetTyp).toBiggestFloat:
```
Comment (GULPF) [inline compiler/semexprs.nim]: I've realized that this isn't entirely correct, due to `high(int64).toBiggestFloat` getting rounded up since it's not representable in `float64`. Is there a way to get the largest representable float that is less-or-equal than some integer?

Comment (Araq) [reply compiler/semexprs.nim]: Yeah, no idea either, sorry.

**Comment by GULPF** [comment]
Rebased and cleaned up the commit mess. To get the correct behavior for conversion of very large floats to int64 I added `nextAfter` and `toBiggestFloatSlice` to the `math` module. If those should not be in the stdlib I can put them somewhere else, but the compiler will need it in multiple places so it needs to reusable.

**Comment by Araq** [comment]
@LemonBoy got superseeded by your PRs?

**Comment by Araq** [comment]
@narimiran Please check which of these bugs are still open and how to integrate this PR.

**Comment by narimiran** [comment]
@GULPF sorry for one unneeded force-push — I was trying to resolve the conflicts locally but something went very wrong with appveyor after a (regular) push containing the commit with the merge, so I took that back and resolved the conflicts here on Github. 

(And now I'm trying to go through the failed testing attempts)

**Comment by narimiran** [comment]
Now that devel is successfully merged, there is still one breaking change that should be addressed.

In `tests/statictypes/tstatictypes.nim`, lines 135–139 now fail with `type mismatch: got <N> but expected 'int8'`.

Changing those lines to this:
```nim
block:
  type
    Coord[N: static[int]] = tuple[col, row: range[0'i8 .. (N-1).int8]]
    Point[N: static[int]] = range[0'i16 .. (N * N - 1).int16]
``` 
would make them work, but @Araq confirmed that "`N.int8 - 1` should be of type int8", i.e. everything should work with the existing versions (`N.int8 - 1` and `N.int16 * N.int16 - 1`).

@GULPF, can you make your changes work with the existing test?
