### PR TITLE
fixes #22787; marks `var section` in the loop as reassign preventing cursor

### LINKED ISSUE #22787: Different results on orc/refc or global/procedure scope with orc
### Description

Upgraded to nim 2 and some code stopped working.

Isolated it to:

```
var s:seq[string]

for i in 0..3:
  s.add ("test" & $i)
  s.add ("test" & $i)

var lastname:string

for i in s:
  var name = i[0..4]

  if name != lastname:
    echo "NEW:",name
  else:
    echo name,">",lastname

  lastname = name     
```

var name = i[0..4]

The problem seems to be in the i[0..4] part with orc.

https://play.nim-lang.org/#ix=4I8a

### Nim Version

2.0.0

### Current Output

```text
NEW:test0
test0>test0
test1>test1
test1>test1
test2>test2
test2>test2
test3>test3
test3>test3
```

### Expected Output

```text
NEW:test0
test0>test0
NEW:test1
test1>test1
NEW:test2
test2>test2
NEW:test3
test3>test3
```

### Possible Solution

_No response_

### Additional Information

Expected output is generated with -refc or if the code is written in global scope.
Wrong output is generated with -orc if the code is written in a procedure.

### PR DESCRIPTION
**Pull request by ringabout**
fixes #22787

### CODE REVIEW

File: compiler/varpartitions.nim [hunk 1]
```diff
@@ -823,6 +823,11 @@ proc computeLiveRanges(c: var Partitions; n: PNode) =
           registerVariable(c, child[i])
           #deps(c, child[i], last)
 
+        if child[0].kind == nkSym: # bug #22787
+          let vid = variableId(c, child[0].sym)
+          if child[^1].kind != nkEmpty:
+            if c.inLoop > 0:
+              markAsReassigned(c, vid)
```
Comment (Araq) [inline compiler/varpartitions.nim]:
```suggestion
        if c.inLoop > 0 and child[0].kind == nkSym: # bug #22787
          let vid = variableId(c, child[0].sym)
          if child[^1].kind != nkEmpty:
            markAsReassigned(c, vid)
```
