### PR TITLE
fix #16993, #18054, #17835 runnableExamples now works with templates and nested templates

### LINKED ISSUE #16993: regression: `runnableExamples` in template should not affect caller
reduced from CI failure in https://github.com/nim-lang/Nim/pull/16988
### Example
```nim
# t11840b.nim:
template doAssert2*(cond: untyped) =
  ## foo
  runnableExamples:
    echo "D20210209T192323"
  discard

# main.nim:
import t11840b
doAssert2 true
doAssert2 true
doAssert2 true
```

nim doc main.nm

### Current Output
D20210209T192323
D20210209T192323
D20210209T192323

### Expected Output
(nothing)

### Additional Information
worked in 0.19.0
fails since 0.19.6 including devel 1.5.1 0d34345f29aa3b862f21c8dcff6b94b5ac5b9572

as an example, this prevents adding runnableExamples in `doAssert` (refs https://github.com/nim-lang/Nim/pull/16988) but obviously this affects other code, eg when adding runnableExamples to a template.

Note that transforming a proc (that would contain a runnableExamples) to a template shouldn't affect semantics wrt runnableExamples.
Also note that current behavior is bad because it makes it impossible to add runnableExamples to templates without it affecting semantics as demoed here.

### LINKED ISSUE #17835: Docgen issue with runnableExamples on specific usage of anyIt template.
### Example
```nim
import std/sequtils

proc foo*(n: seq[int]): bool =
  result = anyIt(n, it == 0)
```

### Current Output
```
$ nim doc test.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
Hint: used config file '/etc/nim/nimdoc.cfg' [Conf]
......
sequtils.nim(721, 3) Error: runnableExamples must appear before the first non-comment statement
```

### Additional Information
Any statement before `result =` will make the bug disappear.

This is causing disruptek/cps docs to not build.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-04-24
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: b667e288e27a09ce4f65166fc66a6b713350a9b6
active boot switches: -d:release -d:nimUseLinenoise -d:nativeStackTrace
```

Bisect shows that a807233aebcd3759bc3e21b450ed89e1eb6ddace is the first bad commit.

/cc @timotheecour @xflywind

### LINKED ISSUE #18054: nim doc: Unexpected output when runnableExamples are present in templates and nested templated
I was going through [this old post](https://forum.nim-lang.org/t/1188#7366) on doing pointer arithmetic and I thought of just adding `runnableExamples` to it for the sake of my better understanding and documentation.

I ended up adding `runnableExamples` for the inner templates as well. `nim doc` command runs fine and tests snippets from all runnableExamples, but the issue is that random runnableExamples snippets then show up at the top of the generated doc.

I was able to reproduce that issue with this minimal example:

### Example `t.nim`
```nim
template outer*(body: untyped) =
  ## outer template doc string.
  runnableExamples:
    doAssert 1 == 1
  ##
  template inner1*() =
    ## inner1 template doc string.
    runnableExamples:
      doAssert 2 == 2
    ##
    echo "inner1"

  template inner2*() =
    ## inner2 template doc string.
    runnableExamples:
      doAssert 3 == 3
    ##
    echo "inner2"

  body

when isMainModule:

  echo "in main module"

  outer:
    inner1()
    inner2()
```

- Run `nim doc t.nim`

### Current Output

image

### Expected Output

The expected output is that:
1. The runnableExamples from the nested templates do not show up at the very top. Right now they are getting duplicated.
2. The nested templates look as if they are available at the top level. May be we do not yet have a way to represent nested templates in generated docs. But the output above seems wrong.

### Possible Solution

This is not a solution, but if I comment out the `outer:` block in `when isMainModule:` as shown below, the template duplication goes away, but then I also lose the documentation of all the nested templates from the doc HTML.

```nim
when isMainModule:

  echo "in main module"

  # outer:
  #   inner1()
  #   inner2()
```

Now the doc looks like below, which also doesn't seem like the right solution:

image

I just lost all the documentation and runnableExamples for all the nested templates.

See https://kaushalmodi.github.io/ptr_math/ for the actual example.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-01-11
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: fd5c8ef20845a511ad4e0af8dd8ad4331bf46ffc
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by timotheecour**
fix #16993
fix #18054
fix #17835
close #17842 as this is a proper fix whereas #17842 was a workaround

the diff in nimdoc/testproject/subdir/subdir_b/utils.nim sums it up.

## future work
- [ ] after this PR, `code-block` has almost no use cases left in nim sources and should be replaced by  `runnableExamples`
- [ ] we could also introduce a flag `runnableExamples(inject = true)` to inject the runnableExamples of a template `foo` at the place where `foo` is called, but this is a niche feature, and the main use case is the one implemented by this PR (as evidenced by those bug reports)

## notes
related past issues (dealing with doc comments instead of runnableExamples):
https://github.com/nim-lang/Nim/issues/9596, https://github.com/nim-lang/Nim/issues/9432, https://github.com/nim-lang/Nim/issues/9626, https://github.com/nim-lang/Nim/issues/9473, https://github.com/nim-lang/Nim/issues/9469

I also encountered https://github.com/nim-lang/Nim/issues/18077 while fixing this (EDIT: fixing it here: https://github.com/nim-lang/Nim/pull/18086)

### CODE REVIEW

File: lib/system/assertions.nim [hunk 1]
```diff
@@ -86,21 +57,39 @@ template assert*(cond: untyped, msg = "") =
...
   ## Similar to `assert <#assert.t,untyped,string>`_ but is always turned on regardless of `--assertions`.
+  runnableExamples:
+    doAssert 1 == 1 # generates code even when built with `-d:danger` or `--assertions:off`
   assertImpl(cond, msg, astToStr(cond), true)
 
 template onFailedAssert*(msg, code: untyped): untyped {.dirty.} =
   ## Sets an assertion failure handler that will intercept any assert
   ## statements following `onFailedAssert` in the current scope.
+  runnableExamples:
+    type MyError = object of CatchableError
```
Comment (timotheecour) [inline lib/system/assertions.nim:76]: i've also improved a bit the examples after moving them at template scope

File: tests/nimdoc/trunnableexamples.nim [hunk 2]
```diff
@@ -1,19 +1,31 @@
 discard """
-cmd: "nim doc --doccmd:-d:testFooExternal --hints:off $file"
+cmd: "nim doc --doccmd:--hints:off --hints:off $file"
 action: "compile"
+nimoutFull: true
```
Comment (timotheecour) [inline tests/nimdoc/trunnableexamples.nim:4]: without nimoutFull, this test wouldn't be sufficient to check that the bugs were fixed; so because of https://github.com/nim-lang/Nim/issues/18077 i have to split the test in 2 files temporarily until https://github.com/nim-lang/Nim/issues/18077 gets fixed

**Review by ringabout — APPROVED** [review]

File: nimdoc/testproject/expected/subdir/subdir_b/utils.html [hunk 3]
```diff
@@ -206,9 +206,9 @@ <h1><a class="toc-backref" href="#18">Templates</a></h1>
 <dt><pre><span class="Keyword">template</span> <a href="#fromUtilsGen.t"><span class="Identifier">fromUtilsGen</span></a><span class="Other">(</span><span class="Other">)</span><span class="Other">:</span> <span class="Identifier">untyped</span></pre></dt>
 <dd>
 
-this should be shown in utils.html
+should be shown in utils.html only
 <p><strong class="examples_text">Example:</strong></p>
-<pre class="listing"><span class="Identifier">assert</span> <span class="DecNumber">3</span><span class="Operator">*</span><span class="DecNumber">2</span> <span class="Operator">==</span> <span class="DecNumber">6</span></pre>ditto
+<pre class="listing"><span class="Keyword">discard</span> <span class="StringLit">&quot;should be in utils.html only, not in module that calls fromUtilsGen&quot;</span></pre>ditto
```
Comment (Araq) [inline nimdoc/testproject/expected/subdir/subdir_b/utils.html:211]: This seems to be worse, now the runnableExample for template `formUtilsGen` disappeared?

Comment (timotheecour) [inline nimdoc/testproject/expected/subdir/subdir_b/utils.html:211]: no it's there, see `hould be in utils.html only, not in module that calls fromUtilsGen`

File: nimdoc/testproject/subdir/subdir_b/utils.nim [hunk 4]
```diff
@@ -50,9 +50,9 @@ template bEnum*(): untyped =
     discard
 
 template fromUtilsGen*(): untyped =
-  ## this should be shown in utils.html
+  ## should be shown in utils.html only
   runnableExamples:
-    assert 3*2 == 6
+    discard "should be in utils.html only, not in module that calls fromUtilsGen"
```
Comment (Araq) [inline nimdoc/testproject/subdir/subdir_b/utils.nim:55]: Why was this changed? Does the `assert` inside a runnableExample inside a template still work?

Comment (timotheecour) [reply nimdoc/testproject/subdir/subdir_b/utils.nim:55]: yes, of course assert still works, the new comment makes it clear when you look at nim sources + generated file where it came from and where it should end up

Comment (timotheecour) [reply nimdoc/testproject/subdir/subdir_b/utils.nim:55]: this is also tested via tests/nimdoc/trunnableexamples.nim btw

**Comment by timotheecour** [comment]
ping @Araq

**Comment by timotheecour** [comment]
merging, refs https://discord.com/channels/371759389889003530/768367394547957761/849568304807804928
