### PR TITLE
`$(a: float)` now works consistently in nim js, avoiding printing floats as ints

### LINKED ISSUE #133: var a = 2.0; echo a prints 2 in nim js
var a = 2.0; echo a prints 2 in nim js

### Example
```nim
import unittest

template fun(a2: static float) =
  const a: float = a2 # needed pending https://github.com/timotheecour/Nim/issues/132
  var b = a
  check $b == $a

fun 2
fun 2.0
fun 2.1
fun 1_000
fun 1_000.1
fun 1_000_000_000.1
fun 1_000_000_000_000.1
```

### Current Output
```
fails
```

### Expected Output
```
works
```

### Possible Solution
* see my branch pr_dollar_float_js

### Additional Information
* D20200426T152233
* 9384f7ad35aa36a22b31d7541254e89890d6cec2

### LINKED ISSUE #7605: Inconsistent float formatting in javascript.
```
echo 123.0 # this prints 123.0 in both c and js
var f = 123.0
echo f # this prints 123 in js and 123.0 in c
```
I would expect floats to be printed the say way if they are immediate or variable.

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @Araq 
* fix https://github.com/nim-lang/Nim/issues/7605
* fix https://github.com/timotheecour/Nim/issues/133 (has more examples; didn't know about #7605 when i wrote it)
* avoids changing the test for tpegs.nim in https://github.com/nim-lang/Nim/pull/14095 which introduced js support for pegs
* after PR: `$(a: float)` now works more consistently and matches behavior of c, vm targets
```nim
echo 2.0 # 2.0
var b = 2.0
echo b # before PR: 2, after PR: 2.0
```

- [ ] it would be nice to merge https://github.com/nim-lang/Nim/pull/14122 before this PR so I can avoid creating a new tests/js/tdollar_float.nim

- [ ] once this is green-lighted but before merge, I'll use the single argument `applyFormat` in jsgen (as I did for mFloatToStr) everywhere appropriate to make code DRY

## after PR
I'm thinking to introduce a compiler flag (eg `--ecmascript:es5`) to let users choose which js version they want to target. The `Number.isInteger` I'm using in this PR is available on all browsers but not on IE, but there is a polyfill we can easily introduce for that, say in `std/jspolyfills`. The workaround implementation should be used or not depending on the desired js version in `--ecmascript`; `BigInt` could for example be introduced for `int` for  `--ecmascript:es2020`

## 
ci failures unrelated

### CODE REVIEW

**Comment by metagn** [comment]
#7605 is the same as the issue in your repo

**Comment by timotheecour** [comment]
thanks! updated the PR msg; this PR will allow you to not change the test (or, better, to increase test coverage by using both float+int) in tpegs.nim in your PR https://github.com/nim-lang/Nim/issues/4247

File: lib/system/jssys.nim [hunk 1]
```diff
@@ -476,6 +476,21 @@ proc negInt(a: int): int {.compilerproc.} =
 proc negInt64(a: int64): int64 {.compilerproc.} =
   result = a*(-1)
 
+proc nimFloatToString(a: float): cstring {.compilerproc.} =
+  ## ensures the result doesn't print like an integer, ie return 2.0, not 2
+  asm """
+    function nimOnlyDigitsOrMinus(n) {
+      return n.toString().match(/^-?\d+$/);
+    }
+    if (Number.isSafeInteger(`a`)) `result` =  `a`+".0"
```
Comment (metagn) [inline lib/system/jssys.nim:485]:
```suggestion
    var abs = Math.abs(`a`)
    if (!isFinite(`a`)) `result` = `a`.toString();
    else if (abs >= 1e15 || abs < 1e-4) `result` = `a`.toExponential();
    else if (Math.floor(`a`) == `a`) `result` = `a`.toFixed(1);
    else `result` = `a`.toString();
```

A combination of [toExponential](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toExponential) and [toFixed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) might be useful here. They both have IE support.

`toFixed` expands the exponential up to 1e20 whereas Nim's C backend expands the exponential up to 1e15, so we can reflect that here. Ditto for JS: 1e-6 and C: 1e-4, you can change the abs comparisons to the JS limits if you like

Changed to `Math.floor(a) == a` since that's what the MDN polyfill uses and we have to account for `!isFinite(a)`.

Comment (timotheecour) [reply lib/system/jssys.nim:485]: * this would print 0.0 as 0e+0 (ok, easy to fix)
> They both have IE support.

That shouldn't be the criterion, for same reason as i gave in https://github.com/nim-lang/RFCs/issues/187#issuecomment-619561119 ; the correct way IMO is to use the more standard / newer features + provide polyfills for those so that we get the best of both worlds:
* old browsers (= IE in practice) still work thanks to our polyfill
* new browsers/node benefit from a (likely) higher performance from that builtin function

We can also use `--jsversion:es5|es6|...` to branch at CT on what's generated

* same argument holds for BigInt (but obviously that's a trickier, separate issue)

that being said, it'd be good to have c,vm,js be consistent as much as possible; where did you find those consants in nim code?

EDIT: u mean `var n: int = c_sprintf(addr buf, "%.16g", value)` ? (in formatfloat.writeFloatToBuffer)

(note also that this may change when ryu comes, and idk whether there's a ryu library for js; but again, matching backends is a best-effort thing, not a spec thing; what shd be in spec is that floats dont' look like ints)

Comment (metagn) [reply lib/system/jssys.nim:485]: Yeah, I don't care for IE support either but it's still an upside. I'm sure V8/SpiderMonkey can optimize `Math.floor(x) == x` as well as `isInteger`. I've made a small (probably bullcrap) [benchmark](https://jsben.ch/7uaLM) that can show `Math.floor(x)` winning on a cold JIT, presumably due to no `typeof` checks. Still shouldn't matter too much.

I didn't look for constants I tested values, but yes that line must be the reason.

If we implement ryu in pure Nim then we won't need a JS library for it (of which there is none), or one could just use WASM.

Comment (timotheecour) [reply lib/system/jssys.nim:485]: so looks like it's gonna be hard to match exactly what `nim c` or `nim vm` produces because it's already inconsistent across OS, see https://github.com/timotheecour/Nim/issues/138, and I'm not sure it's simple to reproduce what sprintf prints. So I'm instead leaving it at the formula from the PR which at least fixes the bug it was intended to fix (print floats so they  don't look like int's); further tweaks can be done in other PR's if needed.

(and yes, we need better wasm interop, it'd simplify lots of things, in particular performance; separate topic though; my best luck with nim+wasm was through emscripten so far)

Comment (metagn) [reply lib/system/jssys.nim:485]: I didn't mean to shift the focus to consistency, correctness is best above all, which is why I'd recommend you try a hand at #7169 next.

You left a small mistake in your code, in nimOnlyDigitsOrMinus it does `n.toString()` even though the argument is a string. Beyond that, I have an alternative to my previous solution that's cleaner and focused on correctness, in case you decide against using regex.

```js
var abs;
if (`a` === 0) `result` = "0.0";
else if (!isFinite(`a`) || (abs = Math.abs(`a`), abs) >= 1e20 || abs < 1e-6 || Math.floor(`a`) !== `a`) `result` = `a`+"";
else `result` = `a`+".0";
```

There are a couple things you can do here, replace `+".0"` with toFixed(1) and `+""` with toString(), you can remove the `abs` variable and just call Math.abs twice (it's practically an OR on a bit), you can use !Number.isInteger instead of Math.floor !== a, you can get rid of the a === 0 branch and replace `abs < 1e-6` with `(a !== 0 && abs < 1e-6)`.
