### PR TITLE
RST heading improvements (fix #17091)

### LINKED ISSUE #17091: rst should error when using incorrect heading hierarchies (root cause for manual.rst not rendering as RST in github)
### Example 1
```
Heading1
========

Heading2
--------

Heading3
~~~~~~~~

Heading4
========

Heading5
~~~~~~~~
```

nim rst2html -r main.rst

### Current Output
no warning nor error, but the rst file will not render as rst in github (and maybe other tools) because an intermediate level heading is needed between Heading4 and Heading 5. See https://github.com/github/markup/issues/1446 which I just filed after a painful binary search to figure out why manual.rst wasn't rendering properly in github

### Expected Output
either give a warning or error mentioning that a heading level was skipped and that it won't render in github.

### Example 2
manual.rst suffers from this, see https://github.com/nim-lang/Nim/blob/devel/doc/manual.rst which renders as raw text instead of RST in github
(I'm fixing manual.rst in https://github.com/nim-lang/Nim/pull/17092)

### Additional Information
1.5.1 301d78425649026636e6f840f6d2aeb2ea6cbc05

### PR DESCRIPTION
**Pull request by a-mr**
* fix #17091 : now heading hierarchy is checked for RST-style headings and a detailed error message is printed
* overline and underline styles constitute single hierarchy in compliance with [the spec](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#sections). Previously they were treated independently of each other. 
* fix subtitle handling. [This is defined in official quickstart](https://docutils.sourceforge.io/docs/user/rst/quickstart.html#document-title-subtitle). Now the second consecutive overline that has no peers (nodes with the same overline+symbol style) is recognized as subtitle. (now this peers check is applied for an overline setting main title too). Previously every second overline just disappeared. Though a part of the code for displaying subtitle was already in `rstgen.nim`. An example of title+subtitle definition from the spec:
```
================
 Document Title
================
----------
 Subtitle
----------

Section Title
=============
```
"Section Title" can be defined in overline style now since third and subsequent overlines are considered as sections. The spec is not really clear on this, I played with python rst2html to verify it.

cc @narimiran

### CODE REVIEW

File: lib/packages/docutils/rst.nim [hunk 1]
```diff
@@ -410,7 +414,14 @@ proc getTokens(buffer: string, skipPounds: bool, tokens: var TokenSeq): int =
     tokens[0].kind = tkIndent
 
 type
-  LevelMap = array[char, int]
+  LevelInfo = tuple
```
Comment (narimiran) [inline lib/packages/docutils/rst.nim]: I personally don't mind, but I know that the usual practice in Nim's codebase is to use `object`, not `tuple`.

And since you already use `(symbol: c, hasOverline: hasOverline, line: curLine(p), hasPeers: false)` (line 1425), it shouldn't be too big of the change.

**Review by narimiran — COMMENTED** [review]
I'd like to see a test where you mix rst- and markdown-headlines in the same file. Is everything rendered as expected?

**Comment by a-mr** [comment]
> I'd like to see a test where you mix rst- and markdown-headlines in the same file. Is everything rendered as expected?

It depends on the definition of expected  here :-)

Currently RST and Markdown headings just don't interfere with each other. And Markdown headings are not checked, so it's still possible to mix them inside one document without any limitations and break (visually) the aforementioned RST heading hierarchy by inserting Markdown:

```rst
(Paragraph)

Level 1 RST
===========

##### Markdown Level 5 (what?!!)
```
and our parser won't complain — they will be rendered as `<h1>` and `<h5>` respectively.

I added a test that they can co-exist together in this way.
