### PR TITLE
fix #16542

### LINKED ISSUE #16542: hash float doesn't work in JS or VM backend
```nim
import hashes

echo hash(0.3456)
```
devel

Output:

```
D:\QQPCmgr\Desktop\Nim\pair.js:265
          var res   = hi_xor_lo_js(hi_xor_lo_js(P0, BigInt(x_486539499) ^ P1), P58);
                                                    ^

RangeError: The number 0.3456 cannot be converted to a BigInt because it is not an integer
```

I will revisit https://github.com/nim-lang/Nim/pull/16403 and make it work for JS backend.

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

File: lib/pure/hashes.nim [hunk 1]
```diff
@@ -198,7 +198,20 @@ else:
...
+    when not defined(js):
+      result = hash(cast[Hash](y))
+    else:
+      var res: Hash
+      asm """const buffer = new ArrayBuffer(8);
+      const floatBuffer = new Float64Array(buffer);
+      const uintBuffer = new BigUint64Array(buffer);
+      floatBuffer[0] = `y`;
+      `res` = uintBuffer[0];
+  """
```
Comment (timotheecour) [inline lib/pure/hashes.nim]:
```suggestion
      `res` = uintBuffer[0];"""
```

**Comment by ringabout** [comment]
After this PR, `hash(float)` works both in JS and VM backend.

Notes that `hash(float)` never worked in JS backend. So I won't fix it in this PR. `bigInt` PR needs to be merged first.

- [x] In the next PR make a workaround for platforms doesn't support BigUint64Array
```nim
const buffer = new ArrayBuffer(8);
const floatBuffer = new Float64Array(buffer);
const uintBuffer = new Uint32Array(buffer);
floatBuffer[0] = x_503316698;
result_503316699 = uintBuffer[1];
```

see https://bugs.webkit.org/show_bug.cgi?id=190800

File: tests/stdlib/thashes.nim [hunk 2]
```diff
@@ -75,3 +75,15 @@ block largeSize: # longer than 4 characters
   doAssert hash(xx) == hash(ssl, 0, 4)
   doAssert hash(xx, 0, 3) == hash(xxl, 0, 3)
   doAssert hash(xx, 0, 3) == hash(ssl, 0, 3)
+
+proc main() =
```
Comment (timotheecour) [inline tests/stdlib/thashes.nim:79]: for future work:
unfortunately wrapping the other blocks inside main fails at CT:
`Error: cannot generate code for: mSlice`

File: lib/pure/hashes.nim [hunk 3]
```diff
@@ -197,8 +197,29 @@ else:
 
 proc hash*(x: float): Hash {.inline.} =
   ## Efficient hashing of floats.
-  var y = x + 0.0 # for denormalization
-  result = hash(cast[ptr Hash](addr(y))[])
+  let y = x + 0.0 # for denormalization
+  when nimvm:
+    when defined(js):
+      # workaround a JS VM bug
+      # TODO see issue #16547
```
Comment (timotheecour) [inline lib/pure/hashes.nim]:
```suggestion
      # workaround a JS VM bug: bug #16547
```
https://nim-lang.github.io/Nim/contributing.html
> Always refer to a GitHub issue using the following exact syntax: bug #1234 as shown above, so that it's consistent and easier to search or for tooling [...]

File: lib/pure/hashes.nim [hunk 4]
```diff
@@ -197,8 +197,29 @@ else:
...
+      var res: Hash
+      asm """const buffer = new ArrayBuffer(8);
+    const floatBuffer = new Float64Array(buffer);
+    const uintBuffer = new BigUint64Array(buffer);
+    floatBuffer[0] = `y`;
+    `res` = uintBuffer[0];"""
+
+      # res is a `BigInt` type, but we cheat the type system
+      # and say it is a `Hash` type.
+      # TODO refactor it using bigInt once jsBigInt is ready
```
Comment (timotheecour) [inline lib/pure/hashes.nim]:
```suggestion
      # TODO refactor it using bigInt once jsBigInt is ready, pending pr #16409
```

(links makes it easier to search and for tooling)

File: tests/stdlib/thashes.nim (hunk 2 above)
Comment (ringabout) [reply tests/stdlib/thashes.nim:79]: Yeah, I tried them too :(

Comment (ringabout) [reply tests/stdlib/thashes.nim:79]:
```nim
import hashes

proc main() =
  echo hash(cstring"abracadabra")

static: main()
```

Comment (xflywind) [reply tests/stdlib/thashes.nim:79]: Even for string types

It doesn't print 
```nim
import hashes

proc main() =
  echo hash("abracadabra")

static: main()
main()
```

Comment (timotheecour) [reply tests/stdlib/thashes.nim:79]: that's https://github.com/nim-lang/Nim/issues/16061 I think

Comment (ringabout) [reply tests/stdlib/thashes.nim:79]: After fixing that, RT still prints wrong result:
```nim
import hashes

proc main() =
  echo hash(cstring"abracadabra")

static: main()
main()
```
both in JS/C VM vs gen
97309975
0

Comment (ringabout) [reply tests/stdlib/thashes.nim:79]: I will fix them(may be after this PR)

File: lib/pure/hashes.nim [hunk 5]
```diff
@@ -197,8 +197,28 @@ else:
...
+      asm """const buffer = new ArrayBuffer(8);
+    const floatBuffer = new Float64Array(buffer);
+    const uintBuffer = new BigUint64Array(buffer);
+    floatBuffer[0] = `y`;
+    `res` = uintBuffer[0];"""
+
+      # res is a `BigInt` type, but we cheat the type system
+      # and say it is a `Hash` type.
+      # TODO refactor it using bigInt once jsBigInt is ready, pending pr #1640
+      result = hashWangYi1(res)
```
Comment (timotheecour) [inline lib/pure/hashes.nim]: how about this to make it easier to evolve/reuse/generalize `asBigInt` in future work
```nim
when defined(js):
  proc asBigInt(x: float): int64 =
    # result is a `BigInt` type in js, but we cheat the type system
    # and say it is a `int64` type.
    # TODO refactor it using bigInt once jsBigInt is ready, pending pr #1640
    asm """
    const buffer = new ArrayBuffer(8);
    const floatBuffer = new Float64Array(buffer);
    const uintBuffer = new BigUint64Array(buffer);
    floatBuffer[0] = `x`;
    `result` = uintBuffer[0];"""

proc hash*(x: float): Hash {.inline.} =
  ## Efficient hashing of floats.
  let y = x + 0.0 # for denormalization
  when nimvm:
    when defined(js):
      # workaround a JS VM bug: bug #16547
      result = hashWangYi1(cast[int64](y))
    else:
      result = hashWangYi1(cast[Hash](y))
  else:
    when not defined(js):
      result = hashWangYi1(cast[Hash](y))
    else:
      result = hashWangYi1(asBigInt(y))
```

Comment (ringabout) [reply lib/pure/hashes.nim]: I see, thanks

File: tests/stdlib/thashes.nim [hunk 6]
```diff
@@ -75,3 +75,26 @@ block largeSize: # longer than 4 characters
...
+  block:
+    doAssert hash(0.0) == hash(0)
+    doAssert hash(1.0) != 0
+    doAssert hash(-1.0) != 0
+    doAssert hash(1000.0) != 0
+    doAssert hash(-1000.0) != 0
+
```
Comment (timotheecour) [inline tests/stdlib/thashes.nim]: stronger test:
```suggestion
    doAssert hash(0.0) == hash(0)
    var s: seq[Hash]
    for a in [0.0, 1.0, -1.0, 1000.0, -1000.0]:
      let b = hash(a)
      doAssert b notin s
      s.add b

```

File: lib/pure/hashes.nim (hunk 5 above)
Comment (xflywind) [reply lib/pure/hashes.nim:221]:
```nim
block hashes:
  block hashing:
    var dummy = 0.0
    doAssert hash(dummy) == hash(-dummy)
```
can't pass this test

File: tests/stdlib/thashes.nim (hunk 6 above)
Comment (ringabout) [reply tests/stdlib/thashes.nim]: thanks

**Review by timotheecour — APPROVED** [review]
excellent

File: lib/pure/hashes.nim [hunk 7]
```diff
@@ -195,10 +195,29 @@ else:
...
+    `result` = uintBuffer[0];"""
+
 proc hash*(x: float): Hash {.inline.} =
   ## Efficient hashing of floats.
-  var y = x + 0.0 # for denormalization
-  result = hash(cast[ptr Hash](addr(y))[])
+  let y = x + 0.0 # for denormalization
+  when nimvm:
+    # workaround a JS VM bug: bug #16547
+    result = hashWangYi1(cast[int64](float64(y)))
```
Comment (timotheecour) [inline lib/pure/hashes.nim:215]: on 32 bit cpu, Hash is int, not int64; is this inefficient there?

Comment (ringabout) [reply lib/pure/hashes.nim:215]: I need to workaround a VM bug in 32 bit cpu.

File: tests/stdlib/thashes.nim [hunk 8]
```diff
@@ -75,3 +75,32 @@ block largeSize: # longer than 4 characters
   doAssert hash(xx) == hash(ssl, 0, 4)
   doAssert hash(xx, 0, 3) == hash(xxl, 0, 3)
   doAssert hash(xx, 0, 3) == hash(ssl, 0, 3)
+
+proc main() =
+  doAssert hash(0.0) == hash(0)
+  when sizeof(int) == 8:
```
Comment (ringabout) [inline tests/stdlib/thashes.nim:81]: see follow-up PR https://github.com/nim-lang/Nim/pull/16551

File: tests/stdlib/thashes.nim [hunk 9]
```diff
@@ -96,10 +96,10 @@ proc main() =
       doAssert hash(-9999.283456) == 5876943921626224834
       doAssert hash(84375674.0) == 1964453089107524848
   else:
-    doAssert hash(0.345602) == 2035867618
-    doAssert hash(234567.45) == -20468103
-    doAssert hash(-9999.283456) == -43247422
-    doAssert hash(84375674.0) == 707542256
+    doAssert hash(0.345602) != 0
```
Comment (timotheecour) [inline tests/stdlib/thashes.nim:99]: weak test, doesn't check that
`hash(x) == static(hash(x))` in this branch
