### PR TITLE
fix #17630: Implement cycle detection for recursive concepts

### LINKED ISSUE #17630: [Concepts] Recursive concepts cause a compiler segfault when testing with `is`
### Example
```nim
type
  A = concept
    proc test(x: Self, y: A)

proc test(x: int, y: int) = discard

discard (int is A)
```

### Current Output
The compiler crashes.
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
An error message or successful compilation.

### Possible Solution
* Disallow referring to the concept being defined inside its definition.

### PR DESCRIPTION
**Pull request by elijahr**
fixes #17630

## Recursive Concept Cycle Detection

- Track (conceptId, typeId) pairs during matching to detect cycles
- Changed marker from IntSet to HashSet[ConceptTypePair]
- Removed unused depthCount field
- Added recursive concepts documentation to manual
- Added tests for recursive concepts, distinct chains, and co-dependent concepts

## Fix Flaky `tasyncclosestall` Test

The macOS ARM64 CI jobs were failing due to a flaky async socket test (unrelated to concepts).

The test only accepted `EBADF` as a valid error code when closing a socket with pending writes. However, depending on timing, the kernel may report `ECONNRESET` or `EPIPE` instead:

- **EBADF**: Socket was closed locally before kernel detected remote state
- **ECONNRESET**: Remote peer sent RST packet (detected first)  
- **EPIPE**: Socket is no longer connected (broken pipe)

All three are valid disconnection errors. The fix accepts any of them, making the test reliable across platforms.

### CODE REVIEW

File: compiler/concepts.nim [hunk 1]
```diff
@@ -188,32 +190,48 @@ iterator traverseTyOr(t: PType): PType {. closure .}=
...
-    # concepts that are more then 2 levels deep are treated like
-    # tyAnything to stop dependencies from getting out of control
+
+  # Handle self-referential concepts: when a concept references itself in its body
+  # (e.g., `A = concept; proc test(x: Self, y: A)`), the inner type A has n=nil.
+  # We detect this by checking if the concept has the same symbol name as the
+  # one we're currently matching and has no body (n=nil).
+  if concpt.n.isNil:
+    if concpt.sym != nil and m.concpt.sym != nil and
+       concpt.sym.name.s == m.concpt.sym.name.s:
```
Comment (Araq) [inline compiler/concepts.nim]:
```suggestion
       concpt.sym == m.concpt.sym:
```

File: compiler/concepts.nim [hunk 2]
```diff
@@ -73,18 +73,20 @@ type
   MatchFlags* = enum
     mfDontBind  # Do not bind generic parameters
     mfCheckGeneric  # formal <- formal comparison as opposed to formal <- operand
-  
+
+  ConceptTypePair = tuple[conceptId, typeId: int]
```
Comment (Araq) [inline compiler/concepts.nim]:
```suggestion
  ConceptTypePair = tuple[conceptId, typeId: ItemId]
```
