### PR TITLE
fix #13543 (CI will break every 4 years on feb 29)  and add times.isLeapDay

### LINKED ISSUE #13543: CI will break every 4 years on feb 28: times doesn't handle leap years properly
```
Hint: /Users/timothee/git_clone/nim/Nim_devel/testament/testament --nim:./bin/nim r tests/stdlib/ttimes.nim [Exec]
FAIL: tests/stdlib/ttimes.nim C
Test "tests/stdlib/ttimes.nim" in category "tests"
Failure: reExitcodesDiffer
Expected:
exitcode: 0

Gotten:
exitcode: 1

Output:
[Suite] ttimes
    /Users/timothee/git_clone/nim/Nim_devel/tests/stdlib/ttimes.nim(354, 26): Check failed: now + 13.months == now + 1.years + 1.months
    now + 13.months was 2021-03-29T10:14:35Z
    now + 1.years + 1.months was 2021-04-01T10:14:35Z
    /Users/timothee/git_clone/nim/Nim_devel/tests/stdlib/ttimes.nim(359, 14): Check failed: ti1 == now
    ti1 was 2020-03-01T10:14:35Z
    now was 2020-02-29T10:14:35Z
    /Users/timothee/git_clone/nim/Nim_devel/tests/stdlib/ttimes.nim(361, 14): Check failed: ti1 == now + 1.days
    ti1 was 2020-03-02T10:14:35Z
    now + 1.days was 2020-03-01T10:14:35Z
  [FAILED] adding/subtracting TimeInterval
ttimes.nim(476)          ttimes
times.nim(2433)          parse
times.nim(2412)          parse
times.nim(2287)          toDateTime
times.nim(1814)          raiseParseException

    Unhandled exception: Failed to parse '1' with format 'YYYY'. 1-02-29 is not a valid date [TimeParseError]
  [FAILED] parse

PASS: tests/stdlib/ttimes.nim JS                                   ( 4.41340017 secs)
```

nim devel 1056f9ecff60f624522f24e508d0976994bcef80 1.1.1

## analysis
lol, I think this test will fail around the 28th of february each year; so it's kind of a serious bug as it can have business case impact with really hard to find bugs
```nim
import times
proc main()=
  let now = getTime().utc
  echo now
  echo now+13.months
  echo now+12.months
  echo now+1.years
  echo now+1.years-1.days
  # echo now+1.mon
  # check now + 13.months == now + 1.years + 1.months
main()
```

```
2020-02-29T10:32:17Z
2021-03-29T10:32:17Z
2021-03-01T10:32:17Z
2021-03-01T10:32:17Z
2021-02-28T10:32:17Z
```
the problem is that 2020-02-29T10:32:17Z + 1 year is 2021-03-01T10:32:17Z because 2020 is a leap year (has feb 29), unlike next year

`times` should properly handle this important use case; maybe we can take a look at how other libs handle this eg https://dlang.org/phobos/std_datetime.html

### PR DESCRIPTION
**Pull request by timotheecour**
* fix https://github.com/nim-lang/Nim/issues/13543
I could've fixed this without exporting a new symbol isLeapDay, but IMO any application that deals with time calculations may want to have this anyway

see also note in https://github.com/nim-lang/Nim/issues/13543#issuecomment-593047347

### CODE REVIEW

File: tests/stdlib/ttimes.nim [hunk 1]
```diff
@@ -345,20 +345,24 @@ suite "ttimes":
...
     let now = getTime().utc
+    let isSpecial = now.isLeapDay
     check now + convert(Seconds, Nanoseconds, 1).nanoseconds == now + 1.seconds
     check now + 1.weeks == now + 7.days
     check now - 1.seconds == now - 3.seconds + 2.seconds
     check now + 65.seconds == now + 1.minutes + 5.seconds
     check now + 60.minutes == now + 1.hours
     check now + 24.hours == now + 1.days
-    check now + 13.months == now + 1.years + 1.months
+    if not isSpecial:
```
Comment (Clyybber) [inline tests/stdlib/ttimes.nim:355]: Just write `now.isLeapDay` directly

Comment (timotheecour) [reply tests/stdlib/ttimes.nim:355]: less DRY so not a clear improvement (I'm reusing it in a few places)

Comment (Clyybber) [reply tests/stdlib/ttimes.nim:355]: Lol, what? And introducing a new variable that literally does nothing except for obfuscating the intent is more DRY?
Anyways doesn't matter, its just a test anyways :)
