### PR TITLE
properly fix #10053 ; `FieldDefect` msg now shows discriminant value + lineinfo, in all backends (c,vm,js)

### LINKED ISSUE #10053: Better FieldError exception messages
\<insert summary here\>

### Example

\<insert example here\>

### Current Output

```
`Error: unhandled exception: sons is not accessible [FieldError]`
```

### Expected Output

```
Error: unhandled exception: sons is not accessible for `otherKind` [FieldError]
```

### Possible Solution
`Error: unhandled exception: sons is not accessible [FieldError]` should show `kind` in error msg for an object variant

### PR DESCRIPTION
**Pull request by timotheecour**
this PR is a followup after https://github.com/nim-lang/Nim/pull/11951 to show more informative FieldError msg. 
* for c/js targets, adds in errmsg the runtime discriminant **value** (eg `k1`) (not just the compile time symbol name (`kind`), which isn't quite as useful for debugging) + offending lineinfo (so that you'll get useful diagnostic even with -d:release)
* adds support for VM 

this shouldn't add any runtime cost
## example
```nim
when true: # D20210812T133052
  type Kind = enum k1, k2
  type Foo = object
    case kind: Kind
    of k1: f1: int
    of k2: f2: int
  proc main()=
    var foo = Foo()
    echo foo.f2
  when defined case_vm:
    static: main()
  when defined case_rt:
    main()
```

nim r -d:case8 -d:case_rt main
nim r -d:case8 -d:case_vm main

## before PR
-d:case_rt:
Error: unhandled exception: 'f2' is not accessible using discriminant 'kind' of type 'Foo' [FieldDefect]
-d:case_vm:
t11373.nim(164, 13) Error: node lacks field: f2

## after current PR
-d:case_rt:
t11373.nim(164, 13) field 'f2' is not accessible for type 'Foo' [discriminant declared in tests/nim/all/t11373.nim(159, 10)] using 'kind = k1' [FieldDefect]

-d:case_vm:
t11373.nim(164, 13) Error: field 'f2' is not accessible for type 'Foo' [discriminant declared in tests/nim/all/t11373.nim(159, 10)] using 'kind = k1'

=> shows the crucial actual discriminant `k1` + relevant information

## note 1
the existing `--declaredlocs` controls whether to output locations in error msgs; without the flag it'd show:

Error: unhandled exception: field 'f2' is not accessible for type 'Foo' using 'kind = k1' [FieldDefect]

instead of:

t11373.nim(165, 13) field 'f2' is not accessible for type 'Foo' [discriminant declared in tests/nim/all/t11373.nim(160, 10)] using 'kind = k1' [FieldDefect]

## note 2
works in all backends and tries to reuse code across backends where possible (c,js,vm)
for newruntime (eg --gc:arc), the error messge shows the ordinal number instead of symbol name because we lack RTTI in newruntime; this can be improved in future work by serializing the enum strings and making it accessible to the runtime

### CODE REVIEW

**Comment by PMunch** [comment]
Any particular reason why this hasn't been merged? These error messages are extremely unhelpful as they are now..

**Comment by timotheecour** [comment]
> Any particular reason why this hasn't been merged?

back in the day it was green, but received 0 attention, and now I need to rebase to fix conflicts; on my TODO list.

> These error messages are extremely unhelpful as they are now..

indeed

File: compiler/ccgexprs.nim [hunk 1]
```diff
@@ -869,16 +871,31 @@ proc genFieldCheck(p: BProc, e: PNode, obj: Rope, field: PSym) =
...
-              [rdLoc(test), strLit, raiseInstr(p)])
-    else:
-      linefmt(p, cpsStmts,
-              "if (!($1)){ #raiseFieldError($2); $3}$n",
-              [rdLoc(test), strLit, raiseInstr(p)])
+    var msg = toFileLineCol(p.config, e.info)
+      # shows the most relevant lineinfo even with -d:release;
+      # should have no runtime cost (unlike -d:stacktrace)
+      # this could be added to all/most chcks.nim errors, and perhaps
+      # can be disabled with a compile flag.
```
Comment (Clyybber) [inline compiler/ccgexprs.nim]: This should respect the normal stacktrace configuration options.
Introducing an option to show locations of errors without a stacktrace can be added in a seperate PR.

File: compiler/ccgexprs.nim [hunk 2]
```diff
@@ -869,16 +871,31 @@ proc genFieldCheck(p: BProc, e: PNode, obj: Rope, field: PSym) =
...
+    msg.add " " & genFieldDefect(p.config, field, disc.sym)
+
+    template newLitRope(s: string): untyped = genStringLiteral(p.module, newStrNode(nkStrLit, s))
+    let strLit = newLitRope(msg)
+    ## discriminant check
+    template fun(code) = linefmt(p, cpsStmts, code, [rdLoc(test)])
+    if op.magic == mNot: fun("if ($1) ") else: fun("if (!($1)) ")
+
+    ## raiseFieldError2 on failure
+    if optTinyRtti in p.config.globalOptions: # optNimV2 disappeared in 61ea85687c2950bb40c23a1a7cd2c13473bd9662
```
Comment (Clyybber) [inline compiler/ccgexprs.nim]:
```suggestion
    if optTinyRtti in p.config.globalOptions:
```

File: compiler/ccgexprs.nim [hunk 3]
```diff
@@ -869,16 +871,31 @@ proc genFieldCheck(p: BProc, e: PNode, obj: Rope, field: PSym) =
...
+      const code = "{ #raiseFieldError2($1, $2); $3} $n"
+      linefmt(p, cpsStmts, code, [strLit, newLitRope("(repr unavailable in newruntime)"), raiseInstr(p)])
```
Comment (Clyybber) [inline compiler/ccgexprs.nim]: repr is now available in --newruntime/arc/orc so it should be used.

File: compiler/ccgexprs.nim [hunk 4]
```diff
@@ -1561,10 +1578,13 @@ proc genNewFinalize(p: BProc, e: PNode) =
   initLocExpr(p, e[1], a)
   initLocExpr(p, e[2], f)
   initLoc(b, locExpr, a.lode, OnHeap)
+
+  # xxx use `genTypeInfo`
```
Comment (Clyybber) [inline compiler/ccgexprs.nim]: Should be addressed or removed in this PR

File: compiler/vmgen.nim [hunk 5]
```diff
@@ -1712,13 +1723,25 @@ proc genCheckedObjAccessAux(c: PCtx; n: PNode; dest: var TDest; flags: TGenFlags
...
   c.freeTemp(rs)
-  let strType = getSysType(c.graph, n.info, tyString)
-  var fieldNameRegister: TDest = c.getTemp(strType)
-  let strLit = newStrNode($accessExpr[1], accessExpr[1].info)
-  strLit.typ = strType
-  c.genLit(strLit, fieldNameRegister)
-  c.gABC(n, opcInvalidField, fieldNameRegister)
-  c.freeTemp(fieldNameRegister)
+
+  when false: # PRTEMP
```
Comment (Clyybber) [inline compiler/vmgen.nim]: `PRTEMP` :)

File: lib/system/repr.nim [hunk 6]
```diff
@@ -77,6 +77,12 @@ proc reprEnum(e: int, typ: PNimType): string {.compilerRtl.} =
 
   result = $e & " (invalid data!)"
 
+proc reprDiscriminant(e: int, typ: PNimType): string {.compilerRtl.} =
+  case typ.kind
+  of tyEnum: reprEnum(e, typ)
+  of tyBool: (if e == 0: "false" else: "true")
+  else: $e
```
Comment (Clyybber) [inline lib/system/repr.nim]: Should probably use `reprAux` instead.

File: compiler/vmgen.nim (hunk 5 above)
Comment (timotheecour) [reply compiler/vmgen.nim]: fixed

File: compiler/ccgexprs.nim (hunk 4 above)
Comment (timotheecour) [reply compiler/ccgexprs.nim]: fixed

File: compiler/ccgexprs.nim (hunk 3 above)
Comment (timotheecour) [reply compiler/ccgexprs.nim]: that doesn't help much for RTTI though, all i can get is the `ord`, not the corresponding symbol string; the latest commits now show at least the ord instead of `repr unavailable in newruntime` for newruntime (eg gc:arc)

File: compiler/ccgexprs.nim (hunk 2 above)
Comment (timotheecour) [reply compiler/ccgexprs.nim]: fixed

File: compiler/ccgexprs.nim (hunk 1 above)
Comment (timotheecour) [reply compiler/ccgexprs.nim]: `--stacktrace` is unrelated and incurs runtime costs; lots of error messages show location info (eg assert errors)

File: lib/system/repr.nim (hunk 6 above)
Comment (timotheecour) [reply lib/system/repr.nim]: fixed by using `of tyBool: $(e != 0)`

**Comment by timotheecour** [comment]
@Araq this PR is now ready, and i've finally implemented support in all backends
