### PR TITLE
fix #16978 unittest js foreign exception

### LINKED ISSUE #16978: Unittest does not notice JS errors
In JS:

### Example
```nim
import unittest

test "Bad test":
  var x: cstring = nil
  discard x[0]
```

### Current Output
```
[OK] Bad test
<test file path>.js:4787       
var eTypeDesc_13450001 = (makeNimstrLit("[") || []).concat(cstrToNimstr(e_13445602.name) || [],makeNimstrLit("]") 
|| []);


       ^

TypeError: Cannot read property 'name' of null
    at Object.<anonymous> (<test file path>.js:4787:84)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)        
    at Function.executeUserEntryPoint 
[as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

### Expected Output
Test fails with stack trace of TypeError from JS.

### Possible Solution

The issue is that the current exception in JS is nil if it's from JS. There could be a `JsException` type or something that wraps these exceptions.

```
$ nim -v
Nim Compiler Version 1.4.2
```

### PR DESCRIPTION
**Pull request by timotheecour**
fix #16978

### CODE REVIEW

File: lib/pure/unittest.nim [hunk 1]
```diff
@@ -515,7 +515,9 @@ template suite*(name, body) {.dirty.} =
     finally:
       suiteEnded()
 
-template exceptionTypeName(e: typed): string = $e.name
+proc exceptionTypeName(e: ref Exception): string {.inline.} =
+  if e == nil: "<foreign exception>"
```
Comment (juancarlospaco) [inline lib/pure/unittest.nim:519]: I like the change, 
but is possible to detect that the target is JavaScript, then use:
`"<JavaScript exception>"` ?.  :thinking:

Comment (timotheecour) [reply lib/pure/unittest.nim:519]: @juancarlospaco I think we can do even better, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name 
do you want to take a stab at it?
