### PR TITLE
semtypinst: don't wrap type nodes from expressions in static[T]

### LINKED ISSUE #18859: Weird static[T](T) type produced by type expression in generic type definition
### Example
```nim
import macros

macro symFromDesc(T: typedesc): untyped =
  let typ = getType(T)
  typ[1]

template produceType(T: typedesc): untyped =
  type
    XT = object
      x: symFromDesc(T)

  XT

type
  X[T] = produceType(T)

  Y = produceType(int)

var y: Y
static: echo "Y is ", typeof(y)
var x: X[int]
static: echo "X[int] is ", typeof(x)
```

### Current Output
```
Y is XT`gensym0
test.nim(21, 5) Error: invalid type: 'static[XT`gensym1](XT`gensym1)' in this context: 'X[system.int]' for var
```

### Expected Output
```
Y is XT`gensym0
X is XT`gensym1
```

or

```
Y is XT`gensym0
X is X[int]
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-09-16
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f8e185fec0d8f9caddc196a713fba196b14f8b6b
active boot switches: -d:release -d:nimUseLinenoise
```

### PR DESCRIPTION
**Pull request by alaviss**
Fixes #18859

### CODE REVIEW

File: compiler/semtypinst.nim [hunk 1]
```diff
@@ -548,7 +548,7 @@ proc replaceTypeVarsTAux(cl: var TReplTypeVars, t: PType): PType =
       result = n.typ.skipTypes({tyTypeDesc})
       # result = n.typ.base
     else:
-      if n.typ.kind != tyStatic:
+      if n.typ.kind != tyStatic and n.kind != nkType:
```
Comment (Araq) [inline compiler/semtypinst.nim:551]:
```suggestion
      if n.typ.kind notin {tyStatic, tyTypeDesc}:
```
