### PR TITLE
fixes #19724; don't be aggressive when you infer sink parameters

### LINKED ISSUE #19724: [ARC] Sink inference prevents the usage of stdlib procedures for functional style
Any stdlib procedure that gets sink inference applied to it can't be used as an argument to procedures like `map` or similar.

### Example
```nim
import std/[os, sequtils]

proc main = 
  let saves = @["/path/to/file.txt"].map(extractFilename)
  echo saves

main()
```

Found in https://github.com/WonkySpecs/rolldice

### Current Output
```
/home/dian/Projects/ficsraper/tast.nim(4, 37) Error: type mismatch: got <seq[string], proc (path: sink string): string{.noSideEffect, gcsafe, locks: 0.}>
but expected one of:
proc map[T, S](s: openArray[T]; op: proc (x: T): S {.closure.}): seq[S]
  first type mismatch at position: 2
  required type for op: proc (x: T): S{.closure.}
  but expression 'extractFilename' is of type: proc (path: sink string): string{.noSideEffect, gcsafe, locks: 0.}

expression: map(@["/path/to/file.txt"], extractFilename)
```

### Expected Output
Successful compilation and `@["file.txt"]`

### Additional Information
`--sinkInference:off` doesn't seem to work, I assume this is because sink inference is explicitly enabled for stdlib so a user flag can't override it.

### Workaround
In this specific case you can workaround it by using `mapIt`, but I assume there might be cases where it's harder to do.

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-04-14
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: dc4cc2dca53e3772efb3654a4ddbbe8350d1db43
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

File: tests/arc/topt_no_cursor.nim [hunk 1]
```diff
@@ -134,17 +134,16 @@ if dirExists(this.value):
   var
     :tmpD_1
     :tmpD_2
```
Comment (ringabout) [inline tests/arc/topt_no_cursor.nim]:
```suggestion
    :tmpD_3
```

File: tests/arc/topt_no_cursor.nim [hunk 2]
```diff
@@ -134,17 +134,16 @@ if dirExists(this.value):
...
-      :tmpD_3 = splitPath do:
+      :tmpD_3 = splitDrive do:
         wasMoved(:tmpD_2)
         `=copy`(:tmpD_2, this.value)
         :tmpD_2
-      :tmpD_3.tail)
+      :tmpD_3.path)
     :tmpD_1)
-  `=destroy`(:tmpD_3)
+  `=destroy`(:tmpD_2)
```
Comment (ringabout) [inline tests/arc/topt_no_cursor.nim]:
```suggestion
  `=destroy`(:tmpD_3)
```

File: tests/arc/topt_no_cursor.nim [hunk 3]
```diff
@@ -133,16 +133,15 @@ if dirExists(this.value):
     :tmpD, front: "") else:
   var
     :tmpD_1
-    :tmpD_2
     :tmpD_3
```
Comment (ringabout) [inline tests/arc/topt_no_cursor.nim]:
```suggestion
    :tmpD_2
    :tmpD_3
```
