### PR TITLE
fixes #22613; Default value does not work with object's discriminator

### LINKED ISSUE #22613: Default value does not work with object's discriminator
### Description

```nim
type
  K = enum
    A = "a"
    B = "b"
  
  T = object
    case kind: K = B
    of A:
      a: int
    of B:
      b: float
 
assert T().kind == B
```

### Nim Version

2.0.0

### Current Output

```text
AssertionDefect
```

### Expected Output

```text
ok
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #22613

will make a following PR on objects with a default descriminator and explicit fields initialization later.

### CODE REVIEW

File: compiler/semobjconstr.nim [hunk 1]
```diff
@@ -326,18 +327,48 @@ proc semConstructFields(c: PContext, n: PNode, constrCtx: var ObjConstrContext,
       if result.status == initPartial:
         collectOrAddMissingCaseFields(c, branchNode, constrCtx, result.defaults)
     else:
+      template collectBranchFields() =
```
Comment (Araq) [inline compiler/semobjconstr.nim]: Turn this into a proc and move it to the module scope.
