### PR TITLE
fixes #25324; Channel incorrectly takes a sink argument in refc

### LINKED ISSUE #25324: Channel incorrectly takes a sink argument, when in fact it performs a deep copy internally
### Nim Version

2.2.4

### Description

Since `Channel` deep-copies the payload, it doesn't really make sense that it takes a sink argument since this only leads to an extra copy.

If Channel is to take a sink, it should instead `move` the argument which may or may not be feasible.

### Current Output

```text

```

### Expected Output

```text

```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
… it performs a deep copy internally

fixes #25324

notes that
> Enabling `-d:nimPreviewSlimSystem` removes the import of `channels_builtin` in
  in the `system` module, which is replaced by [threading/channels](https://github.com/nim-lang/threading/blob/master/threading/channels.nim).

### CODE REVIEW

File: lib/system/channels_builtin.nim [hunk 1]
```diff
@@ -367,23 +367,35 @@ proc sendImpl(q: PRawChannel, typ: PNimType, msg: pointer, noBlock: bool): bool
...
-  ## `msg` is deeply copied. Doesn't block.
-  ##
-  ## Returns `false` if the message was not sent because number of pending items
-  ## in the channel exceeded `maxItems`.
-  result = sendImpl(cast[PRawChannel](addr c), cast[PNimType](getTypeInfo(msg)), unsafeAddr(msg), true)
-  when defined(gcDestructors):
+  proc trySend*[TMsg](c: var Channel[TMsg], msg: sink TMsg): bool {.inline.} =
+    ## Tries to send a message to a thread.
+    ##
+    ## `msg` is deeply copied. Doesn't block.
```
Comment (arnetheduck) [inline lib/system/channels_builtin.nim]: this comment is no longer accurate then?
