### PR TITLE
fixes #23635; tasks.toTask Doesn't Expect a Dot Expression

### LINKED ISSUE #23635: tasks.toTask Doesn't Expect a Dot Expression
### Description

Trying to pass a proc stored in an object does not compile.
Here is a minimal code example that triggers the issue.
```nim
import std/tasks

type
    Store = object
        run: proc (a: int) {.nimcall, gcsafe.}

proc hello(a: int) = echo a

var store = Store()
store.run = hello

let b = toTask store.run(13)
b.invoke()
```

A workaround for this is to wrap the call in a proc that can avoid the dot notation. 
For example, using the following lets it compile correctly.
```nim

proc runner(s: Store, n: int) =
    store.run(n)

let b = toTask runner(store, 13)
```

### Nim Version

Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2024-02-10
Copyright (c) 2006-2024 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
C:\Users\_\.choosenim\toolchains\nim-#devel\lib\std\tasks.nim(124, 20) toTask
C:\Users\_\.choosenim\toolchains\nim-#devel\lib\std\effecttraits.nim(54, 3) isGcSafe
C:\Users\_\.choosenim\toolchains\nim-#devel\lib\core\macros.nim(689, 24) expectKind
d:\dump\Git\_\prep_tests\network_runner\code_format.nim(15, 21) Error: Expected a node of kind nnkSym, got nnkDotExpr
```

### Expected Output

```text
Compilation followed by "13"
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #23635

### CODE REVIEW

File: lib/std/tasks.nim [hunk 1]
```diff
@@ -110,6 +110,19 @@ template addAllNode(assignParam: NimNode, procParam: NimNode) =
...
 
+proc analyseRootSym(s: NimNode): NimNode =
+  result = s
+  while true:
+    case result.kind
+    of nnkBracketExpr, nnkDerefExpr, nnkHiddenDeref,
+        nnkAddr, nnkHiddenAddr,
+        nnkObjDownConv, nnkObjUpConv:
+      result = result[0]
+    of {nnkDotExpr, nnkCheckedFieldExpr} + {nnkHiddenStdConv, nnkHiddenSubConv}:
```
Comment (Araq) [inline lib/std/tasks.nim]:
```suggestion
    of nnkDotExpr, nnkCheckedFieldExpr, nnkHiddenStdConv, nnkHiddenSubConv:
```
