### PR TITLE
fixes #23295; don't expand constants for complex structures

### LINKED ISSUE #23295: Wrong behaviour when wrapping a constant  object variant into a sequence at runtime
### Description

```
# This is a sample code, the first echo statement prints out the error
type
  A = object
    case w: uint8
    of 0:
      n: int
    else:
      other: string
const
  a = A(w: 0, n: 5)
  q = @[a]
let
  b = a

echo ">>> a=", a, " @[a][0]=", @[a][0] # a=(w: 0, n: 5) @[a][0]=(w: 0, n: 0) err
echo ">>> b=", b, " @[b][0]=", @[b][0] # a=(w: 0, n: 5) @[a][0]=(w: 0, n: 5) ok
echo ">>> q[0]=", q[0]                 # q[0]=(w: 0, n: 5)                   ok
```

### Nim Version

Nim Compiler Version 1.6.18 [Linux: amd64]
Compiled at 2024-02-05
Copyright (c) 2006-2023 by Andreas Rumpf

### Current Output

```text
>>> a=(w: 0, n: 5) @[a][0]=(w: 0, n: 0)
>>> a=(w: 0, n: 5) @[a][0]=(w: 0, n: 5)
>>> q[0]=(w: 0, n: 5)
```

### Expected Output

```text
>>> a=(w: 0, n: 5) @[a][0]=(w: 0, n: 5)
>>> a=(w: 0, n: 5) @[a][0]=(w: 0, n: 5)
>>> q[0]=(w: 0, n: 5)
```

### Possible Solution

no idea, the workaround is using `let` instead of `const`

### Additional Information

Nim compiler is compiled as part of `nimbus-eth1`

### PR DESCRIPTION
**Pull request by ringabout**
fixes #23295

### CODE REVIEW

**Comment by ringabout** [comment]
Or use `isCaseObj` to filter types

File: compiler/ccgcalls.nim [hunk 1]
```diff
@@ -139,8 +139,8 @@ proc fixupCall(p: BProc, le, ri: PNode, d: var TLoc,
         var list = initLoc(locCall, d.lode, OnUnknown)
         list.r = pl
         genAssignment(p, tmp, list, flags) # no need for deep copying
-        if canRaise: raiseExit(p)
         genAssignment(p, d, tmp, {})
+        if canRaise: raiseExit(p)
```
Comment (ringabout) [inline compiler/ccgcalls.nim]:
```suggestion
        if canRaise: raiseExit(p)
        genAssignment(p, d, tmp, {})
```

**Comment by ringabout** [comment]
One way or another, we should extend `dontInlineConstant` to case object variants because of the data structures of object variants stored in the VM. 

We can choose either apply `noinline` to `cnst` which is a complex constant (array, etc.) or we need to inspect the types or nodes of `cnst` in order to enforce `noinline` for object variants.
