### PR TITLE
fix testament regression: installed testament works again with testament r path

### LINKED ISSUE #519: can testament be installed?
testament currently relies on files known at CT in several places eg:
* `testament/lib/stdtest/specialpaths.nim`
* `nimRoot` eg:
```nim
  of "r", "run":
    # "/pathto/tests/stdlib/nre/captures.nim" -> "stdlib" + "tests/stdlib/nre/captures.nim"
    var subPath = p.key.string
    let nimRoot = currentSourcePath / "../.."
      # makes sure points to this regardless of cwd or which nim is used to compile this.
    doAssert dirExists(nimRoot/testsDir) # sanity check
    if subPath.isAbsolute: subPath = subPath.relativePath(nimRoot)
```
* (EDIT) getCurrentCompilerExe

### bug 1
this can cause problems if `testament` is installed (eg via choosenim)

according to @xflywind:
> Just the testament installed has issues, if I compile testament by myself, it is fine
```
nim c -r testament/testament.nim r tests/errmsgs/t1154.nim ok
testament/testament.exe r tests/errmsgs/t1154.nim ok
testament r tests/errmsgs/t1154.nim
testament.nim(798, 14) dirExists(nimRoot / testsDir) [AssertionDefect]
```
EDIT: now shows:
> Error: unhandled exception: testament.nim(798, 13) dirExists(nimRoot / testsDir) D:\a\nightlies\nightlies\nim-1.5.1\tests\ doesn't exist! [AssertionDefect]

## constraints
should work in various conditions eg:
* testament r tests/bar/tbar.nim
* testament r /pathto/tests/bar/tbar.nim
* nim r testament/testament.nim r tests/bar/tbar.nim
* testament/testament --nim:/pathto/nim r tests/bar/tbar.nim
* work with testament as a tool for user projects
etc

### solution 1
* don't install testament and require users to compile and run it themselves

### solution 2
* use some logic analog to `getPrefixDir` in compiler/options.nim that infers location of `prefixDir` and allows overriding it at runtime.
Not ideal if it prevents having nimRootDir, stdlibDir, testsDir, buildDir etc known at CT

### solution 3
maybe simply a targetted fix for bug 1 can be made, eg by inferring the location of nimRoot or testsDir at runtime from the input file passed to `testament r inputfile`, eg:

`testament r /pathto/tests/stdlib/nre/captures.nim`
=>
"stdlib" + "tests/stdlib/nre/captures.nim"

by walking up the inputfile until we find the right directory; a question is how to do that reliably so that for eg it's not fooled by: `nim r /pathto/tests/sub/tests/tbar.nim`

## links
* https://github.com/nim-lang/Nim/pull/16163#discussion_r560641690

### PR DESCRIPTION
**Pull request by timotheecour**
* fixes https://github.com/nim-lang/Nim/pull/16163#discussion_r560641690
* closes https://github.com/timotheecour/Nim/issues/519 (seems good enough)

to mimic installing testament and reproduce the bug that gets fixed here, do as follows:
nim c -o:/tmp/testament2 testament/testament.nim
move . to somewhere else to make sure the source files can't be read anymore

then:
mkdir -p tests/somedir
echo "doAssert 1 == 1" > tests/somedir/texample.nim

now these work:
/tmp/testament2 r tests/somedir/texample.nim
/tmp/testament2 r $PWD/tests/somedir/texample.nim
/tmp/testament2 r /patho/tests/somedir2/texample2.nim # can use external tests not relative to PWD

this doesn't work, because we can't get the category:
/tmp/testament2 r tests/texample.nim

(pre-existing issue IIRC, this could be relaxed in future work, by making `.` a special category of its own for eg)

### CODE REVIEW

File: testament/lib/stdtest/specialpaths.nim [hunk 1]
```diff
@@ -24,13 +24,30 @@ const
...
+  for p in file.parentDirs(inclusive = false):
+    let parent = p.parentDir
+    if parent.lastPathPart == testsFname:
+      result.cat = p.lastPathPart
+      let dir = getCurrentDir()
+      if file.isRelativeTo(dir):
+        result.path = file.relativePath(dir)
+      else:
+        result.path = file
+      return result
```
Comment (Araq) [inline testament/lib/stdtest/specialpaths.nim:48]:
```suggestion
      break
```

Comment (Clyybber) [reply testament/lib/stdtest/specialpaths.nim:48]: Then it will hit the `doAssert false` below
