### PR TITLE
fixes #18081; fixes #18079; fixes #18080;  nested ref/deref'd types

### LINKED ISSUE #18079: Illegal storage access compiling call with nested ref/deref'd types
Calling a function with nested layers of object construction, each of which constructs a reference object then dereferences it, results in `SIGSEGV` at compile time with Nim versions 1.2.12, 1.4.2, and current git head.

### Example
```nim
type
  Foo = object
    discard

  Bar = object
    x: Foo

proc baz(state: var Bar) = discard
baz((ref Bar)(x: (new Foo)[])[])
```

### Current Output
```
$ nim c sigsegv.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
....SIGSEGV: Illegal storage access. (Attempt to read from nil?)
$ nim --version
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2021-05-13
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```
```
$ ~/Nim/bin/nim c sigsegv.nim
Hint: used config file 'Nim/config/nim.cfg' [Conf]
Hint: used config file 'Nim/config/config.nims' [Conf]
....SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
$ ~/Nim/bin/nim --version
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-05-24
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: d217888e5679aff063668930bd00892c4f5cb2b3
active boot switches: -d:release
```
```
$ ./env.sh nim c ../sigsegv.nim 
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: sigsegv [Processing]
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
$ ./env.sh nim --version
Nim Compiler Version 1.2.12 [Linux: amd64]
Compiled at 2021-05-23
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 121628357ec7fae91335bd392f03b0e6dd249319
active boot switches: -d:release
```

### Expected Output
Not a segfault.

### LINKED ISSUE #18080: Calling a var-param-proc results in gcc error
Calling a var-param'd proc with a certain object construction results in a gcc error.

### Example
```nim
type
  Foo = object
    discard

  Bar = object
    x: Foo

proc baz(state: var Bar) = discard
baz((ref Bar)(x: Foo())[])
```

### Current Output
```
$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```$ nim c initializer_element_is_not_constant.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
....CC: initializer_element_is_not_constant.nim
/home/outhquin/.cache/nim/initializer_element_is_not_constant_d/@minitializer_element_is_not_constant.nim.c:54:87: error: initializer element is not constant
   54 | static NIM_CONST tyObject_Bar__GgKelZxvGOIwRl5q7fQcEA* TM__ErwDwTejKczskj5eQoYo4w_2 = TM__ErwDwTejKczskj5eQoYo4w_2;
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/usr/lib/nim -I/home/outhquin -o /home/outhquin/.cache/nim/initializer_element_is_not_constant_d/@minitializer_element_is_not_constant.nim.c.o /home/outhquin/.cache/nim/initializer_element_is_not_constant_d/@minitializer_element_is_not_constant.nim.c' failed with exit code: 1
$ nim --version
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2021-05-13
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

```
$ ~/Nim/bin/nim c initializer_element_is_not_constant.nim
Hint: used config file '/home/outhquin/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/outhquin/Nim/config/config.nims' [Conf]
....
CC: stdlib_assertions.nim
CC: stdlib_system.nim
CC: initializer_element_is_not_constant.nim
/home/outhquin/.cache/nim/initializer_element_is_not_constant_d/@minitializer_element_is_not_constant.nim.c:42:87: error: initializer element is not constant
   42 | static NIM_CONST tyObject_Bar__GgKelZxvGOIwRl5q7fQcEA* TM__ErwDwTejKczskj5eQoYo4w_2 = TM__ErwDwTejKczskj5eQoYo4w_2;
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/outhquin/Nim/lib -I/home/outhquin -o /home/outhquin/.cache/nim/initializer_element_is_not_constant_d/@minitializer_element_is_not_constant.nim.c.o /home/outhquin/.cache/nim/initializer_element_is_not_constant_d/@minitializer_element_is_not_constant.nim.c' failed with exit code: 1
$ ~/Nim/bin/nim --version
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-05-24
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: d217888e5679aff063668930bd00892c4f5cb2b3
active boot switches: -d:release
```

```
$ ./env.sh nim c ../initializer_element_is_not_constant.nim
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: initializer_element_is_not_constant [Processing]
CC: stdlib_system.nim
CC: initializer_element_is_not_constant.nim
/home/outhquin/.cache/nim/initializer_element_is_not_constant_d/@minitializer_element_is_not_constant.nim.c:44:87: error: initializer element is not constant
   44 | static NIM_CONST tyObject_Bar__GgKelZxvGOIwRl5q7fQcEA* TM__ErwDwTejKczskj5eQoYo4w_2 = TM__ErwDwTejKczskj5eQoYo4w_2;
      |                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: execution of an external compiler program 'gcc -c  -w   -I/home/outhquin/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib -I/home/outhquin -o /home/outhquin/.cache/nim/initializer_element_is_not_constant_d/@minitializer_element_is_not_constant.nim.c.o /home/outhquin/.cache/nim/initializer_element_is_not_constant_d/@minitializer_element_is_not_constant.nim.c' failed with exit code: 1
$ ./env.sh nim --version
Nim Compiler Version 1.2.12 [Linux: amd64]
Compiled at 2021-05-23
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 121628357ec7fae91335bd392f03b0e6dd249319
active boot switches: -d:release
```

### Expected Output
Not a gcc error.

### Additional Information

Issue https://github.com/nim-lang/Nim/issues/18079 is related, but different, because it constructs the `Foo`-type object differently and results in a `SIGSEGV` rather than a gcc error.

### LINKED ISSUE #18081: Calling proc with nested ref/deref constructed object results in invalid generated code
Calling a proc with nested ref/deref constructed object results in invalid generated code, which gcc refuses to compile.

### Example
```nim
type
  Foo = object
    discard

  Bar = object
    x: Foo

proc baz(state: var Bar) =
  state.x = Foo()

baz((ref Bar)(x: (new Foo)[])[])
```

### Current Output
```
$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ rm .cache/nim/ -r && nim c codegen_issue.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
....CC: stdlib_system.nim
CC: codegen_issue.nim
/home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c: In function ‘NimMainModule’:
/home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c:199:5: error: ‘T1_’ is a pointer; did you mean to use ‘->’?
  199 |  T1_.x = (*T2_);
      |     ^
      |     ->

Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/usr/lib/nim -I/home/outhquin -o /home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c.o /home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c' failed with exit code: 1
$ nim --version
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2021-05-13
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

```
$ rm .cache/nim/ -rf && ~/Nim/bin/nim c codegen_issue.nim
Hint: used config file '/home/outhquin/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/outhquin/Nim/config/config.nims' [Conf]
....
CC: stdlib_assertions.nim
CC: stdlib_system.nim
CC: codegen_issue.nim
/home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c: In function ‘NimMainModule’:
/home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c:197:5: error: ‘T1_’ is a pointer; did you mean to use ‘->’?
  197 |  T1_.x = (*T2_);
      |     ^
      |     ->
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/outhquin/Nim/lib -I/home/outhquin -o /home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c.o /home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c' failed with exit code: 1
$ ~/Nim/bin/nim --version
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-05-24
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: d217888e5679aff063668930bd00892c4f5cb2b3
active boot switches: -d:release
```

```
$ ./env.sh nim c ../codegen_issue.nim 
Hint: used config file '/home/outhquin/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/outhquin/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/config/config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: codegen_issue [Processing]
CC: stdlib_system.nim
CC: codegen_issue.nim
/home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c: In function ‘NimMainModule’:
/home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c:182:5: error: ‘T1_’ is a pointer; did you mean to use ‘->’?
  182 |  T1_.x = (*T2_);
      |     ^
      |     ->
Error: execution of an external compiler program 'gcc -c  -w   -I/home/outhquin/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib -I/home/outhquin -o /home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c.o /home/outhquin/.cache/nim/codegen_issue_d/@mcodegen_issue.nim.c' failed with exit code: 1
$ ./env.sh nim --version
Nim Compiler Version 1.2.12 [Linux: amd64]
Compiled at 2021-05-23
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 121628357ec7fae91335bd392f03b0e6dd249319
active boot switches: -d:release
```

### Expected Output
No gcc errors.

### Additional Information
Issue https://github.com/nim-lang/Nim/issues/18079 is related, but its `baz` function is empty. The test cases are otherwise identical.

Issue https://github.com/nim-lang/Nim/issues/18080 is related, but constructs the `Foo` object differently, resulting in differently invalid generated C code.

### PR DESCRIPTION
**Pull request by ringabout**
fixes #18081;
fixes https://github.com/nim-lang/Nim/issues/18080
fixes #18079

reverts https://github.com/nim-lang/Nim/pull/20738

It is probably more reasonable to use the type node from `nkObjConstr` since it is barely changed unlike the external type, which is susceptible to code transformation e.g. `addr(deref objconstr)`.

### CODE REVIEW

**Comment by ringabout** [comment]
I will check tranf instead. Or add a specific checking for isRef like `or e[0].typ.skipTypes.kind == tyRef`

File: compiler/ccgexprs.nim [hunk 1]
```diff
@@ -1542,7 +1542,7 @@ proc genObjConstr(p: BProc, e: PNode, d: var TLoc) =
     ]#
     if handleConstExpr(p, e, d): return
   var t = e.typ.skipTypes(abstractInstOwned)
-  let isRef = t.kind == tyRef
+  let isRef = e[0].typ.skipTypes(abstractInstOwned+{tyTypedesc}).kind == tyRef
```
Comment (ringabout) [inline compiler/ccgexprs.nim]:
```suggestion
  let isRef = e[0].typ.skipTypes(abstractInstOwned+{tyTypeDesc}).kind == tyRef
```

**Comment by ringabout** [comment]
Succeeded by https://github.com/nim-lang/Nim/pull/24342
