### PR TITLE
Fix unicode.split with seperators examples

### LINKED ISSUE #17174: split example from std/unicode doesn't run
The example at https://nim-lang.org/docs/unicode.html#split.i%2Cstring%2CRune%2Cint does not run.
https://play.nim-lang.org/#ix=2QI0

### Example
```nim
import std/unicode
for word in split("this:is;an$example", {';', ':', '$'}):
  writeLine(stdout, word)
```

### Current Output
```
/usercode/in.nim(2, 18) Error: type mismatch: got <string, set[char]>
but expected one of: 
iterator split(s: string; sep: Rune; maxsplit: int = -1): string
  first type mismatch at position: 2
  required type for sep: Rune
  but expression '{';', ':', '$'}' is of type: set[char]
iterator split(s: string; seps: openArray[Rune] = unicodeSpaces;
               maxsplit: int = -1): string
  first type mismatch at position: 2
  required type for seps: openArray[Rune]
  but expression '{';', ':', '$'}' is of type: set[char]
proc split(s: string; sep: Rune; maxsplit: int = -1): seq[string]
  first type mismatch at position: 2
  required type for sep: Rune
  but expression '{';', ':', '$'}' is of type: set[char]
proc split(s: string; seps: openArray[Rune] = unicodeSpaces; maxsplit: int = -1): seq[
    string]
  first type mismatch at position: 2
  required type for seps: openArray[Rune]
  but expression '{';', ':', '$'}' is of type: set[char]

expression: split("this:is;an$example", {';', ':', '$'})
```

### Expected Output
```
"this"
"is"
"an"
"example"
```

### Possible Solution

I have no idea, sorry, I'm a noob

### Additional Information

I switched to using strutils and that works fine with the above example.

```
$ nim -v
Nim Compiler Version 1.4.4
```

### PR DESCRIPTION
**Pull request by zetashift**
Fixes: https://github.com/nim-lang/Nim/issues/17174
https://nim-lang.org/docs/unicode.html#split.i%2Cstring%2CRune%2Cint didn't work with the set constructor `{}` so replaced it with a string that's converted to an openArray compatible type containing `Rune`s. 

If there is a better/more idiomatic way to get Runes from a set/string, then please do tell, first time interacting with Unicode module.

### CODE REVIEW

File: lib/pure/unicode.nim [hunk 1]
```diff
@@ -971,14 +971,14 @@ iterator split*(s: string, seps: openArray[Rune] = unicodeSpaces,
   ## And the following code:
   ##
   ## .. code-block:: nim
-  ##   for word in split("this:is;an$example", {';', ':', '$'}):
+  ##   for word in split("this:is;an$example", ";:$".toRunes):
```
Comment (timotheecour) [inline lib/pure/unicode.nim]: * use `runnableExamples` so it gets tested in CI
* modernize it (see recent PR's that modernize examples), eg use `suggar.collect` or `toSeq` and assert instead of relying on echo/stdout

Comment (zetashift) [reply lib/pure/unicode.nim]: If I wanna see my changes to I run `nim doc` over `unicode.nim`?
(I'm sorry for the questions I'm new to all this too D:)

Comment (ringabout) [reply lib/pure/unicode.nim]: yeah, you could run `nim doc lib/pure/unicode.nim` I guess?

with `devel` you could use command `nim doc -r `.

**Comment by zetashift** [comment]
@timotheecour using `sugar.cycle` is hard(or I am using it wrong) because `toRunes` returns a `seq[Rune]` and the collect macro packs that into a `seq[seq[Rune]]` should I just use a string as a separators list?
```nim
import sugar

let splittedBySequence = newSeq[string]()
let separators = collect(newSeq):
  for separator in @[";", ":", "$"]:
    separator.toRunes

for word in split("this:is;an$example", separators):
  splittedBySequence.add(word)

doAssert splittedBySequence = @["this", "is", "an", "example"]
```

**Comment by zetashift** [comment]
I currently have this, is this a decent example?
```nim
    # And the following code splits a string using a sequence of Runes.
    import sugar

    var splittedBySequence = newSeq[string]()
    let separators = collect(newSeq):
      for separator in ";:$".runes:
        separator

    for word in split("this:is;an$example", separators):
      splittedBySequence.add(word)

    doAssert splittedBySequence == @["this", "is", "an", "example"]
```

**Comment by ringabout** [comment]
Looks good!

nit:
```nim
import std/sugar


var splittedBySequence = newSeq[string]()
let separators = collect:
  for separator in ";:$".runes:
    separator

for word in split("this:is;an$example", separators):
  splittedBySequence.add(word)

# use assert 
assert splittedBySequence == @["this", "is", "an", "example"]
```

Or even one line
```nim
let separators = collect(for separator in ";:$".runes: separator)
```

**Comment by zetashift** [comment]
I didn't know you could use collect like that, the examples didn't mention it! :D, awesome thanks.

File: lib/pure/unicode.nim [hunk 2]
```diff
@@ -1010,28 +1001,15 @@ proc splitWhitespace*(s: string): seq[string] {.noSideEffect,
...
-  ##   ""
-  ##
+  runnableExamples:
+    var splitted = newSeq[string]()
+
+    for word in split(";;this;is;an;;example;;;", ";".runeAt(0)):
+      splitted.add(word)
+
+    assert splitted == @["", "", "this", "is", "an", "", "example", "", "", ""]
+
```
Comment (timotheecour) [inline lib/pure/unicode.nim]:
```suggestion
    import sequtils
    assert toSeq(";;this;is;an;;example;;;", ";".runeAt(0)) == @["", "", "this", "is", "an", "", "example", "", "", ""]
```

and also, use unicode in the input struct instead of plain ascii otherwise user might as well use strutils.split

File: lib/pure/unicode.nim [hunk 3]
```diff
@@ -955,43 +955,34 @@ iterator split*(s: string, seps: openArray[Rune] = unicodeSpaces,
...
-  ## .. code-block::
-  ##   "2012"
-  ##   "11"
-  ##   "20"
-  ##   "22"
-  ##   "08"
-  ##   "08.398990"
-  ##
+  runnableExamples:
+    var splitted = newSeq[string]()
```
Comment (timotheecour) [inline lib/pure/unicode.nim]: simplify further using toSeq, see https://github.com/nim-lang/Nim/pull/17176/files#r583098165

File: lib/pure/unicode.nim (hunk 2 above)
Comment (zetashift) [reply lib/pure/unicode.nim]: `toSeq(";;this;is;an;;example;;;", ";".runeAt(0))` doesn't entirely work? Where do I call the `split` function in this line? 
This compiles:
```nim
import std/sequtils

assert toSeq(split(";;this;is;an;;example;;;", ";".runeAt(0))) ==
  @["", "", "this", "is", "an", "", "example", "", "", ""]

``` 
but it's getting really hairy to read personally haha.
Also do you have an example of what you mean example with use "use unicode in the input struct instead of plain ascii" ? Do you mean a string containing unicode?

Comment (timotheecour) [reply lib/pure/unicode.nim]: right, i forgot `split`.
> but it's getting really hairy 

i think it's fine, and it's also idiomatic; but feel free to remove whatever you deem redundant, eg:

```nim
assert toSeq(split(";;ab;是;å;;de;;", ";".runeAt(0))) == ...
```
> Do you mean a string containing unicode?

yes, see above

**Comment by zetashift** [comment]
Last question is it better to group the imports?

```nim
    import std/sequtils

    assert toSeq("hÃllo\lthis\lis an\texample\l是".split) ==
      @["hÃllo", "this", "is", "an", "example", "是"]

    # And the following code splits the same string using a sequence of Runes.
    import std/sugar

    var splittedBySequence = newSeq[string]()
    let separators = collect(for separator in ";:$".runes: separator)
```

Turn the imports into a top level:
`import std/[sequtils, sugar]` 
Not sure which makes it better :(

File: lib/pure/unicode.nim [hunk 4]
```diff
@@ -955,43 +955,27 @@ iterator split*(s: string, seps: openArray[Rune] = unicodeSpaces,
...
+  runnableExamples:
+    import std/sequtils
+
+    assert toSeq("hÃllo\lthis\lis an\texample\l是".split) ==
+      @["hÃllo", "this", "is", "an", "example", "是"]
+
+    # And the following code splits the same string using a sequence of Runes.
+    import std/sugar
+
+    let separators = collect(for separator in ";:$".runes: separator)
```
Comment (timotheecour) [inline lib/pure/unicode.nim]: always use the simplest, toSeq works here (refs https://github.com/nim-lang/Nim/pull/17188)

**Comment by timotheecour** [comment]
> Last question is it better to group the imports?

yes but turns out you don't even need `collect` here, in all your examples, `toSeq` is enough.
(Note: https://github.com/nim-lang/RFCs/issues/76 would allow the more explicit: `from std/[sugar, sequtils] import toSeq, collect` but again, that's not needed here)

File: lib/pure/unicode.nim (hunk 4 above)
Comment (zetashift) [reply lib/pure/unicode.nim]: Indeed very true, I didn't see that!

File: lib/pure/unicode.nim [hunk 5]
```diff
@@ -955,43 +955,22 @@ iterator split*(s: string, seps: openArray[Rune] = unicodeSpaces,
...
+  runnableExamples:
+    import std/sequtils
+
+    assert toSeq("hÃllo\lthis\lis an\texample\l是".split) ==
+      @["hÃllo", "this", "is", "an", "example", "是"]
+
+    # And the following code splits the same string using a sequence of Runes.
+    assert toSeq(split("añyóng:hÃllo;是$example", ";:$".toRunes)) ==
+      @["añyóng", "hÃllo", "是", "example"]
+
```
Comment (timotheecour) [inline lib/pure/unicode.nim:967]:
```suggestion

    # example with a `Rune` separator and unused one `;`:
    assert toSeq(split("ab是de:f:", ";:是".toRunes)) == @["ab", "de", "f", ""]

```

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
LGTM, thanks!
further cleanup PR's welcome (see also https://github.com/nim-lang/Nim/pulls?q=is%3Apr+author%3Akonsumlamm+sort%3Aupdated-desc for similar ones, in particular changing `code-block` (often broken since not run in CI, more verbose, etc) to `runnableExamples` is an easy way to get started, starting with the most commonly used modules that still rely on `code-block`

**Comment by zetashift** [comment]
I would love to do more of these! I am gonna ask a lot of questions though since I'm not familiar with all of the stdlib modules, if that's okay haha!
