### PR TITLE
fix #13579 joinPath("/foo/", "../a") is now /a

### LINKED ISSUE #13579: os.joinPath returns wrong path when head ends '\' or '/' and tail starts '..'.
On windows:
### Example
```nim
import os

echo joinPath("C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\", "..\\..\\VC\\vcvarsall.bat")
echo joinPath("C:\\foo", "..\\a")
echo joinPath("C:\\foo\\", "..\\a")
```

### Current Output
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\VC\vcvarsall.bat
C:\a
C:\foo\a
```

### Expected Output
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
C:\a
C:\a
```

On Linux:
### Example
```nim
import os

echo joinPath("/foo", "../a")
echo joinPath("/foo/", "../a")
```

### Current Output
```
/a
/foo/a
```

### Expected Output
```
/a
/a
```

### Additional Information

I updated nim devel today and found that vccexe cannot find cl.exe.
I found that this is because `os.joinPath` has this bug.

```
>nim -v
Nim Compiler Version 1.1.1 [Windows: amd64]
Compiled at 2020-03-03
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: e8c057fb2729b2598b8cb62ae46f85139fb480fa
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by timotheecour**
* fixes https://github.com/nim-lang/Nim/issues/13579
addNormalizePath doesn't work when result ends in a slash (eg foo/), all other uses assumed a path not ending in `/`; I could've fixed it inside `addNormalizePath` but decided to fix it inside `joinPathImpl` instead, and added a comment in `addNormalizePath`

### CODE REVIEW

File: lib/pure/pathnorm.nim [hunk 1]
```diff
@@ -76,6 +76,11 @@ proc addNormalizePath*(x: string; result: var string; state: var int;
       if (state shr 1) >= 1:
         var d = result.len
         # f/..
+        ## We could handle stripping trailing sep here as well: foo// => foo
```
Comment (narimiran) [inline lib/pure/pathnorm.nim]: Why doc-comments suddenly?

Comment (timotheecour) [reply lib/pure/pathnorm.nim]: that was do distinguish from commented code snippet, but I've now removed it

**Comment by Araq** [comment]
@narimiran see if this need to be backported or not please.
