### PR TITLE
httpclient.nim Fixes #14794 and an issue where content-header is not set on postContent 

### LINKED ISSUE #14794: Multipart upload in httpclient broken
Hi,

```nim
var client = newAsyncHTTPClient()
var data = newMultipartData()
data.addFiles({"hello.txt": "/tmp/hello.txt"}) # a 12 byte file
await client.postContent("http://127.0.0.1:7777/", multipart = data)
```
Older versions (tested on v0.20.0) will post 162 bytes to the server, while v1.2.2 httpclient sends only 160 bytes. From quick glance, this seem to also affect v1.2.0 as well.

https://github.com/nim-lang/Nim/blob/v1.2.2/lib/pure/httpclient.nim#L938

```nim
  result.add "--" & bound & "--"
```

should be..

```nim
  result.add "--" & bound &  "--" & httpNewLine
 ```

Related discussion:  https://github.com/nim-lang/Nim/pull/12982

### PR DESCRIPTION
**Pull request by mp035**
EDIT(timotheecour) fix #14794

Fixed missing newline after bound marker in mulipart post (#14794) and a problem where calling postContent with multipart data does not set content-length header.

### CODE REVIEW

File: lib/pure/httpclient.nim [hunk 1]
```diff
@@ -997,12 +997,14 @@ proc requestAux(client: HttpClient | AsyncHttpClient, url: Uri,
 
   await newConnection(client, url)
 
-  let newHeaders = client.headers.override(headers)
+  var newHeaders:HttpHeaders
```
Comment (Araq) [inline lib/pure/httpclient.nim]:
```suggestion
  var newHeaders: HttpHeaders
```

**Comment by timotheecour** [comment]
@mp035 please see contributing.html, the PR message needs to contain `fix #14794` so that github cross-references it (`issue x may be fixed by y`) and so that it auto-closes when this is merged

I added it for you

File: lib/pure/httpclient.nim [hunk 2]
```diff
@@ -997,12 +997,14 @@ proc requestAux(client: HttpClient | AsyncHttpClient, url: Uri,
 
   await newConnection(client, url)
 
-  let newHeaders = client.headers.override(headers)
+  var newHeaders: HttpHeaders
 
   var data: seq[string]
   if multipart != nil and multipart.content.len > 0:
     data = await client.format(multipart)
+    newHeaders = client.headers.override(headers)
```
Comment (timotheecour) [inline lib/pure/httpclient.nim:1007]: can you explain (as comment in the code) why `let newHeaders = client.headers.override(headers)` would not work (instead of calling it in each branch), so that this doesn't regress in future

Comment (dom96) [reply lib/pure/httpclient.nim:1007]: First maybe explain here, I see the change as not producing any semantic changes, am I missing something?

**Review by dom96 — APPROVED** [review]
Other than my comment, this looks good to me.

Although: I am trusting that this is what the spec expects (and wondering a little why the testing for the original implementation in https://github.com/nim-lang/Nim/pull/12982 didn't catch this).

I would also strongly urge to implement a test as part of this PR. It appears that even though I asked for it in #12982 tests weren't added (I could be wrong though, I didn't check closely)

**Comment by timotheecour** [comment]
> I would also strongly urge to implement a test as part of this PR

yes, a test (that would fail before this PR and work after this PR) would be great

File: lib/pure/httpclient.nim (hunk 2 above)
Comment (mp035) [reply lib/pure/httpclient.nim:1007]: Hi, firstly thank you all for the direction (this is my first Nim PR, so every bit of info is helpful).  
Secondly, the issue is that when there is multipart data, a side effect of calling `client.format(multipart)` is that the content-length and content-type headers on the client are set to correct values.  The way that `proc requestAux `was structured meant that the client headers were copied to `newHeaders` before `client.format(mulipart)` was called, and then `newHeaders` was used to generate the request.  This meant that the changes to the headers from `client.format(multipart)` were lost.

The solution I chose is to populate `newHeaders` after `client.format(multipart)` only when there is multipart data. When there is no multipart data, `newHeaders` is populated before the Content-Length value is assessed on that branch so that the caller doesn't loose the the option of overriding the Content-Length header with a custom value when needed.   

I'm happy to add a comment, please let me know if you think it is needed.  I will also try to work out how to compose a test to verify the expected behavior. (That may take some time)

Comment (timotheecour) [reply lib/pure/httpclient.nim:1007]: ya i suspected something like that; you could add a 1 sentence comment along the lines of:

```nim
  # `format` resets `headers`, see https://github.com/nim-lang/Nim/pull/18208#discussion_r647036979
```

Comment (mp035) [reply lib/pure/httpclient.nim:1007]: Will do.   It'll take a little time to get back to the PR due to my current workload, but it won't get forgotten.

**Comment by mp035** [comment]
Ok, I've added the requested comments, and tests. :smile: :thumbsup:

File: tests/stdlib/thttpclient_standalone.nim [hunk 3]
```diff
@@ -21,3 +21,34 @@ block: # bug #16436
...
+      # this next line is probably not required because asynchttpserver does not call
+      # the callback when there is no content-length header.  It instead errors with 
+      # Error: unhandled exception: 411 Length Required
+      # Added for good measure in case the server becomes more permissive.
+      doAssert(req.headers.hasKey("content-length"), "Content-Length header is not present.")
+      killServer = true
+      asyncCheck req.respond(Http200, "OK")
+
+    var server = newAsyncHttpServer()
+    server.listen(Port(5556))
```
Comment (timotheecour) [inline tests/stdlib/thttpclient_standalone.nim:39]: @mp035 can you send a followup PR to improve this test by avoiding hardcoded ports? these cause flaky failures, see https://github.com/timotheecour/Nim/issues/534#issuecomment-821904874

Comment (mp035) [reply tests/stdlib/thttpclient_standalone.nim:39]: Will do.
