### PR TITLE
fix #18986; Import/except doesn't work on devel [backport: 1.6]

### LINKED ISSUE #18986: Import/except doesn't work on devel
I came across this when trying to compile my epaper project with the devel compiler. I managed to boil it down to a sample like this:

```nim
import macros

converter Lit(x: uint): NimNode = newLit(x)

var x = 0.uint
echo "Found a ", x
```

The `converter` was originally from my `macroutils` package (I think I'm going to remove this converter, it keeps creating weird bugs). The original code uses Futhark, and in that package I import `macroutils` with `import macroutils except Lit`. First of should an imported converter trickle through two modules? Secondly shouldn't `import macroutils except Lit` stop those converters from getting imported into Futhark in the first place?

NOTE: The above fails both on devel and on stable, the bug is in the following snippets

### Example
```nim
import macroutils except Lit
import macros

var x = 0.uint
echo "Found a ", x
```

### Current Output
```
(5, 6) Error: type mismatch: got <string, uint>
but expected one of:
proc echo(x: varargs[typed, `$`])
  first type mismatch at position: 2
  required type for x: varargs[typed]
  but expression 'x' is of type: uint

expression: echo "Found a ", x
```

### Expected Output
```
Found a 0
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #18986

### CODE REVIEW

File: tests/converter/t18986.nim [hunk 1]
```diff
@@ -0,0 +1,10 @@
+discard """
+  output: "Found a 0"
+"""
+
+import m18986 except Lit
+import std/macros
+
+# bug #18986
+var x = 0.uint
+echo "Found a ", x
```
Comment (ringabout) [inline tests/converter/t18986.nim:10]: With nim 1.6.4 and devel

```nim
test.nim(5, 6) Error: type mismatch: got <string, uint>but expected one of:proc echo(x: varargs[typed, `$`])
  first type mismatch at position: 2  required type for x: varargs[typed]
  but expression 'x' is of type: uint

expression: echo "Found a ", x
```

**Comment by ringabout** [comment]
I checked CI failures which are unrelated to my PR.


```
2022-04-06T06:34:42.8449467Z [Suite] SSL certificate check - httpclient
2022-04-06T06:34:42.8450691Z D20210322T121353: warning:          no-common-name (dubious_broken) raised: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2022-04-06T06:34:42.8452170Z D20210322T121353: warning:          no-subject (dubious_broken) raised: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2022-04-06T06:34:42.8453654Z D20210322T121353: warning:          incomplete-chain (dubious_broken) raised: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2022-04-06T06:34:42.8454811Z D20210322T121353: error:          sha384 (good) raised: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2022-04-06T06:34:42.8455603Z   [FAILED] sha384
2022-04-06T06:34:42.8456390Z D20210322T121353: error:          sha512 (good) raised: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2022-04-06T06:34:42.8457157Z   [FAILED] sha512
```
