### PR TITLE
Try conversion to static[T] in generic instantation

### LINKED ISSUE #8439: Instantiation error with static[T]
```nim
type
  Cardinal = enum
    north, east, south, west

proc foo[cardinal: static[Cardinal]](): int = 1
echo(foo[north]())
```
```
c:/nimtests $ nim c instantiate.nim
Hint: used config file 'c:\Nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: instantiate [Processing]
instantiate.nim(7, 9) Error: cannot instantiate: 'foo[north]'
```

### PR DESCRIPTION
**Pull request by LemonBoy**
Ugly but needed (?)

Fixes #8439

### CODE REVIEW

**Comment by Araq** [comment]
Eventually I'll remove 'static[T]' and replace it with something sane.

File: compiler/semcall.nim [hunk 1]
```diff
@@ -505,7 +505,15 @@ proc explicitGenericSym(c: PContext, n: PNode, s: PSym): PNode =
...
+    var arg = n[i].typ
+    # try transforming the argument into a static one before feeding it into
+    # typeRel
+    if formal.kind == tyStatic and arg.kind != tyStatic:
+      let evaluated = c.semTryConstExpr(c, n[i])
+      if evaluated != nil:
+        arg = newTypeS(tyStatic, c)
+        arg.sons = @[evaluated.typ]
+        arg.n = evaluated
     let tm = typeRel(m, formal, arg)
```
Comment (zah) [inline compiler/semcall.nim]: I think the problem here was that `typeRel` was used directly, instead of using the full `paramTypesMatchAux`, which has grown with many additional bits of logic over the years. Basically, in this fix you've extracted a little bit of the code in `paramTypesMatchAux` here.

**Comment by zah** [comment]
Under implicit static evaluation, such on-demand static coercions won't be necessary and `static[T]` will be fully sane, no?

**Comment by Araq** [comment]
I hope so, but to be honest, all of ``sigmatch`` should operate on ASTs, not only on types. Arguably we already do that, but in a post processing step (check that lvalues are passed to ``var T``).

File: compiler/semcall.nim (hunk 1 above)
Comment (LemonBoy) [reply compiler/semcall.nim]: Yup, I did not know if using the full-blown matching routine had any unwanted side effect, feel free to change this to use it.

Implicit `static`s may help remove many of those special-cases.
