### PR TITLE
Let getTimezone() to work properly on BSD

### LINKED ISSUE #3059: Error during compilation with cpp option on FreeBSD
Nim output the following error:
```
clang++ -c  -w  -I/usr/home/filippo/Desktop/Nim/lib -o /usr/home/filippo/Desktop/DOtherSide/Nim/Examples/HelloWorld/nimcache/stdlib_times.o /usr/home/filippo/Desktop/DOtherSide/Nim/Examples/HelloWorld/nimcache/stdlib_times.cpp
/usr/home/filippo/Desktop/DOtherSide/Nim/Examples/HelloWorld/nimcache/stdlib_times.cpp:737:9: error: assigning to 'NI' (aka 'long long') from incompatible
      type 'char *(int, int)'
        result = timezone;
```
Maybe the same error appears on linux i didn't test it it there yet

I tested it with both today Nim git snapshot and Nim 0.11.2. Same error.

### PR DESCRIPTION
**Pull request by cheatfate**
Resolve #3059
Make getTimezone() to work properly on FreeBSD and NetBSD.

### CODE REVIEW

File: lib/pure/times.nim [hunk 1]
```diff
@@ -416,18 +417,32 @@ when not defined(JS):
 
 when not defined(JS):
   # C wrapper:
+  when defined(freebsd) or defined(netbsd):
```
Comment (Araq) [inline lib/pure/times.nim]: what about OpenBSD?

Comment (cheatfate) [inline lib/pure/times.nim]: For some reason OpenBSD has this lines in <time.h>
```
#if __XPG_VISIBLE >= 300
extern int daylight;
extern long timezone;
#endif
```
So its not affected to this issue...
But if you want we can add one more define because OpenBSD is also support `tm_gmtoff` member.

Comment (Araq) [inline lib/pure/times.nim]: 'when defined(bsd)' seem more future proof then.
