### PR TITLE
close #17636(remove unchecked and useless line when nimout is present)

### LINKED ISSUE #17636: testament: `line` spec silently ignored in tests where errormsg is not specified
### Example
in tests/init/tuninit1.nim:
```
discard """
  nimout: "Warning: use explicit initialization of 'y' for clarity [Uninit]"
  line:34
  action: compile
"""
...
```

change `line:34` to `line:1234`

### Current Output
test still passes

### Expected Output
give error saying that line is ignored in presence of `nimout` and shouldn't be specified.

note also that specifying line and col and errormsg is IMO bad (because it's more work), instead, the test should specify if there's an error by adding relevant line to nimout, eg:
```
twrongcolon.nim(11, 12) Error: in expression ' do:
```
=> less work and less maintenance (just copy paste error)
=> test is in no way weaker

### Additional Information
* 1.5.1 fe7a76f62fa1563a76e1dcce18e3ee98bcd5d36a
* found while reviewing https://github.com/nim-lang/Nim/pull/16698

EDIT: line is honored when errormsg is specified, and silently ignored when errormsg is not specified.
See https://github.com/nim-lang/Nim/pull/17643#discussion_r607220523 for more details on this and for suggested fix.

### PR DESCRIPTION
**Pull request by ringabout**
close #17636

### CODE REVIEW

File: tests/concepts/twrapconcept.nim [hunk 1]
```diff
@@ -1,7 +1,6 @@
 discard """
   errormsg: "type mismatch: got <string>"
-  line: 21
-  nimout: "twrapconcept.nim(11, 5) Foo: concept predicate failed"
+  nimout: "twrapconcept.nim(10, 5) Foo: concept predicate failed"
```
Comment (timotheecour) [inline tests/concepts/twrapconcept.nim:3]: actually `line` is silently ignored when errormsg is not specified but is honored when errormsg is specified.

That being said, `errormsg` is redundant with nimout since nimout can specify the error line (and in fact lots of tests specify the error line in both nimout and errormsg, which is even more redundant). Right now you've weaked the test by removing the line number where the error occurs, but the following should be used instead: 

it contains all the original information (line nnumber and error msg), is not ambiguous, and also contains column, and is easier to maintain / more systematic.

Other tests could use this too (at least ones in this PR where you've removed line number AND an errormsg was specified)

```nim
discard """
  action: reject
  nimout: '''
twrapconcept.nim(23, 14) Error: type mismatch: got <string>
twrapconcept.nim(13, 5) Foo: concept predicate failed
'''
"""

# https://github.com/nim-lang/Nim/issues/5127

type
  Foo = concept foo
    foo.get is int

  FooWrap[F: Foo] = object
    foo: F

proc get(x: int): int = x

proc wrap[F: Foo](foo: F): FooWrap[F] = FooWrap[F](foo: foo)

let x = wrap(12)
let y = wrap "string"
```


alternatively, this PR could be split in 2:
* one where you remove `line` in cases where it was un-checked (ie errormsg was unspecified)
* one where you furthermore remove errormsg and line and replace it with nimout containing at least the error line, plus `action: reject`.

I think doing this in same PR is fine but let's /cc @Araq

File: tests/concepts/texplain.nim [hunk 2]
```diff
@@ -1,45 +1,45 @@
 discard """
```
Comment (timotheecour) [inline tests/concepts/texplain.nim:1]: - [ ] in followup work, if we agree to use nimout + action:reject instead of errormsg+file+line, we should update contributing.rst which currently doesn't mention nimout and instead mentions:
```
errormsg: The expected compiler error message
file: The file the errormsg was produced at
line: The line the errormsg was produced at
```

File: tests/concepts/texplain.nim [hunk 3]
```diff
@@ -1,45 +1,45 @@
...
   cmd: "nim c --verbosity:0 --colors:off $file"
   nimout: '''
-texplain.nim(164, 10) Hint: Non-matching candidates for e(y)
+texplain.nim(162, 10) Hint: Non-matching candidates for e(y)
```
Comment (Araq) [inline tests/concepts/texplain.nim:4]: Why did this change to 162? What changed?
