### PR TITLE
fix #14082, don't crash on incorrectly formatted input

### LINKED ISSUE #14082: uri.decodeUrl crashes on incorrectly formatted input
Function `uri.decodeUrl` crashes when encoding sequences are incorrect. In server-side contexts, this might cause denial of service if not handled properly.

### Example
```nim
import uri
echo decodeUrl("abc%xx")
```

```nim
import uri
echo decodeUrl("abc%")
```

### Current Output

```
/usercode/in.nim(3)      in
/playground/nim/lib/pure/uri.nim(109) decodeUrl
/playground/nim/lib/pure/uri.nim(100) handleHexChar
/playground/nim/lib/system/assertions.nim(29) failedAssertImpl
/playground/nim/lib/system/assertions.nim(22) raiseAssert
/playground/nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: /playground/nim/lib/pure/uri.nim(100, 17) `false`  [AssertionError]
```

or

```
/usercode/in.nim(3)      in
/playground/nim/lib/pure/uri.nim(109) decodeUrl
/playground/nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index 4 not in 0 .. 3 [IndexError]
```

### Expected Output

Either some correct way to handle the error (I don't think there is, in go, the error is returned as an error object) or the situation should be properly checked to avoid runtime errors.

In any case, the documentation should mention the possibility of errors.

### Possible Solution

Add an assert for the first case, or detect both cases properly and raise a specific error

### Additional Information

I found this while I was using the following code: https://github.com/nim-lang/Nim/pull/7761#issuecomment-616810243

Nim version 1.2.0 from the playground

### PR DESCRIPTION
**Pull request by narimiran**
This is an alternative to https://github.com/nim-lang/Nim/pull/14972 — without raising exceptions.

### CODE REVIEW

File: lib/pure/cgi.nim [hunk 1]
```diff
@@ -93,40 +104,26 @@ proc getEncodedData(allowedMethods: set[RequestMethod]): string =
 iterator decodeData*(data: string): tuple[key, value: TaintedString] =
   ## Reads and decodes CGI data and yields the (name, value) pairs the
   ## data consists of.
+  proc parseData(data: string, i: var int, field: var string) {.inline.} =
```
Comment (Araq) [inline lib/pure/cgi.nim]:
```nim

proc parseData(data: string, i: int, field: var string): int =
  ## return the 'i' after the call.
```
