### PR TITLE
fixed #2240 and #3586

### LINKED ISSUE #2240: ICE dereferencing array pointer
Error dereferencing pointer when passing to function that takes openarray.
```nimrod
proc f(a: openarray[int]) =
    discard

var a : array[10, int]
var p = addr a
f(p[])
```
Error:
```
Error: internal error: openArrayLoc: ptr array[0..9, int]
Traceback (most recent call last)
nim.nim(92)              nim
nim.nim(56)              handleCmdLine
main.nim(251)            mainCommand
main.nim(62)             commandCompileToC
modules.nim(203)         compileProject
modules.nim(151)         compileModule
passes.nim(193)          processModule
passes.nim(137)          processTopLevelStmt
cgen.nim(1208)           myProcess
ccgstmts.nim(1064)       genStmts
ccgexprs.nim(2060)       expr
ccgstmts.nim(1064)       genStmts
ccgexprs.nim(2025)       expr
ccgcalls.nim(501)        genCall
ccgcalls.nim(177)        genPrefixCall
ccgcalls.nim(134)        genArg
ccgcalls.nim(121)        openArrayLoc
msgs.nim(850)            internalError
msgs.nim(780)            rawMessage
msgs.nim(777)            rawMessage
msgs.nim(724)            handleError
```
Maybe related to #1715.

### PR DESCRIPTION
**Pull request by jangko**
#2240 and #3586 are the same bug

### CODE REVIEW

File: compiler/ccgcalls.nim [hunk 1]
```diff
@@ -118,6 +118,14 @@ proc openArrayLoc(p: BProc, n: PNode): Rope =
         result = "$1->data, $1->$2" % [a.rdLoc, lenField(p)]
     of tyArray, tyArrayConstr:
       result = "$1, $2" % [rdLoc(a), rope(lengthOrd(a.t))]
+    of tyPtr, tyRef:
+      case a.t.sons[0].kind
```
Comment (Araq) [inline compiler/ccgcalls.nim]: Use lastSon instead of  sons[0]  since the pointer might be regionized.

**Comment by jangko** [comment]
thanks. done
