### PR TITLE
less verbose type mismatch messages

### LINKED ISSUE #87: [RFC] type mismatch error message improvement
- [ ] The following would be clearer and more concise; especially useful when lots of overloads are shown:

```
test.nim(883, 12) Error: type mismatch: got <Stream, TaintedString>
but expected one of:
proc readLine(f: File; line: var TaintedString): bool
  first type mismatch at position: 1
  required type: File
  but expression 'outp' is of type: Stream
proc readLine(f: File): TaintedString
  first type mismatch at position: 1
  required type: File
  but expression 'outp' is of type: Stream

expression: readLine(outp, line)
      if outp.readLine(line):
```
=>
```
test.nim(883, 12) {if outp.readLine(line):} Error: type mismatch: got <Stream, TaintedString> in expression: readLine(outp, line); candidates:
  proc readLine(f: File {Stream}; line: var TaintedString): bool
  proc readLine(f: File {Stream}): TaintedString
```

**EDIT**
- [ ] furthermore, we should show fully qualified types instead of types, to make it easier to find where symbols are defined and remove ambiguities, eg in case Stream is defined in multiple modules:
```
  proc readLine(f: File {Stream}; line: var TaintedString): bool
=>
  proc readLine(f: mod1.File {mod2.Stream}; line: var mod3.TaintedString): bool
```

**EDIT** the overloads should also show the module + file where they came from (not obvious in complex cases)

### PR DESCRIPTION
**Pull request by ringabout**
Supersedes https://github.com/nim-lang/Nim/pull/20528

fixes https://github.com/nim-lang/RFCs/issues/87
implements https://forum.nim-lang.org/t/9514

screenshot

image

**Compared to before, it also omits some useful information like below** Perhaps the error message should expand and collapse according to verbose levels.

image

### CODE REVIEW

File: compiler/types.nim [hunk 1]
```diff
@@ -1654,7 +1654,7 @@ proc typeMismatch*(conf: ConfigRef; info: TLineInfo, formal, actual: PType, n: P
     let verbose = actualStr == formalStr or optDeclaredLocs in conf.globalOptions
     var msg = "type mismatch:"
     if verbose: msg.add "\n"
-    if conf.isDefined("nimLegacyTypeMismatch"):
+    if verboseTypeMismatch in conf.legacyFeatures:
```
Comment (ringabout) [inline compiler/types.nim]:
```suggestion
    if conf.isDefined("nimLegacyTypeMismatch"):
```
