### PR TITLE
Raise IndexDefect when deleting element at out of bounds index

### LINKED ISSUE #16544: `delete(seq, index)` with invalid index deletes an element instead of raising
### Example
```nim
when true:
  var a = @[1,2,3]
  a.delete 6
  echo a
```

### Current Output
@[1, 2]

### Expected Output
raise `IndexError` via `raiseIndexError2`

### Additional Information
devel 1.5.1 505d04389ad5c83b50001e3108d89fcdec9c462f
a fix should include a comprehensive test 

note that `RangeDefect` is raised if passing `i` == 0 with x.len == 0
> Error: unhandled exception: value out of range: -1 notin 0 .. 9223372036854775807 [RangeDefect]

note that `del` correctly raises:
`Error: unhandled exception: index 6 not in 0 .. 2 [IndexDefect]`

### PR DESCRIPTION
**Pull request by hnicke**
Resolves #16544

### CODE REVIEW

File: lib/system.nim [hunk 1]
```diff
@@ -1345,6 +1345,13 @@ proc delete*[T](x: var seq[T], i: Natural) {.noSideEffect.} =
   ## .. code-block:: Nim
   ##  var i = @[1, 2, 3, 4, 5]
   ##  i.delete(2) # => @[1, 2, 4, 5]
+  if i > high(x):
+    var e: ref IndexDefect
+    new(e)
+    e.msg = "out of bounds!"
+    raise e
+    # raiseIndexError2(i, high(x))
```
Comment (hnicke) [inline lib/system.nim]: Can someone help me out here? I am not sure how to properly import/include `raiseIndexError2` from `chcks`, because `chcks` needs `sysFatal` and `sysFatal` needs `&`.

Comment (Araq) [reply lib/system.nim]: I would try it this way:

```nim

    # by moving the first iteration out of the loop, we gurantee
    # that invalid indexes are caught:
    movingCopy(x[i], x[if i+1 < xl: i+1 else: xl-1])
    for j in i+1..xl-2: movingCopy(x[j], x[j+1])
```

File: tests/system/tsystem_misc.nim [hunk 2]
```diff
@@ -63,6 +63,16 @@ doAssert high(float64) > low(float64)
 var s = @[1]
 s.delete(0)
 
+# deleting nonexistent index should raise #16544
```
Comment (timotheecour) [inline tests/system/tsystem_misc.nim]:
```suggestion
# bug #16544: deleting out of bounds index should raise
```
(see contributing.html for rationale for having a fixed formatting for issue references for ease of search)

File: tests/system/tsystem_misc.nim [hunk 3]
```diff
@@ -63,6 +63,16 @@ doAssert high(float64) > low(float64)
...
+block:
+  var s = @["foo", "bar"]
+  s.delete(1)
+  doAssert @["foo"] == s
+
+  var s2 = @["foo"]
+  doAssertRaises(IndexDefect):
```
Comment (timotheecour) [inline tests/system/tsystem_misc.nim]: this needs a few more tests, eg: negative indexes, index 0 when input has length 0 (implementations may change)

File: lib/system.nim (hunk 1 above)
Comment (hnicke) [reply lib/system.nim]: This would not raise the `IndexDefect` in the generated javascript.
Or do you mean, putting this first iteration to line 1348?

File: tests/system/tsystem_misc.nim (hunk 3 above)
Comment (hnicke) [reply tests/system/tsystem_misc.nim]: Added test for index 0 when input has length 0.
Negative indexes do not compile, `delete` takes a Natural. I'm not sure if it's possible to test that something doesn't compile.

Comment (hnicke) [reply tests/system/tsystem_misc.nim]: nvm, i found the `compiles` template

Comment (timotheecour) [reply tests/system/tsystem_misc.nim]: `tests/system/tsystem_misc.nim` is not ideal because it's not testing in either VM nor js; most recent tests nowdays use a pattern like this: https://github.com/nim-lang/Nim/pull/17767#issuecomment-822052627 which allows ensuring we test on those backends without test duplication. How about creating `tests/stdlib/tsystem.nim` that follows the same pattern and move those tests there (future work can move other tests there and add more tests, and modernize the existing tests)

File: lib/system.nim (hunk 1 above)
Comment (timotheecour) [reply lib/system.nim]: this works:
move this right below `export dollars`:
```nim
proc delete*[T](x: var seq[T], i: Natural) {.noSideEffect.} =
  ## Deletes the item at index `i` by moving all `x[i+1..]` items by one position.
  ##
  ## This is an `O(n)` operation.
  ##
  ## See also:
  ## * `del <#del,seq[T],Natural>`_ for O(1) operation
  ##
  ## .. code-block:: Nim
  ##  var i = @[1, 2, 3, 4, 5]
  ##  i.delete(2) # => @[1, 2, 4, 5]
  if i > high(x):
    # xxx this should call `raiseIndexError2(i, high(x))` after some refactoring
    raise (ref IndexDefect)(msg: "index out of bounds: '" & $i & "' < '" & $x.len & "' failed")

  template defaultImpl =
    let xl = x.len
    for j in i.int..xl-2: movingCopy(x[j], x[j+1])
    setLen(x, xl-1)

  when nimvm:
    defaultImpl()
  else:
    when defined(js):
      {.emit: "`x`.splice(`i`, 1);".}
    else:
      defaultImpl()
```

then change `.. code-block:: Nim` to runnableExamples and also add a doAssertRaises example showing a failure case

File: tests/system/tsystem_misc.nim (hunk 3 above)
Comment (hnicke) [reply tests/system/tsystem_misc.nim]: thanks- very helpful remark, done.

File: lib/system.nim (hunk 1 above)
Comment (hnicke) [reply lib/system.nim]: That makes sense, done.
However, now there's this error: `Error: undeclared identifier: '$'`

Comment (hnicke) [reply lib/system.nim]: My bad, failed to correctly read your comment. fixed.

**Comment by timotheecour** [comment]
congratulations, your PR exposed a preexisting bug which fails CI:

```
2021-04-23T15:55:58.2069930Z Output:
2021-04-23T15:55:58.2143960Z gcleak3.nim(27)          gcleak3
2021-04-23T15:55:58.2244900Z gcleak3.nim(25)          limit
2021-04-23T15:55:58.2345070Z system.nim(2175)         delete
2021-04-23T15:55:58.2446770Z Error: unhandled exception: index out of bounds: '513' < '512' failed [IndexDefect]
2021-04-23T15:55:58.2545770Z 

```

this should work:
```
diff --git a/tests/gc/gcleak3.nim b/tests/gc/gcleak3.nim
index 588e238e9..d7cc50459 100644
--- a/tests/gc/gcleak3.nim
+++ b/tests/gc/gcleak3.nim
@@ -18,7 +18,8 @@ for i in 0..1024:

 proc limit*[t](a: var seq[t]) =
   var loop = s.len() - 512
-  for i in 0..loop:
+  for i in 0..<s.len:
+    if i >= s.len: break
     #echo i
     #GC_fullCollect()
     if getOccupiedMem() > 3000_000: quit("still a leak!")
```

plus similar for the other mostly copy pasted tests that fail

long term, some of those tests should be refactored to remove copy pasting

File: tests/gc/gcleak3.nim [hunk 4]
```diff
@@ -18,7 +18,8 @@ for i in 0..1024:
 
 proc limit*[t](a: var seq[t]) =
   var loop = s.len() - 512
-  for i in 0..loop:
+  for i in 0..<s.len:
+    if i > high(s): break
```
Comment (Araq) [inline tests/gc/gcleak3.nim]: Redundant check, we know that i < s.len inside the loop body.

File: lib/system.nim [hunk 5]
```diff
@@ -2178,6 +2154,40 @@ const
...
+    var s = @[1, 2, 3, 4, 5]
+    s.delete(2)
+    doAssert s == @[1, 2, 4, 5]
+
+    doAssertRaises(IndexDefect):
+        s.delete(10)
+
+  if i > high(x):
+    # xxx this should call `raiseIndexError2(i, high(x))` after some refactoring
+    raise (ref IndexDefect)(msg: "index out of bounds: '" & $i & "' < '" & $x.len & "' failed")
```
Comment (Araq) [inline lib/system.nim:2151]: Instead you should call `raiseIndexError3` or `raiseIndexError2` here.

File: tests/gc/gcleak3.nim (hunk 4 above)
Comment (hnicke) [reply tests/gc/gcleak3.nim]: In line 26, the sequence that is iterated on gets shortened by `s.delete()`. 
I've changed the loop to `for i in high(int)` to clarify the code.

File: lib/system.nim (hunk 5 above)
Comment (hnicke) [reply lib/system.nim:2151]: As I've written earlier, I struggle to properly import/include `chcks` for `raiseIndexError2` to become available in the scope. Once I include `chcks`, a bunch of other declarations are missing.

Among others, I tried this:
```
when not defined(raiseIndexError2):
  when not defined(PNimType):
    import "system/hti"
  include "system/chcks"
# =>  Error: invalid pragma: benign
```
I'm missing expertise on how the stdlib is bootstrapped - any help would be appreciated.

Comment (timotheecour) [reply lib/system.nim:2151]: leaving it as a TODO for future work sounds reasonable to me, unless @Araq has a concrete suggestion here

File: tests/gc/gcleak3.nim (hunk 4 above)
Comment (Araq) [reply tests/gc/gcleak3.nim]: So use a `while` loop...

Comment (hnicke) [reply tests/gc/gcleak3.nim]: done

File: lib/system.nim (hunk 5 above)
Comment (Araq) [reply lib/system.nim:2151]: I'm investigating...

File: tests/gc/gcleak3.nim [hunk 6]
```diff
@@ -18,14 +18,10 @@ for i in 0..1024:
...
 proc limit*[t](a: var seq[t]) =
   var loop = s.len() - 512
-  for i in 0..high(int):
-    if i > high(s): break
-    #echo i
-    #GC_fullCollect()
+  while s.len > 0:
     if getOccupiedMem() > 3000_000: quit("still a leak!")
-    s.delete(i)
+    s.delete(high(s))
```
Comment (timotheecour) [inline tests/gc/gcleak3.nim]: but this (kind of) weakens the test; deleting the last element is "easier" (less work) than deleting elements `0 through high(int)` and stopping when s is empty, and therefore less likely to surface related gc bugs; that's why i preferred the `for i in 0..high(int):` way

Comment (hnicke) [reply tests/gc/gcleak3.nim]: Excuse me, I wasn't sure about the intention of the test. It should be fixed now.

File: lib/system.nim [hunk 7]
```diff
@@ -2178,6 +2154,40 @@ const
...
+  ## See also:
+  ## * `del <#del,seq[T],Natural>`_ for O(1) operation
+  ##
+  runnableExamples:
+    var s = @[1, 2, 3, 4, 5]
+    s.delete(2)
+    doAssert s == @[1, 2, 4, 5]
+
+    doAssertRaises(IndexDefect):
+        s.delete(10)
```
Comment (timotheecour) [inline lib/system.nim]:
```suggestion
        s.delete(4)
```

it's more useful to show the 1st index that fails

File: lib/system.nim [hunk 8]
```diff
@@ -2178,6 +2154,40 @@ const
 import system/dollars
 export dollars
 
+proc delete*[T](x: var seq[T], i: Natural) {.noSideEffect.} =
+  ## Deletes the item at index `i` by moving all `x[i+1..]` items by one position.
```
Comment (timotheecour) [inline lib/system.nim]:
```suggestion
  ## Deletes the item at index `i` by moving all `x[i+1..^1]` items by one position.
```

File: tests/stdlib/tsystem.nim [hunk 9]
```diff
@@ -0,0 +1,38 @@
...
+"""
+
+# TODO: in future work move existing `system` tests here, where they belong
+
+template main =
+
+  block: # system.delete
+    block:
+      var s = @[1]
+      s.delete(0)
```
Comment (timotheecour) [inline tests/stdlib/tsystem.nim:49]:
```suggestion
      s.delete(0)
      doAssert s == @[]
```

File: tests/stdlib/tsystem.nim [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+
+    block:
+      var s = @["foo", "bar"]
+      s.delete(1)
+      doAssert @["foo"] == s
```
Comment (timotheecour) [inline tests/stdlib/tsystem.nim]:
```suggestion
      doAssert s == @["foo"]
```
(more idiomatic: `actual == expected`)

File: tests/stdlib/tsystem.nim [hunk 11]
```diff
@@ -0,0 +1,38 @@
...
+  
+    block:
+      var s = newSeq[string]()
```
Comment (timotheecour) [inline tests/stdlib/tsystem.nim]:
```suggestion
      var s: seq[string]
```

File: tests/stdlib/tsystem.nim [hunk 12]
```diff
@@ -0,0 +1,38 @@
...
+      doAssertRaises(IndexDefect):
+        s.delete(0)
+
+    block:
+      doAssert not compiles(@["foo"].delete(-1))
+
+    block: # bug #6710
+      var s = @["foo"]
+      s.delete(0)
+      doAssert newSeq[string]() == s
```
Comment (timotheecour) [inline tests/stdlib/tsystem.nim]:
```suggestion
      doAssert s == @[]
```

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
@hnicke sorry reviewing this is taking longer than expected, could you please rebase and fix the conflict in tsystem.nim ? let me know if you have difficulties with that

File: lib/system.nim [hunk 13]
```diff
@@ -2178,6 +2154,40 @@ const
...
+  ## See also:
+  ## * `del <#del,seq[T],Natural>`_ for O(1) operation
+  ##
+  runnableExamples:
+    var s = @[1, 2, 3, 4, 5]
+    s.delete(2)
+    doAssert s == @[1, 2, 4, 5]
+
+    doAssertRaises(IndexDefect):
+        s.delete(4)
```
Comment (ringabout) [inline lib/system.nim]:
```suggestion
      s.delete(4)
```

**Comment by timotheecour** [comment]
ping @hnicke (otherwise should we take over?)

**Comment by hnicke** [comment]
sry for the late response.. I will update this PR tomorrow 👍

File: lib/system.nim (hunk 5 above)
Comment (hnicke) [reply lib/system.nim:2151]: @Araq have you been able to look into it?

**Comment by hnicke** [comment]
The PR is now updated.

**Review by ringabout — APPROVED** [review]

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
@araq still no answer on https://github.com/nim-lang/Nim/pull/17821#discussion_r620334045 since april 26 and the code looks fine to me, I'm merging this now as this was LGTM'd by 2 ppl and letting PRs bitrot like this doesn't send a good signal to contributors.
