### PR TITLE
fixes #22932; treats closure iterators as pointers

### LINKED ISSUE #22932: `std/options` don’t consider closure iterators to be pointer types
### Description

https://github.com/nim-lang/Nim/blob/4d11d0619d11d8aecdaff998981efcd054de9760/lib/pure/options.nim#L83-L88

We see `proc` here but not `iterator`. I’m suspicious about such asymmetry.

```nim
import std/options

var it = iterator: int = discard
assert it.option.isSome # Passes.
it = nil
assert it.option.isNone # Fails; equivalent to `it.some.isNone`.
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Current Output

```text
Error: unhandled exception: /home/nickolas/c/test/a.nim(6, 1) `it.option.isNone`  [AssertionDefect]
```

### Expected Output

_No response_

### Possible Solution

Append `| iterator` to the definition of `SomePointer`.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #22932
follow up https://github.com/nim-lang/Nim/pull/21629

### CODE REVIEW

File: lib/pure/options.nim [hunk 1]
```diff
@@ -82,15 +82,15 @@ when defined(nimPreviewSlimSystem):
 
 when (NimMajor, NimMinor) >= (1, 1):
   type
-    SomePointer = ref | ptr | pointer | proc
+    SomePointer = ref | ptr | pointer | proc | iterator
```
Comment (ringabout) [inline lib/pure/options.nim]:
```suggestion
    SomePointer = ref | ptr | pointer | proc | iterator {.closure.}
```

File: lib/pure/options.nim [hunk 2]
```diff
@@ -82,15 +82,15 @@ when defined(nimPreviewSlimSystem):
...
+    SomePointer = ref | ptr | pointer | proc | iterator {.closure.}
 else:
   type
     SomePointer = ref | ptr | pointer
 
 type
   Option*[T] = object
     ## An optional type that may or may not contain a value of type `T`.
-    ## When `T` is a a pointer type (`ptr`, `pointer`, `ref` or `proc`),
+    ## When `T` is a a pointer type (`ptr`, `pointer`, `ref` or `proc` or `iterator {.closure.}`),
```
Comment (SirNickolas) [inline lib/pure/options.nim]:
```suggestion
    ## When `T` is a a pointer type (`ptr`, `pointer`, `ref`, `proc` or `iterator {.closure.}`),
```

With an extra _or_, it reads as `or (proc or iterator) {.closure.}`, but there are no restrictions on the calling convention of procs.
