### PR TITLE
Do not consider enums with holes as ordinals

### LINKED ISSUE #1239: `inc` works on disjoint enum
According to the manual

> ```
> type
>  TTokenType = enum
>    a = 2, b = 4, c = 89 # holes are valid
> ```
> 
> However, it is then not an ordinal anymore, so it is not possible to use these enums as an index type for arrays. The procedures inc, dec, succ and pred are not available for them either.

However, `inc` does not fail on disjoint enums.

IRC Logs

> (04:33:25 PM) flaviu1: Btw, there's a bug in the disjoint enum implementation. It says that `inc` isn't available in the manual, but it does work
> (04:34:23 PM) Araq: flaviu1: guess what ... I bet it's a regression. we got generic constraints, 'inc' stopped being special cased. generic constraints checks for 'enum' ...

### PR DESCRIPTION
**Pull request by LemonBoy**
Make the compiler behave consistently with respect to what's written in
the manual.

Fixes #1239

### CODE REVIEW

File: compiler/types.nim [hunk 1]
```diff
@@ -133,18 +133,19 @@ proc elemType*(t: PType): PType =
   else: result = t.lastSon
   assert(result != nil)
 
-proc isOrdinalType*(t: PType): bool =
+proc enumHasHoles*(t: PType): bool =
+  var b = t
+  while b.kind in {tyRange, tyGenericInst, tyAlias, tySink}: b = b.sons[0]
```
Comment (Araq) [inline compiler/types.nim]: This needs to be ``b = b.lastSon``

File: lib/pure/terminal.nim [hunk 2]
```diff
@@ -468,13 +468,13 @@ proc resetAttributes*(f: File) =
 
 type
   Style* = enum          ## different styles for text output
-    styleBright = 1,     ## bright text
+    styleBright,         ## bright text
```
Comment (Araq) [inline lib/pure/terminal.nim]: But this is not the same. ``styleBright`` is now 0. Whether that makes a difference for terminal.nim, I don't know. Anyway, an enum not starting with 0, is not an enum with a hole.

File: compiler/types.nim [hunk 3]
```diff
@@ -133,18 +133,19 @@ proc elemType*(t: PType): PType =
...
     baseKinds = {tyChar,tyInt..tyInt64,tyUInt8..tyUInt32,tyBool,tyEnum}
     parentKinds = {tyRange, tyOrdinal, tyGenericInst, tyAlias, tySink, tyDistinct}
-  t.kind in baseKinds or (t.kind in parentKinds and isOrdinalType(t.sons[0]))
-
-proc enumHasHoles*(t: PType): bool =
-  var b = t
-  while b.kind in {tyRange, tyGenericInst, tyAlias, tySink}: b = b.sons[0]
-  result = b.kind == tyEnum and tfEnumHasHoles in b.flags
+  (t.kind in baseKinds and not (t.enumHasHoles and not allowEnumWithHoles)) or
+    (t.kind in parentKinds and isOrdinalType(t.sons[0]))
```
Comment (Araq) [inline compiler/types.nim]: ``t.lastSon``

File: lib/pure/terminal.nim (hunk 2 above)
Comment (LemonBoy) [reply lib/pure/terminal.nim]: Sure thing but the inconsistency was bothering me, a quick look shows that nowhere in the code the enum value as an ordinal matters.

Comment (kaushalmodi) [reply lib/pure/terminal.nim]: Oh, styleBright has to be 1, and then the others can follow.

Comment (kaushalmodi) [reply lib/pure/terminal.nim]: It is used here: https://github.com/LemonBoy/Nim/blob/c30612963a4d5f37bc38012e7911e559aa73d8ba/lib/pure/terminal.nim#L503. The current PR will cause all the style encodings to shift by 1. I think I should had a test case or 2 to prevent this in future.

Comment (LemonBoy) [reply lib/pure/terminal.nim]: > I think I should had a test case or 2 to prevent this in future.

Definitely, heh

> Oh, styleBright has to be 1, and then the others can follow.

Not quite because between blink (5) and reverse (7) there's a unused value.

Comment (kaushalmodi) [reply lib/pure/terminal.nim]: I should have carefully reviewed this (on phone now).. but basically this PR should not change the ordinal values of this enum. *If it's not broken don't fix rule applies here :)*

Comment (kaushalmodi) [reply lib/pure/terminal.nim]: Can this enum not be as is, with holes? If not, I'll find out a sensible name for the missing enum with ordinal 6 when I get to a computer.

Comment (LemonBoy) [reply lib/pure/terminal.nim]: A quote from the manual:

> The set's basetype can only be an ordinal type of a certain size.

The holes make the enum a non-ordinal type.

> Can this enum not be as is, with holes?

I think you can also do something like this to avoid the dependency on the ordinal value of the elements:

```nim
const styleToSeq: array[styleBright..styleStrikethrough, int] = [ 1, 2, 3, 4, 6, 7, 8 ]
```

Comment (kaushalmodi) [reply lib/pure/terminal.nim]: @LemonBoy That suggestion would work, but would increase the maintenance cost of keeping that enum up to date.. one would need to update the enum and that const.

How how just filling that "hole"? Just add an enum `styleBlinkRapid` **after** `styleBlink`. See https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters.

Comment (kaushalmodi) [reply lib/pure/terminal.nim]: There is no downside to doing so. If someone is formatting their text with that new ANSI code, and if their terminal supports rapid blinking, then that will happen, else no blinking will happen. It's up to the code implementer to decide; terminal.nim is just providing the API.

Comment (LemonBoy) [reply lib/pure/terminal.nim]: Since this change is orthogonal to the scope of the PR and you're far more familiar with `terminal.nim` I'll just wait for you to patch this first :)

Comment (kaushalmodi) [reply lib/pure/terminal.nim]: @LemonBoy OK, will send a PR in a few mins.

Comment (kaushalmodi) [reply lib/pure/terminal.nim]: Done in https://github.com/nim-lang/Nim/pull/8282. @Araq Can you please review and merge that PR so that this PR can move forward. Thanks!

Comment (kaushalmodi) [reply lib/pure/terminal.nim]: @Lemonboy Can you please rebase this to devel? Now this PR shouldn't need to modify terminal.nim.

**Comment by LemonBoy** [comment]
This is ready for the second round of review/merge.

**Comment by jyapayne** [comment]
This breaks a lot of compatibility with C enums, which can have a lot of holes :( Using them in sets, case statements and other things is now a pain because I have to use some sort of translator or something to get the same effect. Unless there is a better way that I'm not aware of.

For example, I have a lot of translated code from C that uses bit masks in enums. Ex:

```nim
type
  HidKeyboardModifier* {.size: sizeof(cint).} = enum
    KBD_MOD_LCTRL = BIT(0), KBD_MOD_LSHIFT = BIT(1), KBD_MOD_LALT = BIT(2),
    KBD_MOD_LMETA = BIT(3), KBD_MOD_RCTRL = BIT(4), KBD_MOD_RSHIFT = BIT(5),
    KBD_MOD_RALT = BIT(6), KBD_MOD_RMETA = BIT(7), KBD_MOD_CAPSLOCK = BIT(8),
    KBD_MOD_SCROLLLOCK = BIT(9), KBD_MOD_NUMLOCK = BIT(10)
```

(where BIT(0), etc is a bit shift -> BIT(n): int = (1 shl n) )

I used to have a simple case statement to handle this, but now I'm not sure what to do. Any translation advice?

**Comment by LemonBoy** [comment]
Declare a `type HidKeyboardModifier = distinct int` and the enum values as const of that type. Don't forget to borrow any bitwise operator you may need.

**Comment by jyapayne** [comment]
@Araq but it is from c2nim generated code. Any way to configure c2nim to handle these differently?

**Comment by Araq** [comment]
I'm afraid c2nim lacks a ``--mapEnumToDistinct`` feature. :-/

**Comment by jyapayne** [comment]
@LemonBoy thanks for the suggestion. As I said though, I'm using c2nim and have a lot of these instances in my nim-libnx project.

@Araq that's too bad. I'll have to figure something out :/

**Comment by LemonBoy** [comment]
Well then I think the easiest way is to patch `c2nim` and send a PR :P
