### PR TITLE
Don't hide overflow/underflow/divbyzero in semfold 

### LINKED ISSUE #1732: Arithmetic at compile time doesn't catch overflow
Arithmetic at compile time silently overflows:

```
var x = 127'i8 + 127'i8
echo("x = ", x) # x = -2

var
  p1  = 127'i8
  p2  = 127'i8
  sum = p1 + p2 # OverflowError
echo("sum = ", sum)
```

### LINKED ISSUE #2814: Specific types not enforcing types
Sorry for the confusing title. What I mean is:

``` nim
echo ((high(int8) + 1).int8)
```

is producing `128`. If I'm not mistaken, and I haven't made a silly mistake (good chance I have), this should actually be throwing an error, as 128 is outside the range of `int8`. 
On the other hand, being explicit, like

``` nim
echo (128.int8)
```

_does_ cause a conversion error.

What's more, nothing seems to catch the error. That is,

``` nim
const i8: int8 = high(int8) + 1
echo i8 # produces 128
echo (i8 is int8) # produces true!!
echo high(int8) # checking myself, produces 127
```

Here's a range of tests:

``` nim
const 
  i8: int8 = high(int8) + 1
  i16: int16 = high(int16) + 1
  i32: int32 = high(int32) + 1
  i64: int64 = high(int64) + 1
echo i8 # 128
echo i16 # 32768
echo i32 # 2147483648
echo i64 # overflows to -9223372036854775808
```

Note that the `uints` do it too (`uint8` goes to 256). I can't test with `uint64`, since it doesn't have a `high` function.

For a related problem, see the following:

This is different from the original issue in that even being explicit doesn't raise an error if the type is involved in the expression.

``` nim
echo int8(int8(128) + int8(-129)) # gives "-1" without error
echo int8(128) # raises error
```

The compiler doesn't seem to care about the types inside the first expression, which can lead to some unexpected results.

``` nim
echo int8(int8(-128) + int8(-1)) # gives -129, which is outside low(int8) == -128
```

In short, specifying type only seems to work sometimes.

### LINKED ISSUE #5326: bug in pred
``` nim
type
 MyEnum = enum
    Val0, Val1, Val2, Val3, Val4

template loop[T](startFrom:T, container: var T, body:untyped):typed =
  #[ 
    this template will iterate of all values starting at startfrom
   ]#
  var
    pre, suc: T
    goDown=true
    goUp=true
  try:
    pre = pred(startFrom)
  except OverflowError:
    pre = startFrom
    goDown = false
    echo "started at bottom"
  suc = startFrom
 
  while goUp or goDown:
    if goUp:
      container = suc
      body
      try:
        suc =  succ(suc)
      except OverflowError:
        goUp = false
        echo "reached top"
    if goDown:
      container = pre
      body
      try:
        pre = pred(pre)
      except OverflowError:
        goDown= false
        echo "reached bottom"

var i: Myenum = Val2 # the variable in which the value is stored. the first value is deleted
const start: Myenum = Val0 # the value to start from
start.loop(i):
  echo $i
```
the output of the code above is:
```
Val0
255 (invalid data!)
reached bottom
Val1
Val2
Val3
Val4
reached top
```

but if you change 
```nim
const start: Myenum = Val0 # the value to start from
```
this line into 
```nim
var start: Myenum = Val0 # the value to start from
```
or
```nim
let start: Myenum = Val0 # the value to start from
```
the output is
```
started at bottom
Val0
Val1
Val2
Val3
Val4
reached top
```
as you would expect.
and if you would change the same line to
```nim
const start: Myenum = Val2 # the value to start from
```
the output is 
```
Val2
Val1
Val3
Val0
reached bottom
Val4
reached top
```
as you would expect as well.
even
```nim
const start: Myenum = Val4  # the value to start from
```
gives the expected output:
```
Val4
reached top
Val3
Val2
Val1
Val0
reached bottom
```

### LINKED ISSUE #5829: Nim beginner's feedback: inconsistent integer overflow checks
I've recently introduced Nim to a number of colleagues (mostly with a C++ and Go background), and I want to share some of the feedback I got.

Surprise: integer overflows are handled different at compile-time vs. runtime
```
const a = 1 shl 62
var   b = 1 shl 62

echo(a * 2) # problem: no error (and surprising result !)
echo(b * 2) # ok: runtime error - overflow
```

Runtime integer overflow checks are generally regarded as a very welcome feature, but there might be some remaining implementation (or specification) issues.

### LINKED ISSUE #6997: Boundary checker doesn't work when adding values known at compile time
Example:
```nim
let x: int64 = 9223372036854775807 # OK
let y: int64 = 9223372036854775808 # Error: number 9223372036854775808 out of valid range
let z: int64 = 9223372036854775807 + 1 # OK
doAssert z == 9223372036854775807 # ???
```

For literals this doesn't really matter since nobody would write code like that, but it also happens when either or both operands is a constant, which is more significant.

### PR DESCRIPTION
**Pull request by GULPF**
An attempt fix an old compiler issue...

Currently, saturated arithmetic is used to implement constant folding. This means that arithmetic operations behaves differently when evaluated by the constant folder compared to when they are evaluated during run time or by the VM, since saturated arithmetic hides overflows:
```nim
static:
    var x = high(int8)
    echo x + 1 # Error

var x = high(int8)
echo x + 1 # Error

echo high(int8) + 1 # Prints 128
```

This PR changes the behavior of constant folding so that folding only occurs when the arithmetic operation is safe (no over-/underflow or division by zero). When the operation is not safe, no folding is performed, which results in a run time error. Note that it's not a good idea to give a compile time error, because it might catch errors that logically can't happen. For example, this should compile:
```nim
const x = high(int8)
let y =
  if x == high(int8):
    x
  else:
    x + 1
```
(most of these are actually duplicates)

Fixes #6997
Fixes #5829
Fixes #2814
Fixes #1732
Fixes #5326

### CODE REVIEW

File: compiler/types.nim [hunk 1]
```diff
@@ -612,13 +612,13 @@ proc firstOrd*(t: PType): BiggestInt =
     else:
       assert(t.n.sons[0].kind == nkSym)
       result = t.n.sons[0].sym.position
-  of tyGenericInst, tyDistinct, tyTypeDesc, tyAlias:
+  of tyGenericInst, tyDistinct, tyTypeDesc, tyAlias, tyStatic:
```
Comment (GULPF) [inline compiler/types.nim]: Not entirely sure if this change is correct, but one of the tests failed without it

Comment (Araq) [reply compiler/types.nim]: It's probably slightly wrong, but it's better than before.
