### PR TITLE
fix #12122

### LINKED ISSUE #12122: `ByteAddress` broken for its intended purpose
https://github.com/nim-lang/Nim/blob/cb0450398a5695e1e1193e6c49ff9c7548980438/lib/system.nim#L2205

`ByteAddress` is an `int` - this is problematic for several reasons:

* you can't use it for its documented purpose of printing / readability: address space generally is not considered  to go into the negative
* you can't do arithmetic on it because `int` is a checked type that will raise even on seemingly valid pointer operations: for example linux in 32-bit mode uses a 3gb address space for pointers meaning that at least at the 2gb mark, it crosses into `int` negative space

It seems appropriate to deprecate this type and add a new `uint`-based distinct type that has a few pointer operations attached to its name along with documentation explaining the pitfalls of doing  so.

### PR DESCRIPTION
**Pull request by bung87**
as described in https://github.com/nim-lang/Nim/pull/21089 deprecate `ByteAddress` for current stage.

### CODE REVIEW

**Comment by arnetheduck** [comment]
@Araq in this PR, there's still the cast to `int` - it will be quite hard to track down these invalid casts down the line because they can no longer be grep:ed for.

File: lib/system/ctypes.nim [hunk 1]
```diff
@@ -67,7 +67,7 @@ type # these work for most platforms:
     ## This is the same as the type `unsigned long long` in *C*.
 
 type
-  ByteAddress* = int
+  ByteAddress* {.deprecated: "use `uint`".} = int
```
Comment (daniel-j) [inline lib/system/ctypes.nim:70]: Why does the message say uint when the type is int?
