### PR TITLE
fix #5296

### LINKED ISSUE #5296: Compiling in release mode prevents valid code execution.
This snippet of code behaves differently depending on whether or not release mode is used for compilation:
```
proc bug() : void =
    var x = 0
    try:
        inc x
        raise new(Exception)
    except Exception:
        echo x

bug()
```
Here's what happens:
```
$ nim c bug.nim
...
$ ./bug
1
$ nim c -d:release bug.nim
...
$ ./bug
0
$ nim --version
Nim Compiler Version 0.16.0 (2017-01-08) [MacOSX: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 5947403e84ba44397b35f93f9d327c76e794210f
active boot switches: -d:release
```
Please observe that the code prints **1** when using normal compilation and **0** when using release mode.

### PR DESCRIPTION
**Pull request by zah**
My patch follows the rest of the logic in sempass2, but don't we introduce too many volatile variables? We can try to detect only the variables used in the `except:` block.

### CODE REVIEW

**Comment by Araq** [comment]
Very true, but this is the bugfix I had in mind. :-)

File: compiler/sempass2.nim [hunk 1]
```diff
@@ -577,6 +577,9 @@ proc trackOperand(tracked: PEffects, n: PNode, paramType: PType) =
         markGcUnsafe(tracked, a)
       elif tfNoSideEffect notin op.flags:
         markSideEffect(tracked, a)
+  if paramType != nil and paramType.kind == tyVar:
```
Comment (Araq) [inline compiler/sempass2.nim]: Er, there is an ``tracked.inTryStmt > 0`` missing.

Comment (zah) [inline compiler/sempass2.nim]: There is such a check in `makeVolatile` itself. I didn't see a reason for duplicating it and the rest of the code is following the same pattern.

Comment (Araq) [inline compiler/sempass2.nim]: my bad then.
