### PR TITLE
fix #18142: nim doc now works across windows partitions (and make `nativeToUnixPath` work with abs paths)

### LINKED ISSUE #18142: nim doc doesn't work across windows partitions
nim doc output following message for any file.

```
Error: unhandled exception: globs.nim(48, 3) `not path.isAbsolute`  [AssertionDefect]
```

```
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-06-01
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c0e8199acc9f49caa36bae34d103600d112b66f3
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by timotheecour**
fix https://github.com/nim-lang/Nim/issues/18142 (and this was also needed in another PR)

follows cygwin convention which is the most reasonable way to convert C:\foo to a unix path

### CODE REVIEW

File: lib/std/private/globs.nim [hunk 1]
```diff
@@ -45,10 +45,15 @@ iterator walkDirRecFilter*(dir: string, follow: proc(entry: PathEntry): bool = n
 
 proc nativeToUnixPath*(path: string): string =
```
Comment (Varriount) [inline lib/std/private/globs.nim:46]: __[As I](https://github.com/nim-lang/Nim/issues/18142#issuecomment-851889322)__ (and __[others](https://github.com/nim-lang/Nim/pull/13265#issuecomment-674700064)__) have mentioned elsewhere, this is not a function that should be used. It *cannot* accurately translate paths without either a loss of information, or ambiguity. Windows has a __[couple of different path types](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats)__ and using a function that attempts to convert them all to some standard format is not going to work. Please stop pushing this.

**Review by Varriount — CHANGES_REQUESTED** [review]

**Comment by Araq** [comment]
The Nim doc generator should avoid nativeToUnixPath and get fixed differently.

**Comment by Araq** [comment]
Sorry, I didn't realize this is an internal API.

File: lib/std/private/globs.nim (hunk 1 above)
Comment (timotheecour) [reply lib/std/private/globs.nim:46]: >  It cannot accurately translate paths without either a loss of information, or ambiguity.

cygwin works just fine, which is almost what I'm doing. future work will follow more closely what `cygpath` does, so that a spec is followed, you can't argue with that (I'm currently almost doing the same except for 2 edge cases).
