### PR TITLE
highlite: fix #17890 - tokenize Nim escape seq-s

### LINKED ISSUE #17890: regression: rendering of strings has bad syntax highlighting
### Example
```nim
proc fn*() =
  runnableExamples:
    let a = "ok1\nok2\nok3"
    let b = "ok1\nok2 alt\nok3"
```
nim doc main

### Current Output
image

### Expected Output
output with 1.2 was better:
image

### Additional Information
1.5.1 01bca8cd4fad857124794144bff09ae0326895bd
/cc @a-mr if you have any ideas?

### PR DESCRIPTION
**Pull request by a-mr**
**Before:**

image

**After:**

image

### CODE REVIEW

File: tests/stdlib/thighlite.nim [hunk 1]
```diff
@@ -0,0 +1,13 @@
+
+import unittest
+import ../../lib/packages/docutils/highlite
+
+suite "Nim tokenizing":
```
Comment (timotheecour) [inline tests/stdlib/thighlite.nim]:
```suggestion
block: # Nim tokenizing"
```
(will fix the CI failure; `suite` is annoying IMO as it logs even when things work)

File: lib/packages/docutils/highlite.nim [hunk 2]
```diff
@@ -190,31 +190,33 @@ proc nimNextToken(g: var GeneralTokenizer, keywords: openArray[string] = @[]) =
...
   if g.state == gtStringLit:
-    g.kind = gtStringLit
-    while true:
+    if g.buf[pos] == '\\':
+      g.kind = gtEscapeSequence
+      inc(pos)
       case g.buf[pos]
-      of '\\':
-        g.kind = gtEscapeSequence
+      of 'x', 'X':
```
Comment (timotheecour) [inline lib/packages/docutils/highlite.nim:197]: * pre-existing (maybe?) but what about other escape sequences (refs https://nim-lang.github.io/Nim/manual.html#lexical-analysis-string-literals), eg:
```nim
proc main*()=
  ## \x123
  ## `\x123`
  runnableExamples:
    echo "abc\x1234"
    echo "abc\x1"
    echo "abc\uabcd3" # bug with this one
    echo "abc\u{12345}def" # and this one
    echo "abc\e"
main()
```

is there possibility to reuse code (possibly via a lib/std/private/lexerutils) to avoid duplication with what compiler already does?

(a plausible alternative is to not highlight things inside string literals, but see also https://github.com/nim-lang/Nim/pull/17722 which would specify the language with which to highlight)

supporting `\u` etc can also be defered to future work, since it's more rare

Comment (a-mr) [reply lib/packages/docutils/highlite.nim:197]: I just enabled the existing code by moving case of first `\` into surrounding `if` — Github obviously shows more changes than has been really done.

I can hardly guess why `highlite.nim` was written with its own separate lexer.

@Araq ?

Comment (Araq) [reply lib/packages/docutils/highlite.nim:197]: Lexer: Transforms  "\n"  into  \10. Skips comments and whitespace (more or less).
Highlighter: Highlights "\n". Highlights comments and whitespace.

Different code for different things.
