### PR TITLE
fix nested call regression in generic bodies

### LINKED ISSUE #22187: `nim c -c` `SIGSEGV` regression between 1.6 and 2.0, both refc and ORC
### Description

```nim
template m(T: type, s: int64): int64 = s
func p(n: int64): int = int(n)
type F[T; s: static int64] = object
  k: array[p(m(T, s)), int64]
```

The compilation (mis)behaves the same way under refc and ORC under each tested compiler version, `version-1-6` (1.6.14), `version-2-0` (`e8d0f1c3aedd8290cc972e3d06f642e88dbe783e`), and `devel` (`41ec894cb0aa0b0d233a0f62ff4929d64ddad3a7`).

### Nim Version

Compiles successfully:
```
Nim Compiler Version 1.6.14 [Linux: amd64]
Compiled at 2023-06-29
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 71ba2e7f3c5815d956b1ae0341b0743242b8fec6
active boot switches: -d:release
```

Regression between 1.6 and 2.0, so these `SIGSEGV`.

`version-2-0`:
```
Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-06-29
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: e8d0f1c3aedd8290cc972e3d06f642e88dbe783e
active boot switches: -d:release
```

`devel`:
```
Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-06-29
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 41ec894cb0aa0b0d233a0f62ff4929d64ddad3a7
active boot switches: -d:release
```

### Current Output

```text
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
```

### Expected Output

```text
Not a SIGSEGV
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
fixes #22187

What was done for `tyGenericParam` arguments in calls in generic bodies in #22029 is now done for `tyFromExpr` parameters. The "fauxMatch" mechanism seems to have been in place for something like this but it made things more confusing than it had to be in this case, at least I can't see the need for it in the current state, so just skip it for `tyUnknown` (= `tyFromExpr` apparently) and use the failing overload fallback.

### CODE REVIEW

File: compiler/sigmatch.nim [hunk 1]
```diff
@@ -2213,6 +2220,10 @@ proc paramTypesMatchAux(m: var TCandidate, f, a: PType,
   of isNone:
     # do not do this in ``typeRel`` as it then can't infer T in ``ref T``:
     if a.kind in {tyProxy, tyUnknown}:
+      if a.kind == tyUnknown and c.inGenericContext > 0:
+        # don't bother with fauxMatch mechanism in generic type,
+        # reject match, typechecking will be delayed to instantiation
+        return nil
```
Comment (Araq) [inline compiler/sigmatch.nim:2226]: Since typechecking will be delayed to instantiation, why is this code even called with `c.inGenericContext > 0`?

Comment (metagn) [reply compiler/sigmatch.nim:2226]: Was just for safety in case some `tyFromExpr` leaks into instantiated code for some reason. Without this condition `tyUnknown` = `tyFromExpr` would also never use `fauxMatch` which might have broken something I wasn't aware of. The delaying also only happens with `c.inGenericContext > 0` in `semcall`, so this was a bit more predictable.

If this CI run passes I will test removing the condition

Comment (Araq) [reply compiler/sigmatch.nim:2226]: ok

**Comment by tersec** [comment]
Would be interested in a backport to `version-2-0` as well.

**Comment by metagn** [comment]
The issue is a regression in devel caused by #22029, it's possible there are more regressions so it could stay in devel for now
