### PR TITLE
Fixes #5034 illformed AST from getImpl with proc returning value

### LINKED ISSUE #5034: illformed AST from getImpl with proc returning value
The ```ProcDef``` returned from ```getImpl``` has an extra child (```Sym "result"```).

```nim
import macros

macro echoImpl(x: typed): auto =
  echo x.treeRepr
  let impl = x[0].symbol.getImpl
  echo impl.treeRepr
  result = impl.copyNimTree

proc foo1(x: float): float = x

echoImpl: foo1(1.0)
#[
Call
  Sym "foo1"
  Float64Lit 1.0
ProcDef
  Sym "foo1"
  Empty
  Empty
  FormalParams
    Sym "float"
    IdentDefs
      Ident !"x"
      Sym "float"
      Empty
  Empty
  Empty
  Asgn
    Sym "result"
    Sym "x"
  Sym "result"
tgetimpl1.nim(11, 1) template/generic instantiation from here
tgetimpl1.nim(9, 1) Error: illformed AST: proc foo1(x: float): float =
  result = x
]#
```

### PR DESCRIPTION
**Pull request by DylanModesitt**
This is an attempt at fixing #5034, whereby macros that attempt to re-define a proc run into a variety of issues relating to the ownership of the `result` symbol. For example:

- `addResult`, on the 'second pass' would fail because `n[resultPos].sym.owner != getCurrOwner(c)` which gives `"incorrect result proc symbol"`
- `result = ...` gets re-written to `result = result = ...` because `semReturn` in `semexprs` does transformations twice due to `c.p.resultSym != n[0][0].sym` in the case of returning nodes sourced from `getImpl(Transformed)?`

As a fix, ownership mismatch is responded to by re-writing `result` nodes equal to `n[resultPos].sym`. As a less-preferred alternative to this PR, the error message for attempting to do this kind of redefinition could be improved to be discouraged.

### CODE REVIEW

**Comment by timotheecour** [comment]
> This is an attempt at fixing #5034,

if it fixes it, write `fixes #5034` in top PR message so that the issue will auto-close and this PR gets cross referenced from the issue

File: tests/macros/tmacrogetimpl.nim [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+  proc buzz: string =
+    result = "lightyear"
+  if what == "buzz":
+    result = ("buzz " & buzz())
+  else:
+    result = what
+  return result
+
+copyImpl(foo1, foo2)
+echo foo1(1'f)
```
Comment (timotheecour) [inline tests/macros/tmacrogetimpl.nim]: prefer doAssert to echo, see contributing.html

File: tests/macros/tmacrogetimpl.nim [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+1.0
+10.0
+1.0
+buzz lightyear
+macros
+'''
+"""
+import macros
+
+# 5034
```
Comment (timotheecour) [inline tests/macros/tmacrogetimpl.nim]:
```suggestion
# bug #5034
```

see rationale in contributing.html

File: tests/macros/tmacrogetimpl.nim [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+  if one:
+    return 1'f
+  result = x
+
+proc bar1(what: string): string =
+  ## be a little more adversarial with `skResult`
+  proc buzz: string =
+    result = "lightyear"
+  if what == "buzz":
+    result = ("buzz " & buzz())
```
Comment (timotheecour) [inline tests/macros/tmacrogetimpl.nim]:
```suggestion
    result = "buzz " & buzz()
```

File: compiler/semstmts.nim [hunk 4]
```diff
@@ -1437,16 +1437,34 @@ proc semBorrow(c: PContext, n: PNode, s: PSym) =
   else:
     localError(c.config, n.info, errNoSymbolToBorrowFromFound)
 
+proc swapResult(n: PNode, sRes: PSym, dNode: PNode) =
+  ## Swap nodes that are (skResult) symbols to d(estination)Node.
+  for i in 0..<n.safeLen:
+    if n[i].kind == nkSym:
```
Comment (timotheecour) [inline compiler/semstmts.nim]: and
