### PR TITLE
fix #12946 Bad C++ codegen on distinct generics C++ types

### LINKED ISSUE #12946: Bad C++ codegen on distinct generics C++ types (Atomics here).
I expect this would happen as well with distinct std::vector.

Testcase:

```Nim
import std/atomics
type Futex = distinct Atomic[int32]

var x: Futex
```

Output
```
/home/beta/.cache/nim/cpp_futex_d/@mcpp_futex.nim.cpp:31:1: error: invalid use of template-name ‘std::atomic’ without an argument list
   31 | std::atomic x__bqCKmFWuGC2fnFKyiPKa3A;
      | ^~~
/home/beta/.cache/nim/cpp_futex_d/@mcpp_futex.nim.cpp:31:1: note: class template argument deduction is only available with ‘-std=c++17’ or ‘-std=gnu++17’
In file included from /usr/include/c++/9.2.0/atomic:41,
                 from /home/beta/.cache/nim/cpp_futex_d/@mcpp_futex.nim.cpp:10:
/usr/include/c++/9.2.0/bits/atomic_base.h:145:12: note: ‘template<class _Tp> struct std::atomic’ declared here
  145 |     struct atomic;
      |            ^~~~~~
```

So it seems like with distinct the generic type gets stripped out during codegen.

### PR DESCRIPTION
**Pull request by bung87**
fix #12946

### CODE REVIEW

File: tests/cpp/t12946.nim [hunk 1]
```diff
@@ -0,0 +1,4 @@
+import std/atomics
+type Futex = distinct Atomic[int32]
+
+var x: Futex
```
Comment (ringabout) [inline tests/cpp/t12946.nim:4]: ref https://github.com/nim-lang/Nim/pull/21164

cpp backend is not tested.
