### PR TITLE
Fix passing environment in startProcess (win)

### LINKED ISSUE #4499: stdlib: startProcess doesn't handle environment properly.
Under Windows, if `useWinUnicode` is enabled, proc `startProcess` handles its `environment` argument incorrectly:
```nim
import osproc, os, strtabs

# Launches a copy of itself with a new environment.

if paramCount() == 0:
  # Parent process

  let env = newStringTable()
  env["A"] = "1"
  env["B"] = "2"
  env["C"] = "3"

  let p = startProcess(
    getAppFilename(),
    args = @["child"],
    env = env,
    options = {poStdErrToStdOut, poUsePath, poParentStreams}
  )

  discard p.waitForExit

else:
  # Child process
  # Should output "123"
  # Outputs "2"
  echo getEnv("A") & getEnv("B") & getEnv("C")  
```
Reason: `startProcess` first constructs environment `cstring` as specified by `CreateProcessA` (key-value pairs, separated with \0, with additional \0 at the end). Then, if `useWinUnicode` is enabled, this `cstring` is converted via `newWideCString`. However, it stops after the first encountered \0, so only the first pair is handled.

### PR DESCRIPTION
**Pull request by nigredo-tori**
Previous implementation used newWideCString, which doesn't
handle strings with \0 characters.

Fixes #4499 .

### CODE REVIEW

File: lib/pure/osproc.nim [hunk 1]
```diff
@@ -410,6 +410,45 @@ when defined(Windows) and not defined(useNimRtl):
       copyMem(addr(result[L]), cstring(x), x.len+1) # copy \0
       inc(L, x.len+1)
 
+  proc envToWideCString(env: StringTableRef): WideCString =
+    # newWideCString stops on \0 characters, so we have to
```
Comment (Araq) [inline lib/pure/osproc.nim]: There is a ``newWideCString`` that takes a length.

File: lib/pure/osproc.nim [hunk 2]
```diff
@@ -410,6 +410,45 @@ when defined(Windows) and not defined(useNimRtl):
...
+    # convert every pair separately.
+    const wcharSize = 2
+    var rows = newSeq[tuple[str: WideCString, len: int]]()
```
Comment (Araq) [inline lib/pure/osproc.nim]: This temporary seq is not required.

File: lib/pure/osproc.nim [hunk 3]
```diff
@@ -410,6 +410,45 @@ when defined(Windows) and not defined(useNimRtl):
...
+    var L = 0  # length in wide chars
+
+    for key, val in pairs(env):
+      let str = newWideCString(key & "=" & val)
+      let row = (str: str, len: str.len)
+      rows.add(row)
+      inc(L, succ row.len)
+
+    # Leave space for trailing \0
+    result = cast[WideCString](alloc0(wcharSize * (succ L)))
```
Comment (Araq) [inline lib/pure/osproc.nim]: Seems dangerous, WideCString is a ``ref``.

File: lib/pure/osproc.nim (hunk 1 above)
Comment (nigredo-tori) [inline lib/pure/osproc.nim]: True. But it still stops on \0 char (see `runes` iterator). Didn't want to break any code depending on it.

File: lib/pure/osproc.nim (hunk 2 above)
Comment (nigredo-tori) [inline lib/pure/osproc.nim]: Can't see a way to do it without it, that doesn't involve calling newWideCString twice per pair, or allocating overly large result string.

File: lib/pure/osproc.nim (hunk 3 above)
Comment (nigredo-tori) [inline lib/pure/osproc.nim]: My bad. Used the existing code (`envToCString`, former `buildEnv`) as a template, didn't look closely at types... Will fix first thing tomorrow.

File: lib/pure/osproc.nim (hunk 1 above)
Comment (Araq) [inline lib/pure/osproc.nim]: Please fix ``newWideCString`` then, it must take length into account properly.

**Comment by Araq** [comment]
Excellent job!
