### PR TITLE
fixes #22923; fixes `=dup` issues

### LINKED ISSUE #22923: `Error: internal error: genMagicExpr: mDup` when using `arrayWith` with some types.
### Description

Procedure `withArray`, when used with any types except `int` and `string` as first argument (I tested int32, int64, uint, uint8, char), crashes the compiler:

```Nim
let
  a: int = 100
# a: string = "nim"
  b: int32 = 200'i32
# b: char = 'c'
# b: uint = 300'u

let
  x = arrayWith(a, 8) # compiles
  y = arrayWith(b, 8) # internal error
# y = arrayWith(14, 8) # integer literal also results in a crash

echo x
echo y
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-05
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

-----------------------------------------------------------------------------------

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-11-07
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches:

-----------------------------------------------------------------------------------

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-11-08
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 2e070dfc76a1badfaad08d62b0f3f02f6ba2bc02
active boot switches: -d:release

### Current Output

nim-2.0.0-release
```text
/usr/lib64/nim/lib/system.nim(2818, 25) Error: internal error: genMagicExpr: mDup
No stack traceback available
To create a stacktrace, rerun compilation with './koch temp c <file>', see https://nim-lang.github.
io/Nim/intern.html#debugging-the-compiler for details
```
nim-devel-debug
```text
Hint: used config file '/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/config/nim.cfg' [Conf]
Hint: used config file '/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/config/config.nims' [Conf]
.....................................................................
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/lib/system.nim(2916, 25) Error: internal error: genMagicExpr: mDup
Traceback (most recent call last)
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/nim.nim(168) nim
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/nim.nim(123) handleCmdLine
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/main.nim(338) mainCommand
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/main.nim(306) compileToBackend
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/main.nim(143) commandCompileToC
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/pipelines.nim(312) compilePipelineProject
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/pipelines.nim(242) compilePipelineModule
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/pipelines.nim(186) processPipelineModule
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/pipelines.nim(24) processPipeline
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/cgen.nim(2117) genTopLevelStmt
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/cgen.nim(1145) genProcBody
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3112) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1281) genTryGoto
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2749) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3083) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(431) genVarStmt
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(414) genSingleVar
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(401) genSingleVar
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(137) loadInto
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgcalls.nim(817) genAsgnCall
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgcalls.nim(420) genPrefixCall
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/cgen.nim(746) initLocExpr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2935) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/cgen.nim(1385) genProc
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/cgen.nim(1359) genProcNoForward
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/cgen.nim(1220) genProcAux
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/cgen.nim(1145) genProcBody
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3061) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(658) genBlock
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3061) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(658) genBlock
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3082) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(634) genWhileStmt
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2749) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3063) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2760) genStmtList
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1651) genStmts
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3067) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3095) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(1644) genAsgn
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgstmts.nim(147) loadInto
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(3020) expr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/ccgexprs.nim(2403) genMagicExpr
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/msgs.nim(630) internalErrorImpl
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/msgs.nim(585) liMessage
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/msgs.nim(434) handleError
/home/archargelod/Fluffy/code/nim/atlas-workspace/nim-devel/compiler/msgs.nim(423) quit
```

### Expected Output

```text
[100, 100, 100, 100, 100, 100, 100, 100]
[200, 200, 200, 200, 200, 200, 200, 200]
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #22923

### CODE REVIEW

**Comment by ringabout** [comment]
The `=dup` raising unlisted Exception Exception seems to be the same issue of https://github.com/nim-lang/Nim/issues/23129, I will fix it later

File: lib/system.nim [hunk 1]
```diff
@@ -2926,4 +2926,5 @@ proc arrayWith*[T](y: T, size: static int): array[size, T] {.raises: [].} =
     when nimvm:
       result[i] = y
     else:
-      result[i] = `=dup`(y)
+      {.cast(raises: []).}:
+        result[i] = `=dup`(y)
```
Comment (ringabout) [inline lib/system.nim]:
```suggestion
      {.cast(raises: []).}: # TODO: fixme bug #23129
        result[i] = `=dup`(y)
```
