### PR TITLE
std/random: fix overflow bugs #16360 #16296 #17670

### LINKED ISSUE #16296: `rand(a: HSlice)` fails with large ranges of int64 or uint64 values
`rand` fails with large ranges of int64 or uint64 values

### Example
```nim
when true:
  import std/random
  echo rand(10'u64 .. uint64.high) # bug RangeDefect
  echo rand(-2.. int.high-1) # bug: OverflowDefect
```

### Current Output
RangeDefect or OverflowDefect

### Expected Output
works

### Additional Information
devel 1.5.1 2297b9623843bb4c1dbd201a8fb57f9ec334c164
EDIT: related: https://github.com/nim-lang/Nim/issues/10258

### LINKED ISSUE #16360: `random` module randomly raises defect
https://github.com/nim-lang/Nim/blob/1082d62b089e54a584e15b0f97a4b247e214d9ef/lib/pure/random.nim#L327

the `int` conversion prevents `rand()` from being used with any value larger than `int.max`, even though the function signature clearly allows the full range of `Ordinal` types to be used

### LINKED ISSUE #17670: `rand` fails for uint64 range on 32 bit platform
Function `rand` raises `RangeDefect` when given a uint64 range on a 32 bit platform.

### Example
```nim
import std/random
import std/math

type UInt48 = range[0'u64..2'u64^48-1]

let x = rand(UInt48)
```

### Current Output
```
user@development:~/Development/nim-bugreport$ nim c --cpu:i386 --passC:-m32 --passL:-m32 -r repro.nim 
Hint: used config file '/home/user/.asdf/installs/nim/1.4.4/config/nim.cfg' [Conf]
Hint: used config file '/home/user/.asdf/installs/nim/1.4.4/config/config.nims' [Conf]
................
/home/user/Development/nim-bugreport/repro.nim(6, 5) Hint: 'x' is declared but not used [XDeclaredButNotUsed]
CC: stdlib_system.nim
CC: stdlib_times.nim
CC: stdlib_random.nim
CC: repro.nim
Hint:  [Link]
Hint: 40475 lines; 0.886s; 60.84MiB peakmem; Debug build; proj: /home/user/Development/nim-bugreport/repro.nim; out: /home/user/Development/nim-bugreport/repro [SuccessX]
Hint: /home/user/Development/nim-bugreport/repro  [Exec]
/home/user/Development/nim-bugreport/repro.nim(6) repro
/home/user/.asdf/installs/nim/1.4.4/lib/pure/random.nim(367) rand
/home/user/.asdf/installs/nim/1.4.4/lib/pure/random.nim(316) rand
/home/user/.asdf/installs/nim/1.4.4/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: value out of range: 281474976710655 notin -2147483648 .. 2147483647 [RangeDefect]
Error: execution of an external program failed: '/home/user/Development/nim-bugreport/repro '
```

### Expected Output

No error

### Possible Solution

In `random.nim` the offending line converts range values to int, which do not fit on a 32 bit platform:

```nim
result = T(rand(r, int(x.b) - int(x.a)) + int(x.a))
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.4.4 [Linux: amd64]
Compiled at 2021-03-25
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2ff517462bf8609b30e6134c96658aa7912b628a
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by timotheecour**
fix #16360
fix #16296
fix #17670

### CODE REVIEW

File: lib/pure/random.nim [hunk 1]
```diff
@@ -204,7 +204,7 @@ proc skipRandomNumbers*(s: var Rand) =
   s.a0 = s0
   s.a1 = s1
 
-proc rand*(r: var Rand; max: Natural): int {.benign.} =
+proc rand*[T: uint | uint64](r: var Rand; max: T): T =
```
Comment (ringabout) [inline lib/pure/random.nim]: When we need `gcsafe`? Should we mark all as `{.benign.}` or at least `{.gcsafe.}`?

Comment (timotheecour) [reply lib/pure/random.nim]: benign seems to be used very randomly (or at least I'm not understanding when it gets used vs not); I've removed it because we can rely on effect system to infer those.

Comment (rockcavera) [reply lib/pure/random.nim]: Is the `{.benign.}` pragma documented? What is your function?

Comment (timotheecour) [reply lib/pure/random.nim]: > Is the {.benign.} pragma documented?

https://github.com/nim-lang/Nim/issues/10123

Comment (Araq) [reply lib/pure/random.nim]: If you need uint64 to fix the bug internally this doesn't have to imply an API addition.

File: lib/pure/random.nim [hunk 2]
```diff
@@ -213,15 +213,27 @@ proc rand*(r: var Rand; max: Natural): int {.benign.} =
...
   ## * `rand proc<#rand,typedesc[T]>`_ that accepts an integer or range type
-  runnableExamples("-r:off"):
+  runnableExamples:
     var r = initRand(123)
-    assert r.rand(100) == 96 # implementation defined
-
+    if false:
+      assert r.rand(100'u) == 96'u # implementation defined
+  # pending csources >= 1.4.0 or fixing https://github.com/timotheecour/Nim/issues/251#issuecomment-831599772,
+  # use `runnableExamples("-r:off")` instead of `if false`
```
Comment (Araq) [inline lib/pure/random.nim]: No, not "pending csources >= 1.4.0", stop pushing your agenda. The csources work just fine and if the compiler cannot bootstrap without constant csources updates, maybe it's because it has too many dependencies?

File: lib/pure/random.nim [hunk 3]
```diff
@@ -644,4 +659,8 @@ when not defined(nimscript) and not defined(standalone):
     ##   with a given seed
     state = initRand()
 
+proc rand*[T: uint | uint64](max: T): T {.inline.} =
+  ## Overload using the default RNG.
+  rand(state, max)
```
Comment (Araq) [inline lib/pure/random.nim]: Bugfix != API additions.

File: lib/pure/random.nim (hunk 2 above)
Comment (timotheecour) [reply lib/pure/random.nim]: fixed for sake of moving on with this PR but it will have to happen at some point or another (eg around time 2.0 is released), at which point it's only a good idea to keep track of places needed fixing. Cost of upgrading csources_v1 (now that installation is fwd/backward compatible and theres' an API `nimBuildCsourcesIfNeeded` every CI uses) is minimal compared to the costs of bending over backwards to support current version of csources_v1.

File: lib/pure/random.nim (hunk 1 above)
Comment (timotheecour) [reply lib/pure/random.nim]: fixed

File: lib/pure/random.nim (hunk 3 above)
Comment (timotheecour) [reply lib/pure/random.nim]: fixed

**Comment by timotheecour** [comment]
PTAL

**Comment by timotheecour** [comment]
ping @Araq
