### PR TITLE
[vm]fixes #15974 #12551 #19464 #16020 #16780 #16613 #14553 #19909 #18641

### LINKED ISSUE #12551: [regression] var param corruption and variable mutation when run the code with VM
Very hard to shorten the example code, sorry if it's a bit intimidating.
It can be a single bug or two bugs. 

### Example
```nim
type
  StUint = object
    lo: uint64

func `+=`(x: var Stuint, y: Stuint) =
  x.lo += y.lo

func `-`(x, y: Stuint): Stuint =
  result.lo = x.lo - y.lo

func `+`(x, y: Stuint): Stuint =
  result.lo = x.lo + y.lo

func `-=`(x: var Stuint, y: Stuint) =
  x = x - y

func `<`(x, y: Stuint): bool=
  x.lo < y.lo

func `==`(x, y: Stuint): bool =
  x.lo == y.lo

func `<=`(x, y: Stuint): bool =
  x.lo <= y.lo

proc div3n2n(r: var Stuint, b: Stuint) =
  var d: Stuint
  r = d
  r += b

func div2n1n(r: var Stuint, b: Stuint) =
  div3n2n(r, b)

func divmodBZ(x, y: Stuint, r: var Stuint)=
  div2n1n(r, y)
  r.lo = 3

func `mod`(x, y: Stuint): Stuint =
  divmodBZ(x, y, result)

func doublemod_internal(a, m: Stuint): Stuint =
  result = a
  if a >= m - a:
    result -= m
  result += a

func mulmod_internal(a, b, m: Stuint): Stuint =
  var (a, b) = (a, b)
  swap(a, b)
  debugEcho "x1 a: ", a
  a = doublemod_internal(a, m)
  debugEcho "x2 a: ", a
  a = doublemod_internal(a, m)
  debugEcho "x3 a: ", a

func powmod_internal(a, m: Stuint): Stuint =
  var a = a
  debugEcho "z1 m: ", m
  debugEcho "z2 a: ", a
  result = mulmod_internal(result, a, m)
  debugEcho "z3 a: ", a
  a = mulmod_internal(a, a, m)

func powmod*(a, m: Stuint) =
  discard powmod_internal(a mod m, m)

static:
  var x = Stuint(lo: high(uint64))
  var y = Stuint(lo: 12)

  powmod(x, y)
```

### Current Output
```
z1 m: (lo: 12)
z2 a: (lo: 3)
x1 a: (lo: 3)
x2 a: (lo: 6)
x3 a: (lo: 18446744073709551604) # -> corruption, should be 0
z3 a: (lo: 18446744073709551604) # -> mutation, should stay the same as z2
x1 a: (lo: 18446744073709551604)
x2 a: (lo: 18446744073709551568)
x3 a: (lo: 18446744073709551496)
```

### Expected Output
```
z1 m: (lo: 12)
z2 a: (lo: 3)
x1 a: (lo: 3)
x2 a: (lo: 6)
x3 a: (lo: 0)
z3 a: (lo: 3)
x1 a: (lo: 3)
x2 a: (lo: 6)
x3 a: (lo: 0)
```

### Additional Information

* It was working in version 0.19.6
* status-im/nim-stint#98

```
$ nim -v
Nim Compiler Version 1.0.2 [Windows: amd64]
Compiled at 2019-10-29
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: de5f6a07c239ccf5ca3d41d70350a37112025bcf
active boot switches: -d:release
```

### LINKED ISSUE #14553: GC crash in VM with tuple unpacking loop and table
The following code results in a compiler crash.

### Example
```nim
import tables, strutils

const PpcPatterns = @[("aaaa", "bbbb"), ("aaaaa", "bbbbb"), ("aaaaaa", "bbbbbb")]

static:
    var
        needSecondIdentifier = initTable[uint32, seq[(string, string)]]()

    for (name, pattern) in PpcPatterns:
        let
            firstPart = 0'u32
            lastPart = "test"

        needSecondIdentifier.mgetOrPut(firstPart, @[]).add((name, pattern))
```

### Current Output
with nim temp
```
Traceback (most recent call last)
C:\Nim\compiler\nim.nim(117) nim
C:\Nim\compiler\nim.nim(82) handleCmdLine
C:\Nim\compiler\cmdlinehelper.nim(84) loadConfigsAndRunMainCommand
C:\Nim\compiler\main.nim(252) mainCommand
C:\Nim\compiler\main.nim(217) compileToBackend
C:\Nim\compiler\main.nim(93) commandCompileToC
C:\Nim\compiler\modules.nim(143) compileProject
C:\Nim\compiler\modules.nim(84) compileModule
C:\Nim\compiler\passes.nim(210) processModule
C:\Nim\compiler\passes.nim(86) processTopLevelStmt
C:\Nim\compiler\sem.nim(604) myProcess
C:\Nim\compiler\sem.nim(572) semStmtAndGenerateGenerics
C:\Nim\compiler\semstmts.nim(2306) semStmt
C:\Nim\compiler\semexprs.nim(1014) semExprNoType
C:\Nim\compiler\semexprs.nim(2783) semExpr
C:\Nim\compiler\semstmts.nim(2246) semStmtList
C:\Nim\compiler\semexprs.nim(2835) semExpr
C:\Nim\compiler\semstmts.nim(2202) semStaticStmt
C:\Nim\compiler\vm.nim(2194) evalStaticStmt
C:\Nim\compiler\vm.nim(2183) evalConstExprAux
C:\Nim\compiler\vm.nim(773) rawExecute
C:\Nim\lib\system\gc.nim(239) asgnRef
C:\Nim\lib\system\gc.nim(184) incRef
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
It shouldn't crash.

### Additional Information

using commit https://github.com/nim-lang/Nim/commit/55f0df164befdf2304841c74daeaacc5391e08fd

### LINKED ISSUE #15974: regression(0.20.0 => devel): var params assignment gives silently wrong results in VM
regression(0.20.0 => devel): in VM, a copy of a var param is affected when that param is later re-assigned.

### Example
```nim
when true:
  type Foo = object
    f0: int

  proc fn(a: var Foo) =
    var s: Foo
    a = Foo(f0: 2)
    s = a
    doAssert s.f0 == 2
    a = Foo(f0: 3)
    echo s.f0

  proc main()=
    var a = Foo(f0: 1)
    fn(a)

  static: main()
  main()
```

### Current Output
CT:
3
RT:
2

### Expected Output
CT:
2
RT:
2

### Additional Information
regression:
* fails with: devel 1.5.1 c39fa0d49535da7f803d9972abdb15d09eed92a6, and 1.0.2
* works with: nim 0.20.0
* 1.0.0 gives: `nfIsRef in regs[ra].node.flags`  [AssertionError]
* likewise in other cases where you'd have a copy, eg: `var s: seq[Foo]` and `s.add a`
* root cause for https://github.com/flyx/NimYAML/issues/91 (nimyaml gives wrong results at CT), after a painful, painful reduction

## git bisect output
```
162d74db91412d98a4a67b28c1e1c9c1d79a9873 is the first bad commit
commit 162d74db91412d98a4a67b28c1e1c9c1d79a9873
Author: Andreas Rumpf <rumpf_a@web.de>
Date:   Thu Sep 19 14:34:56 2019 +0200

    fixes #10981; fixes #7261 (#12217)

 compiler/vmgen.nim    |  5 ++-
 tests/vm/tmisc_vm.nim | 99 +++++++++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 103 insertions(+), 1 deletion(-)
bisect run success
```
=> points to https://github.com/nim-lang/Nim/pull/12217 /cc @Araq

### LINKED ISSUE #16020: addr(object) doesn't work in VM
addr(object) doesn't work in VM

### Example
```nim
when true:
  type Foo = object
    f0: int
  proc main=
    var f = Foo(f0: 3)
    var f2 = f.addr
    f2[].f0 += 1
    f2.f0 += 1
    echo f
  static: main()
  main()
```

### Current Output
```
--
(f0: 3)
--
(f0: 5)
```

### Expected Output
```
--
(f0: 5)
--
(f0: 5)
```

### Additional Information
* devel 1.5.1 c39fa0d49535da7f803d9972abdb15d09eed92a6
* refs https://github.com/nim-lang/Nim/pull/16002#discussion_r525424113
* potential solution: add `nfIsRef` ?

### LINKED ISSUE #16613: Nim crashes randomly
**Steps to reproduce**:
```
git clone https://github.com/yglukhov/iface
cd iface
git checkout c137f9330cc0bb59b1c9204fecd2358b5c156f52
while nim c tests/test1.nim; do true; done
```
Wait for 5 minutes
**Actual result**:
Nim eventually crashes with stack trace:
```
Traceback (most recent call last)
.../nim-devel/compiler/nim.nim(128) nim
.../nim-devel/compiler/nim.nim(87) handleCmdLine
.../nim-devel/compiler/main.nim(275) mainCommand
.../nim-devel/compiler/main.nim(245) compileToBackend
.../nim-devel/compiler/main.nim(101) commandCompileToC
.../nim-devel/compiler/modules.nim(178) compileProject
.../nim-devel/compiler/modules.nim(98) compileModule
.../nim-devel/compiler/passes.nim(180) processModule
.../nim-devel/compiler/passes.nim(73) processTopLevelStmt
.../nim-devel/compiler/sem.nim(644) myProcess
.../nim-devel/compiler/sem.nim(612) semStmtAndGenerateGenerics
.../nim-devel/compiler/semstmts.nim(2335) semStmt
.../nim-devel/compiler/semexprs.nim(1055) semExprNoType
.../nim-devel/compiler/semexprs.nim(2970) semExpr
.../nim-devel/compiler/semstmts.nim(2277) semStmtList
.../nim-devel/compiler/semexprs.nim(2852) semExpr
.../nim-devel/compiler/semexprs.nim(1038) semDirectOp
.../nim-devel/compiler/semexprs.nim(921) afterCallActions
.../nim-devel/compiler/semexprs.nim(39) semTemplateExpr
.../nim-devel/compiler/sem.nim(421) semAfterMacroCall
.../nim-devel/compiler/semstmts.nim(2335) semStmt
.../nim-devel/compiler/semexprs.nim(1055) semExprNoType
.../nim-devel/compiler/semexprs.nim(2970) semExpr
.../nim-devel/compiler/semstmts.nim(2277) semStmtList
.../nim-devel/compiler/semexprs.nim(2969) semExpr
.../nim-devel/compiler/semexprs.nim(2552) semBlock
.../nim-devel/compiler/semexprs.nim(2970) semExpr
.../nim-devel/compiler/semstmts.nim(2277) semStmtList
.../nim-devel/compiler/semexprs.nim(2978) semExpr
.../nim-devel/compiler/semstmts.nim(204) semTry
.../nim-devel/compiler/semstmts.nim(109) semExprBranchScope
.../nim-devel/compiler/semstmts.nim(102) semExprBranch
.../nim-devel/compiler/semexprs.nim(2970) semExpr
.../nim-devel/compiler/semstmts.nim(2277) semStmtList
.../nim-devel/compiler/semexprs.nim(2970) semExpr
.../nim-devel/compiler/semstmts.nim(2277) semStmtList
.../nim-devel/compiler/semexprs.nim(2852) semExpr
.../nim-devel/compiler/semexprs.nim(1038) semDirectOp
.../nim-devel/compiler/semexprs.nim(921) afterCallActions
.../nim-devel/compiler/semexprs.nim(39) semTemplateExpr
.../nim-devel/compiler/sem.nim(421) semAfterMacroCall
.../nim-devel/compiler/semstmts.nim(2335) semStmt
.../nim-devel/compiler/semexprs.nim(1055) semExprNoType
.../nim-devel/compiler/semexprs.nim(2970) semExpr
.../nim-devel/compiler/semstmts.nim(2277) semStmtList
.../nim-devel/compiler/semexprs.nim(2948) semExpr
.../nim-devel/compiler/semstmts.nim(162) semIf
.../nim-devel/compiler/semstmts.nim(102) semExprBranch
.../nim-devel/compiler/semexprs.nim(2970) semExpr
.../nim-devel/compiler/semstmts.nim(2277) semStmtList
.../nim-devel/compiler/semexprs.nim(2978) semExpr
.../nim-devel/compiler/semstmts.nim(204) semTry
.../nim-devel/compiler/semstmts.nim(109) semExprBranchScope
.../nim-devel/compiler/semstmts.nim(102) semExprBranch
.../nim-devel/compiler/semexprs.nim(2970) semExpr
.../nim-devel/compiler/semstmts.nim(2277) semStmtList
.../nim-devel/compiler/semexprs.nim(2970) semExpr
.../nim-devel/compiler/semstmts.nim(2277) semStmtList
.../nim-devel/compiler/semexprs.nim(2974) semExpr
.../nim-devel/compiler/semstmts.nim(675) semConst
.../nim-devel/compiler/semexprs.nim(86) semExprWithType
.../nim-devel/compiler/semexprs.nim(70) semExprCheck
.../nim-devel/compiler/semexprs.nim(2857) semExpr
.../nim-devel/compiler/semexprs.nim(276) semConv
.../nim-devel/compiler/semexprs.nim(851) semStaticExpr
.../nim-devel/compiler/vm.nim(2220) evalStaticExpr
.../nim-devel/compiler/vm.nim(2212) evalConstExprAux
.../nim-devel/compiler/vm.nim(815) rawExecute
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
Nim version: bbe05c15326c7a62d15c0fe47d1c6e1be3ab11a8

### LINKED ISSUE #16780: object copy broken in vm
I found this issue while investigating ways to fix swap double evaluation bug in vm https://github.com/nim-lang/Nim/issues/16779; this runs into the following issue, that object copy seems broken in vm

### Example
```nim
when true:
  template swap*[T](a, b: var T) =
    var a2 = addr(a)
    var b2 = addr(b)
    var aOld = a2[]
    a2[] = b2[]
    b2[] = aOld

  proc main =
    block:
      var a = 1
      var b = 2
      swap(a, b)
      echo (a,b)

    block:
      type Foo = ref object
        x: int
      var a = Foo(x:1)
      var b = Foo(x:2)
      swap(a, b)
      echo (a.x, b.x)

    block:
      type Foo = object
        x: int
      var a = Foo(x:1)
      var b = Foo(x:2)
      swap(a, b)
      echo (a.x,b.x)

  static: main()
  main()
```

### Current Output
nim r main:
vm:
(2, 1)
(2, 1)
(1, 2)
rt:
(2, 1)
(2, 1)
(2, 1)

nim r -b:js main:
ditto

### Expected Output
nim r main:
vm:
(2, 1)
(2, 1)
(2, 1)
rt:
(2, 1)
(2, 1)
(2, 1)

nim r -b:js main:
ditto

### Additional Information
* 1.5.1 2b5841cd2b096624987d7cd1aa217088447076b7
* note that this issue isn't a stdlib issue nor an issue with swap, it's an issue with VM

### LINKED ISSUE #18641: `addr` doesn't work inside static at proc scope
### Example
```nim
when true:
  type A = object
    ha1: int
  static:
    var a = A()
    var a2 = a.addr
    a2.ha1 = 11
    doAssert a2.ha1 == 11
    a.ha1 = 12
    doAssert a.ha1 == 12
    doAssert a2.ha1 == 12 # ok
  static:
    proc fn() =
      var a = A()
      var a2 = a.addr
      a2.ha1 = 11
      doAssert a2.ha1 == 11
      a.ha1 = 12
      doAssert a.ha1 == 12
      doAssert a2.ha1 == 12 # fails
    fn()
```

### Current Output
the 2nd `a2.ha1 == 12` (inside fn) fails 
t12680.nim(24, 16) `a2.ha1 == 12`  [AssertionDefect]

### Expected Output
works

### Additional Information
1.5.1 6b3c77e7f4421267c551b1cd84717a19c65be2c5

### LINKED ISSUE #19464: [VM] Immutable proc argument is incorrectly modified
### Example
```nim
type
  Wrapper = object
    inner: int

proc assign(r: var Wrapper, a: Wrapper) =
  r = a

proc myEcho(a: Wrapper) =
  var tmp = a
  assign(tmp, Wrapper(inner: 0)) # this shouldn't modify `a`
  echo a

static:
  var result: Wrapper
  assign(result, Wrapper(inner: 1))
  myEcho(result)
```

### Current Output
```
(inner: 0)
```

### Expected Output
```
(inner: 1)
```

### Additional Information
The problem seems to be that `myEcho` directly modifies `a`, instead of just the `tmp` copy.

This doesn't occur if
* the code isn't run at compile time
* no wrapper type is used
* normal assignment is used instead of `assign`

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-01-27
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 4b723c0f5350c5bfb9722dace7a40c66a4630a68
active boot switches: -d:release
```

(This example may seem contrived, but that's because I tried to reduce it as much as possible. I originally encountered this bug while adding debug `echo`s in [nim-lang/bigints](https://github.com/nim-lang/bigints).)

### LINKED ISSUE #19909: addressing ref objects and comparing the pointer address in vm give FieldDefect
```nim
type
  SinglyLinkedList[T] = ref object

proc addMoved[T](a, b: var SinglyLinkedList[T]) =
  if a.addr != b.addr: discard

proc main =
  var a: SinglyLinkedList[int]; new a
  var b: SinglyLinkedList[int]; new b
  a.addMoved b

static: main()
```
gives
```
field 'node' is not accessible for type 'TFullReg' using 'kind = rkRegisterAddr' [FieldDefect]
```

Nim version: 1.6.6/devel

I found the issue while working on https://github.com/nim-lang/Nim/pull/19902

### PR DESCRIPTION
**Pull request by ringabout**
Reverts #12217 since the root problem seems to have been fixed; 
The tests (see tests/vm/tmisc_vm.nim) fixed by #12217 continues to work after reverting the pr.  

fixes #15974 regression(0.20.0 => devel): var params assignment gives silently wrong results in VM
fixes #12551 [regression] var param corruption and variable mutation when run the code with VM 
fixes #19464 [VM] Immutable proc argument is incorrectly modified
fixes #16020 addr(object) doesn't work in VM
fixes #16780 object copy broken in vm
fixes #16613 Nim crashes randomly
fixes #14553 GC crash in VM with tuple unpacking loop and table
fixes #19909 addressing ref objects and comparing the pointer address in vm give FieldDefect 
fixes #18641 addr doesn't work inside static at proc scope

### CODE REVIEW

File: compiler/vm.nim [hunk 1]
```diff
@@ -1028,9 +1027,9 @@ proc rawExecute(c: PCtx, start: int, tos: PStackFrame): TFullReg =
         if regs[rc].kind == rkNodeAddr:
           ret = regs[rb].nodeAddr == regs[rc].nodeAddr
         else:
-          ret = ptrEquality(regs[rb].nodeAddr, regs[rc].node)
+          ret = ptrEquality(regs[rb].nodeAddr, regs[rc].regToNode) # todo fixme
```
Comment (ringabout) [inline compiler/vm.nim]: I'm checking it...

**Comment by Araq** [comment]
Ping me again when it's ready.

File: compiler/vm.nim (hunk 1 above)
Comment (ringabout) [reply compiler/vm.nim]: It seems to be a pre-existing issue:

```nim
type
  SinglyLinkedList[T] = ref object

proc addMoved[T](a, b: var SinglyLinkedList[T]) =
  if a.addr != b.addr: discard

proc main =
  var a: SinglyLinkedList[int]; new a
  var b: SinglyLinkedList[int]; new b
  a.addMoved b

static: main()
```
gives the same error messages as objects(my PR - regToNode) => `field 'node' is not accessible for type 'TFullReg' using 'kind = rkRegisterAddr' [FieldDefect]` with 1.6.6 for ref objects.

My PR re-exposes the scar hidden for objects. I'm gonna to fix this pre-existing issue.

Comment (ringabout) [reply compiler/vm.nim]: => https://github.com/nim-lang/Nim/issues/19909

Comment (ringabout) [reply compiler/vm.nim]: fixed on the latest commit

**Comment by konsumlamm** [comment]
@narimiran could this be backported (preferrably 1.6 and 1.4)? This would allow to fix a bug in https://github.com/nim-lang/bigints for more than just devel (see https://github.com/nim-lang/bigints/issues/94).

**Comment by narimiran** [comment]
> @narimiran could this be backported (preferrably 1.6 and 1.4)?

It is already backported to the 1.6, which is our LTS, and it will be part of our next 1.6 release.

The 1.4 line is not really maintained anymore, i.e. don't expect any new releases.
