### PR TITLE
fix #17888: remove undefined behavior for posix.open; fix tempfiles.createTempFile

### LINKED ISSUE #710: `createTempFile` fails on linux with cgen error
### Example
```nim
import std/tempfiles
let (fda, patha) = createTempFile("", "")
```

### Current Output
seen in https://dev.azure.com/timotheecour/0c472305-f0f6-459d-aeab-b33734c4cb09/_apis/build/builds/3666/logs/72
```
2021-04-28T20:17:13.3476230Z CC: stdlib_tempfiles.nim
2021-04-28T20:17:13.4007854Z In file included from /usr/include/fcntl.h:289:0,
2021-04-28T20:17:13.4009355Z                  from /home/vsts/.cache/nim/testament_r/stdlib_tempfiles.nim.c:12:
2021-04-28T20:17:13.4010876Z In function ‘open’,
2021-04-28T20:17:13.4012305Z     inlined from ‘safeOpen_stdZtempfiles_7’ at /home/vsts/.cache/nim/testament_r/stdlib_tempfiles.nim.c:430:13:
2021-04-28T20:17:13.4016237Z /usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
2021-04-28T20:17:13.4017565Z     __open_missing_mode ();
2021-04-28T20:17:13.4018407Z     ^
2021-04-28T20:17:13.4137965Z In function ‘open’,
2021-04-28T20:17:13.4139158Z     inlined from ‘safeOpen_stdZtempfiles_7’ at /home/vsts/.cache/nim/testament_r/stdlib_tempfiles.nim.c:430:13,
2021-04-28T20:17:13.4140259Z     inlined from ‘createTempFile_stdZtempfiles_24’ at /home/vsts/.cache/nim/testament_r/stdlib_tempfiles.nim.c:585:25:
2021-04-28T20:17:13.4141733Z /usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
2021-04-28T20:17:13.4142543Z     __open_missing_mode ();
2021-04-28T20:17:13.4142862Z     ^
2021-04-28T20:17:13.4188632Z Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3 -O3 -fno-strict-aliasing -fno-ident   -I/home/vsts/work/1/s/lib -I/home/vsts/work/1/s/testament -o /home/vsts/.cache/nim/testament_r/stdlib_tempfiles.nim.c.o /home/vsts/.cache/nim/testament_r/stdlib_tempfiles.nim.c' failed with exit code: 1
2021-04-28T20:17:13.4192355Z 
```

### Expected Output
works

### Additional Information
1.5.1 486b1f621f2f4b3b02905db305d9a8d3985f06e4

### LINKED ISSUE #17888: serious bug with `posix.open`: it creates files with random permissions
### Example
```nim
when true:
  #[
  D20210428T190545
  ]#
  import std/[os,posix]
  proc main =
    let path = paramStr(1)
    let flags = posix.O_RDWR or posix.O_CREAT
    discard posix.open(path, flags)
  main()
```

### Current Output
```
XDG_CONFIG_HOME= nim c -o:/tmp/zbug -f main.nim
/tmp/zbug /tmp/z2
/tmp/zbug /tmp/z5asdfasdfasfasdfasdfasd
/tmp/zbug /tmp/zx23r2prijsdpfijadfassadf234r2

ls -l /tmp/z2
----------  1 timothee  wheel  0 Apr 28 19:05 /tmp/z2
ls -l /tmp/z5asdfasdfasfasdfasdfasd
------xr--  1 timothee  wheel  0 Apr 28 19:05 /tmp/z5asdfasdfasfasdfasdfasd
ls -l /tmp/zx23r2prijsdpfijadfassadf234r2
-rwxr--r-- 1 timothee 0 Apr 28 19:08 /tmp/zx23r2prijsdpfijadfassadf234r2
```

### Expected Output
the same permissions for each generated file

### Possible Solution
raise an error when `posix.open` is called without `mode_t` and the API requires it, as follows:
```nim
# in posix.nim:
proc open*(a1: cstring, a2: cint): cint {.varargs, importc, header: "<fcntl.h>", sideEffect.}
=>
proc openImpl(a1: cstring, a2: cint): cint {.varargs, importc: "open", header: "<fcntl.h>", sideEffect.}
proc open*(a1: cstring, a2: cint): cint =
  if a2 and O_CREAT != 0: raise newException(IOError, "O_CREAT requires mode_t param")
  else: result = openImpl(a1, a2)
proc open*(a1: cstring, a2: cint, mode: Mode): cint =
  openImpl(a1, a2, mode)
```

`man 2 open`
```
 int
     open(const char *path, int oflag, ...);
The oflag argument may indicate that the file is to be created if it does not exist (by specifying the O_CREAT flag).  In this case, open() and
     openat() require an additional argument mode_t mode; the file is created with mode mode as described in chmod(2) and modified by the process' umask
     value (see umask(2)).
```

### Additional Information
1.5.1 01bca8cd4fad857124794144bff09ae0326895bd
I'm on OSX, and this is likely OS-specific

I found this while noticing really weird behavior with `tempfiles.createTempFile`, in which code like this would randomly succeed or fail based on unrelated changes such as:
```
XDG_CONFIG_HOME= nim r -o:/tmp/z01 t12220.nim # ok
XDG_CONFIG_HOME= nim r -o:/tmp/z01asdfasfasfasdfasdfasfafds t12220.nim # IOError
```

```nim
when true: # D20210428T192102
  import std/[tempfiles,os]
  proc main()=
    let (fd, path) = createTempFile("", "")
    echo path
    writeFile(path, "foo\n") # this would succeed or fail
    close fd
    removeFile(path)
  main()
```

## note
* this is most likely related to https://github.com/timotheecour/Nim/issues/710 ; see also https://stackoverflow.com/a/25706405/1426932 ; it looks like on linux there are at least some safeguards in some cases:
> The linker error for __open_too_many_args just a way to fail the compilation/linking done by recent glibc headers by using gcc specific trickery to catch the case where you pass O_CREAT to open(), but fail to provide the 3. mode argument.

## note 2
according to https://man7.org/linux/man-pages/man2/openat.2.html, 
> The mode argument specifies the file mode bits to be
              applied when a new file is created.  If neither O_CREAT
              nor O_TMPFILE is specified in flags, then mode is ignored
              (and can thus be specified as 0, or simply omitted).  The
              mode argument must be supplied if O_CREAT or O_TMPFILE is
              specified in flags; if it is not supplied, some arbitrary
              bytes from the stack will be applied as the file mode.

so `O_TMPFILE` is also affected

### PR DESCRIPTION
**Pull request by timotheecour**
fix #17888
fix https://github.com/timotheecour/Nim/issues/710

### CODE REVIEW

File: lib/pure/streams.nim [hunk 1]
```diff
@@ -1503,6 +1503,7 @@ when false:
       of fmReadWrite: flags = O_RDWR or int(O_CREAT)
       of fmReadWriteExisting: flags = O_RDWR
       of fmAppend: flags = O_WRONLY or int(O_CREAT) or O_APPEND
+      static: doAssert false # handle bug #17888
```
Comment (timotheecour) [inline lib/pure/streams.nim:1506]: it's in a `when false` block so can be handled in future work if it needs revival

File: lib/std/tempfiles.nim [hunk 2]
```diff
@@ -93,17 +94,21 @@ proc createTempFile*(prefix, suffix: string, dir = ""): tuple[fd: File, path: st
...
   if dir.len == 0:
     dir = getTempDir()
 
   createDir(dir)
 
+  # xxx we need a `proc toMode(a: FilePermission): Mode`, possibly by
+  # exposing fusion/filepermissions.fromFilePermissions to stdlib; then we need
+  # to add a `perm` param so users can customize this (e.g. the temp file may
+  # need execute permissions).
+  let mode = Mode(S_IRUSR or S_IWUSR)
```
Comment (ringabout) [inline lib/std/tempfiles.nim]: move mode to the internal of `safeOpen` or use `when not defined(windows)`\
https://github.com/nim-lang/Nim/pull/17889/checks?check_run_id=2464253495

see CI failure

```
2021-04-29T07:01:41.8938561Z  (4, 5): 'pairs' [iterator declared in D:\a\Nim\Nim\lib\system\iterators.nim(166, 10)]
2021-04-29T07:01:41.8939384Z  (4, 5): 'pairs' [iterator declared in D:\a\Nim\Nim\lib\system\iterators.nim(185, 10)]
2021-04-29T07:01:41.8940212Z  (4, 5): 'pairs' [iterator declared in D:\a\Nim\Nim\lib\system\iterators.nim(204, 10)]
2021-04-29T07:01:41.8941013Z  (4, 5): 'repr' [proc declared in D:\a\Nim\Nim\lib\system.nim(1382, 8)]
2021-04-29T07:01:41.8941758Z  (4, 5): 'true' [enumField declared in D:\a\Nim\Nim\lib\system\basic_types.nim(16, 16)]
2021-04-29T07:01:41.8942637Z D:\a\Nim\Nim\lib\std\tempfiles.nim(107, 30) Error: undeclared identifier: 'S_IWUSR'
2021-04-29T07:01:41.8943509Z candidates (edit distance, scope distance); see '--spellSuggest': 
2021-04-29T07:01:41.8944343Z  (1, 4): 'S_IRUSR' [unknown declared in D:\a\Nim\Nim\lib\std\tempfiles.nim(107, 19)]
```

Comment (timotheecour) [reply lib/std/tempfiles.nim]: done; in future work we need to think how to expose `mode` (and `tempPathLength`) in a cross platform way

**Review by ringabout — APPROVED** [review]
