### PR TITLE
docgen: add Pandoc footnotes (fixes #21080)

### LINKED ISSUE #21080: Footnotes in documentation generation seem to be broken by default
### Description

Running `nim doc` to produce HTML documentation on something like

```
## Given a small[#]_ prime number ...
##
## .. [#] 16 or less unsigned bits
```

errors out with

```
Error: unhandled exception: number of footnotes and their references don't match: 1 (lines 7) != 0 (lines ) for auto-numbered footnotes [ERecoverableError]
```

Similarly,

```
## Here's another[#foo]_
##
## .. [#foo] footnote2
```

gives a "broken link" warning, footnote is a regular link pointing to nothing; it was (likely) incorrectly interpreted as a Markdown link? Same goes for `[1]_` etc.

I didn't analyze deeply but the problem seems to be caused by `roSupportMarkdown` (default) getting priority and interpreting either case as a pandoc implicit header ref Markdown link.

Here: https://github.com/nim-lang/Nim/blob/6505bd347df557713061d4e84cf9548d104622d9/lib/packages/docutils/rst.nim#L1714 and here: https://github.com/nim-lang/Nim/blob/6505bd347df557713061d4e84cf9548d104622d9/lib/packages/docutils/rst.nim#L1590

**WORKAROUND**: there's a `doctype` pragma to turn off the `roSupportMarkdown` default, but it seems rather obscure as I had to look at the compiler code to even know about it; it should probably be mentioned on https://nim-lang.org/docs/docgen.html ? I'm not sure what the purpose is of making this weird rST+Markdown amalgam the default.

However, I still contend something is wrong as currently there seems to be no way to actually use the footnote functionality by default (or I am dumb), nor does the `markdown` doctype seem to support pandoc style footnotes.

### Nim Version

Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-10-27
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 3469f37a56c31623eff473c65fd231bb5a77d5d8
active boot switches: -d:release

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by a-mr**
This implements Pandoc Markdown-style footnotes,
that are compatible with Pandoc referencing syntax:

    Ref. [^ftn].

    [^ftn]: Block.

See https://pandoc.org/MANUAL.html#footnotes for more examples.

### CODE REVIEW

File: lib/packages/docutils/rst.nim [hunk 1]
```diff
@@ -1960,8 +2009,26 @@ proc getMdBlockIndent(p: RstParser): int =
     else:
       result = nextIndent                 # allow parsing next lines [case.3]
 
-template isRst(p: RstParser): bool = roPreferMarkdown notin p.s.options
-template isMd(p: RstParser): bool = roPreferMarkdown in p.s.options
+proc indFollows(p: RstParser): bool =
```
Comment (a-mr) [inline lib/packages/docutils/rst.nim:2012]: This block is just moved from below.

File: lib/packages/docutils/rst.nim [hunk 2]
```diff
@@ -3022,6 +3091,57 @@ proc parseEnumList(p: var RstParser): PRstNode =
...
+  of fnAutoSymbol: result = "footnotesym-"
+  of fnCitation: result = "citation-"
+
+proc parseFootnote(p: var RstParser): PRstNode {.gcsafe.} =
+  ## Parses footnotes and citations, always returns 2 sons:
+  ##
+  ## 1) footnote label, always containing rnInner with 1 or more sons
+  ## 2) footnote body, which may be nil
+  var label: PRstNode
+  if isRst(p):
```
Comment (a-mr) [inline lib/packages/docutils/rst.nim:3108]: This block is also just moved to avoid forward declarations, except these few lines, that are actually changed.

**Comment by Araq** [comment]
Why do we need these? Defacto standard in markdown land?

**Comment by Varriount** [comment]
> Why do we need these? Defacto standard in markdown land?

In a sense. Markdown doesn't have any concept of "footnotes", so creating them is tedious.

I would suggest implementing GitHub's [Link Reference Definitions](https://github.github.com/gfm/#link-reference-definitions) instead though. The syntax is nearly the same, and the carrot character won't be required.

**Comment by a-mr** [comment]
> Why do we need these? Defacto standard in markdown land?

Pandoc Markdown? Not really. But it's the only Markdown dialect that strives to be a really universal document markup language, not some domain-specific stopgap, and it's the only dialect on par with RST regarding features.

I did not make my mind whether we need to aim for thorough compatibility with Pandoc. But this particular extension is good because:
1. It's also supported in other Markdown dialects, like [Github Markdown](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/) now [^1], in [Python Markdown](https://python-markdown.github.io/extensions/footnotes/), in [Myst](https://mystmd.org/spec/footnotes), ...
2. If we consider the RST feature as alternative, then its syntax is bad in this case ``[1]_`` — because it uses underscores, and in Markdown underscore is a synonym for emphasis (almost the same as `*`), and using such a thing e.g. breaks syntax highlighting in existing Markdown mode in editors

[^1]: I mean it
