### PR TITLE
VM fix for nil assignment

### LINKED ISSUE #6081: Deque pop return nil nodes when used with NimNodes
Was playing around with parsing ASTs for my macro and got some strange bugs. Traced them back to the deque module not returning the proper output on pop operations. Minimal example:

```
import macros, deques

macro testBug(stmt: untyped): untyped=
  echo "-------------- INPUT-----------------"
  echo stmt.treeRepr
  var deque = initDeque[NimNode]()
  echo "--------------- BUG -----------------"
  ## This doesn't work
  for child in 0..<stmt.len:
    deque.addFirst stmt[child]
  for child in 0..<stmt.len:
    echo deque.popFirst().kind

  echo "--------------- OK ------------------"
  ## This does
  for child in 0..<stmt.len:
    deque.addFirst stmt[child]
  for child in 0..<stmt.len:
    echo deque.peekFirst().kind
    discard deque.popFirst()

testBug:
  These
  are
  some
  test
  nodes
```

Outputs:

```
-------------- INPUT-----------------
StmtList
  Ident !"These"
  Ident !"are"
  Ident !"some"
  Ident !"test"
  Ident !"nodes"
--------------- BUG -----------------
nnkNilLit
nnkNilLit
nnkNilLit
nnkNilLit
nnkNilLit
--------------- OK ------------------
nnkIdent
nnkIdent
nnkIdent
nnkIdent
nnkIdent
```

As you can see the popFirst procedure just returns NilLit nodes, but the peekFirst procedure works fine.

### PR DESCRIPTION
**Pull request by GULPF**
Changes with motivations:
- Don't use `putIntoNode` to implement `opcWrDeref`. `putIntoNode` was used for to many things, which made it hard to make it correct for all cases. This change also means that `putIntoNode` doesn't need to handle a bunch of edge cases that are only relevant to `opcWrDefef`.
- Rename `putIntoNode` to `writeField`. This change reflects that the proc is now only used in `opcWrObj`/`opcWrArr`, and it probably shouldn't be used anywhere else.
- Don't allow dereferencing `nil` (see test case in `tests/vm/tnilref.nim`).
- Add `nfIsRef` flag to `sym` nodes (generated by `opcNBindSym` and `opcGenSym`).

Fixes #6081

### CODE REVIEW

**Comment by GULPF** [comment]
The test failure looks really painful and this doesn't properly fix the VM's handling of ref types anyway, so this PR might not be worth it.

@Araq What's your thoughts on supporting `ptr`/`ref` better in the VM? I don't think it's possible to represent multiple layers of `ptr`/`ref` with the current register design, and bugs like the one this PR tries to solve might be easier to deal with if the design was different.

Instead of this (current design):
```nim
  TRegisterKind = enum
    rkNone, rkNode, rkInt, rkFloat, rkRegisterAddr, rkNodeAddr

  TFullReg = object 
    case kind: TRegisterKind
    of rkNone: nil
    of rkInt: intVal: BiggestInt
    of rkFloat: floatVal: BiggestFloat
    of rkNode: node: PNode
    of rkRegisterAddr: regAddr: ptr TFullReg
    of rkNodeAddr: nodeAddr: ptr PNode
```

I would propose this (note the use of `TNode` instead of `PNode`):
```nim
  RegValueKind = enum
    rkNone, rkNode, rkInt, rkFloat, rkPtr, rkRef

  RegValue = object 
    case kind: RegValueKind
    of rkNone: nil
    of rkInt: intVal: BiggestInt
    of rkFloat: floatVal: BiggestFloat
    of rkNode: node: TNode
    of rkPtr: ptrVal: ptr RegValue
    of rkRef: refVal: ref RegValue
```

Is there anything obviously wrong with this? I will probably get stuck somewhere anyway, but I don't want to spend time on it if it's a terrible idea.

**Comment by Araq** [comment]
> Is there anything obviously wrong with this? I will probably get stuck somewhere anyway, but I don't want to spend time on it if it's a terrible idea.

It is interesting and might work. If it doesn't work, please report back here why it doesn't. :-)

**Comment by GULPF** [comment]
Tried a different approach that I think will be easier to maintain, and fixes some more ref related issues.

One issue is that the vmgen doesn't generate any instruction for global derefences:
```nim
var i: int
var r: ref int
# These two both generate the intructions `LdGlobalAddr`, `LdImInt`, `WrDeref`
# meaning that the actual deref isn't generated.
i = 1
r[] = 1 
```
`WrDeref` currently has an ugly workaround for this, but it should be fixed in vmgen.

> Shouldn't the vmgen produce a `nkNilLit` with this `nfIsRef` flag instead?

I don't think so. `nkNilLit` with `nfIsRef` should represent an allocated ref that points to `nil`, while a `nkNilLit` without `nfIsRef` should represent an unallocated ref.

File: compiler/vm.nim [hunk 1]
```diff
@@ -204,22 +204,14 @@ proc asgnComplex(x: var TFullReg, y: TFullReg) =
...
-      n = x.node
-    else:
-      let destIsRef = nfIsRef in n.flags    
-      n[] = x.node[]
-      # Ref-ness must be kept for the destination
-      if destIsRef:
-        n.flags.incl nfIsRef
-  of rkRegisterAddr: putIntoNode(n, x.regAddr[])
-  of rkNodeAddr: n[] = x.nodeAddr[][]
+  of rkNode: n = copyValue(x.node)
```
Comment (GULPF) [inline compiler/vm.nim]: The VM didn't copy the node here before, but I think it makes some amount of sense. This code fails without it:
```nim
block:
  type Obj = object
    field: int
  var s = newSeq[Obj](1)
  var o = Obj()
  s[0] = o
  o.field = 2
  doAssert s[0].field == 0
```
However, this copy is not needed in many cases, because `vmgen` already generates a copy instruction when needed (I think? Apparently not for globals). Would it be preferable to solve the issue in vmgen instead?

Comment (Araq) [reply compiler/vm.nim]: In general, pushing the logic from ``vm.nim`` into ``vmgen.nim`` is always worth it.

Comment (GULPF) [reply compiler/vm.nim]: OK, I'll remove the copy call and add the test case as an issue for now

**Comment by GULPF** [comment]
Finally managed to make the tests pass, so this is ready for review. I've updated the PR description with an up to date description of the changes.

**Comment by GULPF** [comment]
The VM definitely needs more tests, but `lexim` looks very broken on devel (lots of breaking changes in the last 3 years...) so it's not trivial to extract a test case from it.

**Comment by Araq** [comment]
I'm working on it... :-)
