### PR TITLE
fix #8242, fix #12586: fix 'formatFloat' with 'precision = 0'

### LINKED ISSUE #8242: strutils:formatBiggestFloat() gives different results in JS mode
Test case in [strutils.nim](https://github.com/nim-lang/Nim/blob/8667899d531225e060db3effe72627b9609017ce/lib/pure/strutils.nim#L2392).

```nim
echo formatBiggestFloat(1234.567, ffDecimal, 0, '.')
```

Prints "1235." in C/C++ mode but prints "1235" without the "." in JS mode. Wasn't getting caught all this time since testament wasn't running all test cases. See #8231 and #8232.

### LINKED ISSUE #12586: Trailing dot is returned for formatFloat with precision 0
`strututils.formatFloat` returns a trailing dot when using `precision = 0`.

### Example
```nim
import strutils
echo formatFloat(2.123, ffDecimal, precision = 0)
```

### Current Output
```
2.
```

### Expected Output
```
2
```
### Additional Information
With the JS backend the expected result is returned. Tested with latest devel.

### PR DESCRIPTION
**Pull request by narimiran**
`formatFloat` with `precision = 0` now gives the same result (a number without a decimal point) in all backends.
This is compatible with Python's formatters, too.

----

Before you ask: I've removed tests for `wordWrap` as this proc is deprecated, and those tests are now in `std/wordwrap` library.

### CODE REVIEW

File: lib/pure/strutils.nim [hunk 1]
```diff
@@ -2369,6 +2369,10 @@ proc formatBiggestFloat*(f: BiggestFloat, format: FloatFormatMode = ffDefault,
       # but nothing else is possible:
       if buf[i] in {'.', ','}: result[i] = decimalSep
       else: result[i] = buf[i]
+      if result[^1] == decimalSep:
```
Comment (Araq) [inline lib/pure/strutils.nim]:
```nim

when (NimMajor, NimMinor) >= (1, 1):
  if ...
```

Comment (narimiran) [reply lib/pure/strutils.nim]: 1. This would be then needed for every changed test too.
2. If this won't be backported (and it shouldn't be, IMO), does this switch do anything useful? (That part of the code will only exist in Nim versions >= 1.1)

Comment (Araq) [reply lib/pure/strutils.nim]: The tests are fine the way they are. This switch does *emulate* 1.0.x, so IMO we should strive to make it work.

Comment (narimiran) [reply lib/pure/strutils.nim]: Done.
