### PR TITLE
fix #13491 #17279 runnableExamples now don't get lost in translation

### LINKED ISSUE #13491: runnableExamples transforms `do: => :` and `(expr) => expr`, producing invalid code
runnableExamples code transformation produces invalid code from valid code

### Example 1
```nim
proc fun*(): int = doAssert false
proc main*()=
  runnableExamples:
    doAssertRaises(AssertionError, (discard fun())) # BUG
doAssertRaises(AssertionError, (discard fun())) # ok
```

### Current Output
```
/Users/timothee/git_clone/nim/timn/build/nimcache/runnableExamples/t10250_examples.nim(1, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/build/nimcache/runnableExamples/t10250_examples1.nim(7, 3) Error: expression expected, but found 'keyword discard'
    discard fun())
    ^
```

### Expected Output
works

### Additional Information

* devel 3dad130034e3212159dda5d61988ca2b18959b24 1.1.1

code transform:
```nim
import
  "/Users/timothee/git_clone/nim/timn/tests/nim/all/t10250.nim"

doAssertRaises(AssertionError,
  discard fun())
```
expected transform:
```nim
...

doAssertRaises(AssertionError,
  (discard fun()))
# or:
doAssertRaises(AssertionError, (discard fun()))
```

* workaround:
`doAssertRaises(AssertionError): discard fun()`
but that's just for this particular example; the bug remains

### Example 2
see https://github.com/nim-lang/Nim/issues/13491#issuecomment-731519848

## [EDIT] potential solution
use same technique as in https://github.com/nim-lang/Nim/pull/14439

### LINKED ISSUE #17279: runnableExamples gives wrong values for number literals
### Example
```nim
echo "ok0"
echo 0xffffffffffffffff
runnableExamples:
  echo "ok1"
  echo 0xffffffffffffffff
```

### Current Output
nim doc main
ok0
-1
ok1
4294967295

### Expected Output
ok0
-1
ok1
-1

### Additional Information
* 1.5.1 f28dc2c61ed2ee4452441c1a5508cb1e46a8f288
* originally reported to me by @xflywind 
* the problem stems from fact that the generated file contains:
/Users/timothee/git_clone/nim/timn/build/nimcache/runnableExamples/t11969_examples1.nim
```
echo "ok1"
echo 0xFFFFFFFF
```

* related but different: https://github.com/nim-lang/Nim/issues/13491
* probably different: https://github.com/nim-lang/Nim/issues/17208

### PR DESCRIPTION
**Pull request by timotheecour**
* fix https://github.com/nim-lang/Nim/issues/17279
* fix https://github.com/nim-lang/Nim/issues/13491

This PR fixes all such issues with runnableExamples by avoiding the bugs of `renderModule`, but underlying problem in `renderModule` (and repr) remains and will need to be fixed; at least it won't affect runnableExamples anymore; these are tracked in https://github.com/nim-lang/Nim/issues/17292.

## future work
- [ ] remove `useRenderModule` dead code
- [ ] remove renderModule or add a test

### CODE REVIEW

File: compiler/docgen.nim [hunk 1]
```diff
@@ -508,19 +498,48 @@ proc prepareExample(d: PDoc; n: PNode): tuple[rdoccmd: string, code: string] =
     if n1.kind notin nkStrKinds: globalError(d.conf, n1.info, "string litteral expected")
     rdoccmd = n1.strVal
 
-  var docComment = newTree(nkCommentStmt)
+  let useRenderModule = false
```
Comment (Araq) [inline compiler/docgen.nim:501]: So ... there is a bunch of dead code here regarding `useRenderModule`. Why?

Comment (timotheecour) [reply compiler/docgen.nim:501]: this would snowball into making `renderModule` itself deadcode, which opens another can of worms.
How about i defer to another PR removing this deadcode, and decide there whether to also remove `renderModule` or add some test for it?

Comment (Araq) [reply compiler/docgen.nim:501]: Sure, ok.
