### PR TITLE
`nim doc --backend:js`, `nim doc --doccmd:-d:foo`, `nim r --backend:js`, `--doccmd:skip` + other improvements

### LINKED ISSUE #13129: Allow specifying/forcing the compilation backend in Nim for `nim doc`
### Summary

Allow forcing the compilation backend that get enforced on the usual library compilations and also the code block evaluations done by `nim doc` invocations.

### Description

Certain Nim libraries cannot be compiled in _any_ backend the user wants.

A very good example is a wrapper Nim library for a backend-specific library.. e.g. a Nim wrapper for C++ `std::vector`. For such Nim libraries one can force the user to always compile using the `cpp` backend using something like:

```nim
when not defined(cpp):
  {.error: "This library needs to be compiled with the cpp backend.".}
```

But there is not way to force the `cpp` backend when running the `nim doc` command on that library.

For example, this will always fail right now if I run `nim doc` on it.. because `nim doc` is always using the `c` backend to evaluate the code blocks in doc strings:

```nim
when not defined(cpp):
  {.error: "This library needs to be compiled with the cpp backend.".}

{.push header: "<vector>".}

type
  Vector*[T] {.importcpp: "std::vector".} = object

proc newVector*[T](): Vector[T] {.importcpp: "std::vector<'*0>()", constructor.}

# https://en.cppreference.com/w/cpp/container/vector/size
proc size*(v: Vector): int {.importcpp: "#.size()".}
  ## Return the number of elements in the Vector.
  ##
  ## .. code-block::
  ##    :test:
  ##    var
  ##      v = newVector[int]()
  ##    doAssert v.size() == 0
  ##
  ##    v.add(100)
  ##    v.add(200)
  ##    doAssert v.len() == 2

{.pop.}
```

### Failed attempts

I tried putting this in the project's `config.nims`, but the `nim doc` still uses the `c` backend:

```nim
if getCommand() == "c":
  setCommand("cpp")
```

### Suggestion

Make the above NimScript code affect the `nim doc` command too.

### Additional Information
- I was trying to improve my `std::vector` Nim wrapper library [**std_vector**][1], but stumbled upon this limitation where `nim doc` always uses the `c` backend.
- Slightly related issue: https://github.com/nim-lang/Nim/issues/6201
- https://forum.nim-lang.org/t/3089

[1]: https://github.com/kaushalmodi/std_vector

### LINKED ISSUE #13891: importjs+nim doc,Error:importjs pragma requires JavaScript target
# Examples

```console
$ cat example.nim
func consolog*() {.importjs: "console.log(#)".} =
  ## Documentation

$ nim doc example.nim
example.nim(1, 28) Error: `importjs` pragma requires the JavaScript target

$
```

# Current Output

```nim
example.nim(1, 28) Error: `importjs` pragma requires the JavaScript target
```

# Additional Information

- `{.importcpp.}` works without error.
- Documentation may still generate (?).
- **Doc Test exit non-zero.**

# System Information

<details>

```json

{
  "compiled": "2020-04-04T03:24:50",
  "NimVersion": "1.2.0",
  "hostCPU": "amd64",
  "hostOS": "linux",
  "cpuEndian": "littleEndian",
  "getTempDir": "/tmp/",
  "now": "2020-04-06T02:46:00-03:00",
  "getCurrentEncoding": "UTF-8",
  "getFreeMem": 385024,
  "getTotalMem": 528384,
  "getOccupiedMem": 92592,
  "countProcessors": 6,
  "arch": "x86_64",
  "FileSystemCaseSensitive": true,
  "nimcacheDir": "",
  "ccompilerPath": "",
  "currentCompilerExe": "/home/juan/.choosenim/toolchains/nim-1.2.0/bin/nim",
  "nimpretty": "0.2",
  "nimble": "nimble v0.11.0 compiled at 2020-04-05 13:45:51\ngit hash: couldn't determine git hash",
  "nimgrep": "1.5",
  "nimsuggest": "Nim Compiler Version 1.3.1 [Linux: amd64]\nCompiled at 2020-04-05\nCopyright (c) 2006-2020 by Andreas Rumpf\n\nactive boot switches: -d:release -d:danger --gc:markAndSweep",
  "choosenim": "choosenim v0.6.0 (2020-03-06 18:24:57) [linux/amd64]",
  "gcc": "gcc (Arch Linux 9.3.0-1) 9.3.0",
  "clang": "clang version 9.0.1",
  "git": "2.25.1",
  "node": "v13.12.0",
  "python": "3.8.1",
  "ssd": true
}
```

</details>

### PR DESCRIPTION
**Pull request by timotheecour**
flags introduced here are by design orthogonal so that they work as you'd expect when you combine them.

## `nim --backend:js|c|cpp|objc` (or -b:js etc)
* fix https://github.com/nim-lang/Nim/issues/13891 (importjs+nim doc,Error:importjs pragma requires JavaScript target)
* fix https://github.com/nim-lang/Nim/issues/13129 (Allow specifying/forcing the compilation backend in Nim for `nim doc)
* we now decouple backends from commands. Everything that worked before still works now, but we can now run things like `nim doc --backend:js` to generate js specific docs. This opens door to showing docs specific to different backends, which would be more accurate than what we have now (often wrong since it assumes c target for nim js in system.nim for example)
* `--backend` is then passed on to runnableExamples, which run the examples for the same backend backend by default. (`--doccmd:--backend:cpp` would be able to override it should user want that, see below)
* before this PR, there was no easy way to change the backend in a cmdline invocation (unless you used a separate nimscript file + setCommand); now you can simply do it by appending `--backend:js` to the command right before the $file argument, eg: `nim c -b:cpp $file` => will use cpp backend

## nim r -b:js (etc)
* likewise, `nim r` (introduced in https://github.com/nim-lang/Nim/pull/13382 just for `c` backend) now works with other backends, eg: `nim r -b:js main`
* `nim r` should now be the de facto default to run tests, regardless of backend, since it avoids polluting your sources with generated js or binaries

## `nim doc --doccmd:cmd`
* before PR, there was no way to pass options to runnableExamples command; now there is, eg: `nim doc --doccmd:'-d:foo --threads:on --lib:lib' main`
; this fixes https://github.com/nim-lang/Nim/issues/13129#issuecomment-582796434

## `nim doc --doccmd:skip`, `nim rst2html --doccmd:skip`
* before PR there was no way to skip runnableExamples or (in rst) test snippets ; now you simply pass `--doccmd:skip`; very useful when you just want to see how the generated html file looks like without waiting for all the runnableExamples to run (or snippets to compile), during development.
eg:
* `nim rst2html --outdir:doc/html doc/manual.rst` => 50s
* `nim rst2html --outdir:doc/html --doccmd:skip doc/manual.rst` => 0.9s

## `--usenimcache`
* refs https://github.com/nim-lang/Nim/issues/6583 ; now you can use `--usenimcache` and avoid polluting both $pwd and $projectdir
* `--usenimcache` was implicitly introduced in https://github.com/nim-lang/Nim/pull/13382 just for `nim r`; now it's explicitly a flag decoupled from `nim r` and works in combination with other commands, eg: `nim doc --usenimcache`  => will output html under nimcache
`--usenimcache` by design uses whatever nimcache resolves to after each command was processed, eg:
`nim doc --nimcache:foo --usenimcache --nimcache:bar main` => will output html uner `bar`, not `foo`
* it works with any command, eg: `nim c --usenimcache main` or `nim doc --usenimcache`

## note: setting `-d:js` (etc) manually is bad, hence the need for `--backend:js`
Note that simply setting `-d:js` is naive and won't work in many cases (eg importjs etc; or may end up with both defined(c) and defined(js) etc), likewise with -d:cpp; in fact future PR should probably issue warning when user code sets -d:js (+other backends) as it'd be error prone.

## tests
* tests are added for every feature

## potential future directions
* make `--usenimcache` default for `nim doc` ; IMO that's the best resolution for https://github.com/nim-lang/Nim/issues/6583; any -o or --outdir would override --usenimcache anyway 
* `nim r doc --port:1234 main` will save the html under nimcache (because `-r` implies `--usenimcache`), and setup (on 1st call) a livereload server (see https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en) so that the html opens in the same tab and auto-refreshes
* `nim r -b:js --port:1234 (-d:nimbrowser) main` will create a template html file that simply links against the generated js file so you can see it running in a browser, it will also use the livereload server to auto-refresh the same tab; this avoids setting up a server manually just to see how `nim js` code runs in a browser

### CODE REVIEW

**Comment by kaushalmodi** [comment]
@timotheecour Thank you! for working on this. I started looking into implementing it but didn't have time to dig further on how to add switches that affected "nim doc" and not the regular "nim".

File: lib/pure/strutils.nim [hunk 1]
```diff
@@ -2699,6 +2697,8 @@ proc addf*(s: var string, formatstr: string, a: varargs[string, `$`]) {.
   var i = 0
   var num = 0
   while i < len(formatstr):
+    template invalidFormatString() =
+      raise newException(ValueError, "invalid format string: i: " & $i & "\nprefix:\n" & formatstr[0..<i] & "\nsuffix:\n" & formatstr[i..^1])
```
Comment (Araq) [inline lib/pure/strutils.nim]: The ``.noinline`` proc produces better code.

**Comment by Araq** [comment]
It's excellent work but some tests seem to be red and it's not the usual flaky tests.

File: lib/pure/strutils.nim (hunk 1 above)
Comment (timotheecour) [reply lib/pure/strutils.nim]: good point; I'm moving this change to another PR and will fix that

**Comment by timotheecour** [comment]
@araq PTAL
> some tests seem to be red and it's not the usual flaky tests

fixed it, was a 1 liner fix

* --doccmd:skip now allows `nim rst2html --outdir:doc/html --doccmd:skip doc/manual.rst` to be 50x faster
* I don't understand need for  `keep binary compatible` in `TCommands`, I'm tempted to just remove the newly deadcode enum members
* `--usenimcache` should be default for nim doc IMO, which would fix #6583 2nd regression, but that shd be in another PR


~~CI failures unrelated~~ EDIT: all green now
* https://github.com/timotheecour/Nim/issues/113#issuecomment-625013451 (this i saw 2 days ago from another unrelated PR so unrelated to this PR)
* https://github.com/timotheecour/Nim/issues/113#issuecomment-625584083 (nimx; same root cause as I described here https://github.com/nim-lang/Nim/pull/13868#issuecomment-618890814)

**Comment by alaviss** [comment]
Can we have this for nimsuggest too? :D

**Comment by timotheecour** [comment]
> Can we have this for nimsuggest too? :D

IMO it's best as a separate PR, this PR is big enough already; my guess is this should be a simple followup, eg:
nimsuggest uses `conf.cmd = cmdIdeTools`; in future PR it can learn `--backend` and it should all just work

* likewise with `nim check` and other commands; EDIT: these should work reliably as of https://github.com/nim-lang/Nim/pull/14363

File: doc/advopt.txt [hunk 2]
```diff
@@ -29,6 +30,8 @@ Runtime checks (see -x):
 Advanced options:
   -o:FILE, --out:FILE       set the output filename
   --outdir:DIR              set the path where the output file will be written
+  --usenimcache             will use `outdir=$$nimcache`, whichever it resolves
```
Comment (Araq) [inline doc/advopt.txt:33]: I don't understand the point of ``--usenimcache``.

Comment (timotheecour) [reply doc/advopt.txt:33]: `--usenimcache` is what's implied by `nim r`, and avoids clobbering your sources with generated files (exe, js, html), or having to deal with gitignore.

It's useful for other commands apart from `nim r`, as it allows specifying to output to nimcache without having to guess and repeat what nimcache will resolve to, eg:
```
nim doc -r --usenimcache main # outputs to $nimcache/main.html
nim doc --usenimcache main # also useful without -r; the hintSuccessX tells you where it lands
nim js --usenimcache main # ditto
```

so if I have `~/.config/nim/config.nims` that contains `--nimcache:/tmp/nimcache`, it'll output to /tmp/nimcache/main.js; without it, i'd need to pass `--outdir:/tmp/nimcache` to achieve same effect.
Since nimcache can be determined by several config files, guessing what nimcache resolves to ahead of time is not desirable.

## future: `--usenimcache:usehash` (EDIT: see https://github.com/timotheecour/Nim/issues/199)
In future work, I want to allow the same as what `rdmd` does: store the generated outputs under a dir named after a hash of all options (quite simple to implement on top of what's already implemented in `changeDetectedViaJsonBuildInstructions`, eg `$nimcache/h-$hash/{foo.json,foo}`

## example
```
rdmd -O t10721.d # recompiles (1st time with these options)
rdmd -g t10721.d # recompiles (1st time with these options)
rdmd -O t10721.d # fast: no recompilation (cache hit)
rdmd -g t10721.d # fast: no recompilation (cache hit)
# modify t10721.d or any (recursive) dependency
rdmd -O t10721.d # recompiles (cache miss since hash changed)
```

here's for reference what rdmd outputs after running this:

```
/var/folders/ll/dtd6ksrn50n3xkdy4y61tf_80000gn/T/.rdmd-501/
├── eval.4176BE8C7144BB6EAF3CA1B706BFC853.d
├── eval.D25DF9CF331213004D56C55409E5E99C.d
├── rdmd-eval.4176BE8C7144BB6EAF3CA1B706BFC853.d-1B5EF85CE49FEDB422F66F19721FE135
│   ├── eval.4176BE8C7144BB6EAF3CA1B706BFC853
│   ├── objs
│   ├── rdmd.deps
│   └── rdmd.lock
├── rdmd-eval.D25DF9CF331213004D56C55409E5E99C.d-0BF83D66C1B856F99825200CBECE2C8B
│   ├── eval.D25DF9CF331213004D56C55409E5E99C
│   ├── rdmd.deps
│   └── rdmd.lock
├── rdmd-t10721.d-357B6D1E05DAA5A9B2827122C35E3FB1
│   ├── objs
│   └── rdmd.lock
```

Comment (Araq) [reply doc/advopt.txt:33]: I'll merge and patch it, it's poorly named.
