### PR TITLE
Fixes #16436

### LINKED ISSUE #16436: AsyncHttpClient doesn't handle errors
Which causes all sorts of weird behaviors. E.g. the following sample demonstrates an infinite hang in case when server closes connection before sending all the data. Otherwise if client is the only async "thread" in the process, the client will occasionally fail with error "No handles or timers registered in dispatcher." with totally irrelevant stack trace.
```nim
import asynchttpserver, httpclient, asyncdispatch

proc startServer() {.async.} =
  proc cb(req: Request) {.async.} =
    let headers = { "Content-length": "15"} # Provide invalid content-length
    await req.respond(Http200, "Hello World", headers.newHttpHeaders())

  var server = newAsyncHttpServer()
  await server.serve(Port(5555), cb)

proc runClient() {.async.} =
  let c = newAsyncHttpClient(headers = {"Connection": "close"}.newHttpHeaders)
  let r = await c.getContent("http://127.0.0.1:5555")
  echo r

asyncCheck startServer()
waitFor runClient()
```

### PR DESCRIPTION
**Pull request by yglukhov**
I had to make `FutureStreams` failable for this. cc @dom96

### CODE REVIEW

File: lib/pure/asyncstreams.nim [hunk 1]
```diff
@@ -65,6 +75,10 @@ proc finished*[T](future: FutureStream[T]): bool =
   ## no data waiting to be retrieved.
   result = future.finished and future.queue.len == 0
 
+proc failed*[T](future: FutureStream[T]): bool =
```
Comment (timotheecour) [inline lib/pure/asyncstreams.nim:78]: how about instead introducing an API with opposite semantics `succeeded`, to avoid double negation and make it easier to write things like `doAssert fut.succeeded` etc

Comment (yglukhov) [reply lib/pure/asyncstreams.nim:78]: Then it would be inconsistent with `Future[T].failed()` API  ¯\\_ツ_/¯

**Comment by yglukhov** [comment]
Moved the test to a new file, as the old one is disabled

File: lib/pure/asyncstreams.nim [hunk 2]
```diff
@@ -107,7 +121,10 @@ proc read*[T](future: FutureStream[T]): owned(Future[(bool, T)]) =
       res[0] = true
       res[1] = fs.queue.popFirst()
```
Comment (dom96) [inline lib/pure/asyncstreams.nim:122]: I think it might be better to avoid calling this if `fs` has failed, instead return early from this callback and fail `resFut` before this `if` branch. I think there is a possibility this line can throw an exception otherwise.

**Review by dom96 — APPROVED** [review]
Just one comment to consider, but overall LGTM.

File: tests/stdlib/thttpclient_standalone.nim [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+  asyncCheck startServer()
+
+  var gotException = false
+  try:
+    waitFor runClient()
+  except ProtocolError:
+    gotException = true
+
+  doAssert(gotException)
```
Comment (timotheecour) [inline tests/stdlib/thttpclient_standalone.nim]:
```suggestion
doAssertRaises(ProtocolError): waitFor runClient()
```

File: tests/stdlib/thttpclient_standalone.nim [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+import asynchttpserver, httpclient, asyncdispatch
+
+block: # issue #16436
+  proc startServer() {.async.} =
+    proc cb(req: Request) {.async.} =
+      let headers = { "Content-length": "15"} # Provide invalid content-length
+      await req.respond(Http200, "Hello World", headers.newHttpHeaders())
+
+    var server = newAsyncHttpServer()
+    await server.serve(Port(5555), cb)
```
Comment (timotheecour) [inline tests/stdlib/thttpclient_standalone.nim:14]: causes flaky tests, see https://github.com/nim-lang/Nim/pull/16678#discussion_r555450480 and how that PR solves it;

maybe let's wait until https://github.com/nim-lang/Nim/pull/16678 is merged so you can use `let port = getLocalAddr(server.getSocket.getFd, AF_INET)[1]`

File: tests/stdlib/thttpclient_standalone.nim [hunk 5]
```diff
@@ -0,0 +1,32 @@
+discard """
+  cmd: "nim c --threads:on $file"
+  output: "OK"
+"""
+
+import asynchttpserver, httpclient, asyncdispatch
+
+block: # issue #16436
```
Comment (timotheecour) [inline tests/stdlib/thttpclient_standalone.nim]: https://nim-lang.github.io/Nim/contributing.html
> Always refer to a GitHub issue using the following exact syntax: bug #1234 as shown above, so that it's consistent and easier to search or for tooling

File: tests/stdlib/thttpclient_standalone.nim [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+
+  var gotException = false
+  try:
+    waitFor runClient()
+  except ProtocolError:
+    gotException = true
+
+  doAssert(gotException)
+
+echo "OK"
```
Comment (timotheecour) [inline tests/stdlib/thttpclient_standalone.nim]: remove this line and `output: "OK"` 
refs: https://github.com/nim-lang/Nim/pull/16678#discussion_r555446076

~~and use `cmd: "nim c -r --threads:on $file"` to be on safe side that this file runs (even though it will still run with `cmd: "nim c --threads:on $file"`)~~ (I deleted this sentence because of https://github.com/nim-lang/Nim/issues/16701)

File: tests/stdlib/thttpclient_standalone.nim [hunk 7]
```diff
@@ -0,0 +1,32 @@
...
+      let headers = { "Content-length": "15"} # Provide invalid content-length
+      await req.respond(Http200, "Hello World", headers.newHttpHeaders())
+
+    var server = newAsyncHttpServer()
+    await server.serve(Port(5555), cb)
+
+  proc runClient() {.async.} =
+    let c = newAsyncHttpClient(headers = {"Connection": "close"}.newHttpHeaders)
+    let r = await c.getContent("http://127.0.0.1:5555")
+    echo r
```
Comment (timotheecour) [inline tests/stdlib/thttpclient_standalone.nim]:
```suggestion
    doAssert false, "should fail earlier"
```

File: lib/pure/asyncstreams.nim (hunk 2 above)
Comment (yglukhov) [reply lib/pure/asyncstreams.nim:122]: We're not calling this if `fs` has failed, as failed also means `finished`, and we don't get into this branch.

File: tests/stdlib/thttpclient_standalone.nim (hunk 4 above)
Comment (dom96) [reply tests/stdlib/thttpclient_standalone.nim:14]: Why does this cause flaky tests? Is it because the port is too low? Maybe a higher port number can just be used?

Comment (timotheecour) [reply tests/stdlib/thttpclient_standalone.nim:14]: see https://github.com/nim-lang/Nim/pull/14327 which has all the details. Multiple tests can potentially access the same port and when they run in parallel, you get flaky tests that trigger based on unrelated conditions (eg simply reordering a file etc).

in future PR we can make it easier for users to get the port, in the meantime we can use `let port = getLocalAddr(server.getSocket.getFd, AF_INET)[1]`


But I don't want to block this PR if other PR will take some more time so we can also move forward with this one and then patch this to use Port(0) in future work
