### PR TITLE
fix #19882 Improve error message when instantiating generics that lac…

### LINKED ISSUE #19882: Improve error message when instantiating generics that lack a type
I wish this were a PR but I would require some guidance to where to start differentiating this error condition from others.

Improve error message when instantiating generics that lack a type

### Example
```nim
import critbits
proc init(): ref CritBitTree =      
  new(result)
var a = init()
```

### Current Output
```
 Error: cannot instantiate: 'CritBitTree'
```

Not helpful. Consider a programmer on a deadline after an all nighter at six in the morning. Shouldn't happen, but...

### Expected Output
```
Error: cannot instantiate: 'CritBitTree'
Might the type definition be missing its concrete type, e.g. 'CritBitTree[void]' instead of 'CritBitTree'`?
```

Sleep deprived programmer now loves the compiler.

### Possible Solution

Errors due to lacking concrete type would have to be isolated from other "cannot instantiate" error conditions and this message emitted.

### PR DESCRIPTION
**Pull request by bung87**
…k a type

fix #19882

### CODE REVIEW

File: compiler/seminst.nim [hunk 1]
```diff
@@ -54,7 +54,10 @@ iterator instantiateGenericParamList(c: PContext, n: PNode, pt: TIdTable): PSym
           # later by semAsgn in return type inference scenario
           t = q.typ
         else:
-          localError(c.config, a.info, errCannotInstantiateX % s.name.s)
+          if q.typ.kind == tyCompositeTypeClass:
+            t = errorType(c)
+          else:
+            localError(c.config, a.info, errCannotInstantiateX % s.name.s)
```
Comment (Varriount) [inline compiler/seminst.nim]: Wouldn't this be better as
```suggestion
          if q.typ.kind != tyCompositeTypeClass:
            localError(c.config, a.info, errCannotInstantiateX % s.name.s)
```
given the presence of `t = errorType(c)` on line [58/61](https://github.com/nim-lang/Nim/pull/20356/files#diff-3006485ebf12b3abba7b715cdf74ef427e3bfdbd943de237d4b005170da8b219L58)

File: tests/errmsgs/t19882.nim [hunk 2]
```diff
@@ -0,0 +1,10 @@
+
+discard """
+  errormsg: "cannot instantiate 'A[T, P]' inside of type definition: 'init'; Maybe generic arguments are missing?"
+"""
+type A[T,P] = object
+  b:T
+  c:P
+proc init(): ref A =      
+  new(result)
+var a = init()
```
Comment (Varriount) [inline tests/errmsgs/t19882.nim]:
```suggestion
var a = init()

```

**Review by Varriount — APPROVED** [review]
