### PR TITLE
Remove tracking of environment from osenv.nim v2

### LINKED ISSUE #18533: `getEnv` + friends gives SIGSEGV or wrong results; osenv should not try to keep track of `environment`
### Example 1
```nim
import os

proc c_getenv(env: cstring): cstring {.importc: "getenv", header: "<stdlib.h>".}
var thr: Thread[void]
proc threadFunc {.thread.} =
  putEnv("foo", "fooVal2")
proc main()=
  putEnv("foo", "fooVal1")
  echo getEnv("foo")
  createThread(thr, threadFunc)
  joinThreads(thr)
  echo getEnv("foo")
  echo $c_getenv("foo")
main()
```

### Current Output
before https://github.com/nim-lang/Nim/pull/18530:
```
fooVal1
fooVal1
Traceback (most recent call last)
/Users/timothee/git_clone/nim/timn/tests/nim/all/t12606.nim(18) t12606
/Users/timothee/git_clone/nim/timn/tests/nim/all/t12606.nim(17) main
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

after https://github.com/nim-lang/Nim/pull/18530: it improves, but still wrong (/cc @brightly-salty):
fooVal1
fooVal1
fooVal2

### Expected Output
fooVal1
fooVal2
fooVal2

## Example 2
`delEnv` has similar bug (since it also uses `environment`)

this should raise an `OSError`, but doesn't, because the call is intercepted by 1st checking `environment`
```nim
import std/os
delEnv("foo=bar")
```

### Possible Solution
osenv should not try to keep track of `environment`; it's not thread-safe, and not safe against other modifications of environment variables (eg via importc procs etc)

### Additional Information
1.5.1 25efb5386293540b0542833625d3fb6e22f3cfbc

### PR DESCRIPTION
**Pull request by timotheecour**
* (EDIT) fixes https://github.com/nim-lang/Nim/issues/18533
* fixes windows problems in https://github.com/nim-lang/Nim/pull/18535
* add more tests and also test for js and vm (in addition to c and cpp)
* add tests to ensure empty values work across backends and OS's

the 1st commit is squashed from https://github.com/nim-lang/Nim/pull/18535 and keeps the author's name

## note
code to support empty values on windows (`putEnv("foo", "")`) is inspired from https://github.com/facebook/folly/commit/5d8ca09a3f96afefb44e35808f03651a096ab9c7, see also https://github.com/facebook/folly/blob/master/folly/portability/Stdlib.cpp

this is the best approach I found after extensive research; it allows having same semantics across backends (c,cpp,js,vm) and os's (osx, linux, windows)

## future work
- [x] add a vmops for `envPairs` (via an intermediate seq, like for walkFiles iterator etc)
      => tracked in https://github.com/nim-lang/Nim/pull/18615
- [ ] add clearEnv

## links
* https://gitlab.haskell.org/ghc/ghc/-/issues/12494
* https://github.com/golang/go/issues/5610
* https://gitlab.haskell.org/ghc/ghc/-/commit/49e334c8ea98cd5ecc81cfe10827538182815723
* https://bugs.python.org/issue39413
* https://github.com/python/cpython/pull/18115#issuecomment-577221477 has a good explanation too
* https://github.com/python/cpython/pull/18163

### CODE REVIEW

**Comment by Araq** [comment]
Does this code still work?

```nim

putEnv("key", "value")
assert getEnv("key") == "value"

```

Because 11 years ago when I wrote the code, it didn't and I had to come up with the `environment` workaround...

**Comment by timotheecour** [comment]
> Does this code still work?

yes, i just double-checked; if that didn't work nothing would; more importantly, it's covered in the tests, see tosenv.nim which has increased coverage compared to before this PR (c,cpp,js,vm + threads + more testing)

EDIT: https://github.com/nim-lang/Nim/pull/18530 (which was merged last week) is also an ingredient that makes this work, by avoiding having to hold on to the strings by using setenv instead of putenv.

File: lib/pure/includes/osenv.nim [hunk 1]
```diff
@@ -201,33 +93,14 @@ else:
...
     ## * `envPairs iterator <#envPairs.i>`_
-
-    # Note: by storing the string in the environment sequence,
-    # we guarantee that we don't free the memory before the program
-    # ends (this is needed for POSIX compliance). It is also needed so that
-    # the process itself may access its modified environment variables!
-    when nimvm:
-      discard "built into the compiler"
+    when defined(windows):
+      if key.len == 0 or '=' in key:
```
Comment (Araq) [inline lib/pure/includes/osenv.nim:97]: This `'=' notin key` is a new requirement.

Comment (timotheecour) [reply lib/pure/includes/osenv.nim:97]: = in key causes bug, see https://github.com/nim-lang/Nim/issues/18502 which was already fixed by #18050 

```nim
import os
putEnv("foo2=bar", "baz")
echo getEnv("foo2=bar", "def") # 1.4: prints bar=baz
echo getEnv("foo2", "def") # 1.4: prints bar=baz
```
after https://github.com/nim-lang/Nim/pull/18530, `putEnv("foo2=bar", "baz")` raises on linux|osx

after this PR, it also raises on windows, making code more platform and correct:

https://docs.microsoft.com/en-us/windows/win32/procthread/environment-variables
> The name of an environment variable cannot include an equal sign (=).

Comment (Araq) [reply lib/pure/includes/osenv.nim:97]: Add it to the changelog please then.

Comment (timotheecour) [reply lib/pure/includes/osenv.nim:97]: done

**Comment by timotheecour** [comment]
@araq PTAL
