### PR TITLE
Fixes #17039 - checked field addr analysis

### LINKED ISSUE #17039: VM crash with object variant, adding seq to seq field
Encountered in nimscript. The issue seems to be that fields in object variant branches break when converting to `var T`.

### Example
```nim
type
  Obj1 = object
    case kind: bool
    of false:
      field: seq[int]
    else: discard

static:
  var obj1 = Obj1()
  obj1.field.add(@[])
```

### Current Output

```
....compiler\nim.nim(119) nim
compiler\nim.nim(84) handleCmdLine
compiler\main.nim(242) mainCommand
compiler\main.nim(213) compileToBackend
compiler\main.nim(90) commandCompileToC
compiler\modules.nim(177) compileProject
compiler\modules.nim(97) compileModule
compiler\passes.nim(180) processModule
compiler\passes.nim(73) processTopLevelStmt
compiler\sem.nim(607) myProcess
compiler\sem.nim(575) semStmtAndGenerateGenerics
compiler\semstmts.nim(2306) semStmt
compiler\semexprs.nim(1029) semExprNoType
compiler\semexprs.nim(2865) semExpr
compiler\semstmts.nim(2248) semStmtList
compiler\semexprs.nim(2917) semExpr
compiler\semstmts.nim(2204) semStaticStmt
compiler\vm.nim(2213) evalStaticStmt
compiler\vm.nim(2202) evalConstExprAux
compiler\vm.nim(716) rawExecute
lib\system\fatal.nim(53) sysFatal
Error: unhandled exception: 'node' is not accessible using discriminant 'kind' of type 'TFullReg' [FieldDefect]
```

### Expected Output
compiles

### Possible Solution

As an immediate solution, if you change this line in `opcLdObj`:

https://github.com/nim-lang/Nim/blob/6e267d28b3459aa447cae07ba61209438977cd5c/compiler/vm.nim#L714

to this line below it in `opcLdObjAddr`:

https://github.com/nim-lang/Nim/blob/6e267d28b3459aa447cae07ba61209438977cd5c/compiler/vm.nim#L730

it works. Maybe the wrong VM opcode is getting generated, but it's better to be safe than crashing the compiler.

### Additional Information

```
$ nim -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-02-14
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: fff5819ee728aa62fd857982f799ecc0fac0fd5e
```

### PR DESCRIPTION
**Pull request by saem**
Checked field expressions, such as an object variant field access results in
occasionally broken address analysis crashing the VM. This guard added here
mimics guarded access in ldObjAddr. This is to prevent a crash, while a fix is
devised.

### CODE REVIEW

**Comment by saem** [comment]
All tests passed locally, looking at the way the `nkCheckedFieldExpr` are generated this should be fine.

Let's see what happens in CI more broadly across platforms.

**Comment by saem** [comment]
Nope, going to go with the hackier fix for now to prevent the compiler crash, will update the PR appropriately.

File: compiler/vm.nim [hunk 1]
```diff
@@ -711,7 +711,7 @@ proc rawExecute(c: PCtx, start: int, tos: PStackFrame): TFullReg =
     of opcLdObj:
       # a = b.c
       decodeBC(rkNode)
-      let src = regs[rb].node
+      let src = if regs[rb].kind == rkNode: regs[rb].node else: regs[rb].nodeAddr[]
```
Comment (ringabout) [inline compiler/vm.nim:714]: Maybe something like this is better
```nim
      let kind = regs[rb].kind
      let src = 
        if kind == rkNode: regs[rb].node
        elif kind == rkNodeAddr: regs[rb].nodeAddr[]
        else: doAssert false, $kind
```

Comment (saem) [reply compiler/vm.nim:714]: The error shows up and can be localized without this and if the compile is release or danger it won't work, so it really doesn't add anything. So no, that's not better.
