### PR TITLE
Fixed generic distinct conversions for 'var'

### LINKED ISSUE #17322: Borrowing mutable operations from distinct types via conversion doesn't work when the base type is a generic type.
### Example
```nim
type
  A[T] = distinct string

proc foo(a: var A) =
  a.string.add "foo"

type
  B = distinct A[int]

var b: B
foo A[int](b)
b.string.add "bar"
```

### Current Output
```
test.nim(11, 5) Error: type mismatch: got <A[system.int]>
but expected one of:
proc foo(a: var A)
  first type mismatch at position: 1
  required type for a: var A
  but expression 'A[int](b)' is immutable, not 'var'

expression: foo A[int](b)
test.nim(12, 9) Error: type mismatch: got <string, string>
but expected one of:
proc add(x: var string; y: char)
  first type mismatch at position: 1
  required type for x: var string
  but expression 'string(b)' is immutable, not 'var'
proc add(x: var string; y: cstring)
  first type mismatch at position: 1
  required type for x: var string
  but expression 'string(b)' is immutable, not 'var'
proc add(x: var string; y: string)
  first type mismatch at position: 1
  required type for x: var string
  but expression 'string(b)' is immutable, not 'var'
proc add[T](x: var seq[T]; y: openArray[T])
  first type mismatch at position: 1
  required type for x: var seq[T]
  but expression 'string(b)' is of type: string
proc add[T](x: var seq[T]; y: sink T)
  first type mismatch at position: 1
  required type for x: var seq[T]
  but expression 'string(b)' is of type: string

expression: add(string(b), "bar")
```

### Additional Information
- While not demonstrated here, manual borrowing doesn't work either.

- This issue doesn't happen when `A` is not a generic:

```nim
type
  A = distinct string

proc foo(a: var A) =
  a.string.add "foo"

type
  B = distinct A

var b: B
foo A(b)
b.string.add "bar"
```

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-03-10
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: eb07a5a75b63110642c5ce6f9126c9c8af231a64
active boot switches: -d:release -d:nimUseLinenoise
```

### PR DESCRIPTION
**Pull request by beef331**
Closes: https://github.com/nim-lang/Nim/issues/17322 
Partially addresses https://github.com/nim-lang/Nim/issues/14482

### CODE REVIEW

File: compiler/types.nim [hunk 1]
```diff
@@ -1121,15 +1121,22 @@ proc sameTypeAux(x, y: PType, c: var TSameTypeClosure): bool =
...
+          if t[0].kind == tyGenericInst and t[0][^1].kind == tyDistinct:
+            # Distincts can be generic as such we want to find the node back always
+            t = t[0][^1]
+          else:
+            t = t[0]
+      recurseForBase(a)
+      recurseForBase(b)
       if a.kind != b.kind: return false
     of dcEqOrDistinctOf:
       while a.kind == tyDistinct: a = a[0]
```
Comment (metagn) [inline compiler/types.nim]: `recurseForBase` here too?

Comment (beef331) [reply compiler/types.nim]: You're right, probably should make `getDistinctBase` a procedure so that it can be used for all distinct checks. Same with a `isDistinctType` procedure.

**Comment by beef331** [comment]
Code generated by jsgen is still invalid if anyone can take a look at that for me that'd be great, I cannot figure it out.
