### PR TITLE
remove conflicting `default` call in tables.getOrDefault

### LINKED ISSUE #23587: Error: type mismatch: got <typedesc[A]>, but expected one of: A = proc (){.closure.}
### Description

[https://play.nim-lang.org/#pasty=cVWRkhXTOfpv](https://play.nim-lang.org/#pasty=cVWRkhXTOfpv)

Compiles normally on 'play.nim-lang.org' without uncommenting.
Compiling locally will report an error, just like the title says.

```nim
import std/tables

# After uncommenting and compiling on 'play.nim-lang.org', an error will be reported (killed by system)
# import std/asyncnet
# import std/asyncdispatch

type
  A = proc ()

proc main =
  let repo = initTable[uint32, A]()

  let c1 = repo.getOrDefault(uint32(1), nil)
  echo "c1.isNil: ", c1.isNil

  let c2 = repo.getOrDefault(uint32(1), A(nil))
  echo "c2.isNil: ", c2.isNil

main()

```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-05-05
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 1ef4d04a1e56f67d85559a7964e9467df06bc2d7
active boot switches: -d:release

### Current Output

```text
/root/repos/spaces2/a.nim(13, 16) template/generic instantiation of `getOrDefault` from here
/root/.choosenim/toolchains/nim-#devel/lib/pure/collections/tables.nim(437, 19) Error: type mismatch: got <typedesc[A]>
but expected one of:
A = proc (){.closure.}
```

### Expected Output

```text
no error
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
fixes #23587

As explained in the issue, `getOrDefault` has a parameter named `default` that can be a proc after generic instantiation. But the parameter having a proc type [overrides all other overloads](https://github.com/nim-lang/Nim/blob/f73e03b1323cf3ed65d6996f43c8e6891c40f924/compiler/semexprs.nim#L1203) including the magic `system.default` overload and causes a compile error if the proc doesn't match the normal use of `default`. To fix this, the `result = default(B)` initializer call is removed because it's not needed, `result` is always set in `getOrDefaultImpl` when a default value is provided.

This is still a suspicious behavior of the compiler but `tables` working has a higher priority.

### CODE REVIEW

File: lib/pure/collections/tables.nim [hunk 1]
```diff
@@ -434,7 +434,6 @@ proc getOrDefault*[A, B](t: Table[A, B], key: A, default: B): B =
     let a = {'a': 5, 'b': 9}.toTable
     doAssert a.getOrDefault('a', 99) == 5
     doAssert a.getOrDefault('z', 99) == 99
-  result = default(B)
```
Comment (Araq) [inline lib/pure/collections/tables.nim:437]: No. Instead the parameter `default: B` should be `def: B`.

Comment (metagn) [reply lib/pure/collections/tables.nim:437]: Did both, and did it for all parameters named `default` in tables (`OrderedTable` had the same bug). There are others across the codebase but they're less harmful and this PR being simpler is better.

Unfortunately this breaks named argument usage (i.e. `getOrDefault(foo, bar, default = val)`). We can change the code in this repo but it might still break packages.

Comment (Araq) [reply lib/pure/collections/tables.nim:437]: Yeah I know but it's a risk I'm willing to take.
