### PR TITLE
Fix 1179 unsigned number literals

### LINKED ISSUE #1179: Sign of certain short constants is wrong
When using hexadecimal/binary constants with `'u8`, `'u16`, etc. with the highest bit is set, the compiler seems to have trouble with them. Also, having temporary `char(x)` values, where `x` is negative, seems to run into related problems.

```nimrod
import unsigned, typetraits

let x = 0x80'u8 shr 7
let y = 128'u8 shr 7
echo x.type.name, " ", y.type.name
echo x, " ", y
echo 0x80'u8
echo 0b10000000'u8
echo char(-1) < char(0)
```

### PR DESCRIPTION
**Pull request by ozra**
Fixes #1179, except the `char(-1) < char(0)` which is a different beast.
Also fixes range/bounds checking on non base-10 literals.
Some general readability clean up to my previous edits.

### CODE REVIEW

**Comment by ozra** [comment]
```nim
let x = 0x80'u8 shr 7                   # FIXED
let y = 0b10000000'u8 shr 7             # FIXED
let z = 0x8000'u16 shr 15               # FIXED
let w = 0x80000000'u32 shr 31           # FIXED
echo 0x80'u8                            # FIXED
echo 0b10000000'u8                      # FIXED

# SHOULD FAIL:
#let boundBreakingBinA = 0b10000000'i8  # FIXED
#let boundBreakingHexA = 0x123'u8       # FIXED
#let boundBreakingHexB = 0x123'i8       # FIXED
#let boundBreakingHexC = 0x123123'u16   # FIXED
#let boundBreakingHexD = 0x123123'i16   # FIXED
```

**Comment by Araq** [comment]
Instead of commenting it, can you add it to the test suite? ;-)

**Comment by ozra** [comment]
Haha, sure thing!

**Comment by ozra** [comment]
Now 0xFF'i8 etc. is accepted again by the lexer, checks are instead made that bit overflow doesn't happen.

File: compiler/lexer.nim [hunk 1]
```diff
@@ -452,48 +461,76 @@ proc getNumber(L: var TLexer): TToken =
...
+        xi = 0
+        let len = unsafeParseUInt(result.literal, xi)
+        if len != result.literal.len or len == 0:
+          raise newException(ValueError, "invalid integer: " & $xi)
+        result.iNumber = xi
+      else:
+        result.iNumber = parseBiggestInt(result.literal)
+
+      # Explicit bounds checks
+      let outOfRange = case result.tokType:
```
Comment (Araq) [inline compiler/lexer.nim]: Can't you merge this 'case' with the above 'case'?

Comment (ozra) [inline compiler/lexer.nim]: No, it will lead to more, and more complex code - it's the base10 and base-_other_ branching.
I'm gonna look this over one extra time to see if it is possible refining and why it doesn't solve #2909. From comparing the original code and this, it looks like it should fix that bug too...

Comment (ozra) [inline compiler/lexer.nim]: As already obvious from comment in #2909, that bug is out of the scope of this fix.
