### PR TITLE
simplify extccomp.nim json logic via jsonutils; fix #18084

### LINKED ISSUE #18084: `-d:nimBetterRun` (or `nim r`) should recompile if set of config files change
### Example
```nim
# ~/.config/nim/config.nims
switch("define", "D20210524T132710")
echo "in user config.nims"

# main.nim:
static: echo defined(D20210524T132710)
echo defined(D20210524T132710)
```

### Current Output
`nim r main`

```
in user config.nims
Hint: used config file '/Users/timothee/git_clone/nim/Nim_devel/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/nim/Nim_devel/config/config.nims' [Conf]
Hint: used config file '/Users/timothee/.config/nim/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/.config/nim/config.nims' [Conf]
true
Hint: 55361 lines; 0.426s; 61.672MiB peakmem; proj: /Users/timothee/git_clone/nim/timn/tests/nim/all/t12305.nim; out: /Users/timothee/git_clone/nim/timn/build/nimcache/t12305_8A11A1EA3D74A4F50FDE5CDF881950B0E39FD9D7 [SuccessX]
Hint: ***SLOW, DEBUG BUILD***; -d:release makes code run faster. [BuildMode]
true
```

`XDG_CONFIG_HOME= nim r main`
```
Hint: used config file '/Users/timothee/git_clone/nim/Nim_devel/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/nim/Nim_devel/config/config.nims' [Conf]
Hint: 32314 lines; 0.027s; 39.805MiB peakmem; proj: /Users/timothee/git_clone/nim/timn/tests/nim/all/t12305.nim; out: /Users/timothee/git_clone/nim/timn/build/nimcache/t12305_8A11A1EA3D74A4F50FDE5CDF881950B0E39FD9D7 [SuccessX]
Hint: ***SLOW, DEBUG BUILD***; -d:release makes code run faster. [BuildMode]
Hint: /Users/timothee/git_clone/nim/timn/build/nimcache/t12305_8A11A1EA3D74A4F50FDE5CDF881950B0E39FD9D7  [Exec]
true
```

### Expected Output
the fact that `XDG_CONFIG_HOME= ` was passed causes user config to be skipped (as intended), and that part works as evidenced by the Hint:Conf shown).

What doesn't work is that this skips recompilation (using cached binary), causing wrong results: `defined(D20210524T132710)` should be skipped in this case

### Possible Solution
* keep track of which config files were run in the `nimBetterRun` code
* whether to also keep track of environment variables is a separate topic, not necessary to fix this issue, but plausible
* note that recompilation happens if a config file content changes (as it should); the bug only concerns the set of config files being run

### Additional Information
1.5.1 7f077a76fea389ce4f55e18857c499fadb3958fa

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #18084
* simplify extccomp.nim json logic via jsonutils
the resulting code is much simpler, concise and maintainable (removes 100 LOC, and more after we'll remove the bootstrap workaround)

### CODE REVIEW

File: compiler/extccomp.nim [hunk 1]
```diff
@@ -14,7 +14,7 @@
 
 import ropes, platform, condsyms, options, msgs, lineinfos, pathutils
 
-import os, strutils, osproc, std/sha1, streams, sequtils, times, strtabs, json
+import std/[os, strutils, osproc, sha1, streams, sequtils, times, strtabs, json, jsonutils, sugar]
```
Comment (Araq) [inline compiler/extccomp.nim:17]: No. If you want to improve this, give us a "jsonbuilder" module first. One that doesn't repeat json's mistakes.

Comment (timotheecour) [reply compiler/extccomp.nim:17]: @araq are you referring to https://github.com/timotheecour/Nim/issues/745 (serialize/deserialize directly from string instead of from intermediate JsonNode) or to something else? If so, yes I agree https://github.com/timotheecour/Nim/issues/745 is needed down the line for performance in similar cases but it would be a 1 liner change on top of this PR once that feature lands. If you're worried about performance I can make a benchmark but I don't see a reason why this PR would create any meaningful overhead.

the name jsonbuilder sounds like it'd be instead similar to the `json.%*` operator (`%* {"age":35, "pi":3.1415}`), but that's worse than what I'm doing as there's no spec/type-safety and serialization/deserialization would need more synchronization, unlike this PR with `BuildCache` (which is analog to a protobuf proto)

this PR is a big code simplification as evidenced by the diff

**Comment by Araq** [comment]
> serialize/deserialize directly from string instead of from intermediate JsonNode)

Yes, that's my point.

> If so, yes I agree timotheecour#745 is needed down the line for performance in similar cases but it would be a 1 liner change on top of this PR once that feature lands. 

I fail to see how. 

> the name jsonbuilder sounds like it'd be instead similar to the json.%* operator (%* {"age":35, "pi":3.1415}), but that's worse than what I'm doing as there's no spec/type-safety and serialization/deserialization would need more synchronization

I don't understand but jsonbuilder's API is not outlined anywhere so it's hard to communicate.

**Comment by timotheecour** [comment]
>> it would be a 1 liner change on top of this PR once that feature lands.

> I fail to see how.

once https://github.com/timotheecour/Nim/issues/745 lands, the code in this PR can be changed as follows:

```nim
conf.jsonBuildFile.string.writeFile(bcache.toJson.pretty)
...
bcache.fromJson(jsonFile.string.parseFile)
```
=>
```nim
conf.jsonBuildFile.string.writeFile(bcache.toJsonStr(pretty = true))
...
bcache.fromJsonStr(jsonFile.string.readFile) # or directly from a stream to avoid `readFile`
```

`toJsonStr` is defined (briefly) in https://github.com/timotheecour/Nim/issues/745

in the meantime, there should be no performance penalty resulting from this PR even in absence of toJsonStr, fromJsonStr

**Comment by timotheecour** [comment]
>  there should be no performance penalty resulting from this PR

and indeed, here are timing results:
if i instrument (and compile nim with -d:release as is usual) `writeJsonBuildInstructions` with `let t = cpuTime()` at beginning and `echo cpuTime() - t` at end, here are results (best of 3 runs):

## before PR
nim c compiler/nim 0.0006
nim c -f compiler/nim 0.013 # more expensive because it calls `getCompileCFileCmd` in this case

## after PR
nim c compiler/nim 0.0006
nim c -f compiler/nim 0.011 # ditto

=> no performance drop as a result of this PR, not that there's anything surprising to that.
