### PR TITLE
Fix toJSStr for control characters

### LINKED ISSUE #4190: toJSStr throws exception on some strings
`toJSStr` function fails for some charater sequences. Sample code:
```nim
let s: string = "И\n"
let cs = s.cstring
```
Stacktrace (after nim js -r \<file\>):
```
/home/dmitry/work/tmp/nimcache/test_tojsstr.js:348
        asciiPart : asciiPart + decodeURIComponent(nonAsciiPart.join(""));
                                ^
URIError: URI malformed
    at decodeURIComponent (native)
    at toJSStr (/home/dmitry/work/tmp/nimcache/test_tojsstr.js:348:33)
    at Object.<anonymous> (/home/dmitry/work/tmp/nimcache/test_tojsstr.js:350:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```
Seems like the culprit is line 252:
```nim
nonAsciiPart[offset + 1] = `s`[i].toString(16);
```
which creates one-character code for characters less than 0x10.

Nim version - devel (not the latest, but the code in question didn't change since last year).

### PR DESCRIPTION
**Pull request by nigredo-tori**
fixes #4190 .
Add leading zero to encoded character if it is less than 0x10.
Add regression test.

### CODE REVIEW

File: tests/js/testtojsstr.nim [hunk 1]
```diff
@@ -0,0 +1,6 @@
+discard """
+  output = ""
```
Comment (Araq) [inline tests/js/testtojsstr.nim]: Well that just tests that it doesn't crash. Is that really good enough?

**Comment by nigredo-tori** [comment]
Fair point. Converted cstring back and echoed it - this is slightly better. There still is a possibility that both conversions can be broken simultaneously and in the same way, though.
