### PR TITLE
fix #7997

### LINKED ISSUE #7997: Error: obsolete usage of 'defined', use 'declared' instead
```nim
import locks # Compiles without this line
template ifDebug(e: untyped): untyped =
  when not defined(release): e
ifDebug echo "hi"
```
```
test.nim(6, 9) template/generic instantiation from here
test.nim(4, 19) Error: obsolete usage of 'defined', use 'declared' instead
```

### PR DESCRIPTION
**Pull request by Vindaar**
This is my first PR for the compiler, so I hope I'm not doing anything weird here...

It fixes issue #7997, which was caused by an export of a `release` proc
in `locks`. Thus the `release` in `defined(release)` of the `ifDebug`
template, was of kind `nkSym` instead of `nkIdent`.

This PR fixes that by casing on the kind of `n.sons[1]` in `semexpr.semDefined` now. If
it's of kind `nkSym` we get the corresponding `PIdent` from the symbol
and check if that exists.

The `localError` is removed, due to a clear distinction between
`declared` and `defined` now.

### CODE REVIEW

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -1613,10 +1613,17 @@ proc semDefined(c: PContext, n: PNode, onlyCurrentScope: bool): PNode =
...
+    of nkIdent:
+      if isDefined(c.config, n.sons[1].ident.s):
+        result.intVal = 1
+    of nkSym:
+      # the argument to `defined` may be of kind nkSym, if there exists e.g.
+      # a proc with the same name
+      if isDefined(c.config, n.sons[1].sym.name.s):
+        result.intVal = 1
+    else:
+      discard
```
Comment (jangko) [inline compiler/semexprs.nim]: what if someone type something like `defined(123)`, wouldn't it better to tell the user that it is not allowed rather than let it go silently?

File: compiler/semexprs.nim [hunk 2]
```diff
@@ -1613,10 +1613,17 @@ proc semDefined(c: PContext, n: PNode, onlyCurrentScope: bool): PNode =
   # we replace this node by a 'true' or 'false' node:
   result = newIntNode(nkIntLit, 0)
   if not onlyCurrentScope and considerQuotedIdent(c.config, n[0], n).s == "defined":
-    if n.sons[1].kind != nkIdent:
-      localError(c.config, n.info, "obsolete usage of 'defined', use 'declared' instead")
-    elif isDefined(c.config, n.sons[1].ident.s):
-      result.intVal = 1
+    case n.sons[1].kind
```
Comment (Araq) [inline compiler/semexprs.nim]: it's easier than this. Use:

```nim

let d = considerQuotedIdent(c.config, n[1], n)
result.intVal = isDefined(c.config, d.s)
```

**Comment by Araq** [comment]
Oh and please add a test case.

File: compiler/semexprs.nim (hunk 2 above)
Comment (Vindaar) [reply compiler/semexprs.nim]: Oohhh, that's nice! So many helpful procs in the compiler :)

File: compiler/semexprs.nim (hunk 1 above)
Comment (Vindaar) [reply compiler/semexprs.nim]: With the change @Araq proposed, that is taken care of, if I'm not mistaken. :)

**Comment by Vindaar** [comment]
I put the test case under templates. Not sure if that's a good place for it? And I hope I covered all aspects of it.

File: tests/template/t7997.nim [hunk 3]
```diff
@@ -0,0 +1,46 @@
+discard """
+  output: Valid and not defined
```
Comment (Araq) [inline tests/template/t7997.nim]: You need quotes around this.

Comment (Vindaar) [reply tests/template/t7997.nim]: Ooops, fixed.

Comment (Araq) [reply tests/template/t7997.nim]: 't7997' is a bad test name. Name it 'tdefined' or similiar.

File: compiler/semexprs.nim [hunk 4]
```diff
@@ -1613,10 +1613,8 @@ proc semDefined(c: PContext, n: PNode, onlyCurrentScope: bool): PNode =
   # we replace this node by a 'true' or 'false' node:
   result = newIntNode(nkIntLit, 0)
   if not onlyCurrentScope and considerQuotedIdent(c.config, n[0], n).s == "defined":
-    if n.sons[1].kind != nkIdent:
-      localError(c.config, n.info, "obsolete usage of 'defined', use 'declared' instead")
-    elif isDefined(c.config, n.sons[1].ident.s):
-      result.intVal = 1
+    let d = considerQuotedIdent(c.config, n[1], n)
+    result.intVal = if isDefined(c.config, d.s): 1 else: 0
```
Comment (Araq) [inline compiler/semexprs.nim]: ``ord isDefined(c.config, d.s)`` would be more idiomatic.

File: tests/template/t7997.nim (hunk 3 above)
Comment (Vindaar) [reply tests/template/t7997.nim]: Done.

File: compiler/semexprs.nim (hunk 4 above)
Comment (Vindaar) [reply compiler/semexprs.nim]: Had no idea that works, hehe. Nice :)
