### PR TITLE
symmetric difference operation for sets via `xor`

### LINKED ISSUE #554: introduce two xor operations for `set[T]`
### Abstract

xor instructions usage for `set[T]` are missing
we can introduce two important operations which make usage of xor instructions:
`a ^ b`: calculates xor between a and b
`a.toggle(b)`: toggles b elements of a

### Motivation

xor operations are useful to check differences between two sets or toggle elements of a set

### Description

`set[T]`  is an easy way to do bitflags in Nim, however a bitwise masking operation is missing and that is xor operation, it's importance is mostly to check differences between two sets or toggle elements of a set. those may be done with more operations but it's not so efficient as use xor directly. another workaround is casting to an unsigned integer but it might be unsafe and not so elegant also may not work at vm side.

we can introduce two operations which make usage of xor instructions:
`a ^ b`: calculates xor between a and b - magic: `XorSet`
`a.toggle(b)`: toggles b elements of a - magic: `ToggleSet`

### Code Examples

example of `a ^ b`:
```nim
type
  MyFlags = enum
    flagA, flagB

var flags: MyFlags
let flags0 = flags
# ... do something with those flags ...

# react to flags changes
let delta = flags0 ^ flags
if flagA in delta:
  echo "flagA changed"
if flagB in delta:
  echo "flagB changed"
```

example of `a.toggle(b)`:
```nim
type
  MyFlags = enum
    flagA, flagB, flagC
  MyState = object
    flags: MyFlags

# ... suppose there is a toggle button widget in a gui app ...
proc onclickButtonC(state: var MyState) =
  state.flags.toggle( {flagC} )
```

### Backwards Compatibility

introduces two straightforward magics and two simple procs to system for `set[T]`, no breaking changes

### PR DESCRIPTION
**Pull request by metagn**
closes https://github.com/nim-lang/RFCs/issues/554

Adds a symmetric difference operation to the language bitset type. This maps to a simple `xor` operation on the backend and thus is likely faster than the current alternatives, namely `(a - b) + (b - a)` or `a + b - a * b`. The compiler VM implementation of bitsets already implemented this via `symdiffSets` but it was never used.

The standalone binary operation is added to `setutils`, named `symmetricDifference` in line with [hash sets](https://nim-lang.org/docs/sets.html#symmetricDifference%2CHashSet%5BA%5D%2CHashSet%5BA%5D). An operator version `-+-` and an in-place version like `toggle` as described in the RFC are also added, implemented as trivial sugar.

### CODE REVIEW

**Comment by mrgaturus** [comment]
if you don't want add `-+-` and `toggle` to system, i think `symmetricDifference` should be in `setutils` instead and also add `-+-` and `toggle` to that module

**Comment by metagn** [comment]
Either way is fine but: `incl` and `excl` with 2 set arguments are also simple sugar and still in the system module, and `symmetricDifference` is a compiler magic same as `*`, `+` etc above it; so they could all still go in system. I just figured this PR would be simpler if it just had `symmetricDifference` as the compiler magic. We can even use another name than `-+-` if we also add it to hash sets.

**Comment by Araq** [comment]
IIRC I removed the `-+-` operator before version 1.0 as nobody used it. Now apparently there is some demand for it, but it's so rare that it shouldn't be in system.

**Comment by metagn** [comment]
Moved to `setutils`

File: lib/system/jssys.nim [hunk 1]
```diff
@@ -337,6 +337,18 @@ proc SetMinus(a, b: int): int {.compilerproc, asmNoStackFrame.} =
     return result;
   """.}
 
+proc SetXor(a, b: int): int {.compilerproc, asmNoStackFrame.} =
```
Comment (Araq) [inline lib/system/jssys.nim:340]:
```suggestion
proc setXor(a, b: int): int {.compilerproc, asmNoStackFrame.} =
```
