### PR TITLE
fixes #18543

### LINKED ISSUE #18543: nimyaml doesn't work on devel anymore
# Issue 1
```
git clone https://github.com/flyx/NimYAML
nim r test/tserialization
```

Gives

```
stack trace: (most recent call last)
C:\Users\blue\.choosenim\toolchains\nim-#devel\lib\core\macros.nim(1685, 10) getCustomPragmaVal
C:\Users\blue\Documents\GitHub\NimYAML\test\tserialization.nim(134, 7) template/generic instantiation of `suite` from here
C:\Users\blue\Documents\GitHub\NimYAML\test\tserialization.nim(559, 8) template/generic instantiation of `test` from here
C:\Users\blue\Documents\GitHub\NimYAML\test\tserialization.nim(562, 9) template/generic instantiation of `load` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(1341, 14) template/generic instantiation of `construct` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(1319, 19) template/generic instantiation of `constructChild` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(1166, 18) template/generic instantiation of `constructObject` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(416, 19) template/generic instantiation of `constructChild` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(1145, 20) template/generic instantiation of `constructObject` from here
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(904, 25) template/generic instantiation of `constructObjectDefault` from here   
C:\Users\blue\Documents\GitHub\NimYAML\yaml\serialization.nim(840, 29) template/generic instantiation of `getCustomPragmaVal` from here       
C:\Users\blue\.choosenim\toolchains\nim-#devel\lib\core\macros.nim(1685, 10) Error: O doesn't have any custom pragmas
```
It works on Nim 1.4.8

Related PR probably:
https://github.com/nim-lang/Nim/pull/11526
https://github.com/nim-lang/Nim/pull/17725
etc

Similarly
arraymancer, weave don't work on devel too.
https://github.com/mratsim/Arraymancer/issues/505
https://github.com/mratsim/weave/pull/175

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

File: tests/pragmas/tcustom_pragma.nim [hunk 1]
```diff
@@ -395,23 +395,24 @@ block:
...
+    let hasAttr = sym.hasCustomPragma(myAttr)
     newLit(hasAttr)
 
   doAssert hasMyAttr(TObj)
 
-# misc
-{.pragma: haha.}
-{.pragma: hoho.}
-template hehe(key, val: string, haha) {.pragma.}
+when false:
```
Comment (timotheecour) [inline tests/pragmas/tcustom_pragma.nim:403]: isn't that a regression?

Comment (Clyybber) [reply tests/pragmas/tcustom_pragma.nim:403]: Yes, this basically reverted https://github.com/nim-lang/Nim/pull/11526 :/

**Comment by timotheecour** [comment]
* the PR title and body should have mentioned that it reverts  #11526 
* how about introducing the new API in some std/pragmas instead?
