### PR TITLE
Fixed #4532, VS2010 now can compile Nim

### LINKED ISSUE #4532: Visual Studio 10 unresolved external symbol _trunc(should we support VS2010?)
while investigating #4459, I found this annoying thing. VS2010 cannot compile this code:

```nimrod
from math import trunc
echo trunc(1.0)
```

with error:
```text
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.30319.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) Incremental Linker Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/debug
/stack:33554432
/out:f:\projects\bug\truncate.exe
f:\projects\bug\nimcache\stdlib_math.obj
f:\projects\bug\nimcache\stdlib_system.obj
f:\projects\bug\nimcache\truncate.obj
truncate.obj : error LNK2019: unresolved external symbol _trunc referenced in function _truncateInit000
f:\projects\bug\truncate.exe : fatal error LNK1120: 1 unresolved externals
Error: execution of an external program failed: 'cl.exe  /DEBUG /Zi /Fd"$projectName.pdb" /F33554432  /Fef:\projects\bug\truncate.exe  f:\projects\bug\nimcache\stdlib_math.obj f:\projects\bug\nimcache\stdlib_system.obj f:\projects\bug\nimcache\truncate.obj '
```

Because of this, VS2010 also cannot compile Nim compiler because Nim compiler in vmops.nim contains call to trunc, and in VS2010 math.h there is no trunc or truncf(they are C99 functions, and VS2010 don't support them.

Should we support VS2010, or support only VS2013 and above?

### PR DESCRIPTION
**Pull request by jangko**

### CODE REVIEW

File: lib/pure/math.nim [hunk 1]
```diff
@@ -221,6 +214,32 @@ when not defined(JS):
...
+        if f < 0: return -truncImpl(-f)
+        elif f == 0: return f # Return -0 when f == -0
+        else: return 0
+
+      var x = cast[uint64](f)
+      let e = (x shr shift) and mask - bias
+
+      # Keep the top 12+e bits, the integer part; clear the rest.
+      if e < 64-12:
+        x = x and (not (1.uint64 shl (64.uint64-12.uint64-e) - 1.uint64))
```
Comment (Araq) [inline lib/pure/math.nim]: ``1u64`` is a bit shorter than ``1.uint64``.

File: lib/pure/math.nim [hunk 2]
```diff
@@ -221,6 +214,32 @@ when not defined(JS):
...
+
+      result = cast[float64](x)
+
+    proc trunc*[T: float32| float64](x: T): T =
```
Comment (Araq) [inline lib/pure/math.nim]: Please have the same prototypes as for the other targets:

```
proc trunc*(x: float32): float32
proc trunc*(x: float64): float64
```

File: lib/pure/math.nim [hunk 3]
```diff
@@ -221,6 +214,52 @@ when not defined(JS):
...
+      var x = cast[uint32](f)
+      let e = (x shr shift) and mask - bias
+
+      # Keep the top 9+e bits, the integer part; clear the rest.
+      if e < 32-9:
+        x = x and (not (1'u32 shl (32'u32-9'u32-e) - 1'u32))
+
+      result = cast[float32](x)
+      
+    proc trunc*[T: float32|float64](x: T): T =
```
Comment (Araq) [inline lib/pure/math.nim]: Sorry, not what I meant. Don't use ``T: float32|float64`` (aka a single generic) when the other target uses 2 procs.
