### PR TITLE
fix #18620

### LINKED ISSUE #18620: Stacktrace when using async with arc/orc is different than when using refc
The stacktrace returned by an async program compiled with arc/orc is different than one compiled with refc.
Most importantly, the stacktrace with arc/orc gives little help in finding out where the problem is.

Example

```nim
import std/[asyncdispatch]

proc async4 {.async.} =
  debugEcho "async4"
  await sleepAsync(1000)
  raise newException(Exception, "Fooo")

proc async3 {.async.} =
  debugEcho "async3"
  await sleepAsync(1000)
  await async4()

proc async2 {.async.} =
  debugEcho "async2"
  await sleepAsync(1000)
  await async3()

proc async1 {.async.} =
  debugEcho "async1"
  await sleepAsync(1000)
  await async2()

proc firstTrampoline {.async.} =
  debugEcho "firstTrampoline"
  await async1()

waitFor firstTrampoline()
```

Output with arc/orc

you can see that there's no hint that the problem happened in async4.
The only info is the first async trampoline proc and the exception itself.
```
firstTrampoline
async1
async2
async3
async4
/home/arkanoid/nim/experiments/asyncexceptions.nim(27) asyncexceptions
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1937) waitFor
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390) read
Error: unhandled exception: Fooo
Async traceback:
  /home/arkanoid/nim/experiments/asyncexceptions.nim(27)                    asyncexceptions
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208)  processPendingCallbacks
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29)      firstTrampolineNimAsyncContinue
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(145)     firstTrampolineIter
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390)   read
Exception message: Fooo
 [Exception]
Error: execution of an external program failed: '/home/arkanoid/nim/experiments/asyncexceptions '
```
Output with refc
```
firstTrampoline
async1
async2
async3
async4
/home/arkanoid/nim/experiments/asyncexceptions.nim(27) asyncexceptions
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208) processPendingCallbacks
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29) async4NimAsyncContinue
/home/arkanoid/nim/experiments/asyncexceptions.nim(6) async4Iter
[[reraised from:
/home/arkanoid/nim/experiments/asyncexceptions.nim(27) asyncexceptions
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208) processPendingCallbacks
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29) async3NimAsyncContinue
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(145) async3Iter
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390) read
]]
[[reraised from:
/home/arkanoid/nim/experiments/asyncexceptions.nim(27) asyncexceptions
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208) processPendingCallbacks
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29) async2NimAsyncContinue
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(145) async2Iter
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390) read
]]
[[reraised from:
/home/arkanoid/nim/experiments/asyncexceptions.nim(27) asyncexceptions
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208) processPendingCallbacks
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29) async1NimAsyncContinue
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(145) async1Iter
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390) read
]]
[[reraised from:
/home/arkanoid/nim/experiments/asyncexceptions.nim(27) asyncexceptions
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208) processPendingCallbacks
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29) firstTrampolineNimAsyncContinue
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(145) firstTrampolineIter
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390) read
]]
[[reraised from:
/home/arkanoid/nim/experiments/asyncexceptions.nim(27) asyncexceptions
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1937) waitFor
/home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390) read
]]
Error: unhandled exception: Fooo
Async traceback:
  /home/arkanoid/nim/experiments/asyncexceptions.nim(27)                    asyncexceptions
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208)  processPendingCallbacks
  /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29)      async4NimAsyncContinue
  /home/arkanoid/nim/experiments/asyncexceptions.nim(6)                     async4Iter
  #[
    /home/arkanoid/nim/experiments/asyncexceptions.nim(27)                    asyncexceptions
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208)  processPendingCallbacks
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29)      async3NimAsyncContinue
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(145)     async3Iter
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390)   read
  ]#
  #[
    /home/arkanoid/nim/experiments/asyncexceptions.nim(27)                    asyncexceptions
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208)  processPendingCallbacks
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29)      async2NimAsyncContinue
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(145)     async2Iter
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390)   read
  ]#
  #[
    /home/arkanoid/nim/experiments/asyncexceptions.nim(27)                    asyncexceptions
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208)  processPendingCallbacks
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29)      async1NimAsyncContinue
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(145)     async1Iter
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390)   read
  ]#
  #[
    /home/arkanoid/nim/experiments/asyncexceptions.nim(27)                    asyncexceptions
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1935) waitFor
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1627) poll
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(1368) runOnce
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncdispatch.nim(208)  processPendingCallbacks
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(29)      firstTrampolineNimAsyncContinue
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncmacro.nim(145)     firstTrampolineIter
    /home/arkanoid/.choosenim/toolchains/nim-1.4.8/lib/pure/asyncfutures.nim(390)   read
  ]#
Exception message: Fooo
 [Exception]
Error: execution of an external program failed: '/home/arkanoid/nim/experiments/asyncexceptions '
```

```
$ nim -v
Nim Compiler Version 1.4.8 [Linux: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 44e653a9314e1b8503f0fa4a8a34c3380b26fff3
active boot switches: -d:release

```
EDIT: i've repeated the test with devel and I got same results
```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-07-24
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f4ff276a90091f2b88c191aac5a201dcb3ec9795
active boot switches: -d:release
```

forum thread: https://forum.nim-lang.org/t/8285

### PR DESCRIPTION
**Pull request by ringabout**
close #18620

IMO, `e.trace` shouldn't be moved. Maybe I'm missing something.

If the `e.trace` is cleared as long as `getStackTraceEntries` is called, we can't trace the exception properly. For instance, we cannot decide whether the current error is re-raised. 
```
      if e.trace.len == 0:
        rawWriteStackTrace(e.trace)
      else:
        e.trace.add reraisedFrom(reraisedFromBegin)
        auxWriteStackTraceWithOverride(e.trace)
        e.trace.add reraisedFrom(reraisedFromEnd)
```

The stack trace with `nim c -r --lib:lib --gc:arc test3.nim`

```nim
firstTrampoline
async1
async2
async3
async4
C:\Users\blue\Documents\GitHub\Nim\test3.nim(27) test3
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1933) waitFor
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1625) poll
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(391) runOnce
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(206) processPendingCallbacks
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(28) async4NimAsyncContinue
C:\Users\blue\Documents\GitHub\Nim\test3.nim(6) async4Iter
[[reraised from:
C:\Users\blue\Documents\GitHub\Nim\test3.nim(27) test3
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1933) waitFor
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1625) poll
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(391) runOnce
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(206) processPendingCallbacks
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(28) async3NimAsyncContinue
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(131) async3Iter
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncfutures.nim(389) read
]]
[[reraised from:
C:\Users\blue\Documents\GitHub\Nim\test3.nim(27) test3
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1933) waitFor
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1625) poll
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(391) runOnce
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(206) processPendingCallbacks
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(28) async2NimAsyncContinue
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(131) async2Iter
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncfutures.nim(389) read
]]
[[reraised from:
C:\Users\blue\Documents\GitHub\Nim\test3.nim(27) test3
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1933) waitFor
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1625) poll
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(391) runOnce
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(206) processPendingCallbacks
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(28) async1NimAsyncContinue
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(131) async1Iter
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncfutures.nim(389) read
]]
[[reraised from:
C:\Users\blue\Documents\GitHub\Nim\test3.nim(27) test3
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1933) waitFor
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1625) poll
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(391) runOnce
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(206) processPendingCallbacks
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(28) firstTrampolineNimAsyncContinue
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(131) firstTrampolineIter
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncfutures.nim(389) read
]]
[[reraised from:
C:\Users\blue\Documents\GitHub\Nim\test3.nim(27) test3
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1935) waitFor
C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncfutures.nim(389) read
]]
Error: unhandled exception: Fooo
Async traceback:
  C:\Users\blue\Documents\GitHub\Nim\test3.nim(27)                    test3
  C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1933) waitFor
  C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1625) poll
  C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(391)  runOnce
  C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(206)  processPendingCallbacks
  C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(28)      async4NimAsyncContinue
  C:\Users\blue\Documents\GitHub\Nim\test3.nim(6)                     async4Iter
  #[
    C:\Users\blue\Documents\GitHub\Nim\test3.nim(27)                    test3
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1933) waitFor
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1625) poll
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(391)  runOnce
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(206)  processPendingCallbacks
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(28)      async3NimAsyncContinue
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(131)     async3Iter
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncfutures.nim(389)   read
  ]#
  #[
    C:\Users\blue\Documents\GitHub\Nim\test3.nim(27)                    test3
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1933) waitFor
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1625) poll
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(391)  runOnce
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(206)  processPendingCallbacks
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(28)      async2NimAsyncContinue
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(131)     async2Iter
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncfutures.nim(389)   read
  ]#
  #[
    C:\Users\blue\Documents\GitHub\Nim\test3.nim(27)                    test3
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1933) waitFor
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1625) poll
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(391)  runOnce
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(206)  processPendingCallbacks
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(28)      async1NimAsyncContinue
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(131)     async1Iter
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncfutures.nim(389)   read
  ]#
  #[
    C:\Users\blue\Documents\GitHub\Nim\test3.nim(27)                    test3
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1933) waitFor
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(1625) poll
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(391)  runOnce
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncdispatch.nim(206)  processPendingCallbacks
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(28)      firstTrampolineNimAsyncContinue
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncmacro.nim(131)     firstTrampolineIter
    C:\Users\blue\Documents\GitHub\Nim\lib\pure\asyncfutures.nim(389)   read
  ]#
Exception message: Fooo
 [Exception]
```

### CODE REVIEW

**Comment by xflywind** [comment]
Well I can make an alternative way to fix `asyncdispatch`.

**Comment by ringabout** [comment]
After this PR the behaviour of `getStackTraceEntries` is almost consistent with `proc getStackTrace(e: ref Exception): string =` with/without `arc`.

```nim
proc getStackTrace(e: ref Exception): string =
  if not isNil(e):
    result = $e.trace
  else:
    result = ""
```

File: lib/system/excpt.nim [hunk 1]
```diff
@@ -524,10 +524,7 @@ proc getStackTrace(e: ref Exception): string =
 proc getStackTraceEntries*(e: ref Exception): seq[StackTraceEntry] =
```
Comment (ringabout) [inline lib/system/excpt.nim:524]: How about changing to this? 

```nim
proc getStackTraceEntries*(e: ref Exception): lent seq[StackTraceEntry] =
  ## Returns the attached stack trace to the exception `e` as
  ## a `seq`. This is not yet available for the JS backend.
  e.trace
```

Comment (Araq) [reply lib/system/excpt.nim:524]: can be done in a follow-up PR.
