### PR TITLE
Render bug fixes

### LINKED ISSUE #8761: render bug: inversion of operator priorities
Example
```
import macros

proc fn(x, y: int):int =
  2 * (x + y)
 
macro dumpSym(fn: typed{nkSym}): untyped =
  let fn_impl = fn.getImpl
  fn_impl.name = genSym(nskProc, $fn_impl.name)
  result = parseStmt(fn_impl.repr)
  echo result.repr

dumpSym(fn)
```
``fn`` gets rendered as:

```
proc fn(x, y: int): int =
  result = 2 * x + y
```

### LINKED ISSUE #8762: render bug: binary operators called with with quotes rendered incorrectly
Example

```
import macros

proc t2(a, b: int): int =  
  `+`(a, b)

macro dumpSym(fn: typed{nkSym}): untyped =
  let fn_impl = fn.getImpl
  fn_impl.name = genSym(nskProc, $fn_impl.name)
  result = parseStmt(fn_impl.repr)
  echo result.repr

dumpSym(t2)
```
``t2`` get's rendered as

```
proc t2(a, b: int): int =
  result = +(a, b)
```
not valid Nim code

### LINKED ISSUE #8763: render bug: pure enums not handled correctly
Example

```
import macros

type
  A {.pure.} = enum
    X, Y
  B {.pure.} = enum
    X, Y

proc t4(a: B) =
  case a
    of B.X: echo B.X
    of B.Y: echo B.Y

macro dumpSym(fn: typed{nkSym}): untyped =
  let fn_impl = fn.getImpl
  fn_impl.name = genSym(nskProc, $fn_impl.name)
  result = parseStmt(fn_impl.repr)
  echo result.repr
umpSym(t4)
```

``t4`` get rendered as
```
proc t4(a: B) =
  case a
  of X:
    echo ["X"]
  of Y:
    echo ["Y"]
```
code is referencing wrong X and Y here

### LINKED ISSUE #8764: render bug: negative indices gets rendered as positive indices
Example
```
import macros

proc t3(x: seq[int]): int =
  x[^1]

macro dumpSym(fn: typed{nkSym}): untyped =
  let fn_impl = fn.getImpl
  fn_impl.name = genSym(nskProc, $fn_impl.name)
  result = parseStmt(fn_impl.repr)
  echo result.repr

dumpSym(t3)
```
``t3`` gets rendered as 
```
proc t3(x: seq[int]): int =
  result = x[1]
```

### PR DESCRIPTION
**Pull request by cooldome**
I have moved getPrecedence from parser to lexer to make it available to the renderer.
Yet calling ``getPrecedence`` is still rather painful as you need to open dummy lexer.
Let me know if you have better ideas.

~~Fixes #8764: render bug: negative indices gets rendered as positive indices~~
Fixes #8763: render bug: pure enums not handled correctly
Fixes #8762: render bug: binary operators called with with quotes rendered incorrectly
FIxes #8761: render bug: inversion of operator priorities 

For the #8764 I have changed `^` definition to be inlined proc instead of template, in this way macros output is nicer to deal with. It also made error messages look better, see test changes.

### CODE REVIEW

**Comment by Araq** [comment]
> For the #8764 I have changed ^ definition to be inlined proc instead of template, in this way macros output is nicer to deal with. It also made error messages look better, see test changes.

Please don't do this. It's a lost case to turn every template into an inline proc just because some later transformation would like to see "the original".

File: compiler/lexer.nim [hunk 1]
```diff
@@ -1249,3 +1285,14 @@ proc getIndentWidth*(fileIdx: FileIndex, inputstream: PLLStream;
     result = tok.indent
     if result > 0 or tok.tokType == tkEof: break
   closeLexer(lex)
+
+proc getPrecedence*(fileIdx: FileIndex, s: string, cache: IdentCache, config: ConfigRef): int =
```
Comment (Araq) [inline compiler/lexer.nim]: I don't like this at all and am thinking of a better solution.

File: compiler/renderer.nim [hunk 2]
```diff
@@ -103,7 +104,8 @@ proc initSrcGen(g: var TSrcGen, renderFlags: TRenderFlags; config: ConfigRef) =
   g.pendingNL = -1
   g.pendingWhitespace = -1
   g.inGenericParams = false
-  g.config = config
+  g.config = config  
+  g.cache = newIdentCache()
```
Comment (Araq) [inline compiler/renderer.nim]: This can cause subtle bugs, better pass it to ``initSrcGen`` somehow, if really required (I don't think it is).

File: compiler/renderer.nim [hunk 3]
```diff
@@ -860,6 +867,48 @@ proc isBracket*(n: PNode): bool =
...
+    put(g, tkAccent, "`")
+    gident(g, n)
+    put(g, tkAccent, "`")
+  else:
+    gsub(g, n)
+
+proc infixArgument(g: var TSrcGen, n: PNode, i: int) =
+  if i >= n.len: return
+
+  var needs_parenthesis = false
```
Comment (Araq) [inline compiler/renderer.nim]: As usual, the compiler uses ``camelCase`` everywhere.

File: compiler/lexer.nim (hunk 1 above)
Comment (cooldome) [reply compiler/lexer.nim]: I have found a better way, solved ;))

File: compiler/renderer.nim (hunk 2 above)
Comment (cooldome) [reply compiler/renderer.nim]: Ideal fix: removed IdentCache from the renderer all together

File: compiler/renderer.nim (hunk 3 above)
Comment (cooldome) [reply compiler/renderer.nim]: renamed

**Comment by cooldome** [comment]
Hi Araq,
I have fixed all but 

> Please don't do this. It's a lost case to turn every template into an inline proc just because some later transformation would like to see "the original".

The problem is that I don't see how else you can fix #8764. Template ``^(x:int)`` currently gets expanded to ``BackwardIndex(i)``, but ``BackwardIndex()`` is not seen from ``getImpl``, all you get is ``i``. Likely due to transformation pass. I see only two ways forward let me know if you have better ideas.

1. Make `^` a proc
2. Leave bug not fixed until something like https://github.com/nim-lang/Nim/pull/8489 lands

**Comment by cooldome** [comment]
all done, fix for #8764 is reverted. Ready for review
