### PR TITLE
fixes #7179; Floats are not range checked

### LINKED ISSUE #7179: Floats are not range checked
This generates an exception:
```
var i:int = -10
var n1:Natural = i.Natural
```

This does not:
```
var f:float = -10
var n2:Natural = f.Natural
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes #7179

```nim
var f = 751.0
echo f.int8
```

In this case, `int8(float)` yields different numbers for different optimization levels, since float to int conversions are undefined behaviors. In this PR, it mitigates this problem by conversions to same size integers before converting to the final type: i.e. `int8(int64(float))`, which has UB problems but is better than before

### CODE REVIEW

File: compiler/transf.nim [hunk 1]
```diff
@@ -552,7 +552,34 @@ proc transformConv(c: PTransf, n: PNode): PNode =
     # we don't include uint and uint64 here as these are no ordinal types ;-)
     if not isOrdinalType(source):
       # float -> int conversions. ugh.
-      result = transformSons(c, n)
+      # generate a range check:
+      if dest.kind in tyInt..tyInt64:
+        if dest.kind == tyInt64 or source.kind == tyInt64:
+          result = newTransNode(nkChckRange64, n, 3)
+        else:
+          result = newTransNode(nkChckRange64, n, 3)
```
Comment (Araq) [inline compiler/transf.nim]: So you do the same thing regardless of the condition?!
