### PR TITLE
fixes #17437 - crash where error reporting > 1

### LINKED ISSUE #17437: Nimsuggest crash
```nim
$ cat t.nim 
type
  V = ref object
    x, y: int

proc m =
  var v = V(x: x, y)

m()
```

```
$ nimsuggest t.nim 
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)
```

```
nim check t.nim 
Hint: used config file '/home/salewski/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/salewski/Nim/config/config.nims' [Conf]
....
/tmp/hhh/t.nim(6, 16) Error: undeclared identifier: 'x'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (1, 2): 'V' [type declared in /tmp/hhh/t.nim(2, 3)]
 (1, 2): 'm' [proc declared in /tmp/hhh/t.nim(5, 6)]
 (1, 3): 't' [module declared in /tmp/hhh/t.nim(1, 2)]
 (1, 4): '$' [proc declared in /home/salewski/Nim/lib/system/dollars.nim(1, 6)]
/tmp/hhh/t.nim(6, 16) Error: expression 'x' has no type (or is ambiguous)
/tmp/hhh/t.nim(6, 19) Error: incorrect object construction syntax
/tmp/hhh/t.nim(6, 19) Error: incorrect object construction syntax
/tmp/hhh/t.nim(6, 7) Hint: 'v' is declared but not used [XDeclaredButNotUsed]
fatal.nim(53)            sysFatal
Error: unhandled exception: 'sons' is not accessible using discriminant 'kind' of type 'TNode' [FieldDefect]
```

```
nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-03-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 83e002a318dee2370b266446d5ec26ad97a65f57
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by saem**
Crash occurs in cases where max error reporting is greater than 1 and an object
constructor error exists in a proc body.

Without this the tracking done in semProcAux will assume construction was
successful and not be able to handled the non-semmed nodes.

Scenarios where this occurs:
* nimsuggest
* nim check
* nim with `errorMax` > 1

This is also generally the correct direction nudging us towards proper `nkError`.

fixes #17437

### CODE REVIEW

File: tests/objects/t17437.nim [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  nimout: '''
+t17437.nim(20, 16) Error: undeclared identifier: 'x'
+t17437.nim(20, 16) Error: expression 'x' has no type (or is ambiguous)
+t17437.nim(20, 19) Error: incorrect object construction syntax
+t17437.nim(20, 19) Error: incorrect object construction syntax
+t17437.nim(20, 12) Error: expression '' has no type (or is ambiguous)
+'''
+"""
+
+# bug: #17437 invalid object construction should result in error
```
Comment (timotheecour) [inline tests/objects/t17437.nim]:
```suggestion
# bug #17437 invalid object construction should result in error
```

Comment (timotheecour) [reply tests/objects/t17437.nim]: (see rationale in contributing.rst)

**Comment by dom96** [comment]
Suggestion: to make it easier to go through notifications, include more detail about the issue in the PR title.

File: compiler/semobjconstr.nim [hunk 2]
```diff
@@ -392,17 +392,19 @@ proc semObjConstr(c: PContext, n: PNode, flags: TExprFlags): PNode =
...
   # field (if this is a case object, initialized fields in two different
   # branches will be reported as an error):
   var constrCtx = initConstrContext(t, result)
   let initResult = semConstructTypeAux(c, constrCtx, flags)
+  var hasError = false
 
   # It's possible that the object was not fully initialized while
   # specifying a .requiresInit. pragma:
   if constrCtx.missingFields.len > 0:
+    hasError = true
```
Comment (timotheecour) [inline compiler/semobjconstr.nim:407]: why not: `return errorNode(c, result)` ?

likewise in other cases below where you have `hasError = true`

Comment (saem) [reply compiler/semobjconstr.nim:407]: Because then the analysis changes and doesn't work in cases where you wish to report all errors, which is in fact safe and better to do so.

**Comment by saem** [comment]
Huh, why didn't `[skip ci]` work?

File: compiler/semobjconstr.nim (hunk 2 above)
Comment (saem) [reply compiler/semobjconstr.nim:407]: Added a small comment to explain hasError purpose -- it's a good question.

Comment (timotheecour) [reply compiler/semobjconstr.nim:407]: the flip side of the argument is redundant/bubbling errors, refs https://github.com/nim-lang/Nim/issues/16178, making nim check less useful; ideally I want all errors reported by nim check/nim r + --errormax:N to be unrelated (and non-causal)

as the example in tests/objects/t17437.nim shows, there are indeed redundant errors being reported; I'd need to check whether the above suggestion would improve things

> Because then the analysis changes 

what do you mean?

**Comment by timotheecour** [comment]
> Huh, why didn't [skip ci] work?

* why CI pipelines did it not skip?
we have:;
```
.github/workflows/ci_docs.yml:34:105:      !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]')
.github/workflows/ci_packages.yml:7:105:      !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]')
```

- [ ] i think we need to add similar logic to azure-pipelines.yml, because of https://github.com/microsoft/azure-pipelines-agent/issues/2944
- [ ] we need to update contributing.rst docs, which currently say: 
```
doc/contributing.rst:464:39:   documentation only changes), add `[ci skip]` to your commit message title.
```
(ci skip vs skip ci)

**Comment by saem** [comment]
Thanks, @timotheecour.

Hmm, I wonder if we could do something like have one pipeline stage before everything, which can detect if the change is meaningful and conservatively do a skip? (just seeding a thought to think about in the background, no action needed)

**Comment by timotheecour** [comment]
> Hmm, I wonder if we could

@saem in the spirit of "1 topic, 1 issue", let's move this discussion to https://github.com/timotheecour/Nim/issues/675

File: compiler/semobjconstr.nim (hunk 2 above)
Comment (saem) [reply compiler/semobjconstr.nim:407]: The redundant messages is a different issue.

So if there is an object with two or more fields, and you attempt to construct it but the initialization of two fields is a mismatch in type, then we should report each of those (wait to the end of the loop). Which is what it was doing before and that behavior makes sense, otherwise you'll get under reporting.
