### PR TITLE
fixes regression #17121; adding doc comment in importc proc makes it silently noop at CT

### LINKED ISSUE #17121: regression (0.19=> 0.20 onwards): adding doc comment in importc proc makes it silently noop at CT
### Example 1
```nim
when true:
  proc c_printf*(frmt: cstring): cint {.importc: "printf", header: "<stdio.h>", varargs, discardable.} =
    ## foo bar
    runnableExamples: discard
  static:
    let a = c_printf("abc\n")
```

### Current Output
noop (c_printf isn't actually called)

### Expected Output
Error: cannot 'importc' variable at compile time
(`--experimental:compiletimeFFI` is a separate topic)

### Example 2
same with this case but in this case, `=` is not technically needed unlike Example 1
```nim
  proc c_printf*(frmt: cstring): cint {.importc: "printf", header: "<stdio.h>", varargs, discardable.} =
    ## foo bar
  static:
    let a = c_printf("abc\n")
```
if we remove `=` the bug goes away (meaning it gives CT error)

### Example 3
with just `runnableExamples` but no doc comment, there is no bug (meaning it gives CT error). IIUC, This has to do with how AST differs between statement list vs expression.
```nim
when defined case1b:
  proc c_printf*(frmt: cstring): cint {.importc: "printf", header: "<stdio.h>", varargs, discardable.} =
    runnableExamples: discard

  static:
    let a = c_printf("abc\n")
```

### Additional Information
* 1.5.1 ac82be07d8ed9795caa0778f0f8577b3934d1d86
* root cause for https://github.com/nim-lang/Nim/issues/17118
* works in 0.19, fails in 0.20 onwards including devel

### PR DESCRIPTION
**Pull request by ringabout**
it was introduced by https://github.com/nim-lang/Nim/pull/11635
fixes #17121

### CODE REVIEW

File: compiler/vmgen.nim [hunk 1]
```diff
@@ -1596,11 +1596,23 @@ proc genTypeLit(c: PCtx; t: PType; dest: var TDest) =
...
+  case n.kind
+  of nkStmtList:
+    for i in 0..<n.len:
+      if not isEmptyBody(n[i]): return false
+    result = true
+  else:
+    if n.kind in {nkCommentStmt, nkEmpty}:
+      result = true
+    else:
+      result = false
```
Comment (Araq) [inline compiler/vmgen.nim]:
```suggestion
  else:
    result = n.kind in {nkCommentStmt, nkEmpty}
```
