### PR TITLE
closes #17793 ; improve errmsg when ctor called on non-tyObject kind

### LINKED ISSUE #17793: Confusing error messages for constructors
#### 1
```nim
type Test = object
  x: int

echo Test(42)
```
#### 2
```nim
type Test[T] = object
  x: T

echo Test(42)
```
#### 3
```nim
type Test[T] = object
  x: T

echo Test(x: 42)
```

#### 1
```
Error: type mismatch: got 'int literal(42)' for '42' but expected 'Test = object'
```
#### 2
```
Error: type mismatch: got 'int literal(42)' for '42' but expected 'Test = CompositeTypeClass'
```
#### 3
```
Error: object constructor needs an object type
```

#### 1
```
Error: expected object constructor
```
#### 2
```
Error: expected object constructor
```
#### 3
No error, `T` should be inferred to `int`. The same works with procs:
```nim
proc test[T](x: T): T = x

echo test(42) # compiles
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-04-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 3b80f0dc8ef2bc9d2a981a7c92a6355dfc72b7ef
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by timotheecour**
* closes #17793 (if you agree with what i said in https://github.com/nim-lang/Nim/issues/17793#issuecomment-823674407)
* refs #16533 for eg in #16533 erromsg is now:
```
t12194.nim(24, 11) Error: object constructor needs an object type [genericBody declared in t12194.nim(9, 3)]
      F = cf(f: fs)
```

instead of:
```
t12194.nim(24, 11) Error: object constructor needs an object type
      F = cf(f: fs)
```
which is clear enough.
the feature request in #16533 is still valid though, so this doesn't close it.

### CODE REVIEW

File: compiler/semobjconstr.nim [hunk 1]
```diff
@@ -11,6 +11,8 @@
 
 # included from sem.nim
 
+from std/sugar import dup
```
Comment (Araq) [inline compiler/semobjconstr.nim]: Now breaks the bsd cis... We need a better solution.

Comment (timotheecour) [reply compiler/semobjconstr.nim]: i've now changed it to `from sugar import dup`, but where can i see the logs? it's hard to shoot in the dark

Comment (ringabout) [reply compiler/semobjconstr.nim]: see https://github.com/nim-lang/Nim/pull/17801#issuecomment-823745649
