### PR TITLE
fix partially #13115 (now works for cpp; but still fails for js on openbsd)

### LINKED ISSUE #13115: newException terminates msg early from NULL byte, other IO does not
Error output produced by `raise newException` is inconsistent with other IO such as `echo` or `stdout.write`.

### Example
```nim
const b_null: char = 0.char
var msg = "This char is `" & $b_null & "` and works fine!"

echo msg

raise newException(Exception, msg)
```

### Current Output
```nim
echo msg
# This char is `` and works fine!

raise newException(Exception, msg)
# Error: unhandled exception: This char is `
```

### Expected Output
```nim
echo msg
# This char is `` and works fine!

raise newException(Exception, msg)
# Error: unhandled exception: This char is `` and works fine! [Exception]
```

### Additional Information

* This issue was found via fuzzing some CLI utility, which takes piped input. The error messsage was being cutoff, because the input contained a NULL byte.
EDIT:
* Consistency is the main thing I'd ask for, however, if both could output `^@` for NULL char, that may be better assuming it doesn't introduce needless complexity. 

```
$ nim -v
Nim Compiler Version 1.0.4 [Linux: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release

```

### PR DESCRIPTION
**Pull request by timotheecour**
fix partially #13115 (js on openbsd still broken for some reason)

/cc @xflywind 
before PR: works for js,cpp,vm
after PR: also cpp

## future work
- [ ] doesn't yet work for `openbsd + js` ; EDIT: ... due to an upstream nodejs bug that has been patched in more recent nodejs version

### CODE REVIEW

**Comment by euantorano** [comment]
This seems to have a conflict with `tests/exception/t13115.nim`. I assume JS on OpenBSD still exhibits the same behaviour even with this patch? If so, that's quite strange and I'll need to dig a bit to work out why.

**Comment by timotheecour** [comment]
> This seems to have a conflict with tests/exception/t13115.nim.

fixed

> I assume JS on OpenBSD still exhibits the same behaviour even with this patch? If so, that's quite strange and I'll need to dig a bit to work out why.

thanks

**Comment by Clyybber** [comment]
What prevents this from working on openbsd?

**Comment by timotheecour** [comment]
friendly ping @Clyybber

**Comment by Clyybber** [comment]
I think this should work on OpenBSD before we merge this.

**Comment by timotheecour** [comment]
PTAL

> I think this should work on OpenBSD before we merge this.

* openbsd on js was already failing prior to this PR and fixing it can be done later. I believe this is an upstream nodejs bug similar to the one I had submitted last year (https://github.com/nodejs/node/issues/28761); we should report this upstream after confirming (/cc @euantorano since you have access to openbsd; can you please test the snippet in https://github.com/nodejs/node/issues/28761 on openbsd?).


* I've amended PR msg and commit msg with `s/fix/fix partially/` so #13115 won't auto-close when this PR is merged

* I've improved test coverage for this bug by calling `execCmdEx` directly instead of relying on testament spec DSL which isn't suitable here; the test is stronger now: 
  * it now tests openbsd (except for js)
  * it now checks the msg is exactly what we expect (including the `\0`)
  * it now checks VM too

**Comment by euantorano** [comment]
It looks like there was a node patch to support the null character, I need to work out which versions that patch landed in as it’s possible that version isn’t packaged for OpenBSD yet. 

EDIT: looks like 12.16.1: https://openports.se/lang/node

It looks like the node change was released in 12.16.2: https://github.com/nodejs/node/pull/32313

It’s probably best to leave the test disabled for JS on OpenBSD for now if that’s the case, or else we may need to build our own copy of node as part of the build (or install a binary that’s not in ports...).

File: tests/exception/t13115.nim [hunk 1]
```diff
@@ -1,12 +1,23 @@
...
+    const file = currentSourcePath
+    for b in "c js cpp".split:
+      when defined(openbsd):
+        if b == "js": continue # xxx bug: pending #13115
+      for opt in ["-d:nim_t13115_static", ""]:
+        let cmd = fmt"{nim} r -b:{b} -d:nim_t13115 {opt} --hints:off {file}"
+        let (outp, exitCode) = execCmdEx(cmd)
+        doAssert msg in outp, cmd & "\n" & msg
+        doAssert exitCode == 1
+  main()
```
Comment (Clyybber) [inline tests/exception/t13115.nim:38]: Please get rid of this abomination and use testament to accomplish what you want.

File: tests/exception/t13115.nim [hunk 2]
```diff
@@ -1,12 +1,31 @@
...
+    const file = currentSourcePath
+    for b in "c js cpp".split:
+      when defined(openbsd):
+        if b == "js":
+          # xxx bug: pending #13115
+          # remove special case once nodejs updated >= 12.16.2
+          # refs https://github.com/nim-lang/Nim/pull/16167#issuecomment-738270751
+          continue
+      for opt in ["-d:nim_t13115_static", ""]:
+        let cmd = fmt"{nim} r -b:{b} -d:nim_t13115 {opt} --hints:off {file}"
```
Comment (ringabout) [inline tests/exception/t13115.nim:30]: Please provide an option to switch between `-d:debug` and `-d:release` mode. Because the behaviour differs.

Comment (ringabout) [reply tests/exception/t13115.nim:30]: see https://github.com/nim-lang/Nim/blob/d5ea1cd3ffcd65f97fcca22a4e47611e4f905a23/lib/system/excpt.nim#L151

Comment (ringabout) [reply tests/exception/t13115.nim:30]:
```ini
@if release or danger:
  stacktrace:off
  excessiveStackTrace:off
  linetrace:off
  debugger:off
  line_dir:off
  opt:speed
  define:release
@end
```

Comment (timotheecour) [reply tests/exception/t13115.nim:30]: done, and also took care to avoid combinatorial explosion

File: tests/exception/t13115.nim (hunk 1 above)
Comment (timotheecour) [reply tests/exception/t13115.nim:38]: testament spec DSL isn't flexible enough for this test, sorry. If you disagree, please show a complete example that tests VM, openbsd (for non-js case), the '\0' being part of the output message, allows avoiding combinatorial explosion (as i do in this PR) etc, while also avoiding generating N different test files (not DRY nor desirable).

testament spec may be good for the general case, but you'll always have special cases, which need things like:
* trunner.nim
* trunner_thirdparty.nim (https://github.com/nim-lang/Nim/pull/16221)
* tosproc.nim
* this test, etc

**Comment by timotheecour** [comment]
friendly ping

**Comment by VlkrS** [comment]
Both OpenBSD-current and OpenBSD-stable have a more recent version of nodejs now. 
Is it possible to re-evaluate?

**Comment by euantorano** [comment]
> Both OpenBSD-current and OpenBSD-stable have a more recent version of nodejs now. Is it possible to re-evaluate?

Certainly would be a good idea. Looks like the current version is 16.14.0: https://openports.se/lang/node

**Comment by VlkrS** [comment]
> Certainly would be a good idea. Looks like the current version is 16.14.0: https://openports.se/lang/node

It's 12.22.9 for -stable, but in any case the fix from 12.16.2 should be in ;)
