### PR TITLE
fix #11049, wrong streams.readBool and streams.peekBool

### LINKED ISSUE #11049: Not equal when streams.readBool and peekBool compare `true`
Return value of `streams.readBool()` and `streams.peekBool()` doesn't equal `true`.

### Example

```nim
import streams

block:
  var strm = newStringStream("aaaaaaaaaaaaaaaaaa")
  echo strm.readBool()
  echo strm.readBool() == true
  echo strm.readBool() != false
  echo true == true
  strm.close()

echo "----------------------"

block:
  var strm = newStringStream("aaaaaaaaaaaaaaaaaa")
  echo strm.peekBool()
  echo strm.peekBool() == true
  echo strm.peekBool() != false
  echo true == true
  strm.close()
```

### Current Output
```
true
false
true
true
----------------------
true
false
true
true
```

### Expected Output

```
true
true
true
true
----------------------
true
true
true
true
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.4 [Linux: amd64]
Compiled at 2019-02-01
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

File: lib/pure/streams.nim [hunk 1]
```diff
@@ -412,24 +412,42 @@ proc peekChar*(s: Stream): char =
...
 
-  read(s, result)
+  var t: byte
+  read(s, t)
+  if t == 1.byte:
+    result = true
+  elif t == 0.byte:
+    result = false
+  else:
+    raise newEIO("not a valid Boolean value")
```
Comment (Araq) [inline lib/pure/streams.nim]: Instead simply do: ``result = t != 0``, no ifs, no further checking. IMO.
