### PR TITLE
fix #15704 #15597 wrong VM register was freed

### LINKED ISSUE #15597: regression(1.0.2 => 1.0.4) VM: uncomprehensible FieldDefect error depending on unrelated code changes
I've tried to minimize the following example but it's really hard; almost any trivial (unrelated!) change removes the error, making it hard to isolate / workaround.

Note that in my actual (more complicated) use case, the error is still there and I can't get rid of it by "small code changes".

### Example
```nim
import std/os
import std/deques
import std/[sequtils]

type
  PathEntrySub* = object
    kind*: PathComponent
    path*: string
  PathEntry* = object
    kind*: PathComponent
    path*: string
    depth*: int
  GlobMode* = enum
    gDfs
    gBfs
  FollowCallback* = proc(entry: PathEntry): bool
  X1Callback* = proc (x, y: PathEntrySub): int
  GlobOpt* = object
    dir*: string
    relative: bool
    checkDir: bool
    globMode: GlobMode
    includeRoot: bool
    includeEpilogue: bool
    followSymlinks: bool
    follow: FollowCallback
    x1: X1Callback

proc initGlobOpt*(
  dir: string, relative = false, checkDir = true, globMode = gDfs,
  includeRoot = false, includeEpilogue = false, followSymlinks = false,
  follow: FollowCallback = nil, x1: X1Callback = nil): GlobOpt =
  result = GlobOpt(dir: dir, relative: relative, checkDir: checkDir, globMode: globMode, includeRoot: includeRoot, includeEpilogue: includeEpilogue, followSymlinks: followSymlinks, follow: follow, x1: x1)

iterator globOpt2*(opt: GlobOpt): PathEntry =
  var entry = PathEntry(depth: 0, path: ".")
  if false:
    entry.path = "asdf"
  echo "z4"

iterator globOpt*(opt: GlobOpt): PathEntry =
  var entry = PathEntry(depth: 0, path: ".")
  var stack = initDeque[PathEntry]()
  var checkDir = opt.checkDir
  if false:
    stack.addLast entry
  elif false:
    raise newException(OSError, "invalid root dir: " & opt.dir)

  if false:
    let current = if opt.globMode == gDfs: stack.popLast() else: stack.popFirst()
    discard opt.dir / "a"
  var dirsLevel: seq[PathEntrySub]
  echo "z5"

template glob*(args: varargs[untyped]): untyped =
  ## convenience wrapper
  globOpt(initGlobOpt(args))

template glob2*(args: varargs[untyped]): untyped =
  globOpt2(initGlobOpt(args))

proc processAux[T](a: T): seq[string] =
  a.mapIt(it.path)

const dir = "/tmp"
proc main=
  for ai in glob(dir): discard
  discard toSeq(glob2(dir)).processAux
static: main()
```

### Current Output
```
z5
z4
/Users/timothee/git_clone/nim/Nim_devel/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: 'sym' is not accessible using discriminant 'kind' of type 'TNode' [FieldDefect]
```

### Expected Output
no error

### Additional Information
devel c2ba4ef9799a097fec8b2bb1b033448860d60f1b 1.3.7

### LINKED ISSUE #15704: regression(1.0.2 => 1.0.4) VM register messed up depending on unrelated context
VM register messed up depending on unrelated context

### Example
```nim
when true: # D20201024T132230
  type Deque = object
  proc initDeque2(initialSize: int = 4): Deque = Deque()
  proc len2(a: Deque): int = 2

  proc baz(dir: string): bool = true
  proc bar2(head: string): string = "asdf"
  proc bar3(path: var string) = path = path

  type PathEntry* = object
    kind*: int
    path*: string
    depth*: int

  proc initGlobOpt*(dir: string, a1=false,a2=false,a3=false,a4=false): string =
    dir

  iterator globOpt*(dir: string): int =
    var stack = initDeque2()
    doAssert baz("")
    let z = stack.len2
    var a5: int
    if stack.len2 >= 0:
      var entry = PathEntry()
      echo "here"
      let current = if true: stack.len2 else: stack.len2
      entry.depth = 1
      entry.path = bar2("")
      bar3(entry.path)
    # echo "here2" # uncomment here => you get same error as https://github.com/nim-lang/Nim/issues/15597

  proc processAux(a: float) =
    echo a

  template bar(iter: untyped): untyped =
    var ret: float
    for x in iter:
      break
    ret

  const dir = "."

  proc main() =
    processAux(bar(globOpt(initGlobOpt(dir))))
  static: main()
```

### Current Output
```
stack trace: (most recent call last)
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11180.nim(130, 15) t11180
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11180.nim(128, 15) main
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11180.nim(85, 40) bar3
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11180.nim(5, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11180.nim(85, 40) Error: attempt to access a nil address kind: rkFloat
    proc bar3(path: var string) = path = path
                                         ^
```

### Expected Output
works

### Additional Information
* fails in devel 1.5.1 64016ddedcfc266c87d8fe7eece8b9476aa6db30 or 1.4.0 (tested on OSX)
* works in 1.0.0
* similar to https://github.com/nim-lang/Nim/issues/15597 in that if you uncomment `echo "here2"` you get same error as https://github.com/nim-lang/Nim/issues/15597 (and same stacktrace)
* I managed to reduce this by removing all imports, but it's hard to reduce further; unrelated changes make the bug disappear; in my original use case it's hard to get rid of this error though

EDIT:
fails in 1.0.4
works in 1.0.2

### PR DESCRIPTION
**Pull request by timotheecour**
fix #15704
fix #15597

(regressions caused by https://github.com/nim-lang/Nim/pull/12485)

This was painful to track down, we should improve debug-ability of nim vm; I used `-d:nimVMDebug` for that but `-d:nimVMDebug` should be further improved
* make it easy to track lifetime of a given register
* improve the listing from `-d:nimVMDebug` by showing more contextual information

## CI failure unrelated
=> flaky https://github.com/timotheecour/Nim/issues/352

## future work
- [ ] check a few other suspicious `freeTemp` from https://github.com/nim-lang/Nim/pull/12485
 see also: https://github.com/nim-lang/Nim/pull/15705#issuecomment-716104694 (some `dest` registers being freed) 
* allow configuring `HighRegisterPressure = 40`; will allow for eg lowering it to find more bugs easily, or increasing it for temporary workarounds when there's a similar bug; at least useful for debugging (it was for me in this PR)

### CODE REVIEW

**Comment by Araq** [comment]
This needs to be backported all the way down to 1.0.x, @narimiran

**Comment by timotheecour** [comment]
PTAL:
* also fixed `nkCheckedFieldExpr`
* that's the only 2 `freeTemp` I could find that seemed definitely wrong from https://github.com/nim-lang/Nim/pull/12485

can you explain the added `c.freeTemp(dest)` in `genBinaryStmtVar, genBinaryStmt, genAsgn, nkDerefExpr` etc ?

**Comment by Araq** [comment]
> can you explain the added c.freeTemp(dest) in genBinaryStmtVar, genBinaryStmt, genAsgn, nkDerefExpr etc ?

Not anymore but I did review the entire VM codegen looking for register allocator leaks. Apparently my work wasn't good enough. ;-)

File: lib/system.nim [hunk 1]
```diff
@@ -2106,7 +2106,7 @@ const
     ## is the minor number of Nim's version.
     ## Odd for devel, even for releases.
 
-  NimPatch* {.intdefine.}: int = 1
+  NimPatch* {.intdefine.}: int = 3
```
Comment (Araq) [inline lib/system.nim]: What the heck? That should not be part of this PR!

Comment (Araq) [inline lib/system.nim]:
```suggestion
  NimPatch* {.intdefine.}: int = 1
```

**Comment by Araq** [comment]
Sorry, I took over a bit as we want to release 1.2.8 this morning. :-)

File: lib/system.nim (hunk 1 above)
Comment (timotheecour) [reply lib/system.nim]: that was so code could branch on this bugfix, as explained in https://github.com/nim-lang/Nim/pull/14124#issuecomment-619520051 and it was useful in some PR's to branch on that.

It also makes `nim -v` a little more helpful to show, instead of just a hash + fixed 1.5.1 it shows hash + 1.5.x so it's immediately clearer in bug reports how recent was the nim version used.

Finally, it makes pre-releases / nightly builds easier to distinguish via `nim -v`

I'm not aware of negative consequences in bumping NimPatch, it's a common practice to bump patch on bug fixes. I'm not suggesting to do it on each commit (nim isn't following standard semver anyways), but bumping patch somewhat regularly between 2 stable releases is IMO a good thing.

**Comment by timotheecour** [comment]
> Sorry, I took over a bit as we want to release 1.2.8 this morning. :-)

no problem. too bad https://github.com/nim-lang/Nim/pull/15724 couldn't make the cut for 1.2.8
