### PR TITLE
fix #15623

### LINKED ISSUE #15623: gcc error "invalid use of void expression" from (mis)use of nil
### Example
```nim
when defined(direct):
  echo cast[ptr int](nil)[]

when defined(indirect):
  var x: ref int = nil
  echo cast[ptr int](x)[]
```

### Current Output -d:indirect
```
Traceback (most recent call last)
/home/jfondren/nim/learn/error1.nim(6) error1
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Current Output -d:direct
```
/home/jfondren/.cache/nim/error1_d/@merror1.nim.c: In function ‘NimMainModule’:
/home/jfondren/.cache/nim/error1_d/@merror1.nim.c:152:24: error: invalid use of void expression
  152 |  T1_[0] = nimIntToStr((*NIM_NIL));
      |                       ~^~~~~~~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/jfondren/.choosenim/toolchains/nim-1.4.0/lib -I/home/jfondren/nim/learn -o /home/jfondren/.cache/nim/error1_d/@merror1.nim.c.o /home/jfondren/.cache/nim/error1_d/@merror1.nim.c' failed with exit code: 1
```

### Additional Information
This isn't a blocker to anything. This is my riffing off someone's `nil[]` joke from IRC.
```
$ nim -v
Nim Compiler Version 1.4.0 [Linux: amd64]
Compiled at 2020-10-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: bdcd87afca238a0a7b2c70971827cf9172817b12
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
After this PR. `const expr` doesn't fold `cast[pointer](nil)` into `nil` anymore which will cause problem in c codegen.
```nim
const a = cast[pointer](nil)
```
For example `cast[ptr int](nil)[]` generates `(*NIM_NIL)`

Because VM doesn't support cast nil to pointer, it will cause the same errors as static expr: `VM does not support 'cast' from tyNil to tyPointer`.

```nim
static:
  let a = cast[pointer](nil)
```
If this PR is merged, maybe we could support cast nil to pointer in VM like this
```nim
  elif src.kind == tyNil:
    if dest < 0: dest = c.getTemp(n[0].typ)
    genLit(c, n[1], dest)
```
See PR #16009

### CODE REVIEW

**Comment by cooldome** [comment]
More of general discussion to every one.

Do we want this code to compile:
```nim
echo cast[ptr int](nil)[]
```
Or at compile time Nim can say,  error: this is null dereference, fix you code. 
I would say: `cast[ptr int](nil)` should compile, but `cast[ptr int](nil)[]`  shouldn't. Our semfold/vm should highlight the problem at compile time.

Other opinions? what are the benefits of making it to compile?

**Comment by cooldome** [comment]
I like the PR, but I don't like that in a new test the nil pointers get dereferenced. Could you please test new functionality in another way.

**Comment by ringabout** [comment]
> I like the PR, but I don't like that in a new test the nil pointers get dereferenced. Could you please test new functionality in another way.

I don't understand what I should do. Could you give me some hints?

File: lib/posix/posix_linux_amd64_consts.nim [hunk 1]
```diff
@@ -365,7 +365,7 @@ const SCHED_RR* = cint(2)
 const SCHED_OTHER* = cint(0)
 
 # <semaphore.h>
-const SEM_FAILED* = cast[pointer]((nil))
+const SEM_FAILED* = nil
```
Comment (ringabout) [inline lib/posix/posix_linux_amd64_consts.nim:368]:
```suggestion
const SEM_FAILED* = cast[pointer]((nil))
```
This change could be reverted since #16012 is merged. But CI is boken now, I will process it later.(I think they are the same.)

**Comment by Araq** [comment]
> Other opinions? what are the benefits of making it to compile?

I sometimes use it as an idiom to make my debugger trap but I don't mind if it doesn't compile anymore, there are other idioms I can use.

**Comment by cooldome** [comment]
This would work as a test:
```nim
block:
  echo cast[int](cast[ptr int](nil))

block:
  var x: ref int = nil
  echo cast[int](cast[ptr int](x))
```

**Comment by ringabout** [comment]
These tests also work before this PR in C backend. I will add it to tests.

**Comment by cooldome** [comment]
Please combine two PRs into one that works. Had to revert due to failing tests

**Comment by timotheecour** [comment]
> Do we want this code to compile:
> echo cast[ptr int](nil)[]

out of scope for this PR IMO, and special casing this may not be worth it, at least by default; but the existing `--staticboundchecks` or a similar `--staticChecks:on` could detect this and give CT error (perhaps under more general conditions)
