### PR TITLE
fixes #3498

### LINKED ISSUE #3498: Generic arguments cannot be used in templates (raising undeclared identifier)
Currently there is no way to use generic arguments in templates, as if their identifiers were not replaced by their generic argument values during template evaluation.

```nim
template defaultInt(t: int): expr = (var d: int; d)
template defaultFor[T](t: T): expr = (var d: T; d)

echo defaultInt(1) #<- expected 0
echo defaultFor(1) #<- expected 0, but got Error: undeclared identifier: 'T'
```

### PR DESCRIPTION
**Pull request by nanoant**
Previously it was not possible to use template arguments in template body as
the symbols were not resolved correctly leading to Error: undeclared
identifier: 'XX', eg.:

   template defaultOf[T](t: T): expr = (var d: T; d)
   echo defaultOf(1) #<- invalid identifier, but should output 0

### CODE REVIEW

File: compiler/semtempl.nim [hunk 1]
```diff
@@ -228,7 +228,7 @@ proc semTemplSymbol(c: PContext, n: PNode, s: PSym): PNode =
   of skParam:
     result = n
   of skType:
-    if (s.typ != nil) and (s.typ.kind != tyGenericParam):
+    if (s.typ != nil) and (s.typ.kind == tyGenericParam):
```
Comment (Araq) [inline compiler/semtempl.nim]: This wasn't a typo. If it works differently now, remove the 'if' altogether.
