### PR TITLE
test case for #9180 and re-enables the disabled tcompilerapi test

### LINKED ISSUE #9180: compiler/nimeval can't be used twice: fails 2nd time with: `Error: internal error: n is not nil`
/cc @Araq 
env var nimc_D points to compile git repo

```nim
import compiler / [ast, vmdef, vm, nimeval, llstream]
from os import getEnv
proc evalString(code: string, moduleName = "script.nim"):auto=
  let stream = llStreamOpen(code)
  defer: llStreamClose(stream)
  let path = getEnv("nimc_D") & "/lib/"
  var intr = createInterpreter(moduleName, [path])
  defer: destroyInterpreter(intr)
  intr.evalScript(stream)

evalString("echo 1")
evalString("echo 2")
```

```
rnim bugs/nimeval/t03_n_is_not_nil.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r bugs/nimeval/t03_n_is_not_nil.nim
1
???(0, 0) Error: internal error: n is not nil
Traceback (most recent call last)
/Users/timothee/git_clone/nim/timn/bugs/nimeval/t03_n_is_not_nil.nim(13) t03_n_is_not_nil
/Users/timothee/git_clone/nim/timn/bugs/nimeval/t03_n_is_not_nil.nim(8) evalString
/Users/timothee/.nimble/pkgs/compiler-0.19.0/compiler/nimeval.nim(115) createInterpreter
/Users/timothee/.nimble/pkgs/compiler-0.19.0/compiler/modules.nim(107) compileSystemModule
/Users/timothee/.nimble/pkgs/compiler-0.19.0/compiler/modules.nim(71) compileModule
/Users/timothee/.nimble/pkgs/compiler-0.19.0/compiler/passes.nim(220) processModule
/Users/timothee/.nimble/pkgs/compiler-0.19.0/compiler/passes.nim(95) closePasses
/Users/timothee/.nimble/pkgs/compiler-0.19.0/compiler/sem.nim(626) myClose
/Users/timothee/.nimble/pkgs/compiler-0.19.0/compiler/msgs.nim(524) internalError
/Users/timothee/.nimble/pkgs/compiler-0.19.0/compiler/msgs.nim(495) liMessage
/Users/timothee/.nimble/pkgs/compiler-0.19.0/compiler/msgs.nim(324) handleError
/Users/timothee/.nimble/pkgs/compiler-0.19.0/compiler/msgs.nim(314) quit
Error: execution of an external program failed: '/tmp/nim//app '

```

**EDIT**
/cc @alaviss 
looks suspiciously similar to [1] which was fixed by @alaviss 

[1] running runNimScript on 2 subsequent nims files causes "Error: internal error: n is not nil" #8235

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @araq
* fix #9180
* enables tcompilerapi test which was effectively disabled:
"effectively disable this test as 'nim' is not in the PATH so tcompilerapi cannot find Nim's standard library"
* add `findNimStdLibCompileTime`
* add test case for #9180

~~Note: https://github.com/nim-lang/Nim/issues/9184 is still an issue after this PR (no change before / after this PR regarding that issue)~~

### CODE REVIEW

**Comment by alaviss** [comment]
Instead of implementing more workaround, could you try to solve the root of this issue? https://github.com/nim-lang/Nim/issues/9068

**Comment by timotheecour** [comment]
> Instead of implementing more workaround, could you try to solve the root of this issue? #9068

can be done in a subsequent PR by me or someone else. I prefer incremental progress to no progress ;-)

**Comment by dom96** [comment]
I think this would have been much better as two PRs.

**Comment by timotheecour** [comment]
@dom96 would u accept:
* 1 PR that adds `findNimStdLibCompileTime` and enables tcompilerapi test which was effectively disabled

* 1 PR that does the rest as mentioned here

**Comment by dom96** [comment]
You might as well keep it as-is now, since you've already created it. In the future consider creating two PRs.

As far as accepting this: that's @Araq's turf.

File: tests/compilerapi/tcompilerapi.nim [hunk 1]
```diff
@@ -28,27 +27,28 @@ proc main() =
...
-  # cannot find Nim's standard library:
-  echo "top level statements are executed!"
-  echo "2.0"
-  echo "my secret"
-else:
-  main()
+main()
+
+block issue9180:
+  proc evalString(code: string, moduleName = "script.nim"):auto=
```
Comment (Araq) [inline tests/compilerapi/tcompilerapi.nim]: Write ``=`` here, don't use ``auto``.

File: tests/compilerapi/tcompilerapi.nim [hunk 2]
```diff
@@ -28,27 +27,28 @@ proc main() =
...
+    let stream = llStreamOpen(code)
+    defer: llStreamClose(stream)
```
Comment (Araq) [inline tests/compilerapi/tcompilerapi.nim]: Don't use ``defer``.

File: tests/compilerapi/tcompilerapi.nim [hunk 3]
```diff
@@ -28,27 +27,28 @@ proc main() =
...
+    let std = findNimStdLibCompileTime()
+    var intr = createInterpreter(moduleName, [std])
+    defer: destroyInterpreter(intr)
```
Comment (Araq) [inline tests/compilerapi/tcompilerapi.nim]: Don't use ``defer``.

File: tests/compilerapi/tcompilerapi.nim (hunk 1 above)
Comment (timotheecour) [reply tests/compilerapi/tcompilerapi.nim]: done

File: tests/compilerapi/tcompilerapi.nim (hunk 3 above)
Comment (timotheecour) [reply tests/compilerapi/tcompilerapi.nim]: done (ditto)

File: tests/compilerapi/tcompilerapi.nim (hunk 2 above)
Comment (timotheecour) [reply tests/compilerapi/tcompilerapi.nim]: done to move forward with this PR although I (and others) think defer is preferable, see https://forum.nim-lang.org/t/4022#25111

**Comment by timotheecour** [comment]
PTAL

**Comment by timotheecour** [comment]
@alaviss
> Instead of implementing more workaround, could you try to solve the root of this issue? #9068

issue still there even after #9068 was fixed; this PR should fix this issue.

**Comment by timotheecour** [comment]
PTAL: rebased PR after removing the 1st commit that added workaround for #9068 now that it was fixed in https://github.com/nim-lang/Nim/pull/9259
