### PR TITLE
fixes #22753; Nimsuggest segfault with invalid assignment to table (#22781)

### LINKED ISSUE #22753: Nimsuggest segfault with invalid assignment to table
### Description

Examples below show code that segfaults nimsuggest during `track` in sempass2. Not sure the second case is minimal, but haven't been able to get it smaller yet. Either way both are very disruptive during actual usage of nimsuggest, vscode extension gives up completely and must be restarted.

A real location that also causes the crash in nimsuggest can be found in `compiler/semstmts.nim` which causes a crash at this location [semstmts.nim](https://github.com/nim-lang/Nim/blob/devel/compiler/semstmts.nim#L57), but reducing that seems pretty tough.

Immutable case:
```nim
import std/tables
proc myProc(x: Table[int, int]) =
  x[0] = 0
```

Mutable case:
```nim
import std/tables

type
  OuterType = object
    inner: InnerType

  InnerType = object
    table: Table[int, int]

proc myProc(self: var OuterType) =
  self.inner.table[0] = self.inner
```

### Nim Version

Tested 1.6.14 and latest devel 1b0447c208a8ec03c1abf5c511b3949a882a8996

### Current Output

```text
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

```text
Reports an error/works
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by nickysn**
fixes #22753

## Future work
We should turn all the error nodes into nodes of a nkError kind, which could be a industrious task. But perhaps we can add a special treatment for error nodes to make the transition smooth.

(cherry picked from commit 642ac0c1c31063ae966d8448c64c539203432e94)

### CODE REVIEW

File: tests/generics/tuninstantiated_failure.nim [hunk 1]
```diff
@@ -11,6 +11,6 @@ func `[]`[T, K](x: var Test[T, K], idx: int): var Test[T, K] =
   x
 
 var b: Something
-# Should give a type-mismatch since Something isn't a valid Test
+# Should give an error since Something isn't a valid Test
 b[0].name = "Test" #[tt.Error
-            ^  type mismatch]#
+ ^  expression '' has no type (or is ambiguous)]#
```
Comment (Araq) [inline tests/generics/tuninstantiated_failure.nim:16]: But this error message is now worse!
