### PR TITLE
opensym as node kind + fixed experimental switch

### LINKED ISSUE #23385: Add compile-time symbol for `genericsOpenSym`
### Summary

Add a `nimGenericsOpenSym` injected define when `genericsOpenSym` is enabled

### Description

This is needed to write code that reacts to the experimental feature being enabled, in when expressions so that it can use workarounds when the feature is not enabled.

### Alternatives

_No response_

### Examples

_No response_

### Backwards Compatibility

_No response_

### Links

_No response_

### LINKED ISSUE #23386: `genericsOpenSym` not respecting injections across modules
### Description

Followup on https://github.com/nim-lang/Nim/pull/23091/

This is the same test as https://github.com/nim-lang/Nim/blob/94c599687796f4ee3872c8aa866827b9ed33f52b/tests/generics/tmacroinjectedsym.nim#L100 but split up over two modules:

testit.nim:

```nim
{.experimental: "genericsOpenSym".}

type
  Result*[T, E] = object
    when T is void:
      when E is void:
        oResultPrivate*: bool
      else:
        case oResultPrivate*: bool
        of false:
          eResultPrivate*: E
        of true:
          discard
    else:
      when E is void:
        case oResultPrivate*: bool
        of false:
          discard
        of true:
          vResultPrivate*: T
      else:
        case oResultPrivate*: bool
        of false:
          eResultPrivate*: E
        of true:
          vResultPrivate*: T

template valueOr*[T: not void, E](self: Result[T, E], def: untyped): untyped =
  let s = (self) # TODO avoid copy
  case s.oResultPrivate
  of true:
    s.vResultPrivate
  of false:
    when E isnot void:
      template error: untyped {.used, inject.} = s.eResultPrivate
    def
```

testit2.nim:

```nim
import testit

type Xxx = enum
  error
  value

proc f(): Result[int, cstring] =
  Result[int, cstring](oResultPrivate: false, eResultPrivate: "f")

proc g(T: type): string =
  let x = f().valueOr:
    return $error

  "ok"

doAssert g(int) == "f"
```

```
Error: unhandled exception: /tmp/testit2.nim(16, 1) `g(int) == "f"`  [AssertionDefect]
```

The local symbol in testit2 gets precedence over the injected symbol from testit, even though the injected symbol as a more local scope than the Xxx enum.

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-02-20
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 773c066634d831a968bb464eab35b25a00026525

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
refs https://github.com/nim-lang/Nim/pull/23873#discussion_r1687995060, fixes #23386, fixes #23385, supersedes #23572

Turns the `nfOpenSym` node flag implemented in #23091 and extended in #23102 and #23873, into a node kind `nkOpenSym` that forms a unary node containing either `nkSym` or `nkOpenSymChoice`. Since this affects macros working on generic proc AST, the node kind is now only generated when the experimental switch `genericsOpenSym` is enabled, and a new node flag `nfDisabledOpenSym` is set to the `nkSym` or `nkOpenSymChoice` when the switch is not enabled so that we can give a warning.

Now that the experimental switch has more reasonable semantics, we define `nimHasGenericsOpenSym2`.

### CODE REVIEW

**Comment by metagn** [comment]
Seems to work, but until packages can handle it (macros just need simple skips AFAIK) or until regressions not detected in CI are fixed the node probably shouldn't be generated without the experimental switch enabled. So for the warning we probably need something like #23572, swapping out the existing node flag with one that only exists for a warning and is temporary. I'll do it in this PR if there are no objections, the other PR is out of date already.

**Comment by Araq** [comment]
> swapping out the existing node flag with one that only exists for a warning and is temporary. I'll do it in this PR if there are no objections, the other PR is out of date already.

Fine with me.

**Comment by Araq** [comment]
Please rebase.

**Comment by metagn** [comment]
Done

File: compiler/condsyms.nim [hunk 1]
```diff
@@ -166,4 +166,5 @@ proc initDefines*(symbols: StringTableRef) =
   defineSymbol("nimHasWarnStdPrefix")
 
   defineSymbol("nimHasVtables")
+  defineSymbol("nimHasGenericsOpenSym")
```
Comment (arnetheduck) [inline compiler/condsyms.nim]: shouldn't this be defined only when the experimental is on?

Comment (metagn) [reply compiler/condsyms.nim]: The nimHas defines usually signal that the experimental switch is available, checking if it's enabled is trickier since it can change depending on the context with `push experimental` etc. #23933 was opened recently related to this

**Comment by arnetheduck** [comment]
not sure it's intended, but compiling this branch (3fe15eb1616d0eeef29f06f3dd60c24de7265676) results in lots of warnings:

```
....
/home/arnetheduck/src/Nim/compiler/ic/cbackend.nim(106, 31) template/generic instantiation of `==` from here
/home/arnetheduck/src/Nim/lib/system/comparisons.nim(324, 16) Warning: a new symbol 'true' has been injected during instantiation of ==, however 'true' [enumField declared in /home/arnetheduck/src/Nim/lib/system/basic_types.nim(46, 16)] captured at the proc declaration will be used instead; either enable --experimental:genericsOpenSym to use the injected symbol or `bind` this captured symbol explicitly [GenericsIgnoredInjection]
.
/home/arnetheduck/src/Nim/compiler/ic/integrity.nim(46, 24) template/generic instantiation of `containsOrIncl` from here
/home/arnetheduck/src/Nim/lib/pure/collections/setimpl.nim(59, 17) Warning: a new symbol 'defaultInitialSize' has been injected during instantiation of containsOrIncl, however 'defaultInitialSize' [const declared in /home/arnetheduck/src/Nim/lib/pure/collections/sets.nim(89, 3)] captured at the proc declaration will be used instead; either enable --experimental:genericsOpenSym to use the injected symbol or `bind` this captured symbol explicitly [GenericsIgnoredInjection]
/home/arnetheduck/src/Nim/compiler/ic/integrity.nim(46, 24) template/generic instantiation of `containsOrIncl` from here
/home/arnetheduck/src/Nim/lib/pure/collections/setimpl.nim(67, 14) template/generic instantiation of `enlarge` from here
/home/arnetheduck/src/Nim/lib/pure/collections/setimpl.nim(43, 16) template/generic instantiation of `rawInsert` from here
/home/arnetheduck/src/Nim/lib/pure/collections/setimpl.nim(28, 17) Warning: a new symbol 'defaultInitialSize' has been injected during instantiation of rawInsert, however 'defaultInitialSize' [const declared in /home/arnetheduck/src/Nim/lib/pure/collections/sets.nim(89, 3)] captured at the proc declaration will be used instead; either enable --experimental:genericsOpenSym to use the injected symbol or `bind` this captured symbol explicitly [GenericsIgnoredInjection]
.
/home/arnetheduck/src/Nim/compiler/ic/navigator.nim(96, 26) template/generic instantiation of `containsOrIncl` from here
/home/arnetheduck/src/Nim/lib/pure/collections/setimpl.nim(59, 17) Warning: a new symbol 'defaultInitialSize' has been injected during instantiation of containsOrIncl, however 'defaultInitialSize' [const declared in /home/arnetheduck/src/Nim/lib/pure/collections/sets.nim(89, 3)] captured at the proc declaration will be used instead; either enable --experimental:genericsOpenSym to use the injected symbol or `bind` this captured symbol explicitly [GenericsIgnoredInjection]

```

**Comment by arnetheduck** [comment]
testing this, the semantics of `push experimental` are quite weird:

Neither of these two work at top-level - the `when` condition is basically to allow `-d:resultsGenericsOpenSym` to enable the experimental feature for results only.

```nim
when condition:
  {.experimental: "genericsOpenSym".}
  {.push experimental: "genericsOpenSym".}
```

However, in a situation analogous to the following, the push covers both a and b, even though the push is only inside a:
```nim
template a =
  when condition:
    {.push experimental: "genericsOpenSym".}

template b = 
  template injector = discard # this works now
```

It's kind of weird that inside a template scope, pushing extends to other unrelated templates but not outside..

File: compiler/condsyms.nim (hunk 1 above)
Comment (arnetheduck) [reply compiler/condsyms.nim]: turns out `nimHasGenericsOpenSym` is already declared, but for the broken version shipped in 2.0.8:

- https://github.com/nim-lang/Nim/blob/v2.0.8/compiler/condsyms.nim#L103
- https://github.com/nim-lang/Nim/blob/v2.0.8/compiler/options.nim#L224

will need a new name for this new, working version :tada:

Comment (arnetheduck) [reply compiler/condsyms.nim]: `nimHasGenericsOpenSym2`?

**Comment by metagn** [comment]
> not sure it's intended, but compiling this branch (3fe15eb) results in lots of warnings:

Definitely not, my bad, I moved the warnings to the wrong spot in the code

File: compiler/condsyms.nim (hunk 1 above)
Comment (metagn) [reply compiler/condsyms.nim]: Changed to `nimHasGenericsOpenSym2`

**Comment by arnetheduck** [comment]
https://github.com/arnetheduck/nim-results/pull/35 updated to work with this branch - also includes an ugly emulation hack for Nim versions that don't have this feature..
