### PR TITLE
fix array/set/tuple literals with generic expression elements

### LINKED ISSUE #24484: Set construction syntax no longer works for generic parameter
### Description

The following two cases work up to 2.0.12 but fail since 2.2.0:
```nim
type E = enum A
proc foo[T](t: set[T] = {T.A}) =
  discard
foo[E]()

proc bar[T](t: set[T] = {T(0)}) =
  discard
bar[uint8]()
```

### Nim Version

Tested with choosenim versions 2.0.12, 2.2.0, and devel git hash: 5340005869d513e5c6af06e5d963bcb77abb3fa3

### Current Output

```text
Error: ordinal type expected; given: typeof(T.A)
Error: type mismatch: got 'typeof(T.A)' for 'T.A' but expected 'range 0..65535(int)'
Error: ordinal type expected; given: typeof(T(0))
Error: type mismatch: got 'typeof(T(0))' for 'T(0)' but expected 'range 0..65535(int)'
```

### Expected Output

_No response_

### Known Workarounds

 A workaround:
```nim
template Tset(T: typedesc): untyped =
  {T(0)}

proc bar2[T](t: set[T] = Tset(T)) =
  discard
bar2[E]()
```

### Additional Information

_No response_

### LINKED ISSUE #24672: Nim v2.2.0 and v2.2.2: Compilation Error When Using Template Parameter in Default Argument for Array/Sequence
### Description

I had a project that was compiling fine in v2.0.0.
I upgraded to v.2.2.0 and the compiler would segfault with:

```
Error: internal error: invalid kind for floatRangeCheck:tyGenericParam                                                                                                                      
SIGSEGV: Illegal storage access. (Attempt to read from nil?
```

I upgraded to v.2.2.2 and now get this :
```
Error: type mismatch:
 got 'typeof(T.high)' for 'T.high' [fromExpr]
 but expected 'typeof(T.high)' [fromExpr]
```

I was able to construct an example:
```Nim
func initArray[T](arg: array[1, T] = [T.high]): array[1, T] =
  return arg

echo initArray[float]()  # this would compile and print [inf] in previous versions.
```

This bug at least affects arrays and seq's, however this still works:
```Nim
func initValue[T](arg: T = T.high): T =
  return arg

echo initValue[float]()  # this compiles and prints inf.
```

Also note that things like `100.0.T` will not compile but a default value of just `100.0` will compile.

### Nim Version

v2.0.0 works

v2.2.0 and v2.2.2 do not work

### Current Output

```text
Error: type mismatch:
 got 'typeof(T.high)' for 'T.high' [fromExpr]
 but expected 'typeof(T.high)' [fromExpr]
```

### Expected Output

```text
[inf]
```

### Known Workarounds

_No response_

### Additional Information

Compiled on Linux with GCC using the C or C++ backends and ORC.

### PR DESCRIPTION
**Pull request by metagn**
fixes #24484, fixes #24672

When an array, set or tuple constructor has an element that resolves to `tyFromExpr`, the type of the entire literal is now set to `tyFromExpr` and the subsequent elements are not matched to any type.

The remaining expressions are still typed (a version of the PR before this called `semGenericStmt` on them instead), however elements with int literal types have their types set to `nil`, since generic instantiation removes int literal types and the int literal type is required for implicitly converting the int literal element to the set type. Tuples should not really need this but it is done for them anyway in case it messes up some type inference

### CODE REVIEW

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -3035,6 +3060,11 @@ proc semExport(c: PContext, n: PNode): PNode =
 
 proc semTupleConstr(c: PContext, n: PNode, flags: TExprFlags; expectedType: PType = nil): PNode =
   var tupexp = semTuplePositionsConstr(c, n, flags, expectedType)
+  # convert `tupexp` to typedesc if necessary:
+  if tupexp.typ.kind == tyFromExpr:
+    # tyFromExpr is already ambivalent between types and values
+    result = tupexp
+    return
```
Comment (Araq) [inline compiler/semexprs.nim]:
```suggestion
    return tupexp
```

**Comment by Araq** [comment]
This makes me wonder where else we might have forgotten to handle `tyFromExpr`... And also, what the heck is tyFromExpr? I bet we don't really need it if types where just ASTs...

**Comment by metagn** [comment]
If "instantiating a type/node" was merged into just "semchecking a node" then we could probably do away with the inner node field, making it a nullary `tyUnresolved` or something like that. We would still need to use it during generic semchecking to propagate it. There is also the nuance of it becoming `tyStatic` or just being used for types of expressions (which enables `tfNonConstExpr`).

With this most of the "expression primitive" parts of the compiler propagate it but statements for example like assignments, `if` etc still do not (except `when`). In practice these would be moved into helper procs/templates though which would work.

**Comment by metagn** [comment]
Hopefully simplified the PR, it now just sets the type of the full literal to `tyFromExpr` and makes sure int literals don't get their int literal type stripped and fail the conversion during instantiation.
