### PR TITLE
Fix #19038 - making the Nim compiler work again on Windows XP

### LINKED ISSUE #19038: Compiler version 1.6.0 does not work on Windows XP
I have a Windows XP virtual machine on which I run some tests. I decided to test the new version of Nim and it didn't work. I get this error message: "Could not find procedure entry point _putenv_s in dynamic link library msvcrt.dll" (a translation of the message as the message is in Portuguese). The error occurs when trying to run the compiler with a simple `nim -v` or any other command.

Version 1.4.8 works normally.

The commit that caused this problem is this one: [6b3c77e7f4421267c551b1cd84717a19c65be2c5](https://github.com/nim-lang/Nim/commit/6b3c77e7f4421267c551b1cd84717a19c65be2c5).

Should Nim maintain Windows XP compatibility or not?

Edit: The `mbstowcs_s` function is also not supported by Windows XP crt and it is also present in the commit.

### PR DESCRIPTION
**Pull request by rockcavera**
Fix #19038

The changes are:
- use of `_putenv` instead of `_putenv_s`.
- use of `mbstowcs` instead of `mbstowcs_s`.

The so-called "secure" versions are actually not necessary, in my opinion. To learn more about the security of `_s` functions, see [here](https://docs.microsoft.com/en-us/cpp/c-runtime-library/security-features-in-the-crt?view=msvc-170).

I looked in stdlib and the compiler for other "secures" functions for Windows and couldn't find it, other than `_vsnprintf_s` for the `bcc` backend.

So I see no reason not to use `_putenv` and `mbstowcs`, making the Nim compiler functional again on Windows XP. However, this is not to say that Nim passes all tests on that operating system.

### CODE REVIEW

File: lib/pure/includes/osenv.nim [hunk 1]
```diff
@@ -121,7 +121,8 @@ when not defined(nimscript):
         ]#
         if key.len == 0 or '=' in key:
           raise newException(OSError, "invalid key, got: " & key)
-        if c_putenv_s(key, "") != 0'i32: bail
+        let envToDel: cstring = key & "="
```
Comment (Araq) [inline lib/pure/includes/osenv.nim]:
```suggestion
        let envToDel = key & "="
```

File: lib/pure/includes/osenv.nim [hunk 2]
```diff
@@ -121,7 +121,8 @@ when not defined(nimscript):
...
+        if c_putenv(envToDel) != 0'i32: bail
```
Comment (Araq) [inline lib/pure/includes/osenv.nim]:
```suggestion
        if c_putenv(cstring envToDel) != 0'i32: bail
```

File: lib/std/private/win_setenv.nim [hunk 3]
```diff
@@ -30,44 +30,46 @@ else:
...
     const EINVAL = cint(22)
-    const MAX_ENV = 32767
-      # xxx get it from: `var MAX_ENV {.importc: "_MAX_ENV", header:"<stdlib.h>".}: cint`
-    if overwrite == 0 and c_getenv(name) != nil: return 0
-    if value[0] != '\0':
-      let e = c_putenv_s(name, value)
+    let cname = cstring(name)
+    if overwrite == 0 and c_getenv(cname) != nil: return 0
+    if value != "":
+      let cenvstring = cstring(name & "=" & value)
```
Comment (Araq) [inline lib/std/private/win_setenv.nim]: This pattern is bad. With --gc:orc the temporary string is freed "immediately" (at the scope exit, but still). Instead make the `let` the owner of the expression (aka keep it as `string`) and convert it to `cstring` at the callsites.
