### PR TITLE
fix #18334: handle path with spaces on windows during bootstrap

### LINKED ISSUE #18334: Compiler can't handle nimble pkg file paths with spaces (Windows).
When attempting to compile projects located in a file path with spaces and / or dependent on nimble packages installed under file paths with spaces, the compiler will fail to find the folders / files because the paths are getting split along the spaces. i.e:

```C:\Users\Idak Andrew\.nimble\pkgs``` becomes ```C:\Users\Idak``` and ```Andrew\.nimble\pkgs``` before being passed to GCC, neither of which can be found.

This occurs regardless of what directory I cd into. 

```
Nim Compiler Version 1.4.8
```

### PR DESCRIPTION
**Pull request by timotheecour**
fix #18334

refs https://github.com/nim-lang/Nim/pull/17875#issuecomment-829142033
refs https://github.com/nim-lang/Nim/issues/18334#issuecomment-867114536

### CODE REVIEW

File: compiler/nim.nim [hunk 1]
```diff
@@ -7,21 +7,26 @@
...
-  when defined(x86):
-    {.link: "../icons/nim.res".}
-  else:
-    {.link: "../icons/nim_icon.o".}
+import std/[os, strutils, parseopt]
+when defined(windows):
+  const dir = when defined(nimKochBootstrap):
+    # remove workaround pending bootstrap >= 1.5.1
+    # refs https://github.com/nim-lang/Nim/issues/18334#issuecomment-867114536
+    currentSourcePath.parentDir.quoteShell & "\\"
```
Comment (Araq) [inline compiler/nim.nim]: Quoting (`quoteShell`) only a part of the path is bad style. Why not simply:

```nim

when defined(amd64) and defined(windows) and defined(vcc) and not defined(nimKochBootstrap):
  {.link: "../icons/nim-amd64-windows-vcc.res".}
when defined(i386) and defined(windows) and defined(vcc) and not defined(nimKochBootstrap):
  {.link: "../icons/nim-i386-windows-vcc.res".}

```

Comment (timotheecour) [reply compiler/nim.nim]: done;
but i had done it that way to preserve semantics (would be needed anyways if those files were not optional); in future if there's a situation where those are not optional, smthg like this should work:
```nim
template link2(a) =
  const a2 =
    when defined(nimKochBootstrap):
      quoteShell(currentSourcePath.parentDir / a)
    else: a
  {.link: a2.}
```
then use link2 in such places
