### PR TITLE
RST: fix directive with fields (#16490)

### LINKED ISSUE #16490: regression: rst2html broken (eg: manual.html gets truncated to a small part)
see https://nim-lang.github.io/Nim/manual.html vs https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-amp-keywords

the manual in devel now stops at the section `Identifiers & Keywords`

image

image

I'm suspecting this could be due to recent rst PR's

EDIT: indeed, this PR https://github.com/nim-lang/Nim/pull/16438 seems responsible (works right before, fails right after)

### PR DESCRIPTION
**Pull request by a-mr**
After #16438 RST directives with arguments are broken, they may consume all the text after them.

E.g. nim manual is absent after this code-block:
```
.. code-block:: nim
   :file: keywords.txt
```

This is because parseLiteralBlock does not check current indentation, instead it just expects to be started at some place and continue parsing while indentation ≥ initial place. There was the check that indentation is suitable for that after parsing directive arguments, but I removed it in #16438 because the check got in a way for parsing other directives like this:

```
.. note:: Text of section without any arguments.
```

This commit adds another check that works for both cases.

EDIT: fixes #16490

### CODE REVIEW

File: tests/stdlib/trstgen.nim [hunk 1]
```diff
@@ -535,6 +535,17 @@ Test1
     doAssert count(output1, "<ul ") == 1
     doAssert count(output1, "</ul>") == 1
 
+  test "Nim (RST extension) code-block":
+    # check that presence of fields doesn't consume the following text as
+    # its code (whic is a literal block)
```
Comment (timotheecour) [inline tests/stdlib/trstgen.nim]: whic=>which

**Comment by timotheecour** [comment]
PR message must contain "fix #16490" explicitly otherwise this won't auto-close when this PR is merged
(refs: https://nim-lang.github.io/Nim/contributing.html)

File: tests/stdlib/trstgen.nim (hunk 1 above)
Comment (Clyybber) [inline tests/stdlib/trstgen.nim]:
```suggestion
    # its code (which is a literal block)
```
