### PR TITLE
fix #13150 `nim doc --project` now works reliably

### LINKED ISSUE #13150: `nim doc --project` broken with imports below main project file or duplicate names
`nim doc --project` doesn't work when:
* there are relative imports eg `import ".." / utils`
* there are multiple modules in the project with the same basename

### Example
nim doc --index:on --project --outdir:htmldocs /pathto/msub/main.nim

```nim
# /pathto/msub/main.nim:
from ".."/utils as m1 import nil 
from "."/utils as m2 import nil # note: would still be buggy if that clashing module is imported from somewhere else

# /pathto/msub/utils.nim
proc fun1*() = discard
# /pathto/utils.nim
proc fun2*() = discard
```

### Current Output
* depending on which import comes first, (`from "."/utils as m2 import nil` or `from ".."/utils as m1 import nil`), you'll get one module generated or the other (clashing location)
* you'll get a 404 error when clicking on the import `../utils` as the link will be wrong

### Possible Solution
the most robust solution is to flatten the hierarchy in exactly the same way as done for `nim c` 
```
find /tmp/d28/*.c
/tmp/d28/@m..@sthello2.nim.c
/tmp/d28/@mthello2.nim.c
/tmp/d28/@mthello3.nim.c
/tmp/d28/stdlib_io.nim.c
/tmp/d28/stdlib_system.nim.c
```

perhaps the particular mangling scheme can be adapted for urls but idea is identical.

## note
One additional advantage of a flat hierarchy is that we'd be able to use relative instead of absolute href:
```
 href <link rel="stylesheet" type="text/css" href="nimdoc.css"> # instead of `href="/nimdoc.css"`
```
and it would work with both httpserver and open `pathto/main.html`
currently both absolute and relative hrefs would not work depending on situations

### Additional Information
* nim devel 9fc04a555ca0fc9eaff6d4eb9ba47a0a64feb9c2
* https://github.com/nim-lang/Nim/pull/13117 does not fix this, as this is a long pre-existing issue

### PR DESCRIPTION
**Pull request by timotheecour**
* fixes #13150 `nim doc --project` works reliably, in particular with duplicate names and with imports below main project file

* new option: `--docroot`: nim doc --project --docroot:/pathto/mypkg --outdir:htmldocs /pathto/mypkg/sub/main.nim
=> creates: `htmldocs/sub/main.nim` (ie, `outdir / relativePath(srcfile, docroot)`)
* correctly handles duplicate names (implementation uses PSym.nimblePkg since fakePackageName would be wrong); previously, a duplicate package name would be silently ignored
* `..` gets transformed to `@@` and it all works including in hrefs; turns out skipping files in case they're starting with `..` is tricky / undesirable

## semi-related or unrelated changes
* removed dead code `resetPackageCache`
* removed unused import nimconf
* added `lazyPaths` to `nim dump`
* added `getNimbleFile*(conf: ConfigRef; path: string)` to return path to nimble file corresponding to an input file
  => used to get doc files relative to this for `--docroot:@pkg`
* added `proc getRelativePathFromConfigPath*(conf: ConfigRef; f: AbsoluteFile): RelativeFile`
`getRelativePathFromConfigPath(conf, "/pathto/foo/bar/bar.nim")` returns `"bar/bar.nim"` if `/pathto/foo` is in the `nim --path`
  => used to get doc files relative to this for `--docroot:@path`
* [EDIT] compiler docs now under compiler/, eg: https://nim-lang.github.io/Nim/vmgen.html => https://nim-lang.github.io/Nim/compiler/vmgen.html
[EDIT]: note: this is desirable because otherwise name modules do clash, eg: pure/options vs compiler/options

### CODE REVIEW

File: compiler/ast.nim [hunk 1]
```diff
@@ -823,6 +823,7 @@ type
       # check for the owner when touching 'usedGenerics'.
       usedGenerics*: seq[PInstantiation]
       tab*: TStrTable         # interface table for modules
+      nimblePkg*: PSym
```
Comment (Araq) [inline compiler/ast.nim]: No. We lived without it for a long time so I'm sure it's unnecessary.

Comment (timotheecour) [reply compiler/ast.nim]: done, found another way without introducing this field

**Comment by timotheecour** [comment]
@araq PTAL (and added a few other improvements)

**Comment by timotheecour** [comment]
ping @Araq

File: compiler/ast.nim [hunk 2]
```diff
@@ -1026,6 +1026,26 @@ const
...
+  while result != nil:
+    case result.kind
+    of skModule:
+      result = result.owner
+      assert result.kind == skPackage
+    of skPackage:
+      if result.owner == nil:
+        break
+      else:
+        result = result.owner
```
Comment (Araq) [inline compiler/ast.nim]: Do we have "packages of packages"? I hope we don't. make this an ``assert result.owner == nil``.

File: doc/advopt.txt [hunk 3]
```diff
@@ -67,6 +67,11 @@ Advanced options:
   --clib:LIBNAME            link an additional C library
                             (you should omit platform-specific extensions)
   --project                 document the whole project (doc2)
+  --docRoot:path            nim doc --docRoot:/foo --project --outdir:docs /foo/sub/main.nim
+                            generates: docs/sub/main.html
+                            if path == @pkg, will use nimble file enclosing dir
+                            if path == @path, will use first matching dir in --path
+                            if these are nonexistant, will use project path
```
Comment (Araq) [inline doc/advopt.txt:76]: Why do we need this? Can't we be smart about the project path and do without this?

Comment (timotheecour) [reply doc/advopt.txt:76]: short answer: I've now added a new smart default for `--docRoot`:
`--docRoot` with no arg now implies `--docRoot:@default` which picks the best match among @path, @pkg (and if these have no match, defaults to project path)

most users should simply use `--docRoot` with no arg.

## long answer
before introducing `@default`, the way I wrote it accomodated all scenarios, which all happen in practice:
* user has a nimble package and no --path => use @pkg; eg: `compiler` nimble package (fallsback to project path if no nimble file found)
* user has (1 or more) --path => use @path, eg: `stdlib` which has `--path:$nim/lib/pure`, `--path:$nim/lib/pure/concurrency` etc  (fallsback to project path if no enclosing --path found)
* user has no nimble package and no path => use provided absolute dir

In all likelihood, @default will be more common for user docs, as I noted in the docs

now that I have @default, I'd be ok to remove @pkg and @path (but keep option for user provided absolute dir) but maybe it's best to keep these as option

**Comment by timotheecour** [comment]
PTAL

**Comment by timotheecour** [comment]
ping

**Comment by Araq** [comment]
Waiting for @mratsim's feedback.

**Comment by mratsim** [comment]
A bit short of time today but for context, the goal is to see if I can replace this horrible doc generation script with the PR: https://github.com/mratsim/Arraymancer/blob/v0.6.0/arraymancer.nimble#L219-L303

**Comment by timotheecour** [comment]
@araq @martsim seems to work fine on ur project with simply a single cmd (after this PR):
```
git clone https://github.com/mratsim/Arraymancer
cd Arraymancer
nim doc --path:src --project --outdir:/tmp/htmldocs --docroot:`pwd`/src --index:on src/arraymancer.nim
```

=> see https://gist.github.com/timotheecour/983d2324bf4f22fb02daf7a57e490354

the hrefs links cross-reference correctly also (no broken links), when opening the html files.
it may need some adjustment for your particular use case (eg for docutils.css href) but that's unrelated to this PR

## note
currently arraymancer's docs are broken:
https://mratsim.github.io/Arraymancer/nnp.nnp_convolution.html
=> clicking on conv gives 404 https://mratsim.github.io/Arraymancer/conv.html
