### PR TITLE
fix #8412

### LINKED ISSUE #8412: rawproc can lead to malformed C code
The following

```nimrod
proc f(): int = 0
let fAddr = f.rawProc
```

errors with

```
/home/.../rawproc_issue.c: In function ‘rawProc_7zz9aU4bO5i8iesSr9cYupQwrawproc_issue’:
/home/.../rawproc_issue.c:70:18: error: request for member ‘ClP_0’ in something not a structure or union
        result = x.ClP_0;
```

Making `f` a closure seems to work though. Probably `rawproc` is supposed to work on closures only?

### PR DESCRIPTION
**Pull request by ringabout**
Ref https://github.com/nim-lang/Nim/pull/16552

fix #8412

After this PR is merged, I will fix the next similar issue: https://github.com/nim-lang/Nim/issues/12311

### CODE REVIEW

File: lib/system.nim [hunk 1]
```diff
@@ -2394,16 +2394,22 @@ when notJSnotNims:
...
     ## useful for interfacing closures with C.
-    {.emit: """
-    `result` = `x`.ClP_0;
-    """.}
+    when T is "closure":
+      {.emit: """
+      `result` = `x`.ClP_0;
+      """.}
+    else:
+      raise newException(ValueError, "Only closure function and iterator are allowed!")
```
Comment (Araq) [inline lib/system.nim]: Please use ``{.error: "...".}`` instead.

File: lib/system.nim [hunk 2]
```diff
@@ -2394,16 +2394,22 @@ when notJSnotNims:
...
     ## useful for interfacing closures with C.
-    {.emit: """
-    `result` = `x`.ClE_0;
-    """.}
+    when T is "closure":
+      {.emit: """
+      `result` = `x`.ClE_0;
+      """.}
+    else:
+      raise newException(ValueError, "Only closure function and iterator are allowed!")
```
Comment (Araq) [inline lib/system.nim]: Same.

File: tests/closure/tclosure.nim [hunk 3]
```diff
@@ -37,6 +37,14 @@ joinable: false
...
 
 
+block:
+  proc f(): int = 0
+  doAssertRaises(ValueError):
+    discard f.rawProc
+
+  doAssertRaises(ValueError):
+    discard f.rawEnv
+
```
Comment (Araq) [inline tests/closure/tclosure.nim]: No need to do any testing for now.
