### PR TITLE
Use openarray of bytes in md5

### LINKED ISSUE #19305: `toMD5` does not work at compile time but documentation claims otherwise
[`md5` docs](https://nim-lang.org/docs/md5.html) says "Note: The procs in this module can be used at compile time.". However, `toMD5` does not work.

### Example
```nim
import md5

static:
  block working:
    doAssert(getMD5("Franz jagt im komplett verwahrlosten Taxi quer durch Bayern") ==
      "a3cca2b2aa1e3b5b3b5aad99a8529074")
    doAssert(getMD5("Frank jagt im komplett verwahrlosten Taxi quer durch Bayern") ==
      "7e716d0e702df0505fc72e2b89467910")
  block failing:
    doAssert($toMD5("") == "d41d8cd98f00b204e9800998ecf8427e")
    discard toMD5("")
```

### Current Output
```
nim/lib/system/memory.nim(21, 5) Error: cannot 'importc' variable at compile time; c_memset
```

### Expected Output
compiles

### Possible Solution

Looking at the code, there is no reason for `md5` to use `cstring`/`pointer` behavior. There is already some use of `openarray` so it's puzzling why it doesn't use `openarray` in place of `cstring`/`pointer` as well, the buffer used is an `array[0..63, uint8]`. Same seems to go for endians/oids/sha1.

### Additional Information

* Documentation added in #16631, can't find any tests for md5 at compile time

```
$ nim -v
Nim Compiler Version 1.6.2
```

### PR DESCRIPTION
**Pull request by metagn**
Closes #19305

### CODE REVIEW

File: lib/pure/md5.nim [hunk 1]
```diff
@@ -34,15 +34,16 @@ type
...
+  padding: array[0..63, uint8] = [
+    0x80'u8, 0, 0, 0, 0, 0, 0, 0,
+    0, 0, 0, 0, 0, 0, 0, 0,
+    0, 0, 0, 0, 0, 0, 0, 0,
+    0, 0, 0, 0, 0, 0, 0, 0,
+    0, 0, 0, 0, 0, 0, 0, 0,
+    0, 0, 0, 0, 0, 0, 0, 0,
+    0, 0, 0, 0, 0, 0, 0, 0,
+    0, 0, 0, 0, 0, 0, 0, 0
+  ]
```
Comment (metagn) [inline lib/pure/md5.nim:46]: Not sure what the best way to format this is

File: lib/pure/md5.nim [hunk 2]
```diff
@@ -97,10 +98,35 @@ proc decode(dest: var openArray[uint8], src: openArray[uint32]) =
     dest[i+3] = uint8(src[j] shr 24 and 0xff'u32)
     inc(i, 4)
 
-proc transform(buffer: pointer, state: var MD5State) =
+template slice(s: string, a, b): openArray[uint8] =
+  when nimvm:
+    var s2 = newSeq[uint8](s.len)
+    for i in 0 ..< s2.len:
+      s2[i] = uint8(s[i])
+    s2
```
Comment (metagn) [inline lib/pure/md5.nim:107]: `toOpenArray` is unimplemented for VM (#15952) and `toOpenArrayByte` for cstring is unimplemented in JS, so here are workarounds

File: lib/pure/md5.nim [hunk 3]
```diff
@@ -237,29 +271,41 @@ proc md5Init*(c: var MD5Context) =
   c.state[3] = 0x10325476'u32
   c.count[0] = 0'u32
   c.count[1] = 0'u32
-  zeroMem(addr(c.buffer), sizeof(MD5Buffer))
+  when false:
```
Comment (metagn) [inline lib/pure/md5.nim]: The `when false`s are because I am not sure if it would be better to just remove the `zeroMem`/`copyMem` versions than special casing them for non-VM non-JS.

File: lib/pure/md5.nim [hunk 4]
```diff
@@ -237,29 +271,41 @@ proc md5Init*(c: var MD5Context) =
...
+  c.count[1] = c.count[1] + (uint32(input.len) shr 29)
   var PartLen = 64 - Index
-  if len >= PartLen:
-    copyMem(addr(c.buffer[Index]), input, PartLen)
-    transform(addr(c.buffer), c.state)
+  if input.len >= PartLen:
+    when false:
+      copyMem(addr(c.buffer[Index]), unsafeAddr(input[0]), PartLen)
+    else:
+      c.buffer[Index .. Index + PartLen - 1] = input.slice(0, PartLen - 1)
```
Comment (metagn) [inline lib/pure/md5.nim]: `[]=` with openarray is pure Nim and [raises RangeDefect](https://github.com/nim-lang/Nim/blob/afa4bc34b41307c6c63e8c7c973afe295e9fedd8/lib/system.nim#L2607) without a compile-time precondition to raise it which means the `raises: []` claim above fails if defects are tracked, as in the CI error, even though this should never raise `RangeDefect` . So the choice is between using `{.cast(raises: []).}` here (or inside `[]=`) or saying `raises: [RangeDefect]`/`raises: [Defect]` above.

File: lib/pure/md5.nim [hunk 5]
```diff
@@ -97,10 +98,62 @@ proc decode(dest: var openArray[uint8], src: openArray[uint32]) =
     dest[i+3] = uint8(src[j] shr 24 and 0xff'u32)
     inc(i, 4)
 
-proc transform(buffer: pointer, state: var MD5State) =
+const openArrayTest = compiles do:
```
Comment (metagn) [inline lib/pure/md5.nim]: I really hate how these end up looking. Don't know if people think it's worth it.

Comment (Araq) [reply lib/pure/md5.nim]: It's not good, we need to do something. The compiler could use its own version of md5.nim so that bootstrapping keeps working (the compiler doesn't need md5.nim at its own compile-time either) and then md5.nim can be written in the one good way that is supported with Nim devel / 1.6.
