### PR TITLE
fix #11854

### LINKED ISSUE #11854: regression: CI failing (texplain.nim)
CI is failing (texplain.nim), making all recently rebased PR's fail since ~ july 26

see https://travis-ci.org/nim-lang/Nim/jobs/565206359 for nim's own CI:
```
FAIL: tests/concepts/texplain.nim C
Test "tests/concepts/texplain.nim" in category "concepts"
Failure: reMsgsDiffer
```

### Additional Information
https://github.com/nim-lang/Nim/commit/ceb1a1b6884b28f3f3f88a4be5663d7f0b1f1155 shows as the 1st red commit; not sure if that commit is the culprit though.

### PR DESCRIPTION
**Pull request by krux02**
fix #11854

### CODE REVIEW

**Comment by mratsim** [comment]
I'm completely flummoxed by this fix

**Comment by krux02** [comment]
@mratsim and I am extremely bothered by tests that test a specific implementation.

File: lib/system/threadlocalstorage.nim [hunk 1]
```diff
@@ -144,12 +144,12 @@ else:
       tv_sec: Time
       tv_nsec: clong
 
-  proc pthread_attr_init(a1: var PthreadAttr) {.
+  proc pthread_attr_init(a1: var Pthread_attr) {.
     importc, header: pthreadh.}
-  proc pthread_attr_setstacksize(a1: var PthreadAttr, a2: int) {.
```
Comment (dom96) [inline lib/system/threadlocalstorage.nim]: Are these changes relevant to the fix?

Comment (krux02) [reply lib/system/threadlocalstorage.nim]: Well, they are relevant. I had compilation failures because of the new enforced style checks. But they are indeed from a different issue.
