### PR TITLE
Remove more usages of unary lt (fixes #6634)

### LINKED ISSUE #6634: Incorrect deprecation error
Call me wrong, but I think this piece of code, shouldn't generate a warning:
```nim
# based of nim-glm's source code:
type
    Vec*[N : static[int]] = object
      arr*: array[N, float32]
    
    Vec2f = Vec[2]
# ...

proc `+`*[N](v,u: Vec[N]): Vec[N] {.inline.} =
    discard
    
# ...

# actual example:

let
    a = Vec2f(arr: [0f, 0f])
    b = Vec2f(arr: [1f, 0f])

    c = a + b # the warning occurs in this line
echo c
```
outputs the following warnings:
```
lib\system.nim(654, 6) Warning: < is deprecated [Deprecated]
lib\system.nim(654, 6) Warning: < is deprecated [Deprecated]
abc.nim(19, 11) template/generic instantiation from here
lib\system.nim(654, 6) Warning: < is deprecated [Deprecated]
abc.nim(19, 11) template/generic instantiation from here
lib\system.nim(654, 6) Warning: < is deprecated [Deprecated]
abc.nim(19, 11) template/generic instantiation from here
lib\system.nim(654, 6) Warning: < is deprecated [Deprecated]
abc.nim(19, 11) template/generic instantiation from here
lib\system.nim(654, 6) Warning: < is deprecated [Deprecated]
abc.nim(19, 11) template/generic instantiation from here
lib\system.nim(654, 6) Warning: < is deprecated [Deprecated]
abc.nim(19, 11) template/generic instantiation from here
lib\system.nim(654, 6) Warning: < is deprecated [Deprecated]
```
But the unary `<` operator is never explicitly used. Maybe it's implicitly called?
I couldn't isolate the bug further, but the problem seems to be related to the generic static integer argument. If I remove it and instead set the array argument count to a fix value, the warning disappears.

### PR DESCRIPTION
**Pull request by bluenote10**

### CODE REVIEW

File: lib/system/debugger.nim [hunk 1]
```diff
@@ -261,7 +261,7 @@ proc genericHash(dest: pointer, mt: PNimType): int =
 proc dbgRegisterWatchpoint(address: pointer, name: cstring,
                            typ: PNimType) {.compilerproc.} =
   let L = watchPointsLen
-  for i in 0.. <L:
+  for i in 0 .. pred(L):
```
Comment (Yardanico) [inline lib/system/debugger.nim]: did you try to use ..< here?

Comment (bluenote10) [reply lib/system/debugger.nim]: I didn't try, but I don't think it will work because `pred` is defined earlier in system.nim (at around line 600), while `..<` comes very late at around line 3400. The includes for `debugger` and `repr` come at around line 3200 so they either have to use `pred` or we need to rearrange things.

Comment (Yardanico) [reply lib/system/debugger.nim]: Ah, sorry then
