### PR TITLE
Fix #10630 - fix broken separators in nim doc

### LINKED ISSUE #10630: `nim doc` uses wrong definition for DirSep on windows, causing all sorts of bugs
`nim doc C:\pathto\main.nim` fails below

the root cause is `nim doc` has wrong definition of `DirSep` on windows (but also other symbols that are redefined for `nim doc`)

C:\pathto\main.nim:
```nim
import os
const a = currentSourcePath
const b = splitFile(a)
const b2 = b.dir / "test5.nim"
static: echo (b:b, DirSep: $DirSep) # will show b.dir as `""` and `DirSep` as `/` instead of `\` on windows

static: doAssert b.dir.len > 0 # this fails
const b3 = readFile b2 # this would also fail

# doesn't matter, just shows an example where nim doc could need b3
runnableExamples:
  # do something with b3 for example
  discard
```

### PR DESCRIPTION
**Pull request by genotrance**
PR #10629 implementation was rejected, this style was agreeable to [Araq](https://irclogs.nim-lang.org/17-07-2019.html#13:32:41).

I have leveraged code from compiler/platform.nim which was more expansive. There are variations though which I have highlighted in comments. Please review.

Note that RISCOS is not in platform.nim.

### CODE REVIEW

File: lib/pure/includes/osseps.nim [hunk 1]
```diff
@@ -1,66 +1,95 @@
...
-  const
-    CurDir* = '.'
-      ## The constant character used by the operating system to refer to the
-      ## current directory.
-      ##
-      ## For example: `'.'` for POSIX or `':'` for the classic Macintosh.
+const
+  CurDir* =
+    when defined(macos): ':'
+    elif defined(genode): '/'
```
Comment (timotheecour) [inline lib/pure/includes/osseps.nim:12]: @araq @genotrance @ehmry is `/` (instead of `.`) for indicating current dir correct for genode ? couldn't find any info on the web regarding that; I'm asking since this change wasn't mentioned in this PR and it looks strange

Comment (ghost) [reply lib/pure/includes/osseps.nim:12]: Yes, I was the one that set it to `/`. I think the reasoning was that without a libc the current working directory can only be `/`.
