### PR TITLE
fix #17260 render `\` properly in nim doc, rst2html

### LINKED ISSUE #17260: nim doc/rst2html renders `\v`, `\\`, etc incorrectly
### Example 1
```nim
##[
foo1 `bar` `v` `\` `\v` `\\`

foo2 ``bar`` ``v`` ``\`` ``\v`` ``\\``
]##
```

### Current Output
1st line incorectly rendered:
image

### Expected Output
image

### Example 2
ditto with rst2html:
```
foo1 `bar` `v` `\` `\v` `\\`

foo2 ``bar`` ``v`` ``\`` ``\v`` ``\\``
```
also renders incorrectly 1st line

### Example 3
```nim
when true:
  ##[
  before (irrelevant comment just to show that the (buggy) error also has incorrect line/col info
  ]##

  ##[

  ==================         ===================================================
    Escape sequence          Meaning
  ==================         ===================================================
    `\"`                     foo1
    `\`                      foo2
  ==================         ===================================================
  ]##
```
gives: t11956b.nim(3, 18) Error: '`' expected
which is wrong for 2 reasons:
* there should be no error
* the error has wrong line/col info

### Additional Information
* 1.5.1 507873be25baa06d7da3c44b0c36d253c850625d
* affects/blocks https://github.com/nim-lang/Nim/pull/17259 which renders the table badly, omitting `\`:
image

/cc @a-mr 

## examples 4

the devel docs are broken: https://nim-lang.github.io/Nim/system.html#addEscapedChar%2Cstring%2Cchar
image

## note:
inline in github:
foo1 `bar` `v` `\` `\v` `\\`

foo2 ``bar`` ``v`` ``\`` ``\v`` ``\\``

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @a-mr 

* fix #17260
* unblocks #17259 and #17258 (/cc @quantimnot)

## before PR:
https://nim-lang.github.io/Nim/system.html#addEscapedChar%2Cstring%2Cchar
image

## after PR:
image

## note 1
the fix for this should not be controversial:
```
`/x` (`/` not followed by a backtick)
`//` (ditto, the `/` is paired)
```

## note 2
the fix for this is more controversial but IMO is the correct approach:
I'm treating this as legal:
```
`/` (`/` followed by a backtick)
```
because:
* it's legal in markdown and is what users will expect (and in fact nim docs already uses it even though, prior to this PR, it didn't render properly, eg see `addEscapedChar` docs)
* nim rst spec technically allows it, although it's vague about it see https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#interpreted-text
> Interpreted text is text that is meant to be related, indexed, linked, summarized, or otherwise processed, but the text itself is typically left alone. Interpreted text is enclosed by single backquote characters:

*  as mentioned in https://github.com/nim-lang/Nim/issues/17260#issuecomment-794468681:
> The RST spec does not cover escaping in interpreted text explicitly but the idea is mostly clear.
> The code role is not really documented about that behavior

* the rst behavior has design flaws / limitations, eg https://github.com/sphinx-doc/sphinx/issues/8396

* this does behave differently from rst2html as noted there

* backticks are rarely needed, eg we can use:
```nim
## see `system.[]=` # no need to render a backtick inside the backtick pair
```
for simpler doc links (https://github.com/nim-lang/RFCs/issues/125) this also shouldn't be a problem:
```nim
## see `system.[]=`_
```

## note 3
for the rare cases where we'll want to show a backtick character in docs (outside of code blocks/runnableExamples where this works fine), eg to distinguish ```case``` from ``` `case` ``` , we should use markdown syntax:
```
foo1 ``` ` ``` # strips leading and trailing space and we end up with a single backtick rendered
foo2 ``` `` ``` # ditto, we end up with 2 backticks
foo2 ```` ``` ```` # ditto, we end up with 3 backticks
```
it's flexible and has saner escaping semantics (just increase the number of surrounding backticks)

## future work
- [ ] (refs https://github.com/nim-lang/Nim/issues/17340#issuecomment-806059316) as mentioned in https://stackoverflow.com/a/66557930/1426932 `\|` inside a table cell should render as `|`, not `\|` (but outside a table cell, it should render as in this PR); I've edited the test to make it pass but in future work we should address this edge case
```
| A1 header    | A2 \| not fooled
| :---         | ----:       |
| C1           | C2 **bold** | ignored |
| D1 `code \|` | D2          | also ignored
| E1 \| text   |
|              | F2 without pipe
not in table
```

there are workarounds until this is addressed, eg:
split the rendered pipe in 2:
```
`x` \| `y`
```
or using a different unicode char for the pipe https://stackoverflow.com/a/43070960/1426932

### CODE REVIEW

**Comment by a-mr** [comment]
I don't understand your vigor for exact replicating Markdown behavior.

Using `code` as the default role is fine. (the fact that python rst2html has [title-reference](https://docutils.sourceforge.io/docs/ref/rst/roles.html#title-reference), which is italic text, as the default role makes little sense to me.) But it means we should be able input backticks there with `` \` ``.

> backticks are rarely needed, eg we can use:

The cases when we need a standalone `\` are much more rare. We can just use double ticks for that rare case:
```
``\``
```

> is what users will expect (and in fact nim docs already uses it even though, prior to this PR, it didn't render properly, eg see addEscapedChar docs)

You are a little cunning here. This bug that you showed was actually introduced in double backtick elimination in d447c0fe3f39114f0913df5804e5f7a3406d6edb , previously it was rendered OK with double backticks.

> unblocks #17259 and #17258 

For the time being you can just use double backticks wherever a backslash is present.

**Comment by Araq** [comment]
> after PR:

What? It's much worse *after* your PR. Why would there be double backslashes? o.O

**Comment by a-mr** [comment]
@Araq 
it's just that @timotheecour stumbled upon a bad example accidentally. The original text was written in this confusing way in 8caf257607e0b76f103155add7849fb934371678 indeed.

The essence of this PR is that after the recent double-backtick elimination any changed markup containing backslashes got broken because backslashes are interpreted differently in single backticks. So @timotheecour tries to hotfix that. Which is also dangerous because there can exist markup in single backticks that relies on old behavior.

**Comment by Araq** [comment]
So undo the commits that use single backticks everywhere.

**Comment by konsumlamm** [comment]
> So undo the commits that use single backticks everywhere.

Why not just undo the changes where it breaks something? That should only be a few changes (most of the time, backticks are used around variable names). IMO it's not worth it to sacrifice using single backticks.

File: lib/packages/docutils/rst.nim [hunk 1]
```diff
@@ -1212,7 +1213,7 @@ proc parseInline(p: var RstParser, father: PRstNode) =
       father.add(n)
     elif isInlineMarkupStart(p, "`"):
       var n = newRstNode(rnInterpretedText)
-      parseUntil(p, n, "`", true)
+      parseUntil(p, n, "`", false) # bug #17260
```
Comment (a-mr) [inline lib/packages/docutils/rst.nim:1257]: This call is also used for parsing references (they will change their type to `rnRef` or `rnHyperLink` in the `parsePostfix` proc). But according to the spec backslash **does** escaping in the references.

**Comment by timotheecour** [comment]
> What? It's much worse after your PR. Why would there be double backslashes? o.O

@araq I don't understand this comment. The double backslashes in the rendered html are correct.
In fact it matches 1.4 docs: https://nim-lang.org/docs/system.html#addEscapedChar%2Cstring%2Cchar
image

There is a double backslash because `addEscapedChar` adds a backslash to something like `\n`, otherwise it'd be indistinguishable from `\n`.
```
replaces \n by \\n # correct: after this PR, as well as in 1.4 docs
replaces n by \n # incorrect: in devel docs
replaces \n by \n # incorrect (following your suggestion of no double backslashes) => nothing replaced
```

whether this should written in the doc comment as
```nim
## replaces `\n` by `\\n` (as enabled by this PR)
or
## replaces ``\n`` by ``\\n`` (as was needed in 1.4 to get the desired html, but still possible after this PR)
```
is a different question, but your suggestion that there should be no double backslashes here is incorrect.

> The original text was written in this confusing way in 8caf257 indeed.

I don't see how the original text (in the rendered html) from 8caf257 was confusing, it conveys exactly what the proc does. This is consistent with other uses in the manual and elsewhere in that `\n` means newline, and `\\n` means backslash followed by `n` (total 2 chars)

File: lib/packages/docutils/rst.nim (hunk 1 above)
Comment (timotheecour) [reply lib/packages/docutils/rst.nim:1257]: can you give me a minimal example (eg nim doc comment or rst sample)?
so i know how to trigger this; then i can probably add a flag to distinguish

Comment (a-mr) [reply lib/packages/docutils/rst.nim:1257]: An example from the spec:


> If the reference text happens to end with angle-bracketed text that is not a URI or hyperlink reference, at least one angle-bracket needs to be backslash-escaped or an escaped space should follow. For example, here are three references to titles describing a tag:
```
See `HTML Element: \<a>`_, `HTML Element: <b\> `_, and
`HTML Element: <c>\ `_.
```

Comment (a-mr) [reply lib/packages/docutils/rst.nim:1257]: However I tried it and it is not working currently anyway.

```
HTML Element: <a>
-----------------

See `HTML Element: \<a>`_
```

So it can be left for future work.

Comment (timotheecour) [reply lib/packages/docutils/rst.nim:1257]: can you create an issue `misc rst` (similar to `misc testament` https://github.com/nim-lang/Nim/issues/16521) as a meta-issue to track things like this?
(scope: to track rst issues that aren't major and dont' require a dedicated issue)
(I could also do it but i think you have the most experience with rst)

Comment (a-mr) [reply lib/packages/docutils/rst.nim:1257]: Good idea. Done: #17340

**Comment by Araq** [comment]
> @Araq I don't understand this comment. The double backslashes in the rendered html are correct.

Ok, ok, I take it back. That doesn't mean that I can review this, I cannot, I have no idea what changed and why.

File: lib/packages/docutils/rst.nim [hunk 2]
```diff
@@ -840,7 +840,8 @@ proc isInlineMarkupEnd(p: RstParser, markup: string): bool =
   if not result: return
   # Rule 4:
   if p.idx > 0:
-    if markup != "``" and prevTok(p).symbol == "\\":
+    # refs bug #17260
+    if markup notin ["``", "`"] and prevTok(p).symbol == "\\":
```
Comment (a-mr) [inline lib/packages/docutils/rst.nim]: Please, no. You are committing a double sin here: spec noncompliance and inability to input `` ` ``. Again, case of a standalone `\` can be covered by
```
``\``
```

**Comment by narimiran** [comment]
The example from the `addEscapedChar` documentation should also be added to `nimdoc/rst1html/source/rst_examples.rst` — once the escaping is fixed, we don't want to have those regressions again.

File: lib/packages/docutils/rst.nim (hunk 2 above)
Comment (timotheecour) [reply lib/packages/docutils/rst.nim]: fixed

**Comment by timotheecour** [comment]
PTAL, I'm now honoring these:
```
``foo`` # double backtick behavior unchanged
`fo\a\\b\`o` # single backtick now renders as: fo\a\\b`o (the backtick is escaped, but not the other backslashes)
```

> The example from the addEscapedChar documentation should also be added to

I've added tests to tests/stdlib/trstgen.nim; before this PR, there were no tests for interpreted text or inline literals

**Review by a-mr — APPROVED** [review]

**Comment by Araq** [comment]
@narimiran's turn.

**Comment by timotheecour** [comment]
ping @narimiran
