### PR TITLE
fix #18077 testament now parses `cmd` properly

### LINKED ISSUE #14343: parseCmdLine doesn't handle quoting correctly (and also prevents passing empty arguments)
parseCmdLine doesn't handle quoting correctly. IMO current behavior, even if "works as designed according to docs" is not uesful and should be replaced by a more intuitive behavior.

### Example 1
```nim
import os, unittest

proc main()=
  # let a = "foo '--nimcache:hi world" # ok
  let a = "foo --nimcache:'hi world'" # BUG
  # let a = "foo --nimcache:\"hi world\"" # ditto
  let s = parseCmdLine(a)
  check s == @["foo", "--nimcache:hi world"]
main()
```

### Current Output
fails

### Expected Output
works

### Example 2
this bug prevents passing empty arguments, eg `--batch:''` or `--nimcache:''` (and is the reason why `--threads: on` "works" by accident but shouldn't)

see ``` # BUG: with initOptParser, `--batch:'' all` interprets `all` as the argument of --batch` ```
(refs https://github.com/nim-lang/Nim/pull/14823/files#diff-0bc1750c146a1dfef2e41e4aa555789f310d35a44d7ee97abd35ef3fd128389bR5530)

### Example 3
root cause of https://github.com/nim-lang/Nim/issues/18077

### Possible Solution

We don't need to reproduce everything the shell does (which is complicated) but at least we should handle quoting correctly. If there is valid use case to keep existing behavior, I suggest we add a new proc, but I doubt there's a valid use case.

### Additional Information

* 5fb40af57ef66618d2003dae1091d80e8f026a1c

### LINKED ISSUE #18077: testament doesn't parse `cmd` properly
### Example
in tests/nimdoc/trunnableexamples.nim, replace:
```
cmd: "nim doc --doccmd:-d:testFooExternal --hints:off $file"
```
with:
```
cmd: "nim doc --doccmd:'-d:testFooExternal --hints:off' --hints:off $file"
```

### Current Output
XDG_CONFIG_HOME= nim r --lib:lib testament/testament.nim r tests/nimdoc/trunnableexamples.nim

```
Failure: reNimcCrash
$ /Users/timothee/.nimble/bin/nim doc '--doccmd:'"'"'-d:testFooExternal' '--hints:off'"'"'' --hints:off tests/nimdoc/trunnableexamples.nim
command line(1, 2) Error: 'on', 'off' or 'list' expected, but 'off'' found
```

### Expected Output
works

### Additional Information
maybe it's the same root cause as https://github.com/nim-lang/Nim/issues/14343, this needs to be checked (EDIT: indeed, it is)

i needed to add --hints:off in another PR to add `nimoutFull: true` so as to add a test case for another bug and ran into this

### PR DESCRIPTION
**Pull request by timotheecour**
fix https://github.com/nim-lang/Nim/issues/18077
this PR avoids using `parseCmdLine` which is buggy (see https://github.com/nim-lang/Nim/issues/14343), and calls startProcess with input cmd directly instead of converting it via `parseCmdLine`

in future work we should still fix https://github.com/nim-lang/Nim/issues/14343, for other reasons

see test: tests/misc/t18077.nim (which would fail before this PR)

## future work
- [x] remove callCCompiler + related code as explained in this PR => https://github.com/nim-lang/Nim/pull/18087

### CODE REVIEW

File: testament/testament.nim [hunk 1]
```diff
@@ -85,7 +85,7 @@ type
     name: string
     cat: Category
     options: string
-    args: seq[string]
+    testArgs: seq[string]
```
Comment (timotheecour) [inline testament/testament.nim:88]: renamed for clarity but can be removed from this PR (harmless)

File: testament/testament.nim [hunk 2]
```diff
@@ -224,9 +223,33 @@ proc callNimCompiler(cmdTemplate, filename, options, nimcache: string,
 
 proc callCCompiler(cmdTemplate, filename, options: string,
                   target: TTarget): TSpec =
-  let c = prepareTestArgs(cmdTemplate, filename, options, nimcache = "", target)
+  let cmd = prepareTestCmd(cmdTemplate, filename, options, nimcache = "", target)
+  doAssert false
+  #[
+  this code hasn't been run in a while, and should be removed which simplifies code
```
Comment (timotheecour) [inline testament/testament.nim:229]: => removal will be done in https://github.com/nim-lang/Nim/pull/18087
