### PR TITLE
fix #15326

### LINKED ISSUE #15326: typed macros break generic proc definitions
### Example
```nim
import macros
macro m(n:typed):auto =
  result = n
proc f[T](x:T):T {.m.}= x
echo f 3
```

### Current Output
```
/Users/jin/Work/npg/mtypedgen.nim(4, 7) Error: illformed AST: [T]
```

### Additional Information

```
$ nim -v
Nim Compiler Version 1.3.5 [MacOSX: amd64]
Compiled at 2020-09-14
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: c38487aa225674f67659c28ce171fd93e2231ad1
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by cooldome**
fix #15326

Allow for sem checking already typed procs.

Changes are a lot smaller than `git diff` shows.

### CODE REVIEW

**Comment by cooldome** [comment]
Please review.  required for https://github.com/nim-lang/Nim/issues/15324

File: compiler/semtypes.nim [hunk 1]
```diff
@@ -2054,72 +2054,80 @@ proc semGenericConstraints(c: PContext, x: PType): PType =
...
     return
   for i in 0..<n.len:
-    var a = n[i]
-    if a.kind != nkIdentDefs: illFormedAst(n, c.config)
-    var def = a[^1]
-    let constraint = a[^2]
-    var typ: PType
+    var a = n[i]    
+    case a.kind    
+    of nkSym: result.addSym(a.sym)
```
Comment (Clyybber) [inline compiler/semtypes.nim:2070]: Won't this duplicate the generic params, if we previously semmed this node?

Comment (cooldome) [reply compiler/semtypes.nim:2070]: No, result is empty and we recreate it here reusing symbols
