### PR TITLE
fix #17456 flaky test tasynchttpserver_transferencoding

### LINKED ISSUE #17456: tasynchttpserver_transferencoding.nim is flaky
see https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/14578/logs/83 from https://github.com/nim-lang/Nim/pull/17209, on osx cpp CI.

the recently added tests/stdlib/tasynchttpserver_transferencoding.nim (from https://github.com/nim-lang/Nim/pull/16678) is flaky (ie, there is a bug)

/cc @vabresto

### Current Output
on: `hostOS: macosx, hostCPU: amd64, int: 8, float: 8, cpuEndian: littleEndian, cwd: /Users/runner/work/1/s`
```
2021-03-22T10:55:48.1058030Z megatest:processing: tests/statictypes/tstackmatrix.nim
2021-03-22T10:55:48.1058430Z (M: 3, N: 3, fp: ...)
2021-03-22T10:55:48.1058830Z megatest:processing: tests/stdlib/concurrency/tatomics.nim
2021-03-22T10:55:48.1059270Z megatest:processing: tests/stdlib/t14139.nim
2021-03-22T10:55:48.1059680Z megatest:processing: tests/stdlib/t7686.nim
2021-03-22T10:55:48.1060090Z megatest:processing: tests/stdlib/t9091.nim
2021-03-22T10:55:48.1060430Z test AObj
2021-03-22T10:55:48.1060810Z megatest:processing: tests/stdlib/tasynchttpserver_transferencoding.nim
2021-03-22T10:55:48.1061510Z tasynchttpserver_transferencoding.nim(48) tasynchttpserver_transferencoding
2021-03-22T10:55:48.1062010Z assertions.nim(68)       failedAssertImpl
2021-03-22T10:55:48.1062380Z assertions.nim(58)       raiseAssert
2021-03-22T10:55:48.1062740Z fatal.nim(53)            sysFatal
2021-03-22T10:55:48.1063250Z Error: unhandled exception: tasynchttpserver_transferencoding.nim(48, 10) `sanity`gensym0`  [AssertionDefect]
2021-03-22T10:55:48.1063580Z 
2021-03-22T10:55:48.1063880Z FAIL: megatest execution failed
2021-03-22T10:56:39.0593650Z [32mPASS: [36mlib/pure/algorithm.nim cpp                                  [34m ( 0.86 sec)[0m
```

### Additional Information
1.5.1 c8dda867f2a2607d4049759d09593a66b1697d02

## links
originally reported in https://github.com/timotheecour/Nim/issues/544
as noted there:
> this means that `handler` was not actually called in this case.
> potential causes:
> * not sure whether it relates to discarded future/callSoon (refs https://github.com/nim-lang/Nim/pull/16678#discussion_r556372528)
> * maybe the timeout `waitFor sleepAsync(10)` isn't enough, but this shouldn't ideally depend on some threshold

### PR DESCRIPTION
**Pull request by vabresto**
fix #17456

Per @timotheecour 's suggestion in #17456 I opted to try to spawn a new process, and handle it that way. This seems cleaner and less error-prone. 

However, this now uses the `AsyncHttpClient`, which does not have support for `Transfer-Encoding`-based requests. My solution for now is to move the server-side check for the `Transfer-Encoding` logic to be above that for `Content-Length`, as the two parameters should not both be present on a well-formatted request, and the `Content-Length` seems to be added to the request quite deeply in the current code. Therefore, it should be acceptable to change the checking order as for well-formatted requests it is indistinguishable, but I think it is a little bit ugly.

Moving forward, a few options are possible:
* Re-write this revised test to use sockets (like the original code was doing). This makes sense because the server-side code shouldn't depend on client-side features, but will require further exploration.
* Add support for Transfer-Encoding to the client, and use that. I don't know how complex this would be, especially since the primary use case for this would be streaming data. It seems like most of the current code assumes one-shot messages, but I may be mistaken.
* Keep this PR aside, and investigate using a single process (although unless I misunderstood something, the Nim docs suggest that `spawn` is a new thread, not a new process, so this may already be acceptable/ideal).
* Use this PR to remove the flaky tests in the meantime (ie. remove the file).

I'd appreciate some feedback/guidance on this before moving further, as well as some runs through CI to confirm that the flakiness has disappeared, as I haven't been able to reproduce the flakiness locally with either this or the previous code.

### CODE REVIEW

**Comment by vabresto** [comment]
Any idea why this error is occurring?
```
2021-05-20T23:52:53.1714760Z CT:megatest:processing: [432] tests/stdlib/tasynchttpserver_transferencoding.nim
2021-05-20T23:52:53.1716070Z ../lib/pure/concurrency/threadpool.nim(22, 10) Error: Threadpool requires --threads:on option.
2021-05-20T23:52:53.1716680Z 
2021-05-20T23:52:53.1717290Z FAIL: megatest compilation failed
```

I've included a `.nim.cfg` file with the right setting.

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 1]
```diff
@@ -1,42 +1,40 @@
...
-  let data = postBegin & input
-  var socket = newSocket()
-  socket.connect("127.0.0.1", server.getPort)
-  socket.send(data)
-  waitFor sleepAsync(10)
-  socket.close()
-  server.close()
+  proc run_server(): void =
+    let server = newAsyncHttpServer()
+    discard server.serve(Port(64123), my_handler)
```
Comment (timotheecour) [inline tests/stdlib/tasynchttpserver_transferencoding.nim]: why hardcode port? refs https://github.com/timotheecour/Nim/issues/534#issuecomment-821904874

File: lib/pure/asynchttpserver.nim [hunk 2]
```diff
@@ -271,21 +271,8 @@ proc processRequest(
         await client.sendStatus("417 Expectation Failed")
```
Comment (timotheecour) [inline lib/pure/asynchttpserver.nim]: add `fix #17456` to PR message so that the issue will auto-close when this PR is merged

**Comment by timotheecour** [comment]
> Keep this PR aside, and investigate using a single process (although unless I misunderstood something, the Nim docs suggest that spawn is a new thread, not a new process, so this may already be acceptable/ideal).

spawn is using a single process, as can be seen via:
```nim
import std/[threadpool,os]
proc fn() = echo getCurrentProcessId()
fn()
spawn fn()
```

File: lib/pure/asynchttpserver.nim (hunk 2 above)
Comment (vabresto) [reply lib/pure/asynchttpserver.nim]: Not sure which PR message you're referring to - I see that you changed the title of this PR; I also added it to the last commit message.

File: tests/stdlib/tasynchttpserver_transferencoding.nim (hunk 1 above)
Comment (vabresto) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: Good catch - sloppy old code. Fixed it.

File: lib/pure/asynchttpserver.nim [hunk 3]
```diff
@@ -271,21 +271,8 @@ proc processRequest(
...
-      if contentLength > server.maxBody:
-        await request.respondError(Http413)
-        return false
-      request.body = await client.recv(contentLength)
-      if request.body.len != contentLength:
-        await request.respond(Http400, "Bad Request. Content-Length does not match actual.")
-        return true
-  elif hasChunkedEncoding(request):
+  # - Check for Transfer-Encoding header
+  if hasChunkedEncoding(request):
```
Comment (vabresto) [inline lib/pure/asynchttpserver.nim]: No one remarked on this in the PR yet, so I wanted to highlight that this reorders the check for the `Transfer-Encoding` header to be before the `Content-Length` header. Both headers should not appear on the same request according to the spec, so this should be fine, but I'd appreciate an explicit approval for this.

Comment (dom96) [reply lib/pure/asynchttpserver.nim]: What's the reason for reordering it? I read your description in the PR but I don't get it. You cannot test transfer encoding with httpclient so what are you doing here?

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 4]
```diff
@@ -1,42 +1,40 @@
...
-    asyncdispatch.callSoon wrapper
+  proc send_request(server: AsyncHttpServer, port: Port): Future[AsyncResponse] {.async.} =
+    let client = newAsyncHttpClient()
+    let headers = newHttpHeaders({"Transfer-Encoding": "chunked"})
+    let  clientResponse = await client.request("http://localhost:" & $port & "/", body=input, headers=headers, httpMethod=HttpPost)
+    server.close()
+    return clientResponse
 
-  let server = newAsyncHttpServer()
-  waitFor runSleepLoop(server)
```
Comment (dom96) [inline tests/stdlib/tasynchttpserver_transferencoding.nim:29]:
```
asyncCheck runSleepLoop(server)
```

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 5]
```diff
@@ -1,42 +1,40 @@
...
+      # requests
+      # doAssert(not request.headers.hasKey("Content-Length"))
       sanity = true
       await request.respond(Http200, "Good")
 
-  proc runSleepLoop(server: AsyncHttpServer) {.async.} = 
-    server.listen(Port(0))
-    proc wrapper() = 
-      waitFor server.acceptRequest(handler)
-    asyncdispatch.callSoon wrapper
```
Comment (dom96) [inline tests/stdlib/tasynchttpserver_transferencoding.nim:26]:
```
await server.acceptRequest(handler)
```

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 6]
```diff
@@ -1,42 +1,40 @@
...
-  proc handler(request: Request) {.async.} =
+  proc my_handler(request: Request) {.async.} =
       doAssert(request.body == expected)
       doAssert(request.headers.hasKey("Transfer-Encoding"))
-      doAssert(not request.headers.hasKey("Content-Length"))
+      # TODO: This assert depends on client-side code, not server-side code
+      # Currently, the Nim Http Client does not support Transfer-Encoding-style
+      # requests
+      # doAssert(not request.headers.hasKey("Content-Length"))
       sanity = true
```
Comment (dom96) [inline tests/stdlib/tasynchttpserver_transferencoding.nim]:
```suggestion
      handlerFuture.complete()
```

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 7]
```diff
@@ -1,42 +1,40 @@
...
 
-const postBegin = """
-POST / HTTP/1.1
-Transfer-Encoding:chunked
-
-"""
-
-template genTest(input, expected) =
+template genTest(input, expected: string) =
   var sanity = false
```
Comment (dom96) [inline tests/stdlib/tasynchttpserver_transferencoding.nim]:
```suggestion
  var handlerFuture = newFuture()
```

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 8]
```diff
@@ -1,42 +1,40 @@
...
+    server.close()
+    return clientResponse
 
-  let server = newAsyncHttpServer()
-  waitFor runSleepLoop(server)
-  let data = postBegin & input
-  var socket = newSocket()
-  socket.connect("127.0.0.1", server.getPort)
-  socket.send(data)
-  waitFor sleepAsync(10)
```
Comment (dom96) [inline tests/stdlib/tasynchttpserver_transferencoding.nim:34]:
```
await handlerFuture
```

**Review by dom96 — CHANGES_REQUESTED** [review]
I did say this was likely to be flaky in https://github.com/nim-lang/Nim/pull/16678#issuecomment-768654964...

Sockets are indeed much better for these kinds of tests and since it seems you are working around httpclient's lack of transfer encoding support I don't think this is the direction we should go with this test.

You can use plain sockets with spawn too btw, might be easier to get working but ideally the async code should be fixed. I left a few comments showing what I would change there that might help.

**Comment by vabresto** [comment]
Thanks for the detailed feedback, and sorry for any and all headaches this caused. 

I've undone any changes to `asynchttpserver.nim` from earlier changes in this PR, so the only changes are to the test file itself. As for why I had touched the file in the first place: the `Content-Length` header gets added to all requests sent by the client very deeply in the code, and the server does a check for this header before checking for the `Transfer-Encoding`. But since I couldn't get the client to stop adding the `Content-Length` header, my previous tests in this commit chain simply had both headers. This meant that the simplest way to get the right behaviour was moving the check for `Transfer-Encoding` to be before that of the `Content-Length` header. However, now that the test uses sockets (like the original code), there are no issues with both headers being present because I have complete control over what gets sent down the wire.

Additionally, @dom96 I used the `handlerFuture` approach you suggested - thanks, that worked! The only real issue I ran into is that calling `getPort` before a call to `listen` set results in a segfault, but adding the `listen` call earlier fixed it. Not sure if that's something worth cleaning up further (raise exception instead of a panic?), but either way it isn't really related to this PR.

File: lib/pure/asynchttpserver.nim (hunk 3 above)
Comment (vabresto) [reply lib/pure/asynchttpserver.nim]: Copied from https://github.com/nim-lang/Nim/pull/18052#issuecomment-850014687

The Content-Length header gets added to all requests sent by the client very deeply in the code, and the server does a check for this header before checking for the Transfer-Encoding. But since I couldn't get the client to stop adding the Content-Length header, my previous tests in this commit chain simply had both headers. This meant that the simplest way to get the right behaviour was moving the check for Transfer-Encoding to be before that of the Content-Length header. However, now that the test uses sockets (like the original code), there are no issues with both headers being present because I have complete control over what gets sent down the wire.

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 9]
```diff
@@ -1,42 +1,56 @@
...
-  socket.close()
-  server.close()
+    spawn sendData(data, server.getPort)
```
Comment (dom96) [inline tests/stdlib/tasynchttpserver_transferencoding.nim]: This can be async too, you shouldn't need to use `spawn`.

**Review by dom96 — APPROVED** [review]
Much better, thanks!

Just one thing I would change: you don't need the `spawn`. You can do everything asynchronously, again just turn `sendData` to be async and change `spawn` to `asyncCheck` :)

Not super urgent though, so accepting.

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 10]
```diff
@@ -1,42 +1,56 @@
...
 POST / HTTP/1.1
 Transfer-Encoding:chunked
 
 """
 
-template genTest(input, expected) =
-  var sanity = false
-  proc handler(request: Request) {.async.} =
+template genTest(input, expected: string) =
+  proc handler(request: Request, future: Future[bool]): Future[void] {.async, gcsafe.} =
```
Comment (timotheecour) [inline tests/stdlib/tasynchttpserver_transferencoding.nim]:
```suggestion
  proc handler(request: Request, future: Future[bool]) {.async, gcsafe.} =
```

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 11]
```diff
@@ -1,42 +1,56 @@
...
       doAssert(request.body == expected)
       doAssert(request.headers.hasKey("Transfer-Encoding"))
       doAssert(not request.headers.hasKey("Content-Length"))
-      sanity = true
+      future.complete(true)
       await request.respond(Http200, "Good")
 
-  proc runSleepLoop(server: AsyncHttpServer) {.async.} = 
+  proc runSleepLoop(server: AsyncHttpServer, future: Future[bool]) {.async, gcsafe.} = 
+    proc wrapper(request: Request): Future[void] {.gcsafe, closure.} =
```
Comment (timotheecour) [inline tests/stdlib/tasynchttpserver_transferencoding.nim]:
```suggestion
    proc wrapper(request: Request) {.gcsafe, closure.} =
```

Comment (timotheecour) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: interesting, here it does't here, but it works in https://github.com/nim-lang/Nim/pull/18052/files#r641657077

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 12]
```diff
@@ -1,42 +1,56 @@
...
-template genTest(input, expected) =
-  var sanity = false
-  proc handler(request: Request) {.async.} =
+template genTest(input, expected: string) =
+  proc handler(request: Request, future: Future[bool]): Future[void] {.async, gcsafe.} =
       doAssert(request.body == expected)
       doAssert(request.headers.hasKey("Transfer-Encoding"))
       doAssert(not request.headers.hasKey("Content-Length"))
-      sanity = true
+      future.complete(true)
```
Comment (timotheecour) [inline tests/stdlib/tasynchttpserver_transferencoding.nim]: 2 spaces instead of 4 space indent for this block

File: tests/stdlib/tasynchttpserver_transferencoding.nim [hunk 13]
```diff
@@ -1,42 +1,56 @@
...
       await request.respond(Http200, "Good")
 
-  proc runSleepLoop(server: AsyncHttpServer) {.async.} = 
+  proc runSleepLoop(server: AsyncHttpServer, future: Future[bool]) {.async, gcsafe.} =
```
Comment (timotheecour) [inline tests/stdlib/tasynchttpserver_transferencoding.nim]: instead of adding this proc, and calling `syncCheck runSleepLoop(server, handlerFuture)`, how about this (a bit simpler):

```nim
    proc wrapper2(request: Request): Future[void] {.gcsafe, closure.} =
      handler(request, handlerFuture)
    asyncCheck server.acceptRequest(wrapper2)
```
(i checked it works)

File: tests/stdlib/tasynchttpserver_transferencoding.nim (hunk 9 above)
Comment (timotheecour) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: indeed either of these work:
```nim
# A1:
  proc sendData(data: string, port: Port) {.async.} =
    var socket = newAsyncSocket()
    await socket.connect("127.0.0.1", port)
    await socket.send(data)
    socket.close()

# A2:
  proc sendData(data: string, port: Port) {.async.} =
    var socket = newSocket()
    defer: socket.close()
    socket.connect("127.0.0.1", port)
    socket.send(data)
```

and replacing
```nim
spawn sendData(data, server.getPort)
=> one of these:
# B1:
asyncCheck sendData(data, server.getPort)
# B2:
await sendData(data, server.getPort)
```

@dom96 which version makes more sense here? in particular B1 or B2? (and why)

File: lib/pure/asynchttpserver.nim (hunk 2 above)
Comment (timotheecour) [reply lib/pure/asynchttpserver.nim]: i mean the very 1st msg in your PR, https://github.com/nim-lang/Nim/pull/18052#issue-649541477
it should contain the phrase `fix #17456` (without quotes) so that github auto-closes and so that it cross-references properly

(relying on commit messages is less good for a few reasons)

File: tests/stdlib/tasynchttpserver_transferencoding.nim (hunk 9 above)
Comment (vabresto) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: Fixed.

File: tests/stdlib/tasynchttpserver_transferencoding.nim (hunk 10 above)
Comment (vabresto) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: Fixed, though I don't understand why we want to remove this annotation.

File: tests/stdlib/tasynchttpserver_transferencoding.nim (hunk 11 above)
Comment (vabresto) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: Fixed.

File: tests/stdlib/tasynchttpserver_transferencoding.nim (hunk 12 above)
Comment (vabresto) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: Fixed (and good catch - thanks).

File: tests/stdlib/tasynchttpserver_transferencoding.nim (hunk 13 above)
Comment (vabresto) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: Thanks, this is nicer. Fixed.

File: tests/stdlib/tasynchttpserver_transferencoding.nim (hunk 10 above)
Comment (dom96) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: it's redundant

**Review by timotheecour — APPROVED** [review]
excellent!

**Comment by timotheecour** [comment]
finally merged it; post-merge question for @dom96 and @vabresto: should it be asyncCheck or await (and why) in https://github.com/nim-lang/Nim/pull/18052#discussion_r641676268 ?

**Comment by timotheecour** [comment]
hmm, this seems like introducing a regression, it now fails in freebsd: https://github.com/nim-lang/Nim/issues/18120

File: tests/stdlib/tasynchttpserver_transferencoding.nim (hunk 9 above)
Comment (dom96) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: B1 if you want the socket connection and send to happen in the background.

B2 if you want to pause the current async proc waiting on the socket connection and send to happen.

Which one to choose depends on what the rest of the code is doing. With how the code is right now asyncCheck makes sense (although you could reorder the code a little to make B2 work too).

Comment (dom96) [reply tests/stdlib/tasynchttpserver_transferencoding.nim]: A1/A2: both are not ideal. This is the ideal:

```nim
  proc sendData(data: string, port: Port) {.async.} =
    var socket = newAsyncSocket()
    defer: socket.close()
    await socket.connect("127.0.0.1", port)
    await socket.send(data)
```
