### PR TITLE
[backport] Handle nkOpenSymChoice for nkAccQuoted in considerQuotedIdent

### LINKED ISSUE #20591: Identifier construction in templates partially broken
### What happened?

Using identifier construction to use an existing symbol made up of anything and at least one symbol with overrides leads to an error.

Example can be found at https://play.nim-lang.org/#ix=4dvj

### Nim Version

Pretty much all of them (1.0 up until devel)

### Current Standard Output Logs

_No response_

### Expected Standard Output Logs

_No response_

### Possible Solution

Should be fixed in #20578

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SirOlaf**
Fixes #20591

Makes stuff like this work 

```nim
proc adda = discard

template example(f: untyped) =
  `add f`()

example(a) 
```

### CODE REVIEW

File: compiler/lookups.nim [hunk 1]
```diff
@@ -48,6 +48,11 @@ proc considerQuotedIdent*(c: PContext; n: PNode, origin: PNode = nil): PIdent =
         case x.kind
         of nkIdent: id.add(x.ident.s)
         of nkSym: id.add(x.sym.name.s)
+        of nkOpenSymChoice:
+          if x[0].kind == nkSym:
+            id.add(x[0].sym.name.s)
+          else:
+            handleError(n, origin)
```
Comment (metagn) [inline compiler/lookups.nim]:
```suggestion
        of nkSymChoices: id.add(x[0].sym.name.s)
```

Alternatively we can also check `if x.len != 0` and error otherwise but this should ideally never be possible.

Edit: I just saw that this is copied from below, so it can probably stay, but `nkOpenSymChoice` could still be `nkSymChoices` or `nkOpenSymChoice, nkClosedSymChoice`.

**Comment by metagn** [comment]
There shouldn't really be symchoices in nkAccQuoted but it doesn't matter that much as it might be more effort to deal with it and having this as a fallback is nice. 

I can't find an open issue for this, but I would expect it to be a common issue as the code example is very simple. Because of this I would suggest marking this as [backport] but it would be nice to see if people have encountered it first. A test would be nice as well.

**Comment by SirOlaf** [comment]
Hm, sorry some stuff is missing(?), first attempt at actually fixing a bug instead of complaining about one. Encountered the problem myself while building templates from other templates which led me to figuring out that for creating symbols this is totally fine, but using them seems impossible without this fix. It's an intersting case because it only happens for symbols with at least one override, so add was a good example.

I can open an issue and reference the pr if you think that would help, as for backport, honestly no idea what the difference is.

Lastly, where would the test go?

**Comment by Araq** [comment]
Add it to tests/template/template_various.nim

**Comment by metagn** [comment]
> backport, honestly no idea what the difference is

It means 1.6.10 etc also have this fix, rather than only 2.0 onward. Should be enough to add [backport] to the title.

**Comment by SirOlaf** [comment]
Done, lemme know if anything else is wrong/missing and should be fixed.

File: compiler/lookups.nim [hunk 2]
```diff
@@ -48,6 +48,11 @@ proc considerQuotedIdent*(c: PContext; n: PNode, origin: PNode = nil): PIdent =
         case x.kind
         of nkIdent: id.add(x.ident.s)
         of nkSym: id.add(x.sym.name.s)
+        of nkOpenSymChoice:
```
Comment (Araq) [inline compiler/lookups.nim]:
```suggestion
        of nkSymChoices:
```
