### PR TITLE
fixes #20553; don't format code for stropping identifier

### LINKED ISSUE #20553: Nimpretty mangles numeric literal procs
### What happened?

Running `nimpretty` on the implementation of a custom numeric literal results in broken code.
In general, the proc name has the first letter duplicated with a space between (e.g. `'XYYY` becomes `'X XYYY`)

For example the declaration:

```nim
proc `'u4`(n: string): u4 =
```

becomes:
```nim
proc `'u u4`(n: string): u4 =
```

### Nim Version

Nim Compiler Version 1.7.3 [MacOSX: amd64]
Compiled at 2022-10-12
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 7394587217c3ab26867d698b2ad89fb37cdcf3bb
active boot switches: -d:release

### Current Standard Output Logs

```shell
proc `'u u4`(n: string): u4 =
  # The leading ' is required.
  result = (parseInt(n) and 0x0F).u4
```

### Expected Standard Output Logs

```shell
proc `'u4`(n: string): u4 =
  # The leading ' is required.
  result = (parseInt(n) and 0x0F).u4
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #20553

### CODE REVIEW

**Comment by Araq** [comment]
Patch an existing nimpretty test instead please.

File: nimpretty/tests/expected/simple.nim [hunk 1]
```diff
@@ -13,6 +13,17 @@ proc a() =
   discard
 
 # bug #15596
-discard ## comment 3
+discard## comment 3
```
Comment (ringabout) [inline nimpretty/tests/expected/simple.nim]:
```suggestion
discard ## comment 3
```
