### PR TITLE
fix #16334

### LINKED ISSUE #16334: compile time echo steals newline from stderr so it's included in stdout instead
### Example

Say we have this program saved as test.nim
```nim
static:
    echo "test"

proc abc(x: float) =
    discard
proc abc(x: int) =
    discard

abc("test")
```

And we inspect stdout and stderr using this program (if you're a command line wiz you could probably do that simpler):

```nim
import osproc, streams

let process = startProcess("nim", args = ["check", "test.nim"], options = {poUsePath})
discard process.waitForExit()

echo "std out:"
echo process.outputStream().readAll()
echo "std err:"
echo process.errorStream().readAll()
```

### Current Output
```
std out:

test

std err:
Hint: used config file 'C:\Nim\config\nim.cfg' [Conf]
Hint: used config file 'C:\Nim\config\config.nims' [Conf]
.....C:\Users\Kemal\Desktop\neuerordner\test.nim(22, 4) Error: type mismatch: got <string>
but expected one of:
proc abc(x: float)
  first type mismatch at position: 1
  required type for x: float
  but expression '"test"' is of type: string
proc abc(x: int)
  first type mismatch at position: 1
  required type for x: int
  but expression '"test"' is of type: string

expression: abc("test")
C:\Users\Kemal\Desktop\neuerordner\test.nim(5, 6) Hint: 'y' is declared but not used [XDeclaredButNotUsed]
C:\Users\Kemal\Desktop\neuerordner\test.nim(19, 6) Hint: 'abc' is declared but not used [XDeclaredButNotUsed]
C:\Users\Kemal\Desktop\neuerordner\test.nim(17, 6) Hint: 'abc' is declared but not used [XDeclaredButNotUsed]
C:\Users\Kemal\Desktop\neuerordner\test.nim(1, 8) Warning: imported and not used: 'macros' [UnusedImport]

```

there's no newline between the dots and the path. But an additional one in stdout.

If the echo is removed this is the output:

```
std out:

std err:
Hint: used config file 'C:\Nim\config\nim.cfg' [Conf]
Hint: used config file 'C:\Nim\config\config.nims' [Conf]
.....
C:\Users\Kemal\Desktop\neuerordner\test.nim(20, 4) Error: type mismatch: got <string>
but expected one of:
proc abc(x: float)
  first type mismatch at position: 1
  required type for x: float
  but expression '"test"' is of type: string
proc abc(x: int)
  first type mismatch at position: 1
  required type for x: int
  but expression '"test"' is of type: string

expression: abc("test")
C:\Users\Kemal\Desktop\neuerordner\test.nim(3, 6) Hint: 'y' is declared but not used [XDeclaredButNotUsed]
C:\Users\Kemal\Desktop\neuerordner\test.nim(17, 6) Hint: 'abc' is declared but not used [XDeclaredButNotUsed]
C:\Users\Kemal\Desktop\neuerordner\test.nim(15, 6) Hint: 'abc' is declared but not used [XDeclaredButNotUsed]
C:\Users\Kemal\Desktop\neuerordner\test.nim(1, 8) Warning: imported and not used: 'macros' [UnusedImport]

```

### Additional Information

```
nim -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2020-12-12
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: d15f63a0f2d431a516601530196ac01c26e00f53
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by RSDuck**

### CODE REVIEW

File: compiler/msgs.nim [hunk 1]
```diff
@@ -16,9 +16,9 @@ import strutils2
 type InstantiationInfo* = typeof(instantiationInfo())
 template instLoc(): InstantiationInfo = instantiationInfo(-2, fullPaths = true)
 
-template flushDot(conf, stdorr) =
+template flushDot(conf, stdorr, isstdout) =
```
Comment (timotheecour) [inline compiler/msgs.nim]: isStdout

File: compiler/options.nim [hunk 2]
```diff
@@ -305,6 +305,7 @@ type
     projectFull*: AbsoluteFile # projectPath/projectName
     projectIsStdin*: bool # whether we're compiling from stdin
     lastMsgWasDot*: bool # the last compiler message was a single '.'
+    dotStdout*: bool # if the last message was a '.', whether it was output to stdout
```
Comment (timotheecour) [inline compiler/options.nim]: instead, let's track both stdout/stderr, separately it's more robust
```nim
# 0 for stdout, 1 for stderr, or better, use an enum
lastMsgWasDot*: array[2, boo]
```
that way we can treat each stream independently

**Review by timotheecour — APPROVED** [review]

File: compiler/msgs.nim [hunk 3]
```diff
@@ -16,10 +16,10 @@ import strutils2
 type InstantiationInfo* = typeof(instantiationInfo())
 template instLoc(): InstantiationInfo = instantiationInfo(-2, fullPaths = true)
 
-template flushDot(conf, stdorr) =
+template flushDot(conf, stdorr, stdOrrKind) =
```
Comment (timotheecour) [inline compiler/msgs.nim]: I LGTM'd for sake of moving on with this PR but if you can:

stdOrrKind is redundant with stdorr so this API should be:

```nim
template toStdOrrKind(stdorr): untyped =
  if stdorr == stdout: stdOrrStdout else: stdOrrStderr

template flushDot(conf, stdorr) =
  let stdOrrKind = stdorr.toStdOrrKind
  ....
```

and in msgWrite the code simplifies as well:
```nim
conf.lastMsgWasDot.incl stdOrr.toStdOrrKind
```
without needing the `let (stdOrr, stdOrrKind) = ...` etc

**Review by timotheecour — APPROVED** [review]
