### PR TITLE
fix #18578

### LINKED ISSUE #18578: output static lib is being deleted after compilation
### Example
compile your nim file (even empty) using `nim c --app:staticLib sometest.nim`

### Current Output
File sometest.lib **gets created and then deleted instantly**.
```
Hint: used config file 'D:\Programm\Nim\Nim-devel\config\nim.cfg' [Conf]
Hint: used config file 'D:\Programm\Nim\Nim-devel\config\config.nims' [Conf]
Hint: used config file 'D:\Programm\Nim\nimwrap\sometest.nim.cfg' [Conf]
........................................................
CC: sometest.nim
Hint:  [Link]
Hint: gc: refc; opt: none (DEBUG BUILD, `-d:release` generates faster code)
26617 lines; 1.724s; 31.941MiB peakmem; proj: D:\Programm\Nim\nimwrap\sometest.nim; out: D:\Programm\Nim\nimwrap\sometest.lib [SuccessX]
```

### Expected Output
file sometest.lib being created and stays put.

### Additional Information

git bisect shows this commit as first bad:
https://github.com/nim-lang/Nim/commit/ba64d0c8ab93c7f38b87567059cb2b66747d022c

```diff
--- a/compiler/extccomp.nim
+++ b/compiler/extccomp.nim
@@ -662,6 +662,7 @@ proc addExternalFileToCompile*(conf: ConfigRef; filename: AbsoluteFile) =
 proc getLinkCmd(conf: ConfigRef; output: AbsoluteFile,
                 objfiles: string, isDllBuild: bool): string =
   if optGenStaticLib in conf.globalOptions:
+    removeFile output # fixes: bug #16947
     result = CC[conf.cCompiler].buildLib % ["libfile", quoteShell(output),
                                             "objfiles", objfiles]
   else:
```

But i personally see nothing wrong about it. the output file gets deleted before the call to buildLib.
this is very strange. please help.

* Issue #16947 is related

```
$ nim -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-07-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f4ff276a90091f2b88c191aac5a201dcb3ec9795
active boot switches:
```

<details>
<summary>gcc and ld version</summary>

```
gcc -v
Using built-in specs.
COLLECT_GCC=D:\Programm\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=d:/programm/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/10.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-10.2.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-multilib --enable-64bit --disable-dependency-tracking --prefix=/mingw64 --with-sysroot=/mingw64 --disable-shared --enable-static --disable-nls --enable-version-specific-runtime-libs --disable-win32-registry --without-dwarf2 --enable-sjlj-exceptions --enable-fully-dynamic-string --enable-languages=c,d,ada,lto,c++,objc,obj-c++,fortran --enable-libgomp --enable-lto --enable-libssp -enable-gnattools --disable-bootstrap --with-gcc --with-gnu-as --with-gnu-ld --with-stabs --enable-interwork --with-mpfr-include=/home/betta/gcc-build/../gcc-10.2.0/mpfr/src --with-mpfr-lib=/home/betta/gcc-build/mpfr/src/.libs --enable-objc-gc --with-target-bdw-gc=/mingw64
Thread model: win32
Supported LTO compression algorithms: zlib
gcc version 10.2.0 (GCC)
```
```
ld -v
GNU ld (GNU Binutils) 2.35.1
```

</details>

### PR DESCRIPTION
**Pull request by ringabout**
close #18578

`getLinkCmd` is also called by `writeJsonBuildInstructions` which is executed after `callCCompiler`, so the static lib file is removed wrongly.

```nim
    extccomp.callCCompiler(conf)
    # for now we do not support writing out a .json file with the build instructions when HCR is on
    if not conf.hcrOn:
      extccomp.writeJsonBuildInstructions(conf)
```

### CODE REVIEW

File: tests/compiles/tstaticlib.nim [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import std/[os, osproc, strformat]
+
+
+const dir = "tests/compiles"
+const fileName = dir / "staticlibtest.nim"
+
+block: # bug #18578
+  const libName = dir / "tstaticlib1.a"
+  let (_, status) = execCmdEx(fmt"nim c -o:{libName} --app:staticlib {fileName}")
```
Comment (timotheecour) [inline tests/compiles/tstaticlib.nim]:
```suggestion
  let (_, status) = execCmdEx(fmt"{nim} c -o:{libName} --app:staticlib {fileName}")
```

and add above: `const nim = getCurrentCompilerExe()`

otherwise this breaks `testament --nim:bin/nim_foo`

ditto elsewhere

File: tests/compiles/tstaticlib2.a [hunk 2]
```diff
@@ -0,0 +1 @@
+echo 1234
```
Comment (timotheecour) [inline tests/compiles/tstaticlib2.a]: this is bad for 2 reasons:
* it'll get overwritten (and make git status not clean) after test is run
* we shouldn't check in .a files (even fake ones)

instead, simply create a temporary file with .a extension and remove it in the test (via `createTempFile`)

File: tests/compiles/staticlibtest.nim [hunk 3]
```diff
@@ -0,0 +1 @@
+echo 1234
```
Comment (timotheecour) [inline tests/compiles/staticlibtest.nim]: usually, convention is mfoo for a test foo; 
another option is to get rid of this and make tstaticlib.nim self-contained, either via this approach:
* tests/system/tsigexitcode.nim via `getAppFilename`
* or via an approach similar to `trunner`

File: tests/compiles/tstaticlib2.a (hunk 2 above)
Comment (ringabout) [reply tests/compiles/tstaticlib2.a]: I see

Comment (ringabout) [reply tests/compiles/tstaticlib2.a]: No pollution anymore.

File: tests/compiles/tstaticlib.nim (hunk 1 above)
Comment (ringabout) [reply tests/compiles/tstaticlib.nim]: thanks, fixed

File: tests/compiles/staticlibtest.nim (hunk 3 above)
Comment (ringabout) [reply tests/compiles/staticlibtest.nim]: I renamed the file.

File: compiler/extccomp.nim [hunk 4]
```diff
@@ -667,7 +667,6 @@ proc addExternalFileToCompile*(conf: ConfigRef; filename: AbsoluteFile) =
 proc getLinkCmd(conf: ConfigRef; output: AbsoluteFile,
```
Comment (timotheecour) [inline compiler/extccomp.nim:667]: how about insead add an optional param `removeStaticFile = true` to `getLinkCmd` and in `writeJsonBuildInstructions` call `getLinkCmd` with `removeStaticFile = false`

**Review by timotheecour — APPROVED** [review]
