### PR TITLE
Fix use of custom pragmas in generic procs

### LINKED ISSUE #7626: Custom pragma expands to nothing inside a generic proc
```nim
import "macros"

template simpleAttr {.pragma.}

type
    Annotated {.simpleAttr.} = object

proc generic_proc[T]() =
    # type mismatch: got <type Annotated, void>
    #
    # but expected one of:
    # macro hasCustomPragma(n: typed; cp: typed{nkSym}): untyped
    #
    #expression: hasCustomPragma(Annotated, )
    doAssert Annotated.hasCustomPragma(simpleAttr)
proc non_generic_proc() =
    # works
    doAssert Annotated.hasCustomPragma(simpleAttr)

non_generic_proc()
generic_proc[int]()
```
As illustrated in the example, the pragma(which is defined via a template), does not expand in the proc which isn't generic, which is the correct behavior. But inside of the generic proc, the pragma template expands to nothing and an error is generated.

As a temporary workaround the pragma can be defined this way:
```nim
template simpleAttr(dummyParam = true) {.pragma.}
```
then it works.

### PR DESCRIPTION
**Pull request by LemonBoy**
Fixes #7626

### CODE REVIEW

File: compiler/semgnrc.nim [hunk 1]
```diff
@@ -74,7 +74,7 @@ proc semGenericStmtSymbol(c: PContext, n: PNode, s: PSym,
   of skProc, skFunc, skMethod, skIterator, skConverter, skModule:
     result = symChoice(c, n, s, scOpen)
   of skTemplate:
-    if macroToExpandSym(s):
+    if sfCustomPragma notin s.flags and macroToExpandSym(s):
```
Comment (Araq) [inline compiler/semgnrc.nim]: Shouldn't this check be moved into ``macroToExpandSym``?

Comment (LemonBoy) [reply compiler/semgnrc.nim]: Done, I wasn't 100% sure about the other callsite (`skMacro`) but it should be safe
