### PR TITLE
fixes #23247; don't destroy openarray since it doesn't own the data

### LINKED ISSUE #23247: 1.6 to 2.0 regression with `UncheckedArray[string]`/`toOpenArray` resulting in `SIGSEGV`
### Description

```nim
import std/hashes

func baseAddr[T](x: openArray[T]): ptr T =
  # Return the address of the zero:th element of x or `nil` if x is empty
  if x.len == 0: nil else: cast[ptr T](x)

func makeUncheckedArray[T](p: ptr T): ptr UncheckedArray[T] =
  cast[ptr UncheckedArray[T]](p)

type
  LabelKey = object
    data: seq[string]
    refs: ptr UncheckedArray[string]
    refslen: int

  Gauge = ref object
    metrics: seq[seq[seq[string]]]

template values(key: LabelKey): openArray[string] =
  if key.refslen > 0:
    key.refs.toOpenArray(0, key.refslen - 1)
  else:
    key.data

proc hash(key: LabelKey): Hash =
  hash(key.values)

proc view(T: type LabelKey, values: openArray[string]): T =
  # TODO some day, we might get view types - until then..
  LabelKey(refs: baseAddr(values).makeUncheckedArray(), refslen: values.len())

template withValue2(k: untyped) =
  discard hash(k)

proc setGauge(
    collector: Gauge,
    labelValues: openArray[string],
) =
  let v = LabelKey.view(labelValues)
  withValue2(v)
  collector.metrics.add @[@labelValues, @labelValues]
  discard @labelValues

var nim_gc_mem_bytes = Gauge()
let threadID = $getThreadId()
setGauge(nim_gc_mem_bytes, @[threadID])
setGauge(nim_gc_mem_bytes, @[threadID])
```

With Nim 2.0 and devel, `nim c -r` with no further parameters triggers this. With Nim 1.6, `nim c -r --mm:orc --threads:on` mimics the 2.0/devel settings but does not result in `SIGSEGV`.

### Nim Version

No `SIGSEGV`:
```
Nim Compiler Version 1.6.19 [Linux: amd64]
Compiled at 2024-01-22
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: e8fe9275b5717a4ab77e8cfdc56e6e7b60c146c3
active boot switches: -d:release
```

`SIGSEGV`:
```
Nim Compiler Version 2.0.3 [Linux: amd64]
Compiled at 2024-01-22
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 4a1151d6b457ba48da476e71efbe42f1f836507b
active boot switches: -d:release
```

```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-01-22
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 83f2708909e0c59b84f61c2721907ff896285dce
active boot switches: -d:release
```

### Current Output

```text
Nim 1.6: no output

Nim 2.0:
r.nim(47) metrics
r.nim(42) setGauge
nim20/lib/std/assertions.nim(25) @
nim20/lib/system/alloc.nim(1052) alloc
nim20/lib/system/alloc.nim(868) rawAlloc
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault

Nim devel:
r.nim(47) metrics
r.nim(42) setGauge
nimdevel/lib/system.nim(1679) @
nimdevel/lib/system/alloc.nim(1054) alloc
nimdevel/lib/system/alloc.nim(870) rawAlloc
S
```

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #23247
closes #23251 (which accounts for why the openarray type is lifted because ops are lifted for openarray conversions)

related: https://github.com/nim-lang/Nim/pull/18713

It seems to me that openarray doesn't own the data, so it cannot destroy itself. The same case should be applied to https://github.com/nim-lang/Nim/issues/19435. It shouldn't be destroyed even openarray can have a destructor. A cleanup will be followed for https://github.com/nim-lang/Nim/pull/19723 if it makes sense.

According to https://github.com/nim-lang/Nim/pull/12073, it lifts destructor for openarray when openarray is sunk into the function, when means `sink openarray` owns the data and needs to destroy it. In other cases, destructor shouldn't be lifted for `openarray` in the first place and it shouldn't destroy the data if it doesn't own it.

### CODE REVIEW

**Comment by ringabout** [comment]
The CI failure is surprising. I guess I miss some destroys

File: compiler/injectdestructors.nim [hunk 1]
```diff
@@ -907,7 +909,10 @@ proc p(n: PNode; c: var Con; s: var Scope; mode: ProcessMode; tmpFlags = {sfSing
         result[0] = p(n[0], c, s, normal)
       if canRaise(n[0]): s.needsTry = true
       if mode == normal:
-        result = ensureDestruction(result, n, c, s)
+        if result.typ != nil and result.typ.kind != tyOpenArray:
```
Comment (Araq) [inline compiler/injectdestructors.nim]:
```suggestion
        if result.typ != nil and result.typ.kind notin {tyOpenArray, tyVarargs}:
```
