### PR TITLE
fix #13848: make var result work with nim cpp

### LINKED ISSUE #13848: var return type for proc doesn't work at c++ backend
### Example
`nim cpp -r -d:danger scratch.nim`
```nim
type
  MyType[T] = object
    a,b: T
  MyTypeAlias = MyType[float32]

var m: MyTypeAlias
proc identity(o: var MyTypeAlias): var MyTypeAlias = o
discard identity(m)
```

### Current Output
```
nim cpp -r -d:danger scratch.nim
Hint: used config file '/home/arne/proj/nim/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/arne/proj/nim/Nim/config/config.nims' [Conf]
Hint: used config file '/home/arne/.config/nim/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: scratch [Processing]
CC: scratch.nim
/home/arne/.cache/nim/scratch_r/@mscratch.nim.cpp: In function 'tyObject_MyType__oV8Am5o7e8x2FpgusXVyUg* identity__vOCbByxSDV3Os2F1Z4o1Og(tyObject_MyType__oV8Am5o7e8x2FpgusXVyUg&)':
/home/arne/.cache/nim/scratch_r/@mscratch.nim.cpp:40:11: error: cannot convert 'tyObject_MyType__oV8Am5o7e8x2FpgusXVyUg' to 'tyObject_MyType__oV8Am5o7e8x2FpgusXVyUg*' in assignment
   40 |  result = o;
      |           ^
      |           |
      |           tyObject_MyType__oV8Am5o7e8x2FpgusXVyUg
Error: execution of an external compiler program 'g++ -c -w -w -fpermissive -O3 -fno-strict-aliasing -fno-ident -std=gnu++14 -funsigned-char  -I/home/arne/proj/nim/Nim/lib -I/tmp -o /home/arne/.cache/nim/scratch_r/@mscratch.nim.cpp.o /home/arne/.cache/nim/scratch_r/@mscratch.nim.cpp' failed with exit code: 1



Compilation exited abnormally with code 1
```

### Expected Output
nothing, it should just compile

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #13848

### CODE REVIEW

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -1577,9 +1577,13 @@ proc takeImplicitAddr(c: PContext, n: PNode; isLent: bool): PNode =
         root.name.s, renderTree(n, {renderNoComments}), explanationsBaseUrl])
   case n.kind
   of nkHiddenAddr, nkAddr: return n
-  of nkHiddenDeref, nkDerefExpr: return n[0]
```
Comment (Araq) [inline compiler/semexprs.nim:1580]: I don't understand this patch.

Comment (timotheecour) [reply compiler/semexprs.nim:1580]: var params are nkHiddenDeref, and before PR, would loose their nkHiddenDeref, so `result = param` would deref instead of taking by address, causing a bug in cgen (result = param instead of result = &param)

I've now added plenty of tests regarding `var result` and identified 2 pre-existing bugs (not fixed in this PR)

**Comment by timotheecour** [comment]
PTAL

**Comment by krux02** [comment]
Thanks for the fix. But what does PTAL mean?

**Comment by ghost** [comment]
> Thanks for the fix. But what does PTAL mean?

@krux02 
"Please take another look"

**Comment by timotheecour** [comment]
> Thanks for the fix. But what does PTAL mean?

explained here:
> https://github.com/nim-lang/Nim/pull/11824#issuecomment-577942907
