### PR TITLE
#13806 - getApplFreebsd might lose data

### LINKED ISSUE #13806: `os.getApplFreebsd` could return incorrect paths in the case of a long path
As [noticed by @timotheecour](https://github.com/nim-lang/Nim/pull/12179#discussion_r399875661), [`os.getApplFreebsd`](https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L2793) seems like it has a possibility to return incorrect paths in the case of a path being a very long value.

> The information is copied into the buffer specified by oldp. The size of the buffer is given by the location specified by oldlenp before the call, and that location gives the amount of data copied after a successful call and after a call that returns with the error code ENOMEM. If the amount of data available is greater than the size of the buffer supplied, the call supplies as much data as fits in the buffer provided and returns with the error code ENOMEM. If the old value is not desired, oldp and oldlenp should be set to NULL.

It is recommended to instead use two calls to `sysctl` - the first with `oldp` set to `NULL` in order to get the required capacity, then another with the required capacity:

> The size of the available data can be determined by calling sysctl() with the NULL argument for oldp. The size of the available data will be re- turned in the location pointed to by oldlenp. For some operations, the amount of space may change often. For these operations, the system attempts to round up so that the returned size is large enough for a call to return the data shortly thereafter.

https://www.freebsd.org/cgi/man.cgi?sysctl(3)

### PR DESCRIPTION
**Pull request by euantorano**
Fixes #13806

I haven't yet tested this, let's see what the CI thinks...

### CODE REVIEW

**Comment by euantorano** [comment]
CI passed and tested locally too. `getAppFilename()` and `getCurrentCompilerExe()` return correct values for the following test script:

```nim
import os

echo "compiler: ", getCurrentCompilerExe()
echo "app: ", getAppFilename()
```

File: lib/pure/os.nim [hunk 1]
```diff
@@ -2787,23 +2787,23 @@ when not weirdTarget and (defined(freebsd) or defined(dragonfly)):
...
-        result.setLen(pathLength-1)
-        break
+
+    # first call to get the required length
+    var res = sysctl(addr req[0], 4, nil, addr pathLength, nil, 0)
+
+    if res < 0:
+      return ""
+
+    result = newString(pathLength)
```
Comment (Clyybber) [inline lib/pure/os.nim]:
```suggestion
    result.setLen(pathLength)
```

File: lib/pure/os.nim [hunk 2]
```diff
@@ -2787,23 +2787,23 @@ when not weirdTarget and (defined(freebsd) or defined(dragonfly)):
...
+    res = sysctl(addr req[0], 4, cast[pointer](addr result[0]), addr pathLength, nil, 0)
```
Comment (Clyybber) [inline lib/pure/os.nim]:
```suggestion
    res = sysctl(addr req[0], 4, addr result[0], addr pathLength, nil, 0)
```
That cast shouldn't be necessary

Comment (euantorano) [reply lib/pure/os.nim]: Yeah, I just copied and pasted from previous code that's included a cast for a while. Removed in 021f889.

File: lib/pure/os.nim [hunk 3]
```diff
@@ -2787,23 +2787,23 @@ when not weirdTarget and (defined(freebsd) or defined(dragonfly)):
...
-          break
-      else:
-        # trim the trailing null byte, as the result is a string not a cstring
-        result.setLen(pathLength-1)
-        break
+
+    # first call to get the required length
+    var res = sysctl(addr req[0], 4, nil, addr pathLength, nil, 0)
+
+    if res < 0:
```
Comment (timotheecour) [inline lib/pure/os.nim:2796]: IMO this should raise instead of ignoring the error (and setting the global errno)
```nim
raiseOSError(osLastError(), "something")
```
note that `getApplHeuristic` is buggy (and not even fixable) so that's not a good enough workaround

ditto below

File: lib/pure/os.nim [hunk 4]
```diff
@@ -2787,23 +2787,23 @@ when not weirdTarget and (defined(freebsd) or defined(dragonfly)):
...
+      return ""
+
+    result.setLen(pathLength)
+    res = sysctl(addr req[0], 4, addr result[0], addr pathLength, nil, 0)
+
+    if res < 0:
+      return ""
+
+    let realLen = len(cstring(result))
```
Comment (timotheecour) [inline lib/pure/os.nim:2805]: wouldn't this work:
```nim
doAssert result[^1] == '\0' # sanity check
result.setLen result.len - 1
```

File: lib/pure/os.nim (hunk 3 above)
Comment (euantorano) [reply lib/pure/os.nim:2796]: This approach is copied from other implementations - see for example:

- [getApplgetApplHaiku](https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L2903)
- [getApplHeuristic](https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L2873)
- [getApplOpenBsd](https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L2859)
- [Windows implementation](https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L2937)
- [Mac implementation](https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L2950)

IMO, it's better to be consistent - either all should raise on error or none should.

File: lib/pure/os.nim (hunk 4 above)
Comment (euantorano) [reply lib/pure/os.nim:2805]: This was copied from [`getApplHaiku`](https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L2901) - I wanted to keep the implementation roughly the same.

The old code simply always trimmed the last byte off.
