### PR TITLE
Do not materialize empty varargs[untyped] arrays

### LINKED ISSUE #8706: `varargs[untyped]` doesn't work with 0 arguments, creating an extraneous `nnkHiddenStdConv` varargs[untyped] node
see all mentions of BUG below:

see also workaround in case6 to create a macro `varargsToTuple`

this is a serious bug as it affects generic code (eg I had to work around it for https://github.com/nim-lang/Nim/pull/8679)

```nim
import macros

macro varargsToTuple(args:varargs[untyped]):untyped=
  result = newTree(nnkTupleConstr)
  for a in args:
    result.add a

macro varargsLen(args:varargs[untyped]):untyped=
  # BUG: should be 0 for case2, not 1
  result = newLit(args.len)

template foo(args:varargs[untyped]): untyped =
  varargsLen(args)

when defined(case1):
  doAssert foo(10) == 1
  doAssert foo(10, 20) == 2

when defined(case2):
  # fail
  # doAssert foo() == 0
  echo foo() # BUG: got 1


when defined(case3):
  macro varargsFirst(args:varargs[untyped]):untyped=
    echo args[0].kind # BUG: nnkHiddenStdConv ??

    result = args[0]

  template foo2(args:varargs[untyped]): untyped =
    varargsFirst(args)

  doAssert foo2(10) == 10
  # BUG: Error: invalid type: 'varargs[untyped]' for let
  let a = foo2()

when defined(case4):
  template foo2(args:varargs[untyped]): untyped =
    varargsToTuple(args)

  doAssert foo2(10) == (10,)
  doAssert foo2(10, 20) == (10, 20)
  when defined(case4a):
    # BUG: Error: invalid type: 'varargs[untyped]' in this context: 'tuple of (varargs[untyped])' for let
    let a = foo2()
  when defined(case4b):
     # BUG: Error: invalid type: 'untyped' in this context: 'iterator (x: tuple of (varargs[untyped])): RootObj{.inline, noSideEffect.}' for proc
    echo foo2()

when defined(case5):
  macro bar(arg:typed):untyped=
    result = newLit arg.repr

  template foo2(args:varargs[untyped]): untyped =
    bar(varargsToTuple(args))

  echo foo2(1) #(1,)
  echo foo2(1, 2) #(1, 2)
  echo foo2() # BUG: ([],)


when defined(case6):
  # workaround
  macro varargsToTuple2(args:varargs[untyped]):untyped=
    result = newTree(nnkTupleConstr)
    if args.len != 1:
      for a in args:
        result.add a
    else:
      # workaround for BUG with empty args `()`
      if args[0].kind != nnkHiddenStdConv:
          result.add args[0]

  template foo2(args:varargs[untyped]): untyped =
    varargsToTuple2(args)

  doAssert foo2(10) == (10,)
  doAssert foo2(10, 20) == (10, 20)
  echo foo2()
```

### PR DESCRIPTION
**Pull request by LemonBoy**
When an empty nkArgList `varargs[untyped]` is passed around it is now
reused for efficiency sake and to prevent the introduction of a spurious
element: before this commit we'd pass the caller a
nkArgList[nkHiddenStdConv[nkBracket]] node instead of just an empty
nkArgList.

Fixes #8706

### CODE REVIEW

**Comment by timotheecour** [comment]
thanks for fixing this!
1 question: is reusing instead of copying the container safe? eg in case:
```nim
macro foo(args: varargs[untyped]):untyped=
  fun1(args) # suppose this modifies args
  fun2(args) # args modified under fun2's nose
foo()
```

File: tests/macros/t8706.nim [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+  doAssert args.len == 0
+  result = newLit(args.len)
+
+template bar(a0:varargs[untyped]): untyped =
+  varargsLen(a0)
+
+template foo(x: int, a0:varargs[untyped]): untyped =
+  bar(a0)
+
+echo foo(42)
```
Comment (timotheecour) [inline tests/macros/t8706.nim]: this is simpler/clearer IMO:
doAssert foo(42) == 0
doAssert bar() == 0

**Comment by Araq** [comment]
Pretty nice but it seems to me we should merge ``nkArgList`` with ``nkBracket`` somehow. Why do we need ``nkArgList``?

**Comment by zah** [comment]
`nkArgList` is special, because it supports argument forwarding. If you pass an ArgList node to another call, the parameters get unpacked to separate positions.

**Comment by Araq** [comment]
@zah IIRC we only support that in template evaluations.

**Comment by mratsim** [comment]
I've noticed that I had to pass `nnkArgList` to `varargs[typed]` macro parameter otherwise `getTypeInst` doesn't work properly.
