### PR TITLE
Of operator in vm fixes [backport]

### LINKED ISSUE #9701: of operator can be too strict stopping semantic pass too early with error
The following example does not compile:
```nim
type
  Base = ref object of RootObj
    x: string

  A = ref object of Base
    a: string

  B = ref object of Base
    b: string

template check(n: Base) =
  echo n of A


static:
  let aa = new(B)
  check(aa)
```

Error message by compiler:
```
ref_obj.nim(12, 10) Error: 'B:ObjectType' cannot be of this subtype
```

### LINKED ISSUE #9702: of operator does not work in VM for ref object types
This example crashes in the VM:
```nim
type
  Base = ref object of RootObj
    x: string

  A = ref object of Base
    a: string

  B = ref object of Base
    b: string

proc check(n: Base) =
  echo n of A

static:
  let aa = new(B)
  check(aa)

```
Crash stack trace:
```
nim.nim(109)             nim
nim.nim(73)              handleCmdLine
cmdlinehelper.nim(91)    loadConfigsAndRunMainCommand
main.nim(168)            mainCommand
main.nim(78)             commandCompileToC
modules.nim(126)         compileProject
modules.nim(71)          compileModule
passes.nim(194)          processModule
passes.nim(86)           processTopLevelStmt
sem.nim(603)             myProcess
sem.nim(571)             semStmtAndGenerateGenerics
semstmts.nim(1977)       semStmt
semexprs.nim(914)        semExprNoType
semexprs.nim(2537)       semExpr
semstmts.nim(1918)       semStmtList
semexprs.nim(2589)       semExpr
semstmts.nim(1870)       semStaticStmt
vm.nim(1903)             evalStaticStmt
vm.nim(1893)             evalConstExprAux
vm.nim(1231)             rawExecute
types.nim(1090)          inheritanceDiff
system.nim(3930)         failedAssertImpl
system.nim(3923)         raiseAssert
system.nim(2970)         sysFatal
Error: unhandled exception: C:\nim-devel\compiler\types.nim(1090, 10) `b.kind == tyObject`  [AssertionError]
```

### PR DESCRIPTION
**Pull request by cooldome**
fixes #9701

fixes #9702

### CODE REVIEW

**Comment by krux02** [comment]
Good work. I have no complaints.

File: compiler/semmagic.nim [hunk 1]
```diff
@@ -305,7 +305,7 @@ proc semOf(c: PContext, n: PNode): PNode =
         result.info = n.info
         result.typ = getSysType(c.graph, n.info, tyBool)
         return result
-      elif diff == high(int):
+      elif diff == high(int) and commonSuperclass(a, b) == nil:
```
Comment (Araq) [inline compiler/semmagic.nim]: But that's what ``diff == high(int)`` means, no?

Comment (cooldome) [reply compiler/semmagic.nim]: Not really, suppose you have ``Base`` class and two children``A`` and ``B``. Now you are calling: ``A of B``. In this case ``inheritanceDiff()`` returns ``high(int)``, but ``commonSuperclass()`` returns ``Base``. When``A of B`` is called, I don't want compilation error because in my case it is result of template expansion (very frequiently used template ``log``). I want to get simply false.

**Comment by cooldome** [comment]
I have added optimization ``of`` expression to ``false`` when it is possible

File: compiler/semmagic.nim (hunk 1 above)
Comment (Araq) [reply compiler/semmagic.nim]: Meh, ok.
