### PR TITLE
fix #14179, fix #14142, make CI 1.4x faster (2x faster locally)

### LINKED ISSUE #14142: import os + use of existsDir/dirExists/existsFile/fileExists/findExe in config.nims causes "ambiguous call' error
In `config.nims`, when the `os` module is imported **and** one of these procs are used:

- `existsDir` or `dirExists`
- `existsFile` or `fileExists`
- `findExe`

we get the "ambiguous call" error (because these are defined in both `system` and `os`.

### Example `config.nims`

1. Create this `config.nims` in any directory
2. Run `nim temp123`

```nim
# config.nims
import os # commenting this out fixes the error
# import os except existsDir, dirExists, existsFile, fileExists, findExe # this also does not give that error

task temp123, "Temp task":
  echo existsDir("/usr")
  echo dirExists("/usr")
  echo existsFile("/usr/foo")
  echo fileExists("/usr/foo")
  echo findExe("nim")
```

### Current Output

```
/home/kmodi/sandbox/nim/bug_reports/nimscript_import_os/config.nims(4, 6) template/generic instantiation of `task` from here
/home/kmodi/sandbox/nim/bug_reports/nimscript_import_os/config.nims(5, 17) Error: ambiguous call; both system.existsDir(dir: string) [declared in /home/kmodi/usr_local/apps/6/nim/devel/lib/system/nimscript.nim(135, 6)] and os.existsDir(dir: string) [declared in /home/kmodi/usr_local/apps/6/nim/devel/lib/pure/os.nim(1109, 6)] match for: (string)
```

### Expected Output

Outputs of the echo statements in the above example.

### Workaround

- Use `import os except existsDir, dirExists, existsFile, fileExists, findExe`, or `system.` qualifiers with the ambiguous identifiers.

### Additional Information

This issue is very closely related to https://github.com/nim-lang/Nim/issues/12835 .

```
$ nim -v
Nim Compiler Version 1.3.1 [Linux: amd64]
Compiled at 2020-04-27
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2f1aad02642576d13df018c9e5869c8de7e3a539
active boot switches: -d:release
```

This used to work at some point (probably around Nim 19.x).

### LINKED ISSUE #14179: `nim dump` is roughly 100x slower in 1.3 versus 1.2
See title.

### PR DESCRIPTION
**Pull request by timotheecour**
* make CI significantly faster (1.4x faster on CI machines, 2x locally) 
by avoiding `import os` (and all the modules that it imports recursively) for every single invocation of `nim`; like wise for short-lived commands (eg `nim dump` or `nim c smallfile` or `inim`)

* fix https://github.com/nim-lang/Nim/issues/14179
* fix https://github.com/nim-lang/Nim/issues/14142
* supersedes https://github.com/nim-lang/Nim/pull/14143
* still keeps https://github.com/nim-lang/Nim/issues/12835 as fixed

see https://github.com/nim-lang/Nim/issues/14179#issuecomment-625200718 for the full context

## CI timings on CI machines
before PR => after PR
Linux_amd64 31m => 21m
Linux_i386 32m => 18m
OSX_amd64 17m => 13m
OSX_amd64_cpp 18m => 13m 
Windows_amd64 38m => 33m

## CI timings locally on OSX
via `XDG_CONFIG_HOME= nim c -r testament/testament all`
494s => 253s
(didn't try `./koch runCI` locally in this experiment)

### CODE REVIEW

File: compiler/condsyms.nim [hunk 1]
```diff
@@ -77,7 +77,7 @@ proc initDefines*(symbols: StringTableRef) =
   defineSymbol("nimHasUserErrors")
   defineSymbol("nimUncheckedArrayTyp")
   defineSymbol("nimHasTypeof")
-  defineSymbol("nimErrorProcCanHaveBody")
+  defineSymbol("nimErrorProcCanHaveBody") # since #9665 but now unused
```
Comment (Clyybber) [inline compiler/condsyms.nim:80]: Most of these are unused. This doesn't need a comment IMO

Comment (Clyybber) [inline compiler/condsyms.nim]:
```suggestion
  defineSymbol("nimErrorProcCanHaveBody")
```
Most of these are unused. This doesn't need a comment IMO

File: lib/pure/os.nim [hunk 2]
```diff
@@ -75,8 +75,8 @@ elif defined(posix):
 else:
   {.error: "OS module not ported to your operating system!".}
 
-when weirdTarget and defined(nimErrorProcCanHaveBody):
-  {.pragma: noNimScript, error: "this proc is not available on the NimScript target".}
```
Comment (Araq) [inline lib/pure/os.nim:79]: I spent effort on this specialized error message, why remove it?

File: compiler/condsyms.nim (hunk 1 above)
Comment (timotheecour) [reply compiler/condsyms.nim]: that's not true, most of these are used. I've removed the comment anyhow, can be found with git blame

File: lib/pure/os.nim (hunk 2 above)
Comment (timotheecour) [reply lib/pure/os.nim:79]: this was already answered here: https://github.com/nim-lang/Nim/pull/14143#issuecomment-620484977

Comment (Araq) [reply lib/pure/os.nim:79]: > because the problems in #14142 are real and outweigh the benefits of having a nicer error message.

Well that's debatable and I don't agree. It's simply true that some os procs are unavailable for NimScript and a clear error message helps.

**Comment by timotheecour** [comment]
@araq PTAL, the last commit should address all your concerns (and also provide less misleading error msgs with nim js).

**Comment by Araq** [comment]
Thank you, superb work now.

File: lib/pure/os.nim (hunk 2 above)
Comment (timotheecour) [reply lib/pure/os.nim:79]: addressed in latest commit
