### PR TITLE
fixes #13583; enforce void for `nkWhileStmt`

### LINKED ISSUE #13583: Error: internal error: yield in expr not lowered
Reduced example **(from the comment below)**:

```nim
proc hello(): int {.discardable.} = 12

iterator test(): int {.closure.} =
  while true:
    yield 12
    hello()

let t = test
```

----

**Original issue:**

A very strange error appears when I use the SDL2 library (https://github.com/nim-lang/sdl2):
```
Error: internal error: yield in expr not lowered
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

Here's how it appears:
```nim
method setText*(edittext: EditTextRef, text: cstring) {.async.} =
  ## Redraws the EditText's text.
  ##
  ## If text is empty, then draws hint with hint color.
  ##
  ## Arguments:
  ## -   ``text`` -- new text.
  if text.len == 0:
    edittext.text = text
    edittext.background.fillRect(nil, 0x00000000)
    blitSurface(edittext.saved_background, nil, edittext.background, nil)
    var rendered = edittext.font.renderUtf8BlendedWrapped(
      edittext.hint, await parseColor(edittext.hint_color.int), 1024)
    var rect = rect(edittext.x, edittext.y, rendered.w, rendered.h)
    # The error appears due to the line below
    blitSurface(rendered, nil, edittext.background, rect.addr)
  else:
    await procCall edittext.TextViewRef.setText(text)
```

How do I fix this error?
add `discard` after error line
```nim
method setText*(edittext: EditTextRef, text: cstring) {.async.} =
  ## Redraws the EditText's text.
  ##
  ## If text is empty, then draws hint with hint color.
  ##
  ## Arguments:
  ## -   ``text`` -- new text.
  if text.len == 0:
    edittext.text = text
    edittext.background.fillRect(nil, 0x00000000)
    blitSurface(edittext.saved_background, nil, edittext.background, nil)
    var rendered = edittext.font.renderUtf8BlendedWrapped(
      edittext.hint, await parseColor(edittext.hint_color.int), 1024)
    var rect = rect(edittext.x, edittext.y, rendered.w, rendered.h)
    blitSurface(rendered, nil, edittext.background, rect.addr)
    # When I add discard - the error disappears
    discard
  else:
    await procCall edittext.TextViewRef.setText(text)
```

How do I run the code?
`nim c -r -d: release --showAllMismatches: on --hints: off --threads: on -d: ssl: on --opt: speed FILE.nim`

OS: Windows, x64
Nim version: 1.0.6

Full code here: https://github.com/Ethosa/yukiko

### PR DESCRIPTION
**Pull request by ringabout**
Fixes #13583

A node of a `nkWhileStmt` kind cannot have a type in normal cases. If its last node has a type, it means the final last node contains a node calling a `discardable` function. We know that it cannot be interpreted as an expression in while statement. We should enforce void type for it. Arguably, we can rewrite it as a `discard` statement.

### CODE REVIEW

**Comment by metagn** [comment]
I mean, we get the same error with if/else, which can be an expression.

```nim
proc hello(): int {.discardable.} = 12

iterator test(): int {.closure.} =
  if true:
    yield 12
    hello()
  else: discard

let t = test
```

**Comment by ringabout** [comment]
Yeah, that's a harder problem than `nkWhileStmt` since `discardable` call can be interpreted as expression/statement with if expression/statement. See https://github.com/nim-lang/Nim/issues/20941. The same goes for block, case and try. `case` and `try` don't even have an expression node, which makes the problem trickier. First thing first, `discardable` node is not ambiguous in the while statement.

File: compiler/semstmts.nim [hunk 1]
```diff
@@ -101,6 +103,9 @@ proc semWhile(c: PContext, n: PNode; flags: TExprFlags): PNode =
     result.typ = c.enforceVoidContext
   elif efInTypeof in flags:
     result.typ = n[1].typ
+  elif implicitlyDiscardable(n[1]):
+    result[1].typ = c.enforceVoidContext
```
Comment (Araq) [inline compiler/semstmts.nim:107]: Why would result[1].typ be the void type? `discard producesVoid()` is not allowed.

Comment (ringabout) [reply compiler/semstmts.nim:107]: Since it is an implicit `discardable` call, there is no discard. So I simply set the type of the whole body to void type.

```nim
  while true:
    hello()
 ```

`result[1].typ` corresponds to the type of the while statement body, namely the type of `discardable` call. Since an implicit `discardable` call won't be rewritten to a discard statement, we need to set the type of the body to void type or plus turn the `discardable` call into a discard statement.
