### PR TITLE
[error messages] fix #8794 #9270 #9767 #9768 

### LINKED ISSUE #8794: `Error: undeclared field: 'foo'` should show type (+ where type is defined) (hard to guess in generic code)
probably this would be good: `getSymRepr(c.config, sym)` to show type + where it's defined.

TODO (timothee):
format this in a proper sentence:  (+ where type is defined) (hard to guess in generic code)

### PR DESCRIPTION
**Pull request by timotheecour**
* fixes https://github.com/nim-lang/Nim/issues/8794 => see tests/errmsgs/t8794.nim
* fixes https://github.com/nim-lang/Nim/issues/9270
* fixes https://github.com/nim-lang/Nim/issues/9767
* fixes https://github.com/nim-lang/Nim/issues/9768 => see tests/errmsgs/t9768.nim
* refactors some `col+1` code to `col + ColOffset` (self documents code) 
* ~~fixes off by 1 error in `toFileLineCol` which didn't add 1 to `col` when displaying some `file(line,col)` messages~~ EDIT: was fixed in https://github.com/nim-lang/Nim/pull/10138

* make `getProcHeader` show declared info location also for types and all routine kinds (including macros,templates) instead of just (rather arbitrarily) for iterator,proc,func,method
* ~~adds --forcefullpaths which is meant to force full paths everywhere that's being displayed , including `toFilename` which was used (indirectly) in https://github.com/nim-lang/Nim/issues/9270 ; that's the simplest way to fix this; and it makes sense to have a simple way to force using full paths everywhere in compiler messages~~
  EDIT: after feedback from @araq in IRC, I instead extended meaning of existing listFullPaths flag, instead of adding a new flag forceFullPaths

* fix typo system/except.nim => lib/system/excpt.nim
* remove `substr(foo, 0)` hack in `compiler/vm.nim` which seems old and not applicable anymore:
> this 'substr' prevents a strange corruption. XXX This needs to be investigated eventually but first attempts to fix it broke everything see the araq-wip-fixed-writebarrier branch.

### CODE REVIEW

**Comment by timotheecour** [comment]
```nim
#[
KEY xyz
BUG: VM stacktrace doesn't honor --excessiveStackTrace:on
]#

proc main()=
  doAssert false

proc main2() =
  main()

proc main3()=
  static:
    main2()

main3()
```

**Comment by timotheecour** [comment]
/cc @Araq PTAL 
(after your feedback on IRC, I extended meaning of existing listFullPaths flag instead of adding a new forceFullPaths flag)

File: tests/errmsgs/treportunused.nim [hunk 1]
```diff
@@ -4,13 +4,13 @@ treportunused.nim(19, 10) Hint: 'treportunused.s1(a: string)[declared in treport
...
-treportunused.nim(24, 7) Hint: 's6' is declared but not used [XDeclaredButNotUsed]
+treportunused.nim(24, 7) Hint: 'treportunused.s6(a: int)[declared in treportunused.nim(24, 6)]' is declared but not used [XDeclaredButNotUsed]
 treportunused.nim(23, 6) Hint: 'treportunused.s5(a: T)[declared in treportunused.nim(23, 5)]' is declared but not used [XDeclaredButNotUsed]
 treportunused.nim(20, 10) Hint: 'treportunused.s2()[declared in treportunused.nim(20, 9)]' is declared but not used [XDeclaredButNotUsed]
-treportunused.nim(29, 6) Hint: 's11' is declared but not used [XDeclaredButNotUsed]
+treportunused.nim(29, 6) Hint: 'treportunused.s11[declared in treportunused.nim(29, 5)]' is declared but not used [XDeclaredButNotUsed]
 treportunused.nim(27, 5) Hint: 's9' is declared but not used [XDeclaredButNotUsed]
-treportunused.nim(21, 10) Hint: 's3' is declared but not used [XDeclaredButNotUsed]
-treportunused.nim(28, 6) Hint: 's10' is declared but not used [XDeclaredButNotUsed]
+treportunused.nim(21, 10) Hint: 'treportunused.s3()[declared in treportunused.nim(21, 9)]' is declared but not used [XDeclaredButNotUsed]
```
Comment (krux02) [inline tests/errmsgs/treportunused.nim]: don't you think that this is a bit redundant? Print line information twice?

Comment (timotheecour) [reply tests/errmsgs/treportunused.nim]: yes, but that's a separate, pre-existing issue: look at this file in devel: https://github.com/nim-lang/Nim/blob/f18fcf65b3a61b1960c14aa9503eea34fee76492/tests/errmsgs/treportunused.nim#L3
```
discard """
  nimout: '''
treportunused.nim(19, 10) Hint: 'treportunused.s1(a: string)[declared in treportunused.nim(19, 9)]' is declared but not used [XDeclaredButNotUsed]
treportunused.nim(26, 5) Hint: 's8' is declared but not used [XDeclaredButNotUsed]
treportunused.nim(22, 6) Hint: 'treportunused.s4()[declared in treportunused.nim(22, 5)]' is declared but not used [XDeclaredButNotUsed]
treportunused.nim(25, 7) Hint: 's7' is declared but not used [XDeclaredButNotUsed]
treportunused.nim(24, 7) Hint: 's6' is declared but not used [XDeclaredButNotUsed]
treportunused.nim(23, 6) Hint: 'treportunused.s5(a: T)[declared in treportunused.nim(23, 5)]' is declared but not used [XDeclaredButNotUsed]
treportunused.nim(20, 10) Hint: 'treportunused.s2()[declared in treportunused.nim(20, 9)]' is declared but not used [XDeclaredButNotUsed]
treportunused.nim(29, 6) Hint: 's11' is declared but not used [XDeclaredButNotUsed]
treportunused.nim(27, 5) Hint: 's9' is declared but not used [XDeclaredButNotUsed]
treportunused.nim(21, 10) Hint: 's3' is declared but not used [XDeclaredButNotUsed]
treportunused.nim(28, 6) Hint: 's10' is declared but not used [XDeclaredButNotUsed]
'''
```
it already contains the redundant info, but only for some kinds (eg iterator) and not some other kinds (eg macro), which is arbitrary.

I'm happy to file an issue for this pre-existing issue, but it's a minor annoyance that (IIUC) should only happen with `XDeclaredButNotUsed` ; other error messages will benefit from the extra info as it won't be redundant in these other cases.

**Comment by krux02** [comment]
Didn't read through all the changes (too long), all I see is a decrease of the error message quality (seen in the diff of the test case). I don't like that.

File: tests/errmsgs/treportunused.nim (hunk 1 above)
Comment (krux02) [reply tests/errmsgs/treportunused.nim]: I don't see those "other error messages [that] will benefit from the extra info".

**Comment by timotheecour** [comment]
> Where are the test cases for the issues that you fixed?

see tests/errmsgs/t8794.nim for #8794

it requires https://github.com/nim-lang/Nim/pull/10091 to be merged first

Will follow up with more tests, but would really like #10091 to be merged first (it reuses the logic @krux02 introduced recently to failing tests)

File: tests/errmsgs/treportunused.nim (hunk 1 above)
Comment (timotheecour) [reply tests/errmsgs/treportunused.nim]: reported that separate issue regarding `XDeclaredButNotUsed` being redundant here: https://github.com/nim-lang/Nim/issues/10101

> I don't see those "other error messages [that] will benefit from the extra info".

 see https://github.com/nim-lang/Nim/pull/9766#issuecomment-449714771 that shows how #8794 is fixed; I can add other tests that show how the other issues are being fixed; but AFAIL this particular comment is addressed, marking as resolved

**Comment by timotheecour** [comment]
PTAL /cc @Araq @krux02 

> Didn't read through all the changes (too long), all I see is a decrease of the error message quality (seen in the diff of the test case). I don't like that.

that issue (as I mentioned above) was orhtogonal, and I've already fixed it in the meantime (see https://github.com/nim-lang/Nim/issues/10101)

> Where are the test cases for the issues that you fixed?

done, see:
* tests/errmsgs/t8794.nim
* tests/errmsgs/t9768.nim

for #9270 and #9767 , not sure it's needed since it only affects `--excessiveStackTrace:on` and `--listFullPaths` ; if we do need a test case, please advise how to do test for messages that involve absolute paths in testament (I'm had suggested a few ways before using mocking technique (of absolute file), but @araq was against it.

**Comment by timotheecour** [comment]
ping /cc @Araq @krux02

**Comment by timotheecour** [comment]
ping /cc @Araq @krux02

File: compiler/semcall.nim [hunk 2]
```diff
@@ -287,7 +287,20 @@ proc getMsgDiagnostic(c: PContext, flags: TExprFlags, n, f: PNode): string =
...
-    result = errUndeclaredField % ident & result
+    let sym = n.sons[1].typ.sym
+    var typeHint = ""
+    if sym == nil:
+      #[
+      Perhaps we're in a `compiles(foo.bar)` expression, or
+      in a concept, eg:
+        ExplainedConcept {.explain.} = concept o
+          o.foo is int
+      We coudl use: `(c.config $ n.sons[1].info)` to get more context.
```
Comment (krux02) [inline compiler/semcall.nim]: I would prefer normal # comments instead of block comments. But apart from that I think this PR is fine.

Comment (timotheecour) [reply compiler/semcall.nim]: ok, will fix that in another PR I'll send out shortly (today I hope)

Comment (timotheecour) [reply compiler/semcall.nim]: => PR #10239
