### PR TITLE
close #9901 add testcase

### LINKED ISSUE #9901: `times.parse` causes incorrect proveInit warning
### Example

```nim
import seqUtils
import times

proc parseMyDates(line: string): DateTime =
    result = parse(line, "yyyy-MM-dd")

var dateStrings = @["2018-12-01", "2018-12-02", "2018-12-03"]
var parsed = dateStrings.map(parseMyDates)
```

### Current Output

Compiler warnings:

```txt
scratch.nim(9, 25) template/generic instantiation of `map` from here
/usr/lib/nim/pure/collections/sequtils.nim(238, 10) Warning: Cannot prove that 'result' is initialized. This will become a compile time error in the future. [ProveInit]
```

### Expected Output

I'm new to Nim, so I was not expecting this code to output a warning. Quick question to IRC yielded a suggestion that this was likely a bug in `times` or `seqUtils`, so here I am.

If the warning is not a bug, then may I suggest clearer warning, or suggestion of solution? The current compiler output has me thoroughly confused.

### Possible Solution

Well, the solution I am using at the moment is ignore the warning. As discussed above, my solution would be either to fix whatever is causing the warning, or if the warning should stay, make it be easier to understand.

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

File: tests/errmsgs/t9901.nim [hunk 1]
```diff
@@ -0,0 +1,12 @@
+discard """
+  cmd: "nim c -r --warningAsError[ProveInit]:on $file"
+"""
+
```
Comment (timotheecour) [inline tests/errmsgs/t9901.nim]: how about:

```nim
{.warningAsError[ProveInit]:on.}
template main() =
  proc fn(): var int =
    discard
  discard fn()
doAssert not compiles(main())

# bug #9901
import std/[sequtils, times]
proc parseMyDates(line: string): DateTime =
  result = parse(line, "yyyy-MM-dd")
var dateStrings = @["2018-12-01", "2018-12-02", "2018-12-03"]
var parsed = dateStrings.map(parseMyDates)
discard parsed
```

and using:
```
discard """
  joinable: false
"""
```
on top (joinable:false because it seems to have global effect)

I also notice we don't really have a test for `ProveInit` (do we?) so this could be the one; it could be named tests/misc/tproveinit.nim

**Review by timotheecour — APPROVED** [review]
