### PR TITLE
fix #18844 (Atomics + ARC => Crash)

### LINKED ISSUE #18844: Compilation Failure - empty scalar initializer - Inheritable objects & Atomics [OA]RC on DEVEL
The following fails to compile with the listed error using ARC or ORC however compiles successfully on REFC

```nim
import atomics

type
  # Deprivation* = ref object of RootObj    # compiles
  Deprivation* = object of RootObj        # fails
    memes*: Atomic[int]
  Zoomer = object
    dopamine: Deprivation                 # fails
    # dopamine: ref Deprivation             # compiles

# discard Deprivation()                     # compiles
discard Zoomer()                          # fails
```

I have tagged which lines I have narrowed down to causing issues and what doesn't.

This was found while trying to use elijahrs lockfreequeue types as fields of objects.

```
C:\Users\PC\nimcache\cpsloop_r\@mcpsloop.nim.c:199:132: error: empty scalar initializer
 static NIM_CONST tyObject_Zoomer__yhOZMQHEaznD9aq8IQHJaMQ TM__8CKjD9bWE6mTvTNPLW3KYWw_2 = {{{(&NTIv2__DdWjNMQNgJ9aHiVjMo4gjYw_)}, {{}}}}

                        ^
C:\Users\PC\nimcache\cpsloop_r\@mcpsloop.nim.c:199:132: note: (near initialization for 'TM__8CKjD9bWE6mTvTNPLW3KYWw_2.dopamine.memes.value')
Error: execution of an external compiler program 'gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -O3 -fno-strict-aliasing -fno-ident   -IC:\Users\PC\.choosenim\toolchains\nim-#devel\lib -Ic:\Users\PC\Documents\Programming\ParthianProject\Modules\cps_minfosclient\cpsbridge -o C:\Users\PC\nimcache\cpsloop_r\@mcpsloop.nim.c.o C:\Users\PC\nimcache\cpsloop_r\@mcpsloop.nim.c' failed with exit code: 1
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #18844

### CODE REVIEW

File: lib/pure/concurrency/atomics.nim [hunk 1]
```diff
@@ -288,10 +288,10 @@ else:
...
       # Atomic* {.importcpp: "_Atomic('0)".} [T] = object
 
-      AtomicInt8 {.importc: "_Atomic NI8", size: 1.} = object
-      AtomicInt16 {.importc: "_Atomic NI16", size: 2.} = object
-      AtomicInt32 {.importc: "_Atomic NI32", size: 4.} = object
-      AtomicInt64 {.importc: "_Atomic NI64", size: 8.} = object
+      AtomicInt8 {.importc: "_Atomic NI8".} = int8
+      AtomicInt16 {.importc: "_Atomic NI16".} = int16
+      AtomicInt32 {.importc: "_Atomic NI32".} = int32
+      AtomicInt64 {.importc: "_Atomic NI64".} = int64
```
Comment (Araq) [inline lib/pure/concurrency/atomics.nim:294]: This form of wrapping keeps making problems for the Nim compiler. We should try to stick with `object` and find a different solution.

Comment (ringabout) [reply lib/pure/concurrency/atomics.nim:294]: > This form of wrapping keeps making problems for the Nim compiler. 

Can you tell me what problems it will cause or where is documented? What if I use distinct int64, will it make a difference?

Comment (Araq) [reply lib/pure/concurrency/atomics.nim:294]: Huge difference yes, `distinct` is fine. The problem is that type **aliases** are not supposed to change the meaning and can be substituted which is not true for an "importc alias" which is a contradiction.

File: lib/pure/concurrency/atomics.nim [hunk 2]
```diff
@@ -288,10 +288,15 @@ else:
...
-      AtomicInt8 {.importc: "_Atomic NI8", size: 1.} = object
-      AtomicInt16 {.importc: "_Atomic NI16", size: 2.} = object
-      AtomicInt32 {.importc: "_Atomic NI32", size: 4.} = object
-      AtomicInt64 {.importc: "_Atomic NI64", size: 8.} = object
+      AtomicInt8Impl {.importc: "_Atomic NI8".} = int8
+      AtomicInt16Impl {.importc: "_Atomic NI16".} = int16
+      AtomicInt32Impl {.importc: "_Atomic NI32".} = int32
+      AtomicInt64Impl {.importc: "_Atomic NI64".} = int64
+
+      AtomicInt8 = distinct AtomicInt8Impl
```
Comment (Araq) [inline lib/pure/concurrency/atomics.nim]:
```suggestion
      AtomicInt8 {.importc: "_Atomic NI8".} = distinct int8
```

etc.

Comment (ringabout) [reply lib/pure/concurrency/atomics.nim]: it doesn't work. I tried it in this commit
https://github.com/nim-lang/Nim/pull/18851/commits/6928928a7b368a18e81d821369b130d5ff95a521

It generates

```c
struct tyObject_Atomic__HUNz3b4OL2FRwBYYrZOtoQ {
NI64 value;
};
```
instead of
```c
struct tyObject_Atomic__HUNz3b4OL2FRwBYYrZOtoQ {
_Atomic NI64 value;
};
```

see https://github.com/nim-lang/Nim/runs/3605245177

So I just follow what jsbigint did here:
https://github.com/nim-lang/Nim/pull/16606

```nim
type JsBigIntImpl {.importc: "bigint".} = int
type JsBigInt* = distinct JsBigIntImpl
```

File: lib/pure/concurrency/atomics.nim (hunk 1 above)
Comment (ringabout) [reply lib/pure/concurrency/atomics.nim:294]: I see, thanks!

File: lib/pure/concurrency/atomics.nim (hunk 2 above)
Comment (Araq) [reply lib/pure/concurrency/atomics.nim]: Hmm. I need to think about this, but it looks to me we either need to make this work or officially embrace "importc type aliases".

**Comment by Araq** [comment]
Please roll it back to your previous fix, it was the better one, all things considered.

**Comment by ringabout** [comment]
Related: https://github.com/nim-lang/Nim/issues/18876

> Please roll it back to your previous fix, it was the better one, all things considered.

It may cause problems like https://github.com/nim-lang/Nim/issues/18876, I'm not sure.
