### PR TITLE
successX now correctly shows html output for `nim doc`, `nim jsondoc`; fix #13121

### LINKED ISSUE #13121: [TODO] pathutils.`/` can return invalid AbsoluteFile
pathutils.`/` can return invalid AbsoluteFile

### Example
```nim
import compiler/pathutils
proc main()=
  var a: AbsoluteDir
  let b = "../foo".RelativeFile
  let c: AbsoluteFile = a/b
  echo c

main()
```

### Current Output
```
../foo
```

### Expected Output
`../foo` is not absolute so there's a loophole in API

### Possible Solution
* making a empty behave as `cwd`
* throwing an exception is another option

### Additional Information

* devel a33b72af4960073b0dca95af3b430baade745b0b
* root cause of https://github.com/nim-lang/Nim/pull/13116#discussion_r365580322

Note: I dislike `AbsoluteFile,AbsoluteDir,RelativeFile,RelativeDir` as I've written in https://github.com/nim-lang/RFCs/issues/71 and I think we can find a better API; at least it's not exposed outside compiler

### PR DESCRIPTION
**Pull request by timotheecour**
* also, fixes https://github.com/nim-lang/Nim/issues/13121

### CODE REVIEW

File: compiler/docgen.nim [hunk 1]
```diff
@@ -39,7 +39,7 @@ type
     exampleCounter: int
     emitted: IntSet # we need to track which symbols have been emitted
                     # already. See bug #3655
-    destFile*: AbsoluteFile
+    destFile*: AbsoluteFile # that's a lie...
```
Comment (Araq) [inline compiler/docgen.nim]: Well ok, I believe you. Can we fix it so that it doesn't lie?

Comment (timotheecour) [reply compiler/docgen.nim]: done (https://github.com/nim-lang/Nim/issues/13121 was root caused; this PR includes a fix for it)

**Comment by timotheecour** [comment]
PTAL.
* I've also fixed https://github.com/nim-lang/Nim/issues/13121 to address above comment
* i added semi-unrelated change:
```
Hint: 53431 LOC; 0.131 sec; 46.711MiB peakmem; Debug build; /patho/thello.nim proj; /patho/thello.html out [SuccessX]                                                    
=>
Hint: 53431 LOC; 0.131 sec; 46.711MiB peakmem; Debug build; proj: /patho/thello.nim; out: /patho/thello.html [SuccessX]
```

which is less weird looking

File: compiler/options.nim [hunk 2]
```diff
@@ -244,6 +244,7 @@ type
     searchPaths*: seq[AbsoluteDir]
     lazyPaths*: seq[AbsoluteDir]
     outFile*: RelativeFile
+    outFileAlt*: AbsoluteFile ## eg html produced by `nim doc`
```
Comment (Araq) [inline compiler/options.nim]: Why do we need this?

File: compiler/main.nim [hunk 3]
```diff
@@ -363,8 +363,11 @@ proc mainCommand*(graph: ModuleGraph) =
                 elif isDefined(conf, "release"): "Release"
                 else: "Debug"
     let sec = formatFloat(epochTime() - conf.lastCmdTime, ffDecimal, 3)
-    let project = if optListFullPaths in conf.globalOptions: $conf.projectFull else: $conf.projectName
-    let output = if optListFullPaths in conf.globalOptions: $conf.getOutFileFull else: $conf.outFile
+    template postprocess(path): untyped =
+      if optListFullPaths in conf.globalOptions: $path
+      else: path.`$`.lastPathPart
```
Comment (Araq) [inline compiler/main.nim]: I don't understand this.

File: compiler/docgen.nim [hunk 4]
```diff
@@ -1054,12 +1054,13 @@ proc writeOutput*(d: PDoc, useWarning = false) =
   if optStdout in d.conf.globalOptions:
     writeRope(stdout, content)
   else:
-    template outfile: untyped = d.destFile
```
Comment (Araq) [inline compiler/docgen.nim]: But this style avoided a copy.

Comment (timotheecour) [reply compiler/docgen.nim]: IIUC it's guaranteed to be a move in this case; for eg see below:
```nim
type Foo = distinct string
type Bar = ref object
  foo: Foo

proc main(a: Bar)=
  let b = a.foo
  doAssert cast[int](a.foo.string[0].unsafeAddr) == cast[int](b.string[0].unsafeAddr)

let a = Bar(foo: "abc".Foo)
main(a)
```

if i added `doAssert cast[int](outfile.string[0].unsafeAddr) == cast[int](d.destFile.string[0].unsafeAddr)` below `let outfile = d.destFile`, the assert would also pass. 

`let` is cleaner in this case

Comment (Araq) [reply compiler/docgen.nim]: That's a bug, finally addressed in --gc:arc, the move is unsound.

File: compiler/options.nim (hunk 2 above)
Comment (timotheecour) [reply compiler/options.nim]: fixed; now re-using `outFile` instead and it works

File: compiler/main.nim (hunk 3 above)
Comment (timotheecour) [reply compiler/main.nim]: you had commented here https://github.com/nim-lang/Nim/pull/13043#issuecomment-570941009
> I see the value in it but omg it's verbose

and this allows shortening things when `--listfullpaths:off` (as was done here https://github.com/nim-lang/Nim/pull/13043)

that's the simplest code I can think of that does what we want

File: compiler/docgen.nim (hunk 4 above)
Comment (timotheecour) [reply compiler/docgen.nim]: * but `--gc:arc` also makes the assert pass ; let's discuss this somewhere dedicated to this instead of here ; EDIT :here: https://github.com/nim-lang/Nim/issues/13140
* I've changed it back to `template outfile: untyped = d.destFile` to unblock this PR;  `byRef: outfile = d.destFile` would be what I'd use once https://github.com/nim-lang/Nim/pull/11824 is merged; and it's also shorter than `template outfile: untyped = d.destFile`

**Comment by timotheecour** [comment]
PTAL

File: compiler/main.nim (hunk 3 above)
Comment (Araq) [reply compiler/main.nim]: ``lastPathPart`` is never what I want as my filenames do not in end in slashes anyway. The old code

```nim

let project = if optListFullPaths in conf.globalOptions: $conf.projectFull else: $conf.projectName
let output = if optListFullPaths in conf.globalOptions: $conf.getOutFileFull else: $conf.outFile

```

was perfectly clear code. Clearer than your replacement which I still don't understand.

File: compiler/pathutils.nim [hunk 5]
```diff
@@ -26,6 +26,14 @@ proc copyFile*(source, dest: AbsoluteFile) =
 
 proc removeFile*(x: AbsoluteFile) {.borrow.}
 
+template toRelative(x: typedesc[AnyPath]): typedesc =
+  when x is AbsoluteFile | RelativeFile: RelativeFile else: RelativeDir
+
+proc lastPathPart*(x: AnyPath): auto =
```
Comment (Araq) [inline compiler/pathutils.nim]: The following rule served me well: If you cannot write down the return type what you wrote is not a ``proc`` or ``func``, but something else.

File: compiler/pathutils.nim [hunk 6]
```diff
@@ -54,21 +62,21 @@ when true:
 
   proc `==`*[T: AnyPath](x, y: T): bool = eqImpl(x.string, y.string)
 
-  proc `/`*(base: AbsoluteDir; f: RelativeFile): AbsoluteFile =
```
Comment (Araq) [inline compiler/pathutils.nim:57]: In my world bugfixes are not a justification to rewrite code in a style you happen to like better.

File: compiler/main.nim (hunk 3 above)
Comment (timotheecour) [reply compiler/main.nim]: old code was incorrect because of the logic inside `absOutFile` which sometimes adds `.out` suffix and wasn't reflected here; I've now fixed it differently without using lastPathPart and it should work in all cases

File: compiler/pathutils.nim (hunk 5 above)
Comment (timotheecour) [reply compiler/pathutils.nim]: I've removed `lastPathPart`

File: compiler/pathutils.nim (hunk 6 above)
Comment (timotheecour) [reply compiler/pathutils.nim:57]: reverted to the previous way (which had a lot of code duplication) and instead using a `postProcessBase` which handles the empty `base` case; the correct behavior would be to throw when base is `empty` as was ruled here https://github.com/nim-lang/Nim/pull/10018#issuecomment-448192956 however this would require more unrelated changes and should be done in separate PR; this PR doesn't change externally visible behavior but at least doesn't "lie" (see https://github.com/nim-lang/Nim/pull/13116#discussion_r365580322)

**Comment by timotheecour** [comment]
PTAL
