### PR TITLE
close #10734 add testcase

### LINKED ISSUE #10734: Trailing colon in object definition and case within proc crashes compiler
Might be related to #10677.

### Example (run with `nim check`)
```nim
type
  T = object
    a:
proc p =
  case
```

### Current Output
```
t.nim(4, 1) Error: invalid indentation
t.nim(4, 6) Error: invalid indentation
t.nim(6, 1) Error: expression expected, but found '[EOF]'
t.nim(3, 5) Error: 'proc' is not a concrete type; for a callback without parameters use 'proc()'
t.nim(4, 6) Error: undeclared identifier: 'p'
t.nim(4, 6) Error: 'p' cannot be assigned to
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected
Not crashing

### Additional Information
```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-02-24
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 28a83a838821cbe3efc8ddd412db966ca164ef5c
active boot switches: -d:release -d:useLinenoise
```

### PR DESCRIPTION
**Pull request by ringabout**
close #10734 add testcase

### CODE REVIEW

File: tests/errmsgs/t10734.nim [hunk 1]
```diff
@@ -0,0 +1,18 @@
+discard """
+  cmd: "nim check $file"
+  errormsg: ""
+  nimout: '''t10734.nim(17, 1) Error: invalid indentation
```
Comment (timotheecour) [inline tests/errmsgs/t10734.nim]: general comment: always prefer newline after triple double quote string and triple single quote string, it's the same (see spec) but is more readable:
```
  nimout: '''t10734.nim(17, 1) Error: invalid indentation
```
=>

```
  nimout: '''
t10734.nim(17, 1) Error: invalid indentation
```
