### PR TITLE
error message for accidental use of macro

### LINKED ISSUE #10489: Accidental use of macro name results in unhandled exception
When accidentally using the name of a macro without calling semantics, compilation fails with an unhandled exception:

```nimrod
import macros

macro m(body: untyped): untyped =
  body

let x = m
```

Error:

```
../lib/system.nim(2976)  sysFatal
Error: unhandled exception: /home/fabian/bin/nim-repo/compiler/ccgtypes.nim(180, 17) `false` mapType [AssertionError]
```

Changing the expression to `m()` gives a proper error message:

```
report_2019_01_29_table_constructor.nim(6, 10) Error: type mismatch: got <>
but expected one of: 
macro m(body: untyped): untyped

expression: m()
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-01-12
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 2ee2022c29ec4774eda51cb431052a9fc24982a7
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by krux02**
fix #10489

### CODE REVIEW

File: compiler/semstmts.nim [hunk 1]
```diff
@@ -447,11 +447,16 @@ proc semVarOrLet(c: PContext, n: PNode, symkind: TSymKind): PNode =
 
     var def: PNode = c.graph.emptyNode
     if a.sons[length-1].kind != nkEmpty:
+      let debug = a.sons[length-1].kind == nkIdent and a.sons[length-1].ident.s == "mooboo"
```
Comment (LemonBoy) [inline compiler/semstmts.nim]: oops :)

Comment (krux02) [reply compiler/semstmts.nim]: oh yea, thanks for pointing it out.

**Comment by Araq** [comment]
This also compiles but shouldn't:

```nim

macro m(body: untyped): typed =
  body

const c = m
```
