### PR TITLE
post expr blocks colon fix + correct grammar

### LINKED ISSUE #21982: Trailing `:` in `if` branch of `if`/`else/` successfully parses
### Description

```nim
if true:
  if true:  # unnecessary, but ensure `IND{=}` can't match (could use `block:`, etc)
    discard default int:
else:
  discard
```

The generated AST is, according to `dumpAstGen`, identical whether using `discard default(int)` or `discard default(int):`, or if one wants the `nnkCommand` version, `discard default int` or `discard default int:`.

https://nim-lang.org/docs/manual.html#syntax-grammar doesn't seem to support this parse:
```
colon = ':' COMMENT?
exprColonEqExpr = expr (':'|'=' expr)?
exprColonEqExprList = exprColonEqExpr (comma exprColonEqExpr)* (comma)?
setOrTableConstr = '{' ((exprColonEqExpr comma)* | ':' ) '}'
tupleConstr = '(' optInd (exprColonEqExpr comma?)* optPar ')'
arrayConstr = '[' optInd (exprColonEqExpr comma?)* optPar ']'
primarySuffix = '(' (exprColonEqExpr comma?)* ')'
      | '.' optInd symbol ('[:' exprList ']' ( '(' exprColonEqExpr ')' )?)? generalizedLit?
      | DOTLIKEOP optInd symbol generalizedLit?
      | '[' optInd exprColonEqExprList optPar ']'
      | '{' optInd exprColonEqExprList optPar '}'
      | &( '`'|IDENT|literal|'cast'|'addr'|'type') expr # command syntax
pragma = '{.' optInd (exprColonEqExpr comma?)* optPar ('.}' | '}')
declColonEquals = identWithPragma (comma identWithPragma)* comma?
                  (':' optInd typeDesc)? ('=' optInd expr)?
identColonEquals = IDENT (comma IDENT)* comma?
     (':' optInd typeDesc)? ('=' optInd expr)?)
```
et cetera

- `exprColonEqExpr` would require an `expr` following it, but the following line is indented less, not more
- `exprColonEqExprList` is made up of `exprColonEqExpr`, so see above
- `setOrTableConstr` requires a literal `{` which does not appear
- `tupleConstr` requires a literal `(` which does not appear
- `arrayConstr` requires a literal `[` which does not appear
- `primarySuffix` requires either a literal `(` (no), `.` (no), `[` (no), or `{` (no) to incorporate a colon
- for `pragma`, see `exprColonEqExpr`
- `declColonEquals`, `identColonEquals`, or `paramListColon` would require a `typeDesc`, but there's no such `typeDesc` in this example
- `tupleDecl` incorporates a colon only by reference from `identColonEquals`
- `paramList` incorporates a colon only by reference from `declColonEquals`
- `doBlock` would require a literal `do`, not present

It's maybe trying to match
```
postExprBlocks = ':' stmt? ( IND{=} doBlock
                           | IND{=} 'of' exprList ':' stmt
                           | IND{=} 'elif' expr ':' stmt
                           | IND{=} 'except' exprList ':' stmt
                           | IND{=} 'finally' ':' stmt
                           | IND{=} 'else' ':' stmt )*
```
But `IND{=}` should not be matching any (synthetic) tokens here, because the two `discard`s/`else` are all at different indentation levels.

Using `macros.dumpAstGen` to show the result:
```
StmtList
  IfStmt
    ElifBranch
      Ident "true"
      StmtList
        IfStmt
          ElifBranch
            Ident "true"
            StmtList
              DiscardStmt
                Command
                  Ident "default"
                  Ident "int"
    Else
      StmtList
        DiscardStmt
          Empty
```
that is, the
```
            StmtList
              DiscardStmt
                Command
                  Ident "default"
                  Ident "int"
```
is a leaf in the AST, and it's not attaching the
```
    Else
      StmtList
        DiscardStmt
          Empty
```
to the `default int`, but the outer `if`, per the `IND` levels. This argues against the `postExprBlocks` parse as well.

### Nim Version

```
Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-05-21
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release
```

```
Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-05-31
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: b880cdff49576c0eb83a043cbae595d3587c95b4
active boot switches: -d:release
```

### Current Output

_No response_

### Expected Output

```text
repro.nim(7, 26) Error: invalid indentation
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
fixes #21982

Grammar: Account for all the places that parse `postExprBlocks` on `tkDo`. `postExprBlocks` in `typeDefValue` and `(commandStart ...)` in `primary` are supposed to be optional. Calls that end with `:` now require being followed by either a statement or a proper post expr block.

### CODE REVIEW

**Comment by metagn** [comment]
Seemingly only one package has to be updated: https://github.com/SciNim/Unchained/pull/41

~~Will use fork URL if not merged in a couple days~~ Was merged

**Comment by metagn** [comment]
CI is fine now, failure is unrelated

File: compiler/parser.nim [hunk 1]
```diff
@@ -1500,7 +1504,7 @@ proc postExprBlocks(p: var Parser, x: PNode): PNode =
     result = makeCall(result)
     getTok(p)
     skipComment(p, result)
-    if p.tok.tokType notin {tkOf, tkElif, tkElse, tkExcept, tkFinally}:
+    if not (p.tok.tokType in {tkOf, tkElif, tkElse, tkExcept, tkFinally} and sameInd(p)):
```
Comment (Araq) [inline compiler/parser.nim:1507]: Doesn't this imply that now

```nim

match x
of ...

```

does not work anymore? Or maybe

```nim

match x
  of ...

```

doesn't anymore?

**Comment by Araq** [comment]
Apart from my question, it looks great!

File: compiler/parser.nim (hunk 1 above)
Comment (metagn) [reply compiler/parser.nim:1507]: This is not the actual parsing step, this is just the lookahead triggered by the colon. The actual parsing below does check for `sameInd` (the `while sameInd(p)` part), so only the following worked, which is still true:

```nim
match x:
of ...
```

The problem is that this lookahead ate the colon token when any `of/else/...` token followed, regardless of indent.

```nim
  match x: # colon here gets eaten because the next token is `else`
else: ... # but not same indent, so the call just becomes match(x)
```

This PR just corrects the lookahead to trigger only when post expr blocks will be parsed.
