### PR TITLE
better procvar ambiguity errors, clean up after #20457

### LINKED ISSUE #6359: Unclear error message when assigning ambiguous proc to variable
Test
```nim
proc foo(a: int) = discard
proc foo(b: int) = discard
let f = foo
```
Result:
```nim
Test.nim(3, 5) Error: invalid type: 'None'
```
My original case wasn't as obvious as this example. I would expect a message along the lines of `Error: ambiguous call; both ...`
***
```nim
>nim -v
Nim Compiler Version 0.17.2 (2017-09-10) [Windows: i386]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 3bf8ced69e7b2b5c4c0ef57d8aa3726f2e5906fc
active boot switches: -d:release
```

### LINKED ISSUE #13849: Tuple type mismatch with proc() - Returns None
For some reason sending a proc() to a tuple returns None with *specific* proc names. By far I get None when naming procs as ***close() , dispose(), finished()***

type mismatch: got <int, tuple of (proc (){.noSideEffect, gcsafe, locks: 0.}, None)>

### Example
```nim
proc start*()=discard
proc tick*(delta:float)=discard
proc close*()=discard

# just to show the tuple
proc set_scn_ev*(id:int, events: tuple[start: proc(){.nimcall.}, close: proc(){.nimcall.}])=
  discard
# proc check
proc set_scn_ev*(id:int, ev: proc(){.nimcall.})=
  discard

set_scn_ev(id_scene_game,(start,close)) # error, close is treated as None
set_scn_ev(id_scene_game,close) # but this Is OK
```

### Current Output
```
type mismatch: got <int, tuple of (proc (){.noSideEffect, gcsafe, locks: 0.}, None)>
```

### Expected Output
It should compile

```
Nim Compiler Version 1.0.6 [Windows: amd64]
Nim Compiler Version 1.2.0 [Windows: amd64]
```

### PR DESCRIPTION
**Pull request by metagn**
fixes #6359, fixes #13849, follows up #20457

#18785 is related: The error message is fixed, however there is no way to disambiguate procs in different scopes in the same module.

### CODE REVIEW

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -88,13 +88,30 @@ proc semExprWithType(c: PContext, n: PNode, flags: TExprFlags = {}, expectedType
...
-      result[0].sym.kind == skEnumField:
-    # if overloaded enum field could not choose a type from a closed list,
-    # choose the first resolved enum field, i.e. the latest in scope
-    # to mirror old behavior
-    msgSymChoiceUseQualifier(c, result, hintAmbiguousEnum)
-    result = result[0]
+      efTypeAllowed in flags and
+      result.kind == nkClosedSymChoice and result.len > 0:
+    let first = result[0].sym
+    if first.kind == skEnumField:
```
Comment (Araq) [inline compiler/semexprs.nim]: Use a helper proc for this logic.

Comment (metagn) [reply compiler/semexprs.nim]: Done
