### PR TITLE
fixes #22481; fixes `card` undefined misalignment behavior

### LINKED ISSUE #22481: Undefined behaviorwith `set` `card()` on non-aligned pointer from `cardSetImpl`/`countBits64cast` on `ptr uint64`
### Description

```nim
iterator count0(): int {.closure.} =
  var x: uint8
  var y: set[uint8]    # verified that at least `int8`, `uint16`, and `int16` trigger this too
  echo cast[uint64](unsafeAddr y)
  discard card(y)
  yield 0

for _ in count0():
  discard
```

https://github.com/nim-lang/Nim/blob/a660c17d309e2b077c610fd8c8c697944cff676d/lib/system/sets.nim#L13-L23

The `countBits64((cast[ptr uint64](s[i].unsafeAddr))[])` is the proximate trigger.

### Nim Version

```
Nim Compiler Version 1.6.15 [Linux: amd64]
Compiled at 2023-08-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a2521b1dc7efc775b6cf9a299b51eee44fbd3e81
active boot switches: -d:release
```

```
Nim Compiler Version 2.0.1 [Linux: amd64]
Compiled at 2023-08-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 037f536e7ee25c4baf23dff8a4525825c506442c
active boot switches: -d:release
```

```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a660c17d309e2b077c610fd8c8c697944cff676d
active boot switches: -d:release
```

### Current Output

```text
$ for i in Nim16 Nim20 NimDevel; do rm .cache/nim -r && NimDevel/bin/nim c -r --passC="-fsanitize=undefined" --passL="-fsanitize=undefined" a; done
139979834110065
.cache/nim/a_d/@ma.nim.c:226:10: runtime error: load of misaligned address 0x7f4f9849b071 for type 'NU64', which requires 8 byte alignment
0x7f4f9849b071: note: pointer points here
 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
              ^
139667051241585
.cache/nim/a_d/@ma.nim.c:226:10: runtime error: load of misaligned address 0x7f06c4f9e071 for type 'NU64', which requires 8 byte alignment
0x7f06c4f9e071: note: pointer points here
 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
              ^
140276090032241
.cache/nim/a_d/@ma.nim.c:226:10: runtime error: load of misaligned address 0x7f9492845071 for type 'NU64', which requires 8 byte alignment
0x7f9492845071: note: pointer points here
 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
              ^
```

### Expected Output

```text
No UB unaligned pointer access
```

### Possible Solution

_No response_

### Additional Information

https://github.com/nim-lang/Nim/issues/22387#issuecomment-1667013709

### PR DESCRIPTION
**Pull request by ringabout**
fixes #22481

### CODE REVIEW

File: lib/system/sets.nim [hunk 1]
```diff
@@ -13,9 +13,11 @@
 proc cardSetImpl(s: ptr UncheckedArray[uint8], len: int): int {.inline.} =
   var i = 0
   result = 0
+  var num = uint64(0)
```
Comment (arnetheduck) [inline lib/system/sets.nim]: `{.noinit.}` really and it can safely be moved into the loop (which prevents usages from leaking outside of the loop accidentally

Comment (ringabout) [reply lib/system/sets.nim]: Make sense.

Comment (Araq) [reply lib/system/sets.nim]: Nit pick, use

```suggestion
  var num = 0'u64
```
