### PR TITLE
fixes #24721; Table add missing sink

### LINKED ISSUE #24721: Table add missing `sink`
### Description

Table should not need to copy its key argument during insertion:

```nim
import std/tables
type NoCopies = object

proc `=copy`(a: var NoCopies, b: NoCopies) {.error.}

var t: Table[NoCopies, NoCopies]
t[NoCopies()] = NoCopies() # only moves
```

The same _probably_ holds for a lot of std lib containers, ie the concept applies to all of them.

### Nim Version

2.2

### Current Output

```text
Error: '=copy' is not available for type <NoCopies>; requires a copy because it's not the last read of 'key'; try to make key a 'sink' parameter; routine: rawInsert
```

### Expected Output

```text

```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #24721

### CODE REVIEW

**Comment by arnetheduck** [comment]
this PR is nice because fixes Table, but he same applies to every stdlib module (sets, lists etc) - ie the ideal would be that they all got fixed together

**Comment by ringabout** [comment]
>  same applies to every stdlib module (sets, lists etc) - ie the ideal would be that they all got fixed together

Okay, I will add them once tests pass for tables

**Comment by Araq** [comment]
>  ie the ideal would be that they all got fixed together

That's a bad idea for bisecting codegen regressions.

**Comment by arnetheduck** [comment]
> That's a bad idea for bisecting codegen regressions.

as long as I don't have to open an issue for every function :stuck_out_tongue:

File: lib/pure/collections/tables.nim [hunk 1]
```diff
@@ -313,7 +313,7 @@ proc toTable*[A, B](pairs: openArray[(A, B)]): Table[A, B] =
   result = initTable[A, B](pairs.len)
   for key, val in items(pairs): result[key] = val
 
-proc `[]`*[A, B](t: Table[A, B], key: A): lent B =
+proc `[]`*[A, B](t: Table[A, B], key: sink A): lent B =
```
Comment (Araq) [inline lib/pure/collections/tables.nim]: Nope. This is wrong.

File: lib/pure/collections/tables.nim [hunk 2]
```diff
@@ -336,7 +336,7 @@ proc `[]`*[A, B](t: Table[A, B], key: A): lent B =
       echo a['z']
   get(t, key)
 
-proc `[]`*[A, B](t: var Table[A, B], key: A): var B =
+proc `[]`*[A, B](t: var Table[A, B], key: sink A): var B =
```
Comment (Araq) [inline lib/pure/collections/tables.nim]: Wrong.

File: lib/pure/collections/tables.nim [hunk 3]
```diff
@@ -864,7 +864,7 @@ proc newTableFrom*[A, B, C](collection: A, index: proc(x: B): C): TableRef[C, B]
     for item in collection:
       result[index(item)] = item
 
-proc `[]`*[A, B](t: TableRef[A, B], key: A): var B =
+proc `[]`*[A, B](t: TableRef[A, B], key: sink A): var B =
```
Comment (Araq) [inline lib/pure/collections/tables.nim]: Wrong.

File: lib/pure/collections/tables.nim [hunk 4]
```diff
@@ -1382,7 +1382,7 @@ proc toOrderedTable*[A, B](pairs: openArray[(A, B)]): OrderedTable[A, B] =
   result = initOrderedTable[A, B](pairs.len)
   for key, val in items(pairs): result[key] = val
 
-proc `[]`*[A, B](t: OrderedTable[A, B], key: A): lent B =
+proc `[]`*[A, B](t: OrderedTable[A, B], key: sink A): lent B =
```
Comment (Araq) [inline lib/pure/collections/tables.nim]: Wrong.

File: lib/pure/collections/tables.nim [hunk 5]
```diff
@@ -1406,7 +1406,7 @@ proc `[]`*[A, B](t: OrderedTable[A, B], key: A): lent B =
 
   get(t, key)
 
-proc `[]`*[A, B](t: var OrderedTable[A, B], key: A): var B =
+proc `[]`*[A, B](t: var OrderedTable[A, B], key: sink A): var B =
```
Comment (Araq) [inline lib/pure/collections/tables.nim]: Wrong.

File: lib/pure/collections/tables.nim [hunk 6]
```diff
@@ -1884,7 +1884,7 @@ proc newOrderedTable*[A, B](pairs: openArray[(A, B)]): OrderedTableRef[A, B] =
     for key, val in items(pairs): result[key] = val
 
 
-proc `[]`*[A, B](t: OrderedTableRef[A, B], key: A): var B =
+proc `[]`*[A, B](t: OrderedTableRef[A, B], key: sink A): var B =
```
Comment (Araq) [inline lib/pure/collections/tables.nim]: Wrong.

File: lib/pure/collections/tables.nim [hunk 7]
```diff
@@ -2345,7 +2345,7 @@ proc toCountTable*[A](keys: openArray[A]): CountTable[A] =
   result = initCountTable[A](keys.len)
   for key in items(keys): result.inc(key)
 
-proc `[]`*[A](t: CountTable[A], key: A): int =
+proc `[]`*[A](t: CountTable[A], key: sink A): int =
```
Comment (Araq) [inline lib/pure/collections/tables.nim]: Wrong.

File: lib/pure/collections/tables.nim [hunk 8]
```diff
@@ -2703,7 +2703,7 @@ proc newCountTable*[A](keys: openArray[A]): CountTableRef[A] =
   {.noSideEffect.}:
     for key in items(keys): result.inc(key)
 
-proc `[]`*[A](t: CountTableRef[A], key: A): int =
+proc `[]`*[A](t: CountTableRef[A], key: sink A): int =
```
Comment (Araq) [inline lib/pure/collections/tables.nim]: Wrong.
