### PR TITLE
fix sym of created generic instantiation type

### LINKED ISSUE #22639: `sizeof` for static arrays can yield wrong results
### Description

While `sizeof` generally works correctly also for arrays that are fields for objects of the form `Foo[N: static int]`, when some macro magic comes into play, the size is sometimes not correctly reported / a debug compiler throws an assertion error.

Maybe this can be simplified further, but it shows the problem:

```nim
import macros

type
  Spectrum*[N: static int] = object
    data*: array[N, float]

  AngleInterpolator* = object
    data*: seq[Spectrum[60]]

proc initInterpolator*(num: int): AngleInterpolator =
  result = AngleInterpolator()
  for i in 0 ..< num:
    result.data.add Spectrum[60]()

macro genCompatibleTuple*(t: typed): untyped =
  let typ = t.getType[1].getTypeImpl[2]
  result = nnkTupleTy.newTree()
  for i, ch in typ: # is `nnkObjectTy`
    result.add nnkIdentDefs.newTree(ident(ch[0].strVal), # ch is `nnkIdentDefs`
                                    ch[1],
                                    newEmptyNode())


proc copyFlat[T: object | tuple](x: T) =
  var tmp: genCompatibleTuple(T)
  echo "TMP type: ", typeof(tmp), " of size? ", sizeof(tmp) # <- wrong, should be 480 instead of 8
  for field, val in fieldPairs(x):
    # the field individually is reported correctly, but the full size is not
    echo field, " of field size: ", sizeof(val), " full size of type? ", sizeof(tmp)

let reflectivity = initInterpolator(1)
for el in reflectivity.data:
  copyFlat(el)
echo sizeof(reflectivity.data[0]) # <- this is correct!
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-04
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c5495f40d5d881e6bd155c9e6c9c6e5e49b749a7
active boot switches:

(the debug compiler that produces the assertion error; I got the same problem on a pre 2.0 compiler though)

### Current Output

```text
With a `-d:danger` compiler:

TMP type: tuple[data: array[0..static(pred(N, 1)), float]] of size? 1
data of field size: 480 full size of type? 1
480

With a `-d:debug` compiler we crash:

/home/basti/src/nim/nim_git_repo/compiler/nim.nim(167) nim
/home/basti/src/nim/nim_git_repo/compiler/nim.nim(122) handleCmdLine
/home/basti/src/nim/nim_git_repo/compiler/main.nim(307) mainCommand
/home/basti/src/nim/nim_git_repo/compiler/main.nim(276) compileToBackend
/home/basti/src/nim/nim_git_repo/compiler/main.nim(138) commandCompileToC
/home/basti/src/nim/nim_git_repo/compiler/pipelines.nim(299) compilePipelineProject
/home/basti/src/nim/nim_git_repo/compiler/pipelines.nim(229) compilePipelineModule
/home/basti/src/nim/nim_git_repo/compiler/pipelines.nim(177) processPipelineModule
/home/basti/src/nim/nim_git_repo/compiler/pipelines.nim(24) processPipeline
/home/basti/src/nim/nim_git_repo/compiler/cgen.nim(2092) genTopLevelStmt
/home/basti/src/nim/nim_git_repo/compiler/cgen.nim(1127) genProcBody
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2755) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2744) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3056) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(650) genBlock
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2755) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2755) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2755) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3056) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(650) genBlock
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2755) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3077) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(626) genWhileStmt
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2755) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2744) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2755) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3011) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgcalls.nim genCall
/home/basti/src/nim/nim_git_repo/compiler/ccgcalls.nim(817) genAsgnCall
/home/basti/src/nim/nim_git_repo/compiler/ccgcalls.nim(420) genPrefixCall
/home/basti/src/nim/nim_git_repo/compiler/cgen.nim(732) initLocExpr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2930) expr
/home/basti/src/nim/nim_git_repo/compiler/cgen.nim(1360) genProc
/home/basti/src/nim/nim_git_repo/compiler/cgen.nim(1334) genProcNoForward
/home/basti/src/nim/nim_git_repo/compiler/cgen.nim(1195) genProcAux
/home/basti/src/nim/nim_git_repo/compiler/cgen.nim(1127) genProcBody
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2755) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3107) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1270) genTryGoto
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2744) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3058) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(2755) genStmtList
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(1639) genStmts
/home/basti/src/nim/nim_git_repo/compiler/ccgexprs.nim(3078) expr
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(423) genVarStmt
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(406) genSingleVar
/home/basti/src/nim/nim_git_repo/compiler/ccgstmts.nim(367) genSingleVar
/home/basti/src/nim/nim_git_repo/compiler/cgen.nim(601) assignLocalVar
/home/basti/src/nim/nim_git_repo/compiler/cgen.nim(584) localVarDecl
/home/basti/src/nim/nim_git_repo/compiler/ccgtypes.nim(1110) getTypeDesc
/home/basti/src/nim/nim_git_repo/compiler/ccgtypes.nim(1081) getTypeDescAux
/home/basti/src/nim/nim_git_repo/compiler/ccgtypes.nim(824) getTupleDesc
/home/basti/src/nim/nim_git_repo/compiler/ccgtypes.nim(1014) getTypeDescAux
/home/basti/src/nim/nim_git_repo/compiler/int128.nim(66) toInt64
/home/basti/src/nim/nim_git_repo/lib/std/assertions.nim(41) failedAssertImpl
/home/basti/src/nim/nim_git_repo/lib/std/assertions.nim(34) raiseAssert
Error: unhandled exception: /home/basti/src/nim/nim_git_repo/compiler/int128.nim(66, 11) `arg.sdata(3) == -1` out of range [AssertionDefect]
```

### Expected Output

```text
TMP type: tuple[data: array[0..static(pred(N, 1)), float]] of size? 480
data of field size: 480 full size of type? 480
480
```

### Possible Solution

The `sizeof` call handes the `array` type here: 

https://github.com/nim-lang/Nim/blob/devel/compiler/sizealignoffsetimpl.nim#L264-L276,

which calls `lengthOrd` with the problematic `lastOrd` call here:

https://github.com/nim-lang/Nim/blob/devel/compiler/types.nim#L951

As we have a `tyRange` in the `tyArray` of the form `0..static(pred(N, 1))`, we end up in:

https://github.com/nim-lang/Nim/blob/devel/compiler/types.nim#L867-L870

calling `getOrdValue`. Now the issue is that `getOrdValue` gets a `nkStaticExpr`, which is not handled here:

https://github.com/nim-lang/Nim/blob/devel/compiler/types.nim#L120-L142

meaning it returns `onError`. That eventually leads to the assertion error in the debug compiler. 

Intuitively it seems like the static expression should simply be evaluated to its actual value before / in the `sizeof` logic, but realistically I suppose the actual solution lies further up the stack? I suppose the actual bug is that we are still left with a static expression at this point in the process in the first place? My attempts at fixing this have all failed at least. :)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
fixes #22639

A `tyGenericInst` has its last son as the instantiated body of the original generic type. However this type keeps its original `sym` field from the original generic types, which means the sym's type is uninstantiated. This causes problems in the implementation of `getType`, where it uses the `sym` fields of types to represent them in AST, the relevant example for the issue being [here](https://github.com/nim-lang/Nim/blob/d13aab50cf465a7f2edf9c37a4fa30e128892e72/compiler/vmdeps.nim#L191) called from [here](https://github.com/nim-lang/Nim/blob/d13aab50cf465a7f2edf9c37a4fa30e128892e72/compiler/vmdeps.nim#L143).

To fix this, create a new symbol from the original symbol for the instantiated body during the creation of `tyGenericInst`s with the appropriate type. Normally `replaceTypeVarsS` would be used for this, but here it seems to cause some recursion issue (immediately gives an error like "cannot instantiate HSlice[T, U]"), so we directly set the symbol's type to the instantiated type.

Avoiding recursion means we also cannot use `replaceTypeVarsN` for the symbol AST, and the symbol not having any AST crashes the implementation of `getType` again [here](https://github.com/nim-lang/Nim/blob/d13aab50cf465a7f2edf9c37a4fa30e128892e72/compiler/vmdeps.nim#L167), so the symbol AST is set to the original generic type AST for now which is what it was before anyway.

Not sure about this because not sure why the recursion issue is happening, putting it at the end of the proc doesn't help either. Also not sure if the `cl.owner != nil and s.owner != cl.owner` condition from `replaceTypeVarsS` is relevant here. This might also break some code if it depended on the original generic type symbol being given.

### CODE REVIEW

File: compiler/semtypinst.nim [hunk 1]
```diff
@@ -433,6 +433,18 @@ proc handleGenericInvocation(cl: var TReplTypeVars, t: PType): PType =
...
+  let origSym = newbody.sym
+  if origSym != nil and sfFromGeneric notin origSym.flags:
+    # same as `replaceTypeVarsS` but directly set the type without recursion:
+    newbody.sym = copySym(origSym, cl.c.idgen)
+    incl(newbody.sym.flags, sfFromGeneric)
+    newbody.sym.owner = origSym.owner
+    newbody.sym.typ = newbody
+    # unfortunately calling `replaceTypeVarsN` causes recursion, so this AST
+    # is the original generic body AST
+    newbody.sym.ast = origSym.ast
```
Comment (Araq) [inline compiler/semtypinst.nim]: Not saying it's a good idea but you could use `copyTree(origSym.ast)` here at least.

Comment (metagn) [reply compiler/semtypinst.nim]: Shouldn't matter but ok
