### PR TITLE
JS backend properly extends string with `setLen`

### LINKED ISSUE #20235: `var s = ""; s.setLen(4); echo s[0]` results in error for js
### What happened?

```nim
proc main =
  var s = ""
  s.setLen(4)
  echo s[0]

main()
```
`nim js -r -d:danger`
```
Hint: used config file 'C:\Users\User\.choosenim\toolchains\nim-#devel\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\User\.choosenim\toolchains\nim-#devel\config\config.nims' [Conf]
.................................
Hint: opt: speed; options: -d:danger
21385 lines; 0.348s; 20.605MiB peakmem; proj: D:\User\test.nim; out: D:\User\test.js [SuccessX]
Hint: "C:\Program Files\nodejs\node.exe" --unhandled-rejections=strict D:\User\test.js [Exec]
D:\User\test.js:35
                  var code_33556858 = c_33556845.toString(16);
                                                 ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at toJSStr (D:\User\test.js:35:50)
    at rawEcho (D:\User\test.js:80:16)
    at main_452984833 (D:\User\test.js:263:5)
    at Object.<anonymous> (D:\User\test.js:267:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.0.1
Error: execution of an external program failed: '"C:\Program Files\nodejs\node.exe" --unhandled-rejections=strict D:\User\test.js'
```

### Nim Version

1.7.1

### Current Standard Output Logs

_No response_

### Expected Standard Output Logs

_No response_

### Possible Solution

the js output:
```js
function main_452984833() {
    var s_452984834 = [];
    (s_452984834.length = 4);
    rawEcho(nimCharToStr(s_452984834[0]));
}
```
https://github.com/nim-lang/Nim/blob/9f408ea9430b104eb6c14a84d7a1650bf115b6a0/compiler/jsgen.nim#L2141-L2142
I think it should work set the length and fill with `'\0'` like in the case of `seq`.
https://github.com/nim-lang/Nim/blob/9f408ea9430b104eb6c14a84d7a1650bf115b6a0/compiler/jsgen.nim#L2150-L2151

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ire4ever1190**
Closes #20235

Means this snippet now performs the same on JS/C backends
```nim
var s = ""
s.setLen(4)
echo s[0].ord, " ", s.len
```

### CODE REVIEW

File: tests/js/t20235.nim [hunk 1]
```diff
@@ -0,0 +1,11 @@
+discard """
+  action: "run"
+  output: "0 4"
+"""
+
+proc main =
+  var s = ""
+  s.setLen(4)
```
Comment (Araq) [inline tests/js/t20235.nim:8]: what if it's `s.setLen procThatEchosAndReturns(3)`?

Comment (ire4ever1190) [reply tests/js/t20235.nim:8]: As in something like this?
```nim
import sequtils

proc procThatEchosAndReturns(x: int): int =
  echo "Test"
  x

var s = ""
s.setLen procThatEchosAndReturns(3)
echo s.mapIt(it.ord)
```
Outputs
```
Test
@[0, 0, 0]
```

Would this somehow cause problems?

Comment (ire4ever1190) [reply tests/js/t20235.nim:8]: The parameter is assigned into a temporary so the parameter is not called multiple times

Simplified version of JS generation
```js
if (s[0].length < (Temporary1 = chckRange(procThatEchosAndReturns(s[0], 3), 0, 2147483647), Temporary1)) { for (var i = s[0].length; i < Temporary1; ++i) s[0].push(0); }
else {s[0].length = Temporary1; };
```

Comment (Araq) [reply tests/js/t20235.nim:8]: Ok.
