### PR TITLE
printing float values will have one more digit.

### LINKED ISSUE #13196: Lossy json serialization/deserialization round-trip for floats
A json serialization + deserialization round-trip does not give back the original value for floats.

### Example
```nim
import json
import strformat

# some arbitrary float, not caring about actually significant places here
let x = 0.12345678901234567890123456789
let y = ($(%* x)).parseJson().getFloat()

echo &"{x} == {x} => {x == y}"
doAssert x == y
```
(EDIT(timotheecour): see another example in https://github.com/nim-lang/Nim/issues/15397#issue-707398880)

### Current Output
```
0.1234567890123457 == 0.1234567890123457 => false
/tmp/test.nim(9)         test
/nim/lib/system/assertions.nim(27) failedAssertImpl
/nim/lib/system/assertions.nim(20) raiseAssert
/nim/lib/system/fatal.nim(55) sysFatal
Error: unhandled exception: /tmp/test.nim(9, 10) `x == y`  [AssertionError]
```

### Expected Output

No assertion error at least.

### Possible Solution

This is basically a consequence that `parseFloat` and `$` are not supposed be lossless (see https://github.com/nim-lang/Nim/issues/7717), but the json module builds on these.

I made a quick check with NimYaml and it suffers from exactly the same problem.

It is a natural expectation to rely on `$` to produce an exact string representation. In my opinion the easiest solution would be to improve `$` for floats. Perhaps it would make sense to implement [_Ryū: fast float-to-string conversion_](https://dl.acm.org/doi/10.1145/3192366.3192369) in the Nim standard library to solve the problem for good. A reference implementation is available in [C](https://github.com/ulfjack/ryu) and other languages. This would probably give float-to-string conversion a nice performance boost as well.

```
$ nim -v
Nim Compiler Version 1.1.1 [Linux: amd64]
Compiled at 2020-01-19
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 13ddbc46fc255978ebaf4233009b44db29583cb4
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by krux02**
fixes #13196

### CODE REVIEW

**Comment by narimiran** [comment]
NOTE: this should receive a `[backport]` tag when merging.

**Comment by krux02** [comment]
@narimiran since you wrote the CI integration. How do I find out what test failed here:
https://dev.azure.com/nim-lang/Nim/_build/results?buildId=2387&view=logs&j=30931762-47c4-53b3-6a83-316eb5a6b9d7&t=b1c7d701-c448-5ecb-905d-689d8a5921e0&l=11252

This is the error message that I get.

```
Error: unhandled exception: /Users/runner/.cache/nim/json_d/runnableExamples/json_examples2.nim(9, 10) `pretty(j) ==
    """{
  "name": "Isaac",
  "books": [
    "Robot Dreams"
  ],
  "details": {
    "age": 35,
    "pi": 3.1415
  }
}"""`  [AssertionError]
Error: execution of an external program failed: '/Users/runner/.cache/nim/json_d/runnableExamples/json_examples '
[Examples] failed: see /Users/runner/.cache/nim/json_d/runnableExamples/json_examples.nim

FAILURE
```

I can't fix it when I don't know where the error comes from.

**Comment by narimiran** [comment]
> @narimiran since you wrote the CI integration.

Nope, I didn't.

> I can't fix it when I don't know where the error comes from.

> `nim/json_d/runnableExamples/json_examples2.nim(9, 10)`

Look at the filename: it is the second runnable example of json module:

```nim
proc pretty*(node: JsonNode, indent = 2): string =
  ## Returns a JSON Representation of `node`, with indentation and
  ## on multiple lines.
  ##
  ## Similar to prettyprint in Python.
  runnableExamples:
    let j = %* {"name": "Isaac", "books": ["Robot Dreams"],
                "details": {"age": 35, "pi": 3.1415}}
    doAssert pretty(j) == """
{
  "name": "Isaac",
  "books": [
    "Robot Dreams"
  ],
  "details": {
    "age": 35,
    "pi": 3.1415
  }
}"""
  result = ""
  toPretty(result, node, indent)
```

File: lib/pure/json.nim [hunk 1]
```diff
@@ -677,7 +677,7 @@ proc pretty*(node: JsonNode, indent = 2): string =
   ## Similar to prettyprint in Python.
   runnableExamples:
     let j = %* {"name": "Isaac", "books": ["Robot Dreams"],
-                "details": {"age": 35, "pi": 3.1415}}
+                "details": {"age": 35, "number": 3.125}}
```
Comment (narimiran) [inline lib/pure/json.nim:680]: We're now redefining the value of `pi` just so some tests might pass? :-1:

Comment (krux02) [reply lib/pure/json.nim:680]: No, we are not redefining the value of pi. It is the value "number" now. The reason for this change is simple. 3.1415 isn't a valid binary floating point value, the value can only be represented approximately. When I print it on this branch the output will be ``3.1415000000000002``. Then 3.1415 isn't the exact value of π either, it is just an approximation, and a pretty bad one to be honest. But the test relies on this exact precision. Then last but not least the test isn't really about π, it is just about printing a floating point number. So I've changed the number to a value that is precisely representable as binary float. I think that's reasonable.

Comment (bluenote10) [reply lib/pure/json.nim:680]: That is simply the problem that using 17 digits sometimes produces unnecessary digits.

The string representation 3.1415000000000002 of ryu and Pythons JSON serialization is both `"3.1415"` because there is no need to specify all the extra digits to represent it.

image

Comment (narimiran) [reply lib/pure/json.nim:680]: So, for the following example:

```nim
let a = 3.1415
let b = 0.3

echo a
echo b

echo $a == $3.1415
echo $b == $0.3
```

Before this PR the output is:
```
3.1415
0.3
true
true
```

and after this PR the output is:
```
3.1415000000000002
0.29999999999999999
false
false
```

Comment (Clyybber) [reply lib/pure/json.nim:680]: Maybe we should adopt ryu.

Comment (Araq) [reply lib/pure/json.nim:680]: Oh yes please!

Comment (krux02) [reply lib/pure/json.nim:680]: @narimiran if you rebuild the compiler the output is the following:
```
3.1415000000000002
0.29999999999999999
true
true
```
@bluenote10 True, using 17 digits sometimes produces unnecessary digits, but that is much better than not enough digits where the number can't be converted back to binary without loss of precision. Also I like the numbers ``3.1415000000000002``, because it provides feedback to the user in the form of "sorry, I really can't represent `3.1415` precisely", which really is a very common mistake by many beginner programmers that aren't taught about floating point numbers.

Comment (bluenote10) [reply lib/pure/json.nim:680]: @krux02 I also think that full precision is better than lossy. We only have to keep in mind that this change can increase the size of json serialized data significantly, because the behavior will suddenly apply to many value "short" float values. For instance, a simple 0.1 changes from 3 characters to 19 characters.

Ryu would be really great indeed.

Comment (narimiran) [reply lib/pure/json.nim:680]: > if you rebuild the compiler the output is the following:

You're right, I hadn't rebuilt the compiler when I had run that example.

**Comment by foldl** [comment]
How interesting!

If we can't print `pi` properly (as required by the test case), just change to another number (update the test case)!

**Comment by krux02** [comment]
@foldl there is some outdated discussion about this change. This is what I said: 

> No, we are not redefining the value of pi. It is the value "number" now. The reason for this change is simple. 3.1415 isn't a valid binary floating point value, the value can only be represented approximately. When I print it on this branch the output will be 3.1415000000000002. Then 3.1415 isn't the exact value of π either, it is just an approximation, and a pretty bad one to be honest. But the test relies on this exact precision. Then last but not least the test isn't really about π, it is just about printing a floating point number. So I've changed the number to a value that is precisely representable as binary float. I think that's reasonable.



> If we can't print pi properly

Yes, we can't print pi properly, nobody can, it has infinite digits. The amount of digits to print is preference.

> as required by the test case

Nope. The test case just prints a number that is similar to π, a literal that can't be represented as a floating point number precisely. If it really would have tested π, then it should have taken `math.Pi` and not some arbitrary definition of it.

But don't worry. The PR got reverted. But for other reasons (https://github.com/nim-lang/Nim/issues/13362).

**Comment by foldl** [comment]
By `pi` I referring the value named `pi` in the original testcase. 

Thanks all the same for @krux02 's lecture that 3.1415 is an approximation of  π.

**Comment by krux02** [comment]
Ok then. But If we can't print pi properly, should we then have a test case that expects printing of pi in a specific (but still incorrect) way?

My argument here is. `3.1415` is not the number that is actually stored in the variable `pi`. So then why should we have a test that expects the value to be printed as `"3.1415"`?

**Comment by foldl** [comment]
> Ok then. But If we can't print pi properly, should we then have a test case that expects printing of pi in a specific (but still incorrect) way?

Your statement does not make sense. 3.1415 should be printed properly in Nim.

**Comment by krux02** [comment]
> Your statement does not make sense. 3.1415 should be printed properly in Nim.

Your statement does not make sense, `3.1415` is not a proper IEEE floating point number, it can only be stored approximately.

**Comment by foldl** [comment]
> Your statement does not make sense, 3.1415 is not a proper IEEE floating point number, it can only be stored approximately.

I have posted a paper on the forum. Just read it.

**Comment by krux02** [comment]
printing the value of `pi` as `3.1415` is certainly a sane representation. But don't argue that it is "proper". The only string representation that is also mathematically correct is ``3.141500000000000181188397618825547397136688232421875``. You can argue that this is a bit too verbose and shorten it to ``3.1415000000000002`` because that is all the precision you need. You can also argue that ``3.1415`` is enough. But you can certainly not argue that `3.1415` is proper nor can you argue that it is true, because it isn't. And my argument is, if the string represenation of a number is subjective and might vary on preference, a test should not rely on this preference and pick a number that does not depend on preference. What I do care about though is, if a number is printed and parsed again, it should be the exact same number. And that is what I fixed here.
