### PR TITLE
fix #16693: testament spec `nimout` too lax

### LINKED ISSUE #16693: testament spec `nimout` too lax
nimout spec seems to just check that each line in nimout is a contiguous substring of a line in compilation output. This is way too lax for being usable, as shown here:

### Example 1
```nim
discard """
  nimout: '''
foobar2
foobar
foobar
foobar2
oobar
ba
'''
"""

static: echo "foobar1"
static: echo "foobar2"
```

XDG_CONFIG_HOME= nim r testament/testament.nim r tests/misc/t11682b.nim

### Current Output
PASS: tests/misc/t11682b.nim c 

### Expected Output
fails

### Example 2
this can go horribly wrong, see https://github.com/nim-lang/Nim/pull/16698#discussion_r556938409

### Possible Solution
* each line in nimout should be a complete line in compilation output (no substring match)
* it's ok to have unmatched lines in output (useful for new warnings/hints etc)
* order cannot change
* each matched line should only be used once

EDIT: this is maybe the thing to fix (in testament.nim):
```nim
proc greedyOrderedSubsetLines*(lhs, rhs: string): bool =
  ## returns true if each stripped line in `lhs` appears in rhs, using a greedy matching.
  let rhs = rhs.strip
  var currentPos = 0
  for line in lhs.strip.splitLines:
    currentPos = rhs.find(line.strip, currentPos)
    if currentPos < 0:
      return false
  return true
```

### Additional Information
* 1.5.1 fd5c8ef20845a511ad4e0af8dd8ad4331bf46ffc
* marking high priority because test suite should have sane behavior
* not caused by https://github.com/nim-lang/Nim/pull/16189 since I verified this was the case right before that PR too
* odd behavior noticed by @xflywind in some other PR

### PR DESCRIPTION
**Pull request by ringabout**
fix #16693

### CODE REVIEW

File: tests/vm/tcompiletimetable.nim [hunk 1]
```diff
@@ -1,12 +1,16 @@
 discard """
-  nimout: '''2
+  nimout: '''
+2
 3
 4:2
 Got Hi
 Got Hey
+'''
+  output:'''
```
Comment (ringabout) [inline tests/vm/tcompiletimetable.nim:9]: original tests are wrong. `nimout` only compares compile messages.

File: tests/vm/tmisc_vm.nim [hunk 2]
```diff
@@ -19,6 +19,7 @@ foo4
 (a: 0, b: 0)
 '''
 """
+import std/sets
```
Comment (ringabout) [inline tests/vm/tmisc_vm.nim:22]: a dangerous issue
see https://github.com/nim-lang/Nim/issues/16707

**Comment by timotheecour** [comment]
> annoying dots blocks this PR

how about we add `--hint:processing:off` to tests/config.nims?
tests that actually test this functionality can override this easily (that's exactly what i did in trunner.nim:
```
const
  defaultHintsOff = "--hint:successx:off --hint:exec:off --hint:link:off --hint:cc:off --hint:conf:off --hint:processing:off --hint:QuitCalled:off"
let opt = fmt"{defaultHintsOff} --hint:processing"
```

EDIT: see https://github.com/nim-lang/Nim/pull/16713

File: tests/vm/tmisc_vm.nim (hunk 2 above)
Comment (timotheecour) [reply tests/vm/tmisc_vm.nim:22]: let's do https://github.com/nim-lang/Nim/pull/16698#issuecomment-759765331 instead
EDIT: https://github.com/nim-lang/Nim/pull/16713

File: tests/test/test.nim [hunk 3]
```diff
@@ -0,0 +1,10 @@
+discard """
```
Comment (timotheecour) [inline tests/test/test.nim]: rename to tests/testament/tnimout ? and maybe make the test more useful, eg also add runtime output and an output spec?

File: tests/vm/tcompiletimetable.nim (hunk 1 above)
Comment (timotheecour) [reply tests/vm/tcompiletimetable.nim:9]: wow, i just figured out why this even "worked" before your fix:

the `a` matches the `a` inside
```
tcompiletimetable.nim(54, 8) Warning: imported and not used: 'macros' [UnusedImport]
```

this is ... bad.

thanks for fixing this terrible bug

File: testament/lib/stdtest/testutils.nim [hunk 4]
```diff
@@ -27,10 +27,43 @@ template flakyAssert*(cond: untyped, msg = "", notifySuccess = true) =
 
 proc greedyOrderedSubsetLines*(lhs, rhs: string): bool =
   ## returns true if each stripped line in `lhs` appears in rhs, using a greedy matching.
-  let rhs = rhs.strip
-  var currentPos = 0
-  for line in lhs.strip.splitLines:
-    currentPos = rhs.find(line.strip, currentPos)
-    if currentPos < 0:
+  iterator splitLinesLhs(): string {.closure.} =
```
Comment (timotheecour) [inline testament/lib/stdtest/testutils.nim]: * my gut feeling is this is more complicated than it should, but I need to look into it more closely
* how about adding a tests/testament/ttestutils.nim to test this

File: tests/vm/tmisc_vm.nim (hunk 2 above)
Comment (timotheecour) [reply tests/vm/tmisc_vm.nim:22]: PR was merged, you can undo this change now

File: testament/lib/stdtest/testutils.nim [hunk 5]
```diff
@@ -26,11 +26,22 @@ template flakyAssert*(cond: untyped, msg = "", notifySuccess = true) =
     echo msg2
 
 proc greedyOrderedSubsetLines*(lhs, rhs: string): bool =
-  ## returns true if each stripped line in `lhs` appears in rhs, using a greedy matching.
-  let rhs = rhs.strip
-  var currentPos = 0
+  ## Returns true if each stripped line in `lhs` appears in rhs, using a greedy matching.
```
Comment (timotheecour) [inline testament/lib/stdtest/testutils.nim]: add:
```nim
  doAssert not greedyOrderedSubsetLines("a1\na5", "a0\na1\na2\na3\na4\nprefix:a5")
  doAssert not greedyOrderedSubsetLines("a1\na5", "a0\na1\na2\na3\na4\na5:suffix")
```
to the existing `tests/stdlib/ttestutils.nim`

**Comment by timotheecour** [comment]
friendly ping on this!

**Comment by ringabout** [comment]
After I clean up all my working PRs.

File: testament/lib/stdtest/testutils.nim (hunk 5 above)
Comment (ringabout) [reply testament/lib/stdtest/testutils.nim]: fixed

File: tests/vm/tmisc_vm.nim (hunk 2 above)
Comment (ringabout) [reply tests/vm/tmisc_vm.nim:22]: not necessary

**Comment by ringabout** [comment]
will continue on this PR

File: tests/vm/tmisc_vm.nim (hunk 2 above)
Comment (xflywind) [inline tests/vm/tmisc_vm.nim:22]:
```suggestion
```

File: tests/pragmas/thintprocess.nim [hunk 6]
```diff
@@ -0,0 +1,16 @@
+discard """
+  matrix: "--hint:processing"
+  nimout: '''
+..
```
Comment (Clyybber) [inline tests/pragmas/thintprocess.nim]:
```suggestion
```

File: tests/testament/tshould_not_work.nim [hunk 7]
```diff
@@ -1,5 +1,6 @@
 discard """
 cmd: "testament/testament --directory:testament --colors:off --backendLogging:off --nim:$nim category shouldfail"
+targets: "c"
```
Comment (Clyybber) [inline tests/testament/tshould_not_work.nim]:
```suggestion
```
those overrides should be reverted in the other affected tests too.

Comment (ringabout) [reply tests/testament/tshould_not_work.nim]: it is intended, on cpp based platforms, ci failed.

https://dev.azure.com/nim-lang/Nim/_build/results?buildId=15131&view=logs&jobId=a0440cd6-2060-5545-8b53-639e777de0c6&j=a0440cd6-2060-5545-8b53-639e777de0c6&t=e8126762-32e4-52a6-97de-95cf0bedbe3d

image

File: tests/pragmas/thintprocess.nim (hunk 6 above)
Comment (ringabout) [reply tests/pragmas/thintprocess.nim]: this is the test which tests the dots.

File: tests/testament/tshould_not_work.nim (hunk 7 above)
Comment (ringabout) [reply tests/testament/tshould_not_work.nim]: fixed this file, other files are intended.

File: tests/varres/tprevent_forloopvar_mutations.nim [hunk 8]
```diff
@@ -1,7 +1,7 @@
 discard """
   errormsg: "type mismatch: got <int>"
   line: 17
```
Comment (timotheecour) [inline tests/varres/tprevent_forloopvar_mutations.nim:3]: do we need those 2 lines, given that we already capture
```
nimout: '''tprevent_forloopvar_mutations.nim(17, 7) Error: type mismatch: got <int>
```

I'd prefer simplicity here and in other tests; specifying separately line, col, errormsg is more work and nimout already captures what we want to test.

Ditto in other examples above, eg, replacing:
```
  errormsg: "undeclared identifier: 'undeclared'"
  line: 10
  column: 6
```
by:
```
  nimout: '''tcolumn.nim .nim(10, 6) undeclared identifier: 'undeclared''''
```

and similar examples

File: tests/stdlib/ttestutils.nim [hunk 9]
```diff
@@ -4,3 +4,6 @@ block: # greedyOrderedSubsetLines
   doAssert greedyOrderedSubsetLines("a1\na3", "a0\na1\na2\na3\na4")
   doAssert not greedyOrderedSubsetLines("a3\na1", "a0\na1\na2\na3\na4") # out of order
   doAssert not greedyOrderedSubsetLines("a1\na5", "a0\na1\na2\na3\na4") # a5 not in lhs
+
+  doAssert not greedyOrderedSubsetLines("a1\na5", "a0\na1\na2\na3\na4\nprefix:a5")
+  doAssert not greedyOrderedSubsetLines("a1\na5", "a0\na1\na2\na3\na4\na5:suffix")
```
Comment (timotheecour) [inline tests/stdlib/ttestutils.nim:9]:
```suggestion
  doAssert not greedyOrderedSubsetLines("a1\na5", "a0\na1\na2\na3\na4\na5:suffix")
  doAssert not greedyOrderedSubsetLines("a5", "a0\na1\na2\na3\na4\nprefix:a5")
  doAssert not greedyOrderedSubsetLines("a5", "a0\na1\na2\na3\na4\na5:suffix")
```
just to be on safe side

File: tests/pragmas/thintprocess.nim [hunk 10]
```diff
@@ -0,0 +1,16 @@
...
+warn_module.nim(6, 6) Hint: 'test' is declared but not used [XDeclaredButNotUsed]
+compile end
+'''
+"""
+
```
Comment (timotheecour) [inline tests/pragmas/thintprocess.nim]: rename the file to thintprocessing ? more searchable

File: tests/pragmas/thintprocess.nim [hunk 11]
```diff
@@ -0,0 +1,16 @@
...
+static:
+  echo "compile start"
```
Comment (timotheecour) [inline tests/pragmas/thintprocess.nim]: shouldn't we add that line to nimout ?

File: tests/varres/tprevent_forloopvar_mutations.nim (hunk 8 above)
Comment (ringabout) [reply tests/varres/tprevent_forloopvar_mutations.nim:3]: ok

File: tests/objvariant/tcheckedfield1.nim [hunk 12]
```diff
@@ -1,5 +1,5 @@
 discard """
-  nimout: "Warning: cannot prove that field 'x.s' is accessible [ProveField]"
+  nimout: "tcheckedfield1.nim(40, 6) Warning: cannot prove that field 'x.s' is accessible [ProveField]"
   line:51
```
Comment (timotheecour) [inline tests/objvariant/tcheckedfield1.nim:3]: another bug: if i change this to `line:1234`, the test still passes

EDIT: filed https://github.com/nim-lang/Nim/issues/17636

can be fixed in future work

Comment (ringabout) [reply tests/objvariant/tcheckedfield1.nim:3]: where is the logic? Related to my patch?

Comment (timotheecour) [reply tests/objvariant/tcheckedfield1.nim:3]: pre-existing, it's unrelated to your PR, just that i noticed it while reviewing your PR

File: tests/varres/tprevent_forloopvar_mutations.nim (hunk 8 above)
Comment (ringabout) [reply tests/varres/tprevent_forloopvar_mutations.nim:3]: then I need to change line number which is a huge work can be left in the future PR.

File: tests/pragmas/thintprocess.nim (hunk 10 above)
Comment (ringabout) [reply tests/pragmas/thintprocess.nim]: fixed

File: tests/pragmas/thintprocess.nim (hunk 6 above)
Comment (ringabout) [inline tests/pragmas/thintprocess.nim]:
```suggestion
compile start
..
```

File: tests/pragmas/thintprocessing.nim [hunk 13]
```diff
@@ -0,0 +1,16 @@
+discard """
+  matrix: "--hint:processing"
+  nimout: '''
+..
```
Comment (ringabout) [inline tests/pragmas/thintprocessing.nim:6]:
```suggestion
compile start
..
```

File: tests/pragmas/thintprocess.nim (hunk 11 above)
Comment (ringabout) [reply tests/pragmas/thintprocess.nim]: fixed

File: testament/lib/stdtest/testutils.nim [hunk 14]
```diff
@@ -26,15 +25,29 @@ template flakyAssert*(cond: untyped, msg = "", notifySuccess = true) =
...
+
+    var rhsIter = splitLinesClosure
+    var currentLine = strip(rhsIter())
+
+    for line in lhs.strip.splitLines:
+      let line = line.strip
+      if line.len != 0:
+        while line != currentLine:
+          currentLine = strip(rhsIter())
+          if rhsIter.finished:
```
Comment (timotheecour) [inline testament/lib/stdtest/testutils.nim:45]: just use a seq for rhs, it'll be clearer than with rhs.finished + rhsIter() (which complicates readability because of iterator semantics which requires calling iter before finished)

File: tests/pragmas/thintprocessing.nim (hunk 13 above)
Comment (timotheecour) [reply tests/pragmas/thintprocessing.nim:6]: shoot, this fails on windows:
```
....compile start
```

(known bug IIRC)

given that we already have a similar test in trunner.nim, maybe add `disabled: windows`?

refs:
```
  block: # `hintProcessing` dots should not interfere with `static: echo` + friends
    let cmd = fmt"""{nim} r {defaultHintsOff} --hint:processing -f --eval:"static: echo 1+1""""
    let (outp, exitCode) = execCmdEx(cmd, options = {poStdErrToStdOut})
    template check3(cond) = doAssert cond, $(outp,)
    doAssert exitCode == 0
    let lines = outp.splitLines
    check3 lines.len == 3
    when not defined(windows): # xxx: on windows, dots not properly handled, gives: `....2\n\n`
      check3 lines[0].isDots
      check3 lines[1] == "2"
      check3 lines[2] == ""
    else:
      check3 "2" in outp
```

File: tests/varres/tprevent_forloopvar_mutations.nim (hunk 8 above)
Comment (timotheecour) [reply tests/varres/tprevent_forloopvar_mutations.nim:3]: yes can be deferred


> then I need to change line number

no, you could just add empty newlines

**Review by timotheecour — APPROVED** [review]
LGTM after addressing CI failure on windows, for eg via https://github.com/nim-lang/Nim/pull/16698#discussion_r606776131

(remaining points can be addressed in this PR or in future PRs)

note: the `targets: "c"` became needed after this PR because now nimout whole lines must be matched, eg in
```
tests/testament/tshould_not_work.nim:32:24:FAIL: tests/shouldfail/ttimeout.nim c
```

to re-enable non-c targets (ie cpp here), we can in future work run tests/testament/tshould_not_work.nim via trunner.nim instead of via testament spec (only needs to be done for this file IIUC)

File: tests/pragmas/thintprocessing.nim [hunk 15]
```diff
@@ -0,0 +1,17 @@
+discard """
+  matrix: "--hint:processing"
```
Comment (ringabout) [inline tests/pragmas/thintprocessing.nim:3]:
```suggestion
  disabled: windows
  matrix: "--hint:processing"
```
