### PR TITLE
Fix #17299, fix setAffinity for android

### LINKED ISSUE #17299: Nim devel tries to link to the non-existent pthread_setaffinity_np function
On Android (Termux) I have to apply the following patch to ``/usr/lib/nim/system/threadlocalstorage.nim``

I am not sure if it does the real thing when ``setAffinity`` is called, but it links fine now and I could run a patched version of *Weave*

```nim
--- threadlocalstorage.nim	2021-02-22 09:45:37.790730997 +0100
+++ HJ/threadlocalstorage.nim	2021-03-08 17:38:11.658617339 +0100
@@ -194,8 +194,15 @@
   proc cpusetIncl(cpu: cint; s: var CpuSet) {.
     importc: "CPU_SET", header: schedh.}
 
-  proc setAffinity(thread: SysThread; setsize: csize_t; s: var CpuSet) {.
-    importc: "pthread_setaffinity_np", header: pthreadh.}
+  when defined(android):
+    proc sched_setaffinity(thread: SysThread;  cpuset_size: csize_t, ptrCpuset: ptr  CpuSet) {.
+      importc: "sched_setaffinity", header: schedh.}
+
+    proc setAffinity(thread: SysThread; setsize: csize_t; s: var CpuSet) =
+      sched_setaffinity(thread, setsize, addr s)
+  else:
+    proc setAffinity(thread: SysThread; setsize: csize_t; s: var CpuSet) {.
+      importc: "pthread_setaffinity_np", header: pthreadh.}
 
 
 const
```

### PR DESCRIPTION
**Pull request by Clyybber**
Fixes #17299

### CODE REVIEW

File: lib/system/threadlocalstorage.nim [hunk 1]
```diff
@@ -194,8 +194,23 @@ else:
...
+  when defined(android):
+    # libc of android doesn't implement pthread_setaffinity_np,
+    # it exposes pthread_gettid_np though, so we can use that in combination
+    # with sched_setaffinity to set the thread affinity.
+    type Pid {.importc: "pid_t", header: "<sys/types.h>".} = int32 # From posix_other.nim
+
+    proc setAffinityTID(tid: Pid; setsize: csize_t; s: var CpuSet) {.
+      importc: "sched_setaffinity", header: schedh.}
+
+    proc pthread_gettid_np(thread: SysThread) {.
```
Comment (timotheecour) [inline lib/system/threadlocalstorage.nim]:
```suggestion
    proc pthread_gettid_np(thread: SysThread): Pid {.
```
?

**Comment by Clyybber** [comment]
@HJarausch Can you please test if this works for you?

**Review by timotheecour — APPROVED** [review]

**Comment by dom96** [comment]
@Clyybber please consider including more details in PR titles to make it easier to manage notifications :)
