### PR TITLE
fixes #10886 [backport]

### LINKED ISSUE #10886: Booleans Work Wrong in Compile-time
`sets.containsOrIncl` and `or` in one-line work wrong in compile-time

### Example

```nim
import sets

proc add[T](hs: HashSet[T], tl: openArray[T]): HashSet[T] =
  result = hs
  var
    flag = true
    i = 0
  while flag and i < tl.len:
    flag = result.containsOrIncl(tl[i]) or flag
    inc(i)

const hs = ["a", "b", "c"].toSet
const testC = hs.add(@["b", "c", "d", "e", "f"])
let testL = hs.add(@["b", "c", "d", "e", "f"])

echo testC
echo testL
```

### Current Output
```
{"c", "a", "b", "d"}
{"e", "a", "d", "c", "b", "f"}
```

### Expected Output

```
{"e", "a", "d", "c", "b", "f"}
{"e", "a", "d", "c", "b", "f"}
```

### Additional Information

```
$ nim -v
nim -v
Nim Compiler Version 0.19.4 [Linux: amd64]
Compiled at 2019-03-21
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

File: compiler/vmgen.nim [hunk 1]
```diff
@@ -388,16 +388,28 @@ proc genIf(c: PCtx, n: PNode; dest: var TDest) =
...
 proc genAndOr(c: PCtx; n: PNode; opc: TOpcode; dest: var TDest) =
   #   asgn dest, a
   #   tjmp|fjmp L1
   #   asgn dest, b
   # L1:
-  if dest < 0: dest = getTemp(c, n.typ)
-  c.gen(n.sons[1], dest)
-  let L1 = c.xjmp(n, opc, dest)
-  c.gen(n.sons[2], dest)
+  let copyBack = dest < 0 or not isTemp(c, dest)
```
Comment (narimiran) [inline compiler/vmgen.nim]: `let copyBack = not isTemp(c, dest)` would have been enough

Comment (Araq) [reply compiler/vmgen.nim]: I know but it felt clearer this way.
