### PR TITLE
Fix AsyncFile open flags. Fixes #5531

### LINKED ISSUE #5531: fmWrite doesn't truncate file with openAsync, unlike open()
open and openAsync (from `asyncfile` module) treat fmWrite mode inconsistently:

`open("myfile", fmWrite)` - truncates file
`openAsync("myfile", fmWrite)` - does not truncate file

I think they should behave consistently in this regard and open's behaviour (truncation) is what I expected from the fmWrite mode.

### PR DESCRIPTION
**Pull request by endragor**

### CODE REVIEW

File: tests/async/tasyncfile.nim [hunk 1]
```diff
@@ -41,11 +41,11 @@ proc main() {.async.} =
     await file.write("test2")
     file.close()
     file = openAsync(fn, fmWrite)
-    await file.write("test3")
+    await file.write("t3")
     file.close()
     file = openAsync(fn, fmRead)
     let data = await file.readAll()
-    doAssert data == "test3"
+    doAssert data == "t3"
```
Comment (endragor) [inline tests/async/tasyncfile.nim]: The original test worked only because `test3` is of the same length as `test2`, so it was overwritten. But if you write `t3` without truncating, the result would be `t3st2`.
