### PR TITLE
[JS] Fix casting to ints

### LINKED ISSUE #16806: Casting integers causes out of range values (JS)
Casting integers on JS can result in out of bound integers with no warning or error.

### Example
```nim
let
  a = 42u16
  b = cast[int16](a)
assert a.int16 == 42
assert b in int16.low..int16.high # Fails
```

### Current Output
```
Uncaught Error: Error: unhandled exception: /tmp/flattytest.nim(5, 8) `b in int16.low .. int16.high`  [AssertionDefect]
```

### Expected Output
No errors and value within the int16 range

Tested on devel and stable.

### LINKED ISSUE #16808: Integer casts don't work right in JS mode.
I expect for casts to work the same way they do normally to also work in JS mode. Its surprising that int8 and int16 casts don't work but int32 cast does work.

This works with `nim c` but does not work with `nim js`:

```nim
echo cast[int8](cast[uint8](int8(-12)))
echo cast[int16](cast[uint16](int16(-12)))
echo cast[int32](cast[uint32](int32(-12)))  # works...
```

## Using `nim c`
```
-12
-12
-12
```

## Using `nim js`
```
10
10
-12
```

```
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-01-04
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

Similar to https://github.com/nim-lang/Nim/issues/16547

### PR DESCRIPTION
**Pull request by konsumlamm**
Fixes #16806.
Fixes #16808.

Casting from ints to ints generated nothing, causing for example `doAssert cast[int8](int16.high) == -1` to fail.
Casting from uints to ints used some weird subtracting (I still have no idea how that was supposed to work), which I replaced by shifting left and then right again to sign extend.
The trick to use `| 0` to convert to `int32` also works when the source type isn't 32 bit.

I created a new folder `tests/cast/` for tests related to casting. `tcast.nim` contains tests for both fixed issues and an additional one that I found.

### CODE REVIEW

File: compiler/jsgen.nim [hunk 1]
```diff
@@ -2733,20 +2733,13 @@ proc genCast(p: PProc, n: PNode, r: var TCompRes) =
...
   elif toInt:
-    if fromInt:
-      return
-    elif fromUint:
-      if src.size == 4 and dest.size == 4:
-        # XXX prevent multi evaluations
-        r.res = "($1 | 0)" % [r.res]
+    if fromInt or fromUint:
+      if dest.size == 4:
+        r.res = "(($1) | 0)" % [r.res]
```
Comment (konsumlamm) [inline compiler/jsgen.nim]: I added parentheses around `$1`, not sure if that's necessary, but it's also done in `genConv`. I also removed the comment about multi evaluations, as I don't see how that could happen here.

**Comment by konsumlamm** [comment]
We could also think about just using `BigInt.asIntN` and `BigInt.asUintN` for the conversions. That would be a lot simpler, but maybe also slower?

**Comment by Araq** [comment]
> That would be a lot simpler, but maybe also slower?

Depends on the used JS engine and they are usually really good these days. I wouldn't worry about it.

**Comment by juancarlospaco** [comment]
BigInt is better and simplifies codegen, also less bug prone.

**Comment by konsumlamm** [comment]
`genCast` now uses the `BigInt` methods.
