### PR TITLE
fix #17159 items(cstring) works in VM

### LINKED ISSUE #17159: `items(cstring)` broken in VM
### Example 1
```nim
when true:
  proc main()=
    var a = "abc"
    var b = a.cstring
    echo (b, )
  static: main()
  main()
```

### Current Output
stack trace: (most recent call last)
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11898.nim(34, 15) t11898
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11898.nim(33, 10) main
/Users/timothee/git_clone/nim/Nim_devel/lib/system/dollars.nim(136, 21) $
/Users/timothee/git_clone/nim/Nim_devel/lib/system/iterators.nim(67, 12) addQuoted
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11898.nim(5, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim_devel/lib/system/iterators.nim(67, 12) Error: index 3 not in 0 .. 2
      while a[i] != '\0':
             ^

### Expected Output
works in VM like in RT

### Example 2
```nim
when true:
  proc main()=
    var a = "abc"
    var b = a.cstring
    for bi in b:
      echo (bi,)
  static: main()
  main()
```

```
('a',)
('b',)
('c',)
stack trace: (most recent call last)
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11898.nim(52, 15) t11898
/Users/timothee/git_clone/nim/Nim_devel/lib/system/iterators.nim(67, 12) main
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11898.nim(5, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim_devel/lib/system/iterators.nim(67, 12) Error: index 3 not in 0 .. 2
      while a[i] != '\0':
             ^
```

### Additional Information
1.5.1 74a8f23801316cd9e5b7ea072bf0c8c0465b0626

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #17159 `items(cstring)` (and hence things like `addQuoted`) works in VM
* increase test coverage for tests/stdlib/tcstring.nim
* merge tests/arc/tcstring.nim into tests/stdlib/tcstring.nim, avoiding test duplication, increasing test coverage for arc and illustrating new things that fail in gc:arc
* add reusable helpers `whenRuntimeJs`, `whenVMorJs`, which act as: `when defined(js) and not nimvm`, `when defined(js) or niimvm` (won't be needed if/when nimvm supports it)
* add runnableExamples for items(cstring), mitems(cstring) and identify a bug for nil input

## future work
- [x] give RT error for mitems(cstring) in js RT (currently silently gives wrong results)
   => PR https://github.com/nim-lang/Nim/pull/17161
- [ ] handle nil cstring in items, mitems
- [ ] various bugs identified in this PR marked as `xxx`

### CODE REVIEW

File: testament/lib/stdtest/testutils.nim [hunk 1]
```diff
@@ -42,3 +42,27 @@ template enableRemoteNetworking*: bool =
...
+  do:
+    discard
+  ]##
+  when nimvm: bodyElse
+  else:
+    when defined(js): bodyIf
+    else: bodyElse
+
+template whenVMorJs*(bodyIf, bodyElse) =
+  ## Behaves as: `when defined(js) or niimvm`
```
Comment (ringabout) [inline testament/lib/stdtest/testutils.nim]:
```suggestion
  ## Behaves as: `when defined(js) or nimvm`
```

**Review by ringabout — APPROVED** [review]
