### PR TITLE
Fix `iterable` resolution, prefer iterator overloads

### LINKED ISSUE #22098: Broken overload resolution between proc and iterator for `iterable`
### Description

The following code compiles and runs fine unless the proc is uncommented. If it is, the error is: `Error: undeclared identifier: 'it'`.  Until the [RFC#397](https://github.com/nim-lang/RFCs/issues/397) is implemented, the proc shouldn't even affect this code, because currently it works only when the resulting seq is followed by implicit `items`.

```nim
from std/sequtils import toSeq
template moopIt[T](iter: iterable[T]; expr: untyped): untyped =
  iterator internal(): auto {.gensym.} =
    for it {.inject.} in iter:
      yield expr
  internal()

iterator splat(s: string): string = (for i in @["X", "Y", "Z"]: yield i)
#proc splat(s: string): seq[string] = @["A", "B", "C"]

assert splat("").moopIt(it[0]).toSeq() == @['X', 'Y', 'Z']
```

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-06-14
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 20dfdba2df7c0d4f65c90561ebf75c2084bbd64f
active boot switches: -d:release

### Current Output

_No response_

### Expected Output

```text
* proc doesn't affect resolution, as it doesn't fit itself
* iterator given precedence when resolving `iterable`
```

### Possible Solution

_No response_

### Additional Information

Possibly relevant:
https://github.com/nim-lang/Nim/issues/19206

### PR DESCRIPTION
**Pull request by ZoomRmc**
This fixes type resolution for `iterable[T]`.

I want to proceed with RFC [#562](https://github.com/nim-lang/RFCs/issues/562) and this is the main blocker for composability.

Fixes #22098 and, arguably, #19206

```nim
import std/strutils

template collect[T](it: iterable[T]): seq[T] =
  block:
    var res: seq[T] = @[]
    for x in it:
      res.add x
    res

const text = "a b c d"

let words = text.split.collect()
doAssert words == @[ "a", "b", "c", "d" ]
```

In cases like `strutils.split`, where both proc and iterator overload exists, the compiler resolves to the `func` overload causing a type mismatch.

The old mode resolved `text.split` to `seq[string]` before the surrounding `iterable[T]` requirement was applied, so the argument no longer matched this template.

It should be noted that, compared to older sequtils templates, composable chains based on `iterable[T]` require an iterator-producing expression, e.g. `"foo".items.iterableTmpl()` rather than just `"foo".iterableTmpl()`. This is actually desirable: it keeps the iteration boundary explicit and makes iterable-driven templates intentionally not directly interchangeable with older untyped/loosely-typed templates like those in `sequtils`, whose internal iterator setup we have zero control over (e.g. hard-coding adapters like `items`).

Also, I noticed in `semstmts`  that anonymous iterators are always `closure`, which is not that surprising if you think about it, but still I added a paragraph to the manual.

Regarding implementation:

From what I gathered, the root cause is that `semOpAux` eagerly pre-types all arguments with plain flags before overload resolution begins, so by the time `prepareOperand` processes `split` against the `iterable[T]`, the wrong overload has already won.

The fix touches a few places:

- `prepareOperand` in `sigmatch.nim`:
  When `formal.kind == tyIterable` and the argument was already typed as something else, it's re-semchecked with the `efPreferIteratorForIterable` flag. The recheck is limited to direct calls (`a[0].kind in {nkIdent, nkAccQuoted, nkSym, nkOpenSym}`) to avoid recursing through `semIndirectOp`/`semOpAux` again.

- `iteratorPreference` field `TCandidate`, checked before `genericMatches` in `cmpCandidates`,  gives the iterator overload a win without touching the existing iterator heuristic used  by `for` loops.

**Limitations:**

The implementation is still flag-driven rather than purely formal-driven, so the behaviour is a bit too broad `efWantIterable` can cause iterator results to be wrapped as `tyIterable` in iterable-admitting contexts, not only when `iterable[T]` match is being processed.

`iterable[T]` still does not accept closure iterator values such as`iterator(): T {.closure.}`. It only matches the compiler's internal `tyIterable`, not arbitrary iterator-typed values.

The existing iterator-preference heuristic is still in place, because when I tried to remove it, some loosely-related regressions happened. In particular, ordinary iterator-admitting contexts and iterator chains still rely on early iterator preference during semchecking, before the compiler has enough surrounding context to distinguish between value/iterator producing overloads. Full heuristic removal would require a broader refactor of dot-chain/intermediate-expression semchecking, which is just too much for me ATM. This PR narrows only the tyIterable-specific cases.

**Future work:**

Rework overload resolution to preserve additional information of matching iterator overloads for calls up to the point where the iterator-requiring context is established, to avoid re-sem in `prepareOperand`.

Currently there's no good channel to store that information. Nodes can get rewritten, TCandidate doesn't live long enough, storing in Context or some side-table raises the question how to properly key that info.

### CODE REVIEW

File: compiler/sem.nim [hunk 1]
```diff
@@ -466,9 +476,13 @@ proc semAfterMacroCall(c: PContext, call, macroResult: PNode,
     globalError(c.config, s.info, "template instantiation too nested")
   c.friendModules.add(s.owner.getModule)
   result = macroResult
+  let bodyFlags = if prefersIteratorForIterable(s):
```
Comment (metagn) [inline compiler/sem.nim]: I don't think this does anything, exception flags do not propagate like this, if the body takes an expression flag it will only use it for the last expression in the body. Unless you meant for it to trigger if the return type is `iterable[T]`, which is not what `prefersIteratorForIterable` does, it specifically skips the return type.

File: compiler/semexprs.nim [hunk 2]
```diff
@@ -1525,7 +1526,7 @@ proc builtinFieldAccess(c: PContext; n: PNode; flags: var TExprFlags): PNode =
     return
 
   # extra flags since LHS may become a call operand:
-  n[0] = semExprWithType(c, n[0], flags+{efDetermineType, efWantIterable, efAllowSymChoice})
+  n[0] = semExprWithType(c, n[0], flags + {efDetermineType, efWantIterable, efAllowSymChoice})
```
Comment (metagn) [inline compiler/semexprs.nim:1529]: From what I understand this is one of the only 2 places your new flag and `efWantIterable` are different. Does something happen if you remove `efWantIterable` here? (i.e. does CI break)

For the other use of `efWantIterable` in `semOverloadedCallAnalyseEffects`, maybe instead of setting the type of the node to `tyIterable`, `tyIterable` in `typeRel` can check if the argument node is an iterator call, like a "node typeclass". I don't know if this would work though, just a suggestion.

File: compiler/sem.nim [hunk 3]
```diff
@@ -454,6 +454,16 @@ proc resetSemFlag(n: PNode) =
     for i in 0..<n.safeLen:
       resetSemFlag(n[i])
 
+proc prefersIteratorForIterable(s: PSym): bool =
```
Comment (Araq) [inline compiler/sem.nim]: What this does and when it is done must be covered in the manual.

File: compiler/sigmatch.nim [hunk 4]
```diff
@@ -2765,6 +2771,17 @@ proc prepareOperand(c: PContext; formal: PType; a: PNode, newlyTyped: var bool):
     considerGenSyms(c, result)
     if result.kind != nkHiddenDeref and result.typ.kind in {tyVar, tyLent} and c.matchedConcept == nil:
       result = newDeref(result)
+    if formal.kind == tyIterable and result.typ.kind != tyIterable and
+        a.kind == nkCall and a[0].kind in {nkIdent, nkAccQuoted, nkSym, nkOpenSym}:
```
Comment (metagn) [inline compiler/sigmatch.nim]: Resemming is a last resort solution, and I understand it here (otherwise every single proc/iterator overloaded call would need to emit a "superposition" and collapse it to a proc everywhere except `iterable` and for loops). But this way of doing it might break symbol resolution rules. If we cannot keep the information of which iterators would have matched, maybe we can try to keep the information of if an iterator could have matched in the first place. I don't know though, maybe your way is still more practical.

From what I understand: Maybe the `iteratorPreference` you added can be negated for contexts that do not want iterators, so that ambiguity stops being a problem and `skIterator` can stop being filtered out of calls (i.e. always added to the filter set in `semOverloadedCallAnalyzeEffects`). Then `semOverloadedCallAnalyzeEffects` would reject an iterator call after the match if the context cannot handle it (which I think the code is already there for). This would allow the compiler to mark a call node if any iterator overload matched, and then only try resem again if the node is marked as such (although this can fail if the iterator symbol is lost, but this happens regardless). But the cleanest way to do so would be a node flag which is frowned upon iirc, maybe it gets a pass in this case since it effectively just saves computation, then again maybe the compiler shouldn't be doing something that is too difficult to compute.

Also you might want to check for `nkCallKinds` instead of just `nkCall`.

Comment (ZoomRmc) [reply compiler/sigmatch.nim]: Thanks for the review. I just want to clarify, that I barely managed to make it all compile and not break things. It's all extremely fragile, at least that's my impression.

"Trying things" is a bit over my head, especially considering how slow and unreliable local `buildCI` is.

File: compiler/sem.nim (hunk 3 above)
Comment (ZoomRmc) [reply compiler/sem.nim]: I gather, you mean the whole PR, not this specific proc?

Comment (Araq) [reply compiler/sem.nim]: No, pretty much this specific proc as it does something very unusal. Checks whether the routine has in its signature a use of iterable[T], if I skimmed it correctly.

File: compiler/semexprs.nim (hunk 2 above)
Comment (ZoomRmc) [reply compiler/semexprs.nim:1529]: Removing `efWantIterable` here breaks ufcs.

Regarding your suggestion, I think this will result in ordering issues and implies bigger refactoring. At the point typerel runs, do we actually have any access to overload information or the AST shape generally?
I think typerel could make the check you suggest only if we would provide it with additional info, like other candidates that existed for a given argument.

File: compiler/sigmatch.nim (hunk 4 above)
Comment (ZoomRmc) [reply compiler/sigmatch.nim]: Ok, again, I think this is the only way I could made it all work without redesigning the whole overload resolution to preserve the info on available alternatives for longer.

Regarding the node flag, looks like it might work, let's see what Araq has to say about adding it.

File: compiler/sem.nim (hunk 1 above)
Comment (ZoomRmc) [reply compiler/sem.nim]: Looks like you're right, and it's some dead weight from earlier attempts to make it all work.

File: compiler/sem.nim (hunk 3 above)
Comment (ZoomRmc) [reply compiler/sem.nim]: I think this might actually be inconsequential in the final state of the PR implementation, let's see what CI has to say.

File: compiler/sigmatch.nim (hunk 4 above)
Comment (Araq) [reply compiler/sigmatch.nim]: Node flags are a constant PITA. The macro system doesn't cover them, usually one doesn't know what to do with them wrt copying semantics and if you know the flag should be copied over (usually true), there is the bad news that thousands of lines of code don't bother with it anyway as they use newNode() instead of copyNode()...

Comment (ZoomRmc) [reply compiler/sigmatch.nim]: Understood. I think new node flag here looks leaky and barely worth it, considering it's just an optimization at this point and  re-sem is strongly conditional even without it.

Comment (ZoomRmc) [reply compiler/sigmatch.nim]: The obvious answer is storing a no-false-negatives flag, like "definitelyNoIteratorOverload", so losing it does not result in skipping the re-sem, but I think if it's not in the persistent list we're going to lose this flag in most cases anyway, and it's too obscure and specific for just an optimization that's not even guaranteed to kick-in.

**Comment by Araq** [comment]
@metagn review it one more time please.

File: compiler/sigmatch.nim [hunk 5]
```diff
@@ -2765,6 +2771,17 @@ proc prepareOperand(c: PContext; formal: PType; a: PNode, newlyTyped: var bool):
     considerGenSyms(c, result)
     if result.kind != nkHiddenDeref and result.typ.kind in {tyVar, tyLent} and c.matchedConcept == nil:
       result = newDeref(result)
+    if formal.kind == tyIterable and result.typ.kind != tyIterable and
+        a.kind in nkCallKinds and a[0].kind in {nkIdent, nkAccQuoted, nkSym, nkOpenSym}:
+      let recheck = copyTree(a)
+      recheck.typ = nil
+      if recheck[0].kind == nkSym and recheck[0].sym != nil:
+        recheck[0] = newIdentNode(recheck[0].sym.name, recheck[0].info)
```
Comment (metagn) [inline compiler/sigmatch.nim:2782]: Either of the following should prevent unwanted errors here:
* wrapping the sym in `nkOpenSymChoice` instead of turning it to an ident (as long as this keeps the same functionality)
* adding `efNoUndeclared` as a flag below

Edit: I tested it and `efNoUndeclared` does not work unless you call `semOverloadedCallAnalyseEffects` directly instead of `semOperand` but this isn't available in sigmatch. Symchoice worked for me like so:
```nim
recheck[0] = newTreeI(nkOpenSymChoice, recheck[0].info, recheck[0])
```
but in case it matters, symchoices usually have the type `tyNone` (via `newTypeS(tyNone, c)`), so `newTreeIT` could be used or the `.typ` could be set after manually.

An example of where this might come up is:

```nim
# a.nim
import std/strutils

template collect[T](it: iterable[T]): seq[T] =
  block:
    var res: seq[T] = @[]
    for x in it:
      res.add x
    res

template foo(s: string): untyped =
  s.split.collect # captures split overloads

# b.nim
import a

# split overloads are no longer accessible
let words = foo("abc")
```

Since this already didn't work before it doesn't matter if this still doesn't work, however if we try a semcheck over an ident here it might give an "undeclared identifier" error instead of the normal "could not match `collect` expected iterable got seq[string]".

**Comment by metagn** [comment]
No other objections to the implementation, and the design is unlikely to cause regressions from what I understand, should be good except the 1 comment above.

File: compiler/sigmatch.nim (hunk 5 above)
Comment (ZoomRmc) [reply compiler/sigmatch.nim:2782]: Eh, I think at this point we have only the chosen overload symbol so there's not much to wrap in `nkOpenSymChoice`. We probably wouldn't need to re-sem if we had information on other symbols, right?

Comment (metagn) [reply compiler/sigmatch.nim:2782]: The point is to prevent the resem from erroring (as happens in the snippet), otherwise yes it doesn't gain any information

If you wanted to be precise you can also call `semOverloadedCall` with `efNoUndeclared` and a filter on just `{skIterator}` instead of `semOperand`, it's already included as a callback but you would need to copy the code from `semOverloadedCallAnalyzeEffects` to build the iterable type.

Comment (ZoomRmc) [reply compiler/sigmatch.nim:2782]: Ok, it we don't gain much besides keeping the retry from failing, then to me `efNoUndeclared` looks a bit more attractive :). The `{skIterator}`  retry sounds like a cleaner approach but I'm pretty sure I'll mess it up.
Thanks a lot for the suggestions!
