### PR TITLE
fix #8329, allow case insensitive xmltree.findAll

### LINKED ISSUE #8329: `xmltree.findAll` doesn't work as expected with `htmlparser` for non-lowercase names
I tried the example from [here](https://nim-lang.org/docs/htmlparser.html#example-transforming-hyperlinks) on something like
```html
<P class=MsoNormal 
style="MARGIN-BOTTOM: 0pt; LINE-HEIGHT: normal; TEXT-AUTOSPACE: ; mso-pagination: none; mso-layout-grid-align: none"><SPAN 
lang=de 
style='FONT-SIZE: 12pt; FONT-FAMILY: "TimesNewRoman","serif"; mso-bidi-font-family: TimesNewRoman; mso-ansi-language: #0007'>1</SPAN><I><SPAN lang=de 
style='FONT-SIZE: 12pt; FONT-FAMILY: "TimesNewRoman,Italic","serif"; mso-bidi-font-family: "TimesNewRoman,Italic"; mso-ansi-language: #0007'>2<o:p></o:p></SPAN></I></P>
```
but `html.findAll("P")` doesn't work, instead only `html.findAll("p")` works, which is unexpected.

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

File: lib/pure/xmltree.nim [hunk 1]
```diff
@@ -658,43 +658,55 @@ proc findAll*(n: XmlNode, tag: string, result: var seq[XmlNode]) =
...
+    a.findAll("BAD", s, caseInsensitive = true)
+    assert $s == "@[<bad>c text</bad>, <BAD>d text</BAD>]"
 
   assert n.k == xnElement
   for child in n.items():
     if child.k != xnElement:
       continue
-    if child.tag == tag:
+    if child.tag == tag or
+        (caseInsensitive and child.tag.toLowerAscii == tag.toLowerAscii):
```
Comment (Araq) [inline lib/pure/xmltree.nim]: Instead use ``caseInsensitive and cmpIgnoreCase(child.tag, tag) == 0``
