### PR TITLE
Fixed generic parameters failing to be used in inheritance

### LINKED ISSUE #21864: Inheritance off a generic parameter causes a ICE
### Description

Using the following inheritance tree crashes the compiler inside semtypes:
```nim
type
  HorzLayout[Base, T] = ref object of Base
    data: seq[T]
  UiElement = ref object of RootObj
  Child2[T] = ref object of HorzLayout[UiElement, T]
```

### Nim Version

Present devel

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by beef331**
Fixes #21864

### CODE REVIEW

**Comment by Araq** [comment]
package_level_objects/definefoo.nim(2, 22) Error: Cannot inherit from: 'Foo'

File: compiler/semtypes.nim [hunk 1]
```diff
@@ -1527,7 +1539,10 @@ proc semGeneric(c: PContext, n: PNode, s: PSym, prev: PType): PType =
     return errorType(c)
   if tx != result and tx.kind == tyObject:
     if tx[0] != nil:
-      semObjectTypeForInheritedGenericInst(c, n, tx)
+      if not trySemObjectTypeForInheritedGenericInst(c, n, tx):
+        {.cast(uncheckedAssign).}:
+          result.kind = tyError
```
Comment (Araq) [inline compiler/semtypes.nim]: Dangerous, why is it required? Why can't it be `return newOrPrevType(tyError, prev, c)` or similar?

Comment (beef331) [reply compiler/semtypes.nim]: It's not, I'm just daft.
