### PR TITLE
fix #15934 and #15620

### LINKED ISSUE #15620: [1.2.8 and 1.4 regression] Marshal can't load a string if it was null
It worked in 1.2.6 and earlier, but doesn't work now

### Example
```nim
import marshal

let str = """{"numeric": null}"""

type
  LegacyEntry = object
    numeric: string

let test = to[LegacyEntry](str)
echo test
```

### Current Output
```
Traceback (most recent call last)
/home/dian/Projects/nim-snippets/fa.nim(10) fa
/home/dian/Things/Nim/lib/pure/marshal.nim(343) to
/home/dian/Things/Nim/lib/pure/marshal.nim(276) loadAny
/home/dian/Things/Nim/lib/pure/marshal.nim(196) loadAny
/home/dian/Things/Nim/lib/pure/marshal.nim(231) loadAny
/home/dian/Things/Nim/lib/core/typeinfo.nim(330) setPointer
/home/dian/Things/Nim/lib/system/assign.nim(139) genericAssign
/home/dian/Things/Nim/lib/system/assign.nim(136) genericAssignAux
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
(numeric: "")
```

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-10-17
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: b16b2eb06fa09b22ab50b3bd2703fe79c0ca4fc6
active boot switches: -d:release
```

### LINKED ISSUE #15934: Marshalling and options of reference types
Marshalling an ``Option[T]`` where ``T`` is a reference type (in my case ``T`` is ``JsonNode``) leads to a Segmentation fault if the value is ``none(T)``.

### Example
```nim
import marshal, options, json
let
  a1 = some(newJNull())
  a2 = none(JsonNode)
echo ($$a1).to[:Option[JsonNode]]
echo ($$a2).to[:Option[JsonNode]]
```
### Current Output
```
Some(null)
Traceback (most recent call last)
code/nim/test_marshal_option.nim(7) test_marshal_option
.choosenim/toolchains/nim-#devel/lib/pure/marshal.nim(343) to
.choosenim/toolchains/nim-#devel/lib/pure/marshal.nim(276) loadAny
.choosenim/toolchains/nim-#devel/lib/pure/marshal.nim(196) loadAny
.choosenim/toolchains/nim-#devel/lib/pure/marshal.nim(211) loadAny
.choosenim/toolchains/nim-#devel/lib/core/typeinfo.nim(330) setPointer
.choosenim/toolchains/nim-#devel/lib/system/assign.nim(139) genericAssign
.choosenim/toolchains/nim-#devel/lib/system/assign.nim(134) genericAssignAux
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
Some(null)
None[JsonNode]
```

### Additional Information

The issue is present with version 1.2.8, 1.4.0 and the current devel (see below).
It works as expected in version 1.2.6.

It might be related to issue #15620 

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-11-12
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: a81434a890d70e7146c440c59caadc701c6099b3
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #15934 
fix #15620

### CODE REVIEW

File: lib/core/typeinfo.nim [hunk 1]
```diff
@@ -327,7 +327,8 @@ proc setPointer*(x: Any, y: pointer) =
   ## ``akString``, ``akCString``, ``akProc``, ``akRef``, ``akPtr``,
   ## ``akPointer``, ``akSequence``.
   assert x.rawType.kind in pointerLike
-  genericAssign(x.value, y, x.rawType)
+  if y != nil:
+    genericAssign(x.value, y, x.rawType)
```
Comment (Araq) [inline lib/core/typeinfo.nim:331]: This fix is not correct. You need to set ``x.value`` to ``nil`` if y == nil.

**Comment by ringabout** [comment]
I will copy tests from this:
https://github.com/nim-lang/Nim/pull/15342
https://github.com/nim-lang/Nim/issues/9754

Tests works as expected locally:
```
D:\QQPCmgr\Desktop\Nim>choosenim 1.2.6
   Switched to Nim 1.2.6

D:\QQPCmgr\Desktop\Nim>testament r stdlib/t9754.nim
FAIL: tests/stdlib/t9754.nim C
Test "tests\stdlib\t9754.nim" in category "stdlib"
Failure: reExitcodesDiffer
Expected:
exitcode: 0

Gotten:
exitcode: 1

Output:
{"age": 12, "bio": "Я Cletus", "blob": [65, 66, 67, 128], "name": "Cletus"}
true
true
alpha 100
omega 200
Traceback (most recent call last)
tparsesql.nim(107)       tparsesql
parsesql.nim(1502)       parseSQL
parsesql.nim(1494)       parseSQL
parsesql.nim(1169)       parse
parsesql.nim(1158)       parseStmt
parsesql.nim(1066)       parseSelect
parsesql.nim(944)        parseFromItem
parsesql.nim(1066)       parseSelect
parsesql.nim(944)        parseFromItem
parsesql.nim(1066)       parseSelect
parsesql.nim(580)        add
gc.nim(448)              newSeq
gc.nim(440)              newObj
alloc.nim(783)           rawAlloc
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

FAILURE! total: 1 passed: 0 skipped: 0 failed: 1

D:\QQPCmgr\Desktop\Nim>testament --nim:bin/nim_temp r stdlib/t9754.nim
PASS: tests/stdlib/t9754.nim C                                     ( 7.26 sec)
Used bin/nim_temp.exe to run the tests. Use --nim to override.
```

**Comment by ringabout** [comment]
This PR also tests memory corruption issue from #9754
