### PR TITLE
Lexer fix for multi byte characters

### LINKED ISSUE #7884: non-ASCII letters gives error when using object
From https://forum.nim-lang.org/t/3860
The following code

```nim
type Test* = object
  あ: int
  い: int

proc add(test: Test): int =
  test.あ + test.い

let a = Test(あ: 123, い: 122)

echo a
echo add(a)
```

gives the following error

```
test.nim(8, 1) Error: invalid indentation
```

### PR DESCRIPTION
**Pull request by GULPF**
Turns out that that multi byte characters where sometimes treated as operators.

Fixes #7884

### CODE REVIEW

**Comment by tim-st** [comment]
I think the comment means this line should be changed, too:
https://github.com/nim-lang/Nim/blob/25a41d5d90c707e8d926308c495c95e2cd13d984/lib/packages/docutils/highlite.nim#L133

**Comment by GULPF** [comment]
Fixed, thanks

File: tests/parser/tunicodeidents.nim [hunk 1]
```diff
@@ -0,0 +1,11 @@
+discard """
+    action: run
+"""
+
```
Comment (Araq) [inline tests/parser/tunicodeidents.nim]: This test case can easily be added to one of the existing lexer tests instead.
