### PR TITLE
fixes #20873; rework vcc with arc/orc

### LINKED ISSUE #20873: arc/orc is broken for vcc (devel)
### What happened?

The compiler fails with an error when trying to compile using arc/orc any simple code such as an `echo "hello"`. This error only appears using `--cc:vcc`.

### Nim Version

Nim Compiler Version 1.7.3 [Windows: amd64]
Compiled at 2022-11-17
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 68f6926348da35c82a637ec3bc7f9ea0d761f615
active boot switches: -d:release

### Current Standard Output Logs

```shell
nim c --cc:vcc -f --mm:arc test
Hint: used config file 'E:\Nim\config\nim.cfg' [Conf]
Hint: used config file 'E:\Nim\config\config.nims' [Conf]
....................................................
E:\Nim\lib\system\alloc.nim(768, 19) template/generic instantiation of `atomicPrepend` from here
E:\Nim\lib\system\alloc.nim(762, 16) template/generic instantiation of `storea` from here
E:\Nim\lib\system\alloc.nim(145, 36) Error: undeclared identifier: 'atomicStoreN'
candidates (edit distance, scope distance); see '--spellSuggest':
 (4, 3): 'atomicLoadN' [proc declared in E:\Nim\lib\system\atomics.nim(192, 8)]
 (4, 3): 'atomicStatDec' [template declared in E:\Nim\lib\system\alloc.nim(155, 10)]
 (4, 3): 'atomicStatInc' [template declared in E:\Nim\lib\system\alloc.nim(156, 10)]

```

With `--threads:off` the error message is different.
```
nim c --cc:vcc -f --mm:arc --threads:off test
Hint: used config file 'E:\Nim\config\nim.cfg' [Conf]
Hint: used config file 'E:\Nim\config\config.nims' [Conf]
..............................................
E:\Nim\lib\system\alloc.nim(768, 19) template/generic instantiation of `atomicPrepend` from here
E:\Nim\lib\system\alloc.nim(763, 10) Error: undeclared identifier: 'atomicCompareExchangeN'
candidates (edit distance, scope distance); see '--spellSuggest':
 (10, 4): 'interlockedCompareExchange8' [proc declared in E:\Nim\lib\system\atomics.nim(254, 10)]

```

### Expected Standard Output Logs

```shell
It is expected to compile without problems.
```

### Possible Solution

_No response_

### Additional Information

I believe it is connected with this #20492

### PR DESCRIPTION
**Pull request by ringabout**
fixes https://github.com/nim-lang/Nim/issues/20873

### CODE REVIEW

File: lib/std/sysatomics.nim [hunk 1]
```diff
@@ -245,21 +288,6 @@ proc atomicDec*(memLoc: var int, x: int = 1): int {.inline, discardable, raises:
     result = memLoc
 
 when someVcc:
-  when defined(cpp):
-    proc interlockedCompareExchange64(p: pointer; exchange, comparand: int64): int64
-      {.importcpp: "_InterlockedCompareExchange64(static_cast<NI64 volatile *>(#), #, #)", header: "<intrin.h>".}
-    proc interlockedCompareExchange32(p: pointer; exchange, comparand: int32): int32
-      {.importcpp: "_InterlockedCompareExchange(static_cast<NI volatile *>(#), #, #)", header: "<intrin.h>".}
```
Comment (ringabout) [inline lib/std/sysatomics.nim:252]: Isn't NI means int?
