### PR TITLE
fix #16474 `unittest.check type1 is type2` gives CT error

### LINKED ISSUE #16474: regression (1.4.0=>1.4.2, devel): `unittest.check type1 is type2` gives CT error
### Example
```nim
when true:
  import unittest
  check (type(1.0)) is float
```

### Current Output
 Error: invalid type: 'type float64' for var

### Expected Output
works

### Additional Information
1.4.0: works
1.4.2: fails
devel 1.5.1 a29bbeee41e43f00ba7a3b1951445ff5d21ccc52: fails

* without parens, it fails for devel, 1.4.0, 1.2.0
```nim
  import unittest
  check type(0.1) is float
```
(for 1.2.0, the error is: unittest.nim(647, 43) Error: 'typedesc' metatype is not valid here; typed )

* with an intermediate typedef it works, but then the check error message on check fail is not as informative because it doesn't show the expression being asserted:
```nim
when true:
  import unittest
  type T = type(0.1)
  check T is float
  check T is int
```

```
t11582.nim(26, 10): Check failed: T is int
T was float64
int was int
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #16474
fix #https://github.com/timotheecour/Nim/issues/131

fix check with pars which is a regression
```nim
when true:
  import unittest
  check (type(1.0)) is float
```

fix check without pars which is a bug
```nim
  import unittest
  check type(0.1) is float
```

### CODE REVIEW

File: lib/pure/unittest.nim [hunk 1]
```diff
@@ -669,7 +669,8 @@ macro check*(conditions: untyped): untyped =
           let paramAst = exp[i]
           if exp[i].kind == nnkIdent:
             result.printOuts.add getAst(print(argStr, paramAst))
-          if exp[i].kind in nnkCallKinds + {nnkDotExpr, nnkBracketExpr, nnkPar}:
+          if exp[i].kind in nnkCallKinds + {nnkDotExpr, nnkBracketExpr, nnkPar} and
+                  (exp[i].typeKind notin {ntyTypeDesc} or $exp[0] notin ["is", "isnot"]):
```
Comment (Clyybber) [inline lib/pure/unittest.nim:673]:
```suggestion
                  not(exp[i].typeKind in {ntyTypeDesc} and $exp[0] in ["is", "isnot"]):
```

Comment (ringabout) [reply lib/pure/unittest.nim:673]: Is it more clear than before?

Comment (ringabout) [reply lib/pure/unittest.nim:673]: Neither of both is readable.

File: tests/stdlib/tunittestpass.nim [hunk 2]
```diff
@@ -0,0 +1,19 @@
+discard """
+  targets: "c js"
+"""
+
```
Comment (timotheecour) [inline tests/stdlib/tunittestpass.nim:4]: @xflywind why not in tests/stdlib/tunittest.nim ?

Comment (ringabout) [reply tests/stdlib/tunittestpass.nim:4]: `tests/stdlib/tunittest.nim ` is very messy.
