### PR TITLE
fixes #24504; fixes `ensureMove` for refs

### LINKED ISSUE #24504: ensureMove usage leading to memory leak for JsonNode !
### Description

I was using `ensureMove` with custom objects to make sure compiler is doing what i expect.
I accidentally used `ensureMove`  with a `JsonNode` (with kind `JObject`),  later i pinned memory leak to usage of `ensureMove` .

I am not sure if i am supposed to use `ensureMove` anywhere , but compiler didn't give me any warning.

Following minimal code reproduces the issue for me .

```nim

# happens both with ARC and ORC mm
import std/json
proc test_something():JsonNode=

    var final_result = JsonNode(kind:JObject)
    var a = JsonNode(kind:JArray)
    for i in 0..<10000:
        a.add(JsonNode(kind:JString, str:"random string"))
    final_result["key"] = ensureMove a
    # final_result["key"] = a

    return final_result

var temp:JsonNode
for i in 0..<100000:
    temp = test_something()
```
 

### Nim Version

Nim Compiler Version 2.2.0 [Windows: amd64]
Compiled at 2024-10-02
Copyright (c) 2006-2024 by Andreas Rumpf

active boot switches: -d:release

### Current Output

_No response_

### Expected Output

```text
I think it is not supposed to do memory leak or i don't know if `ensureMove` is supposed to be used for custom objects only!
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #24504

### CODE REVIEW

File: compiler/injectdestructors.nim [hunk 1]
```diff
@@ -888,7 +888,11 @@ proc p(n: PNode; c: var Con; s: var Scope; mode: ProcessMode; tmpFlags = {sfSing
...
       if n[0].kind == nkSym and n[0].sym.magic == mEnsureMove:
         inc c.inEnsureMove
-        result = p(n[1], c, s, sinkArg)
+        if isAnalysableFieldAccess(n[1], c.owner) and isLastRead(n[1], c, s) and
+            hasDestructor(n[1].typ):
+          result = p(n[1], c, s, normal)
+        else:
+          result = p(n[1], c, s, sinkArg)
         dec c.inEnsureMove
         return
```
Comment (Araq) [inline compiler/injectdestructors.nim]: I think the real problem here is your special case and the `return`. Instead the usual logic should be performed where the diagnosis intercepts `c.inEnsureMove`.

Comment (ringabout) [reply compiler/injectdestructors.nim:894]: I made the return because `ensureMove` has different logic with normal calls. The bug is that the `result` should have been destroyed if it is sunk.

Comment (ringabout) [reply compiler/injectdestructors.nim]: Most logic of normal calls are not needed for `ensureMove`. The bug is that when a value is moved to a location (`sinkArg`), the location should own the value and ensure its destruction. (Another way is to translate `ensureMove(x)` into `move(x)` instead of `=sink(x)`)

Comment (Araq) [reply compiler/injectdestructors.nim]: So where did you get this logic from?

Comment (ringabout) [reply compiler/injectdestructors.nim]: > Instead the usual logic should be performed where the diagnosis intercepts c.inEnsureMove.

Okay, I removed the special treatment. Though I need to pass the paramenter of `ensureMove` with `sinkArg`?

**Comment by Araq** [comment]
@narimiran this needs to be backported to every relevant version.
