### PR TITLE
fix #15043

### LINKED ISSUE #15043: [ARC] Compiler error with a closure proc in a macro
This code doesn't work with arc while it should. Found in https://github.com/PMunch/macroutils. Maybe compiler forgets that this is compile-time? :P 

### Example
```nim
import macros

macro extract(): untyped =
  result = newStmtList()
  var x: seq[tuple[node: NimNode]]

  proc test(n: NimNode) {.closure.} =
    x.add (node: n)
  
  test(parseExpr("discard"))
  
extract()
```

### Current Output
```
/home/dian/Stuff/arctest/macroutils/a.nim(3, 7) Error: cannot generate destructor for generic type: seq[tuple[node: NimNode]]
```

### Expected Output
Successful compilation

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-07-23
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: ec65bfae3ac20a6c3d13249bc1fc8413db2b3abb
active boot switches: -d:release -d:danger
```

### PR DESCRIPTION
**Pull request by cooldome**
fix #15043

### CODE REVIEW

File: tests/arc/trepr.nim [hunk 1]
```diff
@@ -71,3 +71,19 @@ proc p2 =
 
 discard repr p2
 
+
+#####################################################################
```
Comment (timotheecour) [inline tests/arc/trepr.nim:75]: move to tests/arc/tarcmisc.nim
(not related to repr IIUC)

**Comment by cooldome** [comment]
Test failures unrelated

File: tests/arc/trepr.nim (hunk 1 above)
Comment (cooldome) [reply tests/arc/trepr.nim:75]: I have chosen `trepr` because is busy `tarcmisc` with my other PR and I don't want to introduce merging conflicts. Anything else except `tarcmisc` ?
