### PR TITLE
fixes #19278; make `privateAccess` work with generic ref object

### LINKED ISSUE #19278: `privateAccess` doesn't work with generic `ref object` types.
I haven't been able to make `privateAccess` work on standalone generic ref types. `ARef[T] = ref A[T]` works, but `B[T] = ref object` doesn't.

### Example
```nim
# module a
type
  A[T] = object
    a: T
  ARef*[T] = ref A[T]
  B*[T] = ref object
    a: T
```

```nim
# module main
import std/importutils
import a

privateAccess ARef
let x = ARef[int](a: 1)  # works

privateAccess B
let y = B[int](a: 1)  # Error: the field 'a' is not accessible
```

In addition to `privateAccess B` I've tried `privateAccess B[int]`, `privateAccess B[int].default.type`, and `privateAccess B[int].default[].type`

```
$ nim -v
Nim Compiler Version 1.6.2 [MacOSX: arm64]
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes #19278

### CODE REVIEW

File: compiler/suggest.nim [hunk 1]
```diff
@@ -265,8 +265,8 @@ proc fieldVisible*(c: PContext, f: PSym): bool {.inline.} =
       if fmoduleId == module.id: return true
     if f.kind == skField:
       var symObj = f.owner
-      if symObj.typ.kind in {tyRef, tyPtr}:
-        symObj = symObj.typ[0].sym
+      if symObj.typ.skipTypes({tyGenericBody}).kind in {tyRef, tyPtr}:
```
Comment (Araq) [inline compiler/suggest.nim]: What about `tyGenericInst`? Why not use `skipTypes(abstractInst)` here?

Comment (ringabout) [reply compiler/suggest.nim]: I changed it to `{tyGenericBody, tyGenericInst, tyGenericInvocation, tyAlias}` which is consistent with `toObjectFromRefPtrGeneric`.
