### PR TITLE
fix #9695 asyncmacro: tfuturevar fails when activated [backport: 1.0]

### LINKED ISSUE #9695: tfuturevar fails when activated
The test [tfuturevar](https://github.com/nim-lang/Nim/blob/devel/tests/async/tfuturevar.nim) is not executed, even though it should be executed. When it is activated, it fails.

this is the output on my machine
```
tfuturevar.nim(46)       tfuturevar
asyncmacro.nim(307)      main
asyncmacro.nim(39)       main_continue
tfuturevar.nim(29)       mainIter
asyncfutures.nim(313)    read
[[reraised from:
tfuturevar.nim(46)       tfuturevar
asyncdispatch.nim(1658)  waitFor
asyncfutures.nim(308)    read
]]
Error: unhandled exception: Future still in progress.
Async traceback:
  tfuturevar.nim(46)    tfuturevar
  asyncmacro.nim(307)   main
  asyncmacro.nim(39)    main_continue
    ## Resumes an async procedure
  tfuturevar.nim(29)    mainIter
  asyncfutures.nim(313) read
Exception message: Future still in progress.
Exception type: [ValueError]
Error: execution of an external program failed: '/home/arne/proj/nim/Nim/tests/async/tfuturevar '
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #9695
This bug is introduced in https://github.com/nim-lang/Nim/pull/7573

### CODE REVIEW

**Comment by disruptek** [comment]
I appreciate that fixes go in but pull and commit titles like this really do remove a lot of value from the git history.

File: tests/async/tfuturevar.nim [hunk 1]
```diff
@@ -1,7 +1,6 @@
 discard """
```
Comment (timotheecour) [inline tests/async/tfuturevar.nim]: if action is `run`, it's implied, so the whole discard section can go away (unless you need other testament spec fields)

**Comment by timotheecour** [comment]
> I appreciate that fixes go in but pull and commit titles like this really do remove a lot of value from the git history.

I think what @disruptek is saying is that the PR title should be:
`fix #9695 asyncmacro[backport: 1.0]`
(or, up to you, `fix #9695 asyncmacro: tfuturevar fails when activated [backport: 1.0]`)
and the 1st commit msg should also mention `fix #9695` (so that when squash and merge happens, the commit msg will be correct and the person who's merging won't have to edit it by hand)

other than this, +1 for this bugfix!

**Comment by ringabout** [comment]
Thanks! I have changed the title.

File: tests/async/tfuturevar.nim (hunk 1 above)
Comment (ringabout) [inline tests/async/tfuturevar.nim]:
```suggestion
```

File: tests/async/tfuturevar.nim [hunk 2]
```diff
@@ -1,7 +1,6 @@
...
-action: compile
+action: run
```
Comment (ringabout) [inline tests/async/tfuturevar.nim]:
```suggestion
```

File: tests/async/tfuturevar.nim [hunk 3]
```diff
@@ -1,7 +1,6 @@
...
 """
```
Comment (ringabout) [inline tests/async/tfuturevar.nim]:
```suggestion
```

File: tests/async/tfuturevar.nim [hunk 4]
```diff
@@ -1,7 +1,6 @@
...
-# XXX: action should be run!
```
Comment (ringabout) [inline tests/async/tfuturevar.nim]:
```suggestion
```

File: lib/pure/asyncmacro.nim [hunk 5]
```diff
@@ -118,7 +118,8 @@ proc getFutureVarIdents(params: NimNode): seq[NimNode] {.compileTime.} =
   for i in 1 ..< len(params):
     expectKind(params[i], nnkIdentDefs)
     if params[i][1].kind == nnkBracketExpr and
-       params[i][1][0].eqIdent("futurevar"):
+       params[i][1][0].eqIdent("FutureVar"):
```
Comment (timotheecour) [inline lib/pure/asyncmacro.nim]: `FutureVar.astToStr` ?
more typesafe (and avoid similar bugs in future eg if variable is renamed, you'll get a CT error instead of silently being wrong

**Review by timotheecour — APPROVED** [review]

File: lib/pure/asyncmacro.nim (hunk 5 above)
Comment (xflywind) [reply lib/pure/asyncmacro.nim:121]: It's not the part of this PR.
And many `eqident`s are used in this file

Comment (ringabout) [reply lib/pure/asyncmacro.nim]: Sounds useful!

Comment (ringabout) [reply lib/pure/asyncmacro.nim]: I will add this later in this PR.

Comment (ringabout) [inline lib/pure/asyncmacro.nim]:
```suggestion
       params[i][1][0].eqIdent(FutureVar.astToStr):
```
