### PR TITLE
Field checks for everybody

### LINKED ISSUE #6612: Issue with javascript compiler, var parameters and case fields
This snippet of code runs well on the native compiler, but doesn't work when js compiled

~~~nim
proc fillWith(sq: var seq[int], n: int, unused: string) =
  # It's skipping the *n* parameter
  # the string "unused" is being saved in *n*
  # and *unused* is undefined

  # TypeError: Cannot read property 'length' of undefined
  # echo "unused: ", unused

  echo "Fill with the number ", n
  sq = @[n]

type
  Object = object of RootObj
    case hasNums: bool
    of true:
      numbers: seq[int]
    of false:
      discard
    always: seq[int]

var obj = Object(hasNums: true)

# Works, because *always* does not depend on a case field
obj.always.fillWith(5, "unused")
echo obj.always

# Doesn't work, because *numbers* depends on *hasNums*
obj.numbers.fillWith(3, "unused")
echo obj.numbers
~~~

Output of `nim c -r main.nim`:
~~~
Fill with the number 5
@[5]
Fill with the number 3
@[3]
~~~

Output of `nim js -r main.nim`:
~~~
Fill with the number 5
@[5]
Fill with the number 117,110,117,115,101,100,0
/.../nimcache/main.js:385
		sq_25007[sq_25007_Idx] = nimCopy(null, [n_25008], NTI25023);
		                       ^

TypeError: Cannot set property '3' of null
    at fillWith_25003 (/.../nimcache/main.js:385:26)
    at Object.<anonymous> (/.../nimcache/main.js:632:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
~~~

`Nim Compiler Version 0.17.2 (2017-09-11) [Linux: i386]`

### PR DESCRIPTION
**Pull request by LemonBoy**
To do before merging:

- New test case for
```nim
static:
  doAssertRaises(ValueError):
    raise newException(ValueError, "Yes")
```
- Some tests for the VM (?)
- Accidentally fixes #6612, add a test case
- Find who thought that adding the field name only to `nkCheckedFieldExpr` was a good idea

### CODE REVIEW

File: compiler/lowerings.nim [hunk 1]
```diff
@@ -281,15 +281,16 @@ proc genDeref*(n: PNode): PNode =
                      n.typ.skipTypes(abstractInst).sons[0])
   result.add n
 
-proc callCodegenProc*(g: ModuleGraph; name: string, arg1: PNode;
-                      arg2, arg3, optionalArgs: PNode = nil): PNode =
-  result = newNodeI(nkCall, arg1.info)
+proc callCodegenProc*(g: ModuleGraph; name: string;
+                      arg1, arg2, arg3, optionalArgs: PNode = nil): PNode =
+  let info = if arg1 != nil: arg1.info else: g.emptyNode.info
```
Comment (Araq) [inline compiler/lowerings.nim]: This is bad, ``callCodegenProc`` needs an ``info`` parameter instead then.

File: compiler/vmgen.nim [hunk 2]
```diff
@@ -544,6 +544,7 @@ proc needsAsgnPatch(n: PNode): bool =
 
 proc genField(c: PCtx; n: PNode): TRegister =
   if n.kind != nkSym or n.sym.kind != skField:
+    debug n
```
Comment (Araq) [inline compiler/vmgen.nim]: Remove this again please.

**Comment by LemonBoy** [comment]
Ready for review, now the LHS of the `nkDotExpr` is only evaluated once.
The only rough part that remains is the use of `opcQuit` to signal the error condition.
