### PR TITLE
Don't prepend project path to absolute filenames passed to setCommand

### LINKED ISSUE #4765: nimscript: `setcommand` doesn't support absolute paths on Windows
``` nim
import ospaths

--app:lib
--define:createNimRtl

let nimDir = findExe("nim").parentDir.parentDir
setcommand "c", nimDir / "lib" / "nimrtl.nim"
```

fails:

```
Error: cannot open 'c:\dev\tmp\c:\dev\nim\lib\nimrtl.nim'
```

The reason - code in `compiler/scriptconfig.nim` assumes `canonicalizePath` raises `OSError` on invalid paths. On Windows it does not.

### PR DESCRIPTION
**Pull request by nigredo-tori**
fixes #4765

### CODE REVIEW

File: compiler/scriptconfig.nim [hunk 1]
```diff
@@ -110,10 +110,14 @@ proc setupVM*(module: PSym; cache: IdentCache; scriptName: string;
     let arg = a.getString 1
     if arg.len > 0:
       gProjectName = arg
+      let path = (block:
```
Comment (Araq) [inline compiler/scriptconfig.nim]: get rid of the '(block: )', completely unnecessary

Comment (nigredo-tori) [inline compiler/scriptconfig.nim]: @Araq, done
