### PR TITLE
Implicit return working for async proc

### LINKED ISSUE #11558: Implicit return in `{.async.}` proc causes compile error
Simple example of the behavior:

```nim
import asyncdispatch
import httpclient
import json

proc works*(path: string): Future[JsonNode] {.async.} =
  let resp = newAsyncHttpClient().getContent("https://httpbin.org/get?x=10&y=20")
  return parseJson(await resp)

proc failsToCompile*(path: string): Future[JsonNode] {.async.} =
  let resp = newAsyncHttpClient().getContent("https://httpbin.org/get?x=10&y=20")

  # without the `return` the compiler complains.
  parseJson(await resp)
```

Without the `return`, the compiler error is:

```
/usercode/in.nim(5, 38) template/generic instantiation of `async` from here
/usercode/in.nim(7, 12) Error: expression 'parseJson(read(future508016))' is of type 'JsonNode' and has to be discarded
```

I don't know if this is intentional. If so, it would be good to understand why. Otherwise, I believe this to be a bug?

```
$ nim -v
Nim Compiler Version 0.20.0 [Windows: amd64]
Compiled at 2019-06-06
Copyright (c) 2006-2019 by Andreas Rumpf
```
git hash: e7471cebae2a404f3e4239f199f5a0c422484aac
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ire4ever1190**
Closes #11558

Uses an overloaded template to tell if the block has an implicit return or not

### CODE REVIEW

**Comment by ire4ever1190** [comment]
Docs CI failing because of #20938

**Comment by Araq** [comment]
Please rebase.

File: tests/async/t11558.nim [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import std/asyncdispatch
+discard """
+output: "Hello\n9"
+"""
```
Comment (Araq) [inline tests/async/t11558.nim]:
```suggestion
discard """
output: "Hello\n9"
"""
import std/asyncdispatch
```

File: lib/pure/asyncmacro.nim [hunk 2]
```diff
@@ -214,9 +214,18 @@ proc asyncSingleProc(prc: NimNode): NimNode =
   # don't do anything with forward bodies (empty)
   if procBody.kind != nnkEmpty:
     # fix #13899, defer should not escape its original scope
-    procBody = newStmtList(newTree(nnkBlockStmt, newEmptyNode(), procBody))
-    procBody.add(createFutureVarCompletions(futureVarIdents, nil))
+    let blockStmt = newStmtList(newTree(nnkBlockStmt, newEmptyNode(), procBody))
+    procBody = newStmtList()
     let resultIdent = ident"result"
+    procBody.add quote do:
+      template setResult(x: `subRetType`) {.used.} =
```
Comment (arnetheduck) [inline lib/pure/asyncmacro.nim:221]: We've considered a similar thing in chronos so that nim-result can work better - https://github.com/status-im/nim-chronos/pull/297 - perhaps we should coordinate the mechanism here - one thing that often comes up is symbol resolution issues - ie template lookup scope is confusing / broken and has a tendency to ruin unrelated code when used together with generics: https://github.com/status-im/nim-stew/issues/161 - as a consequence, we've started using more "unique" names, also for "private" templates like this.

Comment (ire4ever1190) [reply lib/pure/asyncmacro.nim:221]: From reading those PR's I think this is a different problem to whats in them. This doesn't effect how its returned but just means that code like this can now compile and work (Doesn't effect how normal `return` and `result = ` works)
```nim
# Not exactly a good async example, but just needed something basic
proc foo(x: int): Future[string] {.async.} =
  if x mod 2 == 0:
    "even"
  else:
    "odd"
```

But see what you mean about needing unique names. Maybe could make it very explicit like `asyncDispatchSetResult`?

**Comment by arnetheduck** [comment]
@Araq  this needed a more unique name for the template

**Comment by ire4ever1190** [comment]
Sorry my fault, I forgot to rename template.
Will make followup PR asap to fix
