### PR TITLE
fixes #10216

### LINKED ISSUE #10216: {.push raises: [].} breaks when combined with certain symbols
`{.push raises: [].}` still cannot be reliably used on a whole module to enforce tracked exceptions.

### Examples
```nim
{.push raises: [].} # Error: cannot attach a custom pragma to 'e2'

type
  Enum = enum
    e1, e2

{.pop.}
```
```nim
{.push raises: [].} # Error: cannot attach a custom pragma to 'm'

macro m: typed =
  discard

{.pop.}
```

```nim
{.push raises: [].} # Error: invalid pragma: raises: []

type O {.final.} = object

{.pop.}
```

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

**Comment by nc-x** [comment]
https://github.com/nim-lang/Nim/blob/ceabbeadd7807dd21f274271acc779a7a8e69132/compiler/pragmas.nim#L1057-L1064
can also probably be changed back to
```nim
of wRaises, wTags: pragmaRaisesOrTags(c, it)
```

**Comment by Araq** [comment]
@nc-x: I don't think so.

**Comment by Araq** [comment]
Irrelevant CI failure.

File: compiler/pragmas.nim [hunk 1]
```diff
@@ -64,10 +64,10 @@ const
   varPragmas* = {wImportc, wExportc, wVolatile, wRegister, wThreadVar, wNodecl,
     wMagic, wHeader, wDeprecated, wCompilerProc, wCore, wDynlib, wExtern,
     wImportCpp, wImportObjC, wError, wNoInit, wCompileTime, wGlobal,
-    wGensym, wInject, wCodegenDecl, wGuard, wGoto, wExportNims, wUsed, wRaises}
+    wGensym, wInject, wCodegenDecl, wGuard, wGoto, wExportNims, wUsed}
```
Comment (nc-x) [inline compiler/pragmas.nim]: @Araq since wRaises is no longer valid for vars/lets/consts, the code will never reach https://github.com/nim-lang/Nim/blob/ceabbeadd7807dd21f274271acc779a7a8e69132/compiler/pragmas.nim#L1057-L1064
instead it will go to your new branch `elif comesFromPush and whichKeyword(ident) in {wTags, wRaises}:`, so yes, the code can be changed back.

Comment (nc-x) [reply compiler/pragmas.nim]: Created PR https://github.com/nim-lang/Nim/pull/10278
