### PR TITLE
fixes #21138; closure `func` used in the loop

### LINKED ISSUE #21138: `Error: unhandled exception: field 'sym' is not accessible for type 'TNode'`
### Description

```nim
iterator p(): int =
  when nimvm:
    yield 0
  else:
    yield 0

block:
  for k in p():
    func e() {.closure.} = discard

static:
  for k in p():
    func e() {.closure.} = discard
```

### Nim Version

```
Nim Compiler Version 1.9.1 [Linux: amd64]
Compiled at 2022-12-19
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: e278a781fc5bfc115326ed6c1873268d51b25303
active boot switches: -d:release
```

```
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-23
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

Not fixed by https://github.com/nim-lang/Nim/pull/21136 

### Current Output

```text
`Error: unhandled exception: field 'sym' is not accessible for type 'TNode' using 'kind = 155' [FieldDefect]`
```

### Expected Output

```text
Not a Nim compiler `Defect`
```

### Possible Solution

_No response_

### Additional Information

Inspired by https://github.com/nim-lang/Nim/pull/21136 -- though, a bit separate, potentially. It does seem related insofar as using `proc` here doesn't have this issue with 21136 applied, and it might be reasonable for that PR to address this as well.

### PR DESCRIPTION
**Pull request by ringabout**
fixes #21138

### CODE REVIEW

File: compiler/transf.nim [hunk 1]
```diff
@@ -329,7 +329,7 @@ proc introduceNewLocalVars(c: PTransf, n: PNode): PNode =
     if a.kind == nkSym:
       n[1] = transformSymAux(c, a)
     return n
-  of nkProcDef: # todo optimize nosideeffects?
+  of nkProcDef, nkFuncDef: # todo optimize nosideeffects?
```
Comment (Araq) [inline compiler/transf.nim]: Converters? Methods?

Comment (ringabout) [reply compiler/transf.nim]: They can not be used in a local scope in a for loop

e.g.
> 'converter' is only allowed at top level

Comment (Araq) [reply compiler/transf.nim]: Good point. Maybe add them anyway? Maybe we'll allow them to be local one day.

Comment (ringabout) [reply compiler/transf.nim]: okay
