### PR TITLE
Fix sequtils.delete bug with out of bounds indexes

### LINKED ISSUE #12388: sequtils.delete and system.delete inconsistencies when index out of bounds
The delete proc for seqs is defined in [system ](https://nim-lang.github.io/Nim/system.html#delete%2Cseq%5BT%5D%5BT%5D%2CNatural) and [sequtils](https://nim-lang.github.io/Nim/sequtils.html#delete%2Cseq%5BT%5D%5BT%5D%2CNatural%2CNatural).

The difference is that the definition from system takes 1 parameter for the index to delete whereas the definition from sequtils takes 2 parameters which represent the range of indices to delete (inclusive)

Since the range is inclusive, you would expect both results below to be the same

### Example

```nim
import sequtils

var ones: seq[string] 

echo "-- delete at index 50 ---"

ones = @["one"]
ones.delete(50)           # unexpected: shouldn't delete anything since index 50 is out of bounds
echo repr ones

ones = @["one"]
ones.delete(50,50)        # unexpected: should be the same thing as delete(50)
echo repr ones
```

### Current Output
```
-- delete at index 50 ---
@[]
@["one", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
```

### Expected Output

```
@["one"]
@["one"]
```

### Suggestions
Make deleting an out of bounds index return the same exact array, unmodified. (Or possibly throw an error)
Possibly make the proc return a bool if the array was modified using the [discardable pragma](https://nim-lang.github.io/Nim/tut1.html#procedures-discard-statement) so that its ignored by default

The documentation should say what happens for edge cases like when a parameter is out of bounds for the seq

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.2
```

### PR DESCRIPTION
**Pull request by GULPF**
The proc already handled the case where `last` is out of bounds, so this is imo just a bugfix.

Fixes #12388

### CODE REVIEW

File: lib/pure/collections/sequtils.nim [hunk 1]
```diff
@@ -434,7 +434,9 @@ proc delete*[T](s: var seq[T]; first, last: Natural) =
     var dest = @[1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1]
     dest.delete(3, 8)
     assert outcome == dest
-
+  doAssert first <= last
```
Comment (GULPF) [inline lib/pure/collections/sequtils.nim]: Previously sending `first > last` resulted in a `IndexError`, which doesn't tell the user much about what went wrong. If sending `first > last` is supposed to work I can fix it instead.

Comment (cooldome) [reply lib/pure/collections/sequtils.nim]: IMO, first greater than last should silently delete nothing. This how you define empty sequence with inclusive ranges.

Comment (cooldome) [reply lib/pure/collections/sequtils.nim]: And first >= len should be IndexError

Comment (GULPF) [reply lib/pure/collections/sequtils.nim]: > And first >= len should be IndexError

I actually agree, but it would be inconsistent with how the `last` parameter is handled (out of bounds allowed) and how `system.delete` behaves. If `first >= len` results in IndexError then `last >= len` should also result in IndexError, which would be a breaking change.

Comment (Araq) [reply lib/pure/collections/sequtils.nim]: There is some Python influence here too, ``"oobasfd"[:10000] == 'oobasfd'``, Python is usually silent about index out of bounds for slices.

**Comment by narimiran** [comment]
The code example in https://github.com/nim-lang/Nim/issues/12388 shows that also `system.delete` has a bug where it wrongly deletes the last element of the seq if you pass an index which is out of bounds.

Can you also patch that one?

----

Btw, `system.del` has another behaviour — it throws `IndexError`.
Shouldn't all three (`sequtils.delete`, `system.delete`, `system.del`) be consistent with each other when an out of bounds index is passed?

**Comment by Araq** [comment]
This improves the situation so I'm merging this now and later on we can make these APIs more consistent with each other.
