### PR TITLE
fix #15148

### LINKED ISSUE #15148: Writing an empty string to an AsyncFile raises an IndexDefect
Attempting to write an empty string to an AsyncFile raises an IndexDefect.

### Example
```nim
import asyncdispatch, asyncfile

proc saveEmpty() {.async.} =
  let
    text = ""
    file = open_async("test.txt", fmWrite)
  await file.write(text)
  file.close()

waitFor saveEmpty()
```

### Current Output
**Note:** I replaced my username with the word "USER" and the path to the nim source file with the word "PATH" for privacy reasons.
```
Hint: used config file '/home/USER/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/home/USER/.choosenim/toolchains/nim-#devel/config/config.nims' [Conf]
Hint: used config file '/home/USER/.config/nim/nim.cfg' [Conf]
...................................
Hint:  [Link]
Hint: 62816 lines; 0.775s; 93.91MiB peakmem; Debug build; proj: /home/USER/PATH/main.nim; out: /home/USER/PATH/main [SuccessX]
Hint: /home/USER/PATH/main  [Exec]
/home/USER/PATH/main.nim(10) main
/home/USER/.choosenim/toolchains/nim-#devel/lib/pure/asyncmacro.nim(248) saveEmpty
/home/USER/.choosenim/toolchains/nim-#devel/lib/pure/asyncmacro.nim(23) saveEmptyNimAsyncContinue
/home/USER/PATH/main.nim(7) saveEmptyIter
/home/USER/.choosenim/toolchains/nim-#devel/lib/pure/asyncfile.nim(473) write
/home/USER/.choosenim/toolchains/nim-#devel/lib/pure/asyncfile.nim(458) cb
/home/USER/.choosenim/toolchains/nim-#devel/lib/system/fatal.nim(49) sysFatal
[[reraised from:
/home/USER/PATH/main.nim(10) main
/home/USER/.choosenim/toolchains/nim-#devel/lib/pure/asyncdispatch.nim(1934) waitFor
/home/USER/.choosenim/toolchains/nim-#devel/lib/pure/asyncfutures.nim(383) read
]]
Error: unhandled exception: index out of bounds, the container is empty
Async traceback:
  /home/USER/PATH/main.nim(10)               main
  /home/USER/.choosenim/toolchains/nim-#devel/lib/pure/asyncmacro.nim(248) saveEmpty
  /home/USER/.choosenim/toolchains/nim-#devel/lib/pure/asyncmacro.nim(23)  saveEmptyNimAsyncContinue
  /home/USER/PATH/main.nim(7)                saveEmptyIter
  /home/USER/.choosenim/toolchains/nim-#devel/lib/pure/asyncfile.nim(473)  write
  /home/USER/.choosenim/toolchains/nim-#devel/lib/pure/asyncfile.nim(458)  cb
  /home/USER/.choosenim/toolchains/nim-#devel/lib/system/fatal.nim(49)     sysFatal
Exception message: index out of bounds, the container is empty
Exception type: [IndexDefect]
Error: execution of an external program failed: '/home/USER/PATH/main '
```

### Expected Output
The empty string is correctly written to the given file and no exception is raised.

### Nim Version
```bash
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-08-02
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```
**Commit:** https://github.com/nim-lang/Nim/commit/d6161e7e9ea1f40ad734c6e811e8169fe24b5e9f
**Operating System:** Linux

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

File: lib/pure/asyncfile.nim [hunk 1]
```diff
@@ -454,8 +454,15 @@ proc write*(f: AsyncFile, data: string): Future[void] =
...
       result = true
+
       let remainderSize = data.len-written
-      let res = write(fd.cint, addr copy[written], remainderSize.cint)
+
+      let res =
+        if data.len == 0:
+          0
+        else:
+          write(fd.cint, addr copy[written], remainderSize.cint)
```
Comment (alaviss) [inline lib/pure/asyncfile.nim]: Please don't change this path. POSIX does permit actions to be taken by the operating system even when `0` is the length.

Comment (ringabout) [reply lib/pure/asyncfile.nim]: I will change to:
```nim
if data.len == 0:
  write(fd.cint, copy.cstring, 0)
```

File: tests/async/t15148.nim [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import asyncdispatch, asyncfile, os
+
+const filename = "t15148.txt"
```
Comment (alaviss) [inline tests/async/t15148.nim]:
```suggestion
const Filename = "t15148.txt"
```

File: tests/async/t15148.nim [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+proc saveEmpty() {.async.} =
+  let
+    text = ""
+    file = open_async(filename, fmWrite)
+  await file.write(text)
+  file.close()
+
+waitFor saveEmpty()
+
+doAssert fileExists(filename)
```
Comment (alaviss) [inline tests/async/t15148.nim]:
```suggestion
```

Not needed. The bug concerns about whether `write()` with empty string works, not whether `openAsync` creates a file.

File: tests/async/t15148.nim [hunk 4]
```diff
@@ -0,0 +1,14 @@
+import asyncdispatch, asyncfile, os
+
+const filename = "t15148.txt"
+
+proc saveEmpty() {.async.} =
+  let
+    text = ""
+    file = open_async(filename, fmWrite)
```
Comment (alaviss) [inline tests/async/t15148.nim]:
```suggestion
    file = openAsync(filename, fmWrite)
```

It's written as `openAsync` in the API.

File: lib/pure/asyncfile.nim [hunk 5]
```diff
@@ -454,8 +454,15 @@ proc write*(f: AsyncFile, data: string): Future[void] =
...
     proc cb(fd: AsyncFD): bool =
       result = true
-      let remainderSize = data.len-written
-      let res = write(fd.cint, addr copy[written], remainderSize.cint)
+
+      let remainderSize = data.len - written
+
+      let res =
+        if data.len == 0:
+          write(fd.cint, copy.cstring, 0)
```
Comment (Araq) [inline lib/pure/asyncfile.nim:462]: what is a write of size zero supposed to do?

Comment (ringabout) [reply lib/pure/asyncfile.nim:462]: When the written string is empty, create a new file and write nothing. Before it will crash because empty string can't be indexed.

```nim
addr copy[written]
```

Comment (Araq) [reply lib/pure/asyncfile.nim:462]: Sure but why not omit the ``write`` call then?

Comment (alaviss) [reply lib/pure/asyncfile.nim:462]: Because POSIX in all of their wisdom allows `write()` with size `0` to perform actions such as error checking.
