### PR TITLE
fix #15958

### LINKED ISSUE #15958: `lent` codegen error for c++ (works with c,js,vm)
`lent` codegen error for c++ (works with c,js,vm)
### Example
```nim
when true: # D20201113T132829
  proc byLent[T](a: T): lent T = a
  let a = [11,12]
  doAssert byLent(a) == [11,12] # error: no matching function for call 
```

### Current Output
```
@mt11278.nim.cpp:160:48: error: no matching function for call to 'byLent__YR8W5QF853QkzHxY0HJTiA'
                NIM_BOOL T3_ = eqeq___kPWPhCv4sxSS5oUvoHpOvQ(byLent__YR8W5QF853QkzHxY0HJTiA(a__9aK0EFj6IzQ9aQ33j9bVJ0VvA), TM__tQ8kc6yAWJgOgIMsVcTMMQ_2);
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/timothee/git_clone/nim/timn/build/nimcache/@mt11278.nim.cpp:107:30: note: candidate function not viable: no known conversion from 'tyArray__HU7qaqKu9czJLT84iCBJnsA' (aka 'NI [2]') to 'tyArray__HU7qaqKu9czJLT84iCBJnsA *'
      (aka 'NI (*)[2]') for 1st argument; take the address of the argument with &
N_LIB_PRIVATE N_NIMCALL(NI*, byLent__YR8W5QF853QkzHxY0HJTiA)(tyArray__HU7qaqKu9czJLT84iCBJnsA* a) {
                             ^
/Users/timothee/git_clone/nim/Nim_devel/lib/nimbase.h:252:44: note: expanded from macro 'N_NIMCALL'
#  define N_NIMCALL(rettype, name) rettype name /* no modifier */

```

### Expected Output
works

### Additional Information
* devel 1.5.1 c39fa0d49535da7f803d9972abdb15d09eed92a6
* works with c, js, vm

eg:
```nim
when true:
  template main=
    proc byLent[T](a: T): lent T = a
    let a = [11,12]
    doAssert byLent(a) == [11,12]
  static: main() # ok
  main() # bug
```
* works with tuple instead of array:
```nim
when true:
  proc byLent[T](a: T): lent T = a
  let a2 = (11,)
  doAssert byLent(a2) == (11,)
```

* added disabled test case in https://github.com/nim-lang/Nim/pull/15960

### PR DESCRIPTION
**Pull request by cooldome**
fix #15958

### CODE REVIEW

File: compiler/ccgtypes.nim [hunk 1]
```diff
@@ -282,7 +282,7 @@ proc ccgIntroducedPtr(conf: ConfigRef; s: PSym, retType: PType): bool =
     result = false
   # first parameter and return type is 'lent T'? --> use pass by pointer
   if s.position == 0 and retType != nil and retType.kind == tyLent:
-    result = pt.kind != tyVar
+    result = pt.kind notin {tyVar, tyArray}
```
Comment (Araq) [inline compiler/ccgtypes.nim]: But C arrays are pointers already, why would the C code generator introduce another indirection in this case?

Comment (cooldome) [reply compiler/ccgtypes.nim]: This fix actually removes double pointer

Comment (Araq) [reply compiler/ccgtypes.nim]: But then what about ``tyOpenArray, tyVarargs`` (and maybe ``tySequence``)?

Comment (cooldome) [reply compiler/ccgtypes.nim]: Yes, you are right tyOpenArray, tyVarargs also need this fix. Seq is fine.
Added tests to cover tyOpenArray, tyVarargs to PR

File: tests/lent/tbasic_lent_check.nim [hunk 2]
```diff
@@ -1,4 +1,5 @@
 discard """
+  targets: "c cpp"
```
Comment (timotheecour) [inline tests/lent/tbasic_lent_check.nim:2]: js?

File: tests/lent/tbasic_lent_check.nim [hunk 3]
```diff
@@ -14,3 +15,31 @@ proc main =
...
+  doAssert byLent2(b) == 21
+  doAssert byLent2(b).unsafeAddr == b[0].unsafeAddr
+
+
+  proc byLent3[T](a: varargs[T]): lent T = a[1]
+  let 
+    x = 10
+    y = 20
+    z = 30
+  doAssert byLent3(x, y, z) == 20
```
Comment (timotheecour) [inline tests/lent/tbasic_lent_check.nim:54]: also check VM by wrapping everything inside a
```nim
template main =
  ...
static: main()
main()
```

File: tests/lent/tbasic_lent_check.nim [hunk 4]
```diff
@@ -14,3 +15,31 @@ proc main =
   doAssert(not compiles(passToVar(viewInto(x))))
 
 main()
+
```
Comment (timotheecour) [inline tests/lent/tbasic_lent_check.nim:18]: also un-disable the disabled test case introduced in https://github.com/nim-lang/Nim/pull/15960

File: tests/lent/tbasic_lent_check.nim (hunk 3 above)
Comment (cooldome) [reply tests/lent/tbasic_lent_check.nim:54]: I am not fixing VM or JS in this PR

File: tests/lent/tbasic_lent_check.nim (hunk 4 above)
Comment (cooldome) [reply tests/lent/tbasic_lent_check.nim:18]: I am not fixing VM or JS in this PR

File: tests/lent/tbasic_lent_check.nim (hunk 2 above)
Comment (cooldome) [reply tests/lent/tbasic_lent_check.nim:2]: I am not fixing VM or JS in this PR

File: tests/lent/tbasic_lent_check.nim (hunk 4 above)
Comment (timotheecour) [reply tests/lent/tbasic_lent_check.nim:18]: this one: see https://github.com/nim-lang/Nim/pull/15960/files
```nim
  block:
    when not defined(cpp): # pending bug #15958
      let a = [11,12]
      doAssert byLent(a) == [11,12]
    let a2 = (11,)
    doAssert byLent(a2) == (11,)
```

File: tests/lent/tbasic_lent_check.nim (hunk 2 above)
Comment (timotheecour) [reply tests/lent/tbasic_lent_check.nim:2]: yes but js and already work, so it would make sense to increase test coverage by including those as regression tests. Either way, I can do a followup PR add those.

File: tests/lent/tbasic_lent_check.nim (hunk 3 above)
Comment (timotheecour) [reply tests/lent/tbasic_lent_check.nim:54]: => https://github.com/nim-lang/Nim/pull/15970#discussion_r524396526

File: compiler/ccgtypes.nim (hunk 1 above)
Comment (Araq) [reply compiler/ccgtypes.nim]: Also, big sets are mapped to C arrays... :-)

Comment (cooldome) [reply compiler/ccgtypes.nim]: Yes, they are and they need the fix. Added big sets as well :)

**Comment by cooldome** [comment]
ready for review

File: tests/lent/tbasic_lent_check.nim (hunk 4 above)
Comment (timotheecour) [reply tests/lent/tbasic_lent_check.nim:18]: => fixing this in https://github.com/nim-lang/Nim/pull/16075

File: tests/lent/tbasic_lent_check.nim (hunk 2 above)
Comment (timotheecour) [reply tests/lent/tbasic_lent_check.nim:2]: => fixing this in https://github.com/nim-lang/Nim/pull/16075
