### PR TITLE
fix #16206

### LINKED ISSUE #16206: Error parsing INI section names with spaces
I was trying out the [example program from the documentation](https://nim-lang.org/docs/parsecfg.html) for parsing INI files. If the section name contains spaces, it would parse the INI file incorrectly.

### Example INI file
```INI
[SectionA]
[Section B]
```

### Current Output
```
new Section: SectionA
test.ini(2, 10) Error: ']' expected, but found: B
key-value-pair: B:
test.ini(2, 11) Error: invalid token: ]
```

### Expected Output
```
newSection: SectionA
newSection: Section B
```

### Possible Solution

* The documentation states, that the configuration syntax is similar to Windows Ini, so maybe this is the expected output?

### Additional Information

```
$ nim -v
Nim Compiler Version 1.4.2
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #16206

After this PR, the codes below work:
https://gist.github.com/xflywind/e3551e662a085a981e001e8b2c0dd681

### CODE REVIEW

File: lib/pure/parsecfg.nim [hunk 1]
```diff
@@ -306,6 +306,7 @@ proc getSymbol(c: var CfgParser, tok: var Token) =
     add(tok.literal, c.buf[pos])
     inc(pos)
     if not (c.buf[pos] in SymChars): break
+  tok.literal = tok.literal.strip
```
Comment (timotheecour) [inline lib/pure/parsecfg.nim]: no strong opinion here; is that so that
`[  No Values  ]` behaves as `[No Values]` ?

Comment (ringabout) [reply lib/pure/parsecfg.nim]: `key` and `value` will ignore space around in Python, I don't know whether `section` should.
https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

Comment (timotheecour) [reply lib/pure/parsecfg.nim]: according to https://en.wikipedia.org/wiki/INI_file it varies:

> Interpretation of whitespace varies. Most implementations ignore leading and trailing whitespace around the outside of the property name. Some even ignore whitespace within values (for example, making "host name" and "hostname" equivalent). Some implementations also ignore leading and trailing whitespace around the property value; others consider all characters following the equals sign (including whitespace) to be part of the value.

then, how about:
```nim
type IniOptions* = enum iniKeepWhitespace # etc
proc initCfgParser*(options: set[IniOptions] = {}): CfgParser = ...
```

can be done in future work though

**Comment by ringabout** [comment]
Before this PR, section name, key and value can't contain space  and spaces around word are ignored
`nim world` is wrong. `nim_world` and ` nim_world  ` are the same.
After this PR, they could contain space and spaces around word are ignored
`nim world`, `   nim  world  ` are the same.

File: lib/pure/parsecfg.nim (hunk 1 above)
Comment (narimiran) [reply lib/pure/parsecfg.nim]: @xflywind before implementing this, please wait until somebody else agrees on the proposed solution. 

(There are some of us that don't think that having lots of possibilities/options is always a good idea)

Comment (ringabout) [reply lib/pure/parsecfg.nim]: The same behaviour as before

```nim
import parsecfg, streams
var dict = loadConfig(newStringStream("""[ Simple_Values ]
    key  =  value  """))

echo dict
```

[Simple_Values]
key=value

Comment (ringabout) [reply lib/pure/parsecfg.nim]: @narimiran 
Yeah, I won't implement that. I just keep the same behaviour as before.

Feature PR will be postponed at next PR, this PR is intended to fix the issue.

File: lib/pure/parsecfg.nim [hunk 2]
```diff
@@ -107,6 +107,70 @@
...
+## Supported INI File structure
+## ----------------------------
+## The examples below are supported:
+##
+
+# taken from https://docs.python.org/3/library/configparser.html#supported-ini-file-structure
+runnableExamples:
+  import streams
+
+  var dict = loadConfig(newStringStream("""[Simple Values]
```
Comment (timotheecour) [inline lib/pure/parsecfg.nim:120]: nit (can be done after PR): newline after `"""` is more readable (and equivalent; it's a feature of triple string literals)

ditto in other file in this PR

File: tests/stdlib/tparsecfg.nim [hunk 3]
```diff
@@ -78,3 +77,59 @@ name=hello
 name=lihf8515
 qq=10214028
 """
+
+block:
```
Comment (timotheecour) [inline tests/stdlib/tparsecfg.nim:81]: in future PR: add this diff:
```
diff --git a/tests/stdlib/tparsecfg.nim b/tests/stdlib/tparsecfg.nim
index bbf88ee03..dc1070f34 100644
--- a/tests/stdlib/tparsecfg.nim
+++ b/tests/stdlib/tparsecfg.nim
@@ -84,6 +84,7 @@ block:
   spaces in keys=allowed
   spaces in values=allowed as well
   spaces around the delimiter = obviously
+  quoted string = " spaces part of key  "
   you can also use : to delimit keys from values
   [All Values Are Strings]
   values like this: 19990429
@@ -99,6 +100,8 @@ block:
   [You can use comments]
   # like this
   ; or this
+  comment after line start = stops here # inside comment
+  comment after line start 2 = stops here 2 ; inside comment ; still inside comment
   # By default only in an empty line.
   # Inline comments can be harmful because they prevent users
   # from using the delimiting characters as parts of values.
@@ -116,6 +119,7 @@ block:
   doAssert dict.getSectionValue(section1, "spaces in keys") == "allowed"
   doAssert dict.getSectionValue(section1, "spaces in values") == "allowed as well"
   doAssert dict.getSectionValue(section1, "spaces around the delimiter") == "obviously"
+  doAssert dict.getSectionValue(section1, "quoted string") == " spaces part of key  "
   doAssert dict.getSectionValue(section1, "you can also use") == "to delimit keys from values"

   let section2 = "All Values Are Strings"
@@ -129,6 +133,10 @@ block:
   doAssert dict.getSectionValue(section3,
     "space around section name will be ignored", "not an empty value") == ""

+  let sectionComments = "You can use comments"
+  doAssert dict.getSectionValue(sectionComments, "comment after line start") == "stops here"
+  doAssert dict.getSectionValue(sectionComments, "comment after line start 2") == "stops here 2"
+
   let section4 = "Sections Can Be Indented"
   doAssert dict.getSectionValue(section4, "can_values_be_as_well") == "True"
   doAssert dict.getSectionValue(section4, "does_that_mean_anything_special") == "False"
```

**Review by timotheecour — APPROVED** [review]

File: lib/pure/parsecfg.nim [hunk 4]
```diff
@@ -306,6 +370,7 @@ proc getSymbol(c: var CfgParser, tok: var Token) =
     add(tok.literal, c.buf[pos])
     inc(pos)
     if not (c.buf[pos] in SymChars): break
+  tok.literal = tok.literal.strip
```
Comment (Araq) [inline lib/pure/parsecfg.nim]: I'd rather fix the lexer so that it doesn't producing leading/trailing whitespace. ``.strip`` feels a bit hacky.

Comment (xflywind) [reply lib/pure/parsecfg.nim:373]: how about strip it in `parseSymbol`?

Comment (ringabout) [reply lib/pure/parsecfg.nim]: Now it only strips trailing whitespace.
Leading space is skipped by `skip` function already.

I don't where I should fix. Any hints?

Comment (ringabout) [reply lib/pure/parsecfg.nim]: the trailing space comes from:
```nim
[section name   ]
foo   :text
time spent  = hello
```
- The space before special char such as `:`, `=`, `]` and so on
- The space before `newLine`.

File: lib/pure/parsecfg.nim [hunk 5]
```diff
@@ -370,7 +370,10 @@ proc getSymbol(c: var CfgParser, tok: var Token) =
     add(tok.literal, c.buf[pos])
     inc(pos)
     if not (c.buf[pos] in SymChars): break
-  tok.literal = tok.literal.strip
+
+  while tok.literal.len > 0 and tok.literal[^1] == ' ':
+    tok.literal.setLen(tok.literal.len - 1)
```
Comment (timotheecour) [inline lib/pure/parsecfg.nim:375]: doesn't handle things like `\t`
This should be instead:
```nim
tok.literal = tok.literal.strip(leading = false)
```
if that's your intention to only strip trailing whitespace

Comment (ringabout) [reply lib/pure/parsecfg.nim:375]: `\t` is already handled by `parseSymbol`, because `\t` isn't in `SymbolChars`.

Comment (timotheecour) [reply lib/pure/parsecfg.nim:375]: ok. But other point remains, `tok.literal = tok.literal.strip(leading = false)` is more readable, no? 

On this note, we need an inplace `strip(...)` variant in strutils, refs https://github.com/timotheecour/Nim/issues/422 (although in this particular case,  I doubt efficiency would make a difference). (EDIT:s/stripRight/strip/ since even strip can be made inplace)

Comment (ringabout) [reply lib/pure/parsecfg.nim:375]: AFAIR, `strip` inplace is used in some places in compiler, I hope it could be added to `strutils`.
You could search `== ' '` or similar to find them.

**Comment by Araq** [comment]
Still not how I would have done it but ok.
