### PR TITLE
fix term rewriting with sideeffect

### LINKED ISSUE #6217: noSideEffect pragma problem
I took the code from the manual.
https://nim-lang.org/docs/manual.html#term-rewriting-macros
```nim
template optMul{`*`(a, 2)}(a: int{noSideEffect}): int = a+a

proc f(): int =
  echo "side effect!"
  result = 55

echo f() * 2 # not optimized ;-)
```
When I run it, I get:
```
side effect!
side effect!
110
```
As I understand it, this should not be.

### PR DESCRIPTION
**Pull request by ringabout**
fix #6217; `tfNoSideEffect` seems to be inferred.

### CODE REVIEW

File: tests/template/template_various.nim [hunk 1]
```diff
@@ -145,9 +145,6 @@ block pattern_with_converter:
 
   doAssert floatDouble(5) == 10.0
```
Comment (ringabout) [inline tests/template/template_various.nim]:
```suggestion




```
