### PR TITLE
[backport] fixes #23711;  C code contains backtick`gensym 

### LINKED ISSUE #23711: [Semi-regression] C code contains backtick`gensym
As mentioned in Discord at https://discord.com/channels/371759389889003530/768367394547957761/1250440092208730152

Using the latest `version2-0` branch I have a regression compared to 2.0.4 that leads to backtick of gensym'ed symbols not being translated to X60 as usual due to https://github.com/nim-lang/Nim/pull/22944 being backported.

See CI run: https://github.com/mratsim/constantine/actions/runs/9471919674/job/26096274691?pr=393#step:23:47

image

It seems to also lead to conflicting types using same name variables
image

https://github.com/mratsim/constantine/actions/runs/9471919674/job/26096274691?pr=393#step:23:13

----

Reproducing

```
git clone https://github.com/mratsim/constantine
cd constantine
nim c --cc:clang --outdir:build -d:danger --hints:off --warnings:off --verbosity:0 --threads:on --noMain --app:lib --nimMainPrefix:ctt_init_ --nimcache:nimcache/X60 bindings/lib_constantine.nim
```

Note that gcc-14 has issues that might not be backported yet so it's easier to use Clang (https://github.com/nim-lang/Nim/pulls?q=is%3Apr+%22gcc+14%22+is%3Aclosed+ )

----

Similar bug

If it helps, in the past I used to have those issues in v2.0.4, but only in templates and only with `{.noInit.}` variables.

I found 2 workarounds:
1. functions see: https://github.com/mratsim/constantine/pull/338/files#diff-9d369fc072ba230397943805ef3e09f4726cef5166ed8774d71657ee0fe0a6c1L1442
    image
2. Using inject see: https://github.com/mratsim/constantine/pull/346/files#diff-9af16dfbdb13c0086d14ae9290dab7feba9d35fe1e14f3a4f8ca04455aef49b2L68
    image

 Unfortunately I tried to minimize the issue to a single file and failed at the time.

### PR DESCRIPTION
**Pull request by ringabout**
fixes #23711

### CODE REVIEW

File: compiler/semtypes.nim [hunk 1]
```diff
@@ -555,11 +555,15 @@ proc semIdentWithPragma(c: PContext, kind: TSymKind, n: PNode,
     else: discard
   else:
     result = semIdentVis(c, kind, n, allowed)
+    let invalidPragmasForPush = if fromTopLevel and "`gensym" notin result.name.s:
```
Comment (metagn) [inline compiler/semtypes.nim]: Could we maybe remove the check for `` `gensym `` here and mangle the output of `{.exportc.}` when no string is given to it instead? Because this errors too despite not being `skVar/skLet/skConst` (#20911):

```nim
{.push exportc.}

template foo =
  proc bar {.gensym.} = discard

foo()
```

Comment (Araq) [reply compiler/semtypes.nim]: Too hacky.

Comment (ringabout) [reply compiler/semtypes.nim]: > Too hacky.

How should we check `gensym`? There is not a flag dedicated for it since it is a newly created ident. 

```nim
if sfGenSym in s.flags:
  result.add newIdentNode(getIdent(c.ic, x.name.s & "`gensym" & $c.instID),
    if c.instLines: actual.info else: templ.info)
```

>  mangle the output of {.exportc.} when no string is given to it instead

I would like to revive https://github.com/nim-lang/Nim/pull/19636 with some adaptations

Comment (Araq) [reply compiler/semtypes.nim]: Introduce a new flag like `sfWasGenSym`.

Comment (ringabout) [reply compiler/semtypes.nim]: Okay, I will move `` `gensym`` check into `newSymG` and incl the flag there.

Comment (Araq) [reply compiler/semtypes.nim]: At least make the check cheaper by doing:

```nim

getIdent(c.ic, "`" & x.name.s & "`gensym" & $c.instID)
...

s.name.s[0] == '`'

```

Comment (ringabout) [reply compiler/semtypes.nim]: Well, if the name is changed, it is going to break https://github.com/iffy/nim-argparse/blob/4048a76b24919807b0871dd145ba93a48c2688e7/src/argparse/macrohelp.nim#L36 which splits gensym based on "`". Since we are fixing a regression, I will settle for a comprised solution: 

```nim
if find(result.name.s, '`') >= 0:
  result.flags.incl sfWasGenSym
```

**Comment by ringabout** [comment]
`dnsclient` in important packages seems to be quite unstable or broken
