### PR TITLE
Really fix StringStream with ARC at compile-time, improve streams test

### LINKED ISSUE #19716: StringStream in static context (arc) now broken after recent write fix
Recent fix meaning #19708

It now seemingly attempts to use prepareMutation in the VM (when using arc/orc)  which gives the error `Error: opcCastIntToPtr: regs[rb].kind: rkNodeAddr`,   from here https://github.com/nim-lang/Nim/blob/devel/lib/system/strs_v2.nim#L177

This code was valid before and is still valid when using refc.

### Example:
```nim
import streams
static:
  let s = newStringStream("a")
  echo s.data # only added for illustrative purposes, breaks before this point
```

### PR DESCRIPTION
**Pull request by ghost**
Now tstreams is actually tested with ARC.

I also fixed `readDataStr` branch that is executed when the `readDataStrImpl` is nil so that it works with ARC (it's covered by the tstreams test).

Also changed issue references in the test to the preferred convention.

Fixes https://github.com/nim-lang/Nim/issues/19716

### CODE REVIEW

File: lib/pure/streams.nim [hunk 1]
```diff
@@ -243,6 +243,9 @@ proc readDataStr*(s: Stream, buffer: var string, slice: Slice[int]): int =
     result = s.readDataStrImpl(s, buffer, slice)
   else:
     # fallback
+    when declared(prepareMutation):
```
Comment (ghost) [inline lib/pure/streams.nim:246]: I didn't add a nimvm check here because this code branch isn't supported by the VM anyway
