### PR TITLE
Fix for #4719.

### LINKED ISSUE #4719: cant create thread after join
The following hangs:

``` nim
proc p() {.thread.} = discard

var t: Thread[void]

createThread(t, p)
joinThread(t)
createThread(t, p)
joinThread(t)
```

Reset doesn't help:

``` nim
proc p() {.thread.} = discard

var t: Thread[void]

createThread(t, p)
joinThread(t)
reset(t)
createThread(t, p)
joinThread(t)
```

Simply using a different thread variable does work:

``` nim
proc p() {.thread.} = discard

var t: Thread[void]

createThread(t, p)
joinThread(t)

var u: Thread[void]
createThread(u, p)
joinThread(u)
```

But as the manual says, threads are heavy objects....

### PR DESCRIPTION
**Pull request by cheatfate**
Fix #4719.
Allow reuse of Thread[TArg] object.
Added 2 tests.

### CODE REVIEW

File: lib/system/threads.nim [hunk 1]
```diff
@@ -491,8 +491,6 @@ else:
     ## waits for every thread in `t` to finish.
     for i in 0..t.high: joinThread(t[i])
 
-when false:
-  # XXX a thread should really release its heap here somehow:
```
Comment (Araq) [inline lib/system/threads.nim]: Huh? You like to enable ``destroyThread``?

Comment (cheatfate) [inline lib/system/threads.nim]: Nope, thats mistake. To enable `destroyThread` we really need to release heap somehow.
