### PR TITLE
fix #14350, cstrings in JS init as null

### LINKED ISSUE #14350: [Regression] karax events are not firing
Regression caused by https://github.com/nim-lang/Nim/pull/14158

Test case
```nim
proc render(): VNode =
  result = buildHtml(tdiv(class="normalDiv")):
    label(`for`=comboID):
      text "default should be C"
      br()
      select(id=comboID):
        for p in ["A", "B", "C", "D"]:
          if p=="C":
            option(selected="true"): text p.kstring
          else:
            option: text p.kstring
```
Combobox should be in position `C` but after https://github.com/nim-lang/Nim/commit/707367e1ca231d964ba82a92b642eb5efdc1aa7c, it remains in position A.

### PR DESCRIPTION
**Pull request by metagn**
This fixes the wrongly introduced behaviour in #14158 which initialized cstrings as `""` instead of `null`. The previous PR got rid of `null` initialized strings/seqs, which I grouped cstrings with without thinking about it

I did locally test the code snippet in #14350 with Karax and it does indeed work as expected. I don't think it's plausible to add a test for that though.

### CODE REVIEW

File: tests/js/tcstrinit.nim [hunk 1]
```diff
@@ -0,0 +1,5 @@
+# #14350
```
Comment (timotheecour) [inline tests/js/tcstrinit.nim]: merge this inside existing `tests/system/tdollars.nim` which tests c,cpp,js

File: tests/js/tcstrinit.nim [hunk 2]
```diff
@@ -0,0 +1,5 @@
...
+var cstr: cstring
+doAssert cstr == cstring(nil)
```
Comment (timotheecour) [inline tests/js/tcstrinit.nim]: also add:
`doAssert cstr == nil` for completeness-sake

**Review by timotheecour — APPROVED** [review]
LGTM (I'm assuming `doAssert default(cstring) == nil` should pass and doesn't need a test)
