### PR TITLE
fixes #5444 - nre.findIter keeps searching when no match is possible

### LINKED ISSUE #5444: Nim hangs forever in infinite loop in nre library
Short code example that hangs Nim:-

```
import httpclient
import nre

var http = newHttpClient()
var data = http.getContent("http://downloads.tomsguide.com/MusicBee,0301-27475.html")

echo data.findall(re"url.*? = &#39;(.*?)&#39;")
```

On pressing CTRL-C, following stack is printed:-

```
Traceback (most recent call last)
http.nim(7)              http
nre.nim(521)             findAll
nre.nim(452)             matchImpl
SIGINT: Interrupted by Ctrl-C.
SIGINT: Interrupted by Ctrl-C.
```

Replace URL with google.com and it works fine, try cnn.com, it hangs again. Not sure what about the content is confusing Nim or PCRE.

### PR DESCRIPTION
**Pull request by napalu**
nre.findIter keeps on searching when it's never matched until it reaches the end of the input. The function keeps incrementing the offset by one and searches again until len of input is reached. The function should bail early when never matched instead of searching for the next match boundary.

### CODE REVIEW

File: lib/impure/nre.nim [hunk 1]
```diff
@@ -516,23 +516,24 @@ iterator findIter*(str: string, pattern: Regex, start = 0, endpos = int.high): R
...
+
   while true:
     var flags = 0
-
     if match.isSome and
        match.get.matchBounds.a > match.get.matchBounds.b:
       # 0-len match
       flags = pcre.NOTEMPTY_ATSTART
-
+
```
Comment (Araq) [inline lib/impure/nre.nim]: remove the trailing whitespace please.

Comment (napalu) [inline lib/impure/nre.nim]: Done.

File: lib/impure/nre.nim [hunk 2]
```diff
@@ -516,23 +516,23 @@ iterator findIter*(str: string, pattern: Regex, start = 0, endpos = int.high): R
...
     var flags = 0
-
     if match.isSome and
        match.get.matchBounds.a > match.get.matchBounds.b:
       # 0-len match
       flags = pcre.NOTEMPTY_ATSTART
-
     match = str.matchImpl(pattern, offset, endpos, flags)
-
+
```
Comment (Araq) [inline lib/impure/nre.nim]: Still whitespace here.

Comment (napalu) [inline lib/impure/nre.nim]: Hi Araq

I tried to follow the whitespace use of the original version which is:
```nim
iterator findIter*(str: string, pattern: Regex, start = 0, endpos = int.high): RegexMatch =
  ## Works the same as ```find(...)`` <#proc-find>`_, but finds every
  ## non-overlapping match. ``"2222".find(re"22")`` is ``"22", "22"``, not
  ## ``"22", "22", "22"``.
  ##
  ## Arguments are the same as ```find(...)`` <#proc-find>`_
  ##
  ## Variants:
  ##
  ## -  ``proc findAll(...)`` returns a ``seq[string]``
  # see pcredemo for explanation
  let matchesCrLf = pattern.matchesCrLf()
  let unicode = uint32(getinfo[culong](pattern, pcre.INFO_OPTIONS) and
    pcre.UTF8) > 0u32
  let strlen = if endpos == int.high: str.len else: endpos+1

  var offset = start
  var match: Option[RegexMatch]
  while true:
    var flags = 0

    if match.isSome and
       match.get.matchBounds.a > match.get.matchBounds.b:
      # 0-len match
      flags = pcre.NOTEMPTY_ATSTART

    match = str.matchImpl(pattern, offset, endpos, flags)

    if match.isNone:
      # either the end of the input or the string
      # cannot be split here
      if offset >= strlen:
        break

      if matchesCrLf and offset < (str.len - 1) and
         str[offset] == '\r' and str[offset + 1] == '\L':
        # if PCRE treats CrLf as newline, skip both at the same time
        offset += 2
      elif unicode:
        # XXX what about invalid unicode?
        offset += str.runeLenAt(offset)
        assert(offset <= strlen)
      else:
        offset += 1
    else:
      offset = match.get.matchBounds.b + 1

      yield match.get


proc find*(str: string, pattern: Regex, start = 0, endpos = int.high): Option[RegexMatch] =
```
What would be the desired whitespace? Something like:

```nim
iterator findIter*(str: string, pattern: Regex, start = 0, endpos = int.high): RegexMatch =
  ## Works the same as ```find(...)`` <#proc-find>`_, but finds every
  ## non-overlapping match. ``"2222".find(re"22")`` is ``"22", "22"``, not
  ## ``"22", "22", "22"``.
  ##
  ## Arguments are the same as ```find(...)`` <#proc-find>`_
  ##
  ## Variants:
  ##
  ## -  ``proc findAll(...)`` returns a ``seq[string]``
  # see pcredemo for explanation
  let matchesCrLf = pattern.matchesCrLf()
  let unicode = uint32(getinfo[culong](pattern, pcre.INFO_OPTIONS) and
    pcre.UTF8) > 0u32
  let strlen = if endpos == int.high: str.len else: endpos+1
  var offset = start
  var match: Option[RegexMatch]
  var neverMatched = true

  while true:
    var flags = 0
    if match.isSome and
       match.get.matchBounds.a > match.get.matchBounds.b:
      # 0-len match
      flags = pcre.NOTEMPTY_ATSTART
    match = str.matchImpl(pattern, offset, endpos, flags)
    if match.isNone:
      # either the end of the input or the string
      # cannot be split here - we also need to bail
      # if we've never matched and we've already tried to...
      if offset >= strlen or neverMatched:
        break
      if matchesCrLf and offset < (str.len - 1) and
         str[offset] == '\r' and str[offset + 1] == '\L':
        # if PCRE treats CrLf as newline, skip both at the same time
        offset += 2
      elif unicode:
        # XXX what about invalid unicode?
        offset += str.runeLenAt(offset)
        assert(offset <= strlen)
      else:
        offset += 1
    else:
      neverMatched = false
      offset = match.get.matchBounds.b + 1
      yield match.get

proc find*(str: string, pattern: Regex, start = 0, endpos = int.high): Option[RegexMatch] =
```

Comment (Araq) [inline lib/impure/nre.nim]: I don't understand your question. Files shouldn't have trailing whitespace and as far as I can tell the original has none, you introduced it and 'git diff' tells us this. I've marked the line where the whitespace was introduced.

**Comment by Araq** [comment]
Also this need to be covered by a test case.

File: lib/impure/nre.nim (hunk 2 above)
Comment (napalu) [inline lib/impure/nre.nim]: Hmm I get what you mean - you mean trailing white space after a new line right? I've just noticed - I've been goign back and forth working between linux and mac depending on where I am and just seen that VSCode on mac os seems to be inserting trailing spaces. Shouldn't because I've got it set up same as on linux. I'll recheck the settings and recommit.
