### PR TITLE
fix #13132 tnetdial flaky test

### LINKED ISSUE #13132: [CI] tnetdial flaky test
tnetdial is a flaky test

### Example
seen in https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/1743/logs/67
https://dev.azure.com/nim-lang/Nim/_build/results?buildId=1743&view=logs&jobId=a2a5264e-d0bc-5457-c91f-790ef943da8d&j=a2a5264e-d0bc-5457-c91f-790ef943da8d&t=11f6ff42-da87-5aa4-32c0-8d3b40d555ad
in unrelated PR https://github.com/nim-lang/Nim/pull/11824

### Current Output
```
2020-01-13T18:47:22.5700990Z [32mPASS: [36mtests/stdlib/tnetbind.nim C++                               [34m ( 1.29746890 secs)[0m
2020-01-13T18:47:22.5701590Z [1m[31mFAIL: [36mtests/stdlib/tnetdial.nim C++[0m
2020-01-13T18:47:22.5702230Z [1m[36mTest "tests/stdlib/tnetdial.nim" in category "stdlib"[0m
2020-01-13T18:47:22.5702640Z [1m[31mFailure: reExitcodesDiffer[0m
2020-01-13T18:47:22.5703140Z [33mExpected:[0m
2020-01-13T18:47:22.5703510Z [1mexitcode: 0
2020-01-13T18:47:22.5703880Z [0m
2020-01-13T18:47:22.5704260Z [33mGotten:[0m
2020-01-13T18:47:22.5704630Z [1mexitcode: 1
2020-01-13T18:47:22.5704690Z 
2020-01-13T18:47:22.5704750Z Output:
2020-01-13T18:47:22.5704820Z tnetdial.nim(34)         testThread
2020-01-13T18:47:22.5704890Z net.nim(1604)            dial
2020-01-13T18:47:22.5704970Z oserr.nim(94)            raiseOSError
2020-01-13T18:47:22.5705030Z Error: unhandled exception: Connection refused [OSError]
2020-01-13T18:47:22.5705410Z [0m
2020-01-13T18:47:22.5705860Z [32mPASS: [36mtests/stdlib/tnre.nim C++                                   [34m ( 3.71296191 secs)[0m
```

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #13132
* you can see this by adding `for i in 0..<10000: test()`, it always failed before this PR after a few iterations (but won't fail depending on whether you add other modifications, eg `echo i`)

### CODE REVIEW

**Comment by Araq** [comment]
Ok, *why* does this fix the test?

**Comment by timotheecour** [comment]
it fixes a race condition, we now setup the server before spawning a thread that pings it

File: tests/stdlib/tnetdial.nim [hunk 1]
```diff
@@ -2,7 +2,6 @@ discard """
   cmd: "nim c --threads:on $file"
   exitcode: 0
   output: "OK"
-  disabled: "travis"
```
Comment (narimiran) [inline tests/stdlib/tnetdial.nim:5]: Even after this PR, this test fails on Travis.

Comment (dom96) [reply tests/stdlib/tnetdial.nim:5]: Why does it fail? What's the problem? Timing sensitivity?
