### PR TITLE
lots of testament bug fixes and improvements:

### LINKED ISSUE #9328: testsuite silently ignores a number of tests
- [ ] are isMainModule blocks run by CI or not?
if not, they either should, or its use should be discouraged for testing as it gives false sense of it working
**EDIT**: they're not, currently

- [ ] isMainModule block fails for ./lib/core/typeinfo.nim

nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r ./lib/core/typeinfo.nim

/Users/timothee/git_clone/nim/Nim/lib/core/typeinfo.nim(685) typeinfo
/Users/timothee/git_clone/nim/Nim/lib/system.nim(3876) failedAssertImpl
/Users/timothee/git_clone/nim/Nim/lib/system.nim(3869) raiseAssert
/Users/timothee/git_clone/nim/Nim/lib/system.nim(2916) sysFatal
Error: unhandled exception: /Users/timothee/git_clone/nim/Nim/lib/core/typeinfo.nim(685, 18) `n == "name" and $kind(a) == "akString"`  [AssertionError]

using echo shows "Field0" instead of "name"

Note:
git rev-parse HEAD
fde4a086c5be2140b3b39014b302f681c87cb33c

## proposal
* testament should list all files `foo.nim` with a `isMainModule` block (using maybe nimgrep)
* we maintain a (small) blacklist of files where we don't want to run `foo.nim` (or don't want to run in a particular platform)
* we run each of the resulting `foo.nim`

Note: it's important to keep a blacklist of files that we skip, as opposed to other way around (a whilelist) as it's much easier to maintain that way; so if someone adds a `isMainModule` in a file, it'll automatically be run by CI (except if added to blacklist)

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @Araq @krux02 

* fix #9328 testsuite silently ignores a number of tests
* all stdlib modules are now compiled (and run when appropriate), except an explicit blacklist that fails
  (previously it ignored deeper nested modules, eg lib/pure/foo/bar.nim)
* that exposed a number of failing tests that were never previously run under CI, see disabledFilesDefault
* ditto with files under tests/
* ditto with identifying modules suitable for megatest

* isJoinableSpec now returns false if there's a nims file
* isJoinableSpec now searches deeper for a nim.cfg (and config.nims) file, since that's how config files work

* show absolute progress (eg: category 10 / 120)
* new --dryrun mode that just completes in ~5 seconds and prints out all the testSpec that would be run; helpful for debugging
* files are now processed in sorted order, making test run order more deterministic and easier to follow
* testament now doesn't strip dir component, making it easier to follow, eg:
  PASS: cyclecollector C -d:release
  =>
  PASS: tests/gc/cyclecollector C -d:release

### CODE REVIEW

File: testament/categories.nim [hunk 1]
```diff
@@ -527,6 +555,10 @@ proc isJoinableSpec(spec: TSpec): bool =
     spec.outputCheck != ocSubstr and
     spec.ccodeCheck.len == 0 and
     (spec.targets == {} or spec.targets == {targetC})
+  if result:
+    for dir in parentDirs(spec.file, inclusive=false):
```
Comment (Araq) [inline testament/categories.nim]: So my personal config in ``~`` disables all of these? I don't think so. Testament should test the tests, it's not required to replicate the compiler's terrible config logic here.

File: testament/categories.nim [hunk 2]
```diff
@@ -517,7 +545,7 @@ proc isJoinableSpec(spec: TSpec): bool =
   result = not spec.sortoutput and
     spec.action == actionRun and
     not fileExists(spec.file.changeFileExt("cfg")) and
-    not fileExists(parentDir(spec.file) / "nim.cfg") and
```
Comment (Araq) [inline testament/categories.nim]: This is a heuristic and the tests all use ``nim.cfg``. Nothing to change here.

File: testament/categories.nim (hunk 1 above)
Comment (Araq) [reply testament/categories.nim]: That we keep it simple. This part of the logic can also be removed if the tests get patched with ``joinable: false``.

File: testament/tester.nim [hunk 3]
```diff
@@ -521,6 +546,8 @@ proc main() =
         useColors = false
       else:
         quit Usage
+    of "dryrun":
+      dryrun = true
```
[the remark this answers is not in the document]
Comment (timotheecour) [reply testament/tester.nim]: it really helps with debugging though (that's how I debugged #9328)

Currently, debugging testament (the default `all` tests) is hard because:
* it takes 390 seconds to run
* it's forced to be multi-process (via execProcesses)

I deliberately kept the logic for `dryun` as simple as possible; there's only 2 `if dryrun:` places, complexity wise, it's not bad.

[the remark this answers is not in the document]
Comment (Araq) [reply testament/tester.nim]: This could also be in a ``when debug`` section then. And I would name it "simulate", not "dryrun".

File: testament/tester.nim [hunk 4]
```diff
@@ -12,10 +12,11 @@
 import
   parseutils, strutils, pegs, os, osproc, streams, parsecfg, json,
   marshal, backend, parseopt, specs, htmlgen, browsers, terminal,
-  algorithm, compiler/nodejs, times, sets, md5
+  algorithm, compiler/nodejs, times, sets, md5, sequtils
```
Comment (Araq) [inline testament/tester.nim]: But ``sequtils`` is pretty complex, if we break it, it's nice to see sequtils test case failures instead of broken testament builds.

File: testament/categories.nim [hunk 5]
```diff
@@ -644,7 +684,13 @@ proc processCategory(r: var TResults, cat: Category, options, testsDir: string,
     runJoinedTest(r, cat, testsDir)
   else:
     var testsRun = 0
-    for name in os.walkFiles("tests" & DirSep &.? cat.string / "t*.nim"):
+
+    var files: seq[string]
+    for file in walkDirRec("tests" & DirSep &.? cat.string):
+        if isTestFile(file): files.add file
+    files.sort # give reproducible order
```
[the remark this answers is not in the document]
Comment (timotheecour) [reply testament/categories.nim]: the OS's directory listing is never in alphabetical order, for efficiency, eg:
```nim
import os
for file in walkDirRec("tests"): echo file
```
tests/mmaptest.nim
tests/dummy.txt
tests/js.nim
tests/test_nimscript.nims
tests/readme.md
tests/js.html
tests/test.txt
tests/rectest.nim
...

different environments will produce different orderings; it's just less easy to look at when order is random / un-predicatable. And the big-O cost for doing so is 0,

File: testament/tester.nim (hunk 4 above)
Comment (timotheecour) [reply testament/tester.nim]: ok, will remove dependency on sequtils

Comment (timotheecour) [reply testament/tester.nim]: done

File: testament/categories.nim (hunk 1 above)
Comment (timotheecour) [reply testament/categories.nim]: kept it like before (it only look in parent dir); but also look for config.nims / myfile.nims ; these are needed as we'll want to test for that

File: testament/categories.nim (hunk 2 above)
Comment (timotheecour) [reply testament/categories.nim]: pushed commit to address that, as described here https://github.com/nim-lang/Nim/pull/10044#discussion_r242873682

File: testament/tester.nim (hunk 3 above)
[the remark this answers is not in the document]
Comment (timotheecour) [reply testament/tester.nim]: I pushed a commit to rename to `simulate` (the name dryrun is quite common though, eg in `brew` cmd line, `rsync`, etc)
However, hiding behind a `when debug` will cause code rot (ie over time, it may stop compiling) and making it harder to use.
If you really insist, for the sake of moving on I'll hide it behind a `when debug`
