### PR TITLE
fix #16206, `nim r / nim -r` recompiles if cwd changes

### LINKED ISSUE #16206: Error parsing INI section names with spaces
I was trying out the [example program from the documentation](https://nim-lang.org/docs/parsecfg.html) for parsing INI files. If the section name contains spaces, it would parse the INI file incorrectly.

### Example INI file
```INI
[SectionA]
[Section B]
```

### Current Output
```
new Section: SectionA
test.ini(2, 10) Error: ']' expected, but found: B
key-value-pair: B:
test.ini(2, 11) Error: invalid token: ]
```

### Expected Output
```
newSection: SectionA
newSection: Section B
```

### Possible Solution

* The documentation states, that the configuration syntax is similar to Windows Ini, so maybe this is the expected output?

### Additional Information

```
$ nim -v
Nim Compiler Version 1.4.2
```

### LINKED ISSUE #16271: Nimcache confusion compiling files with the same name in different directories
When having multiple file with the same name, living in different directories, Nim does not properly understand these are different files and re-uses the wrong nimcache result.

Reproducing:

- Create 2 Nim files with the same base name in different directories:

  * `a/t.nim`: `echo "a"`
  * `b/t.nim`: `echo "b"`

- Compile and run `t.nim` in `./a`
```
$ cd a
$ nim r t.nim
Hint: used config file '/home/idoornekamp/external/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/idoornekamp/external/Nim/config/config.nims' [Conf]
....CC: stdlib_io.nim
CC: stdlib_system.nim
CC: t.nim

Hint:  [Link]
Hint: 22400 lines; 0.594s; 30.547MiB peakmem; Debug build; proj: /tmp/a/t.nim; out: /home/idoornekamp/.cache/nim/t_d/t [SuccessX]
Hint: /home/idoornekamp/.cache/nim/t_d/t  [Exec]
a
```

- Compile and run `t.nim` in `./b`
```
$ cd b
$ nim r  t.nim 
Hint: used config file '/home/idoornekamp/external/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/idoornekamp/external/Nim/config/config.nims' [Conf]
Hint: 7853 lines; 0.021s; 11.359MiB peakmem; Debug build; proj: /tmp/b/t.nim; out: /home/idoornekamp/.cache/nim/t_d/t [SuccessX]
Hint: /home/idoornekamp/.cache/nim/t_d/t  [Exec]
a
```

Observe that the second run of `b/t.nim` results in `a/t.nim` getting executed, and no compilation is performed.

### PR DESCRIPTION
**Pull request by timotheecour**
fix https://github.com/nim-lang/Nim/issues/16271

`nim r` / `nim -r` recompiles if cwd changes

I'm hitting same bug as original reporter of https://github.com/nim-lang/Nim/issues/16271, eg with `nim r testament/testament args...`; this PR fixes that in the simplest possible way, that is robust even if pessimistic (recompile on cwd change). Future PR's can add more logic to be robust and less pessimistic, see comment in PR.

## future work
* `-d:nimBetterRunIgnoreCwd` (see `pr_fix_nimcache_nimrun_16271_followup_nimBetterRunIgnoreCwd` wip PR)
* robust approach described inside PR comment (it has other advantages which is caching more than 1 compilation, using a LRU cache to avoid blowing up disk usage)

### CODE REVIEW

File: compiler/extccomp.nim [hunk 1]
```diff
@@ -1043,14 +1045,23 @@ proc changeDetectedViaJsonBuildInstructions*(conf: ConfigRef; projectfile: Absol
...
+      # the N most recent unique build instructions, as done with `rdmd`,
+      # which is both robust and avoids recompilation when switching back and forth
+      # between projects, see https://github.com/timotheecour/Nim/issues/199
       return true
     let oldCmdLine = data["cmdline"].getStr
     if conf.commandLine != oldCmdLine:
       return true
     if hashNimExe() != data["nimexe"].getStr:
       return true
-    if not data.hasKey("stdinInput"): return true
```
Comment (Araq) [inline compiler/extccomp.nim:1053]: Why did you remove this line?

**Comment by Clyybber** [comment]
This means that doing
```
nim c file
cd ..
nim c folder/file
```
triggers a recompilation. This is too eager IMO.
Instead those flags that implicitly depend on the CWD should be checked to make sure the CWD is added to the respective path before checking for changes.

File: compiler/extccomp.nim (hunk 1 above)
Comment (timotheecour) [reply compiler/extccomp.nim:1053]: it's made redundant by:
```nim
for key in "depfiles cmdline stdinInput currentDir".split:
  if not data.hasKey(key): return true
```

**Comment by timotheecour** [comment]
> Instead those flags that implicitly depend on the CWD should be checked to make sure the CWD is added to the respective path before checking for changes.

I don't know of a reliable way to do that, so many flags can depend on CWD:
```
# examples:
nim r --lib:lib main
--path:.
--outdir:dir
-o:bin/main

# also:
--import
--include
--cincludes
--nimcache
--clibdir
--clib
--docRoot
--NimblePath
--excludePath
```

Furthermore, this would involve among other things understanding and parsing clang flags and linker flags, eg:
```
nim r --passl:-Wl,-rpath,lib --hotcodereloading:on /pathto/main.nim
```

or nim's own flags: `--docCmd:"--lib:lib" `

I also don't know which other flags (or error messages, depending on provided flags) implicitly depend on cwd, `jsondoc ctags buildIndex genDepend, genDeps...`

The robust approach I have in mind is described inside PR comment, and can be done later (it has other advantages which is caching more than 1 compilation, using a LRU cache to avoid blowing up disk usage).

That said, I'd be totally ok with an opt-in flag though, eg `-d:nimBetterRunIgnoreCwd` (named after existing `-d:nimBetterRun`, or a better name) which would use a best effort approach (starting with expanding input project file).

**Comment by timotheecour** [comment]
@Clyybber in light of https://github.com/nim-lang/Nim/issues/16354 i think we should merge this first, and once https://github.com/nim-lang/Nim/issues/16354 is fixed, introduce an opt-in `-d:nimBetterRunIgnoreCwd` which would use a best effort (optimistic) algorithm to decide whether to rebuild.

**Review by ringabout — COMMENTED** [review]
Related: https://github.com/nim-lang/Nim/issues/16531

**Review by Clyybber — APPROVED** [review]

**Review by ringabout — APPROVED** [review]

**Comment by 89z** [comment]
https://github.com/nim-lang/Nim/issues/16531
