### PR TITLE
Fixes multiple bugs with sink arguments 

### LINKED ISSUE #9781: Sink arguments type instantiation problem
In the example below I am checking the type of result variable of ``newUniquePtr`` proc.
I am expecting it to be ``UniquePtr[MySeq[system.float]]`` however it is ``UniquePtr[MySeq]`` which is not the concrete type. If I replace `sink T` argument of ``newUniquePtr`` with  usual `T` argument then problem goes away.
```
type
  UniquePtr*[T] = object
    ## non copyable pointer to object T, exclusive ownership of the object is assumed
    val: ptr T
  MySeq* [T] = object
    len: int
    data: ptr UncheckedArray[T]

proc `=destroy`*[T](m: var MySeq[T]) {.inline.} =
  if m.data != nil:
    deallocShared(m.data)
    m.data = nil

proc `=`*[T](m: var MySeq[T], m2: MySeq[T]) =
  if m.data == m2.data: return
  if m.data != nil:
    `=destroy`(m)

  m.len = m2.len
  let bytes = m.len.int * sizeof(float) 
  if bytes > 0:
    m.data = cast[ptr UncheckedArray[float]](allocShared(bytes))
    copyMem(m.data, m2.data, bytes)

proc `=sink`*[T](m: var MySeq[T], m2: MySeq[T]) {.inline.} =
  if m.data != m2.data:
    if m.data != nil:
      `=destroy`(m)
    m.len = m2.len
    m.data = m2.data

proc len*[T](m: MySeq[T]): int {.inline.} = m.len

proc `[]`*[T](m: MySeq[T]; i: int): float {.inline.} =
  m.data[i.int]

proc `[]=`*(m: var MySeq; i: int, val: float) {.inline.} =
  m.data[i.int] = val

proc setTo[T](s: var MySeq[T], val: float) = 
  for i in 0..<s.len.int:
    s.data[i] = val

proc newMySeq*[T](size: int, initial_value = 0.0): MySeq[T] =
  result.len = size
  if size > 0:
    result.data = cast[ptr UncheckedArray[float]](createShared(float, size))
  result.setTo(initial_value)


#-------------------------------------------------------------
# Unique pointer implementation
#-------------------------------------------------------------

proc `=destroy`*[T](p: var UniquePtr[T]) =
  if p.val != nil:
    `=destroy`(p.val[])
    dealloc(p.val)
    p.val = nil

proc `=`*[T](dest: var UniquePtr[T], src: UniquePtr[T]) {.error.}

proc `=sink`*[T](dest: var UniquePtr[T], src: UniquePtr[T]) {.inline.} =
  if dest.val != nil and dest.val != src.val:
    `=destroy`(dest)
  dest.val = src.val

import typetraits

proc newUniquePtr*[T](val: sink T): UniquePtr[T] =
  result.val = cast[type(result.val)](alloc(sizeof(result.val[])))
  reset(result.val[])
  result.val[] = val
  echo name(result.type)
  echo name(result.val.type)

converter convertPtrToObj*[T](p: UniquePtr[T]): var T =
  p.val[]

var pu = newUniquePtr(newMySeq[float](5, 1.0))
echo pu.len

#
```

### PR DESCRIPTION
**Pull request by cooldome**
Fixes #9781
also fixes issues with sizeof computation for sink arguments

### CODE REVIEW

File: compiler/sigmatch.nim [hunk 1]
```diff
@@ -1045,7 +1045,7 @@ proc typeRelImpl(c: var TCandidate, f, aOrig: PType,
     return typeRel(c, f, lastSon(aOrig))
 
   if a.kind == tyGenericInst and
-      skipTypes(f, {tyVar, tyLent}).kind notin {
+      skipTypes(f, {tyVar, tyLent, tySink}).kind notin {
```
Comment (Araq) [inline compiler/sigmatch.nim]: Weird that ``tySink`` is the same as ``tyVar`` here when it IMHO should be treated like ``tyAlias``.

**Comment by Araq** [comment]
See my remark, but I'm merging it anyway since it improves the situation.
