### PR TITLE
nimIoselector option

### LINKED ISSUE #10991: Epoll does not support many file types (EPERM from epoll_ctl)
The documentation for selectors.nim claims:
> Supported features: files, sockets, pipes, timers, processes, signals and user events.

For epoll that is not true, as it by design does not support notifications from file types which do not implement readiness and are always considered non-blocking. This includes plain files and some very common devices such as /dev/null.
Trying to use such file descriptors with epoll ioselector will yield error such as:
```
asyncdispatch.nim(1154)  addWrite
ioselectors_epoll.nim(164) updateHandle
selectors.nim(284)       raiseIOSelectorsError
Error: unhandled exception: Operation not permitted (code: 1) [IOSelectorsException]
```

The poll and select ioselectors don't have this issue, but there is no mechanism to use the ioselector or asyncdispatch API with those on Linux as epoll is hardcoded.
This can be remedied by adding compile-time define option to select the desired implementation. I will make pull request which does just that.
I would also suggest that ioselectors_poll should be the default on all POSIX platforms (or at least on Linux) to have most predictable application behaviour across platforms and let people manually select other if they need it.

### PR DESCRIPTION
**Pull request by bung87**
close #10991
ref: https://github.com/nim-lang/Nim/pull/10992

### CODE REVIEW

File: lib/pure/selectors.nim [hunk 1]
```diff
@@ -344,7 +344,18 @@ else:
           res = int(fdLim.rlim_cur) - 1
         res
 
-  when defined(linux) and not defined(emscripten):
+  when defined(ioselector):
```
Comment (Araq) [inline lib/pure/selectors.nim]: shouldn't this be `nimIoselector`?
