### PR TITLE
Fix #18718

### LINKED ISSUE #18718: RunningStat Incorrectly Initialized For `max`
Basically it does the right thing for `min` but not `max`.  The wrong only really impacts data series with negative numbers.

### Example
```nim
import stats
var rs: RunningStat
rs.push -1
echo rs.max # 0.0 not -1.0
```

### Current Output
```
0.0
```

### Expected Output
```
-1.0
```

### Possible Solution

* In file lib/pure/stats.nim:  proc push*(s: var RunningStat, x: float) = ..

Just change one line:
```
-  if s.n == 0: s.min = x
+  if s.n == 0: s.min = x; s.max = x
```

### Workaround

Since the max field is exported, a user can, as a workaround, set `s.max = float.low` to get the max accumulating from the first non-NAN `x`.  Without something like such, the `.max` field can never go negative while a `float` sure can.  If all the numbers are NAN this gives a different result (`-inf` instead of NAN). This is not a huge deal, but asymmetric treatment of min & max alone seems enough reason to just fix it as I suggest above.

### Additional Information

The git log says this has been a bug more or less forever (even the first 2009 release of `math.nim`), but in November 2015 @jlp765 *half*-fixed it (min-only) - oops. :-)

`stats.clear` does some weird `s.min = toBiggestFloat(int.high)` instead of `float.high`.  This is a misleading quasi-bug since `float` obviously has a much bigger `high` than `int.high`.  The way `push` logic works, all that really matters anyway is `n == 0` for `.min` (and should-be-IMO `.max`).  So, changing to `s.min = float.high` and `s.max = float.low` is also misleading.  In light of all this, it is probably also worthwhile changing that `clear` bit to just `s.min = 0.0` to be more transparently similar to a simple `var rs: RunningStats` zero init.

But, at the very least, someone should do is fix `.max` initialization which is super easy.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-08-20
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f2910077ac41a614154f3851f5bffc02b06124a2
active boot switches: -d:release -d:nimHasLibFFI
```

### PR DESCRIPTION
**Pull request by konsumlamm**
Fixes #18718.

I changed `clear` to set `s.min` and `s.max` to 0, as that's what @c-blake suggested and it's consistent with the default value of `RunningStat`. However, I'd have no problem to change that to `float.high` and `float.low`, respectively.

I also updated the tests to:
* include a test for #18718.
* test in the VM.
* not `include` the `std/stats` module

### CODE REVIEW

File: tests/stdlib/tstats.nim [hunk 1]
```diff
@@ -1,46 +1,55 @@
-include stats
+import std/stats
 
-proc clean(x: float): float =
-  result = round(1.0e8*x).float * 1.0e-8
+proc `~=`(x, y: float): bool =
+  abs(x - y) < 10e-8
```
Comment (timotheecour) [inline tests/stdlib/tstats.nim:4]: would math.almostEqual work?

Comment (konsumlamm) [reply tests/stdlib/tstats.nim:4]: Not without adjusting the `unitsInLastPlace` parameter, I tried using `almostEquals` first (the assertions fail).

**Review by timotheecour — APPROVED** [review]

File: tests/stdlib/tstats.nim (hunk 1 above)
Comment (timotheecour) [reply tests/stdlib/tstats.nim:4]: > Not without adjusting the unitsInLastPlace parameter

adjusting that param would be fine
