### PR TITLE
fix #17325 linux 32bit CI; fix #17085 flaky test

### LINKED ISSUE #17085: memory allocation during {.global.} init breaks GC
```nim
[arnetheduck@tempus tmp]$ more testit.nim
proc init(): string =
  for a in 0..<10000000:
    result.add 'c'

proc f() =
  var a {.global.} = init()
  var b {.global.} = init()
  var c {.global.} = init()

  echo a.len
  echo b.len
  echo c.len

f()
[arnetheduck@tempus tmp]$ nim c --hints:off -r testit.nim 
9920232
9920232
10000000
[arnetheduck@tempus tmp]$ nim --version
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-11-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release
```

this is because globals are registered to the global variable table _after_ `init` is run, meaning that any memory allocated while initializing globals will be collected by the gc

### LINKED ISSUE #17325: CI fails on azure 32 bit linux Linux_i386: sudo apt-fast install fails
I'm seeing:
`nim-lang.Nim (packages Linux_i386) Failing after 58s — packages Linux_i386 failed`
in several unrelated PRs (eg https://github.com/nim-lang/Nim/pull/17257#issuecomment-796247652)

eg https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/14075/logs/38

```
2021-03-10T21:10:24.0269335Z CC: stdlib_assertions.nim
2021-03-10T21:10:24.0288424Z CC: stdlib_dollars.nim
2021-03-10T21:10:24.1410956Z Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3  -I/home/vsts/work/1/s/lib -I/home/vsts/work/1/s -o /home/vsts/.cache/nim/koch_d/stdlib_assertions.nim.c.o /home/vsts/.cache/nim/koch_d/stdlib_assertions.nim.c' failed with exit code: 1
2021-03-10T21:10:24.1412125Z 
2021-03-10T21:10:24.1412666Z In file included from /usr/include/limits.h:25:0,
2021-03-10T21:10:24.1413573Z                  from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:168,
2021-03-10T21:10:24.1414497Z                  from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/syslimits.h:7,
2021-03-10T21:10:24.1415407Z                  from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:34,
2021-03-10T21:10:24.1416047Z                  from /home/vsts/work/1/s/lib/nimbase.h:268,
2021-03-10T21:10:24.1416680Z                  from /home/vsts/.cache/nim/koch_d/stdlib_assertions.nim.c:9:
2021-03-10T21:10:24.1417570Z /usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
2021-03-10T21:10:24.1418154Z compilation terminated.
2021-03-10T21:10:24.1472789Z ##[error]Bash exited with code '1'.
2021-03-10T21:10:24.1576588Z ##[section]Finishing: Build koch
```

(refs https://github.com/nim-lang/Nim/issues/3123#issuecomment-122125096)
refs:
* sudo apt-get install g++-multilib https://stackoverflow.com/questions/51765069/fatal-error-sys-cdefs-h-no-such-file-or-directory-while-compiling-openssl-1-1
* libc6-dev-i386 https://itectec.com/ubuntu/ubuntu-fatal-error-sys-cdefs-h-no-such-file-or-directory/

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @narimiran 
* fix https://github.com/nim-lang/Nim/issues/17325 linux 32bit CI
* fix #17085 flaky test
* closes https://github.com/nim-lang/Nim/pull/17451

note, the underlying issue with 32bit linux CI was due to upstream broken packages and lasted from 1 to 2 weeks but the upstream issue has now been fixed. In the meantime other tests were added that were broken in i386; this PR fixes those tests

### CODE REVIEW

File: lib/pure/json.nim [hunk 1]
```diff
@@ -1069,12 +1069,13 @@ when defined(nimFixedForwardGeneric):
     dst = jsonNode.copy
 
   proc initFromJson[T: SomeInteger](dst: var T; jsonNode: JsonNode, jsonPath: var string) =
-    when T is uint|uint64:
+    when T is uint|uint64 or (not defined(js) and int.sizeof == 4):
```
Comment (timotheecour) [inline lib/pure/json.nim:1072]: this logic can be refined in future work, but at least it's good to re-enable a non-broken i386

File: tests/gc/trace_globals.nim [hunk 2]
```diff
@@ -15,8 +21,8 @@ proc f() =
   var b {.global.} = init()
   var c {.global.} = init()
 
-  echo a.len
-  echo b.len
-  echo c.len
+  doAssert a.len == 10000000
+  doAssert b.len == 10000000
+  doAssert c.len == 10000000
```
Comment (Araq) [inline tests/gc/trace_globals.nim]: I don't remember exactly but I suspect I could trigger the corruptions only with the `echo`, not with `doAssert`... Besides, my fix works too and makes the CI a tiny bit faster.

Comment (timotheecour) [reply tests/gc/trace_globals.nim]: as you wish; note that I can't reproduce the original bug report, see https://github.com/nim-lang/Nim/issues/17085#issuecomment-805355052

for things like this we should add comments like: `# bug triggered by echo` so that tests don't later get transformed into doAssert

(if you merge https://github.com/nim-lang/Nim/pull/17487, I'll update this PR and add this comment)

Comment (timotheecour) [reply tests/gc/trace_globals.nim]: done, I've put back the echo and added a comment

**Review by ringabout — APPROVED** [review]
