### PR TITLE
Handle failed uri parsing in asynchttpserver

### LINKED ISSUE #6358: asynchttpserver crashes on double slash url
```
going to example 
localhost:8080// 
```
will crash with error
```
Error: unhandled exception: Expected authority got nothing.
  processClient's lead up to read of failed Future:
    Traceback (most recent call last)
    prof.nim(7)              prof
    asyncdispatch.nim(278)   waitFor
    asyncdispatch.nim(333)   poll
    asyncdispatch.nim(179)   processPendingCallbacks
    asyncmacro.nim(34)       cb0
    asynchttpserver.nim(181) processClientIter
    uri.nim(139)             parseUri [ValueError]
```
```
Nim Compiler Version 0.17.2 (2017-09-07) [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 811fbdafd958443ddac98ad58c77245860b38620
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by superfunc**
Fixes #6358

### CODE REVIEW

File: lib/pure/asynchttpserver.nim [hunk 1]
```diff
@@ -178,7 +178,12 @@ proc processClient(client: AsyncSocket, address: string,
         except ValueError:
           asyncCheck request.respondError(Http400)
           continue
-      of 1: parseUri(linePart, request.url)
+      of 1: 
+        try:
+          parseUri(linePart, request.url)
+        except ValueError:
+          asyncCheck request.respondError(Http400)
```
Comment (yglukhov) [inline lib/pure/asynchttpserver.nim]: Are these `asyncCheck`s really correct here? Should not we block further socket processing with `await`s instead? Also should not we close the connection after errors?

Comment (dom96) [reply lib/pure/asynchttpserver.nim]: The reason for the `asyncCheck` here is that `await` cannot be put inside an `except` branch (IIRC).

Responding with Http400 is cool. The client should be given a chance to retry (as above).

Comment (yglukhov) [reply lib/pure/asynchttpserver.nim]: > await cannot be put

That is not an excuse for the code that behaves incorrectly. What if both HTTP method and URL are incorrect? Shall we reply twice?

Comment (dom96) [reply lib/pure/asynchttpserver.nim]: I don't think that can happen. The ``continue`` ensures it.

**Comment by Araq** [comment]
Tests can be added later, I'm merging it now.

File: lib/pure/asynchttpserver.nim (hunk 1 above)
Comment (yglukhov) [reply lib/pure/asynchttpserver.nim]: It does happen, and results in complete garbage:
```sh
$ telnet localhost 5000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
BLA BLA BLA
HTTP/1.1 400 Bad Request
Content-Length: 15

400 Bad RequestHTTP/1.1 400 Bad Request
Content-Length: 15

400 Bad RequestHTTP/1.1 400 Bad Request
Content-Length: 15

400 Bad Request
HTTP/1.1 404 Not Found
Content-Length: 178
Content-Type: text/html;charset=utf-8

<html xmlns="http://www.w3.org/1999/xhtml"><head><title>404 Not Found</title></head><body style="text-align: center;"><h1>404 Not Found</h1><hr/><p>Jester 0.1.0</p></body></html>Connection closed by foreign host.
```

Comment (yglukhov) [reply lib/pure/asynchttpserver.nim]: This bug is very critical IMO. This could potentially result in clients getting `404` for urls that are actually valid.

Comment (dom96) [reply lib/pure/asynchttpserver.nim]: It's hard to see what you're sending to the server in your session. Can you create an issue for this and elaborate?

Comment (yglukhov) [reply lib/pure/asynchttpserver.nim]: #6386
