### PR TITLE
Adjust the correct chunk's free space in allocator

### LINKED ISSUE #23788: Segfaults in multithreaded code after recent allocator changes
### Description

Best repro I got currently, consistently segfaults in debug mode, less consistent in release, so it's probably a race condition in the allocator.

```nim
import std/[os]

import malebolgia


proc main =
  proc worker(x: string) =
    for p in parentDirs(x, fromRoot=true):
      discard
  var strs = newSeq[string]()
  for i in 0 ..< 10000:
    strs.add "/AAAA/AAAAAAAA/AAAAAAAA/AAAAAAAA/AAAAAAAA/AAAAAAAA/AAAAAAAA/AAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/" & $i

  var m = createMaster()
  m.awaitAll:
    for i in 0 ..< strs.len():
      m.spawn worker(strs[i])

main()
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-07-02
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: fe3039410f9fa637fdd958df4d96272484ebdb86
active boot switches: -d:release

### Current Output

```text
Traceback (most recent call last)
.../a.nim(19) a
.../a.nim(17) main
.../Nim/lib/system.nim(378) worker
.../Nim/lib/system/alloc.nim(1072) dealloc
.../Nim/lib/system/alloc.nim(952) rawDealloc
.../Nim/lib/system/alloc.nim(556) listRemove
SIGSEGV: Illegal storage access. (Attempt to read from nil?
```

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SirOlaf**
Fixes #23788

### CODE REVIEW

File: lib/system/alloc.nim [hunk 1]
```diff
@@ -943,12 +943,13 @@ proc rawDealloc(a: var MemRegion, p: pointer) =
                 s -% sizeof(FreeCell))
       # check if it is not in the freeSmallChunks[s] list:
       if c.free < s:
+        # TODO: Steal freeList from the other chunk? Leaving it as is will waste a lot of cells until we return to the other chunk
```
Comment (Araq) [inline lib/system/alloc.nim]: What does that mean? Do we leak here or is the memory reused later?

File: lib/system/alloc.nim [hunk 2]
```diff
@@ -943,12 +943,13 @@ proc rawDealloc(a: var MemRegion, p: pointer) =
...
         # add it to the freeSmallChunks[s] array:
         listAdd(a.freeSmallChunks[s div MemAlign], c)
         inc(c.free, s)
       else:
         inc(c.free, s)
-        if c.free == SmallChunkSize-smallChunkOverhead():
+        if a.freeSmallChunks[s div MemAlign] == c and c.free == SmallChunkSize-smallChunkOverhead():
```
Comment (Araq) [inline lib/system/alloc.nim]: Change the order of these tests for better performance.

File: lib/system/alloc.nim (hunk 1 above)
Comment (SirOlaf) [reply lib/system/alloc.nim]: The memory should be reused _eventually_, but through bad ordering of dealloc a chunk may hold onto both owned and foreign cells until it becomes the head of the list again. If this happens multiple times in a worst case scenario you'd lose out on `SmallChunkSize - smallChunkOverhead() - size` per suspended chunk (maybe more with foreign cells)

File: lib/system/alloc.nim (hunk 2 above)
Comment (SirOlaf) [reply lib/system/alloc.nim]: You're right, I actually tried that locally and it didn't make a significant difference in my tests, but no reason to leave it on the table.

File: lib/system/alloc.nim (hunk 1 above)
Comment (SirOlaf) [reply lib/system/alloc.nim]: It is also difficult to free a suspended chunk because of the potential for shared cells, so it must stay in memory.

Comment (SirOlaf) [reply lib/system/alloc.nim]: Because of similar reasons I was thinking that a chunk doesn’t actually need the `free` field, but no concrete ideas to improve it. A vague idea though would be to repurpose it to keep track of cells it lent to other chunks.

Comment (SirOlaf) [reply lib/system/alloc.nim]: Looking at it again the `TODO` probably isn't a concern because it should cycle the chunks. Would be good to come up with a way to free pages without checking if it's active though.

**Comment by SirOlaf** [comment]
Test failures look to be related to the default hash change.
