### PR TITLE
Fix #4275: Argument count not checked in importcpp

### LINKED ISSUE #4275: Argument count not checked: importcpp
This code crashes the compiler. 0.13.0 and devel. Both "nim cpp" and "nim c". It doesn't matter whether foo.h exists or not.
```nim
proc f() {.header: "foo.h", importcpp: "f(#)".}
f()
```
```
Traceback (most recent call last)
nim.nim(115)             nim
nim.nim(71)              handleCmdLine
main.nim(257)            mainCommand
main.nim(64)             commandCompileToC
modules.nim(227)         compileProject
modules.nim(172)         compileModule
passes.nim(203)          processModule
passes.nim(137)          processTopLevelStmt
cgen.nim(1220)           myProcess
ccgstmts.nim(1120)       genStmts
ccgexprs.nim(2048)       expr
ccgcalls.nim(529)        genCall
ccgcalls.nim(421)        genInfixCall
ccgcalls.nim(392)        genPatternCall
ccgcalls.nim(263)        genOtherArg
system.nim(2527)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```
Easy to see the problem here. Not so easy in a large codebase when the compiler crashes before reporting any errors.

### PR DESCRIPTION
**Pull request by mbaulch**
Varargs is now supported, though the check still occurs at the call, not the definition.

The drawbacks I can see are: (1) slightly greater overhead due to repeated notin checks, (2) error is reported at callsite, which is potentially misleading.

Is this okay for now, or should I find a way to check at the definition?

Note: This PR supercedes https://github.com/nim-lang/Nim/pull/4355

### CODE REVIEW

**Comment by mbaulch** [comment]
It seems there are two options for handling arguments to `importcpp`:

1. Pre-process and semantically check that each argument against the Nim proc prototype; or
2. Save each argument in the AST as a string, and only process it if/when the corresponding proc is called.

At present, the compiler takes the second option. This has the benefit of low overhead for imported procs that aren't called. For instance, a small app importing large libraries containing many C++ bindings. The disadvantage is that syntactic and semantic errors in `importcpp` args are only caught when the proc is called.

The first option imposes an upfront performance (and most likely space) penalty. Nevertheless, it allows for earlier error detection and performance gains when `importcpp`'ed procs are called repeatedly.

What sits best where language design is concerned? `importcpp` is a "pragma" or _hint_ only. Perhaps that means it shouldn't receive semantic checking unless necessary? If so then option 2, the status quo, wins.

Implementation of option 1 wouldn't be a quick endeavor. Therefore, if anyone wants to start on it, some sort of prior consensus would help to avoid wasted effort.

What do others think?

File: compiler/ccgcalls.nim [hunk 1]
```diff
@@ -260,6 +260,8 @@ proc genOtherArg(p: BProc; ri: PNode; i: int; typ: PType): Rope =
     else:
       result = genArgNoParam(p, ri.sons[i]) #, typ.n.sons[i].sym)
   else:
+    if tfVarargs notin typ.flags:
+      localError(ri.info, "wrong argument count")
```
Comment (Araq) [inline compiler/ccgcalls.nim]: localError is allowed to return, so you end up calling 'genArgNoParam' with the index error anyway. Use an 'else' and let the result be nil.

**Comment by mbaulch** [comment]
You're right. Just had a closer look. If `msgs.gErrorMax > 1` this can happen.
