### PR TITLE
Fixes #25261

### LINKED ISSUE #25261: `SIGSEGV` regression from Nim v2.2.4 to v2.2.6/devel with closure iteratures
### Nim Version

No `SIGSEGV`:
```
Nim Compiler Version 2.2.4 [Linux: amd64]
Compiled at 2025-11-03
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: f7145dd26efeeeb6eeae6fff649db244d81b212d
active boot switches: -d:release
```

`SIGSEGV`:
```
Nim Compiler Version 2.2.6 [Linux: amd64]
Compiled at 2025-11-05
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: ab00c56904e3126ad826bb520d243513a139436a
active boot switches: -d:release
```

```
Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2025-11-05
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: cfefd1d95b02fe8c099ee28074616031cf5a0b3b
active boot switches: -d:release
```

### Description

```nim
iterator y(): int {.closure.} =
  try:
    try:
      raise newException(CatchableError, "")
    except CatchableError:
      return
    yield 0
  finally:
    discard

let w = y
discard w()
```

### Current Output

```text
/tmp/m.nim(7, 5) Warning: unreachable code after 'return' statement or '{.noReturn.}' proc [UnreachableCode]
CC: system/exceptions.nim
CC: std/private/digitsutils.nim
CC: system/dollars.nim
CC: system.nim
CC: m.nim
Hint:  [Link]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
28942 lines; 0.491s; 31.199MiB peakmem; proj: /tmp/m.nim; out: /tmp/m [SuccessX]
Hint: /tmp/m [Exec]
Traceback (most recent call last)
/tmp/m.nim(12)           m
/tmp/m.nim(1)            y
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
Error: execution of an external program failed: '/tmp/m'
```

### Expected Output

```text
No SIGSEGV
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by yglukhov**
Returning or yielding from a closureiter must restore "external" exception, but `popCurrentException` from `blockLeaveActions` was getting in the way. So now `blockLeaveActions` doesn't emit `popCurrentException` for returns in closureiters. I'm not a fan of this "abstraction leakage", but don't see a better solution yet. Any input is much appreciated.

### CODE REVIEW

File: compiler/ccgstmts.nim [hunk 1]
```diff
@@ -258,9 +258,9 @@ proc blockLeaveActions(p: BProc, howManyTrys, howManyExcepts: int) =
 
   # Pop exceptions that was handled by the
   # except-blocks we are in
-  if noSafePoints notin p.flags:
-    for i in countdown(howManyExcepts-1, 0):
-      p.s(cpsStmts).addCallStmt(cgsymValue(p.module, "popCurrentException"))
+  if noSafePoints notin p.flags and not (isReturnStmt and isClosureIterator(p.prc.typ)):
+      for i in countdown(howManyExcepts-1, 0):
+        p.s(cpsStmts).addCallStmt(cgsymValue(p.module, "popCurrentException"))
```
Comment (Araq) [inline compiler/ccgstmts.nim]:
```suggestion
    for i in countdown(howManyExcepts-1, 0):
      p.s(cpsStmts).addCallStmt(cgsymValue(p.module, "popCurrentException"))
```

**Comment by arnetheduck** [comment]
cc @narimiran to be backported please!

**Comment by narimiran** [comment]
> cc @narimiran to be backported please!

It has already been backported to `version-2-2` three days ago :)
