### PR TITLE
fix #16822

### LINKED ISSUE #14574: js: `lent` doesn't work in iterators with tuple destructuring
`toTable` doesn't work with js target with values of non-primitive type: Cannot read property 'slice' of undefined
### Example
```nim
import tables
type Foo = object
  a: int
proc fn() =
  let x = Foo(a: 10) # likewise with tuples
  block:
    var t: Table[string, Foo]
    t["abc"] = x # ok
  block:
    let t = {"abc": x}.toTable # bug
fn()
```

### Current Output
nim js -r --lib:lib $timn_D/tests/nim/all/t10893.nim
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:170
        result_33250219 = src_33245024.slice(0);
                                       ^

TypeError: Cannot read property 'slice' of undefined
    at nimCopy (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:170:40)
    at nimCopyAux (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:1994:48)
    at nimCopyAux (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:1999:7)
    at nimCopy (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:145:7)
    at toTable_34360655 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:2647:13)
    at fn_34271017 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:2673:24)
    at Object.<anonymous> (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:2682:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
```

### Expected Output
```
works
```

### Additional Information
* devel 0824fdd06100282a853fa50efb66e2161f4235d8 1.3.5

EDIT:
this works:
```nim
proc toTable2*[A, B](pairs: openArray[(A, B)]): Table[A, B] =
  result = initTable[A, B](rightSize(pairs.len))
  # for key, val in items(pairs):
  for i in 0..<len(pairs):
    result[pairs[i][0]] = pairs[i][1]
```

so looks like what's broken is items tuple destructuring:

```nim
  proc fn() =
    let a = @[("foo", (12, 13))]
    for (k,v) in a:
      echo (k,v)
  fn()
```
crashes with:
```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:198
        result_33250219 = src_33245024.slice(0);
                                       ^

TypeError: src_33245024.slice is not a function
    at nimCopy (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:198:40)
    at nimCopyAux (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:366:48)
    at nimCopyAux (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:371:7)
    at nimCopy (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:173:7)
    at fn_33627401 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:895:13)
    at Object.<anonymous> (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10893.js:915:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
```

EDIT: bug disappears if I remove `lent` in iterators.nim
```nim
iterator items*[T](a: seq[T]): lent2 T {.inline.} =
=>
iterator items*[T](a: seq[T]): T {.inline.} =
```

### LINKED ISSUE #16822: Tuple unpacking in for loops does not work on js backend
When using `js` backend with `-d:nodejs` enabled following code errors out with `Cannot read property '0' of null`.

### Example
```nim
var scores: seq[(set[char], int)] = @{{'/'} : 10}

for item in items(scores):
  echo item[0]

for (chars, value) in items(scores):
  echo chars
```

### Current Output

For nim `1.4.2` compiled js code crashes with error. Compiled on `devel` code does not crash, but prints incorrect output (empty set `{}` for loop unpacking)

**1.4.2. output**
```
{'/'}
/mnt/workspace/github/hax-nim/jsback/nimcache/arriter.js:697
            if ((x_1860665[i_1861194] != undefined)) {
                          ^

TypeError: Cannot read property '0' of null
```

**devel output**
```
{'/'}
{}
```

### Expected Output
C backend produces following output:

```
{'/'}
{'/'}
```

### Additional Information

```
$ nim -v
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-11-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release -d:danger
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #16822
fix #14574
The kind of y may be `nkHiddenAddr`(so could be fixed by `skipAddr` too), so using `x.type` may be more correct.

### CODE REVIEW

File: tests/js/t16822.nim [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+var x: set[char]
+for item in items(scores):
+  x = item[0]
+
+doAssert x == {'/'}
+
+for (chars, value) in items(scores):
+  x = chars
+
+doAssert x == {'/'}
```
Comment (metagn) [inline tests/js/t16822.nim]: Should use a different `x` here, the loop could be a nop

**Comment by timotheecour** [comment]
@xflywind, awesome this also fixes https://github.com/nim-lang/Nim/issues/14574; please add these tests:
```nim
block: # bug #14574
  proc fn(): auto =
    let a = @[("foo", (12, 13))]
    for (k,v) in a:
      return (k,v)
  doAssert fn() == ("foo", (12, 13))

block: # bug #14574
  iterator fn[T](a:T): lent T = yield a
  let a = (10, (11,))
  proc bar(): auto =
    for (x,y) in fn(a):
      return (x,y)
  doAssert bar() == (10, (11,))
```

and change:
```
    when not defined(js): # pending https://github.com/nim-lang/Nim/issues/14574
      testRoundtrip({"z": (f1: 'f'), }.toTable): """{"z":{"f1":102}}"""
```
to
```nim
    # bug #14574
    testRoundtrip({"z": (f1: 'f'), }.toTable): """{"z":{"f1":102}}"""
```
in `tests/stdlib/tjsonutils.nim`

and add: "fix https://github.com/nim-lang/Nim/issues/14574" to your PR description so it auto-closes it

thanks!

File: tests/js/t16822.nim [hunk 2]
```diff
@@ -0,0 +1,29 @@
+block: # bug #16822
```
Comment (timotheecour) [inline tests/js/t16822.nim:1]: optional (we can also do this in future work) how about:
* move these to `tests/tuples/ttuples_issues.nim` instead of creating a new js-only test
* change spec to:
```nim
discard """
  targets: "c cpp js"
"""
```
(also cpp here because tuple have often caused bugs specific to cpp in past)
* remove the echo in this test by changing last few lines to:
```nim
block: # bug #14911
  doAssert $(a: 1) == "(a: 1)" # works
  doAssert $(`a`: 1) == "(a: 1)" # works
  doAssert $(`a`: 1, `b`: 2) == "(a: 1, b: 2)" # was: Error: named expression expected
```
(i checked, it works with js,c,cpp)

* change labels like `block t1986` to `block: # bug #1986`

* running those tests in vm with `template main` will face a bug, while running those in vm with `proc main` will run into https://github.com/nim-lang/Nim/issues/12492

more generally, IMO we should reserve `tests/js` to things that are really only relevant to js, so we increase test coverage on all backends while keeping tests DRY

File: tests/js/t16822.nim (hunk 1 above)
Comment (timotheecour) [reply tests/js/t16822.nim]: was fixed

File: compiler/jsgen.nim [hunk 3]
```diff
@@ -1077,10 +1077,10 @@ proc genAsgnAux(p: PProc, x, y: PNode, noCopyNeeded: bool) =
       # supports proc getF(): var T
       if x.kind in {nkHiddenDeref, nkDerefExpr} and x[0].kind in nkCallKinds:
           lineF(p, "nimCopy($1, $2, $3);$n",
-                [a.res, b.res, genTypeInfo(p, y.typ)])
+                [a.res, b.res, genTypeInfo(p, x.typ)])
```
Comment (timotheecour) [inline compiler/jsgen.nim:1080]: does 
```nim
lineF(p, "$1 = nimCopy(null, $2, $3);$n",
               [a.rdLoc, b.res, genTypeInfo(p, y.typ)])
```
a few lines above also need to change to y.typ => x.typ?
(I don't know which one is correct)

**Comment by Araq** [comment]
@timotheecour's remarks can be done later, merging this as it is because it's small and simple.

File: tests/js/t16822.nim (hunk 2 above)
Comment (timotheecour) [reply tests/js/t16822.nim:1]: => https://github.com/nim-lang/Nim/pull/16907
