### PR TITLE
fixes #22844; uses arrays to store holeyenums for iterations; much more efficient than sets and reasonable for holeyenums

### LINKED ISSUE #22844: enumutils items[HoleyEnum] example code produces "unsafe" warnings
### Description

The [items[T: HoleyEnum](E: typedesc[T]): T](https://nim-lang.org/docs/enumutils.html#items.i%2Ctypedesc%5BT%5D) example code (after fixing)* produces several copies of this warning:

> conversion to enum with holes is unsafe: T(i) [HoleEnumConv]

This gives the impression that the iterator is being misused, which seems very strange given that it is specifically made for HoleyEnum types. Is this intended behavior?

*(The example actually fails to compile at all; it has the required sequtils import, but it's missing the enumutils import.)

```nim
type
  A = enum
    a0 = 2
    a1 = 4
    a2
  B[T] = enum
    b0 = 2
    b1 = 4
from std/enumutils import items  # missing from the example code
from std/sequtils import toSeq
assert A.toSeq == [a0, a1, a2]
assert B[float].toSeq == [B[float].b0, B[float].b1]
```

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-10-19
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
$ nim c enum.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
...........................................................................
/tmp/nim/enum.nim(11, 1) template/generic instantiation of `assert` from here
/usr/lib/nim/lib/pure/collections/sequtils.nim(848, 11) template/generic instantiation of `toSeq1` from here
/usr/lib/nim/lib/pure/collections/sequtils.nim(791, 30) template/generic instantiation of `items` from here
/usr/lib/nim/lib/std/enumutils.nim(107, 25) template/generic instantiation of `items` from here
/usr/lib/nim/lib/system/iterators.nim(59, 9) Warning: conversion to enum with holes is unsafe: T(i) [HoleEnumConv]
/tmp/nim/enum.nim(11, 1) template/generic instantiation of `assert` from here
/usr/lib/nim/lib/pure/collections/sequtils.nim(848, 11) template/generic instantiation of `toSeq1` from here
/usr/lib/nim/lib/pure/collections/sequtils.nim(791, 30) template/generic instantiation of `items` from here
/usr/lib/nim/lib/std/enumutils.nim(107, 25) template/generic instantiation of `items` from here
/usr/lib/nim/lib/system/iterators.nim(59, 26) Warning: conversion to enum with holes is unsafe: T(i) [HoleEnumConv]
/tmp/nim/enum.nim(12, 1) template/generic instantiation of `assert` from here
/usr/lib/nim/lib/pure/collections/sequtils.nim(848, 11) template/generic instantiation of `toSeq1` from here
/usr/lib/nim/lib/pure/collections/sequtils.nim(791, 30) template/generic instantiation of `items` from here
/usr/lib/nim/lib/std/enumutils.nim(107, 25) template/generic instantiation of `items` from here
/usr/lib/nim/lib/system/iterators.nim(59, 9) Warning: conversion to enum with holes is unsafe: T(i) [HoleEnumConv]
/tmp/nim/enum.nim(12, 1) template/generic instantiation of `assert` from here
/usr/lib/nim/lib/pure/collections/sequtils.nim(848, 11) template/generic instantiation of `toSeq1` from here
/usr/lib/nim/lib/pure/collections/sequtils.nim(791, 30) template/generic instantiation of `items` from here
/usr/lib/nim/lib/std/enumutils.nim(107, 25) template/generic instantiation of `items` from here
/usr/lib/nim/lib/system/iterators.nim(59, 26) Warning: conversion to enum with holes is unsafe: T(i) [HoleEnumConv]
CC: ../../usr/lib/nim/lib/system/exceptions.nim
CC: ../../usr/lib/nim/lib/std/private/digitsutils.nim
CC: ../../usr/lib/nim/lib/std/assertions.nim
CC: ../../usr/lib/nim/lib/system/dollars.nim
CC: ../../usr/lib/nim/lib/system.nim
CC: enum.nim
Hint:  [Link]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
31124 lines; 0.236s; 37.566MiB peakmem; proj: /tmp/nim/enum.nim; out: /tmp/nim/enum [SuccessX]
```

### Expected Output

```text
no warnings
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #22844

### CODE REVIEW

File: lib/system/iterators.nim [hunk 1]
```diff
@@ -61,7 +61,10 @@ iterator items*[T](a: set[T]): T {.inline.} =
   ## able to hold).
   var i = low(T).int
   while i <= high(T).int:
-    if T(i) in a: yield T(i)
+    when not defined(nimHasCastExtendedVm):
```
Comment (ringabout) [inline lib/system/iterators.nim]:
```suggestion
    when defined(nimHasCastExtendedVm):
```

File: lib/system/iterators.nim [hunk 2]
```diff
@@ -61,7 +61,10 @@ iterator items*[T](a: set[T]): T {.inline.} =
   ## able to hold).
   var i = low(T).int
   while i <= high(T).int:
-    if T(i) in a: yield T(i)
+    when defined(nimHasCastExtendedVm):
```
Comment (ringabout) [inline lib/system/iterators.nim]:
```suggestion
    when defined(nimHasCastExtendedVm) and T is enum::
```

File: lib/system/iterators.nim [hunk 3]
```diff
@@ -61,7 +61,10 @@ iterator items*[T](a: set[T]): T {.inline.} =
   ## able to hold).
   var i = low(T).int
   while i <= high(T).int:
-    if T(i) in a: yield T(i)
+    when defined(nimHasCastExtendedVm) and T is enum::
```
Comment (ringabout) [inline lib/system/iterators.nim]:
```suggestion
    when defined(nimHasCastExtendedVm) and T is enum:
```

File: lib/system/iterators.nim [hunk 4]
```diff
@@ -61,7 +61,10 @@ iterator items*[T](a: set[T]): T {.inline.} =
   ## able to hold).
   var i = low(T).int
   while i <= high(T).int:
-    if T(i) in a: yield T(i)
+    when defined(nimHasCastExtendedVm) and T is enum:
+      if cast[T](i) in a: yield cast[T](i)
+    else:
+      if T(i) in a: yield T(i)
```
Comment (ringabout) [inline lib/system/iterators.nim]:
```suggestion
    if T(i) in a: yield T(i)
```
