### PR TITLE
fix generic param substitution in templates

### LINKED ISSUE #6340: issues using generic parameters in template
In `template fooT[T](x: A[T])` calling `foo(T)`, which is a proc, crashes the compiler and calling `fooT(T)`, which is a template, matches the `int` overload instead of `typedesc[int]`.

```nim
type
  A[T] = object
    v: T

proc foo(x: int) = echo "int"
proc foo(x: typedesc[int]) = echo "typedesc[int]"
template fooT(x: int) = echo "int"
template fooT(x: typedesc[int]) = echo "typedesc[int]"

proc foo[T](x: A[T]) =
  foo(T)   # typedesc[int]  (correct)
  fooT(T)  # typedesc[int]  (correct)

template fooT[T](x: A[T]) =
  foo(T)   # typedescparam.nim(20, 5) Error: internal error: expr(skType); unknown symbol
  fooT(T)  # int  (should be typedesc[int])

var x: A[int]
foo(x)
fooT(x)
```

### LINKED ISSUE #13527: template generics don't bind generic params on instantiation; causing wrong runtime values or crashes
template generics don't bind generic params on instantiation; causing wrong runtime values or crashes

### Example
```nim
when true:
  template getTypStr[T](a: T): string = $T
  echo(getTypStr(1))   # 170141183460469231731687303715884105727; should be: int
  # echo(getTypStr(true))   # true ; should be: bool
  # echo(getTypStr(1.0)) # Error: unhandled exception: cannot extract number from invalid AST node 
  # echo(getTypStr(1u8))   # Error: internal error: expr(skType); unknown symbol
```

### Current Output
170141183460469231731687303715884105727

### Expected Output
```
int
```

### other example: `default`
```nim
  template isDefault[T](a: T): bool = a == default(T) # BUG
  doAssert isDefault(0.0)
```
gives: `Error: type mismatch: got <int> but expected one of: proc default(T: typedesc): T:type`

### workarounds are not good
use `type(a)` instead of `T` works in example above but won't work in more general cases eg:
```nim
  type Foo[M, P] = object
  template getTypStr[T1, T2](a: Foo[T1, T2]): untyped =
    # $T1 # doesn't work because of this issue
    $type(a).M # bad: you have to "know" that `T1` corresponds to `M`
  let a = Foo[int8, bool]()
  let b=getTypStr(a)
  echo (b, $type(b))
```
but then (despite being bad), that doesn't even work with special cases like `seq[T]`, giving `Error: undeclared field: 'T'`
```nim
  template getTypStr[X](a: seq[X]): untyped =
    $type(a).T # doesnt' work for seq[T] even though it's declared like seq[T] !
  var a: seq[int]
  let b=getTypStr(a)
  echo (b, $type(b))

```

So you're forced to use the newly introduced `typetraits.genericParams` (see https://github.com/nim-lang/Nim/pull/13433), which seems overkill for these specific cases.

### note
interestingly, `static[T]` generic params do seem to bind correctly, unlike non-static generic params eg:
```nim
  type Foo[N: static float, T: Ordinal] = object
  template getTypStr[N, T](a: Foo[N, T]): auto = N
  let a = Foo[3.1, bool]()
  doAssert getTypStr(a) == 3.1
```

### root cause for:
* https://github.com/nim-lang/Nim/issues/17413

### Additional Information
* 1056f9ecff60f624522f24e508d0976994bcef80 devel
* related but different from:
  * https://github.com/nim-lang/Nim/issues/6340
  * https://github.com/nim-lang/Nim/issues/11794

### LINKED ISSUE #17240: `T` in `typedesc[T]` treated as value in templates
### Example
```nim
func to(c: int, t: typedesc[float]): t = discard

template converted[I, T](i: seq[I], t: typedesc[T]): seq[T] =
  var result = newSeq[T]()
  result[0] = i[0].to(T)
  result

echo newSeq[int]().converted(float)
```

### Current Output

```
/home/solitude/test.nim(23, 19) Error: type mismatch: got <int, float>
but expected one of:
func to(c: int; t: typedesc[float]): t:type
  first type mismatch at position: 2
  required type for t: typedesc[float]
  but expression 'T' is of type: float

expression: to(newSeq(Natural(0))[0], T)
```

### Expected Output
compiles

### Possible Solution
using typedesc parameter itself like `i[0].to(t)` works.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-03-01
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: d27c0e2982d19ae2203b40a3227c62ea32d11b72
```

### LINKED ISSUE #19076: compiler crash, regression: internal error: expr(skType); unknown symbol when genArg a type parameter
related to  #17617, unimplemented symbol kinds in proc parameters

### Example
```nim
import tables
var tested:Table[string,int]

template `[]`[V](t:Table[string,V],key:string):V =
  echo V
  tables.`[]`(t,key)
discard tested["three"]
```

#### nim 1.6.0, 1.7.1
```
/tmp/mre.nim(15, 15) Error: internal error: expr(skType); unknown symbol
Traceback (most recent call last)
nim.nim                  nim
nim.nim                  handleCmdLine
main.nim                 mainCommand
main.nim                 compileToBackend
main.nim                 commandCompileToC
modules.nim              compileProject
modules.nim              compileModule
passes.nim               processModule
passes.nim               processTopLevelStmt
cgen.nim                 myProcess
cgen.nim                 genTopLevelStmt
cgen.nim                 genProcBody
ccgstmts.nim             genStmts
ccgexprs.nim             expr /tmp/mre.nim(15, 1) nkDiscardStmt
cgen.nim                 initLocExprSingleUse
ccgexprs.nim             expr /tmp/mre.nim(15, 15) nkHiddenDeref
ccgexprs.nim             genDeref
cgen.nim                 initLocExprSingleUse
ccgexprs.nim             expr /tmp/mre.nim(15, 15) nkStmtListExpr
ccgexprs.nim             genStmtListExpr
ccgstmts.nim             genStmts
ccgexprs.nim             expr /tmp/mre.nim(6, 8) nkCommand
ccgexprs.nim             genMagicExpr
ccgexprs.nim             genEcho
cgen.nim                 initLocExpr
ccgexprs.nim             expr /tmp/mre.nim(15, 15) nkBracket
ccgexprs.nim             genArrayConstr
ccgexprs.nim             expr /tmp/mre.nim(15, 15) nkHiddenCallConv
ccgcalls.nim             genCall
ccgcalls.nim             genAsgnCall
ccgcalls.nim             genPrefixCall
ccgcalls.nim             genParams
ccgcalls.nim             genArg
cgen.nim                 initLocExprSingleUse
ccgexprs.nim             expr /tmp/mre.nim(15, 15) nkSym
msgs.nim                 internalErrorImpl
msgs.nim                 liMessage
msgs.nim                 handleError
msgs.nim                 quit
```

#### nim 1.4.8
```
170141183460469231731687303715884105727
0
```

### Expected Output
```
int
0
```

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2021-10-30
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f755e452d2a2c7656f07793b7f01dc654a7c5253
active boot switches: -d:release
```

### LINKED ISSUE #19576: Template findFirst fails to compile, proc with same code works fine
Hi
I wrote a template findFirst() to find the first element in a seq[T] which fulfills a predicate - minimal source attached.
Compilation of template code raises:
```
$ nim c -r nimbug.nim 
Hint: used config file '.../.choosenim/toolchains/nim-1.6.4/config/nim.cfg' [Conf]
Hint: used config file '.../.choosenim/toolchains/nim-1.6.4/config/config.nims' [Conf]
.............................................................
.../nimbug.nim(31, 21) template/generic instantiation of `findFirst` from here
.../nimbug.nim(16, 18) Error: type mismatch: got <RegistryKey>
but expected one of:
proc none(T: typedesc): Option[T]
  first type mismatch at position: 1
  required type for T: typedesc
  but expression 'T' is of type: RegistryKey
proc none[T](): Option[T]
  first type mismatch at position: 1
  extra argument given

expression: none(T)
```

If template code is copied to a "proc" and all "T" replaced by "RegistryKey" (the type), it works well. You can simply check that by changing a const "failure" in the source.

I work with nim-1.6.4

Thanks for help!

Source:
[nimbug.zip](https://github.com/nim-lang/Nim/files/8164957/nimbug.zip)

### LINKED ISSUE #20033: type mismatch error when use generic as typedesc in templates
### Example
```nim
template run[T](): T = default(T)

echo run[int]()
```
https://play.nim-lang.org/#ix=44pk

### Current Output
```
Error: type mismatch: got <int>
but expected one of:
proc default[T](_: typedesc[T]): T
  first type mismatch at position: 1
  required type for _: typedesc[T]
  but expression 'T' is of type: int

expression: default(T)
```

### Expected Output
```
0
```

This work if use proc instead of template

### Workaround
```nim
template run[T](): T = default(typedesc[T])

echo run[int]()
```

Maybe [#2005](https://github.com/nim-lang/Nim/issues/20005) is related.

```
$ nim -v
Nim Compiler Version 1.6.6 [Windows: amd64]
Compiled at 2022-05-05
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by metagn**
fixes #13527, fixes #17240, fixes #6340, fixes #20033, fixes #19576, fixes #19076

When a generic template is called, for the generic parameter in the template body to be substituted with the matching generic parameter, before evaluation the matched generic types are added to the call node as extra arguments. These nodes are `nkSym` nodes of the original generic parameter symbol, with the type of the symbol and thus the node being the matched type. This is irregular in normal code, and when the template tries to use it, it gets treated as some value with the type instead of the type itself.

To prevent this, remove the type field from these nodes which will make regular code semcheck them and provide them with the appropriate type (similar to #20315). Different places in the compiler treat these symbols differently so there is no uniform computation we can do ahead of time.

### CODE REVIEW

**Comment by metagn** [comment]
PR to fix nimPNG which relied on the bug: https://github.com/jangko/nimPNG/pull/83 (merged)

PR to fix nim-lang NESM (seemingly this is the one CI uses): https://github.com/nim-lang/NESM/pull/1

And original NESM: https://github.com/xomachine/NESM/pull/22

<details>

<summary>preemptive NESM patch description</summary>

NESM is really bothersome to patch, the problem is here:

https://github.com/nim-lang/NESM/blob/0861da16e59974eb5c04ee8777adbcf3f8464d75/nesm.nim#L98-L99

The `S` argument provided to the macro used to have an `S` type, now it has a `type S` type, which the macro has to recognize and skip. This also needs to work with and without the bugfix. Not to mention what I linked is the nim-lang org fork and not the original nesm repo, when a PR would ideally go to both as the entire library seems to rely on that template. Just an annoying situation.

</details>

**Comment by metagn** [comment]
It seems like original NESM has been inactive for a long time now, would be nice if someone could merge the patch into the nim-lang repo (https://github.com/nim-lang/NESM/pull/1) for the time being.

File: tests/template/tgenericparam.nim [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+    doAssert getval("abc") == some("def")
+  block: # issue #19076
+    block: # case 1
+      var tested: Table[string,int]
+      template `[]`[V](t:Table[string,V],key:string):untyped =
+        $V
+      doAssert tested["abc"] == "int"
+      template `{}`[V](t:Table[string,V],key:string):untyped =
+        ($V, tables.`[]`(t, key))
+      doAssert (try: tested{"abc"} except: ("not there", 123)) == ("not there", 123)
```
Comment (metagn) [inline tests/template/tgenericparam.nim]: This should be `except KeyError`, will fix after the remaining package PR is merged

**Comment by metagn** [comment]
Sorry, the PR to NESM was not enough, made a new one for the nim-lang repo, locally tested this time: https://github.com/nim-lang/NESM/pull/2 and updated the one for the original repo

**Comment by metagn** [comment]
CI finally passes
