### PR TITLE
Make getSockDomain work with AF_UNIX sockets

### LINKED ISSUE #9055: "unknown socket family in getSockFamily"
I get this error when recieving a socket. (Nim built with latest git)
```
server.nim(9)            server
net.nim(876)             accept
net.nim(802)             acceptAddr
nativesockets.nim(464)   getSockDomain
oserr.nim(66)            raiseOSError
Error: unhandled exception: ; Additional info: "unknown socket family in getSockFamily" [OSError]
```

client.nim
```
import net
let sock = newSocket(AF_UNIX, SOCK_STREAM, IPPROTO_IP)
sock.connectUnix("sock")
sock.send("{'apt_method:'CallLog'}\n")
```

server.nim
```
import net
let sock = newSocket(AF_UNIX, SOCK_STREAM, IPPROTO_IP)
sock.bindUnix("sock")
sock.listen()
while true:
  var client = new(Socket)
  sock.accept(client)
  var output = ""
  output.setLen 32
  client.readLine(output)
  echo "got ", output
  client.close()
```

### PR DESCRIPTION
**Pull request by LemonBoy**
Fixes #9055

### CODE REVIEW

File: lib/pure/nativesockets.nim [hunk 1]
```diff
@@ -456,13 +456,10 @@ proc getSockDomain*(socket: SocketHandle): Domain =
...
     raiseOSError(osLastError())
-  if name.sin6_family.cint == nativeAfInet:
-    result = AF_INET
-  elif name.sin6_family.cint == nativeAfInet6:
-    result = AF_INET6
-  else:
-    raiseOSError(osLastError(), "unknown socket family in getSockFamily")
-
+  try:
+    let domain = toKnownDomain(name.sin6_family.cint).get()
```
Comment (skilchen) [inline lib/pure/nativesockets.nim]: with:
```nim
result = toKnownDomain(name.sin6_family.cint).get()
```
[tests/async/tacceptcloserace.nim](https://github.com/nim-lang/Nim/blob/devel/tests/async/tacceptcloserace.nim) will no longer fail...
