### PR TITLE
fix #16061

### LINKED ISSUE #16061: regression(0.18 => devel): hash(cstring) fails in VM
hash(cstring) fails in VM

### Example
```nim
import std/hashes
proc main() =
  echo hash(cstring"abracadabra")
static: main()
main()
```

### Current Output
lib/pure/hashes.nim(326, 33) Error: cannot generate code for: mSlice
        murmurHash(toOpenArrayByte(x, 0, x.high))

### Expected Output
works

### Additional Information
* fails: devel 1.5.1 b3c3557c338c6cb0992abf9d2d877e927d815ea3
* works: 0.18

### LINKED ISSUE #16542: hash float doesn't work in JS or VM backend
```nim
import hashes

echo hash(0.3456)
```
devel

Output:

```
D:\QQPCmgr\Desktop\Nim\pair.js:265
          var res   = hi_xor_lo_js(hi_xor_lo_js(P0, BigInt(x_486539499) ^ P1), P58);
                                                    ^

RangeError: The number 0.3456 cannot be converted to a BigInt because it is not an integer
```

I will revisit https://github.com/nim-lang/Nim/pull/16403 and make it work for JS backend.

### PR DESCRIPTION
**Pull request by ringabout**
fix #16061

### CODE REVIEW

File: tests/stdlib/thashes.nim [hunk 1]
```diff
@@ -77,8 +77,13 @@ block largeSize: # longer than 4 characters
...
 
 proc main() =
+
+
   doAssert hash(0.0) == hash(0)
-  when sizeof(int) == 8:
+  doAssert hash(cstring"abracadabra") == 97309975
+  doAssert hash(cstring"abracadabra") == hash("abracadabra")
+
+  when sizeof(int) == 8 or defined(js):
```
Comment (xflywind) [inline tests/stdlib/thashes.nim:86]: see follow-up PR: https://github.com/nim-lang/Nim/pull/16549
