### PR TITLE
fix #8671 show helpful msg (lookup symbol, eg iterator) on 'attempting to call undeclared routine' error

### LINKED ISSUE #8671: when Foo (of type iterator) is used where an expression is expected, show useful err msg instead of confusing `Error: attempting to call undeclared routine Foo`
TLDR: see proposal below.

## motivation
the following example shows a regression (became a regression since `forLoopMacros` became controlled by `experimental` flag), see [1]

I DON'T care about this regression (it's easy to fix). What this issue is about is the more general **root cause** causing the error message to be so confusing:
`Error: attempting to call undeclared routine: 'items'` when in fact `items` is declared and works right above (see code), as an iterator.

The same error happens when using an iterator in place where an expression is expected, see `case3` below.

I suspect the root cause is fact that `iterators` use their own namespace, and that, when an expression is expected, an expression involving an iterator will not typecheck (eg in [`items([4, 5, 6])` in case3]  or [`items([1, 2, 3])` in case2 without `.experimental: "forLoopMacros"` ]), because it'll just give a lookup error.

bugs/compiler/t17_items_regression.nim:
```nim
import macros

when defined(case1):
  {.experimental: "forLoopMacros".}

macro enumerate*(x: ForLoopStmt): untyped = 
  expectKind x, nnkForStmt
  result = newStmtList()
  # we strip off the first for loop variable and use
  # it as an integer counter:
  result.add newVarStmt(x[0], newLit(0))
  var body = x[^1]
  if body.kind != nnkStmtList:
    body = newTree(nnkStmtList, body)
  body.add newCall(bindSym"inc", x[0])
  var newFor = newTree(nnkForStmt)
  for i in 1..x.len-3:
    newFor.add x[i]
  # transform enumerate(X) to 'X'
  newFor.add x[^2][1]
  newFor.add body
  result.add newFor
  # echo treeRepr(result)

proc test_enumerate*()=
  # ok
  for a in items([1, 2, 3]):
    echo a

  when defined(case2):
    # Error: attempting to call undeclared routine: 'items', unless -d:case1 is used
    for a, b in enumerate(items([1, 2, 3])):
      echo a, " ", b

  when defined(case3):
    # Error: attempting to call undeclared routine: 'items'
    let badUsage = items([4, 5, 6])
```

[1]
rnim -d:case2 bugs/compiler/t17_iterm_regression.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r -d:case2 bugs/compiler/t17_iterm_regression.nim
/Users/timothee/git_clone/nim/timn/bugs/compiler/t17_iterm_regression.nim(25, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/bugs/compiler/t17_iterm_regression.nim(32, 32) Error: attempting to call undeclared routine: 'items'
      for a, b in enumerate(items([1, 2, 3])):

## proposal

when an expression is expected and a symbol lookup in regular namespace for `Foo` fails (eg `items` above), instead of `Error: attempting to call undeclared routine: 'Foo'`, do this:
* try to lookup in iterator namespace for `Foo` symbol; if it exists, show error:
```
Error: expected an expression but got `Foo`, which is an iterator
```
if it doesn't exist, show old error `Error: attempting to call undeclared routine: 'Foo'`

Likewise in opposite direction, when an iterator is expected but we get something that's in a different namespace.

## Note:
this got me a number of times; I suspect I'm not the only one.

## implementation
* Nim/compiler/procfind.nim ?

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @Araq 
* fixes #8671

### CODE REVIEW

File: compiler/semcall.nim [hunk 1]
```diff
@@ -323,10 +323,16 @@ proc resolveOverloads(c: PContext, n, orig: PNode,
...
+      var msg = ""
       if nfDotField in n.flags and nfExplicitCall notin n.flags:
-        localError(c.config, n.info, errUndeclaredField % considerQuotedIdent(c, f, n).s)
+        msg = errUndeclaredField % ident
       else:
-        localError(c.config, n.info, errUndeclaredRoutine % considerQuotedIdent(c, f, n).s)
+        msg = errUndeclaredRoutine % ident
+      let sym = qualifiedLookUp(c, f, {})
+      if sym != nil:
+        msg &= "; found '$1' of kind '$2' used in wrong context" % [getSymRepr(c.config, sym), $sym.kind]
```
Comment (LemonBoy) [inline compiler/semcall.nim]: The error message is quite verbose and leaks implementation details such as the SK flags.
I'd just modify it so that it says "undeclared <routine/template/macro/...>", basically stringify the filter set in a smart way.

This is also super helpful for unknown pragma names, seeing the " undeclared routine" error always left me puzzled.

Comment (timotheecour) [reply compiler/semcall.nim]: I made the msg a bit less verbose, and special cased `kind skIterator` to `kind iterator` to avoid leaking implementation detail in that case; 

I'd like to keep the relevant information as to where the symbol was found `eg: undeclared_routime.myiter()[declared in undeclared_routime.nim(5, 9)]` and its kind, as these help for understanding what went wrong;

if that's not ok for some reason, please write the exact msg you'd want to see in place of
"attempting to call undeclared routine: 'myiter', found 'undeclared_routime.myiter()[declared in undeclared_routime.nim(5, 9)]' of kind 'iterator'"

**Comment by timotheecour** [comment]
PTAL

File: compiler/semcall.nim (hunk 1 above)
Comment (LemonBoy) [reply compiler/semcall.nim]: Well, you're telling the user that `x` is undeclared and where `x` is declared, the user may not appreciate the irony :)

The same error shows up when you apply a non existent pragma name to something (custom pragmas are templates marked with `{.pragma.}`).

I'd just make it say `attempting to call undeclared iterator/template/routine 'myiter'`.

Including some extra context may also be wrong since you may have a symbol choice and it doesn't make sense to print just one candidate.

Comment (timotheecour) [reply compiler/semcall.nim]: > Well, you're telling the user that x is undeclared and where x is declared, the user may not appreciate the irony :)

fixed

> The same error shows up when you apply a non existent pragma name to something (custom pragmas are templates marked with {.pragma.}).

add test for this

> Including some extra context may also be wrong since you may have a symbol choice and it doesn't make sense to print just one candidate.

fixed: I now show all candidates in case we expected a call (eg proc/template etc) and instead all we get is something that can't be called (eg iterator); test cases demonstrate that.

I find behavior after this PR much friendlier; in complex cases it helps to see what went wrong

File: compiler/semcall.nim [hunk 2]
```diff
@@ -327,10 +328,30 @@ proc resolveOverloads(c: PContext, n, orig: PNode,
...
+      if c.compilesContextId > 0:
+        # we avoid running more diagnostic when inside a `compiles(expr)`, to
+        # errors while running diagnostic (see test D20180828T234921), and
+        # also avoid slowdowns in evaluating `compiles(expr)`.
+        discard
+      else:
+        var o: TOverloadIter
+        var sym = initOverloadIter(o, c, f)
+        while sym != nil:
+          proc toHumanStr(kind: TSymKind): string=
```
Comment (Araq) [inline compiler/semcall.nim]: `: string =`

File: compiler/semcall.nim [hunk 3]
```diff
@@ -327,10 +328,30 @@ proc resolveOverloads(c: PContext, n, orig: PNode,
...
+            result = $kind
+            if result.startsWith "sk": result = result[2..^1].toLowerAscii
```
Comment (Araq) [inline compiler/semcall.nim]: It always starts with ``sk``.

File: compiler/semcall.nim [hunk 4]
```diff
@@ -327,10 +328,30 @@ proc resolveOverloads(c: PContext, n, orig: PNode,
       pickBest(callOp)
 
     if overloadsState == csEmpty and result.state == csEmpty:
+      var msg = ""
```
Comment (Araq) [inline compiler/semcall.nim]: This should be extracted into a helper proc.

File: compiler/semcall.nim [hunk 5]
```diff
@@ -327,10 +328,30 @@ proc resolveOverloads(c: PContext, n, orig: PNode,
...
+        # also avoid slowdowns in evaluating `compiles(expr)`.
+        discard
+      else:
+        var o: TOverloadIter
+        var sym = initOverloadIter(o, c, f)
+        while sym != nil:
+          proc toHumanStr(kind: TSymKind): string=
+            result = $kind
+            if result.startsWith "sk": result = result[2..^1].toLowerAscii
+          msg &= "\n  * found '$1' of kind '$2'" % [getSymRepr(c.config, sym), sym.kind.toHumanStr]
```
Comment (Araq) [inline compiler/semcall.nim]: The compiler doesn't output asterisk lists.

**Comment by Araq** [comment]
Ping.

File: compiler/semcall.nim (hunk 2 above)
Comment (timotheecour) [reply compiler/semcall.nim]: done

File: compiler/semcall.nim (hunk 3 above)
Comment (timotheecour) [reply compiler/semcall.nim]: done

File: compiler/semcall.nim (hunk 4 above)
Comment (timotheecour) [reply compiler/semcall.nim]: done

File: compiler/semcall.nim (hunk 5 above)
Comment (timotheecour) [reply compiler/semcall.nim]: done

[the remark this answers is not in the document]
Comment (timotheecour) [reply compiler/semcall.nim]: I'm not seeing anything redundant in this output:
```nim
undeclared_routime.nim(13, 15) Error: attempting to call routine: 'myiter'
  found 'undeclared_routime.myiter(a: string)[declared in undeclared_routime.nim(10, 9)]' of kind 'iterator'
  found 'undeclared_routime.myiter()[declared in undeclared_routime.nim(11, 9)]' of kind 'iterator'
```

**Comment by timotheecour** [comment]
PTAL, all comments addressed and rebased against devel

File: tests/misc/tnoop.nim [hunk 6]
```diff
@@ -1,7 +1,7 @@
 discard """
   file: "tnoop.nim"
   line: 11
-  errormsg: "attempting to call undeclared routine: 'a'"
+  errormsg: "attempting to call routine: 'a'"
```
Comment (Araq) [inline tests/misc/tnoop.nim]: This error message is worse than before tough (and previously it already was bad). We know that ``a()`` is a routine call, what the user does not know is that there is no such thing here in the scope.

Comment (timotheecour) [reply tests/misc/tnoop.nim]: that's because I wasn't showing full err msg in this test; just added a commit to show full msg; in cmd line it shows as:
```
/Users/timothee/git_clone/nim/Nim/tests/misc/tnoop.nim(12, 2) Error: attempting to call routine: 'a'
  found 'a' of kind 'var'
```
which IMO is better than what was before.

Comment (Araq) [reply tests/misc/tnoop.nim]: Ok, that is acceptable, thanks for your patience.
