### PR TITLE
Fix #6906

### LINKED ISSUE #6906: "not registered in the selector" in asyncfile.close() for something that clearly was registered
This program works on 0.17.2 but fails on devel. I know it is doing some non-portable things that aren't officially sanctioned, but I think there is an actual bug introduced in the changes to asyncdispatch. FWIW, I decided to roll my own asyncExecCmd after getting the same error with asyncproc from https://github.com/cheatfate/asynctools.

```nim
import osproc
import asyncfile
import asyncdispatch

when defined(posix):
  import nativesockets
  import posix

type ProcessResult* = tuple[exitCode: int, output: string]

proc asyncExecCmd*(cmd: string): Future[ProcessResult] =
  var p = startProcess(cmd, options={poStdErrToStdOut, poEvalCommand})

  when defined(posix):
    p.inputHandle.SocketHandle.close()
    assert p.errorHandle == p.outputHandle

    p.outputHandle.SocketHandle.setBlocking(false)
    var outFile = p.outputHandle.int.AsyncFD.newAsyncFile
  else:
    {.error: "TODO stop assuming all FileHandles are socket-like".}


  proc readOuput(): Future[ProcessResult] {.async.} =
    result.output = await outfile.readAll()
    result.exitCode = p.waitForExit()
    outFile.close()

  return readOuput()

when isMainModule:
  var
    hello = asyncExecCmd("echo -n 'hello world'")
    goodbye = asyncExecCmd("echo -n 'goodbye world'")
  echo waitFor goodbye
  echo waitFor hello
```

```
my_async_proc.nim(35)    my_async_proc
asyncdispatch.nim(1204)  waitFor
asyncdispatch.nim(1253)  poll
asyncdispatch.nim(181)   processPendingCallbacks
asyncmacro.nim(34)       cb0
my_async_proc.nim(27)    readOuputIter
asyncfile.nim(497)       close
asyncdispatch.nim(1105)  unregister
ioselectors_epoll.nim(193) unregister
system.nim(3747)         raiseAssert
system.nim(2813)         sysFatal
[[reraised from:
my_async_proc.nim(35)    my_async_proc
asyncdispatch.nim(1612)  waitFor
asyncfutures.nim(243)    read
]]
Error: unhandled exception:
not (pkey.ident == 0) Descriptor 7 is not registered in the selector!
  readOuput's lead up to read of failed Future:
    my_async_proc.nim(35)    my_async_proc
    asyncdispatch.nim(1204)  waitFor
    asyncdispatch.nim(1253)  poll
    asyncdispatch.nim(181)   processPendingCallbacks
    asyncmacro.nim(34)       cb0
    my_async_proc.nim(27)    readOuputIter
    asyncfile.nim(497)       close
    asyncdispatch.nim(1105)  unregister
    ioselectors_epoll.nim(193) unregister
    system.nim(3747)         raiseAssert
    system.nim(2813)         sysFatal [AssertionError]
```

If the problem is that I'm Doing It Wrong, what is the right way to asynchronously get the output from running a command?

### PR DESCRIPTION
**Pull request by cheatfate**

### CODE REVIEW

File: lib/pure/asyncdispatch.nim [hunk 1]
```diff
@@ -1234,7 +1234,7 @@ else:
           processBasicCallbacks(fd, writeList)
           result = true
 
-        if Event.User in events or events == {Event.Error}:
+        if Event.User in events:
```
Comment (dom96) [inline lib/pure/asyncdispatch.nim]: Could we keep this and instead change:

```
            if rLength == 0: 
```

To

```
            if rLength == 0 and Event.User in events: 
```

My concern is that selectors containing only "User" events will silently fail.

Comment (cheatfate) [reply lib/pure/asyncdispatch.nim]: For keys which has only `{Event.Error}` we schedule callbacks 2 times... This is mistake.
For issue sourcecode it sometimes return `{Event.Read, Event.Error}` but sometimes it only gets `{Event.Error}`, and this is not bug of `ioselectors.nim`, epoll returns `EPOLLIN|EPOLLHUP` in some cases and in some cases it only returns `EPOLLHUP` for selected fd.

We already processed this callback here:
```nim
        if Event.Read in events or events == {Event.Error}:
          processBasicCallbacks(fd, readList)
          result = true
```

And we must not schedule it second time here, and you trying to apply patch after callback schedule.

Comment (dom96) [reply lib/pure/asyncdispatch.nim]: What if only custom user events are registered with nothing else? The following code:

```nim
        if Event.Read in events or events == {Event.Error}:
          processBasicCallbacks(fd, readList)
          result = true
```

Won't be executed. No?

Comment (cheatfate) [reply lib/pure/asyncdispatch.nim]: I don't care about custom user events, because i think it must be deprecated or not be part of `asyncdispatch`. In most cases this is just simple pipes and make them different from {Event.Read} was my mistake.

And answer on your question - This code would not be executed because custom user events got market with {Event.User} not {Event.Read}, but if some rare error could happen, then this code will be executed but not real {Event.User} code.

Comment (dom96) [reply lib/pure/asyncdispatch.nim]: Alright, I still have some reservations but I'm gonna merge this nonetheless. Thanks for answering my questions :)
