### PR TITLE
fix RST parsing when no indent after enum.item (fix #17249)

### LINKED ISSUE #17249: regression (1.4 => devel): rst: paragraph incorrectly created on line break, in 1st line of a list
### Example
```nim
Conventions
-----------
1. New stdlib modules should go under `Nim/lib/std/`. The rationale is to require
users to import via `import std/foo` instead of `import foo`, which would cause
potential conflicts with nimble packages. Note that this still applies for new modules
in existing logical directories, e.g.:
use `lib/std/collections/foo.nim`, not `lib/pure/collections/foo.nim`.

2. New module names should prefer plural form whenever possible, e.g.:
`std/sums.nim` instead of `std/sum.nim`. In particular, this reduces chances of conflicts
between module name and the symbols it defines. Furthermore, module names should
use `snake_case` and not use capital letters, which cause issues when going
from an OS without case sensitivity to an OS with it.
```

### Current Output
the bug is that there is a new paragraph after `The rationale is to require` and after `possible, e.g.:`
image

### Expected Output
image

### Additional Information
* bug in 1.5.1 507873be25baa06d7da3c44b0c36d253c850625d
* works in 1.4.4
/cc @a-mr

### PR DESCRIPTION
**Pull request by a-mr**
According to [RST spec](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#enumerated-lists) this fragment
```RST
1. Nim is a statically typed compiled systems
programming language.
```
should be parsed as normal paragraph, not an enum.list, because there is no necessary indentation on the second line.

This PR makes rst.nim handle it in compliance with the spec and also adds a warning with suggestions how to fix it. Original python rst does not emit any warning but I think it's necessary since this behavior confuses people that are used to Markdown.

- also change docs in 2 other places appropriately
- fix that rst2html started numeration of lines from 0 - now it will be from 1 as in all text editors. It should have been done long ago. In this PR it's essential since human interpretation of the warning depends on proper line numbers

cc @narimiran 

EDIT(timotheecour) fix https://github.com/nim-lang/Nim/issues/17249 (needed to put in body otherwise this PR won't show up in the ref'd issue: the link in title isn't enough) /cc @a-mr

### CODE REVIEW

File: compiler/docgen.nim [hunk 1]
```diff
@@ -1347,7 +1347,7 @@ proc commandRstAux(cache: IdentCache, conf: ConfigRef;
   var d = newDocumentor(filen, cache, conf, outExt)
 
   d.isPureRst = true
-  var rst = parseRst(readFile(filen.string), filen.string, 0, 1, d.hasToc,
+  var rst = parseRst(readFile(filen.string), filen.string, 1, 1, d.hasToc,
```
Comment (timotheecour) [inline compiler/docgen.nim]: not sure those line changes are correct (either that or something else should be changed too), because other compiler code might already do the offset:
```nim
ok1

.. asdfasdf::

ok2

```
before PR:
t11958.rst(3, 2) Error: invalid directive: 'asdfasdf'
after PR:
t11958.rst(4, 2) Error: invalid directive: 'asdfasdf'
=> incorrect line number

in future work, maybe we should add a `type LineNumber = distinct int` (1-based) or similar to avoid guesswork everywhere

see client code:
```nim
compiler/msgs.nim:284:10:  result.toLocation(info.filename, info.line, info.column + ColOffset)
compiler/msgs.nim:287:10:  result.toLocation(toMsgFilename(conf, info), info.line.int, info.col.int + ColOffset)
lib/js/jsconsole.nim:13:54:import std/private/since, std/private/miscdollars  # toLocation
lib/js/jsconsole.nim:77:10:    temp.toLocation(info.filename, info.line, info.column + 1)
lib/std/private/miscdollars.nim:1:10:template toLocation*(result: var string, file: string | cstring, line: int, col: int) =
lib/system/assertions.nim:49:10:  result.toLocation(info.filename, info.line, info.column + 1)
lib/system/excpt.nim:241:5:  s.toLocation(f.filename, f.line, 0)
lib/system/jssys.nim:97:12:    result.toLocation($tempFrames[j].filename, tempFrames[j].line, 0)
testament/lib/stdtest/testutils.nim:18:5:    toLocation(msg2, info.filename, info.line, info.column)
```

if possible, make sure the line numbers for rstgen matches the convention used by compiler for processing nim files, that'll lead to the least friction

* maybe also a test could be added to expect error msg has correct line numbers

Comment (a-mr) [reply compiler/docgen.nim]: I checked the case of directives thoroughly: it happens because `getDirective` https://github.com/nim-lang/Nim/blob/6c1931747aece5f95f6d67876a558d05940d4547/lib/packages/docutils/rst.nim#L1282 
advances `p.idx` to the next line.

I fixed line in `rstMessage`. Also I remembered clearly that indeed all elements errors/warnings had the line shifted by `-1`, except directives, that had it right.

Your 2 other ideas are good as usual... Especially it's worth checking line numbers in the test. Currently we have a more basic problem that I haven't learned how to handle `rstMessage` invocation in test, it just throws `AssertionDeffect` by some reason, which is ridiculous :-(

**Comment by a-mr** [comment]
Digging into line numbers reporting I observed that columns are also wrong but this time they are shifted by +1 (it was not clear  because columns are much more often reported **completely** incorrectly because of more `p.idx` movement sensitivity).

It's because Nim global error/warning reporting adds `ColOffset=1`, while there is no such addition for lines. So before rst was parsed with initial `line=0, column=1` but it should be `line=1, column=0`.

**Comment by timotheecour** [comment]
let's followup in https://github.com/timotheecour/Nim/issues/638 for how to solve this aspect cleanly throughout nim compiler in followup work

File: lib/packages/docutils/rst.nim [hunk 2]
```diff
@@ -1937,13 +1945,32 @@ proc parseEnumList(p: var RstParser): PRstNode =
...
+    let j = tokenAfterNewline(p, start=p.idx+1)
+    if p.tok[j].kind notin {tkIndent, tkEof} and
+        p.tok[j].col < p.tok[p.idx+wildToken[w]].col and
+        (p.tok[j].col > col or
+          (p.tok[j].col == col and not match(p, j, wildcards[w]))):
+      # check `result == nil` to avoid duplication of warning since for
+      # subsequent enum.items parseEnumList will be called second time
+      if result == nil:
+        let n = p.line + p.tok[j].line
+        rstMessage(p, mwRstStyle, ("\n  not enough indentation on line $2" &
```
Comment (timotheecour) [inline lib/packages/docutils/rst.nim]: use multiline `""" ... """` instead, more readable

Comment (a-mr) [reply lib/packages/docutils/rst.nim]: OK. Though I don't like to use `"""` without `dedent` — and it's not available.

Comment (timotheecour) [reply lib/packages/docutils/rst.nim]: * what do you mean? it works if i add dedent
* also, it's cleaner to not add `"\n" &`, this works:
```nim
        let msg = """

          not enough indentation on line $2
              (if it's continuation of enumeration list),
          or no blank line after line $1 (if it should be the next paragraph),
          or no escaping \ at the beginning of line $1
              (if lines $1..$2 are a normal paragraph, not enum. list)""".dedent
```

(but ok if you prefer `"\n" &`)

Comment (a-mr) [reply lib/packages/docutils/rst.nim]: 1. I mean bootstrap problem in #16699, which you root-caused as #16646.
2. yes, I prefer to save 1 line of code

Comment (a-mr) [reply lib/packages/docutils/rst.nim]: just added `dedent` and tried to bootstrap, the error is still there:
```
rst.nim(1972, 3) template/generic instantiation of `checkAfterNewline` from here
rst.nim(1964, 26) Error: undeclared identifier: 'dedent'
FAILURE
```

Comment (timotheecour) [reply lib/packages/docutils/rst.nim]: can you change strutils.dedent as follows:
```nim
since (1, 3):
  func indentation*(s: string): Natural = ...
  func dedent*(s: string, count: Natural = indentation(s)): string {.rtl, extern: "nsuDedent".} = ...
```

(see workaround mentioned in https://github.com/nim-lang/Nim/issues/16646)
(if you prefer i can do a PR for that, but might as well do it in your PR)

Comment (a-mr) [reply lib/packages/docutils/rst.nim]: if you are OK with such workarounds let us try it: pushed to this PR.

Also because syntax `dedent*(s: string, count: Natural = indentation(s))` does not work for bootstrap, I had to split that `dedent` to `dedent(s, count)` and `dedent(s)`

File: lib/pure/strutils.nim [hunk 3]
```diff
@@ -1438,43 +1438,49 @@ func unindent*(s: string, count: Natural = int.high,
...
+    runnableExamples:
+      let x = """
+        Hello
+          There
+      """.dedent()
+
+      doAssert x == "Hello\n  There\n"
+    let b = a
+    let i = indentation(b)
+    dedent(a, i)
```
Comment (timotheecour) [inline lib/pure/strutils.nim]: why not simply:
```suggestion
    dedent(a, indentation(a))
```
?
(it's not a template, no risk of multiple evaluation bug)

also, `proc dedent*(a: string): string =` should be {.inline.}

File: lib/packages/docutils/rst.nim (hunk 2 above)
Comment (Clyybber) [reply lib/packages/docutils/rst.nim]: The workarounds around dedent are not worth it IMO. If you want just use dedent and provide count explicitly.

File: lib/pure/strutils.nim (hunk 3 above)
Comment (a-mr) [reply lib/pure/strutils.nim]: Thank you, I added this change. (from my name — sorry, I did not notice button "commit suggestion". I'll be more mindful in the future)

File: lib/packages/docutils/rst.nim (hunk 2 above)
Comment (a-mr) [reply lib/packages/docutils/rst.nim]: @Clyybber if you mean omitting separate proc `dedent(s)` then we need it anyway, it's the default option, it's usually being used without second argument. So we can't declare only `dedent(s, count)`.

File: lib/packages/docutils/rstgen.nim [hunk 4]
```diff
@@ -1506,7 +1506,7 @@ proc rstToHtml*(s: string, options: RstParseOptions,
   initRstGenerator(d, outHtml, config, filen, options, myFindFile,
                    rst.defaultMsgHandler)
   var dummyHasToc = false
-  var rst = rstParse(s, filen, 0, 1, dummyHasToc, options)
+  var rst = rstParse(s, filen, line=1, column=0, dummyHasToc, options)
```
Comment (timotheecour) [inline lib/packages/docutils/rstgen.nim]: DRY: line=1, column=0 is used 3 times.
insted, define:
```nim
const LineRstDefault = 1
const ColRstDefault = 0
```
somewhere and reuse it in those places
(in future we can refactor so that nim uses those constants (renamed))

File: lib/packages/docutils/rst.nim [hunk 5]
```diff
@@ -1937,13 +1945,32 @@ proc parseEnumList(p: var RstParser): PRstNode =
...
     wildIndex: array[0..5, int] = [1, 0, 0, 1, 0, 0]
       # position of enumeration sequence (number/letter) in enumerator
-  result = newRstNodeA(p, rnEnumList)
   let col = currentTok(p).col
   var w = 0
   while w < wildcards.len:
     if match(p, p.idx, wildcards[w]): break
     inc w
   assert w < wildcards.len
+  template checkAfterNewline =
```
Comment (timotheecour) [inline lib/packages/docutils/rst.nim]: turn into a (nested) proc to avoid code bloat
(and avoids hiding hidden control flow like return inside the template; this can be done a bit differently)

File: lib/pure/strutils.nim (hunk 3 above)
Comment (timotheecour) [reply lib/pure/strutils.nim]: >  I'll be more mindful in the future

not a concern, the commits get squashed when the PR is merged anyways; I also do the same sometimes so I can keep rebasing instead of merging

File: lib/packages/docutils/rst.nim (hunk 2 above)
Comment (Clyybber) [reply lib/packages/docutils/rst.nim]: I mean calling dedent or unindent with an explicit count param, like so:
```nim
        let msg = """

          not enough indentation on line $2
              (if it's continuation of enumeration list),
          or no blank line after line $1 (if it should be the next paragraph),
          or no escaping \ at the beginning of line $1
              (if lines $1..$2 are a normal paragraph, not enum. list)""".dedent(10)
```

Comment (timotheecour) [reply lib/packages/docutils/rst.nim]: this is fragile, people should be able to re-indent code without worrying about breaking semantics

Comment (Clyybber) [reply lib/packages/docutils/rst.nim]: Then let's simply not use dedent here, it's not a big deal.

**Comment by a-mr** [comment]
CI failure is unrelated.

Test improvements will be done in a follow-up PR.

File: lib/packages/docutils/rst.nim [hunk 6]
```diff
@@ -1937,13 +1948,33 @@ proc parseEnumList(p: var RstParser): PRstNode =
...
     wildIndex: array[0..5, int] = [1, 0, 0, 1, 0, 0]
       # position of enumeration sequence (number/letter) in enumerator
-  result = newRstNodeA(p, rnEnumList)
   let col = currentTok(p).col
   var w = 0
   while w < wildcards.len:
     if match(p, p.idx, wildcards[w]): break
     inc w
   assert w < wildcards.len
+  proc checkAfterNewline(p: RstParser, report: bool): bool =
```
Comment (timotheecour) [inline lib/packages/docutils/rst.nim:1957]: regression:
```
1. hello 1
1. hello 2
1. hello 3
zook
```

before PR:
image


after PR:
image

the warning generated is good, but the output is bad (text shouldn't be omitted)

File: lib/packages/docutils/rstgen.nim [hunk 7]
```diff
@@ -1506,7 +1506,8 @@ proc rstToHtml*(s: string, options: RstParseOptions,
   initRstGenerator(d, outHtml, config, filen, options, myFindFile,
                    rst.defaultMsgHandler)
   var dummyHasToc = false
-  var rst = rstParse(s, filen, 0, 1, dummyHasToc, options)
+  var rst = rstParse(s, filen, line=LineRstInit, column=ColRstInit,
```
Comment (timotheecour) [inline lib/packages/docutils/rstgen.nim:1509]: the line error reporting is incorrect:
```
1. hello 1
1. hello 2
1. hello 3
zook
```

gives:
```
t11995.rst(3, 1) Warning: RST style:
  not enough indentation on line 4
      (if it's continuation of enumeration list),
  or no blank line after line 3 (if it should be the next paragraph),
  or no escaping \ at the beginning of line 3
      (if lines 3..4 are a normal paragraph, not enum. list) [warnRstStyle]

```
I'd expect:
t11995.rst(4, 1) Warning: RST style:
not
t11995.rst(3, 1) Warning: RST style:

ok to leave as TODO for future work though

File: lib/packages/docutils/rst.nim [hunk 8]
```diff
@@ -1937,13 +1948,34 @@ proc parseEnumList(p: var RstParser): PRstNode =
...
+    let j = tokenAfterNewline(p, start=p.idx+1)
+    if p.tok[j].kind notin {tkIndent, tkEof} and
```
Comment (timotheecour) [inline lib/packages/docutils/rst.nim:1959]: getting there, it's almost perfect...

another regression:


```
1. hello 1
1. hello 2
   foo 2
1. hello 3
   foo 3
   1. sub1
   1. sub2
   1. sub3
   zook5
1. hello 4
1. hello 5
1. hello 6
 zook6
1. hello 7

1. hello 8


1. hello 9

1. hello 10

separator

1. hello 11
1. hello 12
```

## before PR
image

## after PR
image

* sub3 gets displaced
* there shouldn't be an interruption in numbering form `1. hello 5` to `1. hello 6`

but this could potentially be addressed in future PR, wdyt ?

Comment (a-mr) [reply lib/packages/docutils/rst.nim:1959]: Everything is working as expected here.

- sub3 is not displaced. It's just parsed as normal paragraph according to RST specification because there is zook5 without indent after it
- the same here: "1. hello 6" was parsed as a normal paragraph and zook6 became a block quote because it's indented by 1

And the warning is issued in both cases, so it looks ok to me.

rst2html.py does the same thing if you change `1`s to `#`s.

Also note that presence of auto-numerator `1` does not mean that it's a real "markdown mode".

Comment (a-mr) [reply lib/packages/docutils/rst.nim:1959]: I think it's possible to implement also markdown-style enumeration list parsing because it's basically just relaxation of the RST kind. But it would be another task.

**Comment by timotheecour** [comment]
`nim-lang.Nim (packages Linux_i386) Failing after 58s — packages Linux_i386 failed`
failed so i restarted it but it failed again (quickly, after 1mn)

can you rebase against devel maybe?

not sure if it relates to your PR

https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/14075/logs/38

```
2021-03-10T21:10:24.0269335Z CC: stdlib_assertions.nim
2021-03-10T21:10:24.0288424Z CC: stdlib_dollars.nim
2021-03-10T21:10:24.1410956Z Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3  -I/home/vsts/work/1/s/lib -I/home/vsts/work/1/s -o /home/vsts/.cache/nim/koch_d/stdlib_assertions.nim.c.o /home/vsts/.cache/nim/koch_d/stdlib_assertions.nim.c' failed with exit code: 1
2021-03-10T21:10:24.1412125Z 
2021-03-10T21:10:24.1412666Z In file included from /usr/include/limits.h:25:0,
2021-03-10T21:10:24.1413573Z                  from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:168,
2021-03-10T21:10:24.1414497Z                  from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/syslimits.h:7,
2021-03-10T21:10:24.1415407Z                  from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:34,
2021-03-10T21:10:24.1416047Z                  from /home/vsts/work/1/s/lib/nimbase.h:268,
2021-03-10T21:10:24.1416680Z                  from /home/vsts/.cache/nim/koch_d/stdlib_assertions.nim.c:9:
2021-03-10T21:10:24.1417570Z /usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
2021-03-10T21:10:24.1418154Z compilation terminated.
2021-03-10T21:10:24.1472789Z ##[error]Bash exited with code '1'.
2021-03-10T21:10:24.1576588Z ##[section]Finishing: Build koch
```

(refs https://github.com/nim-lang/Nim/issues/3123#issuecomment-122125096)
refs:
* sudo apt-get install g++-multilib https://stackoverflow.com/questions/51765069/fatal-error-sys-cdefs-h-no-such-file-or-directory-while-compiling-openssl-1-1
* libc6-dev-i386 https://itectec.com/ubuntu/ubuntu-fatal-error-sys-cdefs-h-no-such-file-or-directory/

**Comment by timotheecour** [comment]
good news, i have same error in another PR i just rebased (https://github.com/nim-lang/Nim/pull/17304) so this isn't related to your PR (=> issue https://github.com/nim-lang/Nim/issues/17325)

**Review by timotheecour — APPROVED** [review]
LGTM, remaining points can be addressed in followup work

**Comment by timotheecour** [comment]
(closed/re-opened so that bugfix https://github.com/nim-lang/Nim/pull/17327 is included)
