### PR TITLE
fix #20253

### LINKED ISSUE #20253: `{.requiresInit.}` has several bugs
### What happened?

this compiles fine, even though it should probably error when compiling initMeow
```nim
type Meow {.requiresInit.} = object 
  init: bool

proc initMeow(): Meow =
  discard

proc main() =
  var theMeow = initMeow()
  echo theMeow.init
main()
```

on the other hand the following does not compile, even though the manual says requiresInit "does a control flow analysis to prove the variable has been initialized and does not rely on syntactic properties"
```nim
type Meow {.requiresInit.} = object 
  init: bool

proc main() =
  var theMeow: Meow
  theMeow.init = true
  echo theMeow.init
main()
```

Also new and setLen both bypass requiresInit
```nim
type Meow {.requiresInit.} = object 
  init: bool

proc main() =
  var theMeow = new Meow
  echo theMeow.init
```

this last bug is the same as #19139 but the issue isn't that it crashes and it shouldn't crash but that the example compiles at all, new should be considered to default initialize things, not initialize them fully.

setLen is even more nasty, it doesn't have a way to initialize things at all.

### Nim Version

﻿Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2022-08-20
Copyright (c) 2006-2022 by Andreas Rumpf

active boot switches: -d:release

### Current Standard Output Logs

_No response_

### Expected Standard Output Logs

_No response_

### Possible Solution

given all these issues requiresInit is pretty useless, and doesn't manage to do what the various "required to initialize" constructs in other languages do. Personally I think it might be better to make requiresInit just require an explicit initializer and expand it to flow based checks later, given that the flow based checks don't really work now anyway.

Additionally the gaps in what's considered initialization should be fixed. Ironically for returning an uninitialized result the "can not prove result is initialized" warning fires off, but the requiresInit checks still pass.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bung87**
fix #20253

refs: https://github.com/nim-lang/Nim/issues/6557

well, `requiresInit` it's a conflict concept when work with json fields

refs: https://github.com/nim-lang/nimble/pull/1051

### CODE REVIEW

**Comment by bung87** [comment]
CI fails unrelated.

File: koch.nim [hunk 1]
```diff
@@ -10,7 +10,7 @@
 #
 
 const
-  NimbleStableCommit = "afd03bc000f4013c48f52381728327dabfccfc4c" # master
+  NimbleStableCommit = "7efb226ef908297e8791cade20d991784b4e8bfc" # master
```
Comment (Araq) [inline koch.nim]:
```suggestion
  NimbleStableCommit = "afd03bc000f4013c48f52381728327dabfccfc4c" # master
```

Comment (ringabout) [reply koch.nim]: Either bumping nimble or reverting this PR should make CI green.

Comment (ringabout) [reply koch.nim]: => https://github.com/nim-lang/Nim/pull/21259
