### PR TITLE
ambiguous identifier resolution

### LINKED ISSUE #22841: Unittest breaks if proc name on/off defined in same module
### Description

There is an error if a proc named `on` or `off` is defined in the same module as `unittest` is used.

```nim
import unittest

proc on() =
    discard

suite "some suite":
    test "some test":
        discard
```

### Nim Version

`Nim Compiler Version 2.1.1 [Windows: amd64]`

0d4b3ed18edff5ae098be842a986cb32de651fbf

This occurs in 2.0.0 as well.

### Current Output

```text
test_on.nim(6, 1) template/generic instantiation of `suite` from here
nim_tui\test_on.nim(7, 5) template/generic instantiation of `test` from here 
nim-#devel\lib\pure\unittest.nim(555, 34) Error: type mismatch: got 'None' for 'on' but expected 'bool'
```

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### LINKED ISSUE #23002: Ambiguous identifier in pragma
### Description

testit2.nim:
```nim
proc on*(): void = discard
```

testit.nim
```nim
import testit2

proc test() =
  {.warning[ProveInit]: on.}

test()
```

inside the pragma, the evaluation should be looking for a `bool`, not a `proc` - yet, the proc is matched (which in the real world example has more arguments)

### Nim Version

1.6.16, devel

### Current Output

```text
testit.nim(4, 25) Error: ambiguous identifier: 'on' -- use one of the following:
  system.on: bool
  testit2.on: proc (){.noSideEffect, gcsafe, locks: 0.}
```

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
fixes #23002, fixes #22841, refs comments in #23097

When an identifier is ambiguous in scope (i.e. multiple imports contain symbols with the same name), attempt resolving it through type inference (by creating a symchoice).  To do this efficiently, `qualifiedLookUp` had to be broken up so that `semExpr` can access the ambiguous candidates directly (now obtained directly via `lookUpCandidates`). 

This fixes the linked issues, but an example like:

```nim
let on = 123

{.warning[ProveInit]: on.}
```

will still fail, since `on` is unambiguously the local `let` symbol here (this is also true for `proc on` but `proc` symbols generate symchoices anyway).

Type symbols are not considered to not confuse the type inference. This includes the change in sigmatch, up to this point symchoices with nonoverloadable symbols could be created, they just wouldn't be considered during disambiguation. Now every proper symbol except types are considered in disambiguation, so the correct symbols must be picked during the creation of the symchoice node. I remember there being a violating case of this in the compiler, but this was very likely fixed by excluding type symbols as CI seems to have found no issues.

The pure enum ambiguity test was disabled because ambiguous pure enums now behave like overloadable enums with this behavior, so we get a longer error message for `echo amb` like `type mismatch: got <MyEnum | OtherEnum> but expected T`

### CODE REVIEW

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -3026,25 +3034,54 @@ proc semExpr(c: PContext, n: PNode, flags: TExprFlags = {}, expectedType: PType
...
       for f in expected.n:
         if f.kind == nkSym and f.sym.name.id == nameId:
           s = f.sym
           break
     if s == nil:
-      let checks = if efNoEvaluateGeneric in flags:
-          {checkUndeclared, checkPureEnumFields}
-        elif efInCall in flags:
-          {checkUndeclared, checkModule, checkPureEnumFields}
+      var filter = {low(TSymKind)..high(TSymKind)}
```
Comment (Araq) [inline compiler/semexprs.nim]: Use a helper proc.

File: compiler/semexprs.nim [hunk 2]
```diff
@@ -2997,6 +2998,53 @@ proc semPragmaStmt(c: PContext; n: PNode) =
   else:
     pragma(c, c.p.owner, n, stmtPragmas, true)
 
+proc resolveIdent(c: PContext, ident: PIdent, s: var PSym, n: PNode,
+                  flags: TExprFlags, expectedType: PType): PNode =
```
Comment (Araq) [inline compiler/semexprs.nim]: So ... it returns what exactly? And when does it overwrite the `s` parameter? Convoluted.

Comment (metagn) [reply compiler/semexprs.nim]: I swapped `s` and the result value, and made it so only n's info is needed. Every parameter seems to be needed though, not sure how to get this cleaner.

Comment (metagn) [reply compiler/semexprs.nim]: Now merged `n`/`info` and `ident` into the same parameter (just `n`), and renamed to `resolveIdentToSym`. Hopefully this is clearer.

**Comment by Araq** [comment]
I'm merging this now but in a followup PR the manual needs to be patched and describe in detail how symbol lookups now interact with overloading etc.
