### PR TITLE
Fixes #25710 - nimsuggest outline misses methods

### LINKED ISSUE #25710: nimsuggest --v3 and --v4 "outline" output does not list methods
### Nim Version

devel as well as past releases.

### Description

To reproduce:
```
nimsuggest --v3 --stdin <project_file.nim>
> outline <file_with_method_declarations.nim>
```

### Current Output

```text
Names and locations of the definitions of types, procs, macros, templates, etc. But no methods.
```

### Expected Output

```text
Names and locations of all definitions, including methods.
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lou15b**
This adds methods to the list generated by the `outline` command for  `nimsuggest --v3` and `nimsuggest --v4`.
The test file `tv3_outline.nim` was also updated to include a `skMethod` line in the expected output.

### CODE REVIEW

File: nimsuggest/nimsuggest.nim [hunk 1]
```diff
@@ -1042,7 +1042,7 @@ proc iterateOutlineNodes(graph: ModuleGraph, n: PNode, infoPairs: SuggestFileSym
     if symData != nil and symData.sym.kind == skEnumField and symData.info.exactEquals(symData.sym.info):
        let sym = symData.sym
        graph.suggestResult(sym, sym.info, ideOutline, n.endInfo.line, n.endInfo.col)
-  elif (n.kind in {nkFuncDef, nkProcDef, nkTypeDef, nkMacroDef, nkTemplateDef, nkConverterDef, nkEnumFieldDef, nkConstDef}):
+  elif (n.kind in {nkFuncDef, nkProcDef, nkMethodDef, nkTypeDef, nkMacroDef, nkTemplateDef, nkConverterDef, nkEnumFieldDef, nkConstDef}):
```
Comment (Araq) [inline nimsuggest/nimsuggest.nim]:
```suggestion
  elif (n.kind in {nkFuncDef, nkProcDef, nkMethodDef, nkIteratorDef, nkTypeDef, nkMacroDef, nkTemplateDef, nkConverterDef, nkEnumFieldDef, nkConstDef}):
```
