### PR TITLE
fixes #13314

### LINKED ISSUE #13314: Segfault with closure on arc
This segfaults with --gc:arc :

### Example
```nim
type
  O = object
    v: int
  R = ref object
    w: int

proc `$`(r: R): string = $r[]

proc main =
  # var t1 = 1
  # var t2 = O(v: 2)
  # var t3 = [3]
  # var t4 = @[4]
  var t5 = R(w: 5)

  var execute = proc () =
    # echo t1
    # echo t2
    # echo t3
    # echo t4
    echo t5

  execute()

  # t1 = -1
  # t2 = O(v: -2)
  # t3 = [-3]
  # t4 = @[-4]
  t5.w = -5

  execute()

main()
```

### Current Output
```
(w: 5)
Traceback (most recent call last)
/home/clyybber/projects/tests/megusto.nim(33) megusto
/home/clyybber/projects/tests/megusto.nim(29) main
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
(w: 5)
(w: -5)
```

The commented out parts crash only on arc too, but I'm not sure if they are supposed to work.
@Araq, @cooldome What do you think?

```
$ nim -v
#devel
```

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

File: compiler/dfa.nim [hunk 1]
```diff
@@ -609,15 +609,16 @@ proc aliases*(obj, field: PNode): bool =
...
+    ins.n.aliases(loc) or loc.aliases(ins.n)
+  # We can come here if loc is 'x.f' and ins.n is 'x' or the other way round.
   # use x.f;  question: does it affect the full 'x'? No.
   # use x; question does it affect 'x.f'? Yes.
 
 proc defInstrTargets*(ins: Instr; loc: PNode): bool =
   assert ins.kind == def
-  sameTrees(ins.n, loc) or
-  ins.n.aliases(loc) # We can come here if loc is 'x.f' and ins.n is 'x' or the other way round.
+  result = sameTrees(ins.n, loc) or ins.n.aliases(loc)
```
Comment (Clyybber) [inline compiler/dfa.nim:620]: ~~Weird, when I tried to fix this, this didn't work..~~ 
EDIT: Nevermimd, missed the `gen` call.
Now use/defInstrTargets can be one and the same \o/
