### PR TITLE
fix #10678

### LINKED ISSUE #10678: `set[` in proc definition crashes compiler
### Example (run with `nim check`)
```nim
proc a(b: int, c: set[)
```

### Current Output
```
t.nim(1, 23) Error: expression expected, but found ')'
t.nim(2, 1) Error: expected: ']', but got: '[EOF]'
t.nim(2, 1) Error: expected: ')', but got: '[EOF]'
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected
Not crashing

### Additional Information
```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-02-14
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 3520253a09cb8f32df834e619c7435092a370e9d
active boot switches: -d:release -d:useLinenoise
```

### PR DESCRIPTION
**Pull request by krux02**
fix #10678

### CODE REVIEW

File: compiler/semtypes.nim [hunk 1]
```diff
@@ -145,7 +145,7 @@ proc semEnum(c: PContext, n: PNode, prev: PType): PType =
 
 proc semSet(c: PContext, n: PNode, prev: PType): PType =
   result = newOrPrevType(tySet, prev, c)
-  if sonsLen(n) == 2:
+  if sonsLen(n) == 2 and n.sons[1].kind != nkEmpty:
```
Comment (LemonBoy) [inline compiler/semtypes.nim]: `illFormedAst` is better here since the AST is completely wrong.
Also, missing test case.

Comment (krux02) [reply compiler/semtypes.nim]: well the written ast is completely wrong. What the parser generates from it is not that wrong at all. The generated AST just misses a type expression.
