### PR TITLE
`nim doc -r main` and `nim rst2html -r main` now call openDefaultBrowser

### LINKED ISSUE #13974: nim -r option must be valid only when compiling
Nim compiler `-r` option can be used with `doc` command, for example, and will produce an error message.

### Example
```sh
$ nim doc -r tutu
...
Hint: 16297 LOC; 0.202 sec; 15.918MiB peakmem; Debug build; proj: ./tutu; out: ./tutu.html [SuccessX]
Hint: ./tutu.html  [Exec]
sh: 1: ./tutu.html: Permission denied
Error: execution of an external program failed: './tutu.html '
```

### Expected Output
```sh
$ nim doc -r tutu
Invalid option `-r`. Can be used only with commands `c`, `compile`, `js`, `cc`...
TO BE COMPLETED WHERE VALID.
```

### Possible Solution

* Don't write anything!
* Don't use `-r`.

```
$ nim -version
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by timotheecour**
* `nim doc -r main` and `nim rst2html -r main` now call openDefaultBrowser
* fix https://github.com/nim-lang/Nim/issues/13974
* first step towards https://github.com/timotheecour/Nim/issues/165

### CODE REVIEW

File: compiler/nim.nim [hunk 1]
```diff
@@ -86,11 +87,21 @@ proc handleCmdLine(cache: IdentCache; conf: ConfigRef) =
...
+    of cmdDoc, cmdRst2html:
+      if conf.arguments.len > 0:
+        # reserved for future use
+        rawMessage(conf, errGenerated, "'$1 cannot handle arguments" % [$conf.cmd])
+      openDefaultBrowser($output)
+    of cmdCompileToC, cmdCompileToCpp, cmdCompileToOC:
       execExternalProgram(conf, ex & ' ' & conf.arguments)
+    else:
+      # support as needed
+      doAssert false, "'$1 cannot handle --run" % [$conf.cmd]
```
Comment (Clyybber) [inline compiler/nim.nim]: Don't use `doAssert false` here use rawMessage instead.

Comment (timotheecour) [reply compiler/nim.nim]: oups fixed
