### PR TITLE
fixes #23129; fixes generated hooks raise unlisted Exception, which never raise

### LINKED ISSUE #23129: std/isolation raises warning about how =destroy may raise unlisted Exception `Exception`
### Description

In a package of mine that provides an abstraction over communication via Channels I offer support for the threading package.
It uses std/isolate to isolate messages for memory-safe message passing.

When using it, std/isolate raises a warning that spams the terminal, obscuring other, potentially more useful warnings. 

Here a small example that will trigger the warning
```nim
import threading/channels

type   
  Thing = object
    name: string

var chan: Chan[Thing] = newChan[Thing](50)

proc send(x: string) =
  let wrapper = Thing(name: x)
  discard chan.trySend(wrapper)

send("la")
```

The problem appears to be std/isolation calling destroy hooks, which the effects system somehow assumes may raise `Exception`, which *seems* incorrect.

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

This was also tested and reproduced with:

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-12-26
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1324d2e04cb11aaa96e9ba9efc69aee47ed6c1d8
active boot switches: -d:release

### Current Output

```text
*  Executing task: nim r -f -d:warnings:on --path:~/.nimble/ src/playground.nim 

Hint: used config file '/home/philipp/.choosenim/toolchains/nim-2.0.0/config/nim.cfg' [Conf]
Hint: used config file '/home/philipp/.choosenim/toolchains/nim-2.0.0/config/config.nims' [Conf]
Hint: used config file '/home/philipp/dev/playground/config.nims' [Conf]
..........................................................................
/home/philipp/dev/playground/src/playground.nim(11, 15) template/generic instantiation of `trySend` from here
/home/philipp/.nimble/pkgs2/threading-0.2.0-3cd4360369b8abf1c53ddfd49ea8aef70208658c/threading/channels.nim(277, 21) template/generic instantiation of `isolate` from here
/home/philipp/.choosenim/toolchains/nim-2.0.0/lib/std/isolation.nim(37, 14) template/generic instantiation of `=destroy` from here
/home/philipp/.choosenim/toolchains/nim-2.0.0/lib/std/isolation.nim(27, 61) template/generic instantiation from here
/home/philipp/.choosenim/toolchains/nim-2.0.0/lib/std/isolation.nim(29, 13) Warning: `=destroy`(dest.value) can raise an unlisted exception: Exception [Effect]
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/system/exceptions.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/private/digitsutils.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/assertions.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/system/dollars.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/system.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/isolation.nim
CC: ../../../.nimble/pkgs2/threading-0.2.0-3cd4360369b8abf1c53ddfd49ea8aef70208658c/threading/channels.nim
CC: playground.nim
Hint:  [Link]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
38173 lines; 0.704s; 46.691MiB peakmem; proj: /home/philipp/dev/playground/src/playground.nim; out: /home/philipp/.cache/nim/playground_d/playground_F58C1F9A60B5076B8646BFA43FAABD5016F8043C [SuccessX]
```

### Expected Output

```text
*  Executing task: nim r -f -d:warnings:on --path:~/.nimble/ src/playground.nim 

Hint: used config file '/home/philipp/.choosenim/toolchains/nim-2.0.0/config/nim.cfg' [Conf]
Hint: used config file '/home/philipp/.choosenim/toolchains/nim-2.0.0/config/config.nims' [Conf]
Hint: used config file '/home/philipp/dev/playground/config.nims' [Conf]
..........................................................................
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/system/exceptions.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/private/digitsutils.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/assertions.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/system/dollars.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/system.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/isolation.nim
CC: ../../../.nimble/pkgs2/threading-0.2.0-3cd4360369b8abf1c53ddfd49ea8aef70208658c/threading/channels.nim
CC: playground.nim
Hint:  [Link]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
38173 lines; 0.704s; 46.691MiB peakmem; proj: /home/philipp/dev/playground/src/playground.nim; out: /home/philipp/.cache/nim/playground_d/playground_F58C1F9A60B5076B8646BFA43FAABD5016F8043C [SuccessX]
```

### Possible Solution

_No response_

### Additional Information

Elegantbeef pointed me towards the destroy hooks in [system.nim](https://github.com/nim-lang/Nim/blob/1324d2e04cb11aaa96e9ba9efc69aee47ed6c1d8/lib/system.nim#L369) and that this might be resolved by adding the `raises: []` to them.
Testing this locally I can currently not confirm this to be the solution.

### PR DESCRIPTION
**Pull request by ringabout**
fixes #23129

### CODE REVIEW

File: compiler/liftdestructors.nim [hunk 1]
```diff
@@ -1179,7 +1179,12 @@ proc produceSym(g: ModuleGraph; c: PContext; typ: PType; kind: TTypeAttachedOp;
         # bug #19205: Do not forget to also copy the hidden type field:
         genTypeFieldCopy(a, typ, result.ast[bodyPos], d, src)
 
-  if not a.canRaise: incl result.flags, sfNeverRaises
+  if not a.canRaise:
+    incl result.flags, sfNeverRaises
+    result.ast[pragmasPos] = newNodeI(nkPragma, info)
+    result.ast[pragmasPos].add newTree(nkExprColonExpr,
+        newIdentNode(c.cache.getIdent("raises"),  info), newNodeI(nkBracket, info))
```
Comment (ringabout) [inline compiler/liftdestructors.nim]:
```suggestion
        newIdentNode(g.cache.getIdent("raises"),  info), newNodeI(nkBracket, info))
```
