### PR TITLE
fix #13218: avoid some irrelevant warnings for nim doc,rst2html,--app:lib, + other fixes

### LINKED ISSUE #13218: nim doc generates lots of false positive LockLevel warnings
nim doc generates lots of false positive LockLevel warnings.
Generating spurious warnings causes us to ignore them, and in turn the real warnings get ignored too

### Example
```nim
(nim doc lib/pure/times.nim 2>&1)| grep LockLevel | wc -l
(nim doc lib/pure/os.nim 2>&1)| grep LockLevel | wc -l
```

### Current Output
```
30
33
```

### Expected Output
```
0
0
```

### Additional Information
* recent devel e11ecc8266d7345ba553875506d34bdb9ed9106d
* these are indeed spurious, eg: adding `when isMainModule: echo fromUnix(0)` in times.nim and `nim c -r lib/pure/times.nim` causes no such warning, even though nim doc shows a warning for `fromUnix`

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #13218 avoid some irrelevant warnings for nim doc, nim rst2html, nim --app:llib
* alternative approach to https://github.com/nim-lang/Nim/pull/13507 (addresses a subset of the noise in ./koch docs; more could be done in future PR's); it's better to fix at the compiler level than patch every call to the compiler by inserting --warning:foo:off

### CODE REVIEW

File: compiler/commands.nim [hunk 1]
```diff
@@ -628,6 +628,8 @@ proc processSwitch*(switch, arg: string, pass: TCmdLinePass, info: TLineInfo;
       defineSymbol(conf.symbols, "executable")
       defineSymbol(conf.symbols, "consoleapp")
     of "lib":
+      # should that apply also for other `arg` options?
+      conf.setNoteDefaults(warnUnusedImportX, false) # similar to issue #13218
```
Comment (Araq) [inline compiler/commands.nim]: Inconsistent. Why does a library build all of a sudden not care about unused imports anymore?

Comment (timotheecour) [reply compiler/commands.nim]: for typical use like lib/nimrtl.nim which defines:
```
import
  parseutils, strutils, parseopt, parsecfg, strtabs, unicode, pegs, ropes,
  os, osproc, times, cstrutils
```
without using any for the sole purpose of exporting symbols

alternatives:
* add compiler support for `discard modulename` (could help in other situations too) to disable at import-site (as opposed to {.used.} which is at importee-site)
* amend --app:lib to only apply for sfIsMainModule

Comment (Araq) [reply compiler/commands.nim]: Modules that have procs that use ``.exportc, dynlib`` (or maybe just ``.export``)  should instead be considered as "used".

Comment (timotheecour) [reply compiler/commands.nim]: excellent, yes `just .export.` is the right test

Comment (timotheecour) [reply compiler/commands.nim]: I've removed this as your idea is better, can be done in a separate PR

**Comment by timotheecour** [comment]
@araq PTAL
your exportc suggestion is good, will do in a separate PR

EDIT: failure unrelated, and I'm fixing it in https://github.com/Vladar4/nimgame2/pull/41

https://dev.azure.com/nim-lang/Nim/_build/results?buildId=3274&view=logs&jobId=f6c2f757-7152-5b00-b42b-aaebf1a063dd&j=f6c2f757-7152-5b00-b42b-aaebf1a063dd&t=f0f21f3f-4495-55c9-9119-ef53cf103fc2

```
FAIL: https://github.com/Vladar4/nimgame2/ C
Test "https://github.com/Vladar4/nimgame2/" in category "nimble-packages"
Failure: reBuildFailed
package test failed
$ nim c nimgame2/nimgame.nim
Hint: used config file 'd:\a\1\s\config\nim.cfg' [Conf]
Hint: used config file 'd:\a\1\s\config\config.nims' [Conf]
Hint: system [Processing]
...
Hint: streams [Processing]
d:\a\1\s\pkgstemp\nimgame2\nimgame2\utils.nim(169, 54) Warning: use `csize_t` instead; csize is deprecated [Deprecated]
d:\a\1\s\pkgstemp\nimgame2\nimgame2\utils.nim(169, 31) Error: type mismatch: got <ptr RWops, ptr char, csize, int literal(1000)>
but expected one of: 
proc rwRead(context: ptr RWops; p: pointer; size: csize_t; maxnum: csize_t): csize_t
  first type mismatch at position: 3
  required type for size: csize_t
  but expression 'csize(1)' is of type: csize

expression: rwRead(src, addr(result[r]), csize(1), 1000)

```
