### PR TITLE
Fix #17199

### LINKED ISSUE #17199: [ARC] compile-time `move()` on a sink-annotated argument empties the original value even when it's unsafe
This code works fine with refc but fails with arc because system has a different implementation for https://nim-lang.org/docs/system.html#%26%2Cseq%5BT%5D%2CT and with ARC the compiler seems to always pass a variable to a `sink`-annotated argument even when it's unsafe. Found in https://github.com/PMunch/protobuf-nim

### Example
Original example
```nim
proc passSeq(data: seq[string]) = 
  # used the system.& proc initially
  let wat = data & "hello"

proc test = 
  let name = @["hello", "world"]
  passSeq(name)
  doAssert name == @["hello", "world"]

# works at runtime but not compile-time
static:
  test()
```

Example with & taken out of system (fails with both refc/arc):
```nim
proc merge(x: sink seq[string], y: sink string): seq[string] =
  newSeq(result, x.len + 1)
  for i in 0..x.len-1:
    result[i] = move(x[i])
  result[x.len] = move(y)

proc passSeq(data: seq[string]) = 
  # used the system.& proc initially
  let wat = merge(data, "hello")

proc test = 
  let name = @["hello", "world"]
  passSeq(name)
  doAssert name == @["hello", "world"]

# works at runtime but not compile-time
static:
  test()
```

### Current Output
```
stack trace: (most recent call last)
/home/dian/Stuff/protobuf-nim/krr.nim(12, 7) krr
/home/dian/Stuff/protobuf-nim/krr.nim(8, 11) test
/home/dian/Things/Nim/lib/system/assertions.nim(68, 26) failedAssertImpl
/home/dian/Things/Nim/lib/system/assertions.nim(58, 11) raiseAssert
/home/dian/Things/Nim/lib/system/fatal.nim(53, 5) sysFatal
/home/dian/Things/Nim/lib/system/fatal.nim(53, 5) Error: unhandled exception: /home/dian/Stuff/protobuf-nim/krr.nim(8, 12) `name == @["hello", "world"]`  [AssertionDefect]
```

### Expected Output
Successful compilation

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-02-28
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 26a6ceb34eb2bfca4e39dec2dac2d0a2cdc1bade
active boot switches: -d:release -d:danger
```

### PR DESCRIPTION
**Pull request by Clyybber**
Fixes #17199

### CODE REVIEW

File: tests/arc/tarcmisc.nim [hunk 1]
```diff
@@ -390,3 +390,19 @@ proc newPixelBuffer(): PixelBuffer =
...
+
+proc test =
+  let name = @["hello", "world"]
+  passSeq(name)
+  doAssert name == @["hello", "world"]
+
+# works at runtime but not compile-time
+static:
+  test()
+
```
Comment (timotheecour) [inline tests/arc/tarcmisc.nim]:
```suggestion
static: test() # was buggy
test()
```

File: tests/vm/tissues.nim [hunk 2]
```diff
@@ -26,3 +26,25 @@ block t4952:
...
+  let wat = merge(data, "hello")
+
+proc test =
+  let name = @["hello", "world"]
+  passSeq(name)
+  doAssert name == @["hello", "world"]
+
+# works at runtime but not compile-time
+static:
+  test()
```
Comment (timotheecour) [inline tests/vm/tissues.nim]:
```suggestion
static: test() # was buggy
test()
```

File: tests/arc/tarcmisc.nim (hunk 1 above)
Comment (timotheecour) [reply tests/arc/tarcmisc.nim]: (test() + static: test() is now a standard pattern we use to ensure VM works like RT)

**Comment by deech** [comment]
Gentle nudge on this issue ...

**Comment by Clyybber** [comment]
Tests are failing because they test a value being zeroed out after move in the VM. Will adapt them accordingly
