### PR TITLE
fixes #23378; fixes js abs negative int64

### LINKED ISSUE #23378: for JS, `abs BiggestInt -1` failed to run
### Description

A smallest demo
```Nim
var neg = -1  # prevent compile-time evaluation
let n{.used.} = abs BiggestInt neg
```
run the generated JS code either on web browser or nodejs, error:
`Cannot mix BigInt and other types, ...`

If looking into that JS code, it's due to:

- `abs`  is implemented as `<arg> * (-1)` if `<arg>` is negative
- when for Nim's BiggestInt (a.k.a int64), JS uses BigInt
- BigInt cannot be mixed with `-1` (an int)

And, it's a regression (see `Additional Information`)

### Nim Version

Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2024-03-07
Copyright (c) 2006-2024 by Andreas Rumpf

active boot switches: -d:release

And

Nim Compiler Version 2.0.0 [Windows: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
TypeError: Cannot mix BigInt and other types, use explicit conversions
```

### Expected Output

```text
1
```

### Possible Solution

_No response_

### Additional Information

At least I found Nim-1.6.14 didn't have this problem:

```
Nim Compiler Version 1.6.14 [Windows: amd64]
Compiled at 2023-06-27
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
```

Also, just take `BiggestInt -1` as an example,

e.g. `abs -140140140140` will fail on run, too

### PR DESCRIPTION
**Pull request by ringabout**
fixes #23378

### CODE REVIEW

File: compiler/jsgen.nim [hunk 1]
```diff
@@ -788,7 +788,13 @@ proc arithAux(p: PProc, n: PNode, r: var TCompRes, op: TMagic) =
   of mEqProc: applyFormat("($1 == $2)", "($1 == $2)")
   of mUnaryMinusI: applyFormat("negInt($1)", "-($1)")
   of mUnaryMinusI64: applyFormat("negInt64($1)", "-($1)")
-  of mAbsI: applyFormat("absInt($1)", "Math.abs($1)")
+  of mAbsI:
+    let typ = n[1].typ.skipTypes(abstractVarRange)
+    if typ.kind == tyInt64 and optJsBigInt64 in p.config.globalOptions:
+      useMagic(p, "absInt64")
+      applyFormat("absInt64($1)", "Math.abs($1)")
```
Comment (metagn) [inline compiler/jsgen.nim]: Math.abs (generated here with checks off) still doesn't accept bigints, instead we can generate `absInt64` again since the overflow check in the `absInt`/`negInt` functions are delegated to Nim `*` which will correctly decide checking by itself.
