### PR TITLE
fixes #5234

### LINKED ISSUE #5234: Regression: JS: wrong field-access codegen
Introduced with #5226.

```nim
type MyObj = object
    mField: int
var a: MyObj
var b = a
doAssert(a.mField == 0)
```
```
nim js -r test.nim
Error: Error: unhandled exception: a.mField == 0  [AssertionError]
Traceback (most recent call last)
system.raiseAssert
sysFatal.sysFatal, line: 2581

    at unhandledException (/Users/yglukhov/nimcache/test.js:364:11)
    at raiseException (/Users/yglukhov/nimcache/test.js:219:1)
    at sysfatal_21221 (/Users/yglukhov/nimcache/test.js:396:1)
    at raiseassert_21216 (/Users/yglukhov/nimcache/test.js:403:1)
    at Object.<anonymous> (/Users/yglukhov/nimcache/test.js:407:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Also please-please, bring the dot notation back =)

### PR DESCRIPTION
**Pull request by mjendrusch**
My bad. #5234 should now work.

### CODE REVIEW

**Comment by yglukhov** [comment]
👍 
I still think though that now as you have returned to mangling, it's easy to revert to dot-notation. Just add a couple of rules to mangling for js keywords.

**Comment by Araq** [comment]
> I still think though that now as you have returned to mangling, it's easy to revert to dot-notation. Just add a couple of rules to mangling for js keywords.

Yeah, I agree.

File: compiler/jsgen.nim [hunk 1]
```diff
@@ -179,9 +179,24 @@ proc mapType(p: PProc; typ: PType): TJSTypeKind =
   else: result = mapType(typ)
 
 proc mangleName(s: PSym; target: TTarget): Rope =
+  proc validJsName(name: string): bool =
+    result = true
+    const reservedWords = ["break", "case", "catch", "class", "const", "continue",
```
Comment (yglukhov) [inline compiler/jsgen.nim]: Even though the list looks correct, it may be shrinked by excluding nim words, which are already guaranteed not to be present on the parsing phase. This will somewhat improve the lookup speed, as its currently O(n).

Comment (yglukhov) [inline compiler/jsgen.nim]: Maybe a hash set would be a better alternative.

Comment (andreaferretti) [inline compiler/jsgen.nim]: I think a linear lookup in a small array will be faster than using a hashset

Comment (Araq) [inline compiler/jsgen.nim]: Nim's string case statement is mapped to a hash table...

Comment (mjendrusch) [inline compiler/jsgen.nim]: The problem is, in nim you could still do:
```nim
type SomeType = object
  `case`: int
  `for`: cstring
  # ...
```
So unless one would make those names invalid field names for nim, they may not be removed from the list, I think.

Comment (yglukhov) [inline compiler/jsgen.nim]: @andreaferretti, @mjendrusch yeah, I guess you're right, pardon.

Comment (yglukhov) [inline compiler/jsgen.nim]: Ok. The lookup speed can definitely be improved by using sorted array + binary search.

File: compiler/jsgen.nim [hunk 2]
```diff
@@ -179,9 +179,26 @@ proc mapType(p: PProc; typ: PType): TJSTypeKind =
...
+      "finally", "for", "function", "if", "import", "in", "instanceof", "new",
+      "return", "super", "switch", "this", "throw", "try", "typeof", "var",
+      "void", "while", "with", "yield", "enum", "implements", "interface",
+      "let", "package", "private", "protected", "public", "static", "await",
+      "abstract", "boolean", "byte", "char", "double", "final", "float", "goto",
+      "int", "long", "native", "short", "synchronized", "throws", "transient",
+      "volatile", "null", "true", "false"]
+    if name in reservedWords: return false
+    for chr in name:
+      if chr notin {'A'..'Z','a'..'z','_'}:
```
Comment (yglukhov) [inline compiler/jsgen.nim]: and `$` dollars

Comment (mjendrusch) [inline compiler/jsgen.nim]: Digits and `$` should work now.

File: compiler/jsgen.nim (hunk 1 above)
Comment (mjendrusch) [inline compiler/jsgen.nim]: Sorted the array and added a binary search in lieu of the linear one.

File: compiler/jsgen.nim [hunk 3]
```diff
@@ -179,9 +179,36 @@ proc mapType(p: PProc; typ: PType): TJSTypeKind =
   else: result = mapType(typ)
 
 proc mangleName(s: PSym; target: TTarget): Rope =
+  proc validJsName(name: string): bool =
+    result = true
+    const reservedWords = ["abstract", "await", "boolean", "break", "byte",
```
Comment (Araq) [inline compiler/jsgen.nim]: sorry but I said to use a string case statement here. That will be compiled into a compiletime hash table. Easier, faster.

Comment (mjendrusch) [inline compiler/jsgen.nim]: Sorry, I must have misread the discussion on that. Here's the case statement :)

Comment (yglukhov) [inline compiler/jsgen.nim]: I guess I gave you the wrong advise. Sorry for that.
