### PR TITLE
fixes #22419; async/closure environment does not align local variables

### LINKED ISSUE #22419: async/closure environment does not align local variables
### Description

```nim
import std/asyncdispatch

type
  ValidatorPubKey* = object
    blob*: array[96, byte]

proc f() {.async.} =
  var x {.align: 16}: uint8
  var y {.align: 16}: ValidatorPubKey
  let value = cast[uint64](unsafeAddr y)
  echo "f() = ", cast[uint64](unsafeAddr y), " mod(8) = ", value mod 8

proc e() =
  var x: uint8
  var y: ValidatorPubKey
  let value = cast[uint64](unsafeAddr y)
  echo "e() = ", cast[uint64](unsafeAddr y), " mod(8) = ", value mod 8

waitFor f()
e()
```

### Nim Version

```
Nim Compiler Version 1.6.15 [Linux: amd64]
Compiled at 2023-08-08
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1cd48e4b2abd867adf1ab52a70a1d8f1c6ac77c4
active boot switches: -d:release
```

```
Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-08
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release
```

```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-08
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 73e661d01bdde815a5f388b960cd4d0593f7accc
active boot switches: -d:release
```

### Current Output

```text
$ # Test all of Nim 1.6, 2.0, and devel (therefore, both refc and ORC)
$ Nim16/bin/nim c -r --hints:off r
f() = 139823877881961 mod(8) = 1
e() = 140720357015456 mod(8) = 0
$ Nim20/bin/nim c -r --hints:off r
f() = 140174585233530 mod(8) = 2
e() = 140724735024336 mod(8) = 0
$ NimDevel/bin/nim c -r --hints:off r
f() = 140395756572794 mod(8) = 2
e() = 140735821040544 mod(8) = 0
```

### Expected Output

Aligned local variables in closure environment (with or without `align` pragmas, but here even `align` doesn't work around the issue).

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #22419

### CODE REVIEW

File: tests/align/talign.nim [hunk 1]
```diff
@@ -51,3 +51,26 @@ type Bug[T] = object
...
+  proc f() {.async.} =
+    var x {.align: 16.}: uint8
+    var y {.align: 16.}: ValidatorPubKey
+    let value = cast[uint64](unsafeAddr y)
+    doAssert value mod 8 == 0
+
+  proc e() =
+    var x: uint8
+    var y: ValidatorPubKey
+    let value = cast[uint64](unsafeAddr y)
```
Comment (blackmius) [inline tests/align/talign.nim]: doesn't nim 2.0 use addr instead of unsafeAddr?

Comment (ringabout) [reply tests/align/talign.nim]: make sense

Comment (ringabout) [inline tests/align/talign.nim]:
```suggestion
    let value = cast[uint64](addr y)
```

File: tests/align/talign.nim [hunk 2]
```diff
@@ -51,3 +51,26 @@ type Bug[T] = object
...
+
+block:
+  type
+    ValidatorPubKey = object
+      blob: array[96, byte]
+
+  proc f() {.async.} =
+    var x {.align: 16.}: uint8
+    var y {.align: 16.}: ValidatorPubKey
+    let value = cast[uint64](unsafeAddr y)
```
Comment (ringabout) [inline tests/align/talign.nim]:
```suggestion
    let value = cast[uint64](addr y)
```

File: tests/align/talign.nim [hunk 3]
```diff
@@ -51,3 +51,26 @@ type Bug[T] = object
...
+block:
+  type
+    ValidatorPubKey = object
+      blob: array[96, byte]
+
+  proc f() {.async.} =
+    var x {.align: 16.}: uint8
+    var y {.align: 16.}: ValidatorPubKey
+    let value = cast[uint64](addr y)
+    doAssert value mod 8 == 0
```
Comment (arnetheduck) [inline tests/align/talign.nim]:
```suggestion
    doAssert value mod 16 == 0
```
it's the actual alignment that matters

File: tests/align/talign.nim [hunk 4]
```diff
@@ -51,3 +51,26 @@ type Bug[T] = object
 
 var bug: Bug[int]
 doAssert sizeof(bug) == 128, "Oops my size is " & $sizeof(bug) # 16
+
+
+import std/asyncdispatch
```
Comment (arnetheduck) [inline tests/align/talign.nim]: this doesn't need async - a normal closure iterator would exhibit the same bug

File: tests/align/talign.nim [hunk 5]
```diff
@@ -51,3 +51,26 @@ type Bug[T] = object
...
+
+block:
+  type
+    ValidatorPubKey = object
+      blob: array[96, byte]
+
+  proc f() {.async.} =
+    var x {.align: 16.}: uint8
```
Comment (arnetheduck) [inline tests/align/talign.nim]: this align doesn't matter for the purpose of the bug

Comment (ringabout) [reply tests/align/talign.nim]: Yeah, It's harmless, though.

File: tests/align/talign.nim [hunk 6]
```diff
@@ -51,3 +51,26 @@ type Bug[T] = object
...
+    var y {.align: 16.}: ValidatorPubKey
+    let value = cast[uint64](addr y)
+    doAssert value mod 16 == 0
+
+  proc e() =
+    var x: uint8
+    var y: ValidatorPubKey
+    let value = cast[uint64](addr y)
+    doAssert value mod 8 == 0
```
Comment (arnetheduck) [inline tests/align/talign.nim]: there is no reason validatorpubkey should have this alignment, ie the test looks wrong..

Comment (arnetheduck) [reply tests/align/talign.nim]: both structs and arrays struct get the alignment of the most aligned member: 1 in this case because the field has the alignemnt of a `byte`.

File: tests/align/talign.nim (hunk 4 above)
Comment (ringabout) [reply tests/align/talign.nim]: True, but the simplest closure iterator example works.

Comment (blackmius) [reply tests/align/talign.nim]:
```nim
type
  ValidatorPubKey = object
    blob: array[96, byte]

proc f(): auto =
  return iterator() =
    var pad: int8 = 0
    var y {.align: 16.}: ValidatorPubKey
    let value = cast[uint64](addr y)
    doAssert value mod 16 == 0

f()()
```

Comment (ringabout) [reply tests/align/talign.nim]: thanks!

**Comment by Araq** [comment]
Ping @narimiran please backport to 1.6 and 2.0
