### PR TITLE
custom pragmas: correct error condition, remove outdated symkind whitelist

### LINKED ISSUE #21652: Confusing error message
### Description

I attached a tag to a template

    type
      Foo = object

    template foo() {.tags:[Foo].} =
      discard

### Nim Version

Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

### Current Output

```text
e.nim(4, 22) Error: cannot attach a custom pragma to 'foo'
```

### Expected Output

```text
foo.nim(4, 22) Error: cannot attach a custom pragma to 'foo' because it is a template

or at least

    foo.nim(4, 22) Error: cannot attach a custom pragma to template 'foo'
```

### Possible Solution

A brief glance at `proc illegalCustomPragma(c: PContext, n: PNode, s: PSym)` in compiler/pragmas.nim makes it look like the type might be gleanable from `s`.

Looking at the equally sparse error messages in neighboring procedures, it would appear worthwhile to add a bit of context to them, as well.

### Additional Information

Before you ask: I won't be able to master the knowledge required to fix this myself on short notice, or I would have. Sorry, just a report!

### PR DESCRIPTION
**Pull request by metagn**
fixes #21652

Along with fixing the error message, instead of using a whitelist of symbol kinds for custom pragmas, use a blacklist of ones that do not work, so we don't have to keep maintaining this list as much (a symbol kind that does not support custom pragmas silently accepts it in the worst case). Currently this is enum fields, `for` loop variables (both because they do not retain pragma AST after semcheck) and module symbols (as it's not handled). We can also whitelist `PragmaApplicableSymKinds - {skEnumField, skForVar, skModule}` instead to make it more restrictive, but again in the worst case with the blacklist it is just silently accepted.

<details>
<summary>Description for previous patch in this PR</summary>

The symbol kinds you could previously not apply custom pragmas to were:

```
skModule
skMacro
skTemplate
skEnumField
skForVar

probably cannot attach pragmas to but still not checked for:
skGenericParam, skResult
skTemp, skUnknown, skConditional, skDynLib, skLabel, skStub, skPackage
```

Now trying to apply a nonexistant pragma to these symbols will give a proper "invalid pragma" error instead of the "cannot attach custom pragma" error.

This way of doing it will attempt to "attach" existing custom pragmas to these symbol kinds, which should not be a problem for macros and templates, but just swallow the custom pragmas without erroring likely as semchecking removes the pragma AST down the line.

```nim
import macros

template prag {.pragma.}

type Foo = enum
  a {.prag.}

echo hasCustomPragma(a, prag) # false
for b {.prag.} in [123]:
  echo hasCustomPragma(b, prag) # false

template c(x: int): int {.prag.} = x
echo hasCustomPragma(c, prag) # true

macro d(x: int): int {.prag.} = x
echo hasCustomPragma(d, prag) # true

# this just has no way of working
{.prag.}
echo hasCustomPragma(modulename, prag) # false
```

We don't have to fix #21652 this way, there is an easy patch of delaying the "cannot attach custom pragma" error until we succeed in finding the custom pragma in `semCustomPragma`, but I want to test this "swallowing" behavior against CI first to see if it breaks anything.
</details>

### CODE REVIEW

File: compiler/pragmas.nim [hunk 1]
```diff
@@ -1248,13 +1261,8 @@ proc singlePragma(c: PContext, sym: PSym, n: PNode, i: var int,
     elif comesFromPush and whichKeyword(ident) != wInvalid:
       discard "ignore the .push pragma; it doesn't apply"
     else:
-      if sym == nil or (sym.kind in {skVar, skLet, skConst, skParam, skIterator,
-                        skField, skProc, skFunc, skConverter, skMethod, skType}):
-        n[i] = semCustomPragma(c, it)
-      elif sym != nil:
-        illegalCustomPragma(c, it, sym)
-      else:
-        invalidPragma(c, it)
```
Comment (metagn) [inline compiler/pragmas.nim:1257]: This branch was also never called as `sym != nil` is guaranteed to be true

So this doesn't change general performance either
