### PR TITLE
[nodejs backend] paramStr, paramCount

### LINKED ISSUE #11120: Incorrect error message "paramCount is not implemented on Nintendo Switch" in nimscript
NimScript is treated as "weirdTarget" in https://github.com/nim-lang/Nim/blob/b350a9fc52d67cabc778887d8f81d0332eb9db91/lib/pure/os.nim#L2529 leading to an incorrect error message  "paramCount is not implemented on Nintendo Switch"

```
#!/usr/bin/env nim                    
import os     
echo commandLineParams()     
```

### PR DESCRIPTION
**Pull request by ringabout**
ref https://forum.nim-lang.org/t/7519

close #11120

### CODE REVIEW

File: lib/pure/os.nim [hunk 1]
```diff
@@ -2795,13 +2795,14 @@ when defined(nimdoc):
   proc paramStr*(i: int): string {.tags: [ReadIOEffect].} =
     ## Returns the `i`-th `command line argument`:idx: given to the application.
     ##
-    ## `i` should be in the range `1..paramCount()`, the `IndexDefect`
-    ## exception will be raised for invalid values.  Instead of iterating over
-    ## `paramCount() <#paramCount>`_ with this proc you can call the
-    ## convenience `commandLineParams() <#commandLineParams>`_.
+    ## `i` should be in the range `start..paramCount()`, the `IndexDefect`
+    ## exception will be raised for invalid values. start is 1 for c/cpp backend, 
+    ## 2 for nodejs backend. Instead of iterating over `paramCount() <#paramCount>`_
```
Comment (Araq) [inline lib/pure/os.nim]: Start should always be 1...

File: lib/pure/os.nim [hunk 2]
```diff
@@ -2825,7 +2826,21 @@ when defined(nimdoc):
...
+  let argv {.importjs: "process.argv".} : Argv
+  proc len(argv: Argv): int {.importjs: "#.length".}
+  proc `[]`(argv: Argv, i: int): cstring {.importjs: "#[#]".}
+
+  proc paramCount*(): int {.tags: [ReadDirEffect].} =
+    result = argv.len - 2
+
+  proc paramStr*(i: int): string {.tags: [ReadIOEffect].} =
+    if i < argv.len and i >= 0:
+      result = $argv[i]
```
Comment (Araq) [inline lib/pure/os.nim:2840]: Compensate for the start of 1 here via 

```suggestion
      result = $argv[i+1]
```

File: lib/pure/os.nim (hunk 1 above)
Comment (ringabout) [reply lib/pure/os.nim]: for nodejs, the first two elements are node and the path to your script.

E:\node\node.exe
D:\QQPCmgr\Desktop\Nim\test.js
