### PR TITLE
fix: double check inputIndex in base64.decode

### LINKED ISSUE #25530: base64.decode on whitespace prefixed string can lead to index defect
### Nim Version

2.2.6

### Description

(example using fish shell)

```sh
➜ nim c -r (echo '
  import base64
  echo decode("   a")
  ' | psub -s '.nim')
/tmp/.psub.PVFMMD/psub.nim(3) psub
/home/root/.choosenim/toolchains/nim-2.2.6/lib/pure/base64.nim(230) decode
/home/root/.choosenim/toolchains/nim-2.2.6/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: index 4 not in 0 .. 3 [IndexDefect]
```

if a string to be decoded is prefixed with whitespace due to:

https://github.com/nim-lang/Nim/blob/ab00c56904e3126ad826bb520d243513a139436a/lib/pure/base64.nim#L252-L259

as it increments `inputIndex` it can increment it outside of the outer loop bound `inputLen - 4` hence `inputChar` blows up with out of bounds error

### Current Output

```text
`IndexDefect` is raised
```

### Expected Output

```text
base64 should decode as normal
```

### Known Workarounds

call `strip` before using `decode`:

```nim
decode(s.strip())
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by miki725**
fixes https://github.com/nim-lang/Nim/issues/25530

this double checks the index to make sure whitespace related index increments cannot cause index defect error

### CODE REVIEW

File: lib/pure/base64.nim [hunk 1]
```diff
@@ -255,6 +255,9 @@ proc decode*(s: string): string =
   while inputIndex <= inputEnds:
     while s[inputIndex] in {'\n', '\r', ' '}:
       inc inputIndex
+    # double check inputIndex as it can be incremented due to whitespace
+    if inputIndex > inputEnds:
+      continue
```
Comment (Araq) [inline lib/pure/base64.nim]: break?

Comment (miki725) [reply lib/pure/base64.nim]: sure. functionally the same but might be more clear with the intent
