### PR TITLE
fix operators containing percent for VM usage

### LINKED ISSUE #13513: Compiler creates invalid out-of-range int8 constants.
The compiler creates an invalid int8 constant with the value 128.

### Example
```nim
const a = high(int8)
const b = a +% 1

doAssert typeof(b) is int8

doAssert b == 128                # INVALID BUT WORKS !!!
doAssert b <= high(int8)         # FAILS
```

### Current Output
```
Error: unhandled exception: /tmp/test.nim(7, 10) `b <= high(int8)`  [AssertionError]
```

### Expected Output
```
b should be -128
```

```
$ nim -v
Nim Compiler Version 1.1.1 [Linux: amd64]
Compiled at 2020-02-26
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: f091b5a0ee9b5585a08e9130d3ec682a9526ef39
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by krux02**
Short explanation, in the VM signed numbers are stored with an extended sign. Unsigned numbers do not have a sign and therefore no sign extension. Applying unsigned operations on numbers with with sign extensions will have different results than without those extensions. Also unsigned ops do not apply sign extension afterwards, even though signed numbers require the sign extension. The casting operations introduced in this PR will do the sign extension removal and reintroduction for the VM accordingly. For runtime behavior, casting is a noop and should not affect performance.

fixes #13513

### CODE REVIEW

**Comment by krux02** [comment]
Somehow there is a breaking test. This is what breaks, but it also breaks on devel. But it would mean that the development branch is broken.
```nim
import times

echo parse("1", "YYYY", utc())
```

**Comment by timotheecour** [comment]
> BTW I am too lazy to add a test right now.

just copy the one I wrote here: https://github.com/nim-lang/Nim/pull/13532/files#diff-750bc0bcbc3193d1a2854eed2d5ec5d1

**Comment by krux02** [comment]
@timotheecour Thanks for the help, but that test isn't suitable. I am circumventing to fix semfold for `+%`, so I don't special case testing for it. Also I am not just fixing `+%` in isolation. There is a problem with all `%` operators. So I need to test all of them. But if you care, your test does pass on my machine.

File: lib/system/comparisons.nim [hunk 1]
```diff
@@ -161,25 +161,55 @@ proc `<`*(x, y: int16): bool {.magic: "LtI", noSideEffect.}
...
+  ## Returns true if ``x <= y``.
+proc `<=`*(x, y: uint8): bool {.magic: "LeU", noSideEffect.}
+proc `<=`*(x, y: uint16): bool {.magic: "LeU", noSideEffect.}
+proc `<=`*(x, y: uint32): bool {.magic: "LeU", noSideEffect.}
+proc `<=`*(x, y: uint64): bool {.magic: "LeU", noSideEffect.}
 
-proc `<=%`*(x, y: IntMax32): bool {.magic: "LeU", noSideEffect.}
-proc `<=%`*(x, y: int64): bool {.magic: "LeU64", noSideEffect.}
+proc `<`*(x, y: uint): bool {.magic: "LtU", noSideEffect.}
+  ## Returns true if ``unsigned(x) < unsigned(y)``.
```
Comment (timotheecour) [inline lib/system/comparisons.nim]: pre-existing comment but I don't understand it since x is already unsigned here;
IMO that comment belongs under
```
proc `<%`*(x, y: int8): bool {.inline.} = cast[uint8](x) < cast[uint8](y)
```
ditto elsewhere

Comment (krux02) [reply lib/system/comparisons.nim]: might be true. Thanks for the feedback. I will apply it tomorrow. I had to change a lot of ordering in the code and then in the end I moved all the comments into place.

File: tests/concepts/t3330.nim [hunk 2]
```diff
@@ -17,17 +17,17 @@ proc add[T](x: var seq[T]; y: openArray[T])
   first type mismatch at position: 1
   required type for x: var seq[T]
   but expression 'k' is of type: Alias
-proc add(result: var string; x: float)
+proc add(x: var string; y: cstring)
```
Comment (timotheecour) [inline tests/concepts/t3330.nim]: no action needed here but I see this kind of thing break a lot (where ordering is changed), may be good to start sorting sigmatch errors in compiler by some reliable criterion (simplest would be raw string sort) to avoid having to edit tests

File: lib/system/comparisons.nim (hunk 1 above)
Comment (krux02) [reply lib/system/comparisons.nim]: well I just applied the feedback. But I really have to go sleep now. It is already early in the morining.

File: tests/concepts/t3330.nim (hunk 2 above)
Comment (krux02) [reply tests/concepts/t3330.nim]: yea it is annoying. But I don't know what the cause it. Is it that I changed some definitions that symbols get a different order when iterating them? Or is it because I introduce a bug into `+%` so that hash values are calculated differently? Or did I fix `+%` and hash values are calculated differently? I don't know. I am worried because I don't understand it.

File: lib/system/comparisons.nim [hunk 3]
```diff
@@ -161,25 +161,55 @@ proc `<`*(x, y: int16): bool {.magic: "LtI", noSideEffect.}
...
   ## Treats `x` and `y` as unsigned and compares them.
   ## Returns true if ``unsigned(x) <= unsigned(y)``.
+  cast[uint](x) <= cast[uint](y)
+proc `<=%`*(x, y: int8): bool {.inline.} = cast[uint8](x) <= cast[uint8](y)
+proc `<=%`*(x, y: int16): bool {.inline.} = cast[uint16](x) <= cast[uint16](y)
+proc `<=%`*(x, y: int32): bool {.inline.} = cast[uint32](x) <= cast[uint32](y)
+proc `<=%`*(x, y: int64): bool {.inline.} = cast[uint64](x) <= cast[uint64](y)
 
-proc `<%`*(x, y: IntMax32): bool {.magic: "LtU", noSideEffect.}
-proc `<%`*(x, y: int64): bool {.magic: "LtU64", noSideEffect.}
```
Comment (timotheecour) [inline lib/system/comparisons.nim:171]: `mLtU64` is orphaned after your changes and should be removed ; check also if other magics are orphaned (LeU64 etc)

File: lib/system/comparisons.nim [hunk 4]
```diff
@@ -161,25 +161,55 @@ proc `<`*(x, y: int16): bool {.magic: "LtI", noSideEffect.}
...
   ## Treats `x` and `y` as unsigned and compares them.
   ## Returns true if ``unsigned(x) < unsigned(y)``.
+  cast[uint](x) < cast[uint](y)
+proc `<%`*(x, y: int8): bool {.inline.} = cast[uint8](x) < cast[uint8](y)
+proc `<%`*(x, y: int16): bool {.inline.} = cast[uint16](x) < cast[uint16](y)
+proc `<%`*(x, y: int32): bool {.inline.} = cast[uint32](x) < cast[uint32](y)
+proc `<%`*(x, y: int64): bool {.inline.} = cast[uint64](x) < cast[uint64](y)
 
-template `>=%`*(x, y: untyped): untyped = y <=% x
+proc `>=%`*(x, y: int): bool {.inline.} =
```
Comment (timotheecour) [inline lib/system/comparisons.nim]: * instead of introducing all those overloads (previous code had a single template for `>=%`) use this:
```
template `>=%`*[T](x, y: T): untyped = y <=% x
```
* ditto with `>%`

File: tests/concepts/t3330.nim (hunk 2 above)
Comment (timotheecour) [reply tests/concepts/t3330.nim]: not sure about the other points raised but I'm tracking this specific issue here https://github.com/nim-lang/Nim/issues/13538

**Comment by timotheecour** [comment]
> The implementation that uses a proc instead of a magic might cause slower performance on non optimized builds.

from reading your diff, seems like performance impact should only be for VM, not RT, can you confirm?
As for VM performance for such ops, may be good to do a quick benchmark to see what's the damage.
If VM performance isn't negatively affected, getting rid of VM specific code sounds like a very nice cleanup

* you can remove dead code that's introduced in this PR, eg if `mLeU64` is no longer used, these:
```
compiler/ast.nim:617:6:    mLeU64, mLtU64,
compiler/ast.nim:687:6:    mLeU64, mLtU64,
compiler/ccgexprs.nim:608:7:  of mLeU64: applyFormat("((NU64)($1) <= (NU64)($2))")
compiler/forloops.nim:16:42:    mEqUntracedRef, mLeI, mLeF64, mLeU, mLeU64, mLeEnum,
compiler/guards.nim:20:34:  someLe = {mLeI, mLeF64, mLeU, mLeU64, mLeEnum,
compiler/jsgen.nim:579:7:  of mLeU64: applyFormat("($1 <= $2)", "($1 <= $2)")
compiler/semfold.nim:294:13:  of mLeU, mLeU64:
compiler/vmgen.nim:1081:21:  of mLePtr, mLeU, mLeU64: genBinaryABC(c, n, dest, opcLeu)
```
ditto with mLtU64 etc

* and also you may want to add tests that exercise #13513

**Comment by krux02** [comment]
This is the test that you can execute to verify that here is a problem to fix.

```nim
proc testUnsignedOps() =
  let a: int8 = -128
  let b: int8 = 127

  echo toHex(cast[uint16](b +% 1))
  echo toHex(cast[uint16](b -% -1))
  echo toHex(cast[uint16](b *% 2))
  echo toHex(cast[uint16](a /% 4))
  echo toHex(cast[uint16](a %% 7))

testUnsignedOps()
static:
  testUnsignedOps()
```

**Comment by krux02** [comment]
Test failure is unrelated.

File: compiler/jsgen.nim [hunk 5]
```diff
@@ -370,71 +370,69 @@ type
...
+    mBitnotI: ["", ""],
+    mUnaryPlusF64: ["", ""],
+    mUnaryMinusF64: ["", ""],
+    mCharToStr: ["nimCharToStr", "nimCharToStr"],
+    mBoolToStr: ["nimBoolToStr", "nimBoolToStr"],
+    mIntToStr: ["cstrToNimstr", "cstrToNimstr"],
+    mInt64ToStr: ["cstrToNimstr", "cstrToNimstr"],
+    mFloatToStr: ["cstrToNimstr", "cstrToNimstr"],
+    mCStrToStr: ["cstrToNimstr", "cstrToNimstr"],
+    mStrToStr: ["", ""]]
```
Comment (krux02) [inline compiler/jsgen.nim:434]: I had to remove the `mMeU64` and `mLtU64`. Since I was already at it. I converted the comments of the array into proper named array members.

**Comment by Araq** [comment]
I'd be happier with templates instead of inline procs as inline procs are currently not inlined in debug builds. Also you seem to mix refactorings with bugfixes which makes everything harder and slower to review.

**Comment by timotheecour** [comment]
> I'd be happier with templates instead of inline procs as inline procs are currently not inlined in debug builds

then maybe that should be fixed instead ? IMO {.inline.} procs should inline in debug builds (ie without -d:release), but we could have an option `--nimIgnoreInline` to ignore `{.inline.}`
no strong opinion either way

**Comment by krux02** [comment]
> I'd be happier with templates instead of inline procs as inline procs are currently not inlined in debug builds.

I can do it if you say that is how it should be done.

> Also you seem to mix refactorings with bugfixes which makes everything harder and slower to review.

I only mix in those refactoring that are structurally integrated with the bugfixes. The other refactorings are part of my other already merged PR here: https://github.com/nim-lang/Nim/pull/13551

But please don't expect me to like this splitting of the contribution. I only do it to do you a favor. But for me it means that the amount of time that I have to deal the slow CI the review process is doubled. And then when when one of the PRs is merged I usually get merge conflics as the bug fixes and refactorings can't be separated perfectly. So I have to deal with the CI yet another time.

**Comment by timotheecour** [comment]
* in this particular case I feel like those refactorings are directly related to the bugfix so it wouldn't make sense to split in 2 PRs
* in other similar cases though, there's a better way than splitting in 2 PRs PR1,PR2 (and having to deal with a lot of overhead work on the side of the contributor especially when PR1 needs to address review comment which then affects PR2): 
simply make sure there are refactoring-only commits and bugfix-only commits (and if neeed, add a note to reviewer to that effect); and if a change needs to be addressed, use the usual `git rebase -i HEAD~4`

it results in much less overhead on side of contributor than splitting in PR's.

**Comment by Araq** [comment]
> MO {.inline.} procs should inline in debug builds (ie without -d:release), but we could have an option --nimIgnoreInline to ignore {.inline.}

Agreed, let's hope __always_inline (or whatever it is called) is portable enough...

**Comment by timotheecour** [comment]
> Agreed, let's hope __always_inline (or whatever it is called) is portable enough...

=> let's discuss this in https://github.com/nim-lang/RFCs/issues/198

> I'd be happier with templates instead of inline procs as inline procs are currently not inlined in debug builds

that's not what I'm seeing, see https://github.com/nim-lang/RFCs/issues/198: cgen generates
`static N_INLINE(NI, fun2x__rxUfcN4ZvcApCx0waSVH8At10303b)(NI a) {.` regardless of -d:danger or not,

however:
* inline procs WILL be noticably slower than templates in debug builds (or anything with --stacktrace) unless https://github.com/nim-lang/Nim/pull/13582 is merged and user passes the `--stacktrace:noinline` this enables
* in debug builds (even with --stacktrace:off and regardless of #13582) I've observed that templates will be a little bit faster than inline proc, but same speed with danger builds (and maybe -d:release, haven't checked); however IMO codegen can be improved to make inline proc and template same speed even for debug build by removing redundant assignment incurred by inline proc (with `--stacktrace:noinline` or `--stacktrace:off`)

File: lib/system/comparisons.nim [hunk 6]
```diff
@@ -161,16 +161,37 @@ proc `<`*(x, y: int16): bool {.magic: "LtI", noSideEffect.}
...
+proc `<=%`*(x, y: int32): bool {.inline.} = cast[uint32](x) <= cast[uint32](y)
+proc `<=%`*(x, y: int64): bool {.inline.} = cast[uint64](x) <= cast[uint64](y)
 
-proc `<%`*(x, y: IntMax32): bool {.magic: "LtU", noSideEffect.}
-proc `<%`*(x, y: int64): bool {.magic: "LtU64", noSideEffect.}
+proc `<%`*(x, y: int): bool {.inline.} =
   ## Treats `x` and `y` as unsigned and compares them.
   ## Returns true if ``unsigned(x) < unsigned(y)``.
+  cast[uint](x) < cast[uint](y)
+proc `<%`*(x, y: int8): bool {.inline.} = cast[uint8](x) < cast[uint8](y)
```
Comment (narimiran) [inline lib/system/comparisons.nim]: This seems wrong to me.

```nim
var a = -10'i8
var b = 3'i8

proc `<%`*(x, y: int8): bool {.inline.} = cast[uint8](x) < cast[uint8](y)

echo a <% b # prints 'false'
```

Am i missing something?
