### PR TITLE
round out tuple unpacking assignment, support underscores

### LINKED ISSUE #18710: tuple destructuring doesn't always work with `_` (underscore)
Tuple desctructuring does not work with underscores if used outside of `var` section. Inside it it's OK, and that's confusing. It seems Nim sees `_` as a special identifier that should be declared.

### Example
```nim
var x = 0
(x, _) = (1, 2)
```

### Current Output

`Error: undeclared identifier: '_'`

### Expected Output
To work the same way as
```nim
var (x, _) = (1, 2)
```

(This was fixed at some stage, e.g. bug  https://github.com/nim-lang/Nim/issues/2421)

### Additional Information

Checked with Nim 1.4 and Nim 1.5 devel.

### PR DESCRIPTION
**Pull request by metagn**
fixes #18710

Tuple unpacking assignment (`(a, b) = (1, 2)`) now checks the type of the RHS properly for whether it's a tuple and whether it has the correct number of variables as opposed to delegating it to the `tuple` typeclass (#21767, supposedly this broke some macro code and a certain group blamed the separate VarTuple changes instead which if anything should make macros work better). The lowering code used to accomplish tuple unpacking assignment is now made into semantic code accordingly.

Underscores are also now supported, meaning `(a, _) = (1, 2)` is now possible when `a` is declared and `_` isn't. This is a new feature so might have to be changelogged and documented, but it can be done later. The entire feature is 3 lines, 2 of which are `else:` and `continue`. This fixes #18710.

The temp that is generated by tuple unpacking assignment is also no longer named `_` for clarity.

### CODE REVIEW

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -1828,6 +1828,37 @@ proc goodLineInfo(arg: PNode): TLineInfo =
...
+  vpart[0] = tempNode
+  vpart[1] = c.graph.emptyNode
+  vpart[2] = value
+  v.add vpart
+  result.add(v)
+
+  for i in 0..<lhs.len:
+    if lhs[i].kind == nkIdent and lhs[i].ident.id == ord(wUnderscore):
+      # skip _ assignments if we are using a temp as they are already evaluated
+      continue
```
Comment (Araq) [inline compiler/semexprs.nim]:
```suggestion
      discard
```
