### PR TITLE
fixes #22939; fixes #16890; push should but doesn't apply to importc …

### LINKED ISSUE #16890: `{.push nodecl.}` should but doesn't apply to importc var/let symbols, can give silently wrong results
### Example 1
```nim
{.push nodecl, header: "<copyfile.h>".}
# let COPYFILE_DATA* {.nodecl.}: cint # ok
let COPYFILE_DATA*: cint # bug:  Error: 'let' symbol requires an initialization
{.pop.}
```

### Current Output
Error: 'let' symbol requires an initialization

### Expected Output
works 

### Example 2: silently wrong results with var
```nim
when true:
  {.push nodecl, header: "<copyfile.h>".}
  # var COPYFILE_DATA* {.nodecl.}: cint # ok
  var COPYFILE_DATA*: cint # bug: initializes to 0
  {.pop.}
  doAssert COPYFILE_DATA == 8, $COPYFILE_DATA # fails
```

### Example 2
{.push nodecl.} also doesn't apply for types as shown below (even though we have `{.push nodecl.}` and even though `{.push header: ....}` should imply nodecl

this example requires osx but the problem isn't specific to osx
```nim
# t11796b:
when true:
  {.push nodecl, header: "<copyfile.h>".}
  type
    # copyfile_state_t {.nodecl.} = pointer # workaround: would work
    copyfile_state_t = pointer # bug
    copyfile_flags_t = cint
  proc copyfile_state_alloc*(): copyfile_state_t
  proc c_copyfile*(src, dst: cstring,  state: copyfile_state_t, flags: copyfile_flags_t): cint {.importc: "copyfile".}
  {.pop.}

# main.nim:
impor t11796b
if false:
  let state = copyfile_state_alloc()
  discard c_copyfile("", "",  state, 0)
```

nim r -b:cpp -d:case5 $timn_D/tests/nim/all/t11796.nim
```
/Users/timothee/git_clone/nim/timn/build/nimcache/@mt11796.nim.cpp:130:13: error: no matching function for call to 'copyfile'
                int T5_ = copyfile("", "", state__WkrHkIAbpCAcQ7Yk35nGFw, ((int) 0));
                          ^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/copyfile.h:55:5: note: candidate function not viable: cannot convert argument of incomplete type 'void *' to
      'copyfile_state_t' (aka '_copyfile_state *') for 3rd argument
int copyfile(const char *from, const char *to, copyfile_state_t state, copyfile_flags_t flags);
    ^
```

### Example 3
the docs of nodecl should be improved a bit IMO, eg:
`Note: This will not work for the LLVM backend.` => remove this, that backend was removed (and there'd be a way around this anyways)

they should also illustrate better when it's needed, and also explain that you need 2 files to see the need for header and nodecl, eg main.nim that imports fun.nim which contains c declarations (ohterwise cgen errors may be masked).

### Additional Information
1.5.1 eef2948ec2725d69358ab647a25bfa4ac675ed91
importc let without initialization was enabled since #14258
that specific example requires osx but the general bug is the same

### LINKED ISSUE #22939: Pushing `used` suppresses the `XDeclaredButNotUsed` hint for some identifiers, but not others
### Example

```nim
{.push used.}
const a = 42
proc b = echo "hi"
{.pop.}
```

### Current behavior

The compiler outputs an `XDeclaredButNotUsed` hint for `a` (but not `b`):

```
/tmp/used.nim(2, 7) Hint: 'a' is declared but not used [XDeclaredButNotUsed]
```

### Expected behavior

No such hint for `a` or `b`.

### Nim Version

Nim 2.0.0 and devel (https://github.com/nim-lang/Nim/commit/57ffeafda016a9772f6548d462f8d9acdcad33bd).

### Additional Information

The below works as expected, to suppress both hints:

```Nim
const a {.used.} = 42
proc b {.used.} = echo "hi"
```

Issue https://github.com/nim-lang/Nim/issues/4044 was closed 5 years ago, citing the above workaround for

```nim
{.push hint[XDeclaredButNotUsed]: off.}
const a = 42
proc b = echo "hi"
{.pop.}
```

which still produces the `XDeclaredButNotUsed` hint for both `a` and `b`.

The issue in the example was [reported in the #main channel](https://irclogs.nim-lang.org/14-11-2023.html#16:39:34).

### PR DESCRIPTION
**Pull request by ringabout**
…var/let symbols

fixes #22939
fixes #16890

Besides, it was applied to let/const/var with pragmas, now it is universally applied.

```nim
{.push exportc.}
proc foo =
  let bar = 12
  echo bar
{.pop.}
```

For example, the `bar` variable will be affected by `exportc`.

### CODE REVIEW

File: compiler/semtypes.nim [hunk 1]
```diff
@@ -528,6 +528,15 @@ proc semIdentWithPragma(c: PContext, kind: TSymKind, n: PNode,
     else: discard
   else:
     result = semIdentVis(c, kind, n, allowed)
+    case kind
+    of skType:
+      # process pragmas later, because result.typ has not been set yet
+      discard
```
Comment (ringabout) [inline compiler/semtypes.nim]:
```suggestion
```
