### PR TITLE
fixes #21116; always mangles the param

### LINKED ISSUE #21116: os.walkDir breaks if called in a function with a parameter named 'glob'
### Description

```nim
import std/os

when defined(bug):
  proc p(glob: string) =
    for _ in walkFiles(glob): discard
  p("dir/*")
else:
  proc p(g: string) =
    for _ in walkFiles(g): discard
  p("dir/*")
```

### Nim Version

```
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release
```

and

```
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-12-16
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 9a50033d5b09ec3263a53bd2bb4182a8a50e6f4d
active boot switches: -d:release
```

### Current Output

```text
$ nim r globname.n
(no issues)

$ nim -d:bug r globname.nim
Hint: used config file '/home/jfondren/.choosenim/toolchains/nim-1.6.10/config/nim.cfg' [Conf]
Hint: used config file '/home/jfondren/.choosenim/toolchains/nim-1.6.10/config/config.nims' [Conf]
......................................................................................
CC: globname.nim
/home/jfondren/.cache/nim/globname_d/@mglobname.nim.c: In function ‘p__globname_2’:
/home/jfondren/.cache/nim/globname_d/@mglobname.nim.c:254:23: error: called object ‘glob’ is not a function or function pointer
  254 |                 T2_ = glob(nimToCStringConv(glob), ((int) 0), NIM_NIL, (&fX60gensym137_));
      |                       ^~~~
/home/jfondren/.cache/nim/globname_d/@mglobname.nim.c:233:61: note: declared here
  233 | N_LIB_PRIVATE N_NIMCALL(void, p__globname_2)(NimStringDesc* glob) {
      |                                              ~~~~~~~~~~~~~~~^~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/jfondren/.choosenim/toolchains/nim-1.6.10/lib -I/home/jfondren/nim/bug -o /home/jfondren/.cache/nim/globname_d/@mglobname.nim.c.o /home/jfondren/.cache/nim/globname_d/@mglobname.nim.c' failed with exit code: 1
```

### Expected Output

_No response_

### Possible Solution

Mangle parameter names.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #21116

```c
N_LIB_PRIVATE N_NIMCALL(void, p__test55_2)(NimStringV2 glob__icdZQ89bZ6Q81ZmV9cDcnAEQ);
```
Or something simpler?

### CODE REVIEW

File: tests/ccgbugs/t21116.nim [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+  target: "c cpp"
+  disabled: windows
+"""
+# bug #21116
+import posix
+
+proc p(glob: string) =
+  discard posix.glob(glob, 0, nil, nil)
+
+p "*"
```
Comment (ringabout) [inline tests/ccgbugs/t21116.nim]:
```suggestion
import std/os

proc p(glob: string) =
  for _ in walkFiles(glob): discard
p("dir/*")
```
