### PR TITLE
fix #10339 by returning type attached to nkEmpty

### LINKED ISSUE #10339: Devel regression on static semcheck
The commit 87f8ec5b92d5647ab4b1875262e845d51dd82763 introduces a regression in my Laser library.

I get `../../laser/primitives/matrix_multiplication/gemm_tiling.nim(123, 6) Error: object constructor needs an object type`

At the function `x86_ukernel` with signature:

```Nim
type
  MicroKernel* = object
    mr*, nr*: int
    cpu_simd*: CPUFeatureX86
    nb_scalars*: int # Ideally MicroKernel should be generic over T, but static generic ...
    nb_vecs_nr*: int
    c_unit_stride*: bool

  CPUFeatureX86* = enum
    x86_Generic,
    x86_SSE,
    x86_SSE2,
    x86_SSE4_1,
    x86_AVX,
    x86_AVX_FMA,
    x86_AVX2,

func x86_ukernel*(cpu: CPUFeatureX86, T: typedesc, c_unit_stride: bool): MicroKernel =
```

Unfortunately this is quite a tricky bug so the minimal repro is to clone the repo and use the following compilation command:

`../Nim/bin/nim c -d:release -d:openmp -o:build/gemm_i32_omp benchmarks/gemm/gemm_bench_int32.nim`

Everything of interest is happening in this folder https://github.com/numforge/laser/tree/master/laser/primitives/matrix_multiplication, especially the
 - gemm.nim
 - gemm_packing.nim
 - gemm_tiling.nim

The full trace is:
```
gemm_bench_int32.nim(121, 8) template/generic instantiation of `bench` from here
gemm_bench_int32.nim(126, 17) template/generic instantiation of `gemm_strided` from here
../../laser/primitives/matrix_multiplication/gemm.nim(211, 46) template/generic instantiation of `dispatch` from here
../../laser/primitives/matrix_multiplication/gemm.nim(194, 14) template/generic instantiation of `apply` from here
../../laser/primitives/matrix_multiplication/gemm.nim(185, 30) template/generic instantiation of `gemm_impl` from here
../../laser/primitives/matrix_multiplication/gemm.nim(126, 29) template/generic instantiation of `pack_B_kc_nc` from here
../../laser/primitives/matrix_multiplication/gemm_tiling.nim(123, 6) Error: object constructor needs an object type
```

### Important remarks

When implementing Laser, I had the error a lot at the beginning, when I tried to use the following function signature for "packing functions":

```Nim
proc pack_B_kc_nc*[T](
      ukernel: static MicroKernel,
      packedB: ptr UncheckedArray[T],
      kc, nc: int,
      B: MatrixView[T])

# instead of

proc pack_B_kc_nc*[T; ukernel: static MicroKernel](
      packedB: ptr UncheckedArray[T],
      kc, nc: int,
      B: MatrixView[T]) =
```

This PR/branch https://github.com/numforge/laser/pull/16 shows that behaviour when passing static object as parameter instead of as generic param except for that case it never worked.

Furthermore, when replacing the function result type by auto in
```Nim
func x86_ukernel*(cpu: CPUFeatureX86, T: typedesc, c_unit_stride: bool): MicroKernel =
```
I narrowed the issue to the static instantiation of Microkernel.

cc @zah

### PR DESCRIPTION
**Pull request by Vindaar**
I'm not sure if this is actually a fix or more of a hack. :)

The test case at least reproduces the same error as @mratsim's laser code.

The problem without this PR seems to be that we end up in `semObjConstr` with a `nkEmpty` node as the first child. I assume that's because `typ.base` in `semSym` extracts the node we need as a child later on in `semObjConstr`. 

If there's a better fix for this, feel free to close.

### CODE REVIEW

**Comment by LemonBoy** [comment]
You gotta go _slightly_ deeper than this :)
By enabling `useNodeIds` and by using `debug` and `nodeIdToDebug` you can see where the `nkEmpty` is coming from: the VM is generating it as part of the object construction routine (it generates an empty object and then fills it field by field) and places a `nkEmpty` node as first child with `typ` set to the object type.

Now, what's the meaning of the first field? There's no documentation anywhere but we can infer its meaning from the `primarySuffix` routine: the compiler puts there the symbol used to construct the given object!

Indeed the VM does a poor job and tries to get away by doing the least amount of work as possible but is kind enough to set the `typ` correctly.

The error you see comes from `semObjConstr` as it seems that our `typ` is misteriously ignored by `semTypeNode`. By making it return the type attached to the `nkEmpty` node both the examples compile and run without having to introduce this hack, it should be harmless since most of the `nkEmpty` that go through that function should have a `typ` set to `nil`.

**Comment by Vindaar** [comment]
Now that's some useful feedback, @LemonBoy. Thanks a lot! Will get back to this latest on Monday. :)

**Comment by Vindaar** [comment]
Force pushed a rebase onto current devel and added one commit addressing @LemonBoy's feedback. I hope just setting `result` to `n.typ` if non nil in `semTypeNode` is correct.

Thanks again for your help, @LemonBoy! I read about `useNodeIds` before, but never new how to use it, nor what to use it for. Really useful.

File: compiler/semtypes.nim [hunk 1]
```diff
@@ -1474,7 +1474,9 @@ proc semTypeNode(c: PContext, n: PNode, prev: PType): PType =
 
   if c.config.cmd == cmdIdeTools: suggestExpr(c, n)
   case n.kind
-  of nkEmpty: discard
+  of nkEmpty:
+    if n.typ != nil: result = n.typ
```
Comment (LemonBoy) [inline compiler/semtypes.nim]: You can simplify this further since `result` is already initialized to `nil` before and if `n.typ` is `nil` nothing changes.

Comment (Vindaar) [reply compiler/semtypes.nim]: Heh, good point. I should have noticed that. Done.
