### PR TITLE
Finalizer proc must be global

### LINKED ISSUE #10376: Using function argument as `new` finalizer fails to compile
`new` with finalizer works well if I pass a global function as the finilizer, however if I pass an argument of a function (which is of course also a function) to it compilation will fail during calling `gcc`.

### Example

```nim
type
  A = ref object

proc callback(a: A) {. nimcall .} = 
  discard

proc foo(callback: proc(a: A) {. nimcall .}) =
  var a: A
  new(a, callback)

foo(callback)
```

### Current Output
```
Hint: used config file '/home/wtli/.choosenim/toolchains/nim-0.19.0/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test_callback [Processing]
CC: test_callback
Error: execution of an external compiler program 'gcc -c  -w  -I/home/wtli/.choosenim/toolchains/nim-0.19.0/lib -o /home/wtli/.cache/nim/test_callback_d/test_callback.c.o /home/wtli/.cache/nim/test_callback_d/test_callback.c' failed with exit code: 1

/home/wtli/.cache/nim/test_callback_d/test_callback.c: In function ‘test_callbackDatInit000’:
/home/wtli/.cache/nim/test_callback_d/test_callback.c:178:54: error: ‘callback’ undeclared (first use in this function)
 (&NTI_DNgur79be8Ev9cbhq3iBkzxA_)->finalizer = (void*)callback;
                                                      ^
/home/wtli/.cache/nim/test_callback_d/test_callback.c:178:54: note: each undeclared identifier is reported only once for each function it appears in
```

### Expected Output
Successful compilation, or an error message showing I can only use global functions as finalizer.

### Additional Information
```
Nim Compiler Version 0.19.0 [Linux: amd64]
Compiled at 2018-09-26
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: f6c5c636bb1a1f4e1301ae0ba5a8afecef439132
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by LemonBoy**
Fixes #10376

### CODE REVIEW

**Comment by Araq** [comment]
I don't think it must be "global", it must be *direct* proc though, ``skProc`` and not ``skParam``.

**Comment by LemonBoy** [comment]
Good catch, I've amended the PR.
The error message may not be clear enough tho, if you have some suggestions about how to better word it I'm all ears.

File: compiler/semmagic.nim [hunk 1]
```diff
@@ -410,4 +410,9 @@ proc magicsAfterOverloadResolution(c: PContext, n: PNode,
       result = n
     else:
       result = plugin(c, n)
+  of mNewFinalize:
+    # Make sure the finalizer procedure refers to a procedure
+    if n[^1].kind == nkSym and n[^1].sym.kind notin {skProc, skFunc}:
+      localError(c.config, n.info, "finalizer must be a direct reference to a procedure")
```
Comment (Araq) [inline compiler/semmagic.nim]: "finalizer must be a proc or func, it must not be an indirection" ?
