### PR TITLE
fix calls in generic bodies, delay typecheck when no overloads match

### LINKED ISSUE #19284: using static Slice[int] for arbritrarily indexed multidimensional arrays len can't generate VM code for result
Trying to write a multidimensional array that could have arbitrary indices I wrote:
```nim
type Board[N, M: static Slice[int]] = array[len(N)*len(M), int8]

var t: Board[0..4, 0..4]
```

This fails with
```
nim-#devel/lib/system.nim(1592, 3) Error: cannot generate VM code for result
```

The following code compiles OK:
```nim
proc len(x: Slice[int]): int = x.b - x.a
type mdArray[N,M: static Slice[int]] = array[len(M)*len(N), int]
```
(thanks to Rika on discord for coming up with that snippet)

### LINKED ISSUE #19365: generic, compile-time proc creates "cannot generate VM code for T" error
A compile-time procedure with a generic, static type compiles with a VM code generation error.

### Example
```nim
proc f[T](x: static T) {.compileTime.} = discard
```

### Current Output
```
testcase.nim(1, 21) Error: cannot generate VM code for T
```

### Expected Output
Successful compilation.

Tested with Nim versions:
```
Nim Compiler Version 1.2.16 [Linux: amd64]
Compiled at 2022-01-10
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: c6a9f27b3e36bae9aacec1bd6c37893fb98fd33f
active boot switches: -d:release
```

```
Nim Compiler Version 1.6.2 [Linux: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

```
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-01-11
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 9888a29c3de09c73202b2a955e09e2a7b5e56ea4
active boot switches: -d:release
```

### LINKED ISSUE #19916: `cannot generate VM code for and` when using `math.ceilDiv` with generic type argument
Cannot generate VM code for seemingly correct `and` operator in assertion in `math.ceilDiv`

https://github.com/nim-lang/Nim/blob/a65db5e2e924c51af7c654f8e564332299b95cb3/lib/pure/math.nim#L976

When used to operate on generic argument.

### Example
```nim
import math

type
  Test[S: static[Natural]] = object
    a: array[ceilDiv(S, 8), uint8]

let a = Test[32]()
echo a
```

### Current Output
```
/.../nim/lib/pure/math.nim(977, 17) Error: cannot generate VM code for and
```

### Expected Output

Should compile, don't see why not...

### Possible Solution

No idea.

### Additional Information
```console
$ nim --version
Nim Compiler Version 1.6.6 [Windows: amd64]
Compiled at 2022-05-05
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```
Also tried on 1.6.2, same error.

### LINKED ISSUE #20514: Compilation error when using type-generic proc in type definition
### What happened?

Using `prod` in a type definition causes the compiler to fail with an uninformative error message.

```nim
import std/math

type Foo[S:static[array[2, int]]] = object
  values: array[prod(S), float]

echo sizeof(Foo[[4,5]])
```

Curiously, replacing `prod` with `sum` causes a different outcome. The below program erroneously prints `1`:

```nim
import std/math

type Foo[S:static[array[2, int]]] = object
  values: array[sum(S), float]

echo sizeof(Foo[[4,5]])
```

### Nim Version

Nim Compiler Version 1.7.3 [Windows: amd64]
Compiled at 2022-10-07
Copyright (c) 2006-2022 by Andreas Rumpf

active boot switches: -d:release

### Current Standard Output Logs

```shell
C:\Users\dan\.choosenim\toolchains\nim-#devel\lib\pure\math.nim(357, 3) Error: cannot generate VM code for result
```

### Expected Standard Output Logs

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### LINKED ISSUE #20937: VM breaking at template parameter evaluation.
### Description

VM breaks at trying to execute `volume` procedure:
```nim
type
  Vec3*[T: SomeNumber] {.bycopy.} = tuple[x, y, z: T]

func volume*[T](v: Vec3[T]): T =
  when T is SomeUnsignedInt:
    v.x * v.y * v.z
  else:
    abs (v.x * v.y * v.z)

type
  Matrix3*[C: static Vec3[uint], T] = object
    cells: array[C.area, T]

let m = Matrix3[(1.uint, 1.uint, 1.uint), uint](cells: [0.uint])
```

### Nim Version

1.6.8

### Current Output

```text
/usercode/in.nim(7, 15) Error: cannot generate VM code for *
```

### Expected Output

```text
Successful compilation.
```

### Possible Solution

_No response_

### Additional Information

Changing 'volume' func to template fixes the problem, so, breaking probably happens on procedure boundaries.

### PR DESCRIPTION
**Pull request by metagn**
fixes #19916, fixes #20514, fixes #20937, fixes #19284, fixes #19365, refs https://github.com/nim-lang/Nim/commit/7fdf29937d8cb4835953a5e52b59e5f550d0fba2

In generic bodies, the compiler hard-compiles calls in `array`/`range`/`when` static expression parts, including with generic parameter arguments which cannot reasonably be evaluated and have to be special cased in some places in the compiler ([example in `semLowHigh`](https://github.com/nim-lang/Nim/blob/21d941c16a84daa855870717f064802b052d6792/compiler/semexprs.nim#L449-L453)). There was no such special casing for calls in `sigmatch`/`semcall`, instead there was some weird workaround involving not instantiating generic calls in generic bodies which breaks a lot of code that should work.

This workaround is now removed and generic calls are always instantiated. In order for this to work, special casing has also been added to `sigmatch`/`semcall` so that calls with unresolved generic parameters don't match typedesc parameters of procs, and calls with no matching overloads delay their typechecking to instantiation time.

`tyGenericParam` is added to `types.isCompileTimeOnly` to make `T; U: static T` work, due to how `static T` behaves the same as `static foo()` and just converts to a static type when the expression returns a typedesc. Note that `static[T]` is not affected and worked before.

There ~~is~~ was also a new `untyped foo()` syntax (inspired by the "untyped escape hatch" in https://github.com/nim-lang/RFCs/issues/168) to stop hard compilation in generic bodies and delay to instantiation time when the compiler can't delay it by itself. But this isn't needed currently in this PR and can be detached from it (although it might be useful to work around future bugs, like `(U + 1) * 2` not working). Update: It was detached from the PR.

### CODE REVIEW

File: compiler/semtypinst.nim [hunk 1]
```diff
@@ -250,7 +250,7 @@ proc replaceTypeVarsN(cl: var TReplTypeVars, n: PNode; start=0): PNode =
       result = newNodeI(nkRecList, n.info)
   of nkStaticExpr:
     var n = prepareNode(cl, n)
-    n = reResolveCallsWithTypedescParams(cl, n)
+    #n = reResolveCallsWithTypedescParams(cl, n)
```
Comment (Araq) [inline compiler/semtypinst.nim]: Oh yes, that is sweet!

File: compiler/types.nim [hunk 2]
```diff
@@ -1500,7 +1503,7 @@ proc compatibleEffects*(formal, actual: PType): EffectsCompat =
 
 
 proc isCompileTimeOnly*(t: PType): bool {.inline.} =
-  result = t.kind in {tyTypeDesc, tyStatic}
+  result = t.kind in {tyTypeDesc, tyStatic, tyGenericParam}
```
Comment (metagn) [inline compiler/types.nim:1519]: This change exists in this PR for the sole purpose of making `T; U: static T` work (though might be more correct anyway). In any case the compiler treats `static T` the same as `static foo()` and evaluates it as a constant expression which returns `static[T]`. `static[T]` on the other hand goes through `semStaticType` in `semtypes` which doesn't have a reason to fail with generic params.

One might think to add `elif op.id == ord(wStatic): result = semStaticType(...)` [here](https://github.com/nim-lang/Nim/blob/21d941c16a84daa855870717f064802b052d6792/compiler/semtypes.nim#L1938) instead, but this might not be correct and could break some code and I don't want to complicate this PR.

~~Edit: I believe this also fixes #15760, will add test case~~ doesn't

**Comment by metagn** [comment]
The main issue here is that the compiler hard-compiles calls in `array`/`range`/`when` (not tested) static expression parts, including with generic parameter arguments which cannot reasonably be evaluated and have to be special cased in some places in the compiler ([example in `semLowHigh`](https://github.com/nim-lang/Nim/blob/21d941c16a84daa855870717f064802b052d6792/compiler/semexprs.nim#L449-L453)). This special casing is not properly performed for calls in `sigmatch`/`semcall`, instead there is some weird workaround involving not instantiating generic calls which breaks a lot of code that should work.

The reason statics work without this workaround is we already know their type when they're constrained, i.e. when `T: static int` we can compile `T + 1` early without problem. When they're not constrained, like `T; U: static T`, the same problem is there.

The new `untyped foo()` syntax prevents this hard compilation, but the user has to think to use it without any good suggestions, and the compiler has feigned automatically detecting it so far so maybe it should properly do it. This `untyped` also doesn't seem to always work with the old workaround.

~~Right now I am not able to either make the compiler smarter on the broken cases or make the call to use `nkStaticExpr` on every call node in generic range types and lose information people might depend on/performance. For this reason this behavior is now opt-in, but currently this is done with an experimental switch which won't work if it's turned on at the type declaration but not at the site of the instantiation. Maybe it can be attached to the type instead, i.e. `Foo[T] {.instantiateCalls.} = ...`, or this is inferred in a context with the experimental feature turned on.~~ Broken cases work

**Comment by metagn** [comment]
OK I now made it so:

1. unresolved generic parameters can't be passed to `typedesc` arguments (sigmatch change)
2. calls without matching overloads get a `tyFromExpr` type instead of erroring in generic contexts (semcall change, with required followups in semexprs)

This accomplishes "making the compiler smarter" to make the old cases still work. So we don't need any opting in anymore.

This also means the `untyped` feature is not needed in the scope of this proc, but might be needed to workaround bugs not covered here down the line (just realized `(U + 1) * 2` is one such bug). I can either remove it to maybe put in another PR later maybe with an RFC (it's a small change), or keep it and document it etc (without making much noise).

**Comment by Araq** [comment]
> I can either remove it to maybe put in another PR

What would this removal look like?

**Comment by metagn** [comment]
This diff from semexprs gets removed:

```nim
   of tyUntyped: 
     if c.inGenericContext > 0: 
       # could add `and efDetermineType in flags`, but no flags param 
       result = n[1] 
       result.typ = makeTypeFromExpr(c, result.copyTree) 
       return 
     else: 
       localError(c.config, n.info, "illegal type conversion to '$1'" % typeToString(targetType)) 
   of tyAnything, tyTyped:
```

And it's used once in a test which is a copy of another test without it. That's it.

**Comment by Araq** [comment]
So remove it please.

**Comment by metagn** [comment]
Done
