### PR TITLE
Fix #2672. Do not define globalsSlot for native TLS

### LINKED ISSUE #2672: Importing 'impure' libraries while using threads causes segfaults
```
import strutils
import db_sqlite    # Just importing any impure lib causes segfaults

type
  StringChannel = TChannel[string]
var
  channels : array[0..3, StringChannel]
  thr: array [0..3, TThread[int]]

proc consumer(channel: int) {.thread.} =
  let channel = channels[channel].addr
  echo channel[].recv()
  channel[].send("fighters")

proc main =
  for ix in 0..3: channels[ix].open()
  for ix in 0..3: createThread(thr[ix], consumer, ix)
  for ix in 0..3: channels[ix].send("foo (" & intToStr(ix) & ")")
  joinThreads(thr)
  for ix in 0..3: echo channels[ix].recv()
  for ix in 0..3: channels[ix].close()

when isMainModule:
  main()
```
Simple import causes the issue.
Importing the low-level wrapper (sqlite3 in this case) doesn't.

Arch Linux , Nim version 0.11.2 - devel

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Comment by dom96** [comment]
I can't review this, but if it fixes #2672 then nice job!

File: lib/pure/dynlib.nim [hunk 1]
```diff
@@ -57,20 +57,27 @@ when defined(posix):
...
+  proc loadLib(path: string, global_symbols=false): LibHandle =
     var flags = RTLD_NOW
     if global_symbols: flags = flags or RTLD_GLOBAL
-    return dlopen(path, flags)
-  proc loadLib(): LibHandle = return dlopen(nil, RTLD_NOW)
-  proc unloadLib(lib: LibHandle) = dlclose(lib)
-  proc symAddr(lib: LibHandle, name: cstring): pointer = 
-    return dlsym(lib, name)
+    result = dlopen(path, flags)
+    discard dlerror()
```
Comment (Araq) [inline lib/pure/dynlib.nim]: I don't think we need these dlerror() calls everywhere?
