### PR TITLE
don't allow casting to non-concrete types; fixes #5428

### LINKED ISSUE #5428: template instanciation crashes compiler
```nim
type
  MemFile = object
    mem: pointer

proc memfileopen(filename: string, newFileSize: int): MemFile =
  # just a memfile mock
  return

proc close(arg: MemFile): void =
  # just a memfile mock
  discard

type
  MyData = object
    member1: seq[int]
    member2: int

type
  MyReadWrite = object
    memfile: MemFile
    offset: int

proc writeOffset(rw: var MyReadWrite; value: SomeNumber): void =
  ## does not write to memory, only calculates offset
  rw.offset += sizeof(value)

proc write(rw: var MyReadWrite; value: SomeNumber): void =
  (cast[ptr SomeNumber](cast[uint](rw.memfile.mem) + rw.offset.uint))[] = value
  rw.offset += sizeof(SomeNumber)

proc read(rw: var MyReadWrite; value: var SomeNumber): void =
  value = (cast[ptr SomeNumber](rw.memfile.mem + rw.offset))[]
  rw.offset += sizeof(SomeNumber)

proc writeOffset[T](rw: var MyReadWrite; value: var seq[T]): void =
  rw.offset += sizeof(int)
  rw.offset += sizeof(T) * value.len

proc write[T](rw: var MyReadWrite; value: seq[T]): void =
  rw.write value.len
  let dst  = cast[ptr SomeNumber](cast[uint](rw.memfile.mem) + uint(rw.offset))
  let src  = cast[pointer](value[0].unsafeAddr)
  let size = sizeof(T) * value.len
  copyMem(dst, src, size)
  rw.offset += size

proc read[T](rw: var MyReadWrite; value: var seq[T]): void =
  rw.read value.len
  let dst  = cast[pointer](value[0].addr)
  let src = rw.memfile.mem
  let size = sizeof(T) * value.len
  copyMem(dst, src, size)
  rw.offset += size

template readWriteTemplate(rw: untyped; arg: var MyData): void =
  rw(arg.member1)
  rw(arg.member2)

proc saveBinFile(arg: var MyData, filename: string): void =
  var rw: MyReadWrite
  readWriteTemplate(rw.writeOffset, arg)
  echo "rw: ", rw.offset
  rw.memfile = memfileOpen(filename, newFileSize = rw.offset)
  rw.offset = 0
  readWriteTemplate(rw.write, arg)
  rw.memfile.close

```
Compilation output:

```
bin/nim_temp  compile /tmp/scratch.nim
Hint: used config file '/home/arne/proj/nim/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: scratch [Processing]
Error: internal error: getTypeDescAux(tyOr)
Traceback (most recent call last)
nim.nim(121)             nim
nim.nim(77)              handleCmdLine
main.nim(163)            mainCommand
main.nim(74)             commandCompileToC
modules.nim(240)         compileProject
modules.nim(180)         compileModule
passes.nim(213)          processModule
passes.nim(135)          processTopLevelStmt
cgen.nim(1280)           myProcess
ccgstmts.nim(1126)       genStmts
ccgexprs.nim(2079)       expr
ccgstmts.nim(1126)       genStmts
ccgexprs.nim(2151)       expr
cgen.nim(822)            genProc
cgen.nim(787)            genProcNoForward
cgen.nim(686)            genProcAux
ccgstmts.nim(1126)       genStmts
ccgexprs.nim(2079)       expr
ccgstmts.nim(1126)       genStmts
ccgexprs.nim(2101)       expr
ccgstmts.nim(259)        genVarStmt
ccgstmts.nim(237)        genSingleVar
cgen.nim(390)            assignLocalVar
cgen.nim(375)            localVarDecl
ccgtypes.nim(800)        getTypeDesc
ccgtypes.nim(636)        getTypeDescAux
ccgtypes.nim(793)        getTypeDescAux
msgs.nim(997)            internalError
msgs.nim(902)            rawMessage
msgs.nim(899)            rawMessage
msgs.nim(838)            handleError
msgs.nim(822)            quit
FAILURE

```

### PR DESCRIPTION
**Pull request by zah**

### CODE REVIEW

File: compiler/types.nim [hunk 1]
```diff
@@ -20,6 +20,7 @@ type
     preferName, preferDesc, preferExported, preferModuleInfo, preferGenericArg
 
 proc typeToString*(typ: PType; prefer: TPreferedDesc = preferName): string
+template `$`*(typ: PType): string = typeToString(typ)
```
Comment (Araq) [inline compiler/types.nim]: this causes problems with older Nim releases (because of bugs in them), better make it an .inline proc.
