### PR TITLE
fix #15617(fix compilation failure on -d:useMalloc --gc:none)

### LINKED ISSUE #15617: compilation failure on -d:useMalloc --gc:none
Nim fails to compile simple programs when using `-d:useMalloc --gc:none`. See https://forum.nim-lang.org/t/6943

### Example

```nim
let x = 4
```
Compiling with `nim compile -d:useMalloc --gc:none simple.nim` produces
```
Hint: used config file '/home/user/nim-1.4.0/config/nim.cfg' [Conf]
Hint: used config file '/home/user/nim-1.4.0/config/config.nims' [Conf]
.
/home/user/nim-1.4.0/lib/system/mmdisp.nim(96, 77) Error: undeclared identifier: 'newObj'
```

Compiling an empty file also fails.
```shell
$ echo -n "" > simple.nim
$ nim compile -d:useMalloc --gc:none simple.nim
Hint: used config file '/home/user/nim-1.4.0/config/nim.cfg' [Conf]
Hint: used config file '/home/user/nim-1.4.0/config/config.nims' [Conf]
.
/home/user/nim-1.4.0/lib/system/mmdisp.nim(96, 77) Error: undeclared identifier: 'newObj'
```

### Additional Information
Both the one-line program and empty program compile successfully with [1.0.10](https://github.com/nim-lang/nightlies/releases/tag/2020-10-17-version-1-0-c32e002e63cab001c18a81639dad1b3a9ffe2aeb).

Both fail to compile with versions [1.2.8](https://github.com/nim-lang/nightlies/releases/tag/2020-10-17-version-1-2-714fd811996515539eb0efd7b6f7543a73025e18), [1.4.0](https://github.com/nim-lang/nightlies/releases/tag/2020-10-17-version-1-4-bdcd87afca238a0a7b2c70971827cf9172817b12), and [1.5.1](https://github.com/nim-lang/nightlies/releases/tag/2020-10-17-devel-66cd9c2e57de027781a11f4434112ab0e5cfea7b).

### PR DESCRIPTION
**Pull request by ringabout**
fix #15617

### CODE REVIEW

File: tests/gc/gcnone.nim [hunk 1]
```diff
@@ -0,0 +1,6 @@
+discard """
+  matrix: "--gc:none -d:useMalloc"
+"""
+
```
Comment (timotheecour) [inline tests/gc/gcnone.nim]:
```suggestion
# bug #15617
```

File: lib/system/mmdisp.nim [hunk 2]
```diff
@@ -57,6 +57,16 @@ elif defined(gogc):
 elif (defined(nogc) or defined(gcDestructors)) and defined(useMalloc):
   include system / mm / malloc
 
+  when defined(nogc):
+    proc GC_getStatistics(): string = return ""
```
Comment (timotheecour) [inline lib/system/mmdisp.nim]:
```suggestion
    proc GC_getStatistics(): string = ""
```

**Review by timotheecour — APPROVED** [review]
LGTM after nits

if possible add a test with seq since you've added newSeq, eg
```nim
var a = @["ab", "cd"]
a.add "ef"
doAssert a[^1] == "cd"
doAssert a == @["ab", "cd", "ef"]
```

File: tests/gc/gcnone.nim [hunk 3]
```diff
@@ -0,0 +1,6 @@
+discard """
+  matrix: "--gc:none -d:useMalloc"
```
Comment (Araq) [inline tests/gc/gcnone.nim]: Since testament specializes the "gc" directory, this test is never run. --> We need to tweak testament for category "gc" in order to prevent this from happening the next time.

Comment (timotheecour) [reply tests/gc/gcnone.nim]: => tracking as bug 13 in https://github.com/nim-lang/Nim/issues/16521
