### PR TITLE
More converter fixes

### LINKED ISSUE #9735: Converter bug: if converter returns `lent T` it is still possible to pass it as `var T` argument
Title explains it. I will provide a fix

### LINKED ISSUE #9736: Converter bug: if converter returns `var T` and argument expects `var T` it may still be rejected if original variable is `let`
Title explains the problem. I will provide a fix

### PR DESCRIPTION
**Pull request by cooldome**
I am working on smart pointers using new Nim destructors and they require top quality converter support. I have stumbled upon two more issues:

Fixes #9735  (Converter bug: if converter returns `lent T` it is still possible to pass it as `var T` argument)
Fixes #9736  (Converter bug: if converter returns `var T` and argument expects `var T`,  it may still be rejected if original variable is `let`)

I haven't provided examples in the issue description, but the PR contains extensive test case

P.S.
I guess I can contribute the smart pointer library to stdlib if there is an interest.

### CODE REVIEW

**Comment by cooldome** [comment]
fingers crossed let's hope I have fixed the build

**Comment by cooldome** [comment]
I have just discovered that this PR also fixes #3503. I will stick its test somewhere as prove.

**Comment by cooldome** [comment]
Could you please review this one. Let me know if something wrong with the approach.

File: compiler/sigmatch.nim [hunk 1]
```diff
@@ -52,6 +52,8 @@ type
                              # this is used to prevent instantiations.
     genericConverter*: bool  # true if a generic converter needs to
                              # be instantiated
+    converterRetType*: PType # converter can turn let into var and var into let
+                             # used to check mutability differences
```
Comment (krux02) [inline compiler/sigmatch.nim]: Can you alaborate, why you need a new field here and the existing fields are not sufficient?

Comment (cooldome) [reply compiler/sigmatch.nim]: There is a comment there. When argument is converted the mutability check needs to be done not on the original argument, but on the return type of the converter hence return type needs to be made available to `matchesAux`.

It is likely possible to avoid this extra field if it is a problem. The cost of more code in `matchesAux` to unpack prepared call, skip nkHiddenDeref and nknkHiddenCallConv to find the return type of the converter.

**Comment by cooldome** [comment]
I have submitted alternative implementation that does not use additional field in TCandidate.

**Comment by cooldome** [comment]
Could get this PR reviewed please. Without these fixes I don't think it is possible to implement a usable smart pointer library for Nim.

File: compiler/sigmatch.nim [hunk 2]
```diff
@@ -2231,8 +2231,15 @@ proc matchesAux(c: PContext, n, nOrig: PNode,
       else:
         m.state = csNoMatch
         return
+    
     if formal.typ.kind == tyVar:
-      if not n.isLValue:
```
Comment (Araq) [inline compiler/sigmatch.nim]: I would have put this logic into a variant of ``isLValue``, but I'm merging it now since it's blocking you.
