### PR TITLE
fixes #20026; marks system procs which can raise defects

### LINKED ISSUE #20026: doAssertRaises cannot handle IndexDefect with goto exceptions
```nim
var x = "123"

doAssertRaises(IndexDefect):
  discard x[0..99]
```
gives with Orc or goto exceptions

```
Error: unhandled exception: expected raising 'IndexDefect', instead nothing was raised by:
discard x[0 .. 99] [AssertionDefect]
```

ref https://github.com/nim-lang/Nim/pull/19972

### PR DESCRIPTION
**Pull request by ringabout**
fixes #20026

```nim
(n.kind == nkSym and sfSystemModule in getModule(n.sym).flags)
```
Functions in the system module which are not among magics that can raise or cannot  infer their exceptions list will not handle its error after being called.

```nim
proc test =
  var wrong = true

  try:
    if true:
      var x = "1234"
      discard x[1..4]

    wrong = false
  except IndexDefect:
    discard

  doAssert wrong

test()
```
Especially in this case, `discard x[1..4]` doesn't generate `if (NIM_UNLIKELY(*nimErr_)) goto` which is wrong because it should stop immediately so `wrong` is not assigned with `false`.

### CODE REVIEW

**Comment by ringabout** [comment]
It seems to be a more severe bug

```nim
proc main =
  var x = "1234"
  discard x[1..4]
  echo "wtf"

main()
```

image


`echo "wtf"` is executed!!

File: compiler/ast.nim [hunk 1]
```diff
@@ -299,6 +299,7 @@ type
     sfInjectDestructors # whether the proc needs the 'injectdestructors' transformation
     sfNeverRaises     # proc can never raise an exception, not even OverflowDefect
                       # or out-of-memory
+    sfSystemRaisesDefect
```
Comment (arnetheduck) [inline compiler/ast.nim]: what happens to user-defined defects? ie can I declare my own defect and make the bug appear?

Comment (ringabout) [reply compiler/ast.nim]: > what happens to user-defined defects? ie can I declare my own defect and make the bug appear?

You can't. It is not related to user-defined defects. But you can reproduce it by defining a proc raising defects in the system.

There are no bugs outside the system module. The system module is wrongly optimized and ripped off error reporting for defects. It means that the previous optimization on the system functions harms the correctness.

Comment (ringabout) [reply compiler/ast.nim]: `sfSystemRaisesDefect` should be given to all procs in the system which can raise defects. External procs work perfectly fine no matter whether they raise defects or not. There are probably better solutions, though.

Comment (Araq) [reply compiler/ast.nim]: looked into this myself too and there are no better solutions than yours, please proceed.

Comment (ringabout) [reply compiler/ast.nim]: Sure, on it.

Comment (ringabout) [reply compiler/ast.nim]: It is really hard to identify what the group should be. Alternative is to cancel optimizations for public procs (non-magics) in the system.

Comment (ringabout) [reply compiler/ast.nim]: We can come up with a better solution later.
