### PR TITLE
fixes  #20285; prevent oid time overflow at year 2038

### LINKED ISSUE #20285: Tests fail in 2038
### What happened?

As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +16 years, because that is how long I expect some software will be used in some places.
This showed up failing tests in our `nim` package build.
See https://reproducible-builds.org/ for why this matters.

### Nim Version

nim-1.6.6

### Current Standard Output Logs

```shell
[Suite] inet_ntop tests
 megatest:processing: [469] tests/stdlib/tnre.nim
 megatest:processing: [470] tests/stdlib/toids.nim
 oids.nim(82)             oids
 fatal.nim(53)            sysFatal
 Error: unhandled exception: value out of range: 2168246819 notin -2147483648 .. 2147483647 [RangeDefect]
```
```


### Expected Standard Output Logs

_No response_

### Possible Solution

Ensure timestamps are processed as 64-bit values.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #20285
ref https://github.com/py-bson/bson/pull/117

### CODE REVIEW

**Comment by ringabout** [comment]
I reproduce the issue by setting the date on my computer to year 2038.

**Comment by Varriount** [comment]
Is it possible to add a test for this?

**Comment by ringabout** [comment]
I guess not too easy, at least we probably can get one at openSUSE :)

File: lib/pure/oids.nim [hunk 1]
```diff
@@ -74,7 +74,7 @@ proc `$`*(oid: Oid): string =
 
 
 let
-  t = getTime().toUnix.int32
+  t = cast[int32](getTime().toUnix)
```
Comment (Varriount) [inline lib/pure/oids.nim]: So, I'm a bit confused here - won't this *ignore* overflow, rather than prevent it?

Comment (ringabout) [reply lib/pure/oids.nim]: The internal uses 32 bits to store time stamp, we have to stick with it.

Only the last 32 bits are considered, which means if the number exceed 4294967296, it is like starting a new round of counting. For `genOid`, it doesn't require monotonically increasing time, an almost unique time stamp is good enough.

Comment (Varriount) [reply lib/pure/oids.nim]: I feel like this is a limitation that should be corrected - wouldn't it be better to simply modify the OID structure to use a 64-bit integer?

Comment (metagn) [reply lib/pure/oids.nim]: As said in the original issue, making the timestamp different than 32 bit would make it incompatible with MongoDB's specification of the structure, which is what this module is based on.

To make the cast "safer" we can do `cast[int32](getTime().toUnix and 0xFFFFFFFF)`.

**Comment by metagn** [comment]
Can we use the [date command](https://unix.stackexchange.com/questions/151547/linux-set-date-through-command-line) to test it?

edit: lol, [the last commit](https://github.com/nim-lang/Nim/pull/20338/commits/dfcdb6ec2ab6a5fa53b6a99294a84fd122be8f8d) says it was made on Sep 12, 2038

File: lib/pure/oids.nim (hunk 1 above)
Comment (Varriount) [reply lib/pure/oids.nim]: What does MongoDB do in this situation, do you know?

Comment (Araq) [reply lib/pure/oids.nim]: At this point, it's fine to abandon the idea of MongoDB interop. I only tried to say that's where the code came from so don't blame me for its misdesigns.

Comment (metagn) [reply lib/pure/oids.nim]: I mean this only becomes an issue in 2038.

We can use `cast[int32] ` for the existing Oid structure, then we can add a new Oid64 structure, which is the same but with an int64 timestamp instead of int32.

**Comment by Varriount** [comment]
I'm ok with either:
  - Matching whatever behavior MongoDB exhibits (as long as the behavior isn't "raise an exception")
  - Increasing the underlying integer size to 64 bits.

**Comment by Araq** [comment]
I say, please increase the underlying integer size to 64 bits.

**Comment by ringabout** [comment]
Sure

**Comment by ringabout** [comment]
Once again, I set the system date to 2038 and there is no problem.

File: changelog.md [hunk 2]
```diff
@@ -54,6 +54,8 @@
 - `strutils.find` now uses and defaults to `last = -1` for whole string searches,
   making limiting it to just the first char (`last = 0`) valid.
 - `random.rand` now works with `Ordinal`s.
+- `std/oids` now uses `int64` to store time internally (before it was int32), the length of
+  the string form of `Oid` changes from 24 to 32.
```
Comment (metagn) [inline changelog.md:58]: This makes oids backwards incompatible with strings created with it on older versions. Someone will inevitably complain about this.

Comment (ringabout) [reply changelog.md:58]: Fine, let me revert this change.

Comment (metagn) [reply changelog.md:58]: It's fine, you can just support 24 length strings as well as 32.

Comment (ringabout) [reply changelog.md:58]: Yeah, I can only generate 32 length strings when necessary.

Comment (ringabout) [reply changelog.md:58]: done => https://github.com/nim-lang/Nim/pull/20546
