### PR TITLE
fix #14339, #13511, #14420: fixes limited VM support for addr

### LINKED ISSUE #13511: Doc Comment in Template Causes Compilation Failure
A doc comment in the template `foo` causes a compilation failure.

### Example
```nim
import macros

type
  Builder = ref object
    components: seq[Component]
  Component = object

proc add(builder: var Builder, component: Component) {.compileTime.} =
  builder.components.add(component)

macro debugAst(arg: typed): untyped =
  ## just for debugging purpose.
  echo arg.treeRepr
  return arg

static:
  var component = Component()
  var builder = Builder()

  template foo(): untyped =
    ## this doc comment causes compilation failure.
    builder

  debugAst:
    add(foo(), component)
```

### Current Output
```
StmtList
  Call
    Sym "add"
    HiddenAddr
      StmtListExpr
        Empty
        Sym "builder"
    Sym "component"
stack trace: (most recent call last)

/tmp/scratch.nim(25, 9) Error: limited VM support for 'addr'
```

If I delete the doc comment, or convert it to a normal comment, the output is the following:

```
StmtList
  Call
    Sym "add"
    HiddenAddr
      Sym "builder"
    Sym "component"
```

The only difference here is, the `StmtListExpr` is missing.

### Possible Solution

* The semchecker could optimize away the StmtListExpr.
* Patch vmgen and friends so that it works.

### Additional Information

* This issue is blocking my PR here https://github.com/nim-lang/Nim/pull/7265

If this would be my code, I could easily work around this bug. Builder is a `ref` object and passed as a `var` parameter. This is not necessary and removing either the `ref` or the `var` would fix this specific problem as well. But that is how [argparse](https://github.com/iffy/nim-argparse) is implemented and works. My part is the template with the doc comment. The template is in `system.nim` and I don't like the idea to remove the doc comment. Other people would make a PR to introduce it again and then wonder why CI fails.

```
$ nim -v
Nim Compiler Version 1.1.1 [Linux: amd64]
Compiled at 2020-02-26
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: e4ed19c12fcce046d990a918800d9031706e8b66
active boot switches: -d:release -d:danger
```

### LINKED ISSUE #14339: nimvm: CritBitTree does not work: "limited VM support for 'addr'"
The CritBitTree type does not work at compile time.

### Example
```nim
import critbits
static:
  var strings: CritBitTree[int]
  discard strings.containsOrIncl("foo", 1)
  echo strings["foo"]
```

### Current Output
```
stack trace: (most recent call last)
C:\prog\dali\q_ct01.nim(5, 15) q_ct01
C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\pure\collections\critbits.nim(196, 3) []
C:\Users\Mateusz\.choosenim\toolchains\nim-1.2.0\lib\pure\collections\critbits.nim(196, 3) Error: limited VM support for 'addr'
```

### Expected Output
```
1
```

### Additional Information

* I am [using CritBitTree][dali] in my project [dali][], which allows emitting Android .dex files from Nim. I would like to be able to emit .dex files at compile time, when writing Android apps in Nim. Currently, I have to instead:
  - generate strings with Nim code and emit them to a helper file,
  - [compile and run this auxillary file separately](https://github.com/akavel/hellomello/blob/531e869dd7c04ba6622a23a56c70dada6b0cd49d/hellomello.nimble#L24-L25) to generate the final .dex file.

[dali]: https://github.com/akavel/dali/blob/911fea3b41ca4f9bc8eb2013f7456dff38a65af0/src/dali/dex.nim#L60

*Nim version:*
```
C:\prog\dali>nim -v
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

### LINKED ISSUE #14420: VM and js backend require `result` for lent or var annotations to work
Most of the standard library is working at compile-time and there are checks to ensure that.

Unfortunately from https://github.com/nim-lang/Nim/pull/14417#issuecomment-632125417, `lent` is not supported in the VM.

For example the JSON test will fail with

```Nim
Error: limited VM support for 'addr'
```

This would prevent using `lent` to optimize arrays, sequences, options, "result" types, object variants. All of which have a typical no-copy use-case.

The easy fallback would be to make lent a no-op in the VM.

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #14420 (all snippets are tested in this PR, with c,cpp,js,vm)
* fix #14339 ditto
* fix #13511 ditto
* moved isMainModule in critbits to tests/stdlib/tcritbits.nim
* add regression tests for #14339 in tests/stdlib/tcritbits.nim (critbit snippet) and taddr.nim (generic snippet)
* identified a new related bug that affects js => https://github.com/nim-lang/Nim/issues/16003

## future work
now that #14420 will be closed (all snippets work in all backends), decide whether we still need to do anything about https://github.com/nim-lang/Nim/issues/14420#issuecomment-633711557, which is a separate issue /cc @cooldome

### CODE REVIEW

File: compiler/vm.nim [hunk 1]
```diff
@@ -746,10 +746,13 @@ proc rawExecute(c: PCtx, start: int, tos: PStackFrame): TFullReg =
       regs[ra].regAddr = addr(regs[rb])
     of opcAddrNode:
       decodeB(rkNodeAddr)
-      if regs[rb].kind == rkNode:
+      case regs[rb].kind
+      of rkNode:
         regs[ra].nodeAddr = addr(regs[rb].node)
+      of rkNodeAddr: # bug #14339
+        regs[ra].nodeAddr = regs[rb].nodeAddr
```
Comment (Clyybber) [inline compiler/vm.nim:753]: Doesn't that mean that when you do `somePtr = addr someOtherPtr` it will behave like `somePtr = someOtherPtr`?

Comment (timotheecour) [reply compiler/vm.nim:753]: I don't believe so; eg:
```nim
when true:
  type Foo = ref object
    f0: int
  proc main=
    var f = Foo(f0: 3)
    var f2 = f.addr
    var f3 = f2.addr
    var f4 = f3
    f4.f0 += 1 # like f3.f0
    f4[].f0 += 1 # like f2.f0
    f4[][].f0 += 1 # like f.f0
    f4[][][].f0 += 1 # like f[].f0
    doAssert f[].f0 == 7
  static: main()
  main()
```

=> CT behaves like RT

Comment (Clyybber) [reply compiler/vm.nim:753]: Hmm, I'm struggling to come up with a concrete example, but please explain why it is correct (?) and maybe add a comment.
Your example isn't exactly convincing because `f4` is `ptr ptr Foo` and it gets automatically dereferenced. If you change `Foo` to be a non-ref object it fails.

Comment (timotheecour) [reply compiler/vm.nim:753]: > If you change Foo to be a non-ref object it fails.

just filed https://github.com/nim-lang/Nim/issues/16020, but this is a pre-existing bug and this PR exercises a different code path, see https://gist.github.com/timotheecour/fc575c054cddba5bea32df98d1c50cdc

> Hmm, I'm struggling to come up with a concrete example, but please explain why it is correct (?) and maybe add a comment.

TODO on me

Comment (timotheecour) [reply compiler/vm.nim:753]: @Clyybber my understanding is there's an implicit deref that occurs in code paths that lead here due to semantic transform that generates a temporary for block return expressions (without `result = expr` or return expr`)
eg:

```nim
when true: # D20201125T111240
  template main() =
    type
      Node = ref object
        val: int
    proc bar(c: Node): var int =
      discard
      c.val #  before PR: Error: limited VM support for 'addr' (but nim was pointing at wrong lineinfo)
    var a = Node()
    discard a.bar()
  static: main()
```

which is transformed into:
```nim
proc bar(c: Node): var int =
  result = block:
    discard
    c.val
```
instead of:
```nim
proc bar(c: Node): var int =
  discard
  result = c.val
```

this seems related to https://github.com/nim-lang/Nim/issues/16137

This PR is still good IMO (more things now work, and hopefully nothing breaks), but I agree that the code transformation needs to be revisited as @cooldome mentioned here: https://github.com/nim-lang/Nim/issues/14420#issuecomment-633711557

Comment (Clyybber) [reply compiler/vm.nim:753]: The code transformation is correct and is not what my question is about.
I'm asking how treating `... = addr someAddress` as if it were `... = someAddress` is correct/sound here.
