### PR TITLE
Added heapqueue collection. Fixed timers in asyncdispatch.

### LINKED ISSUE #4120: sleepAsync sleeps for too long
Tested on macos:
```nim
import asyncdispatch
import times

proc main() {.async.} =
    echo "1: ", epochTime()
    await sleepAsync(1) # wait for 1 ms. Actual result (see below): ~500 ms
    echo "2: ", epochTime()
    await sleepAsync(1) # wait for 1 ms.  Actual result (see below): ~500 ms
    echo "3: ", epochTime()

asyncCheck main()

runForever()
```
```
nim c -r ~/test.nim
```
```
1: 1461774804.308667
2: 1461774804.81404
3: 1461774805.315593
```

### PR DESCRIPTION
**Pull request by yglukhov**
Fixes #4120

### CODE REVIEW

**Comment by cheatfate** [comment]
Do you made any benchmarks on your timers?

**Comment by yglukhov** [comment]
@cheatfate, I can't see what to benchmark here. My small private tool that relies on intensive polling  (check and sleep with adaptive (close to zero) timeout) shows 600 polls/sec, instead of 2-3 polls/sec as it was before the fix. Timer addition takes log n instead of 1, and timers processing is log n (close to 1 in reality) instead of n, timeout adjustment before polling (new functionality that fixes this bug) is 1. Basically this PR fixes a logic bug, it's not intended to change overall performance really.

File: lib/pure/collections/heapqueue.nim [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+
+proc heapCmp[T](x, y: T): bool {.inline.} =
+  return (x < y)
+
+# 'heap' is a heap at all indices >= startpos, except possibly for pos.  pos
+# is the index of a leaf with a possibly out-of-order value.  Restore the
+# heap invariant.
+proc siftdown[T](heap: var HeapQueue[T], startpos, p: int) =
+  var pos = p
+  var newitem = heap[pos]
```
Comment (Araq) [inline lib/pure/collections/heapqueue.nim]: system.shallowCopy is faster than '='  for these things usually, where data is only moved around internally.

File: lib/pure/collections/heapqueue.nim [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+  let newitem = heap[pos]
+  # Bubble up the smaller child until hitting a leaf.
+  var childpos = 2*pos + 1    # leftmost child position
+  while childpos < endpos:
+    # Set childpos to index of smaller child.
+    let rightpos = childpos + 1
+    if rightpos < endpos and not heapCmp(heap[childpos], heap[rightpos]):
+      childpos = rightpos
+    # Move the smaller child up.
+    heap[pos] = heap[childpos]
```
Comment (Araq) [inline lib/pure/collections/heapqueue.nim]: Same.
