### PR TITLE
fix #15333

### LINKED ISSUE #15333: uri.nim url with literal ipv6 address is printed wrong, and cannot parsed again
When url with ipv6 address is converted to string, the hostname enclosing
"[", and "]" are missing.
This makes the url unparseable.

### Example
```nim
import uri

let org = "udp://[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:8080"
let url = parseUri(org)
echo $url # udp://2001:0db8:85a3:0000:0000:8a2e:0370:7334:8080
echo $url.hostname == "2001:0db8:85a3:0000:0000:8a2e:0370:7334" # true
echo parseUri($url) # udp://2001:0db885a3000000008a2e037073348080
```

```
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-09-13
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

File: lib/pure/uri.nim [hunk 1]
```diff
@@ -52,10 +52,14 @@ include includes/decode_helpers
 type
   Url* = distinct string
 
+  IpKind* = enum
```
Comment (Araq) [inline lib/pure/uri.nim]: You unconditionally export this symbol.

Comment (ringabout) [reply lib/pure/uri.nim]: I will remove `IpKind` and use `initUri(useIpv6: bool)` for compatibility.
