### PR TITLE
Fix #12135 and #12109

### LINKED ISSUE #12109: posix.Time is defined as `clong` on OpenBSD when it should be a `long long`
On OpenBSD, `posix.Time` is defined as a `clong` (due to [`posix_other.nim`](https://github.com/nim-lang/Nim/blob/bc7733827d12152130fc3aad5412c9ea8aef26e5/lib/posix/posix_other.nim#L37)), where OpenBSD [defines](https://github.com/openbsd/src/blob/b66614995ab119f75167daaa7755b34001836821/sys/sys/_types.h#L64) it as a [`__int64_t`](https://github.com/openbsd/src/blob/master/sys/arch/amd64/include/_types.h#L67) which is `long long` on AMD64.

This results in errors like below:

```
/home/build/.cache/nim/tasync_cpp_d/stdlib_times.nim.cpp:1509:19: error: no matching function for call to 'localtime'
        struct tm* T2_ = localtime((&a));
                         ^~~~~~~~~
/usr/include/time.h:131:12: note: candidate function not viable: no known conversion from 'long *' to 'const time_t *' (aka 'const long long *') for 1st argument
struct tm *localtime(const time_t *);
```

Note that it [looks like FreeBSD may also be the same](https://github.com/freebsd/freebsd/blob/master/sys/x86/include/_types.h#L66) under certain circumstances, though I'm not sure?

### Possible Solution

A new `posix_openbsd_amd64` module should be added to define `time_t` correctly, along with any other different values.

### LINKED ISSUE #12135: `pthread_key_t` errors on OpenBSD
Running tests on OpenBSD results in quite a lot of errors such as below:

```
Category: dll
Name: tests/dll/client.nim C --gc:boehm --threads:on
Action: run
Result: reNimcCrash
-------- Expected -------

--------- Given  --------
$ /home/administrator/build/Nim/bin/nim c --debuginfo --hints:on --define:useNimRtl --gc:boehm --threads:on --nimCache:nimcache/tests/dll/client.nim_b72fd7d9778886456f94711ee41aadba tests/
dll/client.nim
Hint: used config file '/home/administrator/build/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/administrator/build/Nim/tests/dll/client.nim.cfg' [Conf]
Hint: used config file '/home/administrator/build/Nim/config/config.nims' [Conf]
Hint: used config file '/home/administrator/build/Nim/tests/config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: client [Processing]
client.nim(24, 6) Hint: 'newOp' is declared but not used [XDeclaredButNotUsed]
client.nim(23, 6) Hint: 'newLit' is declared but not used [XDeclaredButNotUsed]
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: client.nim
Error: execution of an external compiler program 'clang -c  -w -pthread -g  -I/home/administrator/build/Nim/lib -I/home/administrator/build/Nim/tests/dll -o /home/administrator/build/Nim/n
imcache/tests/dll/client.nim_b72fd7d9778886456f94711ee41aadba/stdlib_system.nim.c.o /home/administrator/build/Nim/nimcache/tests/dll/client.nim_b72fd7d9778886456f94711ee41aadba/stdlib_syst
em.nim.c' failed with exit code: 1

/home/administrator/build/Nim/nimcache/tests/dll/client.nim_b72fd7d9778886456f94711ee41aadba/stdlib_system.nim.c:174:1: error: unknown type name 'pthread_key_t'
pthread_key_t globalsSlot__ciXDZu9c27pHpCRMoz4RIgw;
^
1 error generated.
```

This is because `pthread_key_t` is defined in [`pthread.h` on OpenBSD](https://github.com/openbsd/src/blob/master/include/pthread.h) rather than [in `sys/types.h`](https://github.com/nim-lang/Nim/blob/79f1b8592a24e878fd886127708929d7fc613842/lib/posix/posix_other.nim#L164).

### Possible Solution

As with #12109, a new `posix_openbsd_amd64` module should be added to define `pthread_key_t` correctly.

### PR DESCRIPTION
**Pull request by euantorano**
Fixes #12135 and fixes #12109 

Note that the `posix_other_consts` file is used (the same goes for `posix_macos_amd64`) as I can't get `detect.nim` to run on OpenBSD.

### CODE REVIEW

File: lib/system/threadlocalstorage.nim [hunk 1]
```diff
@@ -132,6 +132,13 @@ else:
         abi: array[56 div sizeof(clong), clong]
       ThreadVarSlot {.importc: "pthread_key_t",
                     header: "<sys/types.h>".} = distinct cuint
+  elif defined(openbsd) and defined(amd64):
+    type
+      SysThread* {.importc: "pthread_t", header: "<pthread.h>".} = object
```
Comment (Araq) [inline lib/system/threadlocalstorage.nim]: https://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread.h.html


The pthread_attr_t, pthread_cond_t, pthread_condattr_t, pthread_key_t, pthread_mutex_t, pthread_mutexattr_t, pthread_once_t, pthread_rwlock_t, pthread_rwlockattr_t and pthread_t types are defined as described in <sys/types.h>.

Comment (euantorano) [reply lib/system/threadlocalstorage.nim]: @Araq Yes, that is true on most systems. However, OpenBSD is a little different. Please see the below links:

- [`pthread.h`](https://github.com/openbsd/src/blob/b66614995ab119f75167daaa7755b34001836821/include/pthread.h#L95) - see the type definitions from the linked line downwards
- [A search for `pthread_key_t` in the OpenBSD source](https://github.com/openbsd/src/search?l=C&p=1&q=pthread_key_t) - note the only definition is in pthread.h`
- [`sys/types.h`](https://github.com/openbsd/src/blob/master/sys/sys/types.h) - note no references to `pthread` at all

I amde this PR after actually trying the tests on OpenBSD and having them fail due to `pthread_key_t` being undefined in `sys/types.h`. This PR is the only way to make the tests pass on OpenBSD (see the error message in the linked issue for a stacktrace and compiler output - #12135)

Comment (euantorano) [reply lib/system/threadlocalstorage.nim]: Additionally, it seems FreeBSD [used to be the same, circa 2005](https://lists.freebsd.org/pipermail/freebsd-threads/2005-March/002958.html).

Comment (narimiran) [reply lib/system/threadlocalstorage.nim]: @Araq what is the status of this one?

**Comment by Araq** [comment]
Sorry for the delay.
