### PR TITLE
[sugar] handle HiddenDeref in capture, error at CT if unsupported nnk

### LINKED ISSUE #20679: capture macro assumes ident leading to strVal error
### What happened?

I was trying to use the capture macro to capture a var param of the enclosing proc, which does not work.

Error: `node lacks field: strVal`

```nim
from sugar import capture
proc function(data: var int) =
  capture data:
    discard
```

My current workaround if using the capture macro is to avoid `var`.

### Nim Version

Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-10-14
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: be18f4e513799de186e6de53f32c9488b19f1ec7
active boot switches: -d:release

### Current Standard Output Logs

_No response_

### Expected Standard Output Logs

_No response_

### Possible Solution

_No response_

### Additional Information

Submitted at the suggestion of @Vindaar

### PR DESCRIPTION
**Pull request by Vindaar**
Instead of running into trouble of the `.strVal` access failing, it's better to error at CT.

Personally, I'd add the node kind that was encountered to the error message, but afaik we typically try to avoid "leaking" such implementation details to the user?

Fixes #20679.

### CODE REVIEW

File: lib/pure/sugar.nim [hunk 1]
```diff
@@ -231,9 +231,15 @@ macro capture*(locals: varargs[typed], body: untyped): untyped {.since: (1, 1).}
   let locals = if locals.len == 1 and locals[0].kind == nnkBracket: locals[0]
                else: locals
   for arg in locals:
-    if arg.strVal == "result":
+    var argStr = ""
+    case arg.kind
+    of nnkIdent, nnkSym: argStr = arg.strVal
+    of nnkHiddenDeref: argStr = arg[0].strVal
+    else:
+      error("The argument to be captured `" & arg.repr & "` is not a pure identifier.", arg)
```
Comment (Varriount) [inline lib/pure/sugar.nim]: Could this be expanded a bit? Maybe something like "complex expressions are not currently supported", or something along those lines?

Comment (Vindaar) [reply lib/pure/sugar.nim]: Yeah, I'm open to suggestions. I'm mainly not sure about how to phrase it without becoming overly long. I didn't write something like "complex expression", because I'm worried that some other node kind will also "look" like an identifier, but isn't. That could be more misleading than not.

Comment (Varriount) [reply lib/pure/sugar.nim]: Does `arg.repr` print the node kind? It might be enough to add that, if nothing else.

Comment (Vindaar) [reply lib/pure/sugar.nim]: `repr` doesn't, no. Depending on the node kind it is even pretty confusing, because it will just look like an identifier for example (like in the `nnkHiddenDeref` case) . But one could add an `$arg.kind`  to print the kind. As I alluded to in the opening though, I'm not sure if the stdlib anywhere prints this kind of information. I personally do it in my own macros though, as I find it useful.

File: lib/pure/sugar.nim [hunk 2]
```diff
@@ -231,9 +231,15 @@ macro capture*(locals: varargs[typed], body: untyped): untyped {.since: (1, 1).}
   let locals = if locals.len == 1 and locals[0].kind == nnkBracket: locals[0]
                else: locals
   for arg in locals:
-    if arg.strVal == "result":
+    var argStr = ""
+    case arg.kind
+    of nnkIdent, nnkSym: argStr = arg.strVal
+    of nnkHiddenDeref: argStr = arg[0].strVal
```
Comment (Araq) [inline lib/pure/sugar.nim]: You don't know that the inner node is nnkIdent or nnkSym. What about `var seq[int]`?

Comment (Vindaar) [reply lib/pure/sugar.nim]: Fair.

Comment (Vindaar) [reply lib/pure/sugar.nim]: Well, in the particular case of `var seq[int]`, it's still the same AST (apparently), so `arg[0]` seems valid. But I'm pushing a small fix.

File: lib/pure/sugar.nim (hunk 1 above)
Comment (Vindaar) [reply lib/pure/sugar.nim]: @Varriount I've extended the error message a bit.
