### PR TITLE
fix #16758 Nim crashes in fixAbstractType

### LINKED ISSUE #16758: Nim crashes in fixAbstractType
```nim
import macros

type BlockLiteral[T] = object
  p: T

iterator arguments(formalParams: NimNode): NimNode =
  var iParam = 0
  for i in 1 ..< formalParams.len:
    let pp = formalParams[i]
    for j in 0 .. pp.len - 3:
      yield pp[j]
      inc iParam

macro implementInvoke(T: typedesc): untyped =
  let t = getTypeImpl(T)[1]

  let call = newCall(newDotExpr(ident"blk", ident"p"))
  let params = copyNimTree(t[0])
  result = newProc(ident"invoke", body = call)

  for n in arguments(params):
    call.add(n)

  params.insert(1, newIdentDefs(ident"blk", newTree(nnkBracketExpr, bindSym"BlockLiteral", T)))
  result.params = params

proc getInvoke(T: typedesc) =
  implementInvoke(T)

getInvoke(proc(a: int))
```
```
nim c test.nim
```
```
.../nim-devel/compiler/nim.nim(119) nim
.../nim-devel/compiler/nim.nim(84) handleCmdLine
.../nim-devel/compiler/main.nim(234) mainCommand
.../nim-devel/compiler/main.nim(205) compileToBackend
.../nim-devel/compiler/main.nim(88) commandCompileToC
.../nim-devel/compiler/modules.nim(177) compileProject
.../nim-devel/compiler/modules.nim(102) compileModule
.../nim-devel/compiler/passes.nim(180) processModule
.../nim-devel/compiler/passes.nim(73) processTopLevelStmt
.../nim-devel/compiler/sem.nim(606) myProcess
.../nim-devel/compiler/sem.nim(574) semStmtAndGenerateGenerics
.../nim-devel/compiler/semstmts.nim(2306) semStmt
.../nim-devel/compiler/semexprs.nim(1029) semExprNoType
.../nim-devel/compiler/semexprs.nim(2865) semExpr
.../nim-devel/compiler/semstmts.nim(2248) semStmtList
.../nim-devel/compiler/semexprs.nim(2766) semExpr
.../nim-devel/compiler/semexprs.nim(1010) semDirectOp
.../nim-devel/compiler/semexprs.nim(849) semOverloadedCallAnalyseEffects
.../nim-devel/compiler/semcall.nim(573) semOverloadedCall
.../nim-devel/compiler/semcall.nim(531) semResolvedCall
.../nim-devel/compiler/seminst.nim(388) generateInstance
.../nim-devel/compiler/seminst.nim(148) instantiateBody
.../nim-devel/compiler/semexprs.nim(1785) semProcBody
.../nim-devel/compiler/semexprs.nim(2865) semExpr
.../nim-devel/compiler/semstmts.nim(2248) semStmtList
.../nim-devel/compiler/semexprs.nim(2753) semExpr
.../nim-devel/compiler/semexprs.nim(1011) semDirectOp
.../nim-devel/compiler/semexprs.nim(893) afterCallActions
.../nim-devel/compiler/sem.nim(474) semMacroExpr
.../nim-devel/compiler/sem.nim(417) semAfterMacroCall
.../nim-devel/compiler/semexprs.nim(2883) semExpr
.../nim-devel/compiler/semstmts.nim(2086) semProc
.../nim-devel/compiler/semstmts.nim(2005) semProcAux
.../nim-devel/compiler/semexprs.nim(1785) semProcBody
.../nim-devel/compiler/semexprs.nim(2780) semExpr
.../nim-devel/compiler/semexprs.nim(1003) semIndirectOp
.../nim-devel/compiler/semexprs.nim(623) fixAbstractType
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
FAILURE
```

Reproduces with nim 1.4.2 and 1.2.8

### PR DESCRIPTION
**Pull request by bung87**
fix #16758

can't have better message here for macro.

### CODE REVIEW

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -670,6 +670,8 @@ proc semArrayConstr(c: PContext, n: PNode, flags: TExprFlags; expectedType: PTyp
 proc fixAbstractType(c: PContext, n: PNode) =
   for i in 1..<n.len:
     let it = n[i]
+    if it == nil:
+      localError(c.config, n.info, "'$1' has nil child at index $2" % [renderTree(n, {renderNoComments}), $i])
```
Comment (Araq) [inline compiler/semexprs.nim:674]:
```suggestion
      localError(c.config, n.info, "'$1' has nil child at index $2" % [renderTree(n, {renderNoComments}), $i])
      return
```
