### PR TITLE
fix #13100 nim doc now treats `export localSymbol` correctly

### LINKED ISSUE #13100: `nim doc` treats `export localSymbol` incorrectly
`nim doc` treats `export localSymbol` incorrectly

### Example
```nim
proc fun1()=discard
proc fun2*()=discard
export fun1
```

### Current Output
shows `fun1` in exports section instead of in procs section;
what's even worse is there'll be no way of showing the symbol definition since it belongs to the same module

### Expected Output
fun1 should be shown just like fun2, in the `procs` section (in this specific example), not as a "naked" symbol in exports list

### Additional Information
* devel a33b72af4960073b0dca95af3b430baade745b0b
* this was discussed in https://github.com/nim-lang/Nim/pull/13000#issuecomment-570253710 ; the workarounds are not DRY
* after this is fixed, we should undo the workaround duplication done in https://github.com/nim-lang/Nim/pull/13000 in https://github.com/nim-lang/Nim/pull/13000/commits/56e37804b416e055ba24ae753b12f0e2e1a121e5 and use `export normalizePathEnd ` /cc @disruptek

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #13100

### CODE REVIEW

File: compiler/docgen.nim [hunk 1]
```diff
@@ -886,7 +892,12 @@ proc generateDoc*(d: PDoc, n, orig: PNode) =
     for it in n: traceDeps(d, it)
   of nkExportStmt:
     for it in n:
-      if it.kind == nkSym: exportSym(d, it.sym)
+      if it.kind == nkSym:
+        let ast = it.sym.ast
+        if ast != nil and it.info.fileIndex == ast.info.fileIndex:
```
Comment (Araq) [inline compiler/docgen.nim]: No, but close. Check the it.sym.owner field instead.

Comment (timotheecour) [reply compiler/docgen.nim]: done; had to add some logic to expose `module`

**Comment by timotheecour** [comment]
PTAL, added logic to expose `module` so that i can use `owner`
