### PR TITLE
Propagate the outDir to rstgen to fix hrefs for modules in subdirs

### LINKED ISSUE #14434: `nim doc --index` generates incorrect module href, fooled by doc comments
`nim doc --index` generates incorrect module href, fooled by doc comments

the symbol href's are correct, but not the module hrefs, see below

### Example
```nim
nim doc --project --outdir:/tmp/d57 --index:on nimdoc/testproject/testproject.nim
nim buildIndex -o:/tmp/d57/theindex.html /tmp/d57

grep utils.html /tmp/d57/theindex1.html
```

### Current Output
```
    Modules: <a href="testproject.html">testproject</a>, <a href="utils.html">utils</a>.<br/><p /><h2>API symbols</h2>
          data-doc-search-tag="utils: aEnum(): untyped" href="subdir/subdir_b/utils.html#aEnum.t">utils: aEnum(): untyped</a></li>
          data-doc-search-tag="utils: bEnum(): untyped" href="subdir/subdir_b/utils.html#bEnum.t">utils: bEnum(): untyped</a></li>
```

### Expected Output
```
href="utils.html"
should be
href="subdir/subdir_b/utils.html"
```

### Additional Information
* 1.3.5 c61f7466292cb19c910f4a2f2976f738796e6bdf
* discovered while working on https://github.com/nim-lang/Nim/pull/14324

the bug is already in `/tmp/d57/subdir/subdir_b/utils.idx` which shows
```
This is now a header	utils.html#this-is-now-a-header	 This is now a header	
Next header	utils.html#this-is-now-a-header-next-header	  Next header	
And so on	utils.html#next-header-and-so-on	   And so on	
More headers	utils.html#more-headers	 More headers	
Up to level 6	utils.html#more-headers-up-to-level-6	      Up to level 6	
enumValueA	subdir/subdir_b/utils.html#enumValueA	SomeType.enumValueA	
```

the bug disappears if we simplify the module level doc comment in nimdoc/testproject/subdir/subdir_b/utils.nim

eg:
bug:

```
##[

## Next header

]##
```

no bug:

```
## Next header
```

bug is probably in or around `setIndexTerm`

### PR DESCRIPTION
**Pull request by kaushalmodi**
Fixes https://github.com/nim-lang/Nim/issues/14434

- Propagates the conf.outDir from docgen to rstgen so that the output HTML file paths relative to the outDir can be derived correctly.
- Updated the tests
- Added the missing .idx files to the docgen tests.

/cc @timotheecour

### CODE REVIEW

File: lib/packages/docutils/rstgen.nim [hunk 1]
```diff
@@ -755,7 +757,12 @@ proc renderHeadline(d: PDoc, n: PRstNode, result: var string) =
 
   # Generate index entry using spaces to indicate TOC level for the output HTML.
   assert n.level >= 0
-  setIndexTerm(d, changeFileExt(extractFilename(d.filename), HtmlExt), refname, tmp.stripTocHtml,
+  let
+    htmlFileRelPath = if d.destBaseDir != "".AbsoluteDir: # d is initialized in docgen
```
Comment (timotheecour) [inline lib/packages/docutils/rstgen.nim]: for next time (or in cleanup PR) you can use `isEmpty`

Comment (kaushalmodi) [reply lib/packages/docutils/rstgen.nim]: Thanks, I have force-pushed an edit with your suggestion.

File: lib/packages/docutils/rstgen.nim [hunk 2]
```diff
@@ -57,6 +57,8 @@ type
     options*: RstParseOptions
     findFile*: FindFileHandler
     msgHandler*: MsgHandler
+    destBaseDir*: AbsoluteDir
+    destFile*: AbsoluteFile
     filename*: string
```
Comment (timotheecour) [inline lib/packages/docutils/rstgen.nim]: maybe add doc comments to explain what `filename` is (i'm guessing it's the source file)

Comment (kaushalmodi) [reply lib/packages/docutils/rstgen.nim]: yes.. it was already there though. I'll still document it.

File: lib/packages/docutils/rstgen.nim [hunk 3]
```diff
@@ -57,6 +57,8 @@ type
     options*: RstParseOptions
     findFile*: FindFileHandler
     msgHandler*: MsgHandler
+    destBaseDir*: AbsoluteDir
```
Comment (timotheecour) [inline lib/packages/docutils/rstgen.nim]: is that different from `thisDir` ?
EDIT: ya, looks like it is, thisDir seems to be `destFile.parentDir` whereas
`destBaseDir` is the root of docs (eg `/pathto/htmldocs`); 

can we get rid of `thisDir` ? (could be done in different PR though) since it looks over-specified now that we have (destBaseDir, destFile, thisDir)

```nim
proc externalDep(d: PDoc; module: PSym): string =
  if optWholeProject in d.conf.globalOptions or d.conf.docRoot.len > 0:
    let full = AbsoluteFile toFullPath(d.conf, FileIndex module.position)
    let tmp = getOutFile2(d.conf, presentationPath(d.conf, full), HtmlExt,
                          htmldocsDir, sfMainModule notin module.flags)
    result = relativeTo(tmp, d.thisDir, '/').string
  else:
    result = extractFilename toFullPath(d.conf, FileIndex module.position)
```

File: lib/packages/docutils/rstgen.nim (hunk 2 above)
Comment (kaushalmodi) [reply lib/packages/docutils/rstgen.nim]: Done.

File: lib/packages/docutils/rstgen.nim (hunk 3 above)
Comment (kaushalmodi) [reply lib/packages/docutils/rstgen.nim]: - `thisDir` is the directory containing the nested Nim file. I am mapping `d.conf.outDir` from `docgen` to the new `d.outDir` in rstgen
- Also rstgen cannot "see" `thisDir`

File: lib/packages/docutils/rstgen.nim [hunk 4]
```diff
@@ -57,7 +57,9 @@ type
     options*: RstParseOptions
     findFile*: FindFileHandler
     msgHandler*: MsgHandler
-    filename*: string
+    destBaseDir*: AbsoluteDir   ## output directory, initialized by docgen.nim
+    destFile*: AbsoluteFile     ## output (HTML) file, initialized by docgen.nim
+    filename*: string           ## source Nim file
```
Comment (timotheecour) [inline lib/packages/docutils/rstgen.nim]: source file (nim or rst)

File: lib/packages/docutils/rstgen.nim (hunk 3 above)
Comment (kaushalmodi) [reply lib/packages/docutils/rstgen.nim]: May be I should refactor destBaseDir to outDir.. it's clear that way.

**Update**: Done.

File: lib/packages/docutils/rstgen.nim [hunk 5]
```diff
@@ -57,7 +57,9 @@ type
     options*: RstParseOptions
     findFile*: FindFileHandler
     msgHandler*: MsgHandler
-    filename*: string
+    destBaseDir*: AbsoluteDir   ## output directory, initialized by docgen.nim
```
Comment (timotheecour) [inline lib/packages/docutils/rstgen.nim]: examples always help, and would immediately clarify the only subtle point (which is that it's not destFile.parentDir), eg:
/pathto/htmldocs for destBaseDir
/pathto/htmldocs/sub1/sub2/strutils.html for destFile

File: lib/packages/docutils/rstgen.nim (hunk 4 above)
Comment (kaushalmodi) [reply lib/packages/docutils/rstgen.nim]: I have fixed this now.

File: lib/packages/docutils/rstgen.nim [hunk 6]
```diff
@@ -57,7 +57,9 @@ type
     options*: RstParseOptions
     findFile*: FindFileHandler
     msgHandler*: MsgHandler
-    filename*: string
+    outDir*: AbsoluteDir      ## output directory, initialized by docgen.nim
+    destFile*: AbsoluteFile   ## output (HTML) file, initialized by docgen.nim
+    filename*: string         ## source Nim file
```
Comment (timotheecour) [inline lib/packages/docutils/rstgen.nim]: source file (nim or rst)

File: lib/packages/docutils/rstgen.nim (hunk 5 above)
Comment (timotheecour) [reply lib/packages/docutils/rstgen.nim]: ok now that you've renamed as outDir it's kind of clear

File: lib/packages/docutils/rstgen.nim (hunk 6 above)
Comment (kaushalmodi) [reply lib/packages/docutils/rstgen.nim]: This is now fixed.

File: lib/packages/docutils/rstgen.nim (hunk 5 above)
Comment (kaushalmodi) [reply lib/packages/docutils/rstgen.nim]: Also, I have a little example in the if/else block that I've added in this PR.

https://github.com/nim-lang/Nim/pull/14479/commits/81451f5e132cdcb27afb95091061c61710b9032c#diff-1c214d03fff81766e9939144754ac7dfR761-R767

**Review by timotheecour — APPROVED** [review]
LGTM, thanks!

**Comment by timotheecour** [comment]
awesome thanks!
I still think the path handling in docgen should be simplified further, in future PRs:
* assume outDir is always provided and valid (and `doAssert not outdir.isEmpty`); IIRC that should've been enabled by https://github.com/nim-lang/Nim/pull/14324/files#diff-33add683a8c2129be4da4f1a7d8a83c4R240 and remove all the if outdir is empty or similar branches
* deprecated `-o:foo` in combination with `--project`, which is buggy; probably make it an error or at least a warning (see https://github.com/nim-lang/Nim/pull/14324/files#diff-3cb9f480d71020c8cd3d36be5bdd73afR1240)
* simplify `updateOutfile`, `docOutDir` and in particular `getOutFile2`

* use absolute paths everywhere => we only need `outDir`+`destFile` (relative paths can be computed on the fly) and we shouldn't need `thisDir` (over-specified)

/cc @kaushalmodi CI failure unrelated (caused by nimble not retrying on 503 https://github.com/timotheecour/Nim/issues/266) but can if you want your PR green restart only the one that failed using https://github.com/timotheecour/Nim/issues/211
