### PR TITLE
close #16607 add testcase

### LINKED ISSUE #16607: Constructing a named tuple of a `requiresInit` type causes destructions before initialization
### Example
```nim
type
  O {.requiresInit.} = object
    initialized: bool

proc `=destroy`(o: var O) =
  doAssert o.initialized, "O was destroyed before initialization!"

proc initO(): O =
  O(initialized: true)

proc pair(): tuple[a, b: O] =
  result.a = initO()
  result.b = initO()

proc main() =
  discard pair()

main()
```

### Current Output
```
/tmp/test.nim(18)        test
/tmp/test.nim(16)        main
/tmp/test.nim(9)         pair
/tmp/test.nim(6)         =destroy
/usr/lib/nim/lib/system/assertions.nim(30) failedAssertImpl
/usr/lib/nim/lib/system/assertions.nim(23) raiseAssert
/usr/lib/nim/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: /tmp/test.nim(6, 12) `o.initialized` O was destroyed before initialization! [AssertionDefect]
```

### Expected Output
```
```

### Additional Information

- Blocking alaviss/nim-sys due to [premature deconstruction](https://github.com/alaviss/nim-sys/runs/1653569539?check_suite_focus=true#step:6:10).
- While it is possible to walkaround the sample by using `result = (initO(), initO())`, applying the walkaround to nim-sys generates runaway `tmp` that are destroyed after `wasMoved()`, which is a different bug that I haven't managed to reduce to a simple sample. See the following `--expandArc` output for more information:
```nim
--expandArc: initPipe

var
  :tmp
  :tmp_1
try:
  var handles`gensym5: array[2, cint]
  var flags`gensym5 = 0
  if not contains(flags, ffInheritable):
    flags`gensym5 = flags`gensym5 or 524288'i32
  if false:
    flags`gensym5 = flags`gensym5 or 2048'i32
  if pipe2(handles`gensym5, flags`gensym5) == -1:
    raise newOSError(errno, "Could not create pipe")
  :tmp = initFile(FD(handles`gensym5[0]))
  :tmp_1 = initFile(FD(handles`gensym5[1]))
  result = (
    let blitTmp = :tmp
    wasMoved(:tmp)
    blitTmp,
    let blitTmp_1 = :tmp_1
    wasMoved(:tmp_1)
    blitTmp_1)
finally:
  `=destroy`(:tmp_1)
  `=destroy`(:tmp)
```

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-01-05
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 2c2baa9fad1d144c42baf30ed004decdf8bb0483
active boot switches: -d:release -d:nimUseLinenoise
```

### PR DESCRIPTION
**Pull request by ringabout**
close #16607

### CODE REVIEW

**Review by timotheecour — APPROVED** [review]

File: tests/destructor/t16607.nim [hunk 1]
```diff
@@ -0,0 +1,22 @@
+discard """
+  matrix: "--gc:refc; --gc:arc"
+"""
+
```
Comment (timotheecour) [inline tests/destructor/t16607.nim:4]:
```suggestion
# bug #16607
```
in followup or this PR please add this

see rationale here https://github.com/nim-lang/Nim/pull/17316/files#r591062106
