### PR TITLE
Fix issue 10726 - HTTP response without Content-Length is not accessible

### LINKED ISSUE #10726: HTTP response without Content-Length is not accessible
When HTTP/1.1 server responds with proper content, but without `Content-Length` header, the response is not accessible, i.e. an empty response is returned.

This response is formally wrong, but for example Curl or Firefox displays the text irregardless.

#### Server
```nim
import asynchttpserver, asyncdispatch, asyncnet

var server = newAsyncHttpServer()
proc cb(req: Request) {.async.} =
  var msg = "HTTP/1.1 " & $Http200 & "\c\L"
  msg.add "\c\L\c\L"
  msg.add("Here comes reply")
  await req.client.send(msg)
  req.client.close()

waitFor server.serve(Port(8080), cb)
```
#### Client

```nim
import httpclient

var client = newHttpClient()
echo client.getContent("http://localhost:8080")
```

### Current Client Output
```
 
```

### Expected Client Output

```
Here comes reply
```

### Possible Solution
I've traced it to this if statement:

https://github.com/nim-lang/Nim/blob/b6d96cafc8bcad1f3d32f2910b25cd11a93f7751/lib/pure/httpclient.nim#L995

Changing it to true, makes the reply available.

### PR DESCRIPTION
**Pull request by konradmb**
Fixes #10726 
Added patch by @xenogenesi and test for AsyncHttpClient.

I've tried to add test for sync HttpClient, but the server wasn't responding.

### CODE REVIEW

File: lib/pure/httpclient.nim [hunk 1]
```diff
@@ -340,7 +340,7 @@ proc parseBody(s: Socket, headers: HttpHeaders, httpVersion: string, timeout: in
 
       # -REGION- Connection: Close
       # (http://tools.ietf.org/html/rfc2616#section-4.4) NR.5
-      if headers.getOrDefault"Connection" == "close" or httpVersion == "1.0":
+      if headers.getOrDefault"Connection" == "close" or (httpVersion == "1.0" or httpVersion == "1.1"):
```
Comment (dom96) [inline lib/pure/httpclient.nim]:
```suggestion
      let implicitConnectionClose =
        httpVersion == "1.0" or
        httpVersion == "1.1" # This doesn't match the HTTP spec, but it fixes issues for non-conforming servers.
      if headers.getOrDefault"Connection" == "close" or implicitConnectionClose:
```

Comment (dom96) [reply lib/pure/httpclient.nim]: Same below.

Comment (konradmb) [reply lib/pure/httpclient.nim]: Done
