### PR TITLE
fixes #25125

### LINKED ISSUE #25125: `strutils.formatSize` returns wrong values from large values close to int64.high
### Nim Version

Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2025-08-27
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: b527db9ddd33fd16a8afd8467344fec81a54c84d
active boot switches: -d:release

### Description

`strutils.formatSize` returns wrong values from large values close to int64.high.
And it rounds an input value to the closest floating point value but I think it should round towards zero.
So `formatSize(1024 * 1024 * 2 - 1) == 1.999MiB`, not `2MiB`.

```nim
import std/[strutils, sugar]

dump formatSize(int64.high)
dump formatSize(int64.high div 4 + 1)
dump formatSize(int64.high div 4)
dump formatSize(int64.high div 8 + 1)
dump formatSize(int64.high div 8)
dump formatSize(1024 * 1024 * 2)
dump formatSize(1024 * 1024 * 2 - 1)
dump formatSize(1024 * 2)
dump formatSize(1024 * 2 - 1)
```

### Current Output

```text
formatSize(int64.high) = 140737488355328YiB
formatSize(int64.high div 4 + 1) = 35184372088832YiB
formatSize(int64.high div 4) = 35184372088832YiB
formatSize(int64.high div 8 + 1) = 17592186044416YiB
formatSize(int64.high div 8) = 1024PiB
formatSize(1024 * 1024 * 2) = 2MiB
formatSize(1024 * 1024 * 2 - 1) = 2MiB
formatSize(1024 * 2) = 2KiB
formatSize(1024 * 2 - 1) = 1.999KiB
```

### Expected Output

```text
formatSize(int64.high) = 7.999EiB
formatSize(int64.high div 4 + 1) = 2EiB
formatSize(int64.high div 4) = 1.999EiB
formatSize(int64.high div 8 + 1) = 1EiB
formatSize(int64.high div 8) = 1023PiB
formatSize(1024 * 1024 * 2) = 2MiB
formatSize(1024 * 1024 * 2 - 1) = 1.999MiB
formatSize(1024 * 2) = 2KiB
formatSize(1024 * 2 - 1) = 1.999KiB
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by demotomohiro**
`strutils.formatSize` returns correct strings from large values close to `int64.high`.
Round down `bytes` when it is converted to float.

### CODE REVIEW

**Comment by narimiran** [comment]
@Araq has merged this, but the CIs on our main branches are now red because `tests/stdlib/tstrutils.nim` is failing with `js` backend. @demotomohiro, can you take a look?

**Comment by demotomohiro** [comment]
@narimiran Sorry, I made a new PR to fix the errors: https://github.com/nim-lang/Nim/pull/25132

**Comment by ringabout** [comment]
It leaks?

https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/35110/logs/79
FAIL: [36mtests/destructor/tnewruntime_strutils.nim

File: lib/pure/strutils.nim [hunk 1]
```diff
@@ -2639,37 +2640,35 @@ func formatSize*(bytes: int64,
   ## * `strformat module<strformat.html>`_ for string interpolation and formatting
   runnableExamples:
     doAssert formatSize((1'i64 shl 31) + (300'i64 shl 20)) == "2.293GiB"
-    doAssert formatSize((2.234*1024*1024).int) == "2.234MiB"
+    doAssert formatSize((2.234*1024*1024).int) == "2.233MiB"
```
Comment (arnetheduck) [inline lib/pure/strutils.nim:2643]: sizes are more useful rounded up though.. :/

**Comment by demotomohiro** [comment]
@ringabout
Sorry, `tests/destructor/tnewruntime_strutils.nim` has tests calls `formatSize` and it raised AssertionDefect as this PR changed `formatSize` output.
I made https://github.com/nim-lang/Nim/pull/25142 to fixes the test.

@arnetheduck
I thought it should be rounded down because when people see "1MiB", I don't think most of people expect it can be smaller than 1024*1024 bytes.
Maybe add a parameter to specify whether `bytes` is round down or up?

**Comment by arnetheduck** [comment]
I guess the answer depends on whether you want to show the size of a file or the size of a disk - the former _certainly_ should be rounded up since you're showing "how much space do I need to store this file" and rounding down will underestimate the need - likewise for a transfer of bytes, ie "how many bytes left to download" makes more sense rounded up since otherwise, you'll be showing too low a number for most of the transfer - both of these common cases benefit from being rounded up rather than down - or at least the standard round-to-nearest which is probably what most people are used to.

If you're showing the size of a disk, _maybe_ it makes sense to round down since then the conservative choice is the opposite.

Which basically means that round-to-nearest wins as far as compromises go, and a flag would be needed beyond that.
