### PR TITLE
fix #22834

### LINKED ISSUE #22834: std/nativesockets getHostByAddr should support IPv6
### Summary

Currently, `getHostByAddr` hardcodes AF_INET. It would be nice to support IPv6 addresses.

### Description

Implementing support for IPv6 addresses would let Nim programs do reverse lookups of such IPs.

### Alternatives

_No response_

### Examples

Currently, attempting reverse lookups with eg https://github.com/pcarrier/bz/blob/main/src/shost.nim is broken.

Instead of (on latest MacOS):

```
> ./shost -r ident.me
broadcasthost
v4.ident.me
```

It should return:

```
> ./shost -r ident.me
v6.ident.me
v4.ident.me
```

### Backwards Compatibility

Should not be a problem, if it detects IPv6 addresses (eg presence of `:`), as AFAICT the current behaviour cannot be expected.

### Links

_No response_

### PR DESCRIPTION
**Pull request by rockcavera**
fix #22834

Edit: also fixes `result.addrList` when IPv6, which previously only performed a `result.addrList = cstringArrayToSeq(s.h_addr_list)` which does not provide the textual representation of an IPv6

### CODE REVIEW

File: lib/pure/nativesockets.nim [hunk 1]
```diff
@@ -387,21 +387,37 @@ when not useNimNetLite:
...
+      myAddr = addr cast[ptr Sockaddr_in](addrInfo.ai_addr).sin_addr
+      addrLen = 4
+    elif addrInfo.ai_addr.sa_family.cint == nativeAfInet6:
+      family = nativeAfInet6
+      myAddr = addr cast[ptr Sockaddr_in6](addrInfo.ai_addr).sin6_addr
+      addrLen = 16
+    else:
+      raise newException(IOError, "Unknown socket family in `getHostByAddr()`")
+
+    freeAddrInfo(addrInfo)
```
Comment (haoyu234) [inline lib/pure/nativesockets.nim:407]: Is it too early to call freeAddrInfo here? The myAddr variable is still in use.

Comment (rockcavera) [reply lib/pure/nativesockets.nim:407]: Good observation. The memory was definitely freed, but it was not cleaned.

Do you do PR to fix it?

Comment (haoyu234) [reply lib/pure/nativesockets.nim:407]: OK, I'll try it.
