### PR TITLE
[std/encodings] fix iconv headers on OpenBSD

### LINKED ISSUE #12: aporia
trying to get aporia up and running.  Its an issue specific to openbsd and iconv_open (openbsd uses libiconv_open, libconv*
aporia compiles, but when trying to open it I get cannot import iconv_open
I'm trying to work around it and found glib2.nim is where iconv dynlib resides, just not sure how to change it to get it work

### PR DESCRIPTION
**Pull request by ringabout**
see http://www.polarhome.com/service/man/?qf=iconv_open&tf=2&of=OpenBSD&sf=3

see CI failures: https://builds.sr.ht/~araq/job/496268
> could not import: iconv_open

fix https://github.com/nim-lang/gtk2/issues/12

### CODE REVIEW

File: lib/pure/encodings.nim [hunk 1]
```diff
@@ -282,7 +282,7 @@ else:
 
   var errno {.importc, header: "<errno.h>".}: cint
 
-  when defined(freebsd) or defined(netbsd):
+  when defined(freebsd) or defined(netbsd) or defined(openbsd):
```
Comment (timotheecour) [inline lib/pure/encodings.nim]:
```suggestion
  when defined(bsd):
```
would this work?

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
now this gives:
`ld: error: undefined symbol: libiconv_open`
instead of `could not import: iconv_open`

**Comment by ringabout** [comment]
well, I will look into it soon

File: lib/pure/encodings.nim [hunk 2]
```diff
@@ -282,7 +282,7 @@ else:
...
     {.pragma: importIconv, cdecl, header: "<iconv.h>".}
```
Comment (ringabout) [inline lib/pure/encodings.nim]:
```suggestion
  when defined(bsd):
    {.pragma: importIconv, cdecl, header: "<iconv.h>".}
    when defined(openbsd):
      {.passL: "-I/usr/local/include".}
```

File: lib/pure/encodings.nim [hunk 3]
```diff
@@ -282,8 +282,10 @@ else:
 
   var errno {.importc, header: "<errno.h>".}: cint
 
-  when defined(freebsd) or defined(netbsd):
+  when defined(bsd):
     {.pragma: importIconv, cdecl, header: "<iconv.h>".}
+    when defined(openbsd):
+      {.passL: "-I/usr/local/include".}
```
Comment (ringabout) [inline lib/pure/encodings.nim]: see whether it works, maybe OpenBSD should always link this path

Comment (timotheecour) [reply lib/pure/encodings.nim]: i dont' understand: passL is for linker, -I is for compilation phase

**Comment by timotheecour** [comment]
see https://hisham.hm/2016/02/24/first-time-playing-with-openbsd/

> * iconv is installed under /usr/local, and its library exports symbols with names such as libiconv_open instead of the usual iconv_open, which fools the typical AC_CHECK_LIB test in Autoconf. (In the source code, iconv_open works, so I guess iconv.h uses #define to translate the name. Added a hack to Dit to make it build cleanly out-of-the-box.

maybe the symbol name to dlopen is `libiconv_open` instead of iconv_open on openbsd?

File: lib/pure/encodings.nim (hunk 3 above)
Comment (ringabout) [reply lib/pure/encodings.nim]: well, what do you think how I should do?
I want to link `/usr/local/include/libiconv.a`.

**Comment by ringabout** [comment]
yeah, it is a common problem for OpenBSD.

File: lib/pure/encodings.nim (hunk 3 above)
Comment (ringabout) [inline lib/pure/encodings.nim]:
```suggestion
      {.passL: "/usr/local/include/libiconv.a".}
```

File: lib/pure/encodings.nim [hunk 4]
```diff
@@ -285,7 +285,7 @@ else:
   when defined(bsd):
     {.pragma: importIconv, cdecl, header: "<iconv.h>".}
     when defined(openbsd):
-      {.passL: "-I/usr/local/include".}
+      {.passL: "/usr/local/include/libiconv.a".}
```
Comment (timotheecour) [inline lib/pure/encodings.nim]: is this path correct? why wouldn't it be "/usr/local/lib/libiconv.a ? and should that instead be `passl:-liconv` ?

**Comment by timotheecour** [comment]
i think the issue is (i'm guessing):
the symbol name is something (maybe libiconv_open); a macro in iconv.h defines iconv_open based on it, so in the end you need both the header and a `passl:-liconv` flag or similar

File: lib/pure/encodings.nim (hunk 4 above)
Comment (ringabout) [reply lib/pure/encodings.nim]: sorry, my mistake

Comment (ringabout) [reply lib/pure/encodings.nim]: not sure whether `passl:-liconv` works, it is tricky

File: lib/pure/encodings.nim [hunk 5]
```diff
@@ -282,8 +282,10 @@ else:
 
   var errno {.importc, header: "<errno.h>".}: cint
 
-  when defined(freebsd) or defined(netbsd):
+  when defined(bsd):
     {.pragma: importIconv, cdecl, header: "<iconv.h>".}
+    when defined(openbsd):
+      {.passL: "/usr/local/include/libiconv.a".}
```
Comment (ringabout) [inline lib/pure/encodings.nim]:
```suggestion
      {.passL: "/usr/local/lib/libiconv.a".}
```

**Comment by ringabout** [comment]
Well passing "/usr/local/lib/libiconv.a" works

File: lib/pure/encodings.nim [hunk 6]
```diff
@@ -282,8 +282,10 @@ else:
 
   var errno {.importc, header: "<errno.h>".}: cint
 
-  when defined(freebsd) or defined(netbsd):
+  when defined(bsd):
     {.pragma: importIconv, cdecl, header: "<iconv.h>".}
+    when defined(openbsd):
+      {.passL: "/usr/local/lib/libiconv.a".}
```
Comment (ringabout) [inline lib/pure/encodings.nim]:
```suggestion
      {.passL: "-liconv".}
```

**Comment by ringabout** [comment]
> so in the end you need both the header and a passl:-liconv flag or similar

Yes, now OpenBSD pass CI too.

**Review by timotheecour — APPROVED** [review]
great!
