### PR TITLE
fixes #24033; Yielding from var fails with pairs and destructuring

### LINKED ISSUE #24033: Yielding from var fails with pairs and destructuring
### Description

I expect the following code to compile:

```nim
type Query = ref object

iterator pairs(query: Query): (int, (string, float32)) =
    var output: (int, (string, float32)) = (0, ("foo", 3.14))
    for id in @[ 0, 1, 2 ]:
        output[0] = id
        yield output

for id, (str, num) in Query():
    discard
```

### Nim Version

```
> nim -v
Nim Compiler Version 2.0.8 [Linux: amd64]
Compiled at 2024-07-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release
```

### Current Output

```text
Error: internal error: /home/nycto/Code/Nim/compiler/transf.nim(383, 7)
Traceback (most recent call last)
/home/nycto/Code/Nim/compiler/nim.nim(169) nim
/home/nycto/Code/Nim/compiler/nim.nim(124) handleCmdLine
/home/nycto/Code/Nim/compiler/main.nim(307) mainCommand
/home/nycto/Code/Nim/compiler/main.nim(274) compileToBackend
/home/nycto/Code/Nim/compiler/main.nim(137) commandCompileToC
/home/nycto/Code/Nim/compiler/pipelines.nim(312) compilePipelineProject
/home/nycto/Code/Nim/compiler/pipelines.nim(232) compilePipelineModule
/home/nycto/Code/Nim/compiler/pipelines.nim(179) processPipelineModule
/home/nycto/Code/Nim/compiler/pipelines.nim(25) processPipeline
/home/nycto/Code/Nim/compiler/cgen.nim(2186) genTopLevelStmt
/home/nycto/Code/Nim/compiler/transf.nim(1244) transformStmt
/home/nycto/Code/Nim/compiler/transf.nim(1160) processTransf
/home/nycto/Code/Nim/compiler/transf.nim(1139) transform
/home/nycto/Code/Nim/compiler/transf.nim(108) transformSons
/home/nycto/Code/Nim/compiler/transf.nim(1028) transform
/home/nycto/Code/Nim/compiler/transf.nim(805) transformFor
/home/nycto/Code/Nim/compiler/transf.nim(1139) transform
/home/nycto/Code/Nim/compiler/transf.nim(108) transformSons
/home/nycto/Code/Nim/compiler/transf.nim(1035) transform
/home/nycto/Code/Nim/compiler/transf.nim(264) transformBlock
/home/nycto/Code/Nim/compiler/transf.nim(108) transformSons
/home/nycto/Code/Nim/compiler/transf.nim(1139) transform
/home/nycto/Code/Nim/compiler/transf.nim(108) transformSons
/home/nycto/Code/Nim/compiler/transf.nim(1139) transform
/home/nycto/Code/Nim/compiler/transf.nim(108) transformSons
/home/nycto/Code/Nim/compiler/transf.nim(1035) transform
/home/nycto/Code/Nim/compiler/transf.nim(264) transformBlock
/home/nycto/Code/Nim/compiler/transf.nim(108) transformSons
/home/nycto/Code/Nim/compiler/transf.nim(1033) transform
/home/nycto/Code/Nim/compiler/transf.nim(288) transformWhile
/home/nycto/Code/Nim/compiler/transf.nim(108) transformSons
/home/nycto/Code/Nim/compiler/transf.nim(1139) transform
/home/nycto/Code/Nim/compiler/transf.nim(108) transformSons
/home/nycto/Code/Nim/compiler/transf.nim(1139) transform
/home/nycto/Code/Nim/compiler/transf.nim(108) transformSons
/home/nycto/Code/Nim/compiler/transf.nim(1139) transform
/home/nycto/Code/Nim/compiler/transf.nim(108) transformSons
/home/nycto/Code/Nim/compiler/transf.nim(1105) transform
/home/nycto/Code/Nim/compiler/transf.nim(415) transformYield
/home/nycto/Code/Nim/compiler/msgs.nim(647) asgnTo
/home/nycto/Code/Nim/compiler/msgs.nim(634) internalErrorImpl
/home/nycto/Code/Nim/compiler/msgs.nim(589) liMessage
/home/nycto/Code/Nim/compiler/msgs.nim(433) handleError
/home/nycto/Code/Nim/compiler/msgs.nim(421) quit
FAILURE
```
```


### Expected Output

```text
I expect that code to compile
```

### Known Workarounds

This works:

```
for id, comps in Query():
    discard
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #24033

### CODE REVIEW

File: tests/iter/titer_issues.nim [hunk 1]
```diff
@@ -392,3 +392,20 @@ iterator tryFinally() {.closure.} =
...
+    for id in @[0, 1, 2]:
+      output[0] = id
+      yield output
+
+  var collections: seq[(int, string, string)]
+
+  for id, (str, num) in Query():
+    collections.add (id, str, $num)
+
+  echo collections[1]
```
Comment (ringabout) [inline tests/iter/titer_issues.nim]:
```suggestion
```
