### PR TITLE
fix varargs forwarding for templates; fixes #5455

### LINKED ISSUE #5455: compiler crash in forwarding template
No matter if this is the right way of doing forwarding or not, it should not crash the compiler.
```nim
proc foo*(message: varargs[string, `$`]): void =
  discard

template fooIf*(cond: bool; message: varargs[untyped]): untyped =
  if cond:
    foo(message)

fooIf 17 + 4 < 21, "foobar"
```

```nim
scratch.nim(9, 20) Error: internal error: genLiteral: ty is nil
Traceback (most recent call last)
nim.nim(121)             nim
nim.nim(77)              handleCmdLine
main.nim(163)            mainCommand
main.nim(74)             commandCompileToC
modules.nim(240)         compileProject
modules.nim(180)         compileModule
passes.nim(215)          processModule
passes.nim(135)          processTopLevelStmt
cgen.nim(1280)           myProcess
ccgstmts.nim(1126)       genStmts
ccgexprs.nim(2080)       expr
ccgstmts.nim(313)        genIf
ccgexprs.nim(2044)       expr
ccgcalls.nim(537)        genCall
ccgcalls.nim(176)        genPrefixCall
ccgcalls.nim(142)        genArg
ccgcalls.nim(109)        openArrayLoc
cgen.nim(465)            initLocExpr
ccgexprs.nim(2058)       expr
ccgexprs.nim(1955)       exprComplexConst
ccgexprs.nim(2267)       genConstExpr
ccgexprs.nim(2228)       genConstSimpleList
ccgexprs.nim(2160)       genNamedConstExpr
ccgexprs.nim(2272)       genConstExpr
cgen.nim(465)            initLocExpr
ccgexprs.nim(2030)       expr
ccgexprs.nim(88)         genLiteral
ccgexprs.nim(40)         genLiteral
msgs.nim(997)            internalError
msgs.nim(971)            liMessage
msgs.nim(843)            handleError
msgs.nim(827)            quit
FAILURE
```

EDIT:

I made another example with the same error, this one shows, that the ast I am generating actually should work, because when I generate the exact same AST from manually writing code, it does work.

```nim
import macros

proc foo*(message: varargs[string, `$`]): void =
  discard

# this works
foo(["hello"])

dumpTree:
  foo(["hello"])

macro fooForwarded*(message: varargs[untyped]): untyped =
  result = quote do:
    foo(`message`)

  echo result.treeRepr

fooForwarded("world")
fooForwarded(14)
fooForwarded("world", 21)
```

### PR DESCRIPTION
**Pull request by zah**

### CODE REVIEW

File: compiler/sigmatch.nim [hunk 1]
```diff
@@ -1650,7 +1650,7 @@ proc matchesAux(c: PContext, n, nOrig: PNode,
     if a >= formalLen-1 and formal != nil and formal.typ.isVarargsUntyped:
       incl(marker, formal.position)
       if container.isNil:
-        container = newNodeIT(nkBracket, n.sons[a].info, arrayConstr(c, n.info))
+        container = newNodeIT(nkArgList, n.sons[a].info, arrayConstr(c, n.info))
```
Comment (Araq) [inline compiler/sigmatch.nim]: This is a breaking change. Macros expect an nkBracket, not an nkArgList.

Comment (zah) [inline compiler/sigmatch.nim]: I decided to switch this to `nkArgList`, because I found some code handling it, which was already doing the right thing (obviously left from the past).

I don't think this change is particularly risky for backwards compatibility, because it affects only macros having `varargs[untyped]` arguments. Since these will always be mapped to `nkArgList` (or `nkBracket` in the past), it's unlikely that there will be code, which checks the node kind of the macro param - most of the code probably just takes the `len` and iterates over the node's children. 

I didn't want to keep the `nkBracket`, because I found that it's indistinguishable from a passed-in array. A solution keeping it would have required defining yet another node flag.

Comment (Araq) [inline compiler/sigmatch.nim]: I think the nkArgList solution is quite nice, but it needs to be documented as a breaking change in the news for 0.17.0. Also nkArgList is not handled in the codegens etc, they only know about nkBracket. I'm confused why this doesn't cause more code changes and breaking tests...

> it's unlikely that there will be code, which checks the node kind of the macro param - most of the code probably just takes the len and iterates over the node's children.

That's just good defensive macro programming though. This change needs to be documented.

Comment (zah) [inline compiler/sigmatch.nim]: Pushed a news updated for 0.16.2

Comment (Araq) [inline compiler/sigmatch.nim]: >  I'm confused why this doesn't cause more code changes and breaking tests...

Do you know why?

Comment (zah) [inline compiler/sigmatch.nim]: Well, these nodes never reach the backend. They are created only to be passed in the macro call, which will be replaced a bit later by its AST result. One can imagine a silly macro that just returns the input AST, but my money would be that this would trigger malformed AST error in sem.
