### PR TITLE
js generates spurious >>> on shr

### LINKED ISSUE #17603: js generates spurious `>>>` on `shr`
originally reported in https://forum.nim-lang.org/t/7714#48956
> although it then does it twice

### Example
```nim
when true:
  import std/jsconsole
  let a = 2147483648'u
  console.log(a)
  console.log(a shr 0)
  console.log(a shr 1)
  console.log((a shr 2) shr 3)
```

### Current Output
nim r -b:js -d:danger main.nim
generated js:
```
var a_738197505 = 2147483648;
console.log(a_738197505);
console.log(((a_738197505 >>> 0) >>> 0));
console.log(((a_738197505 >>> 0) >>> 1));
console.log(((((a_738197505 >>> 0) >>> 2) >>> 0) >>> 3));
```
### Expected Output
```
var a_738197505 = 2147483648;
console.log(a_738197505);
console.log((a_738197505 >>> 0));
console.log((a_738197505 >>> 1));
console.log(((a_738197505 >>> 2) >>> 3));
```

### Possible Solution
don't call `unsignedTrimmer` for `shr` (that's probably the only exception; shl isn't affected by this doubling bug for example)

### Additional Information
1.5.1 fe9a37f2a57d0e76984b25c3dfe0fbdc94a30d9e

### PR DESCRIPTION
**Pull request by sivchari**
This PR fixes #17603

This is my first PR on Nim, so I apologize if there are any mistakes.
I fix don't call  unsignedTrimmer for shr.

### CODE REVIEW

**Comment by timotheecour** [comment]
@sivchari thanks for your first PR!

code looks good but please add a test by creating `tests/stdlib/tarithmetics.nim`:
(could be as small as i showed below for now, and grow in future work with more tests)
```nim
discard """
  targets: "c cpp js"
"""

# TODO: in future work move existing arithmetic tests here, where they belong

template main =
  # put all tests here
  block:
    let a = 3 shr 2
    doAssert a == ...
    # etc.
static: main()
main()
```

(`ccodeCheck` can be used for similar things but i don't like it much, and it's c backend only for now; it can be replaced with explict logic in tests which compiles the code and checks generated code explicitly; but for this PR it's not needed anyway IMO)

**Comment by sivchari** [comment]
@timotheecour Thanks for comment on my PR !
I added shr arithmetic test. Please review when you have time !

File: tests/stdlib/tarithmetics.nim [hunk 1]
```diff
@@ -0,0 +1,44 @@
+discard """
+  targets: "c cpp js"
+"""
+
+# TODO: in future work move existing arithmetic tests here, where they belong: Nim/tests/arithm
```
Comment (timotheecour) [inline tests/stdlib/tarithmetics.nim]:
```suggestion
# TODO: in future work move existing arithmetic tests (tests/arithm/*) into this file
```

File: tests/stdlib/tarithmetics.nim [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+template main =
+  # put all arithmetic tests
+
+  block tshr:
+
+    # Signed types
+    block:
+      let
+        t0: int = -3 shr 2
```
Comment (timotheecour) [inline tests/stdlib/tarithmetics.nim]: https://github.com/timotheecour/Nim/issues/534#issuecomment-780791150

File: tests/stdlib/tarithmetics.nim [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+        t1: int8 = -4'i8 shr 1'i8
+        t2: int16 = -5'i16 shr 1'i16
+        t3: int32 = -7'i32 shr 1'i32
```
Comment (timotheecour) [inline tests/stdlib/tarithmetics.nim]: the compiler does const folding for `-7'i32 shr 1'i32`, so that code isn't being run at RT.
so maybe something like:
```nim
let a1 = -4'i8
let a2 = 1'i8
doAssert a1 shr a2 == -2'i8
```
etc

(EDIT: i had mistyped -d'i8, corrected it to -2'i8)

File: tests/stdlib/tarithmetics.nim (hunk 2 above)
Comment (sivchari) [reply tests/stdlib/tarithmetics.nim]: this advise is maybe following ?

brefore
``` nim
let t0: int = -3 shr 2
doAssert t0 == -1
```

after
``` nim
doAssert -3 shr 2 == -1
```

File: tests/stdlib/tarithmetics.nim (hunk 3 above)
Comment (sivchari) [reply tests/stdlib/tarithmetics.nim]: sorry, I have not comprehended the conversation just yet. 
where is the specification you advised below ?

And I can't figure out that the sample code you pointed out for int32 is int8. Also, is the d in the code correct for a hexadecimal d?

```nim
let a1 = -4'i8
let a2 = 1'i8
doAssert a1 shr a2 == -d'i8 # doAssert -2 == -100 ?
```

Comment (ringabout) [reply tests/stdlib/tarithmetics.nim]: use `a1 shr a2 == -2'i8` I think

Comment (timotheecour) [reply tests/stdlib/tarithmetics.nim]: yes, sorry for the typo, i corrected it above. 

for more details, see `ctfeWhitelist` in compiler/ast.nim: it includes `mShrI, mShlI` etc, which means compiler will evaluate `a shl b` at CT if a, b are known at CT, which means it won't test RT code (eg the one generated by jsgen), hence my suggestion to force the RT evaluation by making the arguments `let`, not `const`.

Comment (sivchari) [reply tests/stdlib/tarithmetics.nim]: Thank you. I'll take your advice and fix it.

Comment (timotheecour) [reply tests/stdlib/tarithmetics.nim]: you can verify whether it worked by inspecting the generated js code and making sure it contains `>>>` for those statements; right now (as i predicted) it doesn't, due to const folding

Comment (sivchari) [reply tests/stdlib/tarithmetics.nim]:
```nim
  when true:
    import std/jsconsole
    let
      a = -3
      b = -2
      t0: int = a shr b
    console.log(t0)
```

above code generated following code.

```js
/* Generated by the Nim Compiler v1.5.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var a_369098753 = -3;
var b_369098754 = -2;
var t0_369098759 = (a_369098753 >> b_369098754);
console.log(t0_369098759);
```

but const declation generate following code
```nim
  when true:
    import std/jsconsole
    let
      t0: int = -3 shr -2
    console.log(t0
```

```js
/* Generated by the Nim Compiler v1.5.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var t0_369098757 = -1;
console.log(t0_369098757);
```
I've comprehended the system. Thank you so much ！

**Comment by timotheecour** [comment]
CI failed because of flaky https://github.com/timotheecour/Nim/issues/695, i restarted just the failed job using approach described in contributing.html

**Comment by sivchari** [comment]
> CI failed because of flaky [timotheecour#695](https://github.com/timotheecour/Nim/issues/695), i restarted just the failed job using approach described in contributing.html

thanks so much! I've confirmed it passes all CI checks

File: tests/stdlib/tarithmetics.nim (hunk 2 above)
Comment (timotheecour) [reply tests/stdlib/tarithmetics.nim]: that has been resolved
