### PR TITLE
delay resolved procvar check for proc params + acknowledge unresolved statics

### LINKED ISSUE #23186: Regression from 2.0 to `devel` with macros
### Description

```nim
import std/macros

type
  FieldDescription = object
    name: NimNode

func isTuple(t: NimNode): bool =
  t.kind == nnkBracketExpr and t[0].kind == nnkSym and eqIdent(t[0], "tuple")

proc collectFieldsFromRecList(result: var seq[FieldDescription],
                              n: NimNode,
                              parentCaseField: NimNode = nil,
                              parentCaseBranch: NimNode = nil,
                              isDiscriminator = false) =
  case n.kind
  of nnkRecList:
    for entry in n:
      collectFieldsFromRecList result, entry,
                               parentCaseField, parentCaseBranch
  of nnkIdentDefs:
    for i in 0 ..< n.len - 2:
      var field: FieldDescription
      field.name = n[i]

      if field.name.kind == nnkPragmaExpr:
        field.name = field.name[0]

      if field.name.kind == nnkPostfix:
        field.name = field.name[1]

      result.add field

  of nnkNilLit, nnkDiscardStmt, nnkCommentStmt, nnkEmpty:
    discard

  else:
    doAssert false, "Unexpected nodes in recordFields:\n" & n.treeRepr

proc collectFieldsInHierarchy(result: var seq[FieldDescription],
                              objectType: NimNode) =
  var objectType = objectType

  if objectType.kind == nnkRefTy:
    objectType = objectType[0]

  let recList = objectType[2]
  collectFieldsFromRecList result, recList

proc recordFields(typeImpl: NimNode): seq[FieldDescription] =
  let objectType = case typeImpl.kind
    of nnkObjectTy: typeImpl
    of nnkTypeDef: typeImpl[2]
    else:
      macros.error("object type expected", typeImpl)
      return

  collectFieldsInHierarchy(result, objectType)

proc skipPragma(n: NimNode): NimNode =
  if n.kind == nnkPragmaExpr: n[0]
  else: n

func declval(T: type): T {.compileTime.} =
  doAssert false,
    "declval should be used only in `typeof` expressions and concepts"
  default(ptr T)[]

when not compiles(len((1, 2))):
  import std/typetraits

  func len(x: tuple): int =
    arity(type(x))

macro enumAllSerializedFieldsImpl(T: type, body: untyped): untyped =
  var typeAst = getType(T)[1]
  var typeImpl: NimNode
  let isSymbol = not typeAst.isTuple

  if not isSymbol:
    typeImpl = typeAst
  else:
    typeImpl = getImpl(typeAst)
  result = newStmtList()

  var i = 0
  for field in recordFields(typeImpl):
    let
      fieldIdent = field.name
      realFieldName = newLit($fieldIdent.skipPragma)
      fieldName = realFieldName
      fieldIndex = newLit(i)

    let fieldNameDefs =
      if isSymbol:
        quote:
          const fieldName {.inject, used.} = `fieldName`
          const realFieldName {.inject, used.} = `realFieldName`
      else:
        quote:
          const fieldName {.inject, used.} = $`fieldIndex`
          const realFieldName {.inject, used.} = $`fieldIndex`
          # we can't access .Fieldn, so our helper knows
          # to parseInt this

    let field =
      if isSymbol:
        quote do: declval(`T`).`fieldIdent`
      else:
        quote do: declval(`T`)[`fieldIndex`]

    result.add quote do:
      block:
        `fieldNameDefs`

        type FieldType {.inject, used.} = type(`field`)

        `body`

    i += 1

template enumAllSerializedFields(T: type, body): untyped =
  when T is ref|ptr:
    type TT = type(default(T)[])
    enumAllSerializedFieldsImpl(TT, body)
  else:
    enumAllSerializedFieldsImpl(T, body)

type
  MemRange = object
    startAddr: ptr byte
    length: int

  SszNavigator[T] = object
    m: MemRange

func sszMount(data: openArray[byte], T: type): SszNavigator[T] =
  let startAddr = unsafeAddr data[0]
  SszNavigator[T](m: MemRange(startAddr: startAddr, length: data.len))

func sszMount(data: openArray[char], T: type): SszNavigator[T] =
  let startAddr = cast[ptr byte](unsafeAddr data[0])
  SszNavigator[T](m: MemRange(startAddr: startAddr, length: data.len))

template sszMount(data: MemRange, T: type): SszNavigator[T] =
  SszNavigator[T](m: data)

func navigateToField[T](
    n: SszNavigator[T],
    FieldType: type): SszNavigator[FieldType] =
  default(SszNavigator[FieldType])

type
  FieldInfo = ref object
    navigator: proc (m: MemRange): MemRange {.
      gcsafe, noSideEffect, raises: [IOError] .}

func fieldNavigatorImpl[RecordType; FieldType; fieldName: static string](
    m: MemRange): MemRange =
  var typedNavigator = sszMount(m, RecordType)
  discard navigateToField(typedNavigator, FieldType)
  default(MemRange)

func genTypeInfo(T: type) =
  when T is object:
    enumAllSerializedFields(T):
      discard FieldInfo(navigator: fieldNavigatorImpl[T, FieldType, fieldName])

type
  Foo = object
    bar: Bar

  BarList = seq[uint64]

  Bar = object
    b: BarList
    baz: Baz

  Baz = object
    i: uint64

genTypeInfo(Foo)
```

### Nim Version

Compiles and runs with:
```
Nim Compiler Version 2.0.3 [Linux: amd64]
Compiled at 2024-01-08
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 02497c9533603d8c0cd031b2a91e03d63ee8a35b
active boot switches: -d:release
```

Does not compile with:
```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-01-08
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 8d1c722d2d380ac998495ea508527f9f1c998233
active boot switches: -d:release
```

### Current Output

```text
Error: 'fieldNavigatorImpl' doesn't have a concrete type, due to unspecified generic parameters.
```

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
fixes #23186

As explained in #23186, generics can transform `genericProc[int]` into a call `` `[]`(genericProc, int) `` which causes a problem when `genericProc` is resemmed, since it is not a resolved generic proc. `[]` needs unresolved generic procs since `mArrGet` also handles explicit generic instantiations, so delay the resolved generic proc check to `semFinishOperands` which is intentionally not called for `mArrGet`.

The root issue for [t6137](https://github.com/nim-lang/Nim/blob/devel/tests/generics/t6137.nim) is also fixed (because this change breaks it otherwise), the compiler doesn't consider the possibility that an assigned generic param can be an unresolved static value (note the line `if t.kind == tyStatic: s.ast = t.n` below the change in sigmatch), now it properly errors that it couldn't instantiate it as it would for a type param. ~~The change in semtypinst is just for symmetry with the code above it which also gives a `cannot instantiate` error, it may or may not be necessary/correct.~~ Now removed, I don't think it was correct.

Still possible that this has unintended consequences.

### CODE REVIEW

File: tests/misc/t8545.nim [hunk 1]
```diff
@@ -1,5 +1,6 @@
 discard """
-  targets: "c cpp js"
+  # just tests that this doesn't crash the compiler
+  errormsg: "cannot instantiate: 'a:type'"
```
Comment (metagn) [inline tests/misc/t8545.nim:3]: This test only compiled before because `a` was never used, if you tried to use it you would get this same error. I have a stashed diff that gets this test working and lets you actually use `a` (except `cast[static[bool]](a)` which makes no sense) but this PR is already crowded. (edit: #23194)

File: tests/generics/timplicit_and_explicit.nim [hunk 2]
```diff
@@ -34,7 +34,8 @@ block: #15622
   proc test1[T](a: T, b: static[string] = "") = discard
   test1[int64](123)
   proc test2[T](a: T, b: static[string] = "") = discard
-  test2[int64, static[string]](123)
+  doAssert not (compiles do:
+    test2[int64, static[string]](123))
```
Comment (Araq) [inline tests/generics/timplicit_and_explicit.nim:38]: Huh? Previously this worked and now it doesn't? But it should work as you can pass `123` to `T = int64`. What am I missing?

Comment (metagn) [reply tests/generics/timplicit_and_explicit.nim:38]: The problem is the extra generic parameter `static[string]`, test2 only accepts one generic parameter, and even the implicit generic param which would be the value of `b` doesn't make sense to be set to literally the type `static[string]` (which is why this errors now).
