### PR TITLE
fixes inefficient codegen for field return

### LINKED ISSUE #23395: Inefficient codegen when extracting field from temporary object
### Description

The following snippet, of critical performance importance when working with [sum types](https://github.com/nim-lang/RFCs/issues/548), generates an inefficient copy, even though it can be seen that lifetimes are bounded in such a way that the copy can become a move:

```nim
type X = object
  s*: seq[byte]
proc f(): X = X(s: newSeq[byte](1024*1024*1024))
let v = f().s
```

```c
	nimZeroMem((void*)(&T1_), sizeof(tyObject_X__4CKW0EgTl4SNofakrtBaFw));	_ZN6testit1fE((&T1_));
	genericSeqAssign((&v__testit_u35), T1_.s, (&NTIseqLbyteT__6H5Oh5UUvVCLiakt9aTwtUQ_));}
```

Notably, the same applies to any "last use" of a variable:
```
let 
  fv = f()
  v = fv.s # no need to copy if this is the last use of fv
```

Of course, in the real world, this applies most significantly to `Option` and its ilk:
```nim
proc f(): Option[seq[byte]] = ...
let
  x = f()
if x.isNone():
  return
let y = x.get() # last use of x - we can move value out of x
...
```

### Nim Version

1.6, 2.0, devel....

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### LINKED ISSUE #23741: Inefficient codegen for field return
### Description

```nim
type X = object
  v: string

proc fff(input: string): X =
  X(v: input)

proc ggg(input: string): X =
  fff(input)

proc hhh(input: string): string =
  ggg(input).v # inefficient copy

proc hhh2(input: string): string =
  let v = ggg(input)
  v.v
```

`hhh` and `hhh2` are semantically equivalent and yet in `hhh` the string is copied - this introduces significant inefficiency for sum type-like constructs.

```c
N_LIB_PRIVATE N_NIMCALL(NimStringV2, _ZN6testit3hhhE6string)(NimStringV2 input_p0) {
	NimStringV2 result;
	tyObject_X__DSqG4yj45rrZSFUFxlmNRw colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_X__DSqG4yj45rrZSFUFxlmNRw));
	colontmpD_ = _ZN6testit3gggE6string(input_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_ZN6system7eqcopy_E3varI6stringE6string((&result), colontmpD_.v);
	_ZN6testit10eqdestroy_E3varIN6testit1XEE((&colontmpD_));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, _ZN6testit4hhh2E6string)(NimStringV2 input_p0) {
	NimStringV2 result;
	tyObject_X__DSqG4yj45rrZSFUFxlmNRw v;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&v), sizeof(tyObject_X__DSqG4yj45rrZSFUFxlmNRw));
	v = _ZN6testit3gggE6string(input_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = v.v;
	_ZN6system11eqwasMoved_E3varI6stringE((&v.v));
	_ZN6testit10eqdestroy_E3varIN6testit1XEE((&v));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, _ZN6testit4hhh3E6string)(NimStringV2 input_p0) {
	NimStringV2 result;
	tyObject_X__DSqG4yj45rrZSFUFxlmNRw v;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&v), sizeof(tyObject_X__DSqG4yj45rrZSFUFxlmNRw));
	v = _ZN6testit3gggE6string(input_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = v.v;
	_ZN6system11eqwasMoved_E3varI6stringE((&v.v));
	_ZN6testit10eqdestroy_E3varIN6testit1XEE((&v));
	}BeforeRet_: ;
	return result;
```

### Nim Version

2.0, devel

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes https://github.com/nim-lang/Nim/issues/23395
fixes https://github.com/nim-lang/Nim/issues/23741

### CODE REVIEW

File: compiler/injectdestructors.nim [hunk 1]
```diff
@@ -1205,7 +1224,11 @@ proc moveOrCopy(dest, ri: PNode; c: var Con; s: var Scope, flags: set[MoveOrCopy
     of nkRaiseStmt:
       result = pRaiseStmt(ri, c, s)
     else:
-      if isAnalysableFieldAccess(ri, c.owner) and isLastRead(ri, c, s) and
+      let isOwnsData = ownsData(c, s, ri2, flags)
```
Comment (Araq) [inline compiler/injectdestructors.nim:1227]: Arbitrary logic. Shouldn't `isAnalysableFieldAccess` etc be able to handle this? I think there is a real bug to be fixed here somewhere, not more custom logic to be added.

Comment (ringabout) [reply compiler/injectdestructors.nim:1227]: Isn't `isAnalysableFieldAccess`, `isLastRead` etc. analysis based on nkSym? What's the rule that it should handle callkinds in `f().s`? Should I treat the callkinds as the last read?

On the other hand, the `# Rule 3: =sink(x, z); wasMoved(z)` branch is not correct for `f().s`, because `f()` may have side effects. We need to create a temp for `f()` and clean up the potential memory of `f()`

**Comment by arnetheduck** [comment]
this remains highly interesting to merge

**Comment by Araq** [comment]
I know but I want to solve it differently.

**Comment by Araq** [comment]
Oh whatever, I will likely end up with the same logic.
