### PR TITLE
fixes #22669 constructor pragma doesnt init Nim default fields

### LINKED ISSUE #22669: constructor pragma doesnt init Nim default fields
But default values for object fields doesn't work.
https://nim-lang.github.io/Nim/manual.html#types-default-values-for-object-fields

For example:
```nim
type
  NimClass* = object
    x: int
    y = 777

proc makeNimClass(): NimClass {.constructor.} =
  discard

proc main =
  for i in 0 .. 1:
    var n = makeNimClass()
    echo n.x
    echo n.y
    n.x = 123
    echo n.x

main()
```

Current output:
```
0
0
123
0
0
123
```

Expected output:
```
0
777
123
0
777
123
```

In C++, non-static data members can have default value like Nim.
https://en.cppreference.com/w/cpp/language/data_members#Member_initialization
So when an object's field have non-zero default value, default member initializer can be used for it.

_Originally posted by @demotomohiro in https://github.com/nim-lang/Nim/issues/22665#issuecomment-1711024482_

### PR DESCRIPTION
**Pull request by jmgomez**
fixes #22669 constructor pragma doesnt init Nim default fields

### CODE REVIEW

File: compiler/cgen.nim [hunk 1]
```diff
@@ -1170,6 +1170,12 @@ proc genProcAux*(m: BModule, prc: PSym) =
       returnStmt = ropecg(p.module, "\treturn $1;$n", [rdLoc(res.loc)])
     elif sfConstructor in prc.flags:
       fillLoc(resNode.sym.loc, locParam, resNode, "this", OnHeap)
+      let ty = resNode.sym.typ[0]
+      for n in ty.n: #Inits default Nim fields
+        let val = n.sym.ast
```
Comment (ringabout) [inline compiler/cgen.nim]: I don't know about how the contructor works inernally. @jmgomez Would you mind giving me a cursory introduction?

This doesn't seem to be correct. You need to handle `nkRecList`, `nkRecCase`, `nkSym` separately.

Comment (jmgomez) [reply compiler/cgen.nim]: Ouch, you are right. But those should be handled with the function that I extracted, right? I mean, I would just need to extract the AST for each kind?

`constructor` besides changing the declaration (like `member` and `virtual` which doesnt affect this use case). What it does is to dont inject `result` but `this` in both Nim and C++.
Now I want to generate the inits like so:
`this->x = (NI) 10` (will change in the next push to `(*this).x = (NI)10`, but you get the idea)

Comment (jmgomez) [reply compiler/cgen.nim]: hmm at the point it reaches `genObjConstr` is already flatten like `(x:10..n:whatever)` Im just reusing `genObjConstr` and it assumes it will have that form already

File: compiler/semstmts.nim [hunk 2]
```diff
@@ -1711,6 +1711,8 @@ proc addThis(c: PContext, n: PNode, t: PType, owner: TSymKind) =
   c.p.resultSym = s
   n.add newSymNode(c.p.resultSym)
   addParamOrResult(c, c.p.resultSym, owner)
+  #resolves nim's obj ctor inside cpp ctors see #22669
+  s.ast = (c.semExpr(c, newTree(nkCall, t[0].sym.ast[0])))
```
Comment (Araq) [inline compiler/semstmts.nim]:
```suggestion
  s.ast = c.semExpr(c, newTree(nkCall, t[0].sym.ast[0]))
```
