### PR TITLE
fix #13515 [backport]

### LINKED ISSUE #13515: Calling nullary templates without () doesn't work inside calls inside other templates
### Example
```nim
template test: bool = true

# compiles:
if not test:
  echo "wtf"

# does not compile:
template x =
  if not test:
    echo "wtf"

x
```

### Current Output
```
got template(): bool, expected ...
```

### Expected Output
compiles

### Workaround

```nim
template test: bool = true

template x =
  if not test():
    echo "wtf"

x
```

### Additional Information

* `not` isn't specifically needed here, any call/operator errors. `if test:` compiles.
* First mentioned in https://forum.nim-lang.org/t/5992

```
$ nim -v
Nim Compiler Version 1.0.6
```

### PR DESCRIPTION
**Pull request by metagn**
fixes #13515

Really prepareOperand's behavior of [checking for nil node types](https://github.com/nim-lang/Nim/blob/f433d9cccf1a05da1a24e9fed9b914b7a2a35945/compiler/sigmatch.nim#L2288) is questionable, but I think this change is the most harmless for now, it's partially justified as templates resolving symbols early is unexpected.

Does not specifically need to be backported.

### CODE REVIEW

File: tests/template/t13515.nim [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+template test: bool = true
+
+# compiles:
+if not test:
+  echo "wtf"
+
+# does not compile:
+template x =
+  if not test:
```
Comment (Araq) [inline tests/template/t13515.nim:13]: Why does it matter that `test`'s typ field is set back to nil? It's set to `bool` and that's ok, no need to re-sem it.

Comment (metagn) [reply tests/template/t13515.nim:13]: It's not set to `bool`, it's set to `template(): bool`. `semSym` needs to be called on it to evaluate the template, which `prepareOperand` doesn't call unless the type of the expression is nil.
