### PR TITLE
Fix #14259 #15621

### LINKED ISSUE #14259: VC++ winnt.h fatal error "No Target Architecture" in stdlib_io.
Getting this error from Visual C++ but it works on Apr 15th compiler so its a very recent change.

```nim
# nim cpp --cc:vcc src\main.nim
import net
discard newSocket()
```

```
C:\Program Files (x86)\Windows Kits\8.1\include\\um\winnt.h(147): fatal error C1189: #error:  "No Target Architecture"
```

It looks like this error is related to WIN32_LEAN_AND_MEAN and the order in which one imports <windows.h>. Maybe some thing changed in stdlib_io?

```
Error: execution of an external compiler program 'vccexe.exe /c --platform:amd64  /nologo /EHsc -DWIN32_LEAN_AND_MEAN -D_GLFW_WIN32 /O2  /IC:\Users\me\.choosenim\toolchains\nim-#devel\lib /IC:\p\src /nologo /FoC:\Users\me\nimcache\main_d\stdlib_io.nim.cpp.obj C:\Users\me\nimcache\main_d\stdlib_io.nim.cpp' failed with exit code: 2
```

```
nim -v
Nim Compiler Version 1.3.1 [Windows: amd64]
Compiled at 2020-05-07
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

```
.\cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28612 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

### PR DESCRIPTION
**Pull request by rockcavera**
fixeds [#14259](https://github.com/nim-lang/Nim/issues/14259) [#15621](https://github.com/nim-lang/Nim/issues/15621)

The removal of the handleapi.h header was necessary for solution, invoking SetHandleInformation through kernel32.dll.

This bug happened in almost any package that used std.nativesockets compiling with tcc, vcc or clang

### CODE REVIEW

File: lib/system/io.nim [hunk 1]
```diff
@@ -278,16 +278,14 @@ elif defined(posix) and not defined(lwip) and not defined(nimscript):
   proc c_fcntl(fd: cint, cmd: cint): cint {.
     importc: "fcntl", header: "<fcntl.h>", varargs.}
 elif defined(windows):
-  const HANDLE_FLAG_INHERIT = culong 0x1
+  const HANDLE_FLAG_INHERIT = 0x00000001'i32
```
Comment (Araq) [inline lib/system/io.nim]:
```suggestion
  const HANDLE_FLAG_INHERIT = 1'i32
```

**Comment by rockcavera** [comment]
Maybe it is good to hear @alaviss, because he [implemented it](https://github.com/nim-lang/Nim/commit/1bdc30bdb13422bd5eff830327582a938e7b76ac)?

**Review by alaviss — APPROVED** [review]
LGTM, not sure if removing `IoHandle` type is a good idea though. I find some type safety to be useful, but maybe not here.

**Comment by timotheecour** [comment]
> LGTM, not sure if removing IoHandle type is a good idea though. I find some type safety to be useful, but maybe not here.

Please keep `IoHandle` as a distinct pointer. It makes it **harder to misuse** windows API's.

https://docs.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-sethandleinformation

```
BOOL SetHandleInformation(
  HANDLE hObject,
  DWORD  dwMask,
  DWORD  dwFlags
);

```
`HANDLE` is used fairly consistently in windows docs:

## reference 1:
https://en.wikibooks.org/wiki/Windows_Programming/Handles_and_Data_Types#:~:text=HANDLEs%20are%20defined%20as%20void,other%20words%20HANDLE%20%3D%20void*.


> HANDLE data types are some of the most important data objects in Win32 programming, and also some of the hardest for new programmers to understand. Inside the kernel, Windows maintains a table of all the different objects that the kernel is responsible for. Windows, buttons, icons, mouse pointers, menus, and so on, all get an entry in the table, and each entry is assigned a unique address known as a HANDLE. If you want to pick a particular entry out of that table, you need to give Windows the HANDLE value, and Windows will return the corresponding table entry.
> HANDLEs are defined as void pointers (void*). They are used as unique identifiers to each Windows object in our program such as a button, a window an icon, etc. Specifically their definition follows: typedef PVOID HANDLE; and typedef void *PVOID; In other words HANDLE = void*.


the definition before this PR seems to match windows docs for a `HANDLE` being a `void*`:
```nim
  type
    IoHandle = distinct pointer
```

## reference 2:
https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types
```
PVOID | A pointer to any type.This type is declared in WinNT.h as follows:typedef void *PVOID;
HANDLE | A handle to an object.This type is declared in WinNT.h as follows:typedef PVOID HANDLE;
```

File: lib/system/io.nim [hunk 2]
```diff
@@ -278,16 +278,14 @@ elif defined(posix) and not defined(lwip) and not defined(nimscript):
...
     importc: "fcntl", header: "<fcntl.h>", varargs.}
 elif defined(windows):
-  const HANDLE_FLAG_INHERIT = culong 0x1
+  const HANDLE_FLAG_INHERIT = 1'i32
+  
   proc getOsfhandle(fd: cint): int {.
     importc: "_get_osfhandle", header: "<io.h>".}
-
-  type
-    IoHandle = distinct pointer
```
Comment (timotheecour) [inline lib/system/io.nim:286]: see PR comment

**Review by timotheecour — CHANGES_REQUESTED** [review]
see PR comment

File: lib/system/io.nim [hunk 3]
```diff
@@ -278,16 +278,19 @@ elif defined(posix) and not defined(lwip) and not defined(nimscript):
...
     importc: "_get_osfhandle", header: "<io.h>".}
 
   type
     IoHandle = distinct pointer
       ## Windows' HANDLE type. Defined as an untyped pointer but is **not**
       ## one. Named like this to avoid collision with other `system` modules.
-  proc setHandleInformation(handle: IoHandle, mask, flags: culong): cint {.
-    importc: "SetHandleInformation", header: "<handleapi.h>".}
+
+  proc setHandleInformation(hObject: IoHandle, dwMask: int32, dwFlags: int32):
```
Comment (timotheecour) [inline lib/system/io.nim]: this should be:

```nim
type WinDWORD = culong
type WinBOOL = cint
proc setHandleInformation(hObject: IoHandle, dwMask, dwFlags: DWORD): WinBOOL {.
  stdcall, dynlib: "kernel32", importc: "SetHandleInformation".}
```

or at least:
```nim
proc setHandleInformation(hObject: IoHandle, dwMask, dwFlags: culong): cint {.
  stdcall, dynlib: "kernel32", importc: "SetHandleInformation".}
```

to match API in https://docs.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-sethandleinformation
and https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types

This should still fix the referenced issues since it was IIRC due to `header: "<handleapi.h>"`

## note
in future work, windows specific types need to be refactored/harmonized between winlean.nim and io.nim:
```
type
  Handle* = int # this might need be be revisited
  LONG* = int32
  ULONG* = int32
  PULONG* = ptr int
  WINBOOL* = int32
    ## `WINBOOL` uses opposite convention as posix, !=0 meaning success.
    # xxx this should be distinct int32, distinct would make code less error prone
  DWORD* = int32
  PDWORD* = ptr DWORD
  LPINT* = ptr int32
  ULONG_PTR* = uint
  PULONG_PTR* = ptr uint
  HDC* = Handle
  HGLRC* = Handle
```

File: lib/system/io.nim [hunk 4]
```diff
@@ -346,7 +349,7 @@ when defined(nimdoc) or (defined(posix) and not defined(nimscript)) or defined(w
       result = c_fcntl(f, F_SETFD, flags) != -1
     else:
       result = setHandleInformation(cast[IoHandle](f), HANDLE_FLAG_INHERIT,
-                                    culong inheritable) != 0
+                                    inheritable.int32) != 0
```
Comment (timotheecour) [inline lib/system/io.nim]: with my other comment, this change wouldn't be needed

File: lib/system/io.nim (hunk 3 above)
Comment (rockcavera) [reply lib/system/io.nim]: I had followed winlean, even though I had code using different types, because I also believe that the current winlean does not match the types of WinAPI. Thanks for the comments full of references.

**Review by timotheecour — APPROVED** [review]

**Comment by timotheecour** [comment]
LGTM; ya if you'd like to followup with a PR to harmonize / factorize types between winlean and io that'd be super appreciated! (refs https://github.com/nim-lang/Nim/pull/16322#discussion_r541467108)
