### PR TITLE
fixes #23755; array static inference during overload resolution

### LINKED ISSUE #23755: Regression: compiler crash on static inference
The following snippet works on Nim v2.0.6 but crashes on Nim-devel

```Nim
import std/bitops

# --------------------------------------------------------------

type SecretWord* = distinct uint64
const WordBitWidth* = sizeof(SecretWord) * 8

func wordsRequired*(bits: int): int {.inline.} =
  const divShiftor = fastLog2(WordBitWidth)
  result = (bits + WordBitWidth - 1) shr divShiftor

type
  BigInt*[bits: static int] = object
    limbs*: array[bits.wordsRequired, SecretWord]

type Limbs*[N: static int] = array[N, SecretWord]

# --------------------------------------------------------------

type
  LimbsView* = ptr UncheckedArray[SecretWord]
    ## Type-erased fixed-precision limbs
    ##
    ## This type mirrors the Limb type and is used
    ## for some low-level computation API
    ## This design
    ## - avoids code bloat due to generic monomorphization
    ##   otherwise limbs routines would have an instantiation for
    ##   each number of words.
    ##
    ## Accesses should be done via BigIntViewConst / BigIntViewConst
    ## to have the compiler check for mutability

  # "Indirection" to enforce pointer types deep immutability
  LimbsViewConst* = distinct LimbsView
    ## Immutable view into the limbs of a BigInt
  LimbsViewMut* = distinct LimbsView
    ## Mutable view into a BigInt
  LimbsViewAny* = LimbsViewConst or LimbsViewMut

# Deep Mutability safety
# ------------------------------------------------------------

template view*(a: Limbs): LimbsViewConst =
  ## Returns a borrowed type-erased immutable view to a bigint
  LimbsViewConst(cast[LimbsView](a.unsafeAddr))

template view*(a: var Limbs): LimbsViewMut =
  ## Returns a borrowed type-erased mutable view to a mutable bigint
  LimbsViewMut(cast[LimbsView](a.addr))

template view*(a: openArray[SecretWord]): LimbsViewConst =
  ## Returns a borrowed type-erased immutable view to a bigint
  LimbsViewConst(cast[LimbsView](a[0].unsafeAddr))

template view*(a: var openArray[SecretWord]): LimbsViewMut =
  ## Returns a borrowed type-erased mutable view to a mutable bigint
  LimbsViewMut(cast[LimbsView](a[0].addr))

# --------------------------------------------------------------

func reduce*(r: LimbsViewMut,
            a: LimbsViewAny, aBits: int,
            M: LimbsViewConst, mBits: int) =
  discard

func reduce*[aLen, mLen](r: var Limbs[mLen],
                         a: Limbs[aLen], aBits: static int,
                         M: Limbs[mLen], mBits: static int
                        ) {.inline.} =
  reduce(r.view(), a.view(), aBits, M.view(), mBits)

func reduce*[aBits, mBits](r: var BigInt[mBits], a: BigInt[aBits], M: BigInt[mBits]) =
  reduce(r.limbs, a.limbs, aBits, M.limbs, mBits)

var a, M, r: BigInt[64]
r.reduce(a, M)
```

It crashes in release mode at
```
assertions.nim(34)       raiseAssert
Error: unhandled exception: int128.nim(70, 11) `arg.sdata(3) == 0` out of range [AssertionDefect]
```
And in debug:

```
[...]/Nim/compiler/nim.nim(169) nim
[...]/Nim/compiler/nim.nim(124) handleCmdLine
[...]/Nim/compiler/main.nim(338) mainCommand
[...]/Nim/compiler/main.nim(304) compileToBackend
[...]/Nim/compiler/main.nim(142) commandCompileToC
[...]/Nim/compiler/pipelines.nim(325) compilePipelineProject
[...]/Nim/compiler/pipelines.nim(245) compilePipelineModule
[...]/Nim/compiler/pipelines.nim(187) processPipelineModule
[...]/Nim/compiler/sem.nim(822) semWithPContext
[...]/Nim/compiler/sem.nim(784) semStmtAndGenerateGenerics
[...]/Nim/compiler/semstmts.nim(2888) semStmt
[...]/Nim/compiler/semexprs.nim(1190) semExprNoType
[...]/Nim/compiler/semexprs.nim(3369) semExpr
[...]/Nim/lib/system.nim(918) semStmtList
[...]/Nim/compiler/semexprs.nim(3288) semExpr
[...]/Nim/compiler/semexprs.nim(1081) semIndirectOp
[...]/Nim/compiler/semexprs.nim(3268) semExpr
[...]/Nim/compiler/semexprs.nim(1171) semDirectOp
[...]/Nim/compiler/semexprs.nim(969) semOverloadedCallAnalyseEffects
[...]/Nim/compiler/semcall.nim(752) semOverloadedCall
[...]/Nim/compiler/semcall.nim(703) semResolvedCall
[...]/Nim/compiler/seminst.nim(422) generateInstance
[...]/Nim/compiler/seminst.nim(145) instantiateBody
[...]/Nim/compiler/semexprs.nim(2009) semProcBody
[...]/Nim/compiler/semexprs.nim(3369) semExpr
[...]/Nim/lib/system.nim(918) semStmtList
[...]/Nim/compiler/semexprs.nim(3286) semExpr
[...]/Nim/compiler/semexprs.nim(1171) semDirectOp
[...]/Nim/compiler/semexprs.nim(969) semOverloadedCallAnalyseEffects
[...]/Nim/compiler/semcall.nim(752) semOverloadedCall
[...]/Nim/compiler/semcall.nim(703) semResolvedCall
[...]/Nim/compiler/seminst.nim(422) generateInstance
[...]/Nim/compiler/seminst.nim(145) instantiateBody
[...]/Nim/compiler/semexprs.nim(2009) semProcBody
[...]/Nim/compiler/semexprs.nim(3369) semExpr
[...]/Nim/lib/system.nim(918) semStmtList
[...]/Nim/compiler/semexprs.nim(3286) semExpr
[...]/Nim/compiler/semexprs.nim(1171) semDirectOp
[...]/Nim/compiler/semexprs.nim(969) semOverloadedCallAnalyseEffects
[...]/Nim/compiler/semcall.nim(744) semOverloadedCall
[...]/Nim/compiler/semcall.nim(478) resolveOverloads
[...]/Nim/compiler/semcall.nim(107) pickBestCandidate
[...]/Nim/compiler/sigmatch.nim(2749) matches
[...]/Nim/compiler/sigmatch.nim(2680) matchesAux
[...]/Nim/compiler/sigmatch.nim(2471) prepareOperand
[...]/Nim/compiler/semexprs.nim(55) semOperand
[...]/Nim/compiler/semexprs.nim(3288) semExpr
[...]/Nim/compiler/semexprs.nim(1081) semIndirectOp
[...]/Nim/compiler/semexprs.nim(3286) semExpr
[...]/Nim/compiler/semexprs.nim(1171) semDirectOp
[...]/Nim/compiler/semexprs.nim(969) semOverloadedCallAnalyseEffects
[...]/Nim/compiler/semcall.nim(744) semOverloadedCall
[...]/Nim/compiler/semcall.nim(478) resolveOverloads
[...]/Nim/compiler/semcall.nim(119) pickBestCandidate
[...]/Nim/compiler/sigmatch.nim(306) cmpCandidates
[...]/Nim/compiler/sigmatch.nim(189) checkGeneric
[...]/Nim/compiler/sigmatch.nim(1253) typeRel
[...]/Nim/compiler/sigmatch.nim(1761) typeRel
[...]/Nim/compiler/sigmatch.nim(1293) typeRel
[...]/Nim/compiler/sigmatch.nim(976) inferStaticsInRange
[...]/Nim/compiler/int128.nim(70) toInt64
[...]/Nim/lib/std/assertions.nim(41) failedAssertImpl
[...]/Nim/lib/std/assertions.nim(34) raiseAssert
Error: unhandled exception: [...]/Nim/compiler/int128.nim(70, 11) `arg.sdata(3) == 0` out of range [AssertionDefect]
```

### PR DESCRIPTION
**Pull request by Graveflo**
#23755

### CODE REVIEW

**Comment by mratsim** [comment]
We should add both test cases you mentioned in https://github.com/nim-lang/Nim/issues/23755#issuecomment-2187859094. If it's intentional because you will address the first one later, carry on.

**Comment by Graveflo** [comment]
> We should add both test cases you mentioned in https://github.com/nim-lang/Nim/issues/23755#issuecomment-2187859094. If it's intentional because you will address the first one later, carry on.

Yea I don't have a lot of time to work on this. Im just just leaving it here drafted as  I make progress. Plus, the CI gets effed up every time I try to run it locally and my my repos so I use that here sometimes.

**Comment by Graveflo** [comment]
CI failing, but idk, it looks like http connection issues. This is where I'm at anyway:

Both of these "fixes" are dirty workarounds.  The code near `getOrdValue` might actually be a decent idea, but the code added in `inferStaticsInRange` is not. I still think this incompatibility needs to be flushed out earlier. It's far less then ideal to decide if input is valid by bouncing them off of those ord procs.

I can't help but feel like adding more asserts to specific procs would guard against them being abused and expose logic that is not quite right.

Also, the check for the longer standing bug is just a patch. It's probably fragile.

**Comment by Graveflo** [comment]
Although this is kinda obvious, I should mention what is happening:

In `typeRel`'s `tyArray` branch the range of the array is processed via `inferStaticsInRange`. In that proc, families of functions like `lengthOrd`, `lastOrd`, and eventually `getOrdValue` are called that work with `Int128` types. There was a comment in `getOrdValue` warning that the current error handling scheme (returning `high(Int128)`) was probably a bad idea due to overflow concerns. `inferStaticsInRange` takes the `Int128` and converts it with `toInt64`, which from an erroneous call to `getOrdValue` is not compatible, triggering the assertion error from the issue.

As I said before, I think there is something else wrong with this besides avoiding the overflow. Maybe the node structure is not what is expected.

File: compiler/types.nim [hunk 1]
```diff
@@ -115,7 +118,7 @@ proc isPureObject*(typ: PType): bool =
 proc isUnsigned*(t: PType): bool =
   t.skipTypes(abstractInst).kind in {tyChar, tyUInt..tyUInt64}
 
-proc getOrdValue*(n: PNode; onError = high(Int128)): Int128 =
+proc getOrdValueAux*(n: PNode): Int128Calc =
```
Comment (metagn) [inline compiler/types.nim]: I think the more common way to do this is to define this as `getOrdValue(n: PNode, error: var bool): Int128` where `error` is set to true if it errors, then define an overload that just sets `error` to a dummy variable.

It's weird to depend on this proc failing for logic though.

File: compiler/sigmatch.nim [hunk 2]
```diff
@@ -1279,7 +1282,10 @@ proc typeRel(c: var TCandidate, f, aOrig: PType,
         result = isGeneric
       else:
         result = typeRel(c, ff, aa, flags)
-
+      
+      if fRange.kind == tyArray and fRange.indexType.kind == tyGenericParam:
```
Comment (metagn) [inline compiler/sigmatch.nim]: `fRange.kind == tyArray` doesn't make sense, I think the lines above are wrong:

```nim
if prev == nil:
  put(c, fRange, a.indexType)
  fRange = a
```

`fRange = a` should be `fRange = a.indexType`, then we can just check if `fRange.kind == tyGenericParam`.

File: compiler/types.nim (hunk 1 above)
Comment (Graveflo) [reply compiler/types.nim]: agreed

File: compiler/sigmatch.nim (hunk 2 above)
Comment (Graveflo) [reply compiler/sigmatch.nim]: I'm of the opinion that the whole `tyArray` branch of typeRel needs to be revisited, not just this part. I didn't try to mess with what was already there. Sorry this PR is so patchy. It would take me a while to understand how the statics are packed into the node structure.

Comment (Graveflo) [reply compiler/sigmatch.nim]: And to be clear, I did look at that briefly and `fRange = a` makes zero sense to me at all, so if you have an idea about that you are further along then me.

Comment (Graveflo) [reply compiler/sigmatch.nim]: wait, something just clicked for me. `fRange` is being set to `a` because if it has no binding it's assumed that it can accept `a`, so that is the substitution. What if the generic parameter has constraints though? I think that might be another error. Just because the range is a generic type variable doesn't mean it accepts any type. That's an unconstrained generic type variable.

**Comment by Graveflo** [comment]
If this passes the CI, it seems like the workaround can be removed from `inferStaticsInRange` as well (at least for the givin test cases). I'll probably be asleep by the time it finishes though

File: compiler/sigmatch.nim [hunk 3]
```diff
@@ -985,6 +985,11 @@ proc inferStaticsInRange(c: var TCandidate,
         return isGeneric
       else:
         return isNone
+    if concrete.kind == tyRange:
+      var err = false
+      let lenOrd = getOrdValueAux(concrete.n[1], err)
+      if err:
+        return isNone
```
Comment (metagn) [inline compiler/sigmatch.nim]: I think an alternative to this would be to change the code below:

```nim
if fRange.rangeHasUnresolvedStatic:
  return inferStaticsInRange(c, fRange, a)
```

to:

```nim
if fRange.rangeHasUnresolvedStatic:
  if not aRange.rangeHasUnresolvedStatic:
    return inferStaticsInRange(c, fRange, a)
  else:
    return isNone
```

The issue with the ord value failing is that `f` and `a` both have unresolved statics (which is supposed to happen, `checkGeneric` in `cmpCandidates` compares generic overloads to each other), and the `inferStaticsInRange` tries to evaluate unresolved statics in `a` to assign to the unresolved statics in `f` and crashes because the unresolved statics don't have values. In this case calling `inferStaticsInRange` at all doesn't make sense, we can deal with it early on by checking if `a` has unresolved statics.

This change compiles the test but idk if it'll break anything in CI in general.

Comment (Graveflo) [reply compiler/sigmatch.nim]: As per my comment above the test cases that bring us to this point are avoided by the extra call to `typeRel` from the "try this" push. If that is a good sanity check then maybe it's worth trying it out anyway. Maybe run the CI with the 
```nim
proc view(a: Limbs) = discard
proc view(a: var Limbs) = discard
```
overload scenario on top of `devel` to see if it's worth merging before this PR?

File: compiler/sigmatch.nim [hunk 4]
```diff
@@ -1279,7 +1280,7 @@ proc typeRel(c: var TCandidate, f, aOrig: PType,
         result = isGeneric
       else:
         result = typeRel(c, ff, aa, flags)
-
+
```
Comment (Araq) [inline compiler/sigmatch.nim]:
```suggestion

```

**Comment by narimiran** [comment]
Even after the fixes from this PR, there is still an `Error: fatal error: invalid kind for lastOrd(tyGenericParam)` in an example that @tersec and I are trying to minimize and make self-contained.
I've bisected the problem, and the root cause seems to be the same: https://github.com/nim-lang/Nim/pull/23137

Don't know if this stops the merge of this PR, or if it will be fixed in some future PR.

**Comment by Araq** [comment]
I'm merging it already as the change is a definite improvement.

**Comment by narimiran** [comment]
Here is a self-contained example that worked before https://github.com/nim-lang/Nim/pull/23137 and it fails with `Error: fatal error: invalid kind for lastOrd(tyGenericParam)` after it (including this PR):

```nim
func `xor`[T: array](a, b: T): T =
  for i in 0..<result.len:
    result[i] = a[i] xor b[i]

template eachElement(x, y, res, op: untyped) =
  for i in 0..<res.len:
    res[i] = op(x[i], y[i])

func `xor`*[N: static int; T](x, y: array[N, T]): array[N, T] =
  eachElement(x, y, result, `xor`)

var a: array[5, int]
var b: array[5, int]

discard a xor b
```

**Comment by narimiran** [comment]
> Here is a self-contained example that worked before #23137 and it fails with `Error: fatal error: invalid kind for lastOrd(tyGenericParam)` after it (including this PR):
> 
> ```nim
> func `xor`[T: array](a, b: T): T =
>   for i in 0..<result.len:
>     result[i] = a[i] xor b[i]
> 
> template eachElement(x, y, res, op: untyped) =
>   for i in 0..<res.len:
>     res[i] = op(x[i], y[i])
> 
> func `xor`*[N: static int; T](x, y: array[N, T]): array[N, T] =
>   eachElement(x, y, result, `xor`)
> 
> var a: array[5, int]
> var b: array[5, int]
> 
> discard a xor b
> ```

Is anyone looking into fixing the error from the above example? Should I open a separate issue for it?

EDIT: Ok, I created a new issue for it: https://github.com/nim-lang/Nim/issues/23823
