### PR TITLE
fixes #19457 seqs are not properly updated in loop with ARC/ORC

### LINKED ISSUE #19457: `seq`s are not properly updated in loop with ARC/ORC
### Example
This is the standard euclidean algorithm for calculating the GCD, but stores the values in single-element `seq`s.
```nim
proc gcd(x, y: seq[int]): seq[int] =
    var
      a = x
      b = y
    while b[0] > 0:
      let c = @[a[0] mod b[0]]
      a = b
      b = c
    return a

echo gcd(@[1], @[2])
```

### Current Output
```
Error: unhandled exception: division by zero [DivByZeroDefect]
```

### Expected Output
```
1
```

### Additional Information
This only happens for `arc`/`orc`, it works fine with `refc`.

It also works if you
* `echo b` at the end of the loop (this leads me to the conclusion that `b` is somehow not properly updated)
* create the `seq`s inside the proc
* just use `int`s instead of `seq[int]`s

This is a reduced example of https://github.com/nim-lang/bigints/issues/88.

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-01-21
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 2bd1aa186e09565b2103394bd281478fa1b10ef1
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes https://github.com/nim-lang/Nim/issues/19457

### CODE REVIEW

File: tests/arc/t19457.nim [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+  matrix: "--gc:refc; --gc:arc"
+"""
+
+# bug #19457
+proc gcd(x, y: seq[int]): seq[int] =
+    var
+      a = x
+      b = y
+    while b[0] > 0:
+      let c = @[a[0] mod b[0]]
```
Comment (ringabout) [inline tests/arc/t19457.nim:11]: For a naive fix (not consider optimization), I think variables in the while condition (for this instance b) should have longer alive time than local variables in the while loop body (for this instance c) because b is probably accessed after c is destroyed.

File: compiler/varpartitions.nim [hunk 2]
```diff
@@ -852,6 +857,11 @@ proc computeLiveRanges(c: var Partitions; n: PNode) =
     inc c.inLoop
     for child in n: computeLiveRanges(c, child)
     inc c.inLoop
+
+    if n.kind == nkWhileStmt:
```
Comment (ringabout) [inline compiler/varpartitions.nim:861]: for loop doesn't seem to have the same problem as while loop.

File: tests/arc/t19457.nim (hunk 1 above)
Comment (Araq) [reply tests/arc/t19457.nim:11]: Correct, the cursorfication should be prevented here because `c`'s scope is not `b`'s.

**Comment by ringabout** [comment]
I was invertigating the CI failure of pixie. It seems that they has already fixed it :smile_cat:
