### PR TITLE
#18216 make moveDir work across partitions on windows

### LINKED ISSUE #18216: `moveDir()` not able to move files between partitions on Windows
The `moveDir()` command is not able to move folders between partitions on Windows.

### Example
- Use Windows 
- Create C:\\testdir\
- Create D:\\testdestdir\
```nim
import os

moveDir("C:\\testdir", "D:\\testdestdir")
```

### Current Output
```
D:\Projects\mc\pax\test.nim(3) test
C:\Users\Alexander\nim\nim-1.4.8\lib\pure\os.nim(2407) moveDir
C:\Users\Alexander\nim\nim-1.4.8\lib\pure\os.nim(1828) tryMoveFSObject
C:\Users\Alexander\nim\nim-1.4.8\lib\pure\includes\oserr.nim(94) raiseOSError
Error: unhandled exception: Zugriff verweigert
Additional info: "(\"C:\\\\testdir\", \"D:\\\\testdestdir\")" [OSError]
Error: execution of an external program failed: 'D:\Projects\mc\pax\test.exe '
```

### Additional Information
Bug present since at least V1.2.0.

### PR DESCRIPTION
**Pull request by maradotwebp**
Supersedes #18217.

Fixes `tryMoveFSObject` so when objects are moved across partitions, an error is thrown regardless of operating system.
Changes methods using `tryMoveFSObject` so that `copy`/`remove` methods are used when `tryMoveFSObject` returns false, regardless of operating system.
Fixes #18216.

### CODE REVIEW

**Comment by maradotwebp** [comment]
Ok, all checks are successful except Windows ones.
I'm not that familiar with the Windows API, is there a way to check if the error thrown in `moveFileExW` is the one thrown because moving directories across partitions isn't possible?

If that's not possible, I could also rewrite `moveDir` to use `tryMoveFSObject` on linux and `copyDir`/`removeDir` on Windows, to completely prevent all errors. I don't know if that would introduce any bugs or be a performance hit.

File: lib/pure/os.nim [hunk 1]
```diff
@@ -2015,21 +2015,27 @@ proc tryMoveFSObject(source, dest: string): bool {.noWeirdTarget.} =
   ## Returns false in case of `EXDEV` error.
   ## In case of other errors `OSError` is raised.
   ## Returns true in case of success.
+  var isErr: bool
```
Comment (timotheecour) [inline lib/pure/os.nim]: use `result` variable (with flipped semantics)

**Comment by maradotwebp** [comment]
Also on tests, should I create a new testament test in `tests/stdlib` for this? Or this there already an existing test file for `moveFile`?

File: lib/pure/os.nim [hunk 2]
```diff
@@ -2015,21 +2015,27 @@ proc tryMoveFSObject(source, dest: string): bool {.noWeirdTarget.} =
...
+    let err = osLastError()
+    if err == EXDEV.OSErrorCode:
+      return false
+    else:
+      when defined(windows):
+        raiseOSError(err, $(source, dest))
       else:
-        # see whether `strerror(errno)` is redundant with what raiseOSError already shows
-        raiseOSError(err, $(source, dest, strerror(errno)))
+        raiseOSError(err, $(source ,dest, strerror(errno)))
```
Comment (timotheecour) [inline lib/pure/os.nim]: isn't `strerror(errno))` redundant with what  raiseOSError already shows? please double check (EDIT: i double checked, it is indeed redundant)

this simplifies to:
`raiseOSError(err, $(source, dest))`

Comment (timotheecour) [reply lib/pure/os.nim]: @froehlichA please click "resolve conversation" once you've resolved a comment (unless it's a push bash)

**Comment by timotheecour** [comment]
> Also on tests, should I create a new testament test in tests/stdlib for this? Or this there already an existing test file for moveFile?

it's 1 test per module, not 1 test per API (in almost all cases), the test is `tos.nim`

right now we only have a test for:
```
    # Test moveFile
    moveFile(brokenSymlink, brokenSymlinkCopy)
...
    # Test moveDir
    moveDir(subDir, subDir2)
```
but it's not a sufficient test for those APIs, these only test symlinks; please add a block:
```
  block: # moveFile
...
  block: # moveDir
...
```
above or below the existing block
```
  block: # copyFile, copyFileToDir
```
and use similar logic as in those tests

regarding testing moveDir on separate partition, this may be hard to test in CI so it's ok to skip testing this behavior (unless you have an idea); but please test locally

**Comment by maradotwebp** [comment]
and for the Windows error issue? The current code doesn't compile on Windows because EXDEV is only available on POSIX. See https://github.com/nim-lang/Nim/pull/18223#issuecomment-858067641

**Comment by timotheecour** [comment]
ya i was searching windows docs (I'm not a windows user); 

note that on windows the relevant error seems:
`System Error. Code: 5. Access is denied`

how about:
* add a param `isMoveDir: bool` to tryMoveFSObject
* if isMoveDir and on windows, check if error code is 5 (maybe use `const AccessDeniedError = 5`), if so return false
* for moveFile, IIUC, the pre-existing logic was correct because windows allows moving files across partitions

let me know if anything is unclear

(i've removed the "easy" tag from https://github.com/nim-lang/Nim/issues/18216 but I think you're almost there ;-) )

File: lib/pure/os.nim [hunk 3]
```diff
@@ -2009,28 +2009,32 @@ proc removeFile*(file: string) {.rtl, extern: "nos$1", tags: [WriteDirEffect], n
...
-proc tryMoveFSObject(source, dest: string): bool {.noWeirdTarget.} =
+proc tryMoveFSObject(source, dest: string, isMoveDir: bool): bool {.noWeirdTarget.} =
   ## Moves a file or directory from `source` to `dest`.
   ##
   ## Returns false in case of `EXDEV` error.
   ## In case of other errors `OSError` is raised.
   ## Returns true in case of success.
+  const AccessDeniedError = OSErrorCode(5)
   when defined(windows):
     when useWinUnicode:
```
Comment (timotheecour) [inline lib/pure/os.nim]:
```suggestion
  when defined(windows):
    const AccessDeniedError = OSErrorCode(5)
    when useWinUnicode:
```

(IIUC it's windows specific)

File: lib/pure/os.nim [hunk 4]
```diff
@@ -2009,28 +2009,32 @@ proc removeFile*(file: string) {.rtl, extern: "nos$1", tags: [WriteDirEffect], n
...
-  return true
+    result = c_rename(source, dest) == 0'i32
+
+  if not result:
+    let err = osLastError()
+    var isAccessDeniedError: bool
+    when defined(windows):
+      isAccessDeniedError = isMoveDir and err == AccessDeniedError
+    else:
+      isAccessDeniedError = err == EXDEV.OSErrorCode
```
Comment (timotheecour) [inline lib/pure/os.nim]:
```suggestion
    let isAccessDeniedError =
      when defined(windows): isMoveDir and err == AccessDeniedError
      else: err == EXDEV.OSErrorCode
```

Comment (maradotwebp) [reply lib/pure/os.nim]: huh, didn't know when could be used that way just like an if. Nice :D

File: lib/pure/os.nim [hunk 5]
```diff
@@ -2009,28 +2009,32 @@ proc removeFile*(file: string) {.rtl, extern: "nos$1", tags: [WriteDirEffect], n
   if not tryRemoveFile(file):
     raiseOSError(osLastError(), file)
 
-proc tryMoveFSObject(source, dest: string): bool {.noWeirdTarget.} =
+proc tryMoveFSObject(source, dest: string, isMoveDir: bool): bool {.noWeirdTarget.} =
   ## Moves a file or directory from `source` to `dest`.
   ##
   ## Returns false in case of `EXDEV` error.
```
Comment (timotheecour) [inline lib/pure/os.nim]: update this comment to reflect reality

File: lib/pure/os.nim [hunk 6]
```diff
@@ -2051,8 +2055,8 @@ proc moveFile*(source, dest: string) {.rtl, extern: "nos$1",
   ## * `removeFile proc <#removeFile,string>`_
   ## * `tryRemoveFile proc <#tryRemoveFile,string>`_
 
-  if not tryMoveFSObject(source, dest):
-    when not defined(windows):
+  if not tryMoveFSObject(source, dest, isMoveDir=false):
+    when defined(windows):
```
Comment (timotheecour) [inline lib/pure/os.nim:2059]: why change to `when defined(windows):` ? seems like a bug, it'll silently do nothing on posix when this is reached. instead how about:
```nim
when defined(windows):
  doAssert false
    # this points to a stdlib bug, not user error, on windows it should move
    # the file even if across partitions
else:
  # Fallback to copy & del
  ...
```

File: lib/pure/os.nim [hunk 7]
```diff
@@ -2051,8 +2055,8 @@ proc moveFile*(source, dest: string) {.rtl, extern: "nos$1",
   ## * `removeFile proc <#removeFile,string>`_
   ## * `tryRemoveFile proc <#tryRemoveFile,string>`_
 
-  if not tryMoveFSObject(source, dest):
-    when not defined(windows):
+  if not tryMoveFSObject(source, dest, isMoveDir=false):
```
Comment (timotheecour) [inline lib/pure/os.nim]:
```suggestion
  if not tryMoveFSObject(source, dest, isMoveDir = false):
```

File: lib/pure/os.nim (hunk 6 above)
Comment (maradotwebp) [reply lib/pure/os.nim:2059]: whoops, yeah, sorry

File: lib/pure/os.nim [hunk 8]
```diff
@@ -2009,8 +2009,8 @@ proc removeFile*(file: string) {.rtl, extern: "nos$1", tags: [WriteDirEffect], n
   if not tryRemoveFile(file):
     raiseOSError(osLastError(), file)
 
-proc tryMoveFSObject(source, dest: string): bool {.noWeirdTarget.} =
-  ## Moves a file or directory from `source` to `dest`.
+proc tryMoveFSObject(source, dest: string, isMoveDir: bool): bool {.noWeirdTarget.} =
+  ## Moves a file (or directory if `isMoveDir` is true) from `source` to `dest`.
   ##
   ## Returns false in case of `EXDEV` error.
```
Comment (timotheecour) [inline lib/pure/os.nim]: i see you've udpated the comment above, which is good, but that comment mentioning EXDEV also needs to be updated (for windows, it returns false if isMoveDir and `AccessDeniedError = OSErrorCode(5)` which can be obtained for dir moves across partitions)

Comment (maradotwebp) [reply lib/pure/os.nim]: Oh my god, thanks for being this patient with me ^^

File: tests/stdlib/tos.nim [hunk 9]
```diff
@@ -261,6 +261,43 @@ block fileOperations:
 
     removeDir(dname)
 
+block: # moveFile
```
Comment (timotheecour) [inline tests/stdlib/tos.nim:264]: don't write under cwd, that's bad style (eg this could overwrite existing files, or files from other tests; remember that testament runs in parallel); another problem is that if this crashes, it'll make git status not clean

instead, create a unique dir, for isolation eg:
```nim
block: # moveFile, moveDir
  let dir = getTempDir() / "D20210609T151608"
  createDir(dir)
  defer: removeDir(dir)
  # now only operate inside dir, eg:
  block: # moveFile
     writeFile(dir / "a.txt", "")
     ...
  block: # moveDir
     ...
```

File: tests/stdlib/tos.nim [hunk 10]
```diff
@@ -261,6 +261,43 @@ block fileOperations:
...
+  writeFile("a.txt", "")
+  moveFile("a.txt", "b.txt")
+  doAssert not fileExists("a.txt")
+  doAssert fileExists("b.txt")
+  removeFile("b.txt")
+
+  createDir("moveFile_test/")
```
Comment (timotheecour) [inline tests/stdlib/tos.nim]: no trailing slash here and elsewhere in your test

File: lib/pure/os.nim [hunk 11]
```diff
@@ -2051,7 +2055,7 @@ proc moveFile*(source, dest: string) {.rtl, extern: "nos$1",
   ## * `removeFile proc <#removeFile,string>`_
   ## * `tryRemoveFile proc <#tryRemoveFile,string>`_
 
-  if not tryMoveFSObject(source, dest):
+  if not tryMoveFSObject(source, dest, isMoveDir = false):
     when not defined(windows):
```
Comment (timotheecour) [inline lib/pure/os.nim]: tiny, optional, nit:
simplify as:
when defined(windows): ... else: ...

File: tests/stdlib/tos.nim [hunk 12]
```diff
@@ -261,6 +261,51 @@ block fileOperations:
...
+  createDir(tempDir / "moveFile_test")
+  writeFile(tempDir / "moveFile_test/a.txt", "")
+  moveFile(tempDir / "moveFile_test/a.txt", tempDir / "moveFile_test/b.txt")
+  doAssert not fileExists(tempDir / "moveFile_test/a.txt")
+  doAssert fileExists(tempDir / "moveFile_test/b.txt")
+  removeDir(tempDir / "moveFile_test")
+
+  createDir(tempDir / "moveFile_test")
+  writeFile(tempDir / "a.txt", "")
+  moveFile(tempDir / "a.txt", tempDir / "moveFile_test/b.txt")
```
Comment (timotheecour) [inline tests/stdlib/tos.nim:284]:
```suggestion
  writeFile(tempDir / "a.txt", "")
  doAssertRaises(OSError): moveFile(tempDir / "a.txt", tempDir / "moveFile_test/b.txt")
  createDir(tempDir / "moveFile_test")
  moveFile(tempDir / "a.txt", tempDir / "moveFile_test/b.txt")
```

ditto for moveDir test

File: tests/stdlib/tos.nim [hunk 13]
```diff
@@ -261,6 +261,52 @@ block fileOperations:
...
+  defer: removeDir(tempDir)
+
+  createDir(tempDir / "moveDir_test")
+  moveDir(tempDir / "moveDir_test/", tempDir / "moveDir_test_dest")
+  doAssert not dirExists(tempDir / "moveDir_test")
+  doAssert dirExists(tempDir / "moveDir_test_dest")
+  removeDir(tempDir / "moveDir_test_dest")
+
+  createDir(tempDir / "moveDir_test")
+  writeFile(tempDir / "moveDir_test/a.txt", "")
```
Comment (timotheecour) [inline tests/stdlib/tos.nim:301]:
```suggestion
  writeFile(tempDir / "moveDir_test/a.txt", "")
  doAssertRaises(OSError): moveDir(tempDir / "moveDir_test", tempDir / "nonexistent/moveDir_test_dest")
```

**Review by timotheecour — APPROVED** [review]
LGTM, thanks for your patience, looks correct now; 
* did you verify the PR work locally with the original issue you saw in #18216 ? 
* ditto with file move across partition? (ie is that still working)?
(just as sanity check)

**Comment by maradotwebp** [comment]
Yep, works for me :D
And you don't need to thank me for your patience, I need to thank YOU for your patience.
I'll rebase and then the PR is good to go.

**Comment by timotheecour** [comment]
> I'll rebase and then the PR is good to go.

note that PRs get squashed and merged (and this is enforced in settings), so usually there's no need to squash manually (good to keep history in PR); the exception is when rebasing causes lots of conflicts that are hard to resolve otherwise

**Comment by maradotwebp** [comment]
oh, ok ^^

File: lib/pure/os.nim [hunk 14]
```diff
@@ -2009,28 +2009,32 @@ proc removeFile*(file: string) {.rtl, extern: "nos$1", tags: [WriteDirEffect], n
   if not tryRemoveFile(file):
     raiseOSError(osLastError(), file)
 
-proc tryMoveFSObject(source, dest: string): bool {.noWeirdTarget.} =
-  ## Moves a file or directory from `source` to `dest`.
+proc tryMoveFSObject(source, dest: string, isMoveDir: bool): bool {.noWeirdTarget.} =
```
Comment (Araq) [inline lib/pure/os.nim]: Sorry but what does `isMoveDir` mean?  `isMovable`? `isDir`? `isMovableDir` (but then what are not movable directories)? Please use a clearer name.

Comment (timotheecour) [reply lib/pure/os.nim]: well it's a private proc, and `isMoveDir` is explained in the 1st line of comment; it means that it comes from `moveDir` as opposed to `moveFile`, a distinction which turned out to be needed for this fix.

how about `fromMoveDir` or `callerIsMoveDir` then so we can move forward with this PR? or, please make a suggestion

Comment (maradotwebp) [reply lib/pure/os.nim]: +1 for `isDir`, `tryMoveFSObject(source, dest, isDir = true)` looks semantically correct to me.

Comment (timotheecour) [reply lib/pure/os.nim]: ok isDir better, please go ahead with that

Comment (Araq) [reply lib/pure/os.nim]: agreed, `isDir` is fine.
