### PR TITLE
fixes #4299 #12492 #10849;  lambda lifting for JS backend

### LINKED ISSUE #4299: Nested generic procs scoping in JS backend
Right now generic procs are compiled to families of functions at the top scoping level. If the proc in question is contained inside a scope, this can break code.
Example:

``` nim
proc scopeProc() =
  proc normalProc() =
    echo "In normalProc"

  proc genericProc[T]() =
    normalProc()

  genericProc[string]()

scopeProc()
```

compiles to this:

``` js
function genericproc_23014() {

  var F={procname:"genericProc.genericProc",prev:framePtr,filename:"test_js_generics.nim",line:0};
  framePtr = F;
  normalproc_23005();
  framePtr = framePtr.prev;
}
function scopeproc_23003() {

  function normalproc_23005() {

    var F={procname:"scopeProc.normalProc",prev:framePtr,filename:"test_js_generics.nim",line:0};
    framePtr = F;
    rawEcho(makeNimstrLit("In normalProc"));
    framePtr = framePtr.prev;
  }
  var F={procname:"test_js_generics.scopeProc",prev:framePtr,filename:"test_js_generics.nim",line:0};
  framePtr = F;
  genericproc_23014();
  framePtr = framePtr.prev;
}
scopeproc_23003();
```

which crashes in runtime since `genericproc_23014` has no access to `normalproc_23005`, which is local to `scopeproc_23003`.

Tested with fresh devel branch.

### LINKED ISSUE #10849: Generic closure fields do not work on JS backend
Codegen for generic closures seems to be broken on the JS backend (works fine when compiled to C).

### Example

```nim
type
  Generic[T] = ref object
    getState*: proc(): T

proc newGeneric[T](): Generic[T] =
  var state: T

  proc getState[T](): T =
    state

  Generic[T](getState: getState)

let g = newGeneric[int]()
let state = g.getState()
echo(state)
```

### Current Output

Running the resulting JS code crashes with:
```
/home/fabian/git/NimExperiments/closure_methods/draft4.js:118
		result_79051 = state_79038;
```
Note: The same pattern works on JS when the example doesn't use generics or when the closure is returned directly, i.e., not as an object field.

### Expected Output

Codegen for C works fine and prints 0.

### Additional Information
```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-03-15
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 328901757a2bb5d482afafdd0e45bd54355c90b5
active boot switches: -d:release
```

The generated code is:

```javascript
function get_state_79048() {
	var result_79051 = 0;

	var F={procname:"getState.getState",prev:framePtr,filename:"draft4.nim",line:0};
	framePtr = F;
		F.line = 9;
		result_79051 = state_79038;
	framePtr = F.prev;

	return result_79051;

}

function new_generic_79027() {
	var result_79037 = null;

	var F={procname:"newGeneric.newGeneric",prev:framePtr,filename:"draft4.nim",line:0};
	framePtr = F;
		F.line = 6;
		F.line = 6;
		var state_79038 = 0;
		result_79037 = {getState: get_state_79048};
	framePtr = F.prev;

	return result_79037;

}
var g_79078 = new_generic_79027();
var state_79079 = g_79078.getState();
rawEcho(cstrToNimstr((state_79079)+""));
```

A guess: The compiler did not see that `get_state_79048` closes over `state_79038` and put it into global scope? If it would put the function between the lines `var state_79038 = 0;` and `result_79037 = {getState: get_state_79048};` it would work (which is what happens if I make the example non generic).

### LINKED ISSUE #12492: nested proc vm compilation error when compiling to javascript
When compiling to JS, compiling a nested proc to the vm does not work like in the example. This is strage, because compiling to JS should not affect if I can compile something to the VM.

### Example
`nim js -r scratch.nim`
```nim
proc foo() =
  var i = 0
  proc bar() =
    inc i

  bar()
  echo i

foo()
static:
  foo()
```

### Current Output
```
/tmp/scratch.nim(4, 9) Error: cannot evaluate at compile time: i
```

### Expected Output
```
Hint: scratch [Processing]
1
CC: scratch.nim
Hint:  [Link]
Hint: operation successful (21875 lines compiled; 0.161 sec total; 25.77MiB peakmem; Debug Build) [SuccessX]
Hint: /tmp/scratch  [Exec]
1
```

### Additional Information
 * Compiling with ``nim c -r scratch.nim`` shows no errors at all.
 * This is importat, because my refactoring of the json.to macro test requires this to work.

    https://github.com/nim-lang/Nim/blob/6bfa4eb6c51106d9720a61267d47a5e60e3c3d2f/tests/stdlib/tjsonmacro.nim#L299

### PR DESCRIPTION
**Pull request by ringabout**
fixes #4299 
fixes #12492 
fixes #10849

It binds `function` with `env`: `function.bind(:env)` to ease codegen for now

### CODE REVIEW

File: compiler/jsgen.nim [hunk 1]
```diff
@@ -106,25 +106,18 @@ type
...
 
 proc indentLine(p: PProc, r: Rope): Rope =
   var p = p
-  var ind = 0
-  while true:
-    inc ind, p.blocks.len + p.extraIndent
-    if p.up == nil or p.up.prc != p.prc.owner:
-      break
-    p = p.up
+  var ind = p.blocks.len + p.extraIndent
```
Comment (ringabout) [inline compiler/jsgen.nim]:
```suggestion
  let ind = p.blocks.len + p.extraIndent
```

**Comment by metagn** [comment]
I've wondered if there was a way to do this while allowing the old generation via some `{.jsInner.}` call convention, if it's still deemed to be useful.

**Comment by SirOlaf** [comment]
This actually breaks nimforum frontend build because of https://github.com/nim-lang/Nim/issues/17187

**Comment by ringabout** [comment]
Well, it was arguably not correct for JS case since it doesn't work for C either. I will fix the build of nim forum soon

**Comment by SirOlaf** [comment]
Yeah nimforum is 100% wrong here, just wanted to bring it up in case you didn't know. `illegalCapture` could probably be relaxed to allow `result` with ref type though, was gonna make a pr for that. Note that this would not fix nimforum as it has more of these without using `result`.

**Comment by ringabout** [comment]
Now the forusm should build with `jsnolambdalifting`  https://github.com/nim-lang/nimforum/pull/369
