### PR TITLE
fixes #16246

### LINKED ISSUE #16246: [ARC] codegen error when init seq[T] in callback if T aliased w/ {.nodecl.}
This is a bit of a bizarre one. Took a while to find the culprit, thanks to a mix of code bases involved.

It seems like using callbacks with ARC can lead to a codegen error when sequences are involved with (certain?) type aliases, in particular `cuint` + `uint32` or any alias using `{.nodecl.}`.

### Example

This is the actual issue I isolated:
```nim
proc test() =
  var values = newSeq[cuint](8)
  # var values: seq[cuint] does not produce codegen error
  var drawCb = proc(): seq[uint32] =
    result = newSeq[uint32](10)

test()
```
After I noticed that `cuint` is just an alias for `uint32` I tried it with a custom alias, which works fine. However, a look at the source made me realize that `cuint` uses `{.nodecl.}`. So the following produces a similar issue:
```nim
type
  myInt {.nodecl.} = int # works if `myInt = int` used instead

proc test() =
  var values = newSeq[myInt](8)
  # var values: seq[cuint] does not produce codegen error
  var drawCb = proc(): seq[int] =
    result = newSeq[int](10)

test()
```

### Current Output

```
/home/basti/.cache/nim/testArr_d/@mtestArr.nim.c: In function 'colonanonymous___o5QORvA9cwDAJXgNLYWpaQQ':
/home/basti/.cache/nim/testArr_d/@mtestArr.nim.c:117:11: error: incompatible types when assigning to type 'tySequence__9bAGqSvkAaFL9bWjsEPslrFA' {aka 'struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA'} from type 'tySequence__U48dCdy0noze9bNL2psZZGA' {aka 'struct tySequence__U48dCdy0noze9bNL2psZZGA'}
  117 |  result = newSeq__MSj7lRk8D7wQIj3uPO6UrA(((NI) 10));
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/basti/src/nim/nim_git_repo/lib -I/tmp -o /home/basti/.cache/nim/testArr_d/@mtestArr.nim.c.o /home/basti/.cache/nim/testArr_d/@mtestArr.nim.c' failed with exit code: 1
```

### Expected Output
Compilation without issue.

### Possible Solution

Possibly fix handling of name mangling (?) for aliased types using `{.nodecl.}`.

### Additional Information

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-11-29
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: d29eddf92a1b8147c4709fd828f77152c1f3aab2
active boot switches: -d:release -d:danger
```

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

File: compiler/types.nim [hunk 1]
```diff
@@ -1144,6 +1145,13 @@ proc sameTypeAux(x, y: PType, c: var TSameTypeClosure): bool =
   of tyEmpty, tyChar, tyBool, tyNil, tyPointer, tyString, tyCstring,
      tyInt..tyUInt64, tyTyped, tyUntyped, tyVoid:
     result = sameFlags(a, b)
+    if result and PickyCAliases in c.flags:
+      # additional requirement for the caching of generics for importc'ed types:
+      # the symbols must be identical too:
```
Comment (Vindaar) [inline compiler/types.nim:1150]: Given that I should learn: Why is checking the flags here equivalent to the symbols being identical? Is it just because we have checked for equality of the actual type etc. before in this proc?

Also it seems confusing that `sameFlags` is called before, but then we check more flags here.

In general what makes reading compiler code hard for me is that most procs have no short comment about their intent, e.g. this `sameTypeAux` could use a couple of lines saying what is needed for a type to be considered the same for instance.

**Comment by Vindaar** [comment]
Thanks a lot! I just tested the changes locally and indeed it fixes the issue here as well in a different (but similar) piece of code than the one originally shown in the issue.

It also fixes the problem I reported for the C++ backend that happened without ARC interestingly enough.

File: compiler/types.nim (hunk 1 above)
Comment (Araq) [reply compiler/types.nim:1150]: > Given that I should learn: Why is checking the flags here equivalent to the symbols being identical? Is it just because we have checked for equality of the actual type etc. before in this proc?

Because we have established they are of the type *kind* which for `tyInt` etc means they are atomic types. Arguably we could also have checked for `a.sym == b.sym` instead but this would be worse for type aliases to `cint`, e.g. `type myint = cint`.

> Also it seems confusing that sameFlags is called before, but then we check more flags here.

`sameFlags` looks at the type flags but `importc` is stored as a sym flag. These are different things.

> this sameTypeAux could use a couple of lines saying what is needed for a type to be considered the same for instance.

Nim's type system has both structural and nominal type system aspects and type equality is supposed to follow from the spec.

**Comment by Araq** [comment]
> It also fixes the problem I reported for the C++ backend that happened without ARC interestingly enough.

That is not unexpected as Orc only made the bug manifest in a novel way, the bug was there from the beginning, more or less.

File: compiler/types.nim (hunk 1 above)
Comment (Vindaar) [reply compiler/types.nim:1150]: Thanks for the clarification!
