### PR TITLE
fix #8434 (incomplete info in errmsg about 'required type')

### LINKED ISSUE #8434: type mismatch shows wrong type for union types T1|T2|T3|T4: only keeps T1 or T2, discards rest
type mismatch shows wrong type for union types T1|T2|T3|T4: only keeps 1st 2 types T1 or T2, discards rest (T3, T4) in error msg

```nim
#[ 
Error: type mismatch: got <byte, int literal(0)>
but expected one of:
proc fun0[T1: int | float |
    object | array | seq](a1: T1; a2: int)
  first type mismatch at position: 1
  required type: T1: int or float
  but expression 'byte(1)' is of type: byte

expression: fun0(byte(1), 0)
    fun0(byte(1), 0)
        ^
 ]#
proc fun0[T1:int|float|object|array|seq](a1:T1, a2:int)=discard
when defined(case1):
  fun0(byte(1), 0)
```

Note: even more problematic when type expressions or aliases are involved

### PR DESCRIPTION
**Pull request by skilchen**
fixes #8434 (hopefully in a reasonable way ...)

### CODE REVIEW

File: compiler/types.nim [hunk 1]
```diff
@@ -496,9 +496,15 @@ proc typeToString(typ: PType, prefer: TPreferedDesc = preferName): string =
       add(result, typeToString(t.sons[i]))
     result.add "]"
   of tyAnd:
-    result = typeToString(t.sons[0]) & " and " & typeToString(t.sons[1])
+    for i in 0 .. t.sons.high:
```
Comment (LemonBoy) [inline compiler/types.nim]: Minor nit, you can use `for i, typ in t.sons:` to get both the index and the element in a compact way
