### PR TITLE
Fix enum regression

### LINKED ISSUE #9908: Regression: Enum with tuple with first argument non-ordinal crashes does not give compiler error
```
type
    X = enum
        a = ("a", "b")
```
`nim_temp.exe c t.nim` gives - `Error: unhandled exception: over- or underflow [OverflowError]`
`nim c t.nim` gives no error but assigns some very high int value which leads to the above overflow in debug mode.

It gave a proper error in v0.18.0 as can be seen on the nim playground.

Reason -
It was commented out in this commit and removed in some further commit -
https://github.com/nim-lang/Nim/commit/0d56dd4677b8f6b080844db8655b41c10bee68c1#diff-cf84326149c5f35a0ac0adf0ae6c1ef3R95 with the comment `check usages of getOrdValue`

### PR DESCRIPTION
**Pull request by nc-x**
Fixes #9908

### CODE REVIEW

**Comment by Araq** [comment]
Reading the code, I think

```nim

type E = enum
  myVal = 80.9
```

also triggers an internal compiler crash.

File: compiler/semtypes.nim [hunk 1]
```diff
@@ -98,6 +100,8 @@ proc semEnum(c: PContext, n: PNode, prev: PType): PType =
       of tyString, tyCString:
         strVal = v
         x = counter
+      of tyFloat..tyFloat128:
+        localError(c.config, v.info, errOrdinalTypeExpected)
       else:
         x = getOrdValue(v)
```
Comment (Araq) [inline compiler/semtypes.nim]: No, you need to check before the ``getOrdValue`` for ``isOrdinalType``.

**Comment by nc-x** [comment]
Done.
