### PR TITLE
fix #20023 hash for generic tables

### LINKED ISSUE #20023: Table has inconsistent hash
The hash of a `Table` depends on how that `Table` was derived.

This violates the prime rule of hashes (If two values compare equal, their hashes must also be equal) and results in corrupt data structures when `Table` is used as a key in a hashed container.

### Example
```nim
import std/tables
import std/hashes

let t = ()
var a = toTable({t:t})
del(a,t)
let b = default(typeof(a))

assert a==b , "tables are equal"
# this following assertion fails!
assert hash(a) == hash(b), "table hashes are equal"
```

### Current Output
```
Error: unhandled exception: /Users/dan/Documents/fates/nim/fates/issue.nim(11, 8) `hash(a) == hash(b)` table hashes are equal [AssertionDefect]
```

### Expected Output
no error

### Possible Solution

* I believe the issue is that the hash depends on the allocated table size, since this also fails:
```
var a=initTable[int,int](initialSize=10)
var b=initTable[int,int](initialSize=100)
assert a==b , "tables are equal"
# this following assertion fails!
assert hash(a) == hash(b), "table hashes are equal"
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.6.6 [MacOSX: arm64]
Compiled at 2022-05-05
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise
```

### PR DESCRIPTION
**Pull request by bung87**
fix #20023

not sure is right or not, since the K,V may be custom type

### CODE REVIEW

File: lib/pure/collections/tables.nim [hunk 1]
```diff
@@ -2890,3 +2890,18 @@ iterator mvalues*[A](t: CountTableRef[A]): var int =
     if t.data[h].val != 0:
       yield t.data[h].val
       assert(len(t) == L, "the length of the table changed while iterating over it")
+
+proc hash*[K,V](s: Table[K,V]): Hash =
+  for p in pairs(s):
+    result = result xor hash(p)
```
Comment (Araq) [inline lib/pure/collections/tables.nim:2907]: How do we know if `xor` is good enough for mixing hashes? I understand that we need a commutative operation, but still.

Comment (bung87) [reply lib/pure/collections/tables.nim:2907]: now I use default computation

File: lib/pure/collections/tables.nim [hunk 2]
```diff
@@ -2893,15 +2893,15 @@ iterator mvalues*[A](t: CountTableRef[A]): var int =
 
 proc hash*[K,V](s: Table[K,V]): Hash =
   for p in pairs(s):
-    result = result xor hash(p)
+    result = result !& hash(p)
```
Comment (rotu) [inline lib/pure/collections/tables.nim]: This is definitely not right. `!&` is order-dependent, but you need something order-independent. `xor` fits that bill, but `+` is probably better, since identical values don't cancel.

Comment (bung87) [reply lib/pure/collections/tables.nim]: `+` may cause out of range ?

File: lib/pure/collections/tables.nim [hunk 3]
```diff
@@ -2893,15 +2893,15 @@ iterator mvalues*[A](t: CountTableRef[A]): var int =
...
   result = !$result
 
 proc hash*[K,V](s: OrderedTable[K,V]): Hash =
   for p in pairs(s):
-    result = result xor hash(p)
+    result = result !& hash(p)
```
Comment (rotu) [inline lib/pure/collections/tables.nim:2912]: This on the other hand is right, since equality for ordered tables *is* order-dependent

File: lib/pure/collections/tables.nim (hunk 2 above)
Comment (rotu) [reply lib/pure/collections/tables.nim]: No idea why `Hash` was decided to be `int` instead of `uint`, but you're right. In that case, I'd go with `+%` instead of `+`

Comment (bung87) [reply lib/pure/collections/tables.nim]: maybe u could complete this and add more test, am not good at math :(

Comment (rotu) [inline lib/pure/collections/tables.nim]:
```suggestion
    result = result +% hash(p)
```

File: lib/pure/collections/tables.nim [hunk 4]
```diff
@@ -2893,15 +2893,15 @@ iterator mvalues*[A](t: CountTableRef[A]): var int =
...
   result = !$result
 
 proc hash*[V](s: CountTable[V]): Hash =
   for p in pairs(s):
-    result = result xor hash(p)
+    result = result !& hash(p)
```
Comment (rotu) [inline lib/pure/collections/tables.nim]:
```suggestion
    result = result +% hash(p)
```

**Comment by Araq** [comment]
Why should hash tables themselves be useful as hash table keys? Seems to me that it only encourages poorly written code coming from people yet trying to use hash tables effectively.

**Comment by rotu** [comment]
> Why should hash tables themselves be useful as hash table keys? Seems to me that it only encourages poorly written code coming from people yet trying to use hash tables effectively.

The use case that I had for it was to represent sparse tensors. Each basis element is a product of basis elements from various factor spaces (a Table from the space to the basis vector)

**Comment by rotu** [comment]
> Why should hash tables themselves be useful as hash table keys? Seems to me that it only encourages poorly written code coming from people yet trying to use hash tables effectively.

The use case that I had for it was to represent sparse tensors. Each basis tensor is a product of basis elements from various factor spaces (a `Table[string,int]` from the space to the basis vector) and each tensor is a weighted sum of basis tensors (a `Table[BasisTensor,float]`).

The reason to use `HashMap` was not because it’s the best collection, but because it’s the only generic associative (key-value) container. I would have been happy to use some other, but unfortunately none exist in the standard library.

Another natural application would be memoization of any function whose arguments contain a HashMap.

File: lib/pure/collections/tables.nim [hunk 5]
```diff
@@ -2890,3 +2890,18 @@ iterator mvalues*[A](t: CountTableRef[A]): var int =
     if t.data[h].val != 0:
       yield t.data[h].val
       assert(len(t) == L, "the length of the table changed while iterating over it")
+
+proc hash*[K,V](s: Table[K,V]): Hash =
+  for p in pairs(s):
+    result = result +% hash(p)
```
Comment (Araq) [inline lib/pure/collections/tables.nim]:
```suggestion
    result = result xor hash(p)
```

File: lib/pure/collections/tables.nim [hunk 6]
```diff
@@ -2890,3 +2890,18 @@ iterator mvalues*[A](t: CountTableRef[A]): var int =
...
+  result = !$result
+
+proc hash*[K,V](s: OrderedTable[K,V]): Hash =
+  for p in pairs(s):
+    result = result !& hash(p)
+  result = !$result
+
+proc hash*[V](s: CountTable[V]): Hash =
+  for p in pairs(s):
+    result = result +% hash(p)
```
Comment (Araq) [inline lib/pure/collections/tables.nim]:
```suggestion
    result = result xor hash(p)
```

**Comment by Araq** [comment]
CI is still red, unfortunately.
