### PR TITLE
fix #17467 1st call to rand is now non-skewed; allow seed == 0

### LINKED ISSUE #8589: `random` doesn't generate uniform numbers (very high correlation) when using seed from time
#[ 
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r tests/nim/stdlib/t02_random_seed.nim

/tmp/nim//app
0.7110418528567215
/tmp/nim//app
0.7110418342302638
etc => BUG: they're all very close to each other
 ]#

```nim
import times
import random

proc test()=
  let seed = now().toTime.toUnix
  echo
  seed.randomize
  echo rand(1.0)
  # for i in 0..10: echo rand(1.0) # this would be ok

test()
```

```d
rdmd --eval=' auto seed = Clock.currTime().toUnixTime; auto rnd = Random(seed.to!int); uniform(0.0, 1.0, rnd).writeln'
0.22832

rdmd --eval=' auto seed = Clock.currTime().toUnixTime; auto rnd = Random(seed.to!int); uniform(0.0, 1.0, rnd).writeln'
0.0909191
=> D works
```

### LINKED ISSUE #17467: 1st call to `rand(1.0)` generates predictable values < 1e-4 for seeds in 0..<26844, unlike C++, python, D, ...
## Example
this shows that whatever (small) seed is picked, the 1st call to rand() gives a predictably small value < 1e-4, ie, skews the distribution.

```nim
import std/random
proc main()=
  let n = 100_000
  for i in 1..<n:
    randomize(i)
    let x = rand(1.0)
    doAssert x < 1e-4, $(x, i) # this passes for i in 0..<26844, but should not
main()
```
 
This is a bug, other languages don't have this issue:
## nim: fails
by fail, I mean it produces skewed results
(see example above)

## python: works
```py
import random
for i in range(0,10):
  random.seed(a=i)
  print(random.random())
```
prints:
```
0.8444218515250481
0.13436424411240122
0.9560342718892494
0.23796462709189137
0.23604808973743452
0.6229016948897019
0.793340083761663
0.32383276483316237
0.2267058593810488
0.46300735781502145
```

## D: works
```d
import std.random,std.conv,std.stdio;
void main(){
  //auto seed = Clock.currTime().toUnixTime;
  for(int i=0;i<10;i++) {
    auto rnd = Random(i.to!int);
    uniform(0.0, 1.0, rnd).writeln;
  }
}
```

prints:
```
0.548814
0.417022
0.435995
0.550798
0.96703
0.221993
0.89286
0.0763083
0.873429
0.0103742

```

## C++ works
```c++

#include <random>
#include <iostream>

void fn2() {
  // std::random_device rd;
  std::uniform_real_distribution<double> dist(0.0, 1.0);
  for (int i=0; i<10; ++i){
    std::mt19937 mt(i);
    std::cout << dist(mt) << "\n";
  }
}

int main() {
  // fn1();
  fn2();
  return 0;
}
```
prints:
```
0.592845
0.997185
0.185082
0.0707249
0.900621
0.0551801
0.947476
0.227339
0.0111144
0.364461
```

### Additional Information
1.5.1 d6a16020fe98b467459544ee4cfafe61d681f918

## links
https://stackoverflow.com/questions/19665818/generate-random-numbers-using-c11-random-library
https://channel9.msdn.com/Events/GoingNative/2013/rand-Considered-Harmful

this is also related to an issue I had previously raised: https://github.com/nim-lang/Nim/issues/8589

### LINKED ISSUE #18658: First call to Rand.random(100) after a seeded initRand() is always 0
Something extremely unusual:

```nim
import std / random

const Max = 100
for i in 1 .. 10:
  var x = initRand(i)
  echo x.rand(Max)
```

Changing `Max` to, say, `99` or `101` gives us reasonably random output, however, leave it as `100` [and we get all zeros.](https://play.nim-lang.org/#ix=3vmT)

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #17467: 1st call to rand is now non-skewed; this avoids skewing distributions
* use `-d:nimLegacyRandomInitRand` for restoring previous behavior, for a transition time
* allow passing arbitrary seed including 0

* (EDIT) fixes https://github.com/nim-lang/Nim/issues/8589 (see https://github.com/nim-lang/Nim/issues/8589#issuecomment-838612351)
* (EDIT) fixes https://github.com/nim-lang/Nim/issues/18658

### CODE REVIEW

File: lib/pure/random.nim [hunk 1]
```diff
@@ -563,17 +562,19 @@ proc initRand*(seed: int64): Rand =
 
     let now = getTime()
     var r2 = initRand(now.toUnix * 1_000_000_000 + now.nanosecond)
-
-  doAssert seed != 0 # 0 causes `rand(int)` to always return 0 for example.
+  let seed = if seed != 0: seed else: 1 # because 0 is a fixed point
```
Comment (konsumlamm) [inline lib/pure/random.nim]: This should be documented (also doesn't seem related to the title of this PR).

Comment (timotheecour) [reply lib/pure/random.nim]: done (and fixed title)

File: changelog.md [hunk 2]
```diff
@@ -48,6 +48,17 @@
 - Added `randState` template that exposes the default random number generator.
   Useful for library authors.
 
+- Added `random.initRand()` overload with no argument which uses the current time as a seed.
+
+- `random.initRand(seed)` now allows `seed == 0`
```
Comment (ringabout) [inline changelog.md]:
```suggestion
- `random.initRand(seed)` now allows `seed == 0`.
```

Comment (timotheecour) [reply changelog.md]: done

**Comment by juancarlospaco** [comment]
What are the benefits of seed `0` ?, would it be better to enforce a non-zero seed ?.

**Comment by timotheecour** [comment]
> What are the benefits of seed 0 ?, would it be better to enforce a non-zero seed ?.

simpler API with less edge cases.
PTAL
