### PR TITLE
fix #16576: honor matrix in testament by making such tests non joinable

### LINKED ISSUE #16340: testament: `matrix` in spec should prevent test from joining megatest
I found this while reviewing https://github.com/nim-lang/Nim/pull/16320:
it uses `matrix: "-d:ssl"` but still is joined in megatest. Note that this probably should've used `cmd: nim $target -d:ssl $file` but that's not the point of this issue (and in fact `matrix: "-d:ssl"` actually makes more sense even with single entry since it's shorter)

`isJoinableSpec` should handle this properly

### Example
see https://github.com/nim-lang/Nim/pull/16320
```nim
discard """
  matrix: "-d:ssl"
"""
import openssl
```

### Current Output
test is joined in megatest

### Expected Output
test is not joined in megatest, or alternatively we can create 1 megatest per unique matrix options, so that we still get performance benefit of megatest, while honoring matrix spec.

### Additional Information
devel 1.5.1 0b73106ccf983565d34654ee8b1167827b53b01a
`isJoinableSpec` is what should be fixed

### LINKED ISSUE #16576: testament can silently ignore `matrix` spec
refs https://github.com/nim-lang/Nim/pull/16567#issuecomment-753681785

### Example
testament can silently ignore `matrix` spec
tests/foo/tbar.nim:
```nim
discard """
  matrix:"--nonexistant"
"""
echo "ok1"
```

### Current Output
`XDG_CONFIG_HOME= nim r testament/testament.nim pcat foo`
test passes, and matrix flag is ignored (because test is megatest-joined)
JOINED: tests/foo/tbar.nim c

and that test would be run without matrix flags in megatest

### Expected Output
fails

### Additional Information
1.5.1 a0134671eeed3cfac1e9035568cbdec41825da8d

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #16576
* (EDIT) fix https://github.com/nim-lang/Nim/issues/16340
* fix Bug 6 from https://github.com/nim-lang/Nim/issues/16521
* workaround https://github.com/timotheecour/Nim/issues/510: added almostEqual for i386 + -d:danger

### CODE REVIEW

File: testament/categories.nim [hunk 1]
```diff
@@ -656,7 +660,7 @@ proc runJoinedTest(r: var TResults, cat: Category, testsDir: string) =
   writeFile(megatestFile, megatest)
 
   let root = getCurrentDir()
-  let args = ["c", "--nimCache:" & outDir, "-d:testing", "--listCmd", "--path:" & root, megatestFile]
+  let args = ["c", "--nimCache:" & outDir, "-d:testing", "-d:nimMegatest", "--listCmd", "--path:" & root, megatestFile]
```
Comment (ringabout) [inline testament/categories.nim:663]: So joinable tests will have `nimMegatest` defined?
Please add docs for it.

**Review by ringabout — APPROVED** [review]

File: testament/categories.nim (hunk 1 above)
Comment (timotheecour) [reply testament/categories.nim:663]: it's only meant for testing correctness of logic of whether a test is joined, but sure, tracking this here https://github.com/timotheecour/Nim/issues/64#issuecomment-754156624
