### PR TITLE
fixes #23923; type-aliased seq[T] get different backend C/C++ pointer type names causing invalid codegen

### LINKED ISSUE #23923: type-aliased `seq[T]` get different backend C/C++ pointer type names causing invalid codegen on gcc-14 | g++ | clang++
### Description

```Nim
type
  Uid* = cuint
  Gid* = cuint

proc usrToUid*(usr: string): Uid = 999.Uid

proc usrToUid*(usrs: seq[string]): seq[Uid] =
  for usr in usrs: result.add usrToUid(usr)

proc grpToGid*(grp: string): Gid = 999.Gid

proc grpToGid*(grps: seq[string]): seq[Gid] =
  for grp in grps: result.add grpToGid(grp)

if grpToGid(@["hi"]) != @[999.Gid]: quit 1
```

### Nim Version

nim-devel HEAD from yesterday
```
Nim Compiler Version 2.1.9 [Linux: amd64]
Compiled at 2024-08-03
Copyright (c) 2006-2024 by Andreas Rumpf

active boot switches: -d:release -d:danger -d:nimUseLinenoise
```

### Current Output

The example program fails under `nim cpp --cc=gcc` or `nim cpp --cc=clang` with any backend versions and with `nim c --cc=gcc typeAliasSeq.nim` under gcc-14 (without `--passC=-Wno-error=incompatible-pointer-types` - it works with that).  The error message is roughly the same in all 3 failure cases:

```text
CC: typeAliasSeq.nim
/u/cb/.cache/nim/typeAliasSeq_d/@mtypeAliasSeq.nim.c: In function 'grpToGid__type65lias83eq_u58':
/u/cb/.cache/nim/typeAliasSeq_d/@mtypeAliasSeq.nim.c:151:58: error: passing argument 1 of 'add__type65lias83eq_u30' from incompatible pointer type [-Wincompatible-pointer-types]
  151 |                                 add__type65lias83eq_u30((&result), ((unsigned int) (T5_)));
      |                                                         ~^~~~~~~~
      |                                                          |
      |                                                          tySequence__t9cg37mqWifZWh9b3z1fs0Og *
/u/cb/.cache/nim/typeAliasSeq_d/@mtypeAliasSeq.nim.c:67:93: note: expected 'tySequence__MOLaeFb9cv3vR6ovvXz0FCA *' but argument is of type 'tySequence__t9cg37mqWifZWh9b3z1fs0Og *'
   67 | N_LIB_PRIVATE N_NIMCALL(void, add__type65lias83eq_u30)(tySequence__MOLaeFb9cv3vR6ovvXz0FCA* x_p0, unsigned int y_p1);
      |                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```

### Expected Output

Should compile and run without errors.  It does so with `nim c --cc=clang`, or with early gcc versions and --cc=gcc, but does NOT with `nim cpp -cc=clang` or later gcc versions.

### Possible Solution

Commenting out the `Uid` type and its two procs makes the problem go away.  This is admittedly more of a "hint" to the solution and relates to my issue title than an actual solution.

### Additional Information

The problem *also* goes away if `cuint` is changed to simply `int` (or `int8` or etc. magic int types).  So, AFAICT, the problem may only apply to `importc` types, but it may also be more broad like generic types, etc.  Worth making a test that tries several things before concluding that it's solved.

### PR DESCRIPTION
**Pull request by ringabout**
… type names causing invalid codegen

fixes #23923

### CODE REVIEW

File: compiler/ccgcalls.nim [hunk 1]
```diff
@@ -355,7 +355,7 @@ proc genArg(p: BProc, n: PNode, param: PSym; call: PNode; result: var Rope; need
     a = initLocExprSingleUse(p, n)
     if param.typ.kind in abstractPtrs:
```
Comment (ringabout) [inline compiler/ccgcalls.nim]:
```suggestion
    if param.typ.kind in {tyVar, tyPtr, tyRef, tySink}:
```

**Comment by c-blake** [comment]
FWIW, a Nim compiler built with this PR fixes the gcc-14 problem for me on the C backend only, but NOT `nim cpp` with either `gcc` or `clang` backends.  I only use the C backend, really, so I am ok after this PR, but I believe the C++ pointer pickiness is really ancient.

So, this is perhaps a really old bug and we might want to make that sample program in the linked issue into a compiler test suite program.  Tagging @jmgomez since IIRC he's done a lot of cpp backend work.  For specificity, the errors for the cpp backends on that same sample program look like (for `--cc=gcc`):

```
/u/cb/.cache/nim/j_d/@mj.nim.cpp: In function 'tySequence__Y8bhhYcI3oRmrS9coBCebzQ grpToGid__j_u58(tySequence__sM4lkSb7zS6F7OVMvW9cffQ)':
/u/cb/.cache/nim/j_d/@mj.nim.cpp:136:45: error: invalid initialization of reference of type 'tySequence__9azowa9bJVXNR2NVFGyX1pFg&' from expression of type 'tySequence__Y8bhhYcI3oRmrS9coBCebzQ'
  136 |                                 add__j_u30((*(&result)), ((unsigned int) (T5_)));
      |                                            ~^~~~~~~~~~~
/u/cb/.cache/nim/j_d/@mj.nim.cpp:67:81: note: in passing argument 1 of 'void add__j_u30(tySequence__9azowa9bJVXNR2NVFGyX1pFg&, unsigned int)'
   67 | ALL(void, add__j_u30)(tySequence__9azowa9bJVXNR2NVFGyX1pFg& x_p0, unsigned int y_p1);
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```

and for `--cc=clang`:

```
/u/cb/.cache/nim/j_d/@mj.nim.cpp:136:5: error: no matching
      function for call to 'add__j_u30'
  136 |                                 add__j_u30((*(&result)), ((unsigned int...
      |                                 ^~~~~~~~~~
/u/cb/.cache/nim/j_d/@mj.nim.cpp:67:31: note: candidate
      function not viable: no known conversion from
      'tySequence__Y8bhhYcI3oRmrS9coBCebzQ' to
      'tySequence__9azowa9bJVXNR2NVFGyX1pFg &' for 1st argument
   67 |   ...N_NIMCALL(void, add__j_u30)(tySequence__9azowa9bJVXNR2NVFGyX1pFg& x_p0, ...
      |                      ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/nim/lib/nimbase.h:252:44: note: expanded from
      macro 'N_NIMCALL'
  252 | #  define N_NIMCALL(rettype, name) rettype name /* no modifier */
      |                                            ^
1 error generated.

**Comment by c-blake** [comment]
As noted [here](https://github.com/nim-lang/Nim/issues/23923#issuecomment-2277155927), this seems to be a regression.  So, you should probably add that test program to the PR.
