### PR TITLE
Fix VM's sametype impl to work for generics/typedescs

### LINKED ISSUE #19072: `sameType` on two uninstantiated generic parameter yields `true`
### Example
```nim
import macros

macro inspectAux(x: typed) =
  let typ = getType(x)[1]
  echo treeRepr typ
  echo treeRepr typ[1]
  echo treeRepr typ[2]
  echo "are the same: ", sameType(typ[1], typ[2])

template inspect(x: untyped): untyped =
  # Temporary needed since `A | B` is invalid somehow when passed to a typed
  # parameter.
  type tmp = x
  inspectAux(tmp)

  # Yield a type to keep the compiler happy
  int

func isNil*[A, B](u: inspect(A | B)): bool = false
```

### Current Output
```
BracketExpr
  Sym "or"
  Sym "A"
  Sym "B"
Sym "A"
Sym "B"
are the same: true
```

### Expected Output
```
BracketExpr
  Sym "or"
  Sym "A"
  Sym "B"
Sym "A"
Sym "B"
are the same: false
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2021-10-26
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 582468da1cc266d0dd922ec5c620713bbc45d02a
active boot switches: -d:release -d:nimUseLinenoise
```

### PR DESCRIPTION
**Pull request by beef331**
Should close the following: https://github.com/nim-lang/Nim/issues/19072 https://github.com/nim-lang/Nim/issues/14021

### CODE REVIEW

File: compiler/vm.nim [hunk 1]
```diff
@@ -1044,7 +1044,12 @@ proc rawExecute(c: PCtx, start: int, tos: PStackFrame): TFullReg =
                                      strictSymEquality=true))
     of opcSameNodeType:
       decodeBC(rkInt)
-      regs[ra].intVal = ord(regs[rb].node.typ.sameTypeOrNil regs[rc].node.typ)
+      let
+        aTyp = regs[rb].node.typ.skipTypes({tyGenericInst, tyAlias})
+        bTyp = regs[rc].node.typ.skipTypes({tyGenericInst, tyAlias})
+      regs[ra].intVal = ord(aTyp.sameTypeOrNil(bTyp, {ExactTypeDescValues, ExactGenericParams}))
+      # The types should exactly match which is why we pass `{ExactTypeDescValues..ExactGcSafety}`.
+      # This solves checks with generics.
```
Comment (Araq) [inline compiler/vm.nim]: Please move this into a helper proc and document why `sameTypeOrNil` cannot skip these itself.
