### PR TITLE
close #7875 add testcase

### LINKED ISSUE #7875: using a symbol for generic argument doesn't work
This really should compile.

```nim
import macros

type
  MyType[T] = object

# this is totally fine
var mysym: MyType[float32]

macro foobar(): untyped =
  let floatSym = bindSym"float32"

  result = quote do:
    var mysym: MyType[`floatSym`]

  echo result.repr # var mysym117054: MyType[float32]

foobar()
```
error message:
```
cannot instantiate MyType
got: <float32>
but expected: <T>
```

I am generating type expressions in a macro and I get symbols via "getTypeInst". When I use these type symbols in a macro like above, I get the exact same error message.

### PR DESCRIPTION
**Pull request by ringabout**
close #7875 add testcase

### CODE REVIEW

File: tests/macros/t7875.nim [hunk 1]
```diff
@@ -0,0 +1,22 @@
+discard """
+  nimout: "var mysym`gensym0: MyType[float32]"
+  joinable: false
```
Comment (timotheecour) [inline tests/macros/t7875.nim:3]: nit: why joinable false? this could be moved to a block in tmacros.nim (and with
```nim
doAssert result.repr == "var mysym`gensym0: MyType[float32]"
```
