### PR TITLE
fixes #19291; implements `wasMoved` hook

### LINKED ISSUE #19291: =sink .error is not respected
### Example
I have marked both `=sink` and `=copy` with ` .error` but only the last one is respected, the following example compiles and crashes.
https://play.nim-lang.org/#ix=3JHb

### Current Output

```
hello
/usercode/in.nim(29)     in
/usercode/in.nim(10)     main
/usercode/in.nim(11)     =destroy
/playground/nim/lib/system/assertions.nim(38) failedAssertImpl
/playground/nim/lib/system/assertions.nim(28) raiseAssert
/playground/nim/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: /usercode/in.nim(11, 10) `ready` Window is already opened [AssertionDefect]
```
### Additional information

Compiling with v1.0.10 shows the message:

```
/usercode/in.nim(24, 19) Error: '=sink' is not available for type <Game>; routine: main
```

### Expected Output

Compile time error.

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2021-12-24
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: fa96e56ad06f0562b5d608cc896a9b17c9512958
active boot switches: -d:release --gc:markAndSweep
```

### PR DESCRIPTION
**Pull request by ringabout**
fixes #19291
ref https://forum.nim-lang.org/t/9694

### CODE REVIEW

**Comment by ringabout** [comment]
Working on it today...

**Comment by ringabout** [comment]
There is a problem left. I don't mess with object variants for now.

File: tests/destructor/tv2_cast.nim [hunk 1]
```diff
@@ -77,7 +78,7 @@ data =
 `=destroy`(:tmpD_2)
 `=destroy`(:tmpD_1)
 `=destroy_1`(data)
--- end of expandArc ------------------------'''
+'''
```
Comment (ringabout) [inline tests/destructor/tv2_cast.nim:82]:
```suggestion
-- end of expandArc ------------------------'''
'''
```

File: tests/destructor/tv2_cast.nim [hunk 2]
```diff
@@ -78,6 +79,7 @@ data =
 `=destroy`(:tmpD_1)
 `=destroy_1`(data)
 -- end of expandArc ------------------------'''
```
Comment (ringabout) [inline tests/destructor/tv2_cast.nim]:
```suggestion
-- end of expandArc ------------------------
```

File: tests/arc/topt_refcursors.nim [hunk 3]
```diff
@@ -22,12 +23,12 @@ try:
...
         echo [jt.s]
         `=sink`(jt, ri_1)
-        wasMoved(ri_1)
+        `=wasMoved`(ri_1)
       finally:
         `=destroy`(ri_1)
 finally:
   `=destroy`(jt)
--- end of expandArc ------------------------'''
+'''
```
Comment (ringabout) [inline tests/arc/topt_refcursors.nim:32]:
```suggestion
-- end of expandArc ------------------------
'''
```
