### PR TITLE
StringStream & more stdlib modules support for JS/NimScript

### LINKED ISSUE #4247: Make pegs module compatible with javascript backend
It would be nice to have a regex-like library working consistently across targets. Pegs seems to be the best candidate, since it is pure.

Right now there are two problems I see:
1. `transformFile` uses `readFile`, which is missing in JS. Easily solved by wrapping the whole proc in `when`.
2. After that the module compiles, but fails for even the most basic cases. E.g. this throws an exception:

``` nim
import pegs

assert "x".match(peg"x")
```

### LINKED ISSUE #11066: Trying to use newStringStream results in 'undeclared identifier'
I am not able to use the newStringStream() function from streams module (stdlib), whether by itself or as part of the marshal library.

### Example
```nim
import streams
var test = newStringStream("")
echo test

```

### Current Output
```
Error: undeclared identifier: 'newStringStream'
```

### Expected Output
 It should just work, especially where marshal module is concerned.

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.4
```

### LINKED ISSUE #12417: Enable `StringStream` for JS
Currently `StringStream` from `streams` module is not defined on JS backend. It would be useful to enable to it be able to use libraries that depend on it.

### PR DESCRIPTION
**Pull request by metagn**
Closes #12417, closes #11066, closes #4247 

`streams.StringStream` now compiles for JavaScript, the implementation was already there it was only enabled for compile time for some reason (though it only implemented readDataStr and not read/peek/writeData). StringStreams in JS have the limitation that any buffer `pointer`s used are cast to `ptr string` for the lack of a better option (except maybe a conditional `var openarray[char]` parameter but that would be very ugly), any pointer incompatible with `ptr string` will not work. JS now compiles `parsecsv`, `parsecfg`, `parsesql`, `xmlparser`, `htmlparser`, `ropes` and there is new support for `cstrutils`.

`typeinfo` was broken on JS because of commit https://github.com/nim-lang/Nim/commit/ca4b971bc81b2e751e0388d80896fde7079b1679#diff-f3396a3284b9ca3e52aff3aeef171a09, `jssys` only imported `system/indexerrors` whereas it was included in system on C/C++. It is included now in `jssys`.

`lexbase` and `streams` now compile on NimScript, they would have worked before but they just didn't compile correctly. NimScript now compiles: `parsecsv`, `parsecfg`, `parsesql`, `xmlparser`, `htmlparser`, `ropes`, `json`, `parsejson`, `strtabs`

`unidecode` has never not worked in NimScript, both in compiling and the module being functional, but it was specifically mentioned in the NimScript docs that it didn't, so I added it to the changelog.

`marshal` now mentions JS and NimScript instead of just the new runtime when it's imported on the wrong backend. #11066 mentions `marshal` in JS, but should be closed since it's specifically talking about newStringStream. There is another issue, #5667, about the pointer-to-int cast in marshal in JS, but this is irrelevant, marshal imports typeinfo which doesn't compile on JS.

### CODE REVIEW

File: lib/pure/streams.nim [hunk 1]
```diff
@@ -241,19 +244,29 @@ proc readDataStr*(s: Stream, buffer: var string, slice: Slice[int]): int =
     # fallback
     result = s.readData(addr buffer[0], buffer.len)
 
-when not defined(js):
+template jsOrVm(caseJsOrVm, caseElse: untyped): untyped =
+  when nimvm:
+    block:
```
Comment (timotheecour) [inline lib/pure/streams.nim:249]: why block? it can change semantics (other branches below don't have it)

File: lib/pure/streams.nim [hunk 2]
```diff
@@ -241,19 +244,29 @@ proc readDataStr*(s: Stream, buffer: var string, slice: Slice[int]): int =
...
+      caseJsOrVm
+  else:
```
Comment (timotheecour) [inline lib/pure/streams.nim:251]: elif defined

File: lib/pure/streams.nim [hunk 3]
```diff
@@ -241,19 +244,29 @@ proc readDataStr*(s: Stream, buffer: var string, slice: Slice[int]): int =
...
+      caseJsOrVm
+    else:
+      caseElse
+
+when (NimMajor, NimMinor) >= (1, 3) or not defined(js):
   proc readAll*(s: Stream): string =
     ## Reads all available data.
     ##
-    ## **Note:** Not available for JS backend.
+    ## Available for JS backend since 1.3.
```
Comment (timotheecour) [inline lib/pure/streams.nim]: that's implied by `when (NimMajor, NimMinor) >= (1, 3) or not defined(js):`, I'd skip this line

File: lib/pure/streams.nim (hunk 2 above)
Comment (SolitudeSF) [reply lib/pure/streams.nim:251]: you cant use expressions or elif branch with `when nimvm`

**Comment by timotheecour** [comment]
- [ ] NimPatch is underused. We should start using it, eg: I'd replace `when (NimMajor, NimMinor) >= (1, 3)` by `when (NimMajor, NimMinor, NimPatch) >= (1, 3, 2)` (and increment `system.NimPatch` to 2)

reason: it allows writing portable code in between releases even if switching branches/versions/commits. 
So that I can have in my user config.nims (or just user code) conditionals like `when (NimMajor, NimMinor, NimPatch) >= (1, 3, 2): dosmthg_with_js_ StringStream else: workaround` and it'll work regardless which commit I'm on

File: tests/js/tstreams.nim [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+var s = newStringStream("I\nAM\nGROOT")
+echo s.peekStr(1)
+for line in s.lines:
+  echo line
+s.close
+
+var s2 = newStringStream("abc")
+echo s2.readAll
+s2.write("def")
+echo s2.data
```
Comment (timotheecour) [inline tests/js/tstreams.nim]: prefer assert instead of echo, eg: `doAssert s2.data == "abcdef"`

File: lib/pure/streams.nim (hunk 1 above)
Comment (metagn) [reply lib/pure/streams.nim:249]: Because you can't do this:

```nim
when nimvm:
  var foo = 3
else:
  var foo = 4 # redefinition
```

If you remove the `block` and do the following:

```nim
jsOrVm:
  var foo = 3
do:
  var bar = 4
```

This expands to:

```nim
when nimvm:
  var foo = 3
else:
  when defined(js):
    var foo = 3
  else:
    var bar = 4
```

So if JS is defined, you get a redefinition error.

File: lib/pure/streams.nim [hunk 5]
```diff
@@ -241,19 +244,29 @@ proc readDataStr*(s: Stream, buffer: var string, slice: Slice[int]): int =
     # fallback
     result = s.readData(addr buffer[0], buffer.len)
 
-when not defined(js):
+template jsOrVm(caseJsOrVm, caseElse: untyped): untyped =
+  when nimvm:
+    block:
+      caseJsOrVm
+  else:
+    when defined(js):
```
Comment (ghost) [inline lib/pure/streams.nim]:
```suggestion
    when defined(js) or defined(nimscript):
```
IIRC `when nimvm` is not defined for nimscript.

Comment (timotheecour) [reply lib/pure/streams.nim]: not true:
```nim
proc fun() =
  when nimvm:
    echo "ok1"
  else:
    echo "ok2"
static: fun()
fun()
```
prints:
ok1
ok1

as expected

File: lib/pure/streams.nim (hunk 1 above)
Comment (timotheecour) [reply lib/pure/streams.nim:249]: my point remains; you're changing semantics, so you're increasing risk of code that works with js+c and works differently with nimvm (say, after someone else re-uses your template)

there is no real restriction with my edit since `when nimvm` can't be used for introducing variables used after the block, see https://nim-lang.github.io/Nim/manual.html#statements-and-expressions-when-nimvm-statement

> Code in branches must not affect semantics of the code that follows the when nimvm statement. E.g. it must not define symbols that are used in the following code.

Comment (metagn) [reply lib/pure/streams.nim:249]: What should I do here then? Put the `else` branch in a `block` too and change the name to `jsOrVmLocal`?

Comment (timotheecour) [reply lib/pure/streams.nim:249]: yes, rename to jsOrVmBlock:
```nim
template jsOrVmBlock(caseJsOrVm, caseElse: untyped): untyped =
  when nimvm:
    block: caseJsOrVm
  else:
    block:
      when defined(js): caseJsOrVm
      else: caseElse
```
it's hard for me to test because `nim js -r tests/js/tstreams.nim` fails for me regardless of this change [1] but at least it compiles with this change.

[1]
`nim js -r tests/js/tstreams.nim`
```
/Users/timothee/git_clone/nim/Nim_temp3/tests/js/tstreams.js:692
    throw new Error(cbuf_3715201);
    ^

Error: Error: unhandled exception: index 0 not in 0 .. NaN [IndexError]
Traceback (most recent call last)
streams.peekChar
streams.peekData, line: 303
streams.ssPeekData, line: 1156
[]=.[]=, line: 2463
```

but hopefully https://github.com/timotheecour/Nim/issues/124 can be fixed and we'll be able to introduce your current version of `jsOrVm`

Comment (metagn) [reply lib/pure/streams.nim:249]: I made this change already but named  `jsOrVmLocal`, will rename to `jsOrVmBlock` next commit, marking as resolved

File: changelog.md [hunk 6]
```diff
@@ -36,6 +36,11 @@
   and this can now throw in edge cases where `getCurrentDir` throws.
   `relativePath` also now works for js with `-d:nodejs`.
 
+- `streams.StringStream` is now supported in JS, with the limitation that any
+  buffer `pointer`s used must semantically be `ptr string`, any pointer
+  incompatible with `ptr string` will not work. This should allow the following
+  standard library modules to compile on JS: `parsecsv`, `parsecfg`, `parsesql`,
```
Comment (timotheecour) [inline changelog.md]: this definitely needs a test; create a new
`tests/js/tstdlib_imports.nim` that imports every module supported by js
analog to `tests/test_nimscript.nims` for js instead of nimscript, eg:

```nim
import strutils
import parsecsv
import parsecfg
...
```
if you feel like it, add every js module for which this works, if not, at least all the modules you've now enabled to work with it and add a `# xxx add other modules`

**Comment by timotheecour** [comment]
- [ ] maybe out of scope for this PR but could `newFileStream` be supported for -d:js -d:nodejs ?

**Comment by hlaaftana** [comment]
I implemented read/peek integer/bool procs for JS (in big endian, since that's what JS uses. if there's some kind of routine in the standard library that removes the `shl` boilerplate I'll switch to that) but there is no way to write those integers, since generic `write` doesn't work and there are no `writeInt8` procs. Also I didn't implement it for floats because that would need `ArrayBuffer` and that should be in its own library.

I could overload `write` for integers too but that would be way too much code and, again, ArrayBuffer is a better solution. I want to revert these changes and just say reading/peeking integers and bool doesn't work for JS, but it's not hard to do so it's there.

This PR is a bit unfair to VM, because VM `pointer` casting is very limited but JS can cast to `ptr string` just fine, so I want to introduce a new `BufferPointer` type that's `ptr string` in JS and VM and `pointer` otherwise, and use it in the Stream procs. This would allow `write` and `peek` for VM. I could also just revert `write` and `peek` for JS, all the stdlib parser modules and `lexbase` does is use `readDataStr`, reverting the `ptr string` crap would make things a lot less complex.

I don't have strong opinions either way. There should definitely be an `ArrayBuffer` lib outside this, and defining `FileStream` might be possible in JS if `defined(nodejs)` and the standard library actually uses FileStream, except again, not with `peek`/`write`.

File: tests/js/tstreams.nim [hunk 7]
```diff
@@ -0,0 +1,21 @@
+discard """
+  output: '''I
```
Comment (timotheecour) [inline tests/js/tstreams.nim]: ignorable nit:
this works too and is more readable:
```
output:'''
I
AM
...
```

File: tests/js/tstdlib_imports.nim [hunk 8]
```diff
@@ -64,4 +64,7 @@ import
   # works but shouldn't: segfaults
 
   # Modules for JS backend:
-  asyncjs, dom, jsconsole, jscore, jsffi
\ No newline at end of file
+  asyncjs, dom, jsconsole, jscore, jsffi
+
+  # Unlisted in lib.html:
+  std/[decls, compilesettings, with, wrapnils]
```
Comment (timotheecour) [inline tests/js/tstdlib_imports.nim]: excellent! 

but: this gives error; you can use this: https://gist.github.com/timotheecour/058320de3093737967b82d57d95ff09c

which has a single `std/[` at top-level, i feel it's cleaner

Comment (metagn) [reply tests/js/tstdlib_imports.nim]: Weirdly, you cannot `import std/unidecode`

Edit: Didn't notice that was in your gist already

File: tests/js/tstdlib_imports.nim [hunk 9]
```diff
@@ -64,4 +64,7 @@ import
   # works but shouldn't: segfaults
```
Comment (timotheecour) [inline tests/js/tstdlib_imports.nim:65]: maybe a TODO for future PR so feel free to ignore but I feel the best here would be a glob approach, similar to what I did in https://github.com/nim-lang/Nim/pull/13221 ; this could work  by adding a test inside tests/trunner.nim (`fmt"{nim} js -r {autogenerated}"`) that would populate the list of all modules (via glob), and use a blacklist for things that don't work (instead of what you're doing which is a whitelist).

The point of a blacklist (instead of whitelist) is to keep working even if modules are added, removed, or moved. 

Note that the same code could be reused (with a different blacklist exclusion) for other targets and/or compiler options, eg `nimscript`, `--gc:arg` etc

EDIT: i'll do that in a followup PR => https://github.com/timotheecour/Nim/issues/98#issuecomment-619315201

Comment (metagn) [reply tests/js/tstdlib_imports.nim:65]: To add onto this: I was thinking modules that do not support JS would `include "jsincompatible"` or whatever similar to `include "system/inclrtl"` which would error on JS with an error message. The tester could check for that specific error message, fail if a module not in the blacklist gives it, fail if a module in the blacklist doesn't give it.

**Comment by metagn** [comment]
Some notes:

It's possible to only support `readDataStr` for JS just like the VM before the PR. This will make the PR smaller but I don't think it's worth it. The standard library is slightly affected by this change: `unittest` uses `writeLine(Stream, string)` for "JUnitOutputFormatter" and `ropes` uses `write(Stream, string)` only in its own proc `write(Stream, Rope)` which could just be undeclared for JS. Nothing is using `peek`.

I can either implement `write` overloads for integers and bools just like `read`/`peek` or revert the overloads for `read`/`peek` and undeclare them, telling people to make an ArrayBuffer library.

Streams would have benefited from a kind of `type StreamOp = enum read, write, peek` then you only define 1 closure in the stream field that takes it as an argument. This way we could add `peekDataStr`/`writeDataStr` all to 1 proc too.

Supporting `FileStream` for nodejs would be hard, you'd have to make the programmer call `require("fs")` themselves, and I don't think the standard library has ever used nodejs features locked behind `require`.

File: lib/pure/streams.nim (hunk 5 above)
Comment (metagn) [reply lib/pure/streams.nim]: This was a correct change, `moveMem`/`copyMem` are undeclared in NimScript but not in compile time VM, which made it semantically check `caseElse` and fail

**Comment by timotheecour** [comment]
IMO we should pick whatever solution will maximize the amount of code that works on all backends c,vm,js (with same semantics) and code reuse (as few backend-specific tweaks as possible).

* vm backend can almost always reuse code already written for c backend thanks to vmops; the wrapping logic is getting simpler (see compiler/vmconv.nim) and can be 100% automated via a macro if needed
* ideally, the branching (eg `when nimvm: vmcode else: rtcode`) should happen preferably at the lower levels (eg `copyMem`), to maximize code reuse and avoid rewriting lots of high-level logic for different backends

> Supporting FileStream for nodejs would be hard, you'd have to make the programmer call require("fs") themselves, 

seems like a totally reasonable requirement, we shouldn't restrict to the minimal common features amongst -d:nimbrowser and -d:nodejs. we can simply add a runtime check if needed, eg `doAssert(check_fs_available, "need to require('fs')")` or (in future work) automatically insert select `require(X)` statements in jsgen'd code upon 1st use of a symbol that requires it, for -d:nodejs code).

> and I don't think the standard library has ever used nodejs features locked behind require.

in https://github.com/nim-lang/Nim/pull/13451 I've added nodejs support for `getCurrentDir`, via ```{.emit: "`ret` = process.cwd();".}```, so that   `import os;echo getCurrentDir()` works with `nim js -r -d:nodejs main`; it's tested in CI, see tests/js/tos.nim


## CT failure vs RT failure
This is a subtle point: failing at runtime (eg missing requirements) instead of disable code at CT will simplify a lot of code (less backend-specific branching, more availability across backends), because the runtime failure happens in only a few key places, whereas disabling code at CT is "viral" and affects all the callers, regardless whether runtime code will actually use that feature, eg:

I want this code to work with `nim js -r main`.
when `someRuntimeCondition()` will be true (at runtime), it'll raise an assert failure unless you're in nodejs and `require('fs')` made fs available.
when `someRuntimeCondition()` will be false (at runtime), it'll just work.
```nim
var cond = someRuntimeCondition()
if cond: 
  var s = newFileStream("foo.txt")
  fun(s)
else:
  var s = newStringStream("bar")
  fun(s)
```

This in turns make code that calls this work without being disabled at compile time just because some not-taken-branch would fail.


> I can either implement write overloads for integers and bools

i don't understand; `var s2 = newStringStream("abc"); s2.write (12, true)` already works (as of your PR)

> Streams would have benefited from a kind of type StreamOp = enum read, write, peek then you only define 1 closure in the stream field that takes it as an argument. This way we could add peekDataStr/writeDataStr all to 1 proc too.

that makes sense to me (as long as it doesn't break code?)

**Comment by metagn** [comment]
> i don't understand; var s2 = newStringStream("abc"); s2.write (12, true) already works (as of your PR)

I'm talking about the generic `write[T]` which I disabled. This uses `unsafeAddr` and uses the bit representation of the value, with this PR it will instead use the `write(varargs[$, string])` proc.

> we shouldn't restrict to the minimal common features amongst -d:nimbrowser and -d:nodejs

That makes sense. You were right about it being out of scope though I'm not going to implement it in this PR, I don't have many good ideas on it.

> that makes sense to me (as long as it doesn't break code?)

It would, I'm just complaining that it doesn't exist already.

I've rolled back the integer/bool overloads, a library that performs string -> ArrayBuffer -> integer would be much more elegant.

**Comment by timotheecour** [comment]
* some more info: `npm i builtin-modules; node -e "console.log(require('builtin-modules'))"` shows `fs` (+ many other modules), so it's a builtin, and we can just assume it's there.
* > not going to implement it in this PR

oh ya, I'm not suggesting implementing it in this PR, I'm just saying to simply remove `when not defined(js):` right above `type FileStream* = ref FileStreamObj`, so that `nim js -r main` works below:
```nim
import streams
var cond = someRuntimeCondition()
if cond: echo newFileStream("foo.txt").readAll # fails at RT if goes here, and in future will work for -d:nodejs
else: echo newStringStream("bar").readAll # works if goes here
```
I tried that modification from your PR and it did work; when changing runtime condition to false, it gives an easy-to-understand errmsg:
```
ReferenceError: fopen is not defined
    at open_13745829 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10618.js:636:22)
    at new_file_stream_14050087 (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10618.js:1089:9)
    at Object.<anonymous> (/Users/timothee/git_clone/nim/timn/tests/nim/all/t10618.js:1554:19)
```

benefit: no "viral" propagation of CT disabled code, so that more code works so long it's not attempting to open a newFileStream, which is unlikely to occur by accident; less backend-specific branching via `when defined js: foo else: bar`

> with this PR it will instead use the write(varargs[$, string]) 

I see; yes, `write(varargs[$, string]) ` is the correct approach for js indeed

**Comment by metagn** [comment]
Oh, that's good about fs.

> simply remove when not defined(js): right above type FileStream* = ref FileStreamObj

If I understand correctly then I should reenable `write`/`read`/`peek`, do I throw a ValueError before they do anything? Because runtime errors in this case are not going to be informative. Maybe catch any errors the procs throw in `ssWhateverData` then rethrow them with an extra message? That would also be bad, JS could just never error on a wrong input.

Also, do I change the version checks or can that be done by someone else after the merge?

**Comment by timotheecour** [comment]
> If I understand correctly then I should reenable write/read/peek, do I throw a ValueError before they do anything?

sorry which one for example? like `proc fsPeekData(s: Stream, buffer: pointer, bufLen: int): int =` ?
I don't think that's an issue, because calling `newFileStream` will fail right here on `open` (see my stacktrace above), so it won't ever call `fsPeekData` IIUC.
=> single point of failure.
and you can even provide a good errmsg like this:
```nim
# in newFileStream:
when defined(js):
  # TODO for future work: support nodejs via `fs` builtin module
  doAssert false, "js not yet supported; context: " & filename
else:
  var f: File
  if open(f, filename, mode, bufSize): result = newFileStream(f)
```

> Also, do I change the version checks or can that be done by someone else after the merge?

sorry, I need more context to understand (3am here..)

**Comment by metagn** [comment]
Sorry for keeping you up. I meant StringStream procs, if they get a pointer that isn't `ptr string` they will fail terribly. Specifically `write` uses `unsafeAddr` which is bad on JS (#14100). I'm saying there's 2 options: if `write` or `read` is called for Stream on JS, it throws a ValueError; or when it dereferences it inside the StringStream procs like `ssReadData`, then any error will be caught and rethrown like

```nim
try:
  cast[ptr string](buffer)[][0..<result] = s.data[s.pos..<s.pos+result]
except:
  raise newException(ValueError, "reading to buffer pointer failed, did you use a non-string pointer?", getCurrentException())
```

For context about the versioning:

> NimPatch is underused. We should start using it, eg: I'd replace when (NimMajor, NimMinor) >= (1, 3) by when (NimMajor, NimMinor, NimPatch) >= (1, 3, 2) (and increment system.NimPatch to 2)

Should I do any one of these things (replace with >= (1, 3, 2) or increment version) or can they be done after the PR?

**Comment by timotheecour** [comment]
> Should I do any one of these things (replace with >= (1, 3, 2) or increment version) or can they be done after the PR?

leave it like you did for now, we can always change later if ppl agree

**Comment by timotheecour** [comment]
> I meant StringStream procs, if they get a pointer that isn't ptr string they will fail terribly.

sorry can you give me a simple complete example I can run on top of your PR to see what you mean exactly? (ideally one where calling stream apis would end up with a pointer that is a ptr string, and one where it won't)

because right now this works in your pr:
```nim
when true:
  import streams
  var s2 = newStringStream("abc")
  doAssert s2.readAll == "abc"
  s2.write("def")
```

**Comment by metagn** [comment]
```nim
import streams

var s = newStringStream("abcd")
var i: int
discard s.readData(addr i, sizeof i) # this is what read[T](Stream, var T) does
echo i
```

You get `Error: unhandled exception: index 0 not in 0 .. NaN [IndexError]`, meaning Nim tried to subscript a null/undefined value.

**Comment by Araq** [comment]
I cannot merge this, you used ``[ci skip]`` in the very last commit.

**Comment by timotheecour** [comment]
sadly, `[ci skip]` is broken on azure, see https://github.com/microsoft/azure-pipelines-agent/issues/2944

**Comment by metagn** [comment]
It's ok, #14099 had to get merged first anyway

**Comment by timotheecour** [comment]
@hlaaftana i have some more feedback, please hold on before any merge :)
also, i may have a solution for https://github.com/nim-lang/Nim/pull/14095#issuecomment-619359068 (will update here soon today)

also, can you please rebase + force push instead of merge? otherwise really hard to follow your commits ; that's what i do in all my PR's ; any conflicts are almost always easy to fix and when they're not i squash what needs to be squashed before rebase

(assuming you already know all this stuff but just in case:
even if you've already merged, it's easy to go back and do a rebase:
use `git reflog`, find the hash right before the merge, and `git pull --rebase origin devel` from there, the `git push --force` on your branch)

**Comment by timotheecour** [comment]
- [ ] ok see https://github.com/nim-lang/Nim/pull/14128, it shows that we can support generic read[T] for streams with nim js (eg, for integer types). Right now it builds on top of your PR just for demoing it works, but I'll reduce it to just the new module `jsarrays`, which you'll then be able to import in your PR so that streams works without restriction in nim js.

- [ ] the other feedback I had was related to cstrutils.nim; right now you're re-imlementing a lot of things in the js backend, but I think we can avoid that and maximize code reuse between c and js with just a few primitives that would differ between backends; will provide more details tmrw

**Comment by metagn** [comment]
The new code in cstrutils is just copy pasted from strutils (can be reused right now, just `cmpIgnoreStyle($a, $b).cstring`) which I understand is problematic and didn't pay much attention to at first. Trying my best to adhere to your feedback and not make too many commits: cmpIgnoreStyle and cmpIgnoreCase now say "for JS use strutils instead", maybe strutils can have `cstring | string` arguments for JS later down the line, or maybe when `Enumerable[char]`/`Iterable[char]` is implemented.

I understand that `streams` is a mess when it comes to overspecialization but it's what had to be done to work around `pointer` limitations in JS. The main purpose of this PR anyway was to make the rest of the stdlib compatible with JS, I wasn't aiming to create a real streams library. I like the idea of `jsarrays`, but its current use in `streams` to work around `pointer` is a bit complicated and I think it'd be easier for you to work if this PR was merged first.

**Comment by metagn** [comment]
Ormin caused the test failures on azure but builds.sr.ht complains about the pegs test, most likely an unrelated CI issue. Should be good regardless

**Comment by timotheecour** [comment]
@hlaaftana 
> Ormin caused the test failures on azure but builds.sr.ht complains about the pegs test, most likely an unrelated CI issue. Should be good regardless

the failure is because you haven't rebased against devel so my fix #14134 wasn't picked up; if you `git pull --rebase origin devel` (then push --force) it works, eg rebuild nim the test passes locally:
(eg `XDG_CONFIG_HOME= nim c --lib:lib -r testament/testament --nim:bin/nim r tests/stdlib/tpegs.nim`)

**Comment by hlaaftana** [comment]
I did rebase, just builds.sr.ht didn't pick up on it.

**Comment by metagn** [comment]
Could've sworn I rebased it before. Fine now.

**Comment by metagn** [comment]
Merge?

**Comment by timotheecour** [comment]
@hlaaftana amazing job! this is 1 big step closer to the goal of making all of stdlib available for all targets
