### PR TITLE
fix #3505 wrong var {.global.} initialization, asign variable to it

### LINKED ISSUE #3505: Nim doesn't catch wrong var {.global.} initialization
Test

``` Nim
proc foo =
  let a = 0
  var b {.global.} = a # Nim should complain about this
foo()
```

Result:

``` Nim
>nim c test
[...]\nimcache\compiler_test.c:100:12: error: 'a' undeclared (first use in this f
unction)
  b_97006 = a;
            ^
Error: execution of an external program failed: [...]
```

---

``` Nim
>nim -v
Nim Compiler Version 0.12.0 (2015-10-28) [Windows: i386]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 22a702868bfd242ff76bf86ea00a278f979a112e
active boot switches: -d:release
```

### LINKED ISSUE #5132: Codegen: Faulty code with global pragma and indirect overload based initialization
Sorry for the horrible title, but I don't fully understand what went wrong.

```Nim
proc initX(it: float): int = 8

proc main() =
  var f: float
  var x {.global.} = initX(f)
  
main()
```
gives:
```
Error: execution of an external compiler program 'gcc -c  -w  -I [redacted] -o /tmp/aporia/nimcache/a7.o /tmp/aporia/nimcache/a7.c' failed with exit code: 1
/tmp/aporia/nimcache/a7.c: In function ‘NimMainModule’:
/tmp/aporia/nimcache/a7.c:110:44: error: ‘f0’ undeclared (first use in this function)
  x_98010_899815578 = initx_98003_899815578(f0);
                                            ^
/tmp/aporia/nimcache/a7.c:110:44: note: each undeclared identifier is reported only once for each function it appears in
> Process terminated with exit code 256
````
I'm using overload to control my program flow and this function generates the above error. It also give the same error if I replace the `float` by `int` too. The following variations of the main functions are fine:

W/o parameters
```nim
proc initX(): int = 8

proc main() =
  var f: float
  var x {.global.} = initX()
  
main()
```

W/o {.global.}
```nim
proc initX(it: float): int = 8

proc main() =
  var f: float
  var x = initX(f)
  
main()
````

### PR DESCRIPTION
**Pull request by bung87**
fix #3505
fix #5132

### CODE REVIEW

File: compiler/semstmts.nim [hunk 1]
```diff
@@ -740,7 +741,17 @@ proc semVarOrLet(c: PContext, n: PNode, symkind: TSymKind): PNode =
         vm.setupCompileTimeVar(c.module, c.idgen, c.graph, x)
       if v.flags * {sfGlobal, sfThread} == {sfGlobal}:
         message(c.config, v.info, hintGlobalVar)
-
+      let isGlobal = {sfGlobal, sfPure} <= v.flags
+      if isGlobal and def.kind == nkCall:
```
Comment (Araq) [inline compiler/semstmts.nim]: Right idea but move it to a helper proc and make it recursive so that e.g. `f(g(localVar))` is caught too.

**Comment by Araq** [comment]
It's a pleasure to see your understanding progress. No irony.

File: tests/global/t3505.nim [hunk 2]
```diff
@@ -0,0 +1,33 @@
+discard """
+cmd: "nim check $options --hints:off $file"
+action: "reject"
+nimout: '''
+t3505.nim(22, 22) Error: cannot asign to global variable
+t3505.nim(31, 28) Error: cannot asign to global variable
```
Comment (Araq) [inline tests/global/t3505.nim]:
```suggestion
t3505.nim(22, 22) Error: cannot assign local to global variable
t3505.nim(31, 28) Error: cannot assign local to global variable
```

File: compiler/semstmts.nim [hunk 3]
```diff
@@ -36,6 +36,7 @@ const
   errRecursiveDependencyX = "recursive dependency: '$1'"
   errRecursiveDependencyIteratorX = "recursion is not supported in iterators: '$1'"
   errPragmaOnlyInHeaderOfProcX = "pragmas are only allowed in the header of a proc; redefinition of $1"
+  errCannotAsignToGlobal = "cannot asign to global variable"
```
Comment (Araq) [inline compiler/semstmts.nim]:
```suggestion
  errCannotAssignToGlobal = "cannot assign to global variable"
```

File: compiler/semstmts.nim [hunk 4]
```diff
@@ -590,6 +591,24 @@ proc msgSymChoiceUseQualifier(c: PContext; n: PNode; note = errGenerated) =
...
+    if n[z].kind == nkSym and n[z].sym.kind in {skVar, skLet} and 
+      not ({sfGlobal, sfPure} <= n[z].sym.flags):
+      return true
+    elif n[z].kind in nkCallKinds:
+      if isUseLocalVar(n[z]):
+        return true
+
+proc globalVarInitCheck(c: PContext, s: PSym, n: PNode) =
+  if n.kind in nkCallKinds and isUseLocalVar(n):
+    localError(c.config, n.info, errCannotAsignToGlobal)
```
Comment (Araq) [inline compiler/semstmts.nim]:
```suggestion
    localError(c.config, n.info, errCannotAssignToGlobal)
```

File: compiler/semstmts.nim [hunk 5]
```diff
@@ -590,6 +591,24 @@ proc msgSymChoiceUseQualifier(c: PContext; n: PNode; note = errGenerated) =
...
+        return true
+
+proc globalVarInitCheck(c: PContext, s: PSym, n: PNode) =
+  if n.kind in nkCallKinds and isUseLocalVar(n):
+    localError(c.config, n.info, errCannotAssignToGlobal)
+  elif n.kind == nkSym and 
+      n.sym.kind in {skVar, skLet} and not 
+      ({sfGlobal, sfPure} <= n.sym.flags or
+        sfCompileTime in n.sym.flags):
+    localError(c.config, n.info, errCannotAsignToGlobal)
```
Comment (Araq) [inline compiler/semstmts.nim]:
```suggestion
    localError(c.config, n.info, errCannotAssignToGlobal)
```

**Comment by Araq** [comment]
Refactor `isUseLocalVar` to get rid of the code duplication. And name it `usesLocalVar`.

File: compiler/semstmts.nim [hunk 6]
```diff
@@ -740,7 +759,9 @@ proc semVarOrLet(c: PContext, n: PNode, symkind: TSymKind): PNode =
         vm.setupCompileTimeVar(c.module, c.idgen, c.graph, x)
       if v.flags * {sfGlobal, sfThread} == {sfGlobal}:
         message(c.config, v.info, hintGlobalVar)
-
+      let isGlobal = {sfGlobal, sfPure} <= v.flags
+      if isGlobal:
```
Comment (Araq) [inline compiler/semstmts.nim]:
```suggestion
      if {sfGlobal, sfPure} <= v.flags:
```
