### PR TITLE
 fix #14010(fix std/registry + arc)

### LINKED ISSUE #14010: .choosenim/toolchains/nim-1.2.0/lib/windows/registry.nim(58, 54) Error: expression cannot be cast to pointer
I'm attempting to set a value in the windows registry using the setUnicodeValue function. However, I heard of the --gc:arc (ARC) feature, and I wanted to use it. This resulted in the .choosenim/toolchains/nim-1.2.0/lib/windows/registry.nim(58, 54) Error: expression cannot be cast to pointer

### Example
```nim
setUnicodeValue(reg, subreg, value, key)
```

### Current Output
```
.choosenim/toolchains/nim-1.2.0/lib/windows/registry.nim(58, 54) Error: expression cannot be cast to pointer
```

### Expected Output
``` 
To set the value of the subregistry
```

### Possible Solution
Don't know

### Additional Information

* It was working without --gc:arc
* This issue is blocking my project (I want to test the project with arc, so I don't have to worry about gc stoping execution.

```
$ nim -v
Nim Compiler Version 1.2.0
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #14010

### CODE REVIEW

File: tests/stdlib/tregistry.nim [hunk 1]
```diff
@@ -0,0 +1,9 @@
+discard """
+  disabled: "unix"
```
Comment (ghost) [inline tests/stdlib/tregistry.nim:2]: Just a comment on testament rather than this PR - is there no functionality to _only_ enable test for a specific target? If there's not, then I guess that it might be a good idea to add an optional like that.

Comment (ringabout) [reply tests/stdlib/tregistry.nim:2]: make sense

Comment (timotheecour) [reply tests/stdlib/tregistry.nim:2]: until then this works:
```nim
when defined(unix):
  xxx
```
more generally, I'd rather have most of the logic in pure nim rather than in testament's spec language

Comment (ringabout) [reply tests/stdlib/tregistry.nim:2]: It still wastes some resources?

File: tests/stdlib/tregistry.nim [hunk 2]
```diff
@@ -0,0 +1,9 @@
...
+  matrix: "--gc:refc; --gc:arc"
+"""
+
+import std/registry
+
+# bug #14010
+setUnicodeValue(r"Environment", "fakePath", "flywind", HKEY_CURRENT_USER)
```
Comment (timotheecour) [inline tests/stdlib/tregistry.nim]:
```suggestion
block: # bug #14010
  let path = "Environment"
  let key = "D20210328T202842_key"
  let val = "D20210328T202842_val"
  let handle = HKEY_CURRENT_USER
  setUnicodeValue("Environment", key, val, handle)
  doAssert getUnicodeValue(path, key, handle) == val
```


(untested, please 1st double check)

File: tests/stdlib/tregistry.nim [hunk 3]
```diff
@@ -0,0 +1,14 @@
+discard """
+  disabled: "unix"
+  matrix: "--gc:refc; --gc:arc"
+"""
+
```
Comment (timotheecour) [inline tests/stdlib/tregistry.nim:5]: still needs when defined windows (imagine other OS's)

Comment (ringabout) [reply tests/stdlib/tregistry.nim:5]: fixed

**Review by timotheecour — APPROVED** [review]

**Comment by Araq** [comment]
Superb work!
