### PR TITLE
close #16844

### LINKED ISSUE #16844: improve error message for incorrect formed block
Error message is strange

### Example
```nim
import macros

macro m() =
  nnkBlockStmt.newTree(
    # newEmptyNode(),
    nnkDiscardStmt.newTree(newEmptyNode())
  )

m()
```

### Current Output
```
Traceback from system (most recent call last)
Error: unhandled exception: index 1 not in 0 .. 0 [IndexDefect]
```

### Expected Output
```
/home/levovix/a.nim(9, 2) template/generic instantiation of `m` from here
/usr/lib/nim/core/macros.nim(626, 22) Error: illformed AST: block discard
```

### PR DESCRIPTION
**Pull request by ringabout**
```nim
import macros

macro m() =
  nnkBlockStmt.newTree(
    # newEmptyNode(),
    nnkDiscardStmt.newTree(newEmptyNode())
  )

m()
```

Before this PR:
```
Traceback from system (most recent call last)
Error: unhandled exception: index 1 not in 0 .. 0 [IndexDefect]
```

After this PR:
```
play.nim(8, 2) template/generic instantiation of `m` from here
lib\core\macros.nim(674, 22) Error: illformed AST: block discard
```

### CODE REVIEW

File: compiler/renderer.nim [hunk 1]
```diff
@@ -820,14 +820,24 @@ proc gTypeClassTy(g: var TSrcGen, n: PNode) =
   dedent(g)
 
 proc gblock(g: var TSrcGen, n: PNode) =
+  if n.len == 0:
```
Comment (timotheecour) [inline compiler/renderer.nim:827]: can you simply write:
```nim
  if n.len != 2: return # block stmt should have two children
```
and remove the rest of the diff?

Comment (ringabout) [reply compiler/renderer.nim:827]: It's intended for better error messages.

With this, the error messages don't produce `block ...`

Comment (timotheecour) [reply compiler/renderer.nim:827]: ok; then maybe add a short comment to explain this so that the next person doesn't do this "wrong simplification" ?

**Review by timotheecour — APPROVED** [review]

File: compiler/renderer.nim (hunk 1 above)
Comment (ringabout) [reply compiler/renderer.nim:827]: sure

**Review by timotheecour — APPROVED** [review]

File: compiler/renderer.nim [hunk 2]
```diff
@@ -820,14 +820,28 @@ proc gTypeClassTy(g: var TSrcGen, n: PNode) =
   dedent(g)
 
 proc gblock(g: var TSrcGen, n: PNode) =
+  # you shouldn't simplify it to `n.len < 2`
+  # because the following codes should be executed
+  # even block stmt only one child for getting
```
Comment (ringabout) [inline compiler/renderer.nim]:
```suggestion
  # even when block stmt only one child for getting
```

File: compiler/renderer.nim [hunk 3]
```diff
@@ -820,14 +820,28 @@ proc gTypeClassTy(g: var TSrcGen, n: PNode) =
   dedent(g)
 
 proc gblock(g: var TSrcGen, n: PNode) =
+  # you shouldn't simplify it to `n.len < 2`
+  # because the following codes should be executed
+  # even when block stmt only one child for getting
```
Comment (ringabout) [inline compiler/renderer.nim]:
```suggestion
  # even when block stmt has only one child for getting
```
