### PR TITLE
close #1550 add testcase

### LINKED ISSUE #1550: Passing a generic iterator to another iterator doesn't seem to work
``` nimrod
type
  A[T] = iterator(x: T): T {.gcsafe, closure.}
  B = iterator(y: A[int], z: int): int {.gcsafe, closure.}

iterator aimp[T](x: T): T {.gcsafe, closure.} =
  var total = 0
  while (total < 100):
    yield total
    total += x

iterator bimp(y: A[int], z:int): int {.gcsafe, closure.} =
  #var x = y(z)
  for i in y(z):
    yield i

for x in aimp[int](3):
  echo x

var y = aimp[int]
var z = bimp
for x in z(y):
  echo x
```

This gives: 

```
/tmp/aporia/a16.nim(23, 12) Error: type mismatch: got (int)
but expected one of:
system.items(a: cstring): iter[char]
...
```

Uncommenting  #var x = y(z), yields:

```
/tmp/aporia/a16.nim(31, 10) Error: type mismatch: got (iterator (int): int{.closure, gcsafe.})
but expected one of:
iterator (A[int], int): int{.closure, gcsafe.}
```

which seems incorrect.

### PR DESCRIPTION
**Pull request by ringabout**
close #1550 add testcase

### CODE REVIEW

File: tests/iter/t1550.nim [hunk 1]
```diff
@@ -0,0 +1,20 @@
+type
```
Comment (timotheecour) [inline tests/iter/t1550.nim:1]: add a `block: # bug #1550` (even if in filename; makes things more searchable)
