### PR TITLE
fixes #22553; regression of offsetof(T, anFieldOfUncheckedArray)

### LINKED ISSUE #22553: `offsetof(T, anFieldOfUncheckedArray)` returned the wrong value
### Description

Here is my code example:
```nim
type
  ChunkObj = object
    data: UncheckedArray[byte]

proc main() =
  let n = offsetOf(ChunkObj, data)
  echo n
  assert n != 0                          # By looking at the generated C code, it should be 1 or something else
```
This is the C code generated by the NIM compiler:
```c
struct tyObject_ChunkObj__mOTFrUaGXmv4xFi10w76AA {
	char dummy;                                      // offset 0
	NU8 data[SEQ_DECL_SIZE];                // offset 1
};
```
From the above c code, you can see that the offset of the 'data' field should not be 0.

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-23
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 6b04d0395ab1d6d8efa7d287c73da2c7230800c9
active boot switches: -d:release

### Current Output

```text
output '0' and assertion exception.

0
/root/repos/spaces/src/spaces.nim(33) spaces
/root/repos/spaces/src/spaces.nim(13) main
/root/.choosenim/toolchains/nim-#devel/lib/std/assertions.nim(41) failedAssertImpl
/root/.choosenim/toolchains/nim-#devel/lib/std/assertions.nim(36) raiseAssert
/root/.choosenim/toolchains/nim-#devel/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: /root/repos/spaces/src/spaces.nim(13, 3) `n != 0`  [AssertionDefect]
```

### Expected Output

```text
1
```

### Possible Solution

_No response_

### Additional Information

I also ran into another issue, which I'll explain in a new issue.

### PR DESCRIPTION
**Pull request by ringabout**
fixes #22553

follow up https://github.com/nim-lang/Nim/pull/21979 which introduced a char dummy member prepended to objs only containing an UncheckedArray

### CODE REVIEW

File: tests/misc/tsizeof.nim [hunk 1]
```diff
@@ -732,3 +732,11 @@ type
...
 doAssert sizeof(PackedUnion) == 11
 doAssert alignof(PackedUnion) == 1
+
+# bug #22553
+type
+  ChunkObj = object
+    data: UncheckedArray[byte]
+
+doAssert sizeof(ChunkObj) == 1
+doAssert offsetOf(ChunkObj, data) == 1
```
Comment (Araq) [inline tests/misc/tsizeof.nim:742]: Why? The offset of `data` should be 0.

Comment (ringabout) [reply tests/misc/tsizeof.nim:742]: Because in https://github.com/nim-lang/Nim/pull/21979, it added a char dummy member prepended to objects only containing an `UncheckedArray`.
`c_offsetOf` also gives `1`. 

```nim
type
  ChunkObj = object
    data: UncheckedArray[byte]
```

```c
struct tyObject_ChunkObj__mOTFrUaGXmv4xFi10w76AA {
	char dummy;                                      // offset 0
	NU8 data[SEQ_DECL_SIZE];                // offset 1
};
```
