### PR TITLE
fixes #16585

### LINKED ISSUE #16585: renderSQL can't handle special charaters (e.g. Umlaut)
Function `renderSQL` outputs the wrong string.

### Example
```import parsesql
let word = "Schätze"
let word_sql = newNode(k = nkStringLit, s = word)
echo word_sql.renderSQL()
echo word_sql.strVal
```

### Current Output
```
'Sch\xC3\xA4tze'
Schätze
```

### Expected Output
```
'Schätze'
Schätze
```

### Comment
Let's ask Liselotte Pulver for some Umlaut-classes as granted to James Cagney (One, Two, Three - Billy Wilder, 1961).

### PR DESCRIPTION
**Pull request by Araq**

### CODE REVIEW

File: lib/pure/parsesql.nim [hunk 1]
```diff
@@ -1223,6 +1226,17 @@ proc addMulti(s: var SqlWriter, n: SqlNode, sep = ',', prefix, suffix: char) =
 proc quoted(s: string): string =
   "\"" & replace(s, "\"", "\"\"") & "\""
 
+func escape(result: var string; s: string) =
```
Comment (timotheecour) [inline lib/pure/parsesql.nim:1229]: add a test in tests/stdlib/tparsesql.nim?

**Comment by Araq** [comment]
Unrelated CI failure, merging.
