### PR TITLE
fixes #8371, macros.hasCustomPragma doesn't crash anymore

### LINKED ISSUE #8371: macros.hasCustomPragma() crashes when working with variant fields
```nim
import macros
template thingy {.pragma.}

type
  Cardinal = enum
    north, east, south, west
  Something = object
    a: float32
    case cardinal: Cardinal
    of north:
      b {.thingy.}: int
    of east:
      c: int
    else: discard

var foo: Something
foo.cardinal = north
echo(foo.b.hasCustomPragma(thingy))
```

console output:
```
stack trace: (most recent call last)
lib\core\macros.nim(1354) hasCustomPragma
lib\core\macros.nim(1320) customPragmaNode
pragmatest1.nim(18, 11) template/generic instantiation from here
lib\core\macros.nim(1320, 30) Error: index out of bounds
```

### PR DESCRIPTION
**Pull request by jangko**

### CODE REVIEW

File: lib/core/macros.nim [hunk 1]
```diff
@@ -1319,6 +1319,9 @@ proc customPragmaNode(n: NimNode): NimNode =
           if identDefs.kind == nnkRecCase:
             identDefsStack.add(identDefs[0])
             for i in 1..<identDefs.len:
+              # if it is and empty 'else' branch, skip
+              if identDefs[i].kind == nnkElse and
```
Comment (cooldome) [inline lib/core/macros.nim]: not sure if it is handled, non else branches can be empty as well.

Comment (jangko) [reply lib/core/macros.nim]: true, i will fix it
