### PR TITLE
fix: std/marshal unmarshaling of ref objects

### LINKED ISSUE #16496: marshal regression with refs that alias the same object
### Example
```nim
import marshal
import streams

type
  Obj = ref object
    i: int
    b: bool

let
  strm = newStringStream()

var
  o = Obj(i: 1, b: false)
  t1 = @[o, o]
  t2: seq[Obj]

doAssert t1[0] == t1[1]

strm.store(t1)
strm.setPosition(0)
strm.load(t2)
strm.close()

doAssert t2[0] == t2[1]
```
### Current Output
```
src/example.nim(21) example
.choosenim/toolchains/nim-#devel/lib/pure/marshal.nim(279) load
.choosenim/toolchains/nim-#devel/lib/pure/marshal.nim(266) loadAny
.choosenim/toolchains/nim-#devel/lib/pure/marshal.nim(186) loadAny
.choosenim/toolchains/nim-#devel/lib/pure/marshal.nim(204) loadAny
.choosenim/toolchains/nim-#devel/lib/core/typeinfo.nim(274) setPointer
.choosenim/toolchains/nim-#devel/lib/system/assign.nim(111) genericAssign
.choosenim/toolchains/nim-#devel/lib/system/assign.nim(106) genericAssignAux
.choosenim/toolchains/nim-#devel/lib/system/gc.nim(251) unsureAsgnRef
.choosenim/toolchains/nim-#devel/lib/system/gc.nim(184) incRef
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
### Expected Output
Nothing.

### Additional Information
If `o = Obj(i: 1, b: false)` is replaced with `o = Obj()`, the above segfault will not occur. Instead, the marshaling will appear to succeed, but the second assertion will fail. The example code will run without issues if `Obj` is an `object` rather than a `ref object`. This may be related to issue #15934.

This code runs without issue in 1.2.6, but fails in 1.2.8 and devel.

`git bisect` on the `version-1-2` branch indicates that the first bad commit is 2624de058895b408de70428eb340a2cce5d9ee5e

Output of `nim -v` for above stacktrace:
```
Nim Compiler Version 1.5.1 [MacOSX: amd64]
Compiled at 2020-12-22
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 297c8e403d110dd872e070563328f4e0c734cd01
```

### PR DESCRIPTION
**Pull request by viega**
Fixes #16496 

Marshal doesn't properly unmarshal *most* ref objects; the exceptions being nil ones
Test case added.

Note that this test (t9754) does pass locally, but there are tons of failures by default on OS X arm64, mostly around the bohem GC, so it's pretty spammy, and could easily have missed something. If there are better instructions please do let me know.

### CODE REVIEW

File: lib/core/typeinfo.nim [hunk 1]
```diff
@@ -341,6 +341,9 @@ proc getPointer*(x: Any): pointer =
   assert x.rawType.kind in pointerLike
   result = cast[ppointer](x.value)[]
 
+  if result != nil and x.rawType.kind != tyPointer:
+      result = cast[pointer](x.value)
```
Comment (ringabout) [inline lib/core/typeinfo.nim]:
```suggestion
    result = cast[pointer](x.value)
```

**Comment by ringabout** [comment]
The logic looks correct to me except that it didn't fix #16496, which should pass assertions.

**Comment by ringabout** [comment]
It seems that it might not be the root cause of the problem. It didn't seem to fix https://github.com/nim-lang/Nim/issues/16496, which is supposed to pass the assertions. 

By checking `genericAsgn`, we know that refs are ptr pointers indeed
```nim
unsureAsgnRef(cast[PPointer](dest), cast[PPointer](s)[])
```
I think `cast[pointer]` might not be correct.

File: lib/core/typeinfo.nim [hunk 2]
```diff
@@ -341,6 +341,9 @@ proc getPointer*(x: Any): pointer =
   assert x.rawType.kind in pointerLike
   result = cast[ppointer](x.value)[]
 
+  if result != nil and x.rawType.kind != tyPointer:
+    result = cast[pointer](x.value)
```
Comment (Araq) [inline lib/core/typeinfo.nim]: Still makes no sense to me. Maybe it's a marshal.nim bug?

Comment (viega) [reply lib/core/typeinfo.nim]: None of this code was written for clarity.  

I've just spent some time on it, and I now understand why there was an extra dereference happening.

The DEREFERENCED value (the actual memory location of the object) is returned to marshal via `getPointer()`, and this is what is cached *not* the pointer that the allocating `Any` set.

So the real issue is that, since `getPointer()` returns the actual reference to the memory the user is given, but `setPointer()` expects something different depending on how the any object has been marked.
If it's been marked as a pointer, it expects the actual reference to memory we need. Otherwise, it expects a POINTER to the reference. This is non-intuitive, and not clearly documented in `setPointer()`, but I am sure it's related to the underlying storage model for refs, which I did not dig into (any pointers to docs would be appreciated; I'd prefer not to dig through code).

When the second Any comes along and Marshal recognizes it's using the same object, it's passing to 'setPointer' the actual memory location, NOT a pointer to that pointer.

So the fix was doing the right thing for this one case, but yes, the real problem is that Marshal should have been storing the cached memory address in a local variable, and pass that, instead of passing the raw memory location.

So I've gone ahead and fixed it properly, and pushed that.

Again the asymmetry between `setPointer()` and  `getPointer()` clearly caused confusion and was unexpected. Some better documentation in typeinfo would be welcome-- it'd be nice to understand why it's expecting to be passed a pointer to the object's address, instead of the object's address.

**Comment by viega** [comment]
> It seems that it might not be the root cause of the problem. It didn't seem to fix #16496, which is supposed to pass the assertions.
> 
> By checking `genericAsgn`, we know that refs are ptr pointers indeed
> 
> ```nim
> unsureAsgnRef(cast[PPointer](dest), cast[PPointer](s)[])
> ```
> 
> I think `cast[pointer]` might not be correct.

@ringabout I just added the test from #16496, and it also passes now.

File: lib/core/typeinfo.nim (hunk 2 above)
Comment (Araq) [reply lib/core/typeinfo.nim]: A `ref` is implemented as a single `ptr` in Nim. The asymmetry in `setPointer` likely arises from the fact that `pointer` in Nim points to an object of unknown size.

**Comment by ringabout** [comment]
> I just added the test from https://github.com/nim-lang/Nim/issues/16496, and it also passes now.

You are incredible!
