### PR TITLE
fixes #24974; SIGSEGV when raising Defect/doAssert

### LINKED ISSUE #24974: SIGSEGV when raising `Defect`/doAssert
### Nim Version

```
Nim Compiler Version 2.2.4 [Linux: amd64]
Compiled at 2025-05-31
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: f7145dd26efeeeb6eeae6fff649db244d81b212d
active boot switches: -d:release
```

```
Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2025-05-31
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: db5973361f3387bf3d559f101e44196df246d7d7
active boot switches: -d:release
```

### Description

```nim
type B = seq[array[1, byte]]
proc s(_: var B): bool = doAssert false
proc d(): B =
  var k: B
  if s(k): discard
  quit 0
  k
for _ in [0]: discard d()
```

### Current Output

```text
Traceback (most recent call last)
/tmp/v.nim(4)            v
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
Error: execution of an external program failed: '/tmp/v'
```

### Expected Output

```text
Error: unhandled exception: /tmp/v.nim(2, 26) `false`  [AssertionDefect]
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #24974

 requires `result` initializations when encountering unreachable code (e.g. `quit`)

### CODE REVIEW

File: compiler/cgen.nim [hunk 1]
```diff
@@ -1234,7 +1234,9 @@ proc allPathsAsgnResult(p: BProc; n: PNode): InitResultEnum =
       else:
         allPathsInBranch(n[i].lastSon)
   of nkCallKinds:
-    if canRaiseDisp(p, n[0]):
+    if canRaiseDisp(p, n[0]) or
+        (n[0].kind == nkSym and sfNoReturn in n[0].sym.flags):
```
Comment (Araq) [inline compiler/cgen.nim:1238]: But there can be calls that don't return that are not marked as `noreturn`.

Comment (ringabout) [reply compiler/cgen.nim:1238]: Other cases are already covered by `canRaiseDisp`, which is quite conservative about functions that never raises. In general, only functions in the system can be exempt from this checking. Otherwise, we have `systemRaisesDefect` for functions in the system

e.g.
```nim
proc `[]`*[T](s: openArray[T]; i: BackwardsIndex): T {.inline, systemRaisesDefect.} =
  system.`[]`(s, s.len - int(i))
```

We can treat `noreturn` function calls consistently as result must be initialized in these cases
