### PR TITLE
Fix nested finally handling in closureiters [backport]

### LINKED ISSUE #19911: finally block doesn't execute in async proc
```nim
import asyncdispatch

template with_async(body) =
   try:
      echo "body"
      body
   finally:
      echo "finally"                # this line doesn't execute

proc p1(a: int) {.async.} =
   try:                             # remove this ok
      with_async:
         echo a
         await sleepAsync(100)      # remove this ok
         return                     # remove this ok
   except:
      discard

when isMainModule:
   waitFor p1(10)
```

The finally block doesn't execute with the above code.
If we remove the line ``return`` or ``await sleepAsync(100)``, or remove the ``try..except`` around the codes block, the finally block will execute.

```
Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2022-04-27
Copyright (c) 2006-2022 by Andreas Rumpf

active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by Menduist**
closes #19911

There was two issues:
- The outer `try` was rewriting the `return` of the inner `try` before the inner `try` had a chance to do it (swallowed the inner finally)
- The `unrollFinally` was returning before giving a chance to the outer `finally` to run (swallowed the outer finally)

### CODE REVIEW

File: compiler/closureiters.nim [hunk 1]
```diff
@@ -806,30 +806,37 @@ proc lowerStmtListExprs(ctx: var Ctx, n: PNode, needsSplit: var bool): PNode =
...
+  let ifBody =
+    if ctx.nearestFinally == 0:
+      block:
+        # the last finally can return
+        let asgn = newTree(nkFastAsgn,
+          newSymNode(getClosureIterResult(ctx.g, ctx.fn, ctx.idgen), info),
+          ctx.newTmpResultAccess())
+
+        let retrn = newTree(nkReturnStmt, asgn)
+        newTree(nkIfStmt, branch, newTree(nkElse, retrn))
```
Comment (ringabout) [inline compiler/closureiters.nim]: Use `retStmt`, `returnNode` or something verbose? `retrn` is a bit weird.

Comment (Menduist) [reply compiler/closureiters.nim]: Done

File: compiler/closureiters.nim [hunk 2]
```diff
@@ -864,6 +876,13 @@ proc transformReturnsInTry(ctx: var Ctx, n: PNode): PNode =
 
   of nkSkip:
     discard
+  of nkTryStmt:
+    if n.hasYields:
+      # the inner try will handle theses transformations
```
Comment (dom96) [inline compiler/closureiters.nim]: Small nit:

```suggestion
      # the inner try will handle these transformations
```

As a side note: thank you for including these comments, they will really help with understanding this code base into the future :)
