### PR TITLE
Fixes #5281

### LINKED ISSUE #5281: streams.readLine(): string should raise IOError, but doesn't
There's two variants of readLine() in the streams module; one writing into a var parameter, the other returning a string.

The returning variant should raise a IOError according to the documentation header, but instead it just returns "" on EOF.

Even if that is the intended behaviour, then this is not workable because plaintext files often contain empty lines in between content.

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

File: tests/osproc/tstdin.nim [hunk 1]
```diff
@@ -11,9 +11,8 @@ doAssert fileExists(getCurrentDir() / "tests" / "osproc" / filename)
...
-while true:
-  let line = p.outputStream.readLine()
-  if line != "":
-    echo line
-  else:
-    break
+
+var line = ""
+
+while p.outputStream.readLine(line.TaintedString):
```
Comment (krux02) [inline tests/osproc/tstdin.nim]: What? Well that conversion just defeats the purpose of `TaintedString`. `line` needs to be of type `TaintedString`. I think this shouldn't even be allowed in the language.
