### PR TITLE
fixes #25306; Dangling pointers in stack traces with `-d:nimStackTraceOverride`

### LINKED ISSUE #25306: Dangling pointers in stack traces with `-d:nimStackTraceOverride`
### Nim Version

2.2.4

### Description

With `nimStackTraceOverride`:

When [`StackTrace`](https://github.com/nim-lang/Nim/blob/0f7b37846773f3193f29e628f75086788ac93fe5/lib/system.nim#L516) is copied, the procname/filename fields point to procnameStr/filenameStr memory which makes the type non-copyable since the pointers must be updated - copies [happen](https://github.com/nim-lang/Nim/blob/0f7b37846773f3193f29e628f75086788ac93fe5/lib/system/stacktraces.nim#L80) however and garbage stack traces, UB and crashes happen as result, when the GC runs as part of copying.

### Current Output

```text

```

### Expected Output

```text

```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #25306

```nim
type
  StackTraceEntry* = object ## In debug mode exceptions store the stack trace that led
                            ## to them. A `StackTraceEntry` is a single entry of the
                            ## stack trace.
    procname*: cstring      ## Name of the proc that is currently executing.
    line*: int              ## Line number of the proc that is currently executing.
    filename*: cstring      ## Filename of the proc that is currently executing.
    when NimStackTraceMsgs:
      frameMsg*: string     ## When a stacktrace is generated in a given frame and
                            ## rendered at a later time, we should ensure the stacktrace
                            ## data isn't invalidated; any pointer into PFrame is
                            ## subject to being invalidated so shouldn't be stored.
    when defined(nimStackTraceOverride):
      programCounter*: uint ## Program counter - will be used to get the rest of the info,
                            ## when `$` is called on this type. We can't use
                            ## "cuintptr_t" in here.
      procnameStr*, filenameStr*: string ## GC-ed alternatives to "procname" and "filename"
```

### CODE REVIEW

**Comment by arnetheduck** [comment]
maybe add `=copy...{.error.}` somewhere?

**Comment by ringabout** [comment]
> =copy...{.error.}

I can add it for `nimStackTraceOverride `. Though I hope it won't break something

**Comment by arnetheduck** [comment]
> I can add it for nimStackTraceOverride . Though I hope it won't break something

I think there's more value adding it always to remove as many differences as possible between override and non-override mode

**Comment by ringabout** [comment]
That would potentially break external libraries that use `StackTraceEntry`.

```nim
type
  StackTraceEntry* = object
    when defined(nimStackTraceOverride):
      programCounter*: uint ## Program counter - will be used to get the rest of the info,
                            ## when `$` is called on this type. We can't use
                            ## "cuintptr_t" in here.
      procnameStr*, filenameStr*: string ## GC-ed alternatives to "procname" and "filename"
    else:
      procname*: cstring      ## Name of the proc that is currently executing.
      filename*: cstring      ## Filename of the proc that is currently executing.

when defined(nimStackTraceOverride):
  proc `procname`*(s: StackTraceEntry): cstring =
    s.procnameStr.cstring

  proc `filename`*(s: StackTraceEntry): cstring =
    s.filenameStr.cstring
```
Ideally, we only provide accessors for `procname` and `filename` for `nimStackTraceOverride`. The differences over `filename` and `procname` with/without `nimStackTraceOverride` already makes these options diverge

**Comment by arnetheduck** [comment]
> only provide accessors 

come to think of it, this is tricky because in current versions, libbacktrace has to _set_ these values to a valid pointer as part of constructing the trace entry.

another way I thought of was to implement an actual `=copy` implementation so the compiler would inject copies in the right places - that copy operator would do the necessary pointer adjustments - not sure if that's possible at this early stage of the nim compilation pipeline though

File: lib/system/stacktraces.nim [hunk 1]
```diff
@@ -65,6 +68,23 @@ when defined(nimStackTraceOverride):
...
+    # points `procname`, `filename` to its own corresponding fields
+    # to avoid dangling pointers # bug #25306 18039
+    result.procname = result.procnameStr.cstring
+    result.filename = result.filenameStr.cstring
+
+  proc copyStackTraceEntrySeq(result: var seq[StackTraceEntry]; s: seq[StackTraceEntry]) =
+    for i in 0..<s.len:
+      let entry = addr s[i]
+      result.add(copyStackTraceEntry entry)
+
```
Comment (Araq) [inline lib/system/stacktraces.nim:78]: You don't have to copy anything here, all you need to do it to patch every entry after an `add` operation.

Comment (arnetheduck) [reply lib/system/stacktraces.nim:78]: strictly speaking, in this particular case, one would want to move the existing entries...

Comment (ringabout) [reply lib/system/stacktraces.nim:78]: `add` operation triggers a copy, which is marked `{.error.}`. Perhaps I need to use `nodestroy` or something?

Comment (Araq) [reply lib/system/stacktraces.nim:78]: patch entries after an `add`.

File: lib/system/stacktraces.nim [hunk 2]
```diff
@@ -29,6 +29,9 @@ when defined(nimStackTraceOverride):
       proc (programCounters: seq[cuintptr_t], maxLength: cint): seq[StackTraceEntry] {.
         nimcall, gcsafe, raises: [], tags: [], noinline.}
 
+
+  const NimStackTraceMsgs = compileOption("stacktraceMsgs")
```
Comment (Araq) [inline lib/system/stacktraces.nim]: Unused code?

Comment (ringabout) [inline lib/system/stacktraces.nim]:
```suggestion
```
