### PR TITLE
Fix void async in templates

### LINKED ISSUE #16159: Future[void] in template caused invalid type: 'void' for var
Function `echo` outputs the wrong string.

### Example
```nim
import asyncdispatch

proc demo(): Future[string] {.async.} =
  await sleepAsync 1
  return "hello, world!"

template then(left: untyped, right: untyped): untyped =
  proc temp(): Future[void] {.async, gensym.} =
    right(await left)
  asyncCheck temp()

template then2(left: untyped, right: untyped): untyped =
  proc temp(): Future[int] {.async, gensym.} =
    right(await left)
    return 0
  asyncCheck temp()

demo().then2 do (v: string): echo v
demo().then do (v: string): echo v
```

### Current Output
(both 1.4 and master)
```
***.nim(19, 7) template/generic instantiation of `then` from here
***.nim(8, 3) Error: invalid type: 'void' for var
```

### Expected Output
```
hello, world
hello, world
```

### Possible Solution

no idea 🤔, it works outside template

### Additional Information

```
$ nim -v
Nim Compiler Version 1.4.0 [Windows: amd64]
Compiled at 2020-10-16
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```
(master)
```
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2020-11-27
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 6b77e16c6f86e5c05795fe881a25be3d17e9c22a
active boot switches: -d:release
```

### LINKED ISSUE #16786: async proc inside a generic proc gives CT error
### Example
```nim
when true:
  import asyncdispatch
  # ok
  block:
    proc main(a: int|string)=
      proc bar(b: int|string) = echo b
      bar(a)
    main(1)

  block:
    proc main(a: int) : Future[void] {.async.} =
      proc bar(b: int): Future[void] {.async.} = echo b
      await bar(a)
    waitFor main(1)

  block:
    proc main(a: int) : Future[void] {.async.} =
      proc bar(b: int | string): Future[void] {.async.} = echo b
      await bar(a)
    waitFor main(1)

  block:
    # bug
    proc main(a: int|string) =
      proc bar(b: int): Future[void] {.async.} = echo b
      waitFor bar(a)
    main(1) # uncomment and it'll work, otherwise Error: invalid type: 'void' for var
```

### Current Output
Error: invalid type: 'void' for var

### Expected Output
works

### Additional Information
1.5.1 2b5841cd2b096624987d7cd1aa217088447076b7
root cause for https://github.com/nim-lang/Nim/issues/16741

### PR DESCRIPTION
**Pull request by ardek66**
Fix #16159
(EDIT(timotheecour) potentially also fixes https://github.com/nim-lang/Nim/issues/16786)

It appears that the issue is caused by `subtypeIsVoid` failing to catch `baseType` if `returnType` is not `nnkBracketExpr`, which seems to happen in templates. I'm not sure why that happens, but this case is already covered at 
https://github.com/nim-lang/Nim/blob/c27cd83265558195316e0d3b6d13ccadcaecc728/lib/pure/asyncmacro.nim#L177
knowing that non-void asyncs in templates work fine, and `returnType` was `nnkCall` in my debugging.

While checking -d:nimDumpAsync, I found that what happens is that normally, if the baseType is not void, the macro expands something like this:
```nim
...
var result: T
...
```
where T is the baseType. This happens both inside and outside a template.
If T is void, the line isnt generated because it is obviously incorrect syntax.
When inside a template, the macro fails to find the `void` in `Future[void]`, so it assumes it isnt void, generating something like:
```nim
...
var result: void
...
```
Which correctly causes the exact error in the issue.

What I did to fix this was to add another condition to `subtypeIsVoid`, checking if `baseType.kind` is `nnkSym`, which is the kind after this assignment https://github.com/nim-lang/Nim/blob/c27cd83265558195316e0d3b6d13ccadcaecc728/lib/pure/asyncmacro.nim#L180 
(correct me if i'm wrong), and then I normally check with `eqIdent` if the symbol is `void` at the according index (~~I tried to keep the new condition similar to the other one, I could've also compare variable `baseType` directly~~ I shortened the expression based on the fact that `baseType` is already assigned depending on the case).

I also added a test to check if both void and non-void procedure work inside templates.

## future work
- [x] this is fragile and doesn't work with aliasing etc, see https://github.com/nim-lang/Nim/pull/17562#issuecomment-809637968 which also shows a potential way to fix this
=> https://github.com/nim-lang/Nim/pull/17633
- [x] add tests refs https://github.com/nim-lang/Nim/pull/17562#discussion_r603664142
=> https://github.com/nim-lang/Nim/pull/17633

### CODE REVIEW

File: lib/pure/asyncmacro.nim [hunk 1]
```diff
@@ -184,8 +184,9 @@ proc asyncSingleProc(prc: NimNode): NimNode =
     verifyReturnType(repr(returnType), returnType)
 
   let subtypeIsVoid = returnType.kind == nnkEmpty or
-        (baseType.kind == nnkIdent and returnType[1].eqIdent("void"))
-
+        ((baseType.kind == nnkIdent or baseType.kind == nnkSym) and
```
Comment (Clyybber) [inline lib/pure/asyncmacro.nim]:
```suggestion
        (baseType.kind in {nnkIdent, nnkSym} and
```

**Comment by timotheecour** [comment]
fragile, this fails with aliases:

```nim
when true:
  when defined(js):
    import std/asyncjs
  else:
    import std/asyncdispatch
  type Foo = void
  template then() =
    proc temp(): Future[Foo] {.async.} =
      discard
    discard temp()
  then()
```
note that it works with js

can `macros.sameType` help?

**Comment by ardek66** [comment]
> can `macros.sameType` help?

Yes I'm working on a solution with `macros.sameType` right now. 
It seems that void aliases didn't work before either: https://play.nim-lang.org/#ix=2UuH

File: tests/async/tasyncintemplate.nim [hunk 2]
```diff
@@ -0,0 +1,12 @@
+discard """
+  output: 42
+"""
+
+import asyncdispatch
+
+template foo() =
+  proc temp(): Future[int] {.async.} = return 42
+  proc tempVoid(): Future[void] {.async.} = echo await temp()
```
Comment (dom96) [inline tests/async/tasyncintemplate.nim:9]: Can we get a test for a template returning a non-Future to test we get a compile error?

**Review by dom96 — APPROVED** [review]
LGTM assuming other async tests work pass :)

**Comment by Araq** [comment]
This is an improvement so I'm merging it.

File: tests/async/tasyncintemplate.nim (hunk 2 above)
Comment (timotheecour) [reply tests/async/tasyncintemplate.nim:9]: => https://github.com/nim-lang/Nim/pull/17633
