### PR TITLE
rationals: support Rational[SomeUnsignedInt]

### LINKED ISSUE #22227: Always errors the first time a uint rational is declared
### Description

Nim will produce an uncatchable when a uint rational such as `3u//1` is declared. Using `nim secret`, I was able to observe that subsequent calls so work.

```nim
import std/rationals

try:
    3u//1
except CatchableError:  # Never executes (this is a compile time error)
    echo "error"

# Never executes
echo 3u//1  
```

### Nim Version

Nim Compiler Version 1.6.14 [MacOSX: amd64]
Compiled at 2023-06-29
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
>>> import std/rationals
>>> 3u//1

 Error: type mismatch: got <uint>
but expected one of:
func `-`[T](x: T; y: Rational[T]): Rational[T]
  first type mismatch at position: 2
  missing parameter: y
proc `-`(x, y: uint): uint
  first type mismatch at position: 2
  missing parameter: y
proc `-`(x, y: uint64): uint64
  first type mismatch at position: 2
  missing parameter: y
21 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

>>> 3u//1
3/1: Rational[system.uint]
```

### Expected Output

```text
>>> import std/rationals
>>> 3u//1
3/1: Rational[system.uint]
```

### Possible Solution

_No response_

### Additional Information

This issue existed on version 1.6.12 too.

### PR DESCRIPTION
**Pull request by shirleyquirk**
fixes #22227
rationale:
    - `3u - 4u` is supported why not`3u.toRational - 4u.toRational`
  - all of rationals' api is on SomeInteger, looks like unsigned is declared as supported
  - math on unsigned rationals is meaningful and useful.

### CODE REVIEW

File: lib/pure/rationals.nim [hunk 1]
```diff
@@ -46,8 +46,9 @@ func reduce*[T: SomeInteger](x: var Rational[T]) =
     x.num = x.num div common
     x.den = x.den div common
   elif x.den < 0:
-    x.num = -x.num div common
-    x.den = -x.den div common
+    when T isnot SomeUnsignedInt:
```
Comment (Araq) [inline lib/pure/rationals.nim]: How can `x.den < 0` be true when typeof(x.den) is an unsigned type?

Comment (shirleyquirk) [reply lib/pure/rationals.nim]: it cant.  but the presence of `-x.den` in this branch is preventing SomeUnsignedInt from compiling.

Comment (Araq) [reply lib/pure/rationals.nim]: So move the `when` further up, for this the `elif` needs to be turned into an `else`.

File: lib/pure/rationals.nim [hunk 2]
```diff
@@ -40,17 +40,17 @@ func reduce*[T: SomeInteger](x: var Rational[T]) =
     reduce(r)
     doAssert r.num == 1
     doAssert r.den == 2
-
+  if x.den == 0:
+    raise newException(DivByZeroDefect, "division by zero")
```
Comment (Araq) [inline lib/pure/rationals.nim:44]: Why doesn't the following `gcd` call do that?

File: lib/pure/rationals.nim [hunk 3]
```diff
@@ -40,17 +40,17 @@ func reduce*[T: SomeInteger](x: var Rational[T]) =
...
   if x.den > 0:
     x.num = x.num div common
     x.den = x.den div common
-  elif x.den < 0:
-    when T isnot SomeUnsignedInt:
-      x.num = -x.num div common
-      x.den = -x.den div common
-  else:
-    raise newException(DivByZeroDefect, "division by zero")
+    return
```
Comment (Araq) [inline lib/pure/rationals.nim]: I didn't ask for this `return`.

File: lib/pure/rationals.nim (hunk 2 above)
Comment (shirleyquirk) [reply lib/pure/rationals.nim:44]: i thought it might do that, but the rationale is that
gcd(v,0) = v "because everything divides 0" [wiki](https://en.wikipedia.org/wiki/Binary_GCD_algorithm)

File: lib/pure/rationals.nim (hunk 3 above)
Comment (shirleyquirk) [reply lib/pure/rationals.nim]: sorry, i dont know what you want instead.

would you prefer
```nim
if x.den==0: raise DivByZeroDefect
if x.den > 0:
  blah
when T isnot SomeUnsignedInt:
  if x.den < 0:
    blah
 ```
 ?

Comment (Araq) [reply lib/pure/rationals.nim]: Yes.
