### PR TITLE
Extended side effect error messages

### LINKED ISSUE #4210: Compiler error for pragma noSideEffect isn't very helpful
Consider this code:

``` nim
import tables
import strutils
import math

proc testProc(): void {.noSideEffect.} =
    var
        i: int
        f: float
        s: string
    let table = {'a': 1, 'b': 2, 'c': 3, 'd': 4}.toTable()
    f = log10(54712344.1123)
    i = f.int()
    s = formatFloat(f, ffScientific)
    debugEcho table['c']

when isMainModule:
    testProc()
```

Passing this to Nim produces the following error message:

```
test.nim(5, 6) Error: 'testProc' can have side effects
```

As a user, this isn't very helpful.  Okay: I understand that it has side-effects, but I can't see any side-effects:
- The first operational line (line 10) creates a hash table
- The second (line 11) calculates a logarithm
- The third (line 12) converts a floating point number to a string
- The last (line 13) is a debugEcho (which pretends to not have side-effects)

By going through the code and commenting out lines at random, I worked out that the offending function was `toTable()`, which either has side-effects or doesn't declare a `noSideEffect` pragma.  However, it would have been **so** much easier (especially for long and complex procedures) if the error message had said:

```
test.nim(5, 6) Error: 'testProc' can have side effects at (10, 50)
```

Now of course there may be multiple instances of side effects, but even if only the first one is shown the user at least has the opportunity to work through them one-by-one.  Alternatively (and better in my opinion) the error could be shown as:

```
test.nim(10, 50) Error: 'testProc' can have side effects despite noSideEffect pragma
```

with a separate entry for each line with a side-effect.  This would have the advantage that tools like [syntastic](https://github.com/scrooloose/syntastic) would mark the location of the side-effect directly.

### LINKED ISSUE #10712: Compiler complains about side effects with global func
Test
```nim
var f: (func: int)
f = (func: int = 5)

func test: int = f()
echo test()
```
Output
```nim
Error: 'test' can have side effects
```
Expected
No side effects at all.
***
```nim
>nim -v
Nim Compiler Version 0.19.9 [Linux: i386]
Compiled at 2019-02-13
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 3520253a09cb8f32df834e619c7435092a370e9d
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by quantimnot**
Fixes #4210
Fixes #10712

Is this the right approach?
Any desired changes to make the messages clearer?
All feedback is welcome.

### CODE REVIEW

File: compiler/sempass2.nim [hunk 1]
```diff
@@ -225,7 +225,17 @@ proc markGcUnsafe(a: PEffects; reason: PNode) =
...
+      a.hasSideEffect = true
+      if a.owner.kind in routineKinds:
+        when reason is PNode:
+          if reason.kind == nkSym:
+            a.owner.sideEffectReasons.add reason.sym
+          else:
+            a.owner.sideEffectReasons.add newSym(skUnknown, a.owner.name, nextSymId a.c.idgen,
+                                              a.owner, reason.info, {})
+        else:
+          a.owner.sideEffectReasons.add reason
```
Comment (timotheecour) [inline compiler/sempass2.nim]: factor. eg:
var sym: PSym
when: ... else: ...
a.owner.sideEffectReasons.add sym

File: compiler/sempass2.nim [hunk 2]
```diff
@@ -1357,7 +1396,10 @@ proc trackProc*(c: PContext; s: PSym, body: PNode) =
     when false:
       listGcUnsafety(s, onlyWarning=false, g.config)
     else:
-      localError(g.config, s.info, ("'$1' can have side effects" % s.name.s) & (g.config $ mutationInfo))
+      if hasMutationSideEffect:
+        localError(g.config, s.info, ("'$1' can have side effects" % s.name.s) & (g.config $ mutationInfo))
```
Comment (timotheecour) [inline compiler/sempass2.nim]:
```nim
localError(g.config, s.info, "'$1' can have side effects$2" % [s.name.s, g.config $ mutationInfo])
```

ditto for other instances (eg in listSideEffects)

File: compiler/sempass2.nim [hunk 3]
```diff
@@ -259,6 +269,33 @@ proc listGcUnsafety(s: PSym; onlyWarning: bool; conf: ConfigRef) =
   var cycleCheck = initIntSet()
   listGcUnsafety(s, onlyWarning, cycleCheck, conf)
 
+proc listSideEffects(s: PSym; onlyWarning: bool; cycleCheck: var IntSet; conf: ConfigRef) =
+  for u in s.sideEffectReasons:
```
Comment (timotheecour) [inline compiler/sempass2.nim]: seems expensive; is that called in a compiles() context? if so, it needs to be disabled in the same way as extended diagnostics are skipped for type mismatch during `compiles()`

File: compiler/sempass2.nim [hunk 4]
```diff
@@ -259,6 +269,33 @@ proc listGcUnsafety(s: PSym; onlyWarning: bool; conf: ConfigRef) =
...
+        listSideEffects(u, true, cycleCheck, conf)
+        message(conf, s.info, msgKind,
+          "'$#' has side effects as it calls '$#'" %
+          [s.name.s, u.name.s])
+      of skParam, skForVar:
+        message(conf, s.info, msgKind,
+          "'$#' has side effects as it performs an indirect call via '$#'" %
+          [s.name.s, u.name.s])
+      else:
+        message(conf, u.info, msgKind,
```
Comment (timotheecour) [inline compiler/sempass2.nim]: generate a single message instead and get rid of `onlyWarning: bool; ` which simplifies and renders better:
```nim
proc listSideEffects(result: var string, s: PSym; cycleCheck: var IntSet; conf: ConfigRef) = ... # ok, still recursive

var msg = ""
listSideEffects(msg, ...)
message(conf, n.info, errGenerated, msg)
```

```nim
proc baz(c: int) =
  echo c
proc bar(b: int) =
  baz(b)
func fn1(a: int) =
  bar(a)
proc main()=
  fn1(3)
main()
```
current:
```
tests/nim/all/t12516.nim(9, 1) template/generic instantiation from here
tests/nim/all/t12516.nim(5, 6) Warning: 'baz' has side effects as it calls 'echo' [SideEffect]
  proc baz(c: int) =
       ^
tests/nim/all/t12516.nim(9, 1) template/generic instantiation from here
tests/nim/all/t12516.nim(7, 6) Warning: 'bar' has side effects as it calls 'baz' [SideEffect]
  proc bar(b: int) =
       ^
tests/nim/all/t12516.nim(9, 6) Error: 'fn1' has side effects as it calls 'bar'
```

instead something like this is better:
```
tests/nim/all/t12516.nim(9, 1) template/generic instantiation from here
tests/nim/all/t12516.nim(9, 6) Error: 'fn1' has side effects as it calls 'bar': func fn1(a: int) =
  tests/nim/all/t12516.nim(7, 6) 'bar' has side effects as it calls 'baz': proc bar(b: int) =
  tests/nim/all/t12516.nim(5, 6) 'baz' has side effects as it calls 'echo':  proc baz(c: int) =
```

Comment (quantimnot) [reply compiler/sempass2.nim]: I changed `listSideEffects` to compile a single message.
I'm unsure of the actual rendered messages though.
The rendering form that you state above shows all locations as errors when I use the nim vscode plugin. But I think it would be clearer if the other locations were hints.

What about something like:
```
<lineinfo> Error: `symbol` has side effects
  <lineinfo> Hint: `symbol` accesses/mutates/calls `reason`
    <lineinfo> Hint: `reason` declared here
```

**Comment by quantimnot** [comment]
I just found nim-lang/RFCs#323 and nim-lang/RFCs#324.

I'm not sure what to apply from those discussions.

**Comment by quantimnot** [comment]
tests/effects/tdiagnostic_messages.nim:
```nim
var globalVar = 0
proc indirectCallViaVarParam(call: var proc(): int {.nimcall.}): int =
  call()
proc indirectCallViaPointer(call: pointer): int =
  cast[ptr proc(): int](call)[]()
proc callWithSideEffects(): int =
  var p = proc (): int {.nimcall.} = 0
  discard indirectCallViaVarParam(p)
  discard indirectCallViaPointer(addr p)
  echo ""
  globalVar

func a: int =
  discard callWithSideEffects()
```

Here is the current state of rendering:

Terminal:
```
tdiagnostic_messages.nim(31, 6) Error: 'a' has side effects
  tdiagnostic_messages.nim(32, 30) Hint: 'a' calls 'callWithSideEffects' which has side effects
    tdiagnostic_messages.nim(24, 6) Hint: 'callWithSideEffects' called by a `noSideEffect` routine, but has side effects
      tdiagnostic_messages.nim(26, 34) Hint: 'callWithSideEffects' calls 'indirectCallViaVarParam' which has side effects
        tdiagnostic_messages.nim(20, 6) Hint: 'indirectCallViaVarParam' called by a `noSideEffect` routine, but has side effects
          tdiagnostic_messages.nim(21, 7) Hint: 'indirectCallViaVarParam' calls a routine with side effects via hidden pointer indirection
      tdiagnostic_messages.nim(27, 33) Hint: 'callWithSideEffects' calls 'indirectCallViaPointer' which has side effects
        tdiagnostic_messages.nim(22, 6) Hint: 'indirectCallViaPointer' called by a `noSideEffect` routine, but has side effects
          tdiagnostic_messages.nim(23, 32) Hint: 'indirectCallViaPointer' calls a routine with side effects via pointer indirection
      tdiagnostic_messages.nim(28, 8) Hint: 'callWithSideEffects' calls 'echo' which has side effects
        ../../lib/system.nim(2004, 6) Hint: 'echo' called by a `noSideEffect` routine, but has side effects
      tdiagnostic_messages.nim(29, 3) Hint: 'callWithSideEffects' accesses global state 'globalVar'
        tdiagnostic_messages.nim(19, 5) Hint: 'globalVar' accessed by a `noSideEffect` routine
```

VSCode:

vscode

File: tests/effects/tdiagnostic_messages.nim [hunk 5]
```diff
@@ -0,0 +1,32 @@
+discard """
+  errormsg: "\'a\' can have side effects"
```
Comment (timotheecour) [inline tests/effects/tdiagnostic_messages.nim]: use
```
nimoutFull: true
nimout: '''
blah blah
```
same as in https://github.com/nim-lang/Nim/pull/18384
(and remove line, file, errormsg)

rationale:
* easier to copy paste when things change (a single block)
* ensures we collect all the ouptu

File: compiler/ast.nim [hunk 6]
```diff
@@ -857,6 +857,7 @@ type
     of routineKinds:
       #procInstCache*: seq[PInstantiation]
       gcUnsafetyReason*: PSym  # for better error messages wrt gcsafe
+      sideEffectReasons*: seq[(TLineInfo, PSym)]  # for better side effect error messages
```
Comment (timotheecour) [inline compiler/ast.nim]: instead of changing AST for something that's only used for error msgs, add a Table/HashSet/other to `TContext` (similar to unusedImports or importModuleMap etc, indexed via `PSym.id`)

File: compiler/sempass2.nim [hunk 7]
```diff
@@ -224,8 +224,25 @@ proc markGcUnsafe(a: PEffects; reason: PNode) =
                                           a.owner, reason.info, {})
 
 when true:
-  template markSideEffect(a: PEffects; reason: typed) =
-    if not a.inEnforcedNoSideEffects: a.hasSideEffect = true
+  template markSideEffect(a: PEffects; reason: typed; useLoc: TLineInfo) =
```
Comment (timotheecour) [inline compiler/sempass2.nim]: turn this into a proc/generic, something like this:
```nim
proc markSideEffect[T](a: PEffects; reason: T; useLoc: TLineInfo) = ...
or even:
proc markSideEffect(a: PEffects; reason: PNode | something; useLoc: TLineInfo) = ...
```

File: compiler/sempass2.nim [hunk 8]
```diff
@@ -224,8 +224,25 @@ proc markGcUnsafe(a: PEffects; reason: PNode) =
...
+            of nkHiddenDeref:
+              kind = skParam
+            else: discard
+            sym = newSym(kind, a.owner.name, nextSymId a.c.idgen,
+                                              a.owner, reason.info, {})
+        else:
+          sym = reason
+        a.owner.sideEffectReasons.add (useLoc, sym)
 else:
   template markSideEffect(a: PEffects; reason: typed) =
```
Comment (timotheecour) [inline compiler/sempass2.nim]: remove this disabled template, and add this at the right place:
```nim
when false: markGcUnsafe(a, reason)
```
which preserves the orginial intent without introducing code duplication

File: compiler/sempass2.nim [hunk 9]
```diff
@@ -224,8 +224,25 @@ proc markGcUnsafe(a: PEffects; reason: PNode) =
...
+        var sym: PSym
+        when reason is PNode:
+          if reason.kind == nkSym:
+            sym = reason.sym
+          else:
+            var kind = skUnknown
+            case reason.kind
+            of nkHiddenDeref:
+              kind = skParam
+            else: discard
```
Comment (timotheecour) [inline compiler/sempass2.nim]:
```suggestion
            let kind = if reason.kind == nkHiddenDeref: skParam else: skUnknown
```

File: compiler/sempass2.nim [hunk 10]
```diff
@@ -259,6 +276,29 @@ proc listGcUnsafety(s: PSym; onlyWarning: bool; conf: ConfigRef) =
...
   listGcUnsafety(s, onlyWarning, cycleCheck, conf)
 
+proc listSideEffects(result: var string; s: PSym; cycleCheck: var IntSet; conf: ConfigRef; indentLevel: int) =
+  template add(msg; level = indentLevel) =
+    result.add repeat("  ", level) & msg
+  for (useLineInfo, u) in s.sideEffectReasons:
+    if u != nil and not cycleCheck.containsOrIncl(u.id):
+      case u.kind
+      of skLet, skVar:
+        add("$# Hint: '$#' accesses global state '$#'\n" % [conf $ useLineInfo, s.name.s, u.name.s])
```
Comment (timotheecour) [inline compiler/sempass2.nim]: use `addf` which appends in place (can be done even if `template add(msg; level = indentLevel)` is used under the scene)
also, name `template add(msg; level = indentLevel)` differently to improve readability and avoid confusion

File: compiler/sempass2.nim [hunk 11]
```diff
@@ -259,6 +276,29 @@ proc listGcUnsafety(s: PSym; onlyWarning: bool; conf: ConfigRef) =
   var cycleCheck = initIntSet()
   listGcUnsafety(s, onlyWarning, cycleCheck, conf)
 
+proc listSideEffects(result: var string; s: PSym; cycleCheck: var IntSet; conf: ConfigRef; indentLevel: int) =
+  template add(msg; level = indentLevel) =
+    result.add repeat("  ", level) & msg
```
Comment (timotheecour) [inline compiler/sempass2.nim]:
```nim
    result.add repeat(">", level) & " " & msg
```
characters are easier to count visually than spaces, and this would reuse the same rendering as used in `--processing` (refs https://github.com/nim-lang/Nim/pull/18372) for a similar purpose (rendering a tree of locations)

File: compiler/sempass2.nim (hunk 4 above)
Comment (timotheecour) [reply compiler/sempass2.nim]: one problem is the other locations are not really hints, they're mascarading as such; hints go through a specific code path in the compiler, which generates color, a hint name etc.

not a big deal though, we can always improve this later

File: tests/effects/tdiagnostic_messages.nim [hunk 12]
```diff
@@ -0,0 +1,32 @@
...
+    tdiagnostic_messages.nim(24, 6) Hint: 'callWithSideEffects' called by a `noSideEffect` routine, but has side effects
+      tdiagnostic_messages.nim(26, 34) Hint: 'callWithSideEffects' calls 'indirectCallViaVarParam' which has side effects
+        tdiagnostic_messages.nim(20, 6) Hint: 'indirectCallViaVarParam' called by a `noSideEffect` routine, but has side effects
+          tdiagnostic_messages.nim(21, 7) Hint: 'indirectCallViaVarParam' calls a routine with side effects via hidden pointer indirection
+      tdiagnostic_messages.nim(27, 33) Hint: 'callWithSideEffects' calls 'indirectCallViaPointer' which has side effects
+        tdiagnostic_messages.nim(22, 6) Hint: 'indirectCallViaPointer' called by a `noSideEffect` routine, but has side effects
+          tdiagnostic_messages.nim(23, 32) Hint: 'indirectCallViaPointer' calls a routine with side effects via pointer indirection
+      tdiagnostic_messages.nim(28, 8) Hint: 'callWithSideEffects' calls 'echo' which has side effects
+        ../../lib/system.nim(2004, 6) Hint: 'echo' called by a `noSideEffect` routine, but has side effects
```
Comment (timotheecour) [inline tests/effects/tdiagnostic_messages.nim]: CI fails on windows because of this:
```
2021-07-04T17:29:51.2842395Z -        ../../lib/system.nim(2004, 6) Hint: 'echo' called by a `noSideEffect` routine, but has side effects
2021-07-04T17:29:51.2844010Z +        ..\..\lib\system.nim(2004, 6) Hint: 'echo' called by a `noSideEffect` routine, but has side effects
```


this could be fixed by `--filenames:canonical`, but then you'd have a 2nd problem: the test would become flaky as changes in system would break this test.

instead simply add a local proc in this file:
```nim
proc myEcho(a: string) {.sideEffect.} = discard
```

File: tests/effects/tdiagnostic_messages.nim [hunk 13]
```diff
@@ -0,0 +1,32 @@
+discard """
+  errormsg: "\'a\' can have side effects"
+  nimout: '''  tdiagnostic_messages.nim(32, 30) Hint: 'a' calls 'callWithSideEffects' which has side effects
+    tdiagnostic_messages.nim(24, 6) Hint: 'callWithSideEffects' called by a `noSideEffect` routine, but has side effects
+      tdiagnostic_messages.nim(26, 34) Hint: 'callWithSideEffects' calls 'indirectCallViaVarParam' which has side effects
+        tdiagnostic_messages.nim(20, 6) Hint: 'indirectCallViaVarParam' called by a `noSideEffect` routine, but has side effects
```
Comment (timotheecour) [inline tests/effects/tdiagnostic_messages.nim]:
```suggestion
        tdiagnostic_messages.nim(20, 6) Hint: 'indirectCallViaVarParam' called by a `.sideEffect` routine
```
simpler = better.

ditto with other messages, make use of `.sideEffect` to simplify the wording

File: compiler/sempass2.nim (hunk 11 above)
Comment (quantimnot) [reply compiler/sempass2.nim]: What about using box symbols?
```
└─ lineinfo Error: reason
   ├─ lineinfo Hint: reason
   │  └─ lineinfo Hint: reason
   └─ lineinfo Hint: reason
```

File: compiler/sempass2.nim (hunk 8 above)
Comment (quantimnot) [reply compiler/sempass2.nim]: What is the intent of `when false`?
Keep code around that maybe needed later on?

File: tests/effects/tdiagnostic_messages.nim (hunk 13 above)
Comment (quantimnot) [reply tests/effects/tdiagnostic_messages.nim]: ```Hint: 'indirectCallViaVarParam' called by a `.sideEffect` routine``` is confusing to me.
What does `.sideEffect` mean?

**Comment by quantimnot** [comment]
The terminal rendering's structure gives context to the hints about what `noSideEffect` routine is trying to use routines with side effects.
The VSCode hints don't provide that context. Should I change them to someting like:
```Hint: 'indirectCallViaVarParam' called by `a` ```

File: tests/effects/tdiagnostic_messages.nim (hunk 13 above)
Comment (timotheecour) [reply tests/effects/tdiagnostic_messages.nim]: `sideEffect` is a valid pragma, opposite of noSideEffect:
```nim
proc echo*(x: varargs[typed, `$`]) {.magic: "Echo", tags: [WriteIOEffect], benign, sideEffect.}
```

and `.foo` is a shortcut for a `{.foo.}` pragma that is used in a growing number of places, it's a convention. ask araq :)

File: compiler/sempass2.nim (hunk 11 above)
Comment (timotheecour) [reply compiler/sempass2.nim]: that'd be fine by me but seems harder to implement? it's ascii right? could possibly be implemented in a followup PR?

File: compiler/sempass2.nim (hunk 8 above)
Comment (timotheecour) [reply compiler/sempass2.nim]: yes, and ensures it's still highlighted and parseable, unlike comments

File: tests/effects/tdiagnostic_messages.nim [hunk 14]
```diff
@@ -0,0 +1,32 @@
...
+        tdiagnostic_messages.nim(22, 6) Hint: 'indirectCallViaPointer' called by a `noSideEffect` routine, but has side effects
+          tdiagnostic_messages.nim(23, 32) Hint: 'indirectCallViaPointer' calls a routine with side effects via pointer indirection
+      tdiagnostic_messages.nim(28, 8) Hint: 'callWithSideEffects' calls 'echo' which has side effects
+        ../../lib/system.nim(2004, 6) Hint: 'echo' called by a `noSideEffect` routine, but has side effects
+      tdiagnostic_messages.nim(29, 3) Hint: 'callWithSideEffects' accesses global state 'globalVar'
+        tdiagnostic_messages.nim(19, 5) Hint: 'globalVar' accessed by a `noSideEffect` routine'''
+  file: "tdiagnostic_messages.nim"
+  line: 31
+"""
+
```
Comment (timotheecour) [inline tests/effects/tdiagnostic_messages.nim:22]: > The terminal rendering's structure gives context to the hints about what noSideEffect routine is trying to use routines with side effects.
The VSCode hints don't provide that context. Should I change them to someting like:
Hint: 'indirectCallViaVarParam' called by `a`

(i prefer threading so i moved your question here)

i don't use VSCode, can you explain further with more context? change to
```
Hint: 'indirectCallViaVarParam' called by `a`
```
from what?

File: tests/effects/tdiagnostic_messages.nim (hunk 13 above)
Comment (quantimnot) [reply tests/effects/tdiagnostic_messages.nim]: I wanted to communicate that 'indirectCallViaVarParam'  is trying to be used by a noSideEffect routine. I guess I'm implying a fix of changing 'indirectCallViaVarParam' to be `.noSideEffect` or that the `.noSideEffect` caller needs to be changed to `.sideEffect`.

How would you communicate this to  a new Nim programmer?

File: tests/effects/tdiagnostic_messages.nim (hunk 14 above)
Comment (quantimnot) [reply tests/effects/tdiagnostic_messages.nim:22]: The VSCode screenshot above shows the message ```'globalVar' accessed by a `noSideEffect` routine```.
It seems difficult for a user to answer which `.noSideEffect` routine is trying to use it.
That information is available in the terminal because of the tree structure.

File: tests/effects/tdiagnostic_messages.nim (hunk 13 above)
Comment (timotheecour) [reply tests/effects/tdiagnostic_messages.nim]: it should be obvious if you read the whole error message, which has all the context.
The problem with overly verbose error messages is it drowns the essential part (the things that vary from instance to instance, ie the sym name here) into noise (the things that don't vary). So you might help a tiny bit a confused user the the 1st time they read it, but you'll hurt readability for the next N times you'll see this error msg.

File: tests/effects/tdiagnostic_messages.nim (hunk 14 above)
Comment (timotheecour) [reply tests/effects/tdiagnostic_messages.nim:22]: got it.
```
Hint: 'callWithSideEffects' called by a `noSideEffect` routine, but has side effects
```
=>
```
Hint: 'callWithSideEffects' called by `.noSideEffect` `a`
```

i think is crips and has all the information (adding 
```
Hint: `.sideEffect` 'callWithSideEffects' called by `.noSideEffect` `a`
```

would be possible but kind of redundant IMO, at this point, up to you)

File: compiler/sempass2.nim (hunk 11 above)
Comment (quantimnot) [reply compiler/sempass2.nim]: Not 7-bit US-ASCII. But could be:
```
`-- lineinfo Error: reason
    |-- lineinfo Hint: reason
    |   `-- lineinfo Hint: reason
    `-- lineinfo Hint: reason
```

I'll try to get to it in a later PR (maybe)

Comment (timotheecour) [reply compiler/sempass2.nim]: ya let's defer to another PR, because my immediate reaction would be: "please generalize in an API that can be reused", even if in some private-for-now module

Comment (quantimnot) [reply compiler/sempass2.nim]: Only whitespace before a diagnostic message is supported by the VSCode Nim plugin.

Relevant code:
https://github.com/pragmagic/vscode-nim/blob/0272a0544ddf147fde98f8a8f2b624b7dcb19eb3/src/nimBuild.ts#L86

I can submit a PR for it, but I'd first like to know for sure that leading '>' will be the standard for structured messages. This affects all tooling that parses the messages. I think I read somewhere that tooling support is a priority this year or something.

File: compiler/sempass2.nim (hunk 4 above)
Comment (quantimnot) [reply compiler/sempass2.nim]: Yeah, realized that it's not the same, but I wanted the Nim VSCode plugin to be able to parse it and then markup my code in the editor. VSCode has diagnostic message types of hint, warning and error. The Nim VSCode plugin can be changed to map something else to internal VSCode hints.

File: tests/effects/tdiagnostic_messages.nim [hunk 15]
```diff
@@ -1,22 +1,26 @@
...
-      tdiagnostic_messages.nim(28, 8) Hint: 'callWithSideEffects' calls 'echo' which has side effects
-        ../../lib/system.nim(2004, 6) Hint: 'echo' called by a `noSideEffect` routine, but has side effects
-      tdiagnostic_messages.nim(29, 3) Hint: 'callWithSideEffects' accesses global state 'globalVar'
-        tdiagnostic_messages.nim(19, 5) Hint: 'globalVar' accessed by a `noSideEffect` routine'''
-  file: "tdiagnostic_messages.nim"
-  line: 31
+  nimoutFull: true
+  action: "reject"
+  cmd: "nim r --hint:Conf:off $file"
+  nimout: '''tdiagnostic_messages.nim(35, 6) Error: 'a' can have side effects
```
Comment (timotheecour) [inline tests/effects/tdiagnostic_messages.nim]: optional nit: https://nim-lang.github.io/Nim/nep1.html
> Prefer multiline triple quote literals to start with a newline; it's semantically identical (it's a feature of triple quote literals) but clearer because it aligns with the next line:
[...]

**Review by timotheecour — APPROVED** [review]
LGTM, excellent addition

File: compiler/sempass2.nim (hunk 11 above)
Comment (timotheecour) [reply compiler/sempass2.nim]: i think we can move forward with this PR, and then in followup work either make vscode nim plugin be aware of `>`, or change back to ' ' here as last resort, but the rationale is that counting visibe chars (eg >) is easier.

There will likely be other static analysis messages done in the compiler that can be written this way so it's good to have 1 way to represent those.

I also wonder whether vscode plugin correctly handles things like the cyclic import error message, or other various multiline messages.

**Comment by RSDuck** [comment]
please rather look at https://github.com/saem/vscode-nim as it's [error parsing code]( https://github.com/saem/vscode-nim/blob/main/src/nimvscode/nimBuild.nim#L125) has gotten some fixes (and also feature additions). https://github.com/pragmagic/vscode-nim is somewhat dead.

File: tests/effects/tdiagnostic_messages.nim (hunk 15 above)
Comment (quantimnot) [reply tests/effects/tdiagnostic_messages.nim]: Nit pick all you want my friend!

File: compiler/sempass2.nim (hunk 11 above)
Comment (quantimnot) [reply compiler/sempass2.nim]: I'm fine to move ahead.

The pragmagic/vscode-nim plugin doesn't seem to support much other than single line diagnostics. I'm not sure of the saem/vscode-nim plugin (just learned of it).

The mutation side effect message rendered by `varpartitions.$` also won't be parsed. That should maybe be combined with this side effect diagnostic message in  a later PR.

**Comment by quantimnot** [comment]
Don't merge. I just notice a small bug. Give me a minute.

**Comment by quantimnot** [comment]
@timotheecour
Please take another look at the message changes I just made. I'm exhausted and my mind isn't working.
Ready to merge if it's ok.

@RSDuck
I just submitted a PR to support the leading '>' in the diagnostic messages.

File: tests/effects/tdiagnostic_messages.nim [hunk 16]
```diff
@@ -2,19 +2,20 @@ discard """
...
+> tdiagnostic_messages.nim(37, 30) Hint: 'a' calls `.sideEffect` 'callWithSideEffects'
+>> tdiagnostic_messages.nim(29, 6) Hint: 'callWithSideEffects' called by `.noSideEffect` 'a'
+>>> tdiagnostic_messages.nim(31, 34) Hint: 'callWithSideEffects' calls `.sideEffect` 'indirectCallViaVarParam'
+>>>> tdiagnostic_messages.nim(25, 6) Hint: 'indirectCallViaVarParam' called by `.noSideEffect` 'a'
+>>>>> tdiagnostic_messages.nim(26, 7) Hint: 'indirectCallViaVarParam' calls routine via hidden pointer indirection
+>>> tdiagnostic_messages.nim(32, 33) Hint: 'callWithSideEffects' calls `.sideEffect` 'indirectCallViaPointer'
+>>>> tdiagnostic_messages.nim(27, 6) Hint: 'indirectCallViaPointer' called by `.noSideEffect` 'a'
+>>>>> tdiagnostic_messages.nim(28, 32) Hint: 'indirectCallViaPointer' calls routine via pointer indirection
+>>> tdiagnostic_messages.nim(33, 10) Hint: 'callWithSideEffects' calls `.sideEffect` 'myEcho'
+>>>> tdiagnostic_messages.nim(24, 6) Hint: 'myEcho' called by `.noSideEffect` 'a'
```
Comment (timotheecour) [inline tests/effects/tdiagnostic_messages.nim]: I much prefer the previous messages before last commit; the new way is confusing as you're omitting the direct links; in more complex cases (eg with templates involved or deeper stacks), it'll be hard to tell how is X called by Y because it wouldn't show intermediate links.

>  just notice a small bug

which one?

File: compiler/semdata.nim [hunk 17]
```diff
@@ -159,6 +159,7 @@ type
     exportIndirections*: HashSet[(int, int)] # (module.id, symbol.id)
     importModuleMap*: Table[int, int] # (module.id, module.id)
     lastTLineInfo*: TLineInfo
+    sideEffects*: Table[int, seq[(TLineInfo, PSym)]] # symbol.id index
```
Comment (Araq) [inline compiler/semdata.nim:162]: Looks much too expensive for any realistically sized project. What is the memory consumption like for bootstrapping?

File: tests/effects/tdiagnostic_messages.nim (hunk 16 above)
Comment (quantimnot) [reply tests/effects/tdiagnostic_messages.nim]: Yeah :)
It had said ```Hint: 'globalVar' accessed by `.noSideEffect` 'callWithSideEffects'```.
`callWithSideEffects` is `.sideEffect`

I just dropped the `.noSideEffect` if that's fine.

File: compiler/semdata.nim (hunk 17 above)
Comment (quantimnot) [reply compiler/semdata.nim:162]: ```./koch boot``` (take third result):
Before:
```192.331s; 839.465MiB```
After: 
```192.473s; 839.906MiB```

```time -l nim c -d=release -o=bin/nim compiler/nim``` (run twice; take second result):
Before:
```709918720  maximum resident set size```
After: 
```711106560  maximum resident set size```

**Comment by quantimnot** [comment]
Current rendering with saem/vscode-nim:
msg

**Comment by quantimnot** [comment]
I don't know why the checks failed:
```
cmd: git -C csources_v1 checkout a8a5241f9475099c823cfe1a5e0ca4022ac201ff
fatal: reference is not a tree: a8a5241f9475099c823cfe1a5e0ca4022ac201ff
```

**Comment by Araq** [comment]
> I don't know why the checks failed

Me neither, I'm investigating...

File: compiler/semdata.nim (hunk 17 above)
Comment (timotheecour) [reply compiler/semdata.nim:162]: * don't measure with `./koch boot`, at least measure with `./koch boot -d:release`, but ideally should be more granular, by computing memory+time for `nim c --compileOnly compiler/nim` for a nim build before this PR vs built after this PR (both built with -d:release)
* also informative would be instrumenting code to compute the sum of `sideEffects.len` for all PContext objects created

I would guess the cost is not significant, but it should be indeed verified.

**Comment by timotheecour** [comment]
> I don't know why the checks failed

retry now that https://github.com/nim-lang/Nim/pull/18427 was merged

File: tests/effects/tdiagnostic_messages.nim (hunk 16 above)
Comment (timotheecour) [reply tests/effects/tdiagnostic_messages.nim]: good now :)

File: compiler/semdata.nim (hunk 17 above)
Comment (timotheecour) [reply compiler/semdata.nim:162]: * compile times are indistinguishable, measuring best of 4 for `nim c --compileOnly compiler/nim` before vs after PR using a nim compiler compiled with -d:release 
* memory usage difference is minimal in the reported stats, but here's a more precise analysis via this small instrumentation:
https://gist.github.com/timotheecour/5b8b1f1602ce3876ba38b189fe14e6a6
(totNode: 13231319, totSym: 321575, sideEffectsMax: 687, sideEffectsTot: 20367)
nim --eval:'echo 13231319/20367'
649.6449648941916

furthermore, the Table uses contiguous memory, unlike the memory allocated for PSym, PNode

=> conclusion: it's not costly.
PNode allocations almost always dominates costs, which is why it'd be worthwhile to move the sparsely used comment node to a separate Table as I've argued elsewhere.

**Review by timotheecour — APPROVED** [review]

**Comment by quantimnot** [comment]
Don't merge. I getting an exception while using nimsuggest:
```
/Volumes/origin/ws/ports/rdn/org.nim-lang.nim/origin.src/compiler/sempass2.nim(292) listSideEffects
/Volumes/origin/ws/ports/rdn/org.nim-lang.nim/origin.src/lib/pure/strutils.nim(2698) addf
/Volumes/origin/ws/ports/rdn/org.nim-lang.nim/origin.src/lib/pure/strutils.nim(2638) invalidFormatString
Error: unhandled exception: invalid format string [ValueError]
```

File: compiler/sempass2.nim [hunk 18]
```diff
@@ -289,7 +289,7 @@ proc listSideEffects(result: var string; s: PSym; cycleCheck: var IntSet;
 
 proc listSideEffects(result: var string; s: PSym; conf: ConfigRef; context: PContext) =
   var cycleCheck = initIntSet()
-  result.addf "'$#' can have side effects\n" % s.name.s
+  result.addf("'$#' can have side effects\n", s.name.s)
```
Comment (timotheecour) [inline compiler/sempass2.nim:292]: nice catch; we should probably issue a warning error when addf is used with varargs.len == 0

Comment (quantimnot) [reply compiler/sempass2.nim:292]: Good idea. I'll submit a PR for it. Warning or error?

Comment (timotheecour) [reply compiler/sempass2.nim:292]: warnings are more flexible because they can be turned into errors, but not vice versa, and it's easy to change whether it defaults as a warningAsError:warnSuspiciousAddf:on|off so it gives a natural migration path without breaking change

I'm curious why would nimsuggest crash but not nim though, any clues? or, what was the command? wasn't code before your fix at least valid ?

Comment (quantimnot) [reply compiler/sempass2.nim:292]: A proc ident `$` was formatted into the first string and then that was passed to `strutils.addf`.

Comment (quantimnot) [reply compiler/sempass2.nim:292]: It was invalid code because of side effects that encouraged me to make this PR.

Comment (timotheecour) [reply compiler/sempass2.nim:292]: > Good idea. I'll submit a PR for it. Warning or error?

see also https://github.com/nim-lang/Nim/pull/14282 which may touch related code.
Not that it'd block your PR, just good to be aware of it.

Comment (quantimnot) [reply compiler/sempass2.nim:292]: I don't know what I was thinking about putting a warning in there for this. It's not the compiler.
Is there a compile time method of checking a varargs' length? Should there be?
```
proc a(b: varargs[string]) =
  when b.len == 0: {.warning: "I need args!".}
  discard
```

Comment (quantimnot) [reply compiler/sempass2.nim:292]: I just found `system.varargsLen` but it seems to be broken.
```
proc a(b: varargs[string]) =
  when varargsLen(b) > 0:
    echo(b)
  else:
    echo("nope")
a()
```
Output: ```[]```

Also:
```
proc a(b: varargs[string]) =
  when varargsLen(kasdjhflkasjdhflkasdjflaisudfyaisduflasdfjhalsjdhfaljskdfh) > 0:
    echo(b)
  else:
    echo("nope")
a()
```
Output: ```[]```

Comment (timotheecour) [reply compiler/sempass2.nim:292]: `varargsLen` works inside templates, not procs, refs https://github.com/nim-lang/Nim/issues/18463

let's discuss this in https://github.com/timotheecour/Nim/issues/780 instead to avoid discussing something unrelated to this PR

**Comment by timotheecour** [comment]
@araq is there anything else blocking this PR to be merged? there has been no pending review comment since 8 days ago

Leaving PRs open for a long time guarantees bitrot and eventual demotivation from PR author, eventually joining the train of the 200+ open abandoned PRs where original author gave up, despite being in a mergeable state at some point.

the concern regarding "how costly is this" was answered in https://github.com/nim-lang/Nim/pull/18418#discussion_r664799321

**Comment by Araq** [comment]
Sorry, it said

> Don't merge. I getting an exception while using nimsuggest:

Will test it on my machine wrt memory consumption and then merge it.

**Comment by timotheecour** [comment]
> Sorry, it said [...]

that was fixed in the "fixed double string formatting bug" commit;
if anything, this proves that the "PTAL" label is a good idea (author can add it when ready for next round/merge, anyone can remove it when comments are added / some action is needed on the PR author part)

**Comment by Araq** [comment]
Can confirm that the memory and CPU consumption is acceptable.

**Comment by Araq** [comment]
Btw this needs a changelog entry.
