### PR TITLE
scriptconfig: register passes once

### LINKED ISSUE #8235: running runNimScript on 2 subsequent nims files causes "Error: internal error: n is not nil"
After applying https://github.com/nim-lang/Nim/pull/8234 to apply 2 subsequent nims files (analog to the way 2 subsequent nim.cfg files can be processed, the 2nd one overriding previous ones), I get an error:

```
 c -o:app -r bugs/t36_nims/t01_main.nim
Hint: used config file '/Users/timothee/git_clone/nim/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/.config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/foo/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/git_clone/foo/bugs/t36_nims/config.nims' [Conf]
in bugs/t36_nims/config.nims
???(0, 0) Error: internal error: n is not nil
Traceback (most recent call last)
/Users/timothee/git_clone/nim/Nim/compiler/nim.nim(133) nim
/Users/timothee/git_clone/nim/Nim/compiler/nim.nim(88) handleCmdLine
/Users/timothee/git_clone/nim/Nim/compiler/scriptconfig.nim(171) runNimScript
/Users/timothee/git_clone/nim/Nim/compiler/modules.nim(106) compileSystemModule
/Users/timothee/git_clone/nim/Nim/compiler/modules.nim(71) compileModule
/Users/timothee/git_clone/nim/Nim/compiler/passes.nim(197) processModule
/Users/timothee/git_clone/nim/Nim/compiler/passes.nim(95) closePasses
/Users/timothee/git_clone/nim/Nim/compiler/sem.nim(630) myClose
/Users/timothee/git_clone/nim/Nim/compiler/msgs.nim(524) internalError
/Users/timothee/git_clone/nim/Nim/compiler/msgs.nim(495) liMessage
/Users/timothee/git_clone/nim/Nim/compiler/msgs.nim(324) handleError
/Users/timothee/git_clone/nim/Nim/compiler/msgs.nim(314) quit
```

```
tree bugs/t36_nims/
bugs/t36_nims/
├── config.nims
├── t01_main.nim
└── t01_main.nims
```

### PR DESCRIPTION
**Pull request by alaviss**
A walkaround for #8235

### CODE REVIEW

File: compiler/scriptconfig.nim [hunk 1]
```diff
@@ -159,8 +159,11 @@ proc runNimScript*(cache: IdentCache; scriptName: string;
 
   defineSymbol(conf.symbols, "nimscript")
   defineSymbol(conf.symbols, "nimconfig")
-  registerPass(graph, semPass)
-  registerPass(graph, evalPass)
+  var registeredPasses {.global.} = false
```
Comment (Araq) [inline compiler/scriptconfig.nim]: I think better is to check ``graph`` whether it already has these passes.

Comment (alaviss) [reply compiler/scriptconfig.nim]: I would love to, but `registerPass` [operates on a global var][0], not `graph` (no idea why). This would not be an issue if it operated on `graph`, since it's created everytime the proc run.

[0]: https://github.com/nim-lang/Nim/blob/1074cc1fb9bd0a69f1990f936dd82313cfb2c2c8/compiler/passes.nim#L67

Comment (Araq) [reply compiler/scriptconfig.nim]: well then that's the real bug. We need to attach it to the ModuleGraph properly.

**Comment by Araq** [comment]
Meh ok, can do that later, it was tested this way, merging.

File: compiler/scriptconfig.nim (hunk 1 above)
Comment (timotheecour) [reply compiler/scriptconfig.nim]: fixed in https://github.com/nim-lang/Nim/pull/9259 and https://github.com/nim-lang/Nim/pull/9265
