### PR TITLE
fixes #7332

### LINKED ISSUE #7332: Undefined Behavior when using const/let tables (Nim v0.18.1)
In new version of Nim I've got different results when trying to receive values from table:
```nim
import tables
const tableOfArray = {
    "one": [true, false, false],
    "two": [false, true, false],
    "three": [false, false, true]
}.toTable()
for i in 0..2:
    echo tableOfArray["two"][i]
```
Code above must print `false true false` to console, but instead it can return all values as false. Or fall into infinity loop. Or throw exception. Anything but proper result.
Same if I change `const` to `let`. But it works when I use `var`:
```nim
var tableOfArray = {
    "one": [true, false, false],
    "two": [false, true, false],
    "three": [false, false, true]
}.toTable()
```
When I use sequence instead of array it works too:
```nim
const tableOfArray = {
    "one": @[true, false, false],
    "two": @[false, true, false],
    "three": @[false, false, true]
}.toTable()
````

### PR DESCRIPTION
**Pull request by jangko**
fixed decayed array problem

### CODE REVIEW

File: compiler/cgen.nim [hunk 1]
```diff
@@ -317,8 +317,13 @@ proc resetLoc(p: BProc, loc: var TLoc) =
       genObjectInit(p, cpsStmts, loc.t, loc, true)
     else:
       useStringh(p.module)
+
+      # array passed as argument decayed into pointer, bug #7332
+      let locName = if skipTypes(loc.t, abstractInst).kind == tyArray and loc.k == locParam:
```
Comment (Araq) [inline compiler/cgen.nim]: Can't it use ``getTypeDesc`` here always?

**Comment by Araq** [comment]
``genAssignment``'s produced ``memcpy`` calls are also affected by this bug.

File: compiler/cgen.nim (hunk 1 above)
Comment (jangko) [reply compiler/cgen.nim]: it can, and no harm, only a bit ugly for generated code.
if you concern about compiler performance, then I will use only getTypeDesc

**Comment by jangko** [comment]
> genAssignment's produced memcpy calls are also affected by this bug.

someone already fixed this in the past
