### PR TITLE
fix #12998 nim doc regression

### LINKED ISSUE #12998: regression(1.04) `nim doc main.nim` generates broken html (no css)
`nim doc main.nim` generates broken html (css file absent)
regression possibly introduced in #12816

### Example
real life example: https://disruptek.github.io/gittyup/gittyup.html
minimal example:
```nim
proc fun*()=
  ## some proc
  discard
```

### Current Output
image

### Expected Output
as in nim 1.0.4:
image

### Possible Solution
* either embed the css in html file or update instructions in `nim --fullhelp` for `nim doc`

### Additional Information
D20191231T070930
chrome console shows:
```
nimdoc.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
dochack.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```
it used to show:
```
dochack.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```

* working in version 1.0.4
* broken in b67dea7a33d24cd54afa8bd37677d066f4be0da1

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #12998 nim doc regression; simplifies tools/kochdocs.nim
* the css file is copied to nimdoc.out.css (and copied only once, in doc output root, even if multiple subdirs eg after `--project`) ; it is copied to nimdoc.out.css instead of nimdoc.css to make it easy for gitignore to ignore it wherever it is (eg in users' own repos)
*  unrelated change but might as well put it in this PR: `./koch --nim:bin/nim_temp rest...` allows running koch commands for a custom nim, just like `testament` (useful when debugging; eg for this PR you can build nim as bin/nim_temp and test out `./koch --nim:bin/nim_temp docs`
* EDIT: unrelated change: nim dump now also shows prefixdir, which is the root nim directory (whether local development or installed)

## note
user can now open docs as follows:
```
nim doc --index:on --outdir:myhtmldocs pathto/main.nim
python3 -m http.server 7026 --directory myhtmldocs
open http://0.0.0.0:7026/main.html
```

## future PR
after this is merged, I have another PR that will make `dochack.js` behave properly for user built docs as well, so that search works in that case as well

### CODE REVIEW

File: compiler/docgen.nim [hunk 1]
```diff
@@ -1048,6 +1049,8 @@ proc generateIndex*(d: PDoc) =
                                               d.conf.projectPath), IndexExt)
     writeIndexFile(d[], dest.string)
 
+const nimRepoDir = currentSourcePath / ".." / ".." # this should be exposed somewhere
```
Comment (Araq) [inline compiler/docgen.nim]: What's so hard with proper relative addressing?

**Comment by Araq** [comment]
Let me elaborate on the problem with ``const nimRepoDir = currentSourcePath / ".." / ".."`` please. Nim can be installed in essentially two different ways:

1. Into your home directory. Then the addressing should be relative to ``getAppDir()``.
2. Into ``/usr/bin``. Then addressing should be relative to ``/etc/nim`` or similar. (In fact, on Linux/Unix we don't really know, Unix is the OS most hostile to software packaging hence once Docker was invented it became an instant success. Note that this "design" wasn't copied on OSX and OSX has its own idea of how you can bundle software that actually works. And it works very much like it does on Windows: Do not spread applications over multiple arbitrary directories!)

In all cases the compile-time's location of the Nim compiler source code is **wrong** as the base for relative addressing. Proof: The for nightly builds ``currentSourcePath`` can be something like ``/home/travis/Nim``. Now try to use this nightly binary on your local machine for anything.

**Comment by timotheecour** [comment]
PTAL: 
`getSystemConfigPath` alone wasn't working in case of a local nim repo, but I found a solution based on `getSystemConfigPath` that should work with both local development nim git repo as well as installed nim:
`getNimRoot(conf)` is such that `getNimRoot(conf) / doc/basicopt.txt` should always exist
* added `NIM_ROOT_DIR`  (analog to the existing NIMBLE_DIR) that user can use to override it; but it works without it even for a nim that is installed
* also added `nimroot` key to `nim dump` so user can see exactly what it is

so for example:
`~/git_clone/Nim/bin/nim_temp doc /pathto/fun.nim`
will work (picking up whatever local modifications to the css file)
and so will
`nim doc /pathto/fun.nim`


NIM_ROOT_DIR is not 100% necessary and I can remove it from this PR if that helps

File: compiler/nimconf.nim [hunk 2]
```diff
@@ -238,6 +238,26 @@ proc getSystemConfigPath*(conf: ConfigRef; filename: RelativeFile): AbsoluteFile
...
     if not fileExists(result): result = AbsoluteDir"/etc/nim" / filename
 
+const nimRepoDirCT = currentSourcePath / ".." / ".." # this should be exposed somewhere
+
+proc getNimRoot*(conf: ConfigRef): AbsoluteDir =
+  ## returns root nim dir; works both with installed nim and local nim git repo.
+  ## This can be easily overridden if needed with NIM_ROOT_DIR environment variable
+  ## The result should satisfy: $result/doc/basicopt.txt exists
+  if conf.nimRootDir.isEmpty:
+    result = getEnv("NIM_ROOT_DIR").AbsoluteDir
```
Comment (Araq) [inline compiler/nimconf.nim]: We discussed this and I won't accept it, sorry. One more reason why I dislike environment vars: Some fellow developer can set it locally, forget about this setting, and then is confused about why the test results on the CIs are different.

Comment (timotheecour) [reply compiler/nimconf.nim]: removed; the logic still works with both installed nim and local repo nim without `NIM_ROOT_DIR` as I was explaining in https://github.com/nim-lang/Nim/pull/13117#issuecomment-573477159

**Comment by timotheecour** [comment]
PTAL; i removed `NIM_ROOT_DIR` env var; the logic still handles both installed nim and local repo nim without NIM_ROOT_DIR as I was explaining in #13117 (comment)

File: compiler/nimconf.nim [hunk 3]
```diff
@@ -238,6 +238,23 @@ proc getSystemConfigPath*(conf: ConfigRef; filename: RelativeFile): AbsoluteFile
     if not fileExists(result): result = p / RelativeDir"etc/nim" / filename
     if not fileExists(result): result = AbsoluteDir"/etc/nim" / filename
 
+const nimRepoDirCT = currentSourcePath / ".." / ".." # this should be exposed somewhere
```
Comment (Araq) [inline compiler/nimconf.nim]: As I explained, I don't like it and I don't understand why it's required.

File: compiler/nimconf.nim [hunk 4]
```diff
@@ -238,6 +238,23 @@ proc getSystemConfigPath*(conf: ConfigRef; filename: RelativeFile): AbsoluteFile
...
+
+proc getNimRoot*(conf: ConfigRef): AbsoluteDir =
```
Comment (Araq) [inline compiler/nimconf.nim]: We have this, it's called ``getSystemConfigPath``

File: compiler/nimconf.nim (hunk 3 above)
Comment (timotheecour) [reply compiler/nimconf.nim]: fixed; I've removed it now.
(long answer: that was to also support the case where the local development nim binary is in some location other than `nim/bin/`, however I now realize that this cannot work because rest of code assumes it's in a specific directory of depth (=1) relative to nim root dir)

File: compiler/nimconf.nim (hunk 4 above)
Comment (timotheecour) [reply compiler/nimconf.nim]: fixed; `getSystemConfigPath` did not work (eg `getSystemConfigPath(conf, "doc/nimdoc.css")` would return `/etc/nim/doc/nimdoc.css` on my system, which not only doesnt' exist but is not what I want here.
However, `getPrefixDir` works, both for installed nim as well as for a local development nim binary; so I've removed `getNimRoot`

**Comment by timotheecour** [comment]
PTAL

File: compiler/docgen.nim [hunk 5]
```diff
@@ -1056,10 +1057,18 @@ proc writeOutput*(d: PDoc, useWarning = false) =
   else:
     template outfile: untyped = d.destFile
     #let outfile = getOutFile2(d.conf, shortenDir(d.conf, filename), outExt, "htmldocs")
-    createDir(outfile.splitFile.dir)
```
Comment (Araq) [inline compiler/docgen.nim:1071]: But look, read this code: We want to create the directory that out**file** resides in. 

Your version: "Use the parentDir of outfile". This is worse.

Comment (timotheecour) [reply compiler/docgen.nim:1071]: done
(not sure i understand though; if anything the version i wrote seems more efficient; maybe parentDir is lacking in pathutils but it'd have to handle each of AbsoluteFile, AbsoluteDir, RelativeFile, RelativeDir)

**Comment by timotheecour** [comment]
PTAL

**Comment by Araq** [comment]
Thank you for your effort and patience!

**Comment by Araq** [comment]
Unrelated CI failure, merging.
