### PR TITLE
fixes #24378; supportsCopyMem can fail from macro context with tuples

### LINKED ISSUE #24378: `supportsCopyMem` can fail from macro context with tuples
### Description

I just noticed helping someone with a problem with my https://github.com/Vindaar/forked syntax sugar library that in some cases `std/typetraits` `supportsCopyMem` can fail in a macro context.

The following code illustrates the problem

```nim
import std / [macros, typetraits]

macro forked*(body: typed): untyped = # typed or untyped does not matter
  result = quote do:
    type WIn = typeof(`body`)
    echo "Type? ", Win, " supportsCopyMem? ", Win.supportsCopyMem
    echo "Type? ", (int, Win), " supportsCopyMem? ", (int, Win).supportsCopyMem

forked:
  "foobar"
```

Note that the straightforward version without a macro:

```nim
type
  WIn = typeof("foo")
echo "Type? ", Win, " supportsCopyMem? ", Win.supportsCopyMem
echo "Type? ", (int, Win), " supportsCopyMem? ", (int, Win).supportsCopyMem
```
yields the correct output.

### Nim Version

```
Nim Compiler Version 2.2.1 [Linux: amd64]
Compiled at 2024-10-28
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 15271dba2f4772a193f027d36c05b838dfff5bd4
active boot switches: -d:release -d:danger
```

(previously tested on a devel compiler from 2024/10/13 with the same behavior)

### Current Output

```text
Type? string supportsCopyMem? false
Type? (int, string) supportsCopyMem? true
```

### Expected Output

```text
Type? string supportsCopyMem? false
Type? (int, string) supportsCopyMem? false
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #24378

```nim
type Win = typeof(`body`)
doAssert not supportsCopyMem((int, Win))
```

`semAfterMacroCall` doesn't skip the children aliases types in the tuple typedesc construction while the normal program seem to skip the aliases types somewhere

`(int, Win)` is kept as `(int, alias string)` instead of expected `(int, string)`

### CODE REVIEW

**Comment by metagn** [comment]
Alternatively we can make `tyAlias` propagate some of the flags from the original type instead of using `rawAddSon` [here](https://github.com/nim-lang/Nim/blob/d61897459d551b37964b23e82548e2c92c920e02/compiler/semtypes.nim#L1711) and [here](https://github.com/nim-lang/Nim/blob/d61897459d551b37964b23e82548e2c92c920e02/compiler/semtypes.nim#L1721). In this case the [`hasDestructor` call](https://github.com/nim-lang/Nim/blob/d61897459d551b37964b23e82548e2c92c920e02/compiler/semmagic.nim#L229) works because of missing flags [`tfHasAsgn`/`tfHasOwned`](https://github.com/nim-lang/Nim/blob/d61897459d551b37964b23e82548e2c92c920e02/compiler/ast.nim#L2025).

File: compiler/semtypes.nim [hunk 1]
```diff
@@ -500,7 +500,7 @@ proc semAnonTuple(c: PContext, n: PNode, prev: PType): PType =
   result = newOrPrevType(tyTuple, prev, c)
   for it in n:
     let t = semTypeNode(c, it, nil)
-    addSonSkipIntLitChecked(c, result, t, it, c.idgen)
+    addSonSkipIntLitChecked(c, result, t.skipTypes({tyAlias}), it, c.idgen)
```
Comment (Araq) [inline compiler/semtypes.nim]: why not make `supportsCopyMem` follow `tyAlias` properly?

**Comment by metagn** [comment]
I didn't notice this before, I think this is the problem:

The propagation of `tfHasAsgn` is [restricted](https://github.com/nim-lang/Nim/blob/d61897459d551b37964b23e82548e2c92c920e02/compiler/ast.nim#L1647-L1650) to some type kinds, which includes `tySequence` but not `tyString`, which fails the `ast.hasDestructor` [condition](https://github.com/nim-lang/Nim/blob/d61897459d551b37964b23e82548e2c92c920e02/compiler/semmagic.nim#L229) for the typetrait. And in `isGCRef`, strings and seqs are [excluded](https://github.com/nim-lang/Nim/blob/d61897459d551b37964b23e82548e2c92c920e02/compiler/types.nim#L356) from counting as GC'd memory, so the other `containsGarbageCollectedRef` check also fails.

I would guess the solution is including string types in the filter in `propagateToOwner` (which makes it work) but could it break something else?

**Comment by Araq** [comment]
> but could it break something else?

I don't think so.
