### PR TITLE
fixes #21245; warn about destructors that can raise

### LINKED ISSUE #21245: Destructor not called for all fields when raising
### Description

```nim
type X = object
  v: int

type Y = object
  x: X
  y: X

var destroys: int
proc `=destroy`(x: var X) =
  echo "destroying"
  inc destroys
  raise (ref ValueError)(msg: $destroys)
  
  
proc f() =
  var y: Y = Y()
  echo y

echo "calling f"
try:
  f()
except ValueError as e:
  echo "got ", e.msg
```

This is a continuation of #21004 and #11887 - similarly, an exception in `=destroy` causes the other destructor not to run, but this time for another field in an object meaning that objects are not fully destroyed if any destructor raises.

If instead we raise from a destrutor on `Y`, none of the fields are destroyed, ie only the "main" object destructor runs.

### Nim Version

play latest

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Araq**
Todo:

- [x] changelog update
- [x] document it

### CODE REVIEW

File: compiler/semstmts.nim [hunk 1]
```diff
@@ -1857,6 +1857,11 @@ proc semOverride(c: PContext, s: PSym, n: PNode) =
   case name
   of "=destroy":
     bindTypeHook(c, s, n, attachedDestructor)
+    if s.ast != nil:
+      if s.ast[pragmasPos].kind == nkEmpty:
+        s.ast[pragmasPos] = newNodeI(nkPragma, s.info)
+      s.ast[pragmasPos].add newTree(nkExprColonExpr,
```
Comment (arnetheduck) [inline compiler/semstmts.nim:1863]: what if I want to override it and actually raise?

File: compiler/sempass2.nim [hunk 2]
```diff
@@ -1499,7 +1499,8 @@ proc trackProc*(c: PContext; s: PSym, body: PNode) =
   let p = s.ast[pragmasPos]
   let raisesSpec = effectSpec(p, wRaises)
   if not isNil(raisesSpec):
-    checkRaisesSpec(g, false, raisesSpec, t.exc, "can raise an unlisted exception: ",
+    let useWarning = s.name.s == "=destroy"
+    checkRaisesSpec(g, useWarning, raisesSpec, t.exc, "can raise an unlisted exception: ",
```
Comment (arnetheduck) [inline compiler/sempass2.nim:1503]: the warning here probably needs an explicit text to explain what's going on, ie if someone calls `file.write`, they won't know what hit them..

File: compiler/semstmts.nim (hunk 1 above)
Comment (Araq) [reply compiler/semstmts.nim:1863]: Should still work but it's hacky. :P
