### PR TITLE
fixes #23945; type checking for whenvm expresssions

### LINKED ISSUE #23945: Invalid type in `nkWhenStmt`
### Description

The following snippet (from md5.nim):

```nim
template slice(s: string, a, b): openArray[uint8] =
  when nimvm:
    # toOpenArray is not implemented in VM
    var s2 = newSeq[uint8](s.len)
    for i in 0 ..< s2.len:
      s2[i] = uint8(s[i])
    s2
  else:
    s.toOpenArrayByte(a, b)
```

creates an `nkWhenStmt` whose `typ` is `tySequence` which is wrong, specially for the runtime branch (`s` is an `openArray`) - this disturbs the type analysis done in `nlvm` (since it uses `typ` to determine how to load the source.

### Nim Version

2.0.8

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #23945

### CODE REVIEW

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -2694,6 +2696,11 @@ proc semWhen(c: PContext, n: PNode, semCheck = true): PNode =
     if n.len == 1:
       result.add(newTree(nkElse, newNode(nkStmtList)))
 
+    if $result.typ == "seq[uint8]":
+      echo " -> ", result.typ
+      echo semCheck
+      echo n.renderTree
+
```
Comment (ringabout) [inline compiler/semexprs.nim]:
```suggestion
```

**Comment by ringabout** [comment]
pending https://github.com/nim-lang/checksums/pull/16

**Comment by ringabout** [comment]
Without checking, it causes weird problems when mixing different types

**Comment by ringabout** [comment]
Progress: https://github.com/mratsim/constantine/pull/459
Progress: https://github.com/mratsim/constantine/pull/461
