### PR TITLE
close #5540 generic object with generic field evaluated too early

### LINKED ISSUE #5540: generic object with generic field evaluated too early
```nim
type
  Fruit = object
  Yellow = object
    a: int
  
template getColor(x: typedesc[Fruit]): typedesc = Yellow

type
  Banana[T] = object
    b: T
    a: getColor(Fruit) # this one works

  Apple[T] = object
    a: T
    b: getColor(T) # this one failed to compile
    
var x: Banana[int]
x.b = 13
x.a.a = 17
echo x
```

looks like the compiler evaluate the generic field involving template too early.

error messages:
```text
alias.nim(15, 16) Error: type mismatch: got (typedesc[T])
but expected one of:
template getColor[](x: typedesc[Fruit]): typedesc
```

### PR DESCRIPTION
**Pull request by timotheecour**
close #5540

### CODE REVIEW

File: tests/misc/t5540.nim [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    Fruit = object
+    Yellow = object
+      a: int
+    
+  template getColor(x: typedesc[Fruit]): typedesc = Yellow
+
+  type
+    Banana[T] = object
+      b: T
+      a: getColor(Fruit) # this one works
```
Comment (ringabout) [inline tests/misc/t5540.nim]:
```suggestion
      a: getColor(Fruit)
```

File: tests/misc/t5540.nim [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+
+    Apple[T] = object
+      a: T
+      b: getColor(T) # this one failed to compile
```
Comment (ringabout) [inline tests/misc/t5540.nim]:
```suggestion
      b: getColor(T)
```

**Review by ringabout — APPROVED** [review]
