### PR TITLE
Fix constant folding of len() with concept type

### LINKED ISSUE #7952: Compiler crash with `len` in concept and array
Code:
```nim
type 
  HasLen = concept iter
    len(iter) is int

proc echoLen(x: HasLen) = 
  echo len(x)

echoLen([1, 2, 3, 4, 5])
```
I don't know if this is valid (but I think it is).
Probably related to https://github.com/nim-lang/Nim/issues/6277

<details>
  <summary>`./koch temp c` output (click to open)</summary>

```
tt.nim(8, 13) template/generic instantiation from here
tt.nim(8, 13) template/generic instantiation from here
Error: internal error: invalid kind for lastOrd(tyUserTypeClass)
Traceback (most recent call last)
nim.nim(114)             nim
nim.nim(78)              handleCmdLine
main.nim(169)            mainCommand
main.nim(79)             commandCompileToC
modules.nim(141)         compileProject
modules.nim(78)          compileModule
passes.nim(238)          processModule
passes.nim(126)          processTopLevelStmt
sem.nim(586)             myProcess
sem.nim(554)             semStmtAndGenerateGenerics
semstmts.nim(1875)       semStmt
semexprs.nim(815)        semExprNoType
semexprs.nim(2337)       semExpr
semexprs.nim(798)        semDirectOp
semexprs.nim(651)        semOverloadedCallAnalyseEffects
semcall.nim(449)         semOverloadedCall
semcall.nim(411)         semResolvedCall
seminst.nim(348)         generateInstance
seminst.nim(149)         instantiateBody
semexprs.nim(1500)       semProcBody
semexprs.nim(2431)       semExpr
semstmts.nim(1816)       semStmtList
semexprs.nim(2338)       semExpr
semexprs.nim(1952)       semMagic
semexprs.nim(798)        semDirectOp
semexprs.nim(651)        semOverloadedCallAnalyseEffects
semcall.nim(441)         semOverloadedCall
semcall.nim(265)         resolveOverloads
semcall.nim(93)          pickBestCandidate
sigmatch.nim(2323)       matches
sigmatch.nim(2279)       matchesAux
sigmatch.nim(2023)       paramTypesMatch
sigmatch.nim(2007)       paramTypesMatchAux
sigmatch.nim(1820)       localConvMatch
semexprs.nim(2338)       semExpr
semexprs.nim(1952)       semMagic
semexprs.nim(799)        semDirectOp
semexprs.nim(707)        afterCallActions
semexprs.nim(575)        evalAtCompileTime
semfold.nim(633)         getConstExpr
types.nim(671)           lengthOrd
types.nim(663)           lastOrd
msgs.nim(594)            internalError
msgs.nim(488)            rawMessage
msgs.nim(485)            rawMessage
msgs.nim(408)            handleError
msgs.nim(398)            quit
FAILURE
```
</details>

### PR DESCRIPTION
**Pull request by LemonBoy**
Fixes #7952

### CODE REVIEW

File: compiler/semfold.nim [hunk 1]
```diff
@@ -637,7 +637,7 @@ proc getConstExpr(m: PSym, n: PNode; g: ModuleGraph): PNode =
       of mLengthArray:
         # It doesn't matter if the argument is const or not for mLengthArray.
         # This fixes bug #544.
-        result = newIntNodeT(lengthOrd(g.config, n.sons[1].typ), n, g)
+        result = newIntNodeT(lengthOrd(g.config, n.sons[1].typ.skipTypes(tyUserTypeClasses)), n, g)
```
Comment (Araq) [inline compiler/semfold.nim]: I think ``lengthOrd`` should do this skipping then?

Comment (LemonBoy) [reply compiler/semfold.nim]: Indeed, I've shuffled some other checks to make all the routines more or less uniform-looking

File: compiler/types.nim [hunk 2]
```diff
@@ -699,25 +699,26 @@ proc lastFloat*(t: PType): BiggestFloat =
...
     internalError(newPartialConfigRef(), "invalid kind for lastFloat(" & $t.kind & ')')
     NaN
 
 
 proc lengthOrd*(conf: ConfigRef; t: PType): BiggestInt =
-  case t.kind
+  case t.skipTypes(tyUserTypeClasses).kind
   of tyInt64, tyInt32, tyInt: result = lastOrd(conf, t)
   of tyDistinct: result = lengthOrd(conf, t.sons[0])
+  of tyUserTypeClasses: result = lengthOrd(conf, t.sons[^1])
```
Comment (Araq) [inline compiler/types.nim]: Dead code.
