### PR TITLE
fix https://github.com/nim-lang/RFCs/issues/352: show top-level import for top-level runnableExamples in generated docs

### LINKED ISSUE #352: show top-level import for top-level runnableExamples in generated docs
## proposal
make docgen automatically add `import foo` in the generated html for a top-level `runnableExamples` inside module `foo`;

in fact this is what is done by the part of docgen that does for running the code, see https://github.com/nim-lang/Nim/pull/17282/files#diff-2471f1aaac2c91ed83e0317b1b0b322fc719a4cb431de811baa8e350dade283fR531, except that:

* unlike what's done in docgen though, it'll need to show a canonical relative path, not an absolute path; this requires https://github.com/nim-lang/Nim/pull/16999 which I still need to finalize,
* unlike what's done in docgen, we probably only want to show imports for top-level runnableExamples

## pros
easier to copy paste and edit, matches what's actually being run

## note
to avoid generating too much noise, this proposal only concerns top-level runnableExamples, so that
```nim
doAssert toUpperAscii("FooBar!") == "FOOBAR!"
```
will remain unaffected instead of generating:
```nim
import std/strutils
doAssert toUpperAscii("FooBar!") == "FOOBAR!"
```
which would just obfuscate (a little bit) the code; it should be clear from context that `import std/strutils` is needed for runnableExamples attached to a symbol.

it's not perfect, because some large but non top-level runnableExamples could benefit from showing such import, but these are rare; eg: https://nim-lang.github.io/Nim/sugar.html#collect.m%2Cuntyped

## links
refs https://github.com/nim-lang/Nim/pull/17203#issuecomment-799663181
refs https://forum.nim-lang.org/t/7622#48410
pr_fix_rfc_17282_runnableExamples_show_import

### PR DESCRIPTION
**Pull request by timotheecour**
follows https://github.com/nim-lang/Nim/pull/16999
fix https://github.com/nim-lang/RFCs/issues/352

### CODE REVIEW

File: compiler/docgen.nim [hunk 1]
```diff
@@ -556,7 +556,14 @@ $3
   if rdoccmd notin d.exampleGroups:
     d.exampleGroups[rdoccmd] = ExampleGroup(rdoccmd: rdoccmd, docCmd: d.conf.docCmd, index: d.exampleGroups.len)
   d.exampleGroups[rdoccmd].code.add "import $1\n" % outp.string.quoted
-  result = (rdoccmd, code)
+
+  var codeShown: string
+  if topLevel: # refs https://github.com/nim-lang/RFCs/issues/352
+    let title = canonicalImport(d.conf, AbsoluteFile d.filename)
+    codeShown = "import $#\n$#" % [title, code]
```
Comment (konsumlamm) [inline compiler/docgen.nim:563]:
```suggestion
    codeShown = "import $#\n\n$#" % [title, code]
```
I think it would be nicer to have a blank line between the top-level import and the rest of the code.

File: compiler/docgen.nim [hunk 2]
```diff
@@ -505,7 +505,7 @@ proc runAllExamples(d: PDoc) =
 
 proc quoted(a: string): string = result.addQuoted(a)
 
-proc prepareExample(d: PDoc; n: PNode): tuple[rdoccmd: string, code: string] =
+proc prepareExample(d: PDoc; n: PNode, topLevel: bool): tuple[rdoccmd: string, code: string] =
```
Comment (konsumlamm) [inline compiler/docgen.nim:508]:
```suggestion
proc prepareExample(d: PDoc; n: PNode, topLevel = false): tuple[rdoccmd: string, code: string] =
```
The common case is that the example isn't at the top level.

Comment (timotheecour) [reply compiler/docgen.nim:508]: it doesn't simplify the code, `prepareExample` is used only once

File: compiler/docgen.nim (hunk 1 above)
Comment (timotheecour) [reply compiler/docgen.nim:563]: this would look weird in presence of other imports, eg:
```nim
import std/tables

from std/sequtils import zip

let
  names = ["John", "Paul", "George", "Ringo"]
  years = [1940, 1942, 1943, 1940]
```

plus, vertical real estate matters to avoid too much scrolling.
if there's consensus, i can change it though, but i prefer the way i wrote it
