### PR TITLE
fixes #21974; fixes sameConstant fieldDefect

### LINKED ISSUE #21974: Error compiling with ARC/ORC
### Description

Compiling this code with _ARC/ORC_ produces the exception "_fatal.nim(53) sysFatal Error: unhandled exception: field 'intVal' is not accessible for type 'TNode' using 'kind = 29' [FieldDefect]_".
It works compiling with _--mm:none_ or _--mm:refc_.

```nim
type Test*[T] = ref object
    values : seq[T]
    counter: int

proc newTest*[T](): Test[T] =
    result         = new(Test[T])
    result.values  = newSeq[T](16)
    result.counter = 0

proc push*[T](self: Test[T], value: T) =
    self.counter += 1
    if self.counter >= self.values.len:
        self.values.setLen(self.values.len * 2)
    self.values[self.counter - 1] = value

proc pop*[T](self: Test[T]): T =
    result         = self.values[0]
    self.values[0] = self.values[self.counter - 1] # <--- This line
    self.counter  -= 1

when isMainModule:
    type X = tuple
        priority: int
        value   : string

    var a = newTest[X]()
    a.push((1, "One"))
    doAssert a.pop.value == "One"
```

### Nim Version

Nim Compiler Version 1.9.3 [Windows: amd64]
Compiled at 2023-05-29

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #21974

### CODE REVIEW

File: compiler/injectdestructors.nim [hunk 1]
```diff
@@ -1016,7 +1016,7 @@ proc p(n: PNode; c: var Con; s: var Scope; mode: ProcessMode; tmpFlags = {sfSing
 
 proc sameLocation*(a, b: PNode): bool =
   proc sameConstant(a, b: PNode): bool =
-    a.kind in nkLiterals and a.intVal == b.intVal
+    a.kind in nkLiterals and b.kind in nkLiterals and a.intVal == b.intVal
```
Comment (metagn) [inline compiler/injectdestructors.nim:1019]: This inner proc is misleading, `nkLiterals` includes string and float literals, the only reason we can access `intVal` here is because it's only called in the `nkBracketExpr` branch below. For readability's sake I would suggest renaming to `sameIndexConstant` or just inlining it.
