### PR TITLE
fixes #19967; reset does not work on set [backport: 1.2]

### LINKED ISSUE #19967: `reset` does not work on `set`
```nim
type
  X = object
    a: string
    b: set[char]

var y = X(b: {'a'})

reset(y)

doAssert y.b == {}
```
nim 1.6.6
https://play.nim-lang.org/#ix=41uB

### PR DESCRIPTION
**Pull request by ringabout**
fixes https://github.com/nim-lang/Nim/issues/19967

- [x] add a testcase for emums

### CODE REVIEW

File: compiler/ccgreset.nim [hunk 1]
```diff
@@ -87,6 +87,12 @@ proc specializeResetT(p: BProc, accessor: Rope, typ: PType) =
     lineCg(p, cpsStmts, "$1 = 0;$n", [accessor])
   of tyCstring, tyPointer, tyPtr, tyVar, tyLent:
     lineCg(p, cpsStmts, "$1 = NIM_NIL;$n", [accessor])
+  of tySet:
+    if mapSetType(p.config, typ) == ctArray:
+      lineCg(p, cpsStmts, "#nimZeroMem($1, sizeof($2));$n",
+          [accessor, getTypeDesc(p.module, typ)])
+    else:
+      lineCg(p, cpsStmts, "$1 = 0;$n", [accessor])
```
Comment (arnetheduck) [inline compiler/ccgreset.nim:96]: the discard below is the problem really - ie it would be better if it listed the uninteresting types explicitly..

Comment (xflywind) [reply compiler/ccgreset.nim:95]: I just followed the pre-existing patterns though

```nim
  of tySet:
    if mapSetType(p.config, ty) == ctArray:
      linefmt(p, cpsStmts, "#nimCopyMem((void*)$1, (NIM_CONST void*)$2, $3);$n",
              [rdLoc(dest), rdLoc(src), getSize(p.config, dest.t)])
    else:
      linefmt(p, cpsStmts, "$1 = $2;$n", [rdLoc(dest), rdLoc(src)])
```

Comment (ringabout) [reply compiler/ccgreset.nim:96]: I just followed the pre-existing pattern though

```nim
  of tySet:
    if mapSetType(p.config, ty) == ctArray:
      linefmt(p, cpsStmts, "#nimCopyMem((void*)$1, (NIM_CONST void*)$2, $3);$n",
              [rdLoc(dest), rdLoc(src), getSize(p.config, dest.t)])
    else:
      linefmt(p, cpsStmts, "$1 = $2;$n", [rdLoc(dest), rdLoc(src)])
```

File: tests/stdlib/tsystem.nim [hunk 2]
```diff
@@ -74,3 +74,29 @@ template main =
...
+  type
+    Color = enum
+      Red, Blue, Yellow
+    X = object
+      a: string
+      b: set[Color]
+
+  var fuck = X(b: {Red, Blue})
+
+  doAssert fuck.b == {}
```
Comment (Araq) [inline tests/stdlib/tsystem.nim]: Why would it be empty? What am I missing here?

File: compiler/ccgreset.nim (hunk 1 above)
Comment (arnetheduck) [reply compiler/ccgreset.nim:96]: the pre-existing pattern caused the bug (it would have been obvious that set was missing if there was no catch-all at the end because the compiler would give an error) - if a new type is ever added, this code will need updating

File: tests/stdlib/tsystem.nim (hunk 2 above)
Comment (ringabout) [reply tests/stdlib/tsystem.nim]: Sorry, my mistake. I forgot to change the test after debugging C code.

File: compiler/ccgreset.nim (hunk 1 above)
Comment (ringabout) [reply compiler/ccgreset.nim:96]: Yeah, I prefer this better code.

File: tests/stdlib/tsystem.nim (hunk 2 above)
Comment (ringabout) [reply tests/stdlib/tsystem.nim]: And CI catched my mistake.

File: tests/stdlib/tsystem.nim [hunk 3]
```diff
@@ -74,3 +74,30 @@ template main =
...
+      Red, Blue, Yellow
+    X = object
+      a: string
+      b: set[Color]
+
+  var y = X(b: {Red, Blue})
+
+  reset(y)
+  doAssert y.b == {}
+
```
Comment (juancarlospaco) [inline tests/stdlib/tsystem.nim:103]: Would be better to iterate all primitives from system, call `reset`, and assert results.

A `reset`'d type should be equal to `default()` of that type for easy assert (?) AFAIK.

Comment (ringabout) [reply tests/stdlib/tsystem.nim:103]: I agree it can be a following-up pr.

File: compiler/ccgreset.nim (hunk 1 above)
Comment (arnetheduck) [reply compiler/ccgreset.nim:96]: not sure I follow, ie the suggestion is to change `else: discard` to `of A, B, ...: discard` such that it's obvious which types are skipped by the resetter

Comment (ringabout) [reply compiler/ccgreset.nim:96]: Sorry, I misunderstood what you said. I thought you mean I didn't explicitly list the return type kind of mapSetType.

> not sure I follow, ie the suggestion is to change else: discard to of A, B, ...: discard such that it's obvious which types are skipped by the resetter

Yeah I totally agree.

Comment (ringabout) [reply compiler/ccgreset.nim:96]: Thanks for your advice!

**Comment by ringabout** [comment]
followed the advice from https://github.com/nim-lang/Nim/pull/19968#discussion_r914471750

**Comment by ringabout** [comment]
It is ready for review.

**Comment by Varriount** [comment]
Is this a backport of a change that has already been merged into `devel`? If so, can you give me a link to the relevant PR? Then I can review and merge.

**Comment by ringabout** [comment]
No, it is a PR for the devel branch. Backport annotation is a   convention which means the PR should be backported to 1.2 and 1.6 branches.

File: tests/stdlib/tsystem.nim (hunk 3 above)
Comment (ringabout) [reply tests/stdlib/tsystem.nim:103]: done https://github.com/nim-lang/Nim/pull/20396
