### PR TITLE
fixes #22286; enforce Non-var T destructors by `nimPreviewNonVarDestructor`

### LINKED ISSUE #22286: system.=destroy does not accept non-var types
### Description

The following code cannot be compiled.
```nim
type
  A = object
  B = object
    a: A
  C = object
    b: B

proc `=destroy`(self: A) =
  echo "destroyed"

# Uncomment this out and it will work
# proc `=destroy`(self: B) =
#   `=destroy`(self.a)

proc `=destroy`(self: C) =
  `=destroy`(self.b)

var c = C()
```

### Nim Version

Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-07-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: f9280090f623d8fddbf753ec50e0ecd21f388d00
active boot switches: -d:release

### Current Output

```text
Error: type mismatch
Expression: `=destroy`(self.b)
  [1] self.b: B

Expected one of (first mismatch at [position]):
[1] proc `=destroy`(self: A)
[1] proc `=destroy`(self: C)
[1] proc `=destroy`(x: string)
[1] proc `=destroy`[T](x: ref T)
[1] proc `=destroy`[T](x: seq[T])
[1] proc `=destroy`[T](x: var T)
```

### Expected Output

```text
destroyed
```

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #22286
ref https://forum.nim-lang.org/t/10642

For backwards compatibilities, we might need to keep the changes under a preview compiler flag. Let's see how many packags it break.

**TODO** in the following PRs

- [ ] Turn the `var T` destructors warning into an error with `nimPreviewNonVarDestructor`

### CODE REVIEW

**Comment by ringabout** [comment]
Well, I will turn it into an experimental feature instead

**Comment by ringabout** [comment]
Ops, forgot to add test cases, will push them tomorrow

**Comment by ringabout** [comment]
The failure of tests/arc/thard_alignment.nim seems to be quite nasty... I'm debugging it on my local branch.

**Comment by ringabout** [comment]
It seems that my change may not be the culprit of the failure of `tests/arc/thard_alignment.nim`. 

This is a reduced case:
```nim
{.passC: "-march=native".}

proc isAlignedCheck(p: pointer, alignment: int) = 
  doAssert (cast[uint](p) and uint(alignment - 1)) == 0

proc isAlignedCheck[T](p: ref T, alignment: int) = 
  isAlignedCheck(cast[pointer](p), alignment)

type
  m256d {.importc: "__m256d", header: "immintrin.h".} = object

proc set1(x: float): m256d {.importc: "_mm256_set1_pd", header: "immintrin.h".}
func `+`(a,b: m256d): m256d {.importc: "_mm256_add_pd", header: "immintrin.h".}
proc toString(a: m256d): string = discard


var xx = new(m256d)
xx[] = set1(10)
isAlignedCheck(xx, alignOf(m256d))
echo toString(xx[])
```

When defining a non-var function for `m256d`, it segfaulted on Windows. Not sure whether `{.passC: "-march=native".}` is to blame or not.

So It could cause problems for the non-var destructor that is lifted for `m256d`.

**Comment by ringabout** [comment]
As https://discord.com/channels/371759389889003530/768367394547957761/1177513506610880542 said, the varness change of destructors might affect alignments with `-march=native`.

File: tests/converter/tconverter_unique_ptr.nim [hunk 1]
```diff
@@ -22,12 +22,12 @@ proc `$`(x: MyLen): string {.borrow.}
 proc `==`(x1, x2: MyLen): bool {.borrow.}
 
 
-proc `=destroy`*(m: var MySeq) {.inline.} =
+proc `=destroy`*(m: MySeq) {.inline.} =
   if m.data != nil:
     deallocShared(m.data)
-    m.data = nil
+    (addr m.data)[] = nil
```
Comment (Araq) [inline tests/converter/tconverter_unique_ptr.nim]:
```suggestion
```

File: tests/converter/tconverter_unique_ptr.nim [hunk 2]
```diff
@@ -77,13 +77,13 @@ converter literalToLen*(x: int{lit}): MyLen =
 # Unique pointer implementation
 #-------------------------------------------------------------
 
-proc `=destroy`*[T](p: var UniquePtr[T]) =
+proc `=destroy`*[T](p: UniquePtr[T]) =
   if p.val != nil:
     `=destroy`(p.val[])
     dealloc(p.val)
-    p.val = nil
+    (addr p.val)[] = nil
```
Comment (Araq) [inline tests/converter/tconverter_unique_ptr.nim]:
```suggestion
```

File: tests/converter/tconverter_unique_ptr.nim [hunk 3]
```diff
@@ -118,13 +118,13 @@ type
     ## as it returns only `lent T`
     val: ptr T
 
-proc `=destroy`*[T](p: var ConstPtr[T]) =
+proc `=destroy`*[T](p: ConstPtr[T]) =
   if p.val != nil:
     `=destroy`(p.val[])
     dealloc(p.val)
-    p.val = nil
+    (addr p.val)[] = nil
```
Comment (Araq) [inline tests/converter/tconverter_unique_ptr.nim]:
```suggestion
```

File: tests/destructor/const_smart_ptr.nim [hunk 4]
```diff
@@ -2,13 +2,13 @@ type
   ConstPtr*[T] = object
     val: ptr T
 
-proc `=destroy`*[T](p: var ConstPtr[T]) =
+proc `=destroy`*[T](p: ConstPtr[T]) =
   if p.val != nil:
     `=destroy`(p.val[])
     dealloc(p.val)
-    p.val = nil
+    (addr p.val)[] = nil
```
Comment (Araq) [inline tests/destructor/const_smart_ptr.nim]:
```suggestion
```

File: tests/destructor/const_smart_ptr.nim [hunk 5]
```diff
@@ -31,12 +31,12 @@ type
     len: int
     data: ptr UncheckedArray[float]
 
-proc `=destroy`*(m: var MySeqNonCopyable) {.inline.} =
+proc `=destroy`*(m: MySeqNonCopyable) {.inline.} =
   if m.data != nil:
     deallocShared(m.data)
-    m.data = nil
+    (addr m.data)[] = nil
```
Comment (Araq) [inline tests/destructor/const_smart_ptr.nim]:
```suggestion
```
