### PR TITLE
Fixed mutex usage in SharedList and SharedTable. Closes #6988

### LINKED ISSUE #6988: GC deadlock
```nim
type Foo = ref object
    b1: int64

type Uri* = object
    scheme*, username*, password*: string
    hostname*, port*, path*, query*, anchor*: string
    opaque*: bool

proc initUri*(): Uri = Uri()

GC_fullCollect()
discard Foo.new()
discard initUri()
GC_fullCollect() # < -------------- hangs here on pthread_mutex_lock
echo "done"
```

100% reproduce on Macos + threads + i386 + checks + release. Please use the exact following command to test:
```
nim c -r -d:release --checks:on --threads:on --cpu:i386 --passC:-arch --passC:i386 --passL:-arch --passL:i386 ~/test.nim
```

EDIT: sample simplified
EDIT: removed reference to "breaking" commit, since the last found sample is not affected by it

### PR DESCRIPTION
**Pull request by yglukhov**
Ok, so it's another bug because of mutexes are copied. Related: #5803, #3936.

Here's a man: https://linux.die.net/man/3/pthread_mutex_init
Note the following:
> Only mutex itself may be used for performing synchronization. The result of referring to copies of mutex in calls to pthread_mutex_lock(), pthread_mutex_trylock(), pthread_mutex_unlock(), and pthread_mutex_destroy() is undefined.

### CODE REVIEW

**Comment by yglukhov** [comment]
Maybe #5804 needs to be reverted after all...

**Comment by Araq** [comment]
Hmm, why didn't https://github.com/nim-lang/Nim/pull/5804/files prevent this?

**Comment by yglukhov** [comment]
@Araq, because that's only for ios. I thought MacOS was not affected by this problem, but apparently it is (

File: lib/pure/collections/sharedlist.nim [hunk 1]
```diff
@@ -73,10 +73,10 @@ proc add*[A](x: var SharedList[A]; y: A) =
     node.d[node.dataLen] = y
     inc(node.dataLen)
 
-proc initSharedList*[A](): SharedList[A] =
```
Comment (Araq) [inline lib/pure/collections/sharedlist.nim]: This needs a deprecation period.

File: lib/pure/collections/sharedtables.nim [hunk 2]
```diff
@@ -192,18 +192,18 @@ proc del*[A, B](t: var SharedTable[A, B], key: A) =
   withLock t:
     delImpl()
 
-proc initSharedTable*[A, B](initialSize=64): SharedTable[A, B] =
```
Comment (Araq) [inline lib/pure/collections/sharedtables.nim]: This needs a deprecation period.

File: lib/pure/collections/sharedlist.nim [hunk 3]
```diff
@@ -92,4 +92,10 @@ proc deinitSharedList*[A](t: var SharedList[A]) =
   clear(t)
   deinitLock t.lock
 
+proc initSharedList*[A](): SharedList[A] {.deprecated.} =
+  # This is not posix compliant, may introduce undefined behavior. Use `init` instead.
```
Comment (Araq) [inline lib/pure/collections/sharedlist.nim]: '##' instead of '#' for documentation comments.

File: lib/pure/collections/sharedtables.nim [hunk 4]
```diff
@@ -192,19 +192,28 @@ proc del*[A, B](t: var SharedTable[A, B], key: A) =
...
                                       sizeof(KeyValuePair[A, B]) * initialSize))
-  initLock result.lock
+  initLock t.lock
 
 proc deinitSharedTable*[A, B](t: var SharedTable[A, B]) =
   deallocShared(t.data)
   deinitLock t.lock
+
+proc initSharedTable*[A, B](initialSize=64): SharedTable[A, B] {.deprecated.} =
+  # This is not posix compliant, may introduce undefined behavior. Use `init` instead.
```
Comment (Araq) [inline lib/pure/collections/sharedtables.nim]: '##' instead of '#' for documentation comments.

File: lib/pure/collections/sharedlist.nim (hunk 3 above)
Comment (yglukhov) [reply lib/pure/collections/sharedlist.nim]: Are you sure you want to make deprecated stuff show up in the docs? Because I've intentionally used '#' instead of '##'.

Comment (Araq) [reply lib/pure/collections/sharedlist.nim]: Yes I am sure as long as ``{.deprecated: "Use 'init' instead".}`` does not work.
