### PR TITLE
Fixes #17849

### LINKED ISSUE #17849: `yield in expr not lowered` on `case await`
fails with both asyncdispatch / chronos

```nim
import asyncdispatch
proc f*() {.async.} =
  case await newFuture[bool]()
  of true: discard
  of false: discard

discard f()
```

```
Error: internal error: yield in expr not lowered
```

nim 1.2.6, 1.4.4

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

File: compiler/closureiters.nim [hunk 1]
```diff
@@ -606,6 +606,13 @@ proc lowerStmtListExprs(ctx: var Ctx, n: PNode, needsSplit: var bool): PNode =
             internalError(ctx.g.config, "lowerStmtListExpr(nkCaseStmt): " & $branch.kind)
         result.add(n)
         result.add(ctx.newEnvVarAccess(tmp))
+      else:
+        result = newNodeI(nkStmtList, n.info)
+        if n[0].kind == nkStmtListExpr:
```
Comment (arnetheduck) [inline compiler/closureiters.nim]: what if it's not a stmtlistexpr?

File: compiler/closureiters.nim [hunk 2]
```diff
@@ -606,6 +606,13 @@ proc lowerStmtListExprs(ctx: var Ctx, n: PNode, needsSplit: var bool): PNode =
...
+          let (st, ex) = exprToStmtList(n[0])
+          result.add(st)
+          n[0] = ex
+        result.add(n)
```
Comment (Araq) [inline compiler/closureiters.nim]:
```suggestion
      elif n[0].kind == nkStmtListExpr:
        result = newNodeI(nkStmtList, n.info)
        let (st, ex) = exprToStmtList(n[0])
        result.add(st)
        n[0] = ex
        result.add(n)
```

File: compiler/closureiters.nim (hunk 1 above)
Comment (Araq) [reply compiler/closureiters.nim]: Then it cannot contain a `yield`. I think. :-)

Comment (arnetheduck) [reply compiler/closureiters.nim]: shouldn't it.. error out then? just in case?

Comment (Araq) [reply compiler/closureiters.nim]: Well previously the case wasn't handled and it produced an internal error. If this assumption doesn't hold, it will produce the internal error again:

```nim

  if n.hasYieldsInExpressions():
    internalError(ctx.g.config, "yield in expr not lowered")

```

Comment (arnetheduck) [reply compiler/closureiters.nim]: oh. hm, that's a really really hard message to debug, it should at least include the offending node

Comment (Araq) [reply compiler/closureiters.nim]: We can improve that in a follow-up PR.
