### PR TITLE
fixes #8916 by fixing typeinfo and marshal.

### LINKED ISSUE #8916: `proc isNil*(x: Any): bool =` should be updated with non nil string, seq
```nim
proc isNil*(x: Any): bool =
  ## `isNil` for an any `x` that represents a sequence, string, cstring,
  ## proc or some pointer type.
  assert x.rawType.kind in {tyString, tyCString, tyRef, tyPtr, tyPointer,
                            tySequence, tyProc}
  result = isNil(cast[ppointer](x.value)[])
```

### PR DESCRIPTION
**Pull request by Vindaar**
Fixes https://github.com/nim-lang/Nim/issues/8916.

This PR is partially based on @timotheecour's https://github.com/nim-lang/Nim/pull/8942, but fixes the issue seen in his example.

In `marshal.nim` we must not check for `isNil` of `tySequence` anymore and then in addition make sure we return the length of a sequence in `typeinfo` correctly. If the latter can be done differently, let me know.

### CODE REVIEW

File: lib/core/typeinfo.nim [hunk 1]
```diff
@@ -242,8 +248,7 @@ proc base*(x: Any): Any =
 proc isNil*(x: Any): bool =
   ## `isNil` for an any `x` that represents a sequence, string, cstring,
```
Comment (timotheecour) [inline lib/core/typeinfo.nim]: remove from doc comment: sequence and string

Comment (Vindaar) [reply lib/core/typeinfo.nim]: Oops, thanks!

**Comment by Araq** [comment]
Unrelated test failure, merging.
