### PR TITLE
fixes #21863; Incorrect enum field access can cause internal error

### LINKED ISSUE #21863: Incorrect enum field access can cause internal error
### Description

Incorrectly accessing an overloaded enum field results in an internal error

```nim
type
  EnumA = enum A, B
  EnumB = enum A
  EnumC = enum C

discard EnumC.A
```

### Nim Version

Most recent devel

### Current Output

_No response_

### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #21863

### CODE REVIEW

File: compiler/semexprs.nim [hunk 1]
```diff
@@ -1047,7 +1047,7 @@ proc semIndirectOp(c: PContext, n: PNode, flags: TExprFlags; expectedType: PType
       if s != nil:
         setGenericParams(c, n[0])
         return semDirectOp(c, n, flags, expectedType)
-    elif isSymChoice(n[0]):
+    elif isSymChoice(n[0]) and nfDotField notin n.flags:
```
Comment (ringabout) [inline compiler/semexprs.nim:1050]: I think a overloaded generic dot field/call will not end up here, which has a special syntax, e.g. `a.len[:int]`. It should be fine.

**Comment by Araq** [comment]
Fine as a bugfix but eventually somebody needs to rewrite the semchecker. None of these hacks are according to the spec which is actually rather simple.
