### PR TITLE
fix #9394 by replacing `fmt` with `strutils.%`

### LINKED ISSUE #9394: ansi color code templates fail to bind symbols
The code

```nimrod
import terminal, colors
let code = ansiForegroundColorCode(colAliceBlue)
```

errors with

```
../home/fabian/bin/nim-repo/lib/pure/terminal.nim(639, 14) template/generic instantiation from here
../home/fabian/bin/nim-repo/lib/pure/strformat.nim(315, 39) Error: undeclared identifier: 'fgPrefix'
```

Looking at the source shows that it is probably a consequence of [using stformat in a template](https://github.com/nim-lang/Nim/issues/7632).

### PR DESCRIPTION
**Pull request by Vindaar**
Fixes #9394.

Until issue #7632 is fixed, use string append.

### CODE REVIEW

File: lib/pure/terminal.nim [hunk 1]
```diff
@@ -635,15 +635,17 @@ proc ansiForegroundColorCode*(color: Color): string =
 
 template ansiForegroundColorCode*(color: static[Color]): string =
   const rgb = extractRGB(color)
-  (static(fmt"{fgPrefix}{rgb.r};{rgb.g};{rgb.b}m"))
+  # no usage of `fmt`, see issue #7632
+  (static($fgPrefix & $(rgb.r) & ";" & $(rgb.g) & ";" & $(rgb.b) & "m"))
```
Comment (kaushalmodi) [inline lib/pure/terminal.nim]: Would `%` (imported from `strutils`) work here, for a slightly better looking code? (and the same for the other snippet)

```
(static("$1$2;$3;$4m" % [$fgPrefix, $(rgb.r), $(rgb.g), $(rgb.b)]))
```

Comment (Vindaar) [reply lib/pure/terminal.nim]: Yeah, good point. That looks a lot nicer!

**Comment by Araq** [comment]
I think we should fix ``fmt`` instead but it's hard, so ... merging for now.
