### PR TITLE
Fix #7936

### LINKED ISSUE #7936: SIGSEGV: Illegal storage access. (Attempt to read from nil?)
From chatting on Gitter, I been asked to post this as a bug from @dom96 
`toSeq(lookupTable.values)` seems to be causing a `SIGSEGV`, here is my full code.

```Nim
import
  tables, deques, sequtils

const
  lookupTable = {'(': ')', '{': '}', '[': ']'}.toTable

proc isPaired*(value: string): bool =
  var stack = initDeque[char]() 

  for item in value:
    echo "Looking at " & item
    if item in lookupTable:
      stack.addLast(item)
    if item in toSeq(lookupTable.values):
      if stack.len == 0:
        return false
      if lookupTable[stack.popLast()] != item:
        return false
        
  return stack.len == 0
```

```
➜  bracket-push nimble build --verbose
    Setting Nim stdlib prefix to
    Setting Nim stdlib path to /Users/ascotti/.choosenim/toolchains/nim-0.18.0/lib
  Verifying dependencies for bracket_push@0.1.0
   Building bracket_push/bracket_push using c backend
     Error: Build failed for package: bracket_push
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "/Users/ascotti/.nimble/bin/nim" c --noBabelPath  -o:"/Users/ascotti/Documents/code/nim/bracket-push/bracket_push" "/Users/ascotti/Documents/code/nim/bracket-push/src/bracket_push.nim"
        ... Output: Hint: used config file '/Users/ascotti/.choosenim/toolchains/nim-0.18.0/config/nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: bracket_push [Processing]
        ... Hint: tables [Processing]
        ... Hint: hashes [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: deques [Processing]
        ... Hint: sequtils [Processing]
        ... Hint: macros [Processing]
        ... SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

This is using nim version 0.18.0,

```
nim --version
Nim Compiler Version 0.18.0 [MacOSX: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 855956bf617f68ac0be3717329e9e1181e5dc0c6
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by LemonBoy**
The root cause was the unsemanticized typedesc node being passed around in the AST. That's not much of a problem since it's only used during the `doc` phase but, if the definition occurs in a template, we may also run it trough the `Transf` pass.

The fix is pretty simple and beside fixing the problem at hand it also changes the documentation output from:
```nim
result114130: type(().foo) = 1
```
into
```nim
result114130: int = 1
```

Side note: I see you can't really specify the typedesc for a nkVarTuple, is that a design decision or it's just that nobody implemented it yet?

Fixes #7936

### CODE REVIEW

File: compiler/semfold.nim [hunk 1]
```diff
@@ -490,6 +490,9 @@ proc foldFieldAccess(m: PSym, n: PNode; g: ModuleGraph): PNode =
   var x = getConstExpr(m, n.sons[0], g)
   if x == nil or x.kind notin {nkObjConstr, nkPar, nkTupleConstr}: return
 
+  # this may be a method call in disguise
```
Comment (Araq) [inline compiler/semfold.nim]: Why would the compiler attempt to const fold something that is not yet sem'checked completely?

Comment (LemonBoy) [reply compiler/semfold.nim]: Because when the type() is parsed`transformCall` is invoked on it and `getMagic` returns `mTypeOf`. If you take the code out of the template then the magic field is `mNone`.

**Comment by LemonBoy** [comment]
Ping @Araq, the new fix should be much better.
