### PR TITLE
fix #19600 No error checking on fclose

### LINKED ISSUE #19600: No error checking on fclose
It seems that there is no error checking when closing a file. In lib/system/io.nim:309 the result of c_fclose(f) is discarded.
However, the C stdlib uses buffering and effectively writes small files on fclose. For example it only discovers that there is no space left on device at that point. The error is typically propagated as the result of fclose.

### Example
Small file
```nim
writeFile("/dev/full", "hello\n")
```
Long file
```nim
var
  c = newString(4096)
for i in 0 .. 4095:
  c[i] = 'x'
writeFile("/dev/full", c)
```

### Current Output
nothing for small file
```
Error: unhandled exception: errno: 28 `No space left on device` [IOError]
```
for long file

### Expected Output
```
Error: unhandled exception: errno: 28 `No space left on device` [IOError]
```
for both.

### Possible Solution

Raise exception when result of fclose is not 0.
Note that ferror does not seem to be updated by fclose, which make checkErr useless in that context.

### Additional Information

Note: this was discovered after reading https://blog.sunfishcode.online/bugs-in-hello-world/

```
$ Nim Compiler Version 1.6.4 [Linux: amd64]
Compiled at 2022-02-09
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 7994556f3804c217035c44b453a3feec64405758
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Review by dom96 — APPROVED** [review]
Oooh, awesome. Thank you for fixing this :)

I'm happy to merge, but not sure what our breaking changes policy for introducing new exceptions is, so will wait for someone else to comment on that.

File: lib/std/syncio.nim [hunk 1]
```diff
@@ -689,7 +691,7 @@ when defined(posix) and not defined(nimscript):
 
 proc open*(f: var File, filename: string,
           mode: FileMode = fmRead,
-          bufSize: int = -1): bool {.tags: [], raises: [], benign.} =
+          bufSize: int = -1): bool {.tags: [], raises: [IOError], benign.} =
```
Comment (arnetheduck) [inline lib/std/syncio.nim:694]: adding new exceptions is a breaking change (because it changes the meaning of programs that catch specific exceptions) - this should be done via a new symbol

**Comment by arnetheduck** [comment]
@dom96: https://github.com/nim-lang/Nim/blob/devel/doc/contributing.md#run-time-breaking-changes - avoid raising new exceptions at all costs

**Comment by arnetheduck** [comment]
As an example, this change breaks https://github.com/status-im/nim-eth (see https://github.com/status-im/nim-eth/runs/8156141615?check_suite_focus=true)

**Comment by ringabout** [comment]
Fwiw, the tests didn't work when it was merged. It will be reverted anyway https://github.com/nim-lang/Nim/pull/20297
