### PR TITLE
Use raiseOSError with additionalInfo parameter from devel

### LINKED ISSUE #2573: Some `OSError` exceptions do not provide `errorCode`
There're mainly two ways of using `OSError` in the current code:

1. `raiseOSError(errcode)`
2. `newException(OSError, osErrorMsg(errcode))`

The exceptions raised by the *first way* have `OSError.errorCode` set to `errcode` and that's fine. But the *second way* never set `errorCode` properly, so the code catching an `OSError` can't tell what went wrong. It may be disastrous to us the string message.

### PR DESCRIPTION
**Pull request by singularperturbation**
Fixes #2573.  Uses the new `raiseOSError`  to preserve any additional error message (say, from `gai_strerror`) while making sure that we assign an integer error value (usually from `osLastError()`).

Based on earlier PR made by @HaCk3Dq.

### CODE REVIEW

**Comment by Araq** [comment]
@dom96 ping.

**Comment by Araq** [comment]
@dom96 ping!

**Comment by dom96** [comment]
ooh yes. They finally fixed the syntax highlighting. Now I can review it without my eyes bleeding.

File: lib/pure/os.nim [hunk 1]
```diff
@@ -1019,10 +1019,10 @@ proc moveFile*(source, dest: string) {.rtl, extern: "nos$1",
       let d = newWideCString(dest)
       if moveFileW(s, d, 0'i32) == 0'i32: raiseOSError(osLastError())
     else:
-      if moveFileA(source, dest, 0'i32) == 0'i32: raiseOSError(osLastError())
+      if moveFileA(source, dest, 0'i32) == 0'i32: raiseOSError(osLastError(),$strerror(errno))
```
Comment (dom96) [inline lib/pure/os.nim]: I don't think you can do this on Windows.

**Comment by dom96** [comment]
Fixed it myself. The rest of it was good, thanks!
