### PR TITLE
fix #17118

### LINKED ISSUE #17118: `math.gamma` and `math.lgamma` always return 0.0 in VM
### Example
```nim
import std/math

static:
  echo gamma(5.0)
  echo lgamma(5.0)
```

### Current Output
```
0.0
0.0
```

### Expected Output
```
24.0
3.178053830347946
```

### Additional Information
This doesn't compile on current stable (1.4.2), giving
```
Error: cannot 'importc' variable at compile time
```

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-02-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: da52e81327594ac65c80ddc8d2c7cb152f4b1b24
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #17118

but the root cause of that remains.

EDIT(timotheecour):
* I've changed the msg to `fix #17118` so that it'll auto-close #17118 when merged
* I've filed https://github.com/nim-lang/Nim/issues/17121 which tracks the root casue

### CODE REVIEW

File: compiler/vmops.nim [hunk 1]
```diff
@@ -159,13 +160,17 @@ proc registerAdditionalOps*(c: PCtx) =
...
   wrap1f_math(sqrt)
+  wrap1f_math(cbrt)
   wrap1f_math(ln)
   wrap1f_math(log10)
   wrap1f_math(log2)
   wrap1f_math(exp)
   wrap1f_math(arccos)
   wrap1f_math(arcsin)
   wrap1f_math(arctan)
+  wrap1f_math(arcsinh)
```
Comment (timotheecour) [inline compiler/vmops.nim:171]: in future work, we should be able to write:
`wrap(arcsinh)` and it'd automatically do the conversion based on proc declaration

**Review by timotheecour — APPROVED** [review]
