### PR TITLE
fix `is` with generic types; fix `genericHead(Foo[T])`

### LINKED ISSUE #9855: regression: can't get head `Foo` of `Foo[T]`
/cc @Araq 

while reviving https://github.com/nim-lang/Nim/pull/8554 I noticed my unittests are now failing, there's a regression since 0.19.0

```
Nim Compiler Version 0.19.0
nim c -r test.nim # works
```

```
Nim Compiler Version 0.19.9 [MacOSX: amd64]
Compiled at 2018-12-03
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: f86b827d9e10f0178f1bb89d1c7df8c6b7b7eba0
active boot switches: -d:release

nim c -r test.nim # fails
Error: unhandled exception: /Users/timothee/git_clone/nim/Nim/tests/stdlib/tsugar2.nim(36, 12) `extractGeneric(Foo2, -1) is Foo`  [AssertionError]
=> fails here: `doAssert extractGeneric(Foo2, -1) is Foo`
```

```nim
import macros

macro extractGeneric*(T: typedesc, index:static[int]): untyped =
  ## extract generic type numbered ``index`` used to construct ``T``. Note:
  ## ``-1`` returns ``Foo`` in ``Foo[T]``
  runnableExamples:
    type Foo[T1, T2]=object
    doAssert extractGeneric(Foo[float, string], 0) is float
    doAssert extractGeneric(Foo[float, string], 1) is string
    doAssert extractGeneric(Foo[float, string], -1) is Foo

  var impl = getTypeImpl(T)
  expectKind(impl, nnkBracketExpr)
  impl = impl[1]
  while true:
    case impl.kind
      of nnkSym:
        impl = impl.getImpl
        continue
      of nnkTypeDef:
        impl = impl[2]
        continue
      of nnkBracketExpr:
        if index == -1:
          impl=impl[0] #return `Foo` in `Foo[T]`
        else:
          impl=impl[1+index]  #return `T` in `Foo[T]` (when index = 0)
        break
      else:
        error "internal error: impl.kind: " & $impl.kind
  impl

block extractGeneric:
  type Foo[T1, T2]=object
  type Foo2=Foo[float, string]
  doAssert extractGeneric(Foo2, -1) is Foo
  doAssert extractGeneric(Foo2, 0) is float
  doAssert extractGeneric(Foo2, 1) is string
  doAssert extractGeneric(Foo[float, string], 1) is string
  # doAssert extractGeneric(Foo[float, string], -1) is Foo
  # workaround for seq[int].T not working,
  # see https://github.com/nim-lang/Nim/issues/8433
  doAssert extractGeneric(seq[int], 0) is int
  doAssert extractGeneric(seq[seq[string]], 0) is seq[string]
  # doAssert not compiles(extractGeneric(seq[int], 1))
  doAssert extractGeneric(seq[int], -1) is seq

  type Foo3[T] = T
  doAssert extractGeneric(Foo3[int], 0) is int
```

### LINKED ISSUE #13066: regression (0.19.6 => 0.20): `is` broken with generic types
### Example
```nim
  type Foo[T1,T2] = object
  type Foo2 = Foo
  doAssert Foo2 is Foo # fails since 0.20
  doAssert Foo is Foo2 # fails since 0.20
  doAssert Foo is Foo # fails since 0.20

# EDIT
  doAssert Foo[int,float] is Foo2[int,float] # fails but also failed in 0.19.6

```

### Current Output
```
`Foo2 is Foo`  [AssertionError]
```

### Expected Output
works

### Additional Information
* worked until 0.19.6
* broken since 0.20 including in recent devel ba4fbb63285ce198a9feb62e8058889462a96a87

* maybe root cause of https://github.com/nim-lang/Nim/issues/9855
* maybe root cause of `genericHead` broken as mentioned in https://github.com/nim-lang/Nim/pull/13064 and in https://github.com/nim-lang/Nim/pull/8554 /cc @zah

### PR DESCRIPTION
**Pull request by timotheecour**
* fix #9855
* fix #13066 (both the regression since 0.20 as well as the long standing issue mentioned there)
* fix typetraits.genericHead (was broken since forever)
* `type Foo[T] = object; type Foo2 = Foo` (or `type Foo2 = genericHead(Foo[int])`) will now make Foo2 an alias of Foo instead of a distinct type (just like for non-generic types)

## note
support for `seq[T]` can be added in future PR's (cf #10143)

### CODE REVIEW

File: compiler/semtypes.nim [hunk 1]
```diff
@@ -1403,7 +1403,7 @@ proc semGeneric(c: PContext, n: PNode, s: PSym, prev: PType): PType =
   elif t.kind != tyGenericBody:
     # we likely got code of the form TypeA[TypeB] where TypeA is
     # not generic.
-    localError(c.config, n.info, errNoGenericParamsAllowedForX % s.name.s)
+    localError(c.config, n.info, errNoGenericParamsAllowedForX % $(s.name.s, t.kind))
```
Comment (Araq) [inline compiler/semtypes.nim]: Seriously? ``tyFoobar`` in error messages?

Comment (timotheecour) [reply compiler/semtypes.nim]: fixed via a reusable `toHumanStr`; note that `typeToString()` is not enough (doesn't help debugging what went wrong in many cases: the type name doesn't tell you the type kind).
now you'll get (in the other location under evalTypeTrait, not here) error messages like:
```nim
Error: expected genericInst, got: sequence of type seq[int]
```

**Comment by timotheecour** [comment]
PTAL

File: compiler/semtypes.nim (hunk 1 above)
Comment (Araq) [reply compiler/semtypes.nim]: Still not good enough. "expected genericInst", who is supposed to understand that? And how exactly is ``type seq[int]`` not an instantiation?

Comment (timotheecour) [reply compiler/semtypes.nim]: * I've removed this change here to unblock this PR although IMO more relevant debug info is better and helps anyone with some familiarity with compiler internals (s.name.s doesn't show the typeKind and isn't as useful). And I've changed the other message to show error messages like this:
```nim
 Error: expected generic type, got: type Bar of kind object
```
which IMO is much more helpful than:
```nim
 Error: expected generic type, got: type Bar
```

> And how exactly is type seq[int] not an instantiation?

I don't know how to support `tySequence` (which is implemented very differently) so I'm leaving this part for future PR; users can at least use: `when MyType is seq: seq else: genericHead(MyType)`
in particular this does not work:
```nim
var resType = newType(tySequence, operand.owner)
result = toNode(resType, traitCall.info)
```
This PR is a strict improvement over status quo, where genericHead did not work at all, now it works for generic objects (but not yet `seq[T]`) (in addition to fixing the other 2 issues)

**Comment by krux02** [comment]
@timotheecour You say "`is` now works reliably in the title", then you say that it actually isn't relible because of ``seq[T]``. This really is very annoying clickbait. And this is also one of the reasons you got a ban in the past.

**Comment by timotheecour** [comment]
> @timotheecour You say "is now works reliably in the title", then you say that it actually isn't relible because of seq[T]. This really is very annoying clickbait. And this is also one of the reasons you got a ban in the past.

huh? the title I wrote was accurate to the best of my knowledge. Maybe instead of banning people and making negative character assumptions like you've done so often in the past (see https://github.com/nim-lang/Nim/pull/11722#issuecomment-514192697 + many other instances), you could simply ask for clarification next time ?

#13066 should indeed be fixed with this PR, making `is` reliably working as far as I know; If there are further issues with `is` that aren't fixed by this PR, please simply file a new issue

> then you say that it actually isn't relible because of seq[T]

I did not say that. I said:
> support for seq[T] can be added in future PR's

and that was in reference to `genericHead` (which has never worked before this PR AFAIK, and which now works for `Foo[T]` types). I could've worded this more precisely but hopefully it was clear given the PR content.

The new title you wrote is not accurate (`is` should be fixed with this PR; and `genericHead` isn't mentioned in title)

**Comment by timotheecour** [comment]
@araq is anything else needed to unblock this PR?

File: compiler/semtypes.nim [hunk 2]
```diff
@@ -1383,7 +1383,7 @@ proc semGeneric(c: PContext, n: PNode, s: PSym, prev: PType): PType =
     return newOrPrevType(tyError, prev, c)
 
   var t = s.typ
-  if t.kind == tyCompositeTypeClass and t.base.kind == tyGenericBody:
+  if t.kind in {tyCompositeTypeClass, tyAlias} and t.base.kind == tyGenericBody:
```
Comment (Araq) [inline compiler/semtypes.nim:1386]: Is this related to the bugfix? If so, how?

File: compiler/semtypes.nim [hunk 3]
```diff
@@ -1454,7 +1454,7 @@ proc semGeneric(c: PContext, n: PNode, s: PSym, prev: PType): PType =
     recomputeFieldPositions(tx, tx.n, position)
 
 proc maybeAliasType(c: PContext; typeExpr, prev: PType): PType =
-  if typeExpr.kind in {tyObject, tyEnum, tyDistinct, tyForward} and prev != nil:
+  if typeExpr.kind in {tyObject, tyEnum, tyDistinct, tyForward, tyGenericBody} and prev != nil:
```
Comment (Araq) [inline compiler/semtypes.nim:1457]: Same question.

File: compiler/semtypes.nim [hunk 4]
```diff
@@ -1781,8 +1781,7 @@ proc semTypeNode(c: PContext, n: PNode, prev: PType): PType =
       else:
         assignType(prev, s.typ)
         # bugfix: keep the fresh id for aliases to integral types:
-        if s.typ.kind notin {tyBool, tyChar, tyInt..tyInt64, tyFloat..tyFloat128,
-                             tyUInt..tyUInt64}:
+        if s.typ.kind notin NumberLikeTypes:
```
Comment (Araq) [inline compiler/semtypes.nim]: Doesn't improve readability.

File: compiler/semexprs.nim [hunk 5]
```diff
@@ -396,12 +396,21 @@ proc isOpImpl(c: PContext, n: PNode, flags: TExprFlags): PNode =
     else:
       res = false
   else:
-    maybeLiftType(t2, c, n.info)
+    if t1.skipTypes({tyAlias}).kind != tyGenericBody:
```
Comment (Araq) [inline compiler/semexprs.nim]: Incomprehensible. Why only skip ``tyAlias``? Why only for not tyGenericBody?

I know these are not your faults, but the compiler is full of junk like that. What is the spec that we're following here?

**Comment by Araq** [comment]
1. It helps not to conflate bugfixes with refactorings.
2. This is adding more and more special cases and at the same time, I have no clue what other ``ty*`` enum values should have been special cased but are not.

File: compiler/semtypes.nim (hunk 2 above)
Comment (timotheecour) [reply compiler/semtypes.nim:1386]: yes it is. without this, `nim c -r tests/metatype/ttypetraits.nim` fails:

ttypetraits.nim(36, 15) Error: no generic parameters allowed for C2b
    doAssert C2b[MyInt, C4[cstring]].name2 == "C[int, C4[cstring]]"


with:
```
type
    C[T0, T1] = object
type C2b=C
```

File: compiler/semtypes.nim (hunk 3 above)
Comment (timotheecour) [reply compiler/semtypes.nim:1457]: also related to the bugfixes: without this:

```
ttypetraits.nim(133, 28) Error: type mismatch: got <FooInst, Foo2Inst>
but expected one of:
proc `==`[T: tuple |
    object](x, y: T): bool
  first type mismatch at position: 2
  required type for y: T: tuple or object
  but expression 'default(Foo2Inst)' is of type: Foo2Inst
```

File: compiler/semtypes.nim (hunk 4 above)
Comment (timotheecour) [reply compiler/semtypes.nim]: fixed: removed it ; although i preferred to avoid code duplication here

File: compiler/semexprs.nim (hunk 5 above)
Comment (timotheecour) [reply compiler/semexprs.nim]: this was the simplest patch I found that fixed #13066; `tyGenericBody`, `tyAlias` occur from aliasing a generic head; if I remove this line change, it fails here:
```nim
Error: unhandled exception: ttypetraits.nim(131, 12) `Foo2 is Foo`  [AssertionError]
```

but ok I've now changed `{tyAlias}` to: `{tyGenericInst, tyAlias, tySink, tyDistinct}`

**Comment by timotheecour** [comment]
PTAL all comments addressed

> It helps not to conflate bugfixes with refactorings.

i agree; I'm usually only adding in a refactoring if the bugfix would otherwise cause a new DRY violation (eg  `getTypeDescNode`)

> This is adding more and more special cases and at the same time, I have no clue what other ty* enum values should have been special cased but are not.

that's the shortest patch i could find that fixes `is` #13066 and `genericHead(Foo[T])` ... I'm not aware of other issues with `is` but if new ones are discovered we'll have to fix them later. Moving some builtin types out of the compiler and into library code (eg ala https://github.com/nim-lang/Nim/pull/13324) would definitely simplify things

**Comment by narimiran** [comment]
> support for seq[T] can be added in future PR's (cf #10143)

Any chance you'll be willing to work on that? Because the documentation for `genericHead` currently says:
```
  ## For example:
  ## * `seq[int].genericHead` will be just `seq`
  ## * `seq[int].genericHead[float]` will be `seq[float]`
```

and neither of those two example work.

**Comment by timotheecour** [comment]
> Because the documentation for genericHead currently says:

that doc comment was pre-existing; in any case see https://github.com/nim-lang/Nim/pull/16776 which at least makes it reflect reality
