### PR TITLE
fixes #25419; lift magic types to typeclasses

### LINKED ISSUE #25419: `Error: fatal error: invalid kind for lastOrd(tyNone)` with `type M = set`
### Nim Version

```
Nim Compiler Version 2.2.6 [Linux: amd64]
Compiled at 2026-01-08
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: ab00c56904e3126ad826bb520d243513a139436a
active boot switches: -d:release
```

```
Nim Compiler Version 2.2.7 [Linux: amd64]
Compiled at 2026-01-08
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: 919d0d5ea819ee9f258741247de41c93656bd129
active boot switches: -d:release
```

```
Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2026-01-08
Copyright (c) 2006-2026 by Andreas Rumpf

git hash: b3273e732dd628a0881448bc82ebedf103776ece
active boot switches: -d:release
```

### Description

```nim
type M = set
```

It's not valid code, sure. But it's triggering an error in the compiler, not the compiler properly providing a diagnostic of which line of Nim code is incorrect.

### Current Output

```text
Error: fatal error: invalid kind for lastOrd(tyNone)
```

### Expected Output

```text
No fatal error within the Nim compiler
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
fixes #25419

### CODE REVIEW

**Comment by Araq** [comment]
What about tyOpenArray, tyVarargs, etc?

**Comment by ringabout** [comment]
```nim
 # we fill it out later. For magic generics like 'seq', it won't be filled
  # so we use tyNone instead of nil to not crash for strange conversions
  # like: mydata.seq
  if s.typ.kind in {tyOpenArray, tyVarargs} and s.typ.len == 1:
    # XXX investigate why `tySequence` cannot be added here for now.
    discard
  else:
    rawAddSon(s.typ, newTypeS(tyNone, c))
```

`tyOpenArray, tyVarargs` was special cased here

File: compiler/semstmts.nim [hunk 1]
```diff
@@ -1845,6 +1845,13 @@ proc typeSectionFinalPass(c: PContext, n: PNode) =
           let baseType = s.typ.safeSkipTypes(abstractPtrs)
           if baseType.kind in {tyObject, tyTuple} and not baseType.n.isNil:
             checkForMetaFields(c, baseType.n, hasError)
+
+        if s.typ.kind in {tySet, tyArray, tySequence} and s.typ.elementType.kind == tyNone:
```
Comment (ringabout) [inline compiler/semstmts.nim]:
```suggestion
        if s.typ.kind in {tySet, tyArray, tySequence, tyUncheckedArray} and s.typ.elementType.kind == tyNone:
```

**Comment by ringabout** [comment]
@copilot review my PR
