### PR TITLE
fix regression with uint constant losing abstract type

### LINKED ISSUE #24104: Regression from 2.0.8 to `version-2-0`/`version-2-2`/`devel`: `Error: type mismatch: got 'uint' for '0'u' but expected 'P = distinct uint'` with `distinct`-typed labels in `case`statement
### Description

```nim
type P = distinct uint  # uint, uint8, uint16, uint32, uint64 
let v = 0.P
case v
of 0.P: discard
else:   discard
```

### Nim Version

Builds:
```
Nim Compiler Version 2.0.8 [Linux: amd64]
Compiled at 2024-09-13
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release
```

Does not build:
```
Nim Compiler Version 2.0.9 [Linux: amd64]
Compiled at 2024-09-13
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8bc8347f022982d81ae311223cc59580718b3c48
active boot switches: -d:release
```

`devel`:
```
Nim Compiler Version 2.1.99 [Linux: amd64]
Compiled at 2024-09-13
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 61e04ba0ed4b8c6567f4cfd5c48c2c2439c62371
active boot switches: -d:release
```

### Current Output

```text
/tmp/h.nim(4, 5) Error: type mismatch: got 'uint' for '0'u' but expected 'P = distinct uint'
```

### Expected Output

_No response_

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by metagn**
fixes #24104, refs #23955

The line `result.typ = dstTyp` added in #23955 changes the type of `result`, which was the type of `n` due to the argument passed to `newIntNodeT`, to the abstract type skipped `dstTyp`. The line is removed to just keep the type as abstract.

### CODE REVIEW

**Comment by metagn** [comment]
@ringabout is there any reason this line would be necessary?

File: tests/int/t1.nim [hunk 1]
```diff
@@ -52,3 +52,10 @@ block: # bug #23954
   doAssert testRT_u8 == 7
   const testCT_u8 : uint8 = 0x107.uint8
   doAssert testCT_u8 == 7
+
+block: # issue #24014
```
Comment (tersec) [inline tests/int/t1.nim]: Confused, this looks like my repro from https://github.com/nim-lang/Nim/issues/24104 not https://github.com/nim-lang/Nim/pull/24014

Comment (metagn) [reply tests/int/t1.nim]: Thanks for noticing lol I manually type issue numbers for some reason, thankfully it's a PR number

File: compiler/semfold.nim [hunk 2]
```diff
@@ -423,7 +423,6 @@ proc foldConv(n, a: PNode; idgen: IdGenerator; g: ModuleGraph; check = false): P
       if dstTyp.kind in {tyUInt..tyUInt64}:
         result = newIntNodeT(maskBytes(val, int getSize(g.config, dstTyp)), n, idgen, g)
         result.transitionIntKind(nkUIntLit)
```
Comment (ringabout) [inline compiler/semfold.nim:425]:
```suggestion
        result.transitionIntKind(nkUIntLit)
        result.typ = n.typ
```

Comment (ringabout) [reply compiler/semfold.nim:425]: nvm
