### PR TITLE
fix #18702(fix `parseutils.parseFloat`)

### LINKED ISSUE #18702: parseutils.parseFloat for e.g. 9.123456789012345+ returns a result that is 1e15 too big
parseutils.parseFloat returns a result that is a multiple of the expected result when the input ends on "-" or "+" (maybe others?) for numbers with many digits after the decimal comma

### Example
```nim
import parseutils
var f:float
for x in ["9.123456789012345+","11.123456789012345+","9.123456789012345-","8.123456789012345+","9.12345678901234-","9.123456789012345"]:
    echo x,"\t--> ",parseFloat(x, f, 0), "\t--> ", f
```

In the output below we can see that the first three results give something that is 10^15 too big.
The last three lines give expected output, while their input is only changed minimally:
The 4th line is the same as the first line, but with the initial 9 replaced by a 8. 
The 5th line has the last digit 5 dropped.
The 6th line has no trailing "+". 

### Current Output
```
9.123456789012345+	--> 17	--> 9123456789012344.0
11.123456789012345+	--> 18	--> 11123456789012344.0
9.123456789012345-	--> 17	--> 9123456789012344.0
8.123456789012345+	--> 17	--> 8.123456789012344
9.12345678901234-	--> 16	--> 9.12345678901234
9.123456789012345	--> 17	--> 9.123456789012344
```

### Expected Output
```
9.123456789012345+	--> 17	--> 9.12345678901234
11.123456789012345+	--> 18	--> 11.123456789012344
9.123456789012345-	--> 17	--> 9.12345678901234
8.123456789012345+	--> 17	--> 8.123456789012344
9.12345678901234-	--> 16	--> 9.12345678901234
9.123456789012345	--> 17	--> 9.123456789012344
```

```
# nim -v
Nim Compiler Version 1.5.1 [MacOSX: amd64]
Compiled at 2021-07-06
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 36654fd577f46c49191c5e6f7e499ea31193018c
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #18702

backport?

### CODE REVIEW

File: lib/system/strmantle.nim [hunk 1]
```diff
@@ -229,13 +234,21 @@ proc nimParseBiggestFloat(s: string, number: var BiggestFloat,
   inc(ti, 4)
 
   # insert adjusted exponent
+  echo absExponent
```
Comment (xflywind) [inline lib/system/strmantle.nim:237]:
```suggestion
```

File: lib/system/strmantle.nim [hunk 2]
```diff
@@ -229,13 +234,21 @@ proc nimParseBiggestFloat(s: string, number: var BiggestFloat,
...
   absExponent = absExponent div 10
   t[ti-2] = ('0'.ord + absExponent mod 10).char
   absExponent = absExponent div 10
   t[ti-3] = ('0'.ord + absExponent mod 10).char
+
+  var x: string
+  for i in 0 .. 30:
+    # echo t[i]
+    x.add t[i]
+  echo x
```
Comment (xflywind) [inline lib/system/strmantle.nim:248]:
```suggestion
```

File: lib/system/strmantle.nim [hunk 3]
```diff
@@ -229,13 +234,21 @@ proc nimParseBiggestFloat(s: string, number: var BiggestFloat,
...
   number = c_strtod(addr t, nil)
 
+
```
Comment (xflywind) [inline lib/system/strmantle.nim:251]:
```suggestion
```
