### PR TITLE
Fixes #25340

### LINKED ISSUE #25340: Computed types violate isa transitivity
### Nim Version

Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2025-12-06
Copyright (c) 2006-2025 by Andreas Rumpf

git hash: c3a20fa890615fab288e347791ac93a311e18851
active boot switches: -d:release

### Description

Playing with computed types I wanted to express smth like the following (pseudocode):
```nim
type Foo[T] = object of Foo[getParentType(T)]
```
However the resulting types seem to have broken isa relation. The following code shows a runtime problem, where A is B, B is C, but A is not C, which violates transitivity common sense.

```nim
import macros

type
  JSObj {.inheritable.} = object
  JSExternObjBase {.inheritable.} = object
  Document = object

macro parent(t: typedesc): untyped =
  let n = t.getType()[1]
  result = case $n
           of "JSObj": ident "JSExternObjBase"
           of "Document": ident "JSExternObjDocument"
           else: assert(false); nil
  echo "parent(", n, ") = ", repr result

type
  JSExternObj[T] = parent(T)
  JSExternObjDocument = object of JSExternObj[JSObj]

assert JSExternObj[Document] is JSExternObjDocument
assert JSExternObjDocument is JSExternObj[JSObj]
assert JSExternObj[Document] is JSExternObj[JSObj] # FAILS HERE
```

### Current Output

```text
Error: unhandled exception: .../test.nim(22, 1) `JSExternObj[Document] is JSExternObj[JSObj]`  [AssertionDefect]
```

### Expected Output

```text
No errors
```

### Known Workarounds

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by yglukhov**
~The fix is mostly AI generated (sans tests)~, please review carefully.

### CODE REVIEW

File: compiler/semtypinst.nim [hunk 1]
```diff
@@ -499,6 +499,22 @@ proc handleGenericInvocation(cl: var TReplTypeVars, t: PType): PType =
...
+        newbody.sym.locImpl.snippet = body.sym.loc.snippet  # copy the C name
+    elif newbody.sym.isNil and newbody.kind == tyObject:
+      # Computed type alias returned an anonymous object type - create a symbol for it
+      let s = newSym(skType, body.sym.name, cl.c.idgen, body.sym.owner, cl.info)
+      s.flagsImpl = s.flagsImpl + flagsToCopy
+      if sfImportc in flagsToCopy:
+        s.locImpl.snippet = body.sym.loc.snippet
+      s.typ = newbody
+      newbody.sym = s
+
```
Comment (Araq) [inline compiler/semtypinst.nim]: Avoid the direct writes to the `..Impl` fields, instead use the setters. The Impl fields are new and required for IC.

Comment (yglukhov) [reply compiler/semtypinst.nim]: Done

File: compiler/sigmatch.nim [hunk 2]
```diff
@@ -1702,6 +1702,15 @@ proc typeRel(c: var TCandidate, f, aOrig: PType,
               if hasCovariance:
                 continue
 
+            # Fallback for computed generic type aliases (bug #25340):
+            # Check if the aliased types (last elements) have inheritance relationship
+            let aLast = roota.last
+            let fLast = rootf.last
+            if aLast.kind == tyObject and fLast.kind == tyObject and trIsOutParam notin flags:
```
Comment (Araq) [inline compiler/sigmatch.nim]: There is no subtype relation between `G[T]` and `G[S]` just because there is one between `T` and `S`. This is not sound!

Comment (yglukhov) [reply compiler/sigmatch.nim]: As I understand it aLast and fLast are not T and S, but the implementations of `G[T]` and `G[S]`, so the behavior seems to be correct? Also I tried to come up with an example that demonstrates the unsound behavior, but could not. Again, I'm not 100% sure, but I don't see the problem here.

**Comment by yglukhov** [comment]
Fixed isa relation for refs and ptrs too.

**Comment by yglukhov** [comment]
I've redone the fix. Previously `tyGenericInsts` we checked for covariance if bases are equal, and for object-inheritance otherwise, but we need to check for inheritance in both cases. So now we check it if covariance fails.
